import type { AiCommandHandler } from "../../src/modules/ai/assistantApplication.js";
import type { AiExecutionContext, AiPreparedCommand } from "../../src/modules/ai/contracts.js";
import { V2ApplicationError } from "../../src/errors/applicationError.js";
import { money } from "../../src/modules/shared/commercialValues.js";
import type { BillingPaymentsApplicationService } from "../../src/modules/billing/paymentApplication.js";
import type { FinancialReadApplicationService } from "../../src/modules/billing/financialReadApplication.js";

const text=(value:unknown,max:number)=>typeof value==="string"&&value.trim().length>0&&value.trim().length<=max?value.trim():undefined;
const cents=(value:unknown)=>Number.isSafeInteger(value)&&(value as number)>0?(value as number):undefined;
const occurredAt=(value:unknown)=>{const candidate=text(value,40);if(!candidate||Number.isNaN(Date.parse(candidate)))throw new V2ApplicationError("VALIDATION_ERROR","A valid occurred-at timestamp is required.");return new Date(candidate).toISOString();};
const prepareContext=(context:AiExecutionContext,name:string)=>({principal:context.user,organizationId:context.organizationId,operationId:`ai:prepare:${name}:${context.requestId}`});
const executeContext=(context:Parameters<AiCommandHandler["execute"]>[0],name:string)=>({principal:context.delegatedPrincipal,organizationId:context.organizationId,operationId:`ai:${name}:${context.businessRequestId}`,businessRequest:{id:context.businessRequestId,payloadFingerprint:`ai:${name}:canonical-request`}});
const plan=(name:string,capability:AiCommandHandler["capability"],input:unknown,proposal:string,refs:AiPreparedCommand["expectedEntityReferences"]):AiPreparedCommand=>({commandName:name,capability,normalizedInput:input,proposal,expectedEntityReferences:refs,expiresAt:new Date(Date.now()+5*60_000)});

type ManualPayment=Readonly<{invoiceId:string;amountCents:number;currency:string;method:"cash"|"check"|"external"|"other";occurredAt:string}>;
const payment=(raw:unknown):ManualPayment=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const invoiceId=text(value.invoiceId,128),amountCents=cents(value.amountCents),currency=text(value.currency,8)?.toUpperCase(),method=value.method==="cash"||value.method==="check"||value.method==="external"||value.method==="other"?value.method:undefined;if(!invoiceId||amountCents===undefined||!currency||!method)throw new V2ApplicationError("VALIDATION_ERROR","Exact Invoice, positive cents, currency, and manual method are required.");return {invoiceId,amountCents,currency,method,occurredAt:occurredAt(value.occurredAt)};};
export const recordManualPaymentAiCommand=(payments:BillingPaymentsApplicationService,financialRead:FinancialReadApplicationService):AiCommandHandler=>({
  name:"finance.record_manual_payment",capability:"payment.record",
  prepare:async(context,raw)=>{const input=payment(raw);const current=await financialRead.readInvoice(prepareContext(context,"finance.record_manual_payment"),input.invoiceId as never);if(!current.ok)throw current.error;if(current.value.settlement.balance.currency!==input.currency||input.amountCents>current.value.settlement.balance.cents)throw new V2ApplicationError("CONFLICT","The proposed payment is not within the current collectible Invoice balance.");return plan("finance.record_manual_payment","payment.record",input,`Record manual payment\n\nInvoice: ${input.invoiceId}\nCurrent balance: ${input.currency} ${current.value.settlement.balance.cents}\nAmount: ${input.currency} ${input.amountCents}\nMethod: ${input.method}\nOccurred: ${input.occurredAt}\n\nNo payment has been recorded yet.`,[{type:"invoice",id:input.invoiceId}]);},
  execute:async(context,raw)=>{const input=payment(raw);const saved=await payments.recordManualPayment(executeContext(context,"finance.record_manual_payment"),{organizationId:context.organizationId as never,invoiceId:input.invoiceId as never,amount:money(input.currency as never,input.amountCents),method:input.method,occurredAt:input.occurredAt,businessRequestId:context.businessRequestId as never});if(!saved.ok)throw saved.error;return saved.value;},
});

type ManualRefund=Readonly<{invoiceId:string;paymentId:string;amountCents:number;currency:string;occurredAt:string}>;
const refund=(raw:unknown):ManualRefund=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const invoiceId=text(value.invoiceId,128),paymentId=text(value.paymentId,128),amountCents=cents(value.amountCents),currency=text(value.currency,8)?.toUpperCase();if(!invoiceId||!paymentId||amountCents===undefined||!currency)throw new V2ApplicationError("VALIDATION_ERROR","Exact Invoice, Payment, positive cents, and currency are required.");return {invoiceId,paymentId,amountCents,currency,occurredAt:occurredAt(value.occurredAt)};};
export const recordManualRefundAiCommand=(payments:BillingPaymentsApplicationService,financialRead:FinancialReadApplicationService):AiCommandHandler=>({
  name:"finance.record_manual_refund",capability:"refund.issue",
  prepare:async(context,raw)=>{const input=refund(raw);const current=await financialRead.readInvoice(prepareContext(context,"finance.record_manual_refund"),input.invoiceId as never);if(!current.ok)throw current.error;if(current.value.invoice.currency!==input.currency||!current.value.history.some(item=>item.kind==="payment"&&item.paymentId===input.paymentId))throw new V2ApplicationError("CONFLICT","The exact Invoice payment is no longer available for this refund.");return plan("finance.record_manual_refund","refund.issue",input,`Record manual refund\n\nInvoice: ${input.invoiceId}\nPayment: ${input.paymentId}\nRefund amount: ${input.currency} ${input.amountCents}\nOccurred: ${input.occurredAt}\n\nNo refund has been recorded yet.`,[{type:"invoice",id:input.invoiceId},{type:"payment",id:input.paymentId}]);},
  execute:async(context,raw)=>{const input=refund(raw);const saved=await payments.recordRefund(executeContext(context,"finance.record_manual_refund"),{organizationId:context.organizationId as never,invoiceId:input.invoiceId as never,paymentId:input.paymentId as never,amount:money(input.currency as never,input.amountCents),occurredAt:input.occurredAt,businessRequestId:context.businessRequestId as never});if(!saved.ok)throw saved.error;return saved.value;},
});
