import type { AiCommandHandler } from "../../src/modules/ai/assistantApplication.js";
import type { AiExecutionContext, AiPreparedCommand } from "../../src/modules/ai/contracts.js";
import { V2ApplicationError } from "../../src/errors/applicationError.js";
import type { PrepressApplicationService } from "../../src/modules/prepress/prepressApplication.js";
import type { ProductionApplicationService } from "../../src/modules/production/productionApplication.js";
import type { FulfillmentApplicationService } from "../../src/modules/fulfillment/fulfillmentApplication.js";
import type { ProofingApplicationService } from "../../src/modules/proofing/proofingApplication.js";

const text=(value:unknown,maximum:number)=>typeof value==="string"&&value.trim().length>0&&value.trim().length<=maximum?value.trim():undefined;
const positive=(value:unknown)=>Number.isSafeInteger(value)&&(value as number)>0?(value as number):undefined;
const operation=(context:AiExecutionContext,name:string)=>({principal:context.user,organizationId:context.organizationId,operationId:`ai:prepare:${name}:${context.requestId}`});
const execution=(context:Parameters<AiCommandHandler["execute"]>[0],name:string)=>({principal:context.delegatedPrincipal,organizationId:context.organizationId,operationId:`ai:${name}:${context.businessRequestId}`,businessRequest:{id:context.businessRequestId,payloadFingerprint:`ai:${name}:canonical-request`}});
const prepared=(commandName:string,capability:AiCommandHandler["capability"],normalizedInput:unknown,proposal:string,references:AiPreparedCommand["expectedEntityReferences"]):AiPreparedCommand=>({commandName,capability,normalizedInput,proposal,expectedEntityReferences:references,expiresAt:new Date(Date.now()+5*60_000)});

type PrepressSend=Readonly<{prepressUnitId:string}>;
const prepressSend=(raw:unknown):PrepressSend=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const prepressUnitId=text(value.prepressUnitId,128);if(!prepressUnitId)throw new V2ApplicationError("VALIDATION_ERROR","An exact Prepress unit is required.");return {prepressUnitId};};
export const prepressSendToProductionAiCommand=(service:PrepressApplicationService):AiCommandHandler=>({
  name:"prepress.send_to_production",capability:"prepress.complete",requiredCapabilities:["prepress.complete","route.advance","production.work"],
  prepare:async(context,raw)=>{const input=prepressSend(raw);const current=await service.getUnit(operation(context,"prepress.send_to_production"),input.prepressUnitId as never);if(!current.ok)throw current.error;return prepared("prepress.send_to_production","prepress.complete",input,`Send Prepress work to Production\n\nPrepress unit: ${input.prepressUnitId}\nCurrent completion: ${current.value.completedAt?"complete":"not complete"}\n\nThe canonical frozen route and destination will be revalidated. No changes have been made yet.`,[{type:"prepress_unit",id:input.prepressUnitId}]);},
  execute:async(context,raw)=>{const input=prepressSend(raw);const saved=await service.sendToProduction(execution(context,"prepress.send_to_production"),{...input,businessRequestId:context.businessRequestId} as never);if(!saved.ok)throw saved.error;return saved.value;},
});

type ProductionStart=Readonly<{productionWorkId:string;stationKey:"flatbed"|"roll";kind:"initial"|"reprint"|"correction"}>;
const productionStart=(raw:unknown):ProductionStart=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const productionWorkId=text(value.productionWorkId,128),stationKey=value.stationKey==="flatbed"||value.stationKey==="roll"?value.stationKey:undefined,kind=value.kind==="initial"||value.kind==="reprint"||value.kind==="correction"?value.kind:undefined;if(!productionWorkId||!stationKey||!kind)throw new V2ApplicationError("VALIDATION_ERROR","Exact Production work, station, and attempt kind are required.");return {productionWorkId,stationKey,kind};};
export const productionStartAiCommand=(service:ProductionApplicationService):AiCommandHandler=>({
  name:"production.start",capability:"production.work",
  prepare:async(context,raw)=>{const input=productionStart(raw);const current=await service.getWork(operation(context,"production.start"),input.productionWorkId as never);if(!current.ok)throw current.error;return prepared("production.start","production.work",input,`Start Production\n\nWork: ${input.productionWorkId}\nStation: ${input.stationKey}\nRemaining quantity: ${current.value.remainingGoodQuantity}\n\nNo changes have been made yet.`,[{type:"production_work",id:input.productionWorkId}]);},
  execute:async(context,raw)=>{const input=productionStart(raw);const saved=await service.start(execution(context,"production.start"),{...input,businessRequestId:context.businessRequestId} as never);if(!saved.ok)throw saved.error;return saved.value;},
});

type ProductionOutput=Readonly<{productionWorkId:string;productionAttemptId:string;goodQuantityDelta:number;wasteQuantityDelta?:number}>;
const productionOutput=(raw:unknown):ProductionOutput=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const productionWorkId=text(value.productionWorkId,128),productionAttemptId=text(value.productionAttemptId,128),goodQuantityDelta=positive(value.goodQuantityDelta),waste=value.wasteQuantityDelta===undefined?undefined:positive(value.wasteQuantityDelta);if(!productionWorkId||!productionAttemptId||goodQuantityDelta===undefined||(value.wasteQuantityDelta!==undefined&&waste===undefined))throw new V2ApplicationError("VALIDATION_ERROR","Exact work, attempt, and positive output quantity are required.");return {productionWorkId,productionAttemptId,goodQuantityDelta,...(waste===undefined?{}:{wasteQuantityDelta:waste})};};
export const productionRecordOutputAiCommand=(service:ProductionApplicationService):AiCommandHandler=>({
  name:"production.record_output",capability:"production.work",
  prepare:async(context,raw)=>{const input=productionOutput(raw);const current=await service.getWork(operation(context,"production.record_output"),input.productionWorkId as never);if(!current.ok)throw current.error;if(current.value.activeAttempt?.productionAttemptId!==input.productionAttemptId)throw new V2ApplicationError("CONFLICT","The exact Production attempt is no longer active.");if(input.goodQuantityDelta>current.value.remainingGoodQuantity)throw new V2ApplicationError("CONFLICT","Proposed good output exceeds the current remaining quantity.");return prepared("production.record_output","production.work",input,`Record Production output\n\nWork: ${input.productionWorkId}\nAttempt: ${input.productionAttemptId}\nRemaining quantity: ${current.value.remainingGoodQuantity}\nGood quantity to record: ${input.goodQuantityDelta}\nResulting remaining: ${current.value.remainingGoodQuantity-input.goodQuantityDelta}\n\nNo changes have been made yet.`,[{type:"production_work",id:input.productionWorkId},{type:"production_attempt",id:input.productionAttemptId}]);},
  execute:async(context,raw)=>{const input=productionOutput(raw);const {productionWorkId,...command}=input;const saved=await service.recordOutput(execution(context,"production.record_output"),{...command,businessRequestId:context.businessRequestId} as never);if(!saved.ok)throw saved.error;return saved.value;},
});

type ProductionComplete=Readonly<{productionWorkId:string;productionAttemptId:string}>;
const productionComplete=(raw:unknown):ProductionComplete=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const productionWorkId=text(value.productionWorkId,128),productionAttemptId=text(value.productionAttemptId,128);if(!productionWorkId||!productionAttemptId)throw new V2ApplicationError("VALIDATION_ERROR","Exact Production work and attempt are required.");return {productionWorkId,productionAttemptId};};
export const productionCompleteAiCommand=(service:ProductionApplicationService):AiCommandHandler=>({
  name:"production.complete",capability:"production.complete",
  prepare:async(context,raw)=>{const input=productionComplete(raw);const current=await service.getWork(operation(context,"production.complete"),input.productionWorkId as never);if(!current.ok)throw current.error;if(current.value.activeAttempt?.productionAttemptId!==input.productionAttemptId)throw new V2ApplicationError("CONFLICT","The exact Production attempt is no longer active.");return prepared("production.complete","production.complete",input,`Complete Production attempt\n\nWork: ${input.productionWorkId}\nAttempt: ${input.productionAttemptId}\nRecorded good quantity: ${current.value.recordedGoodQuantity}\nRemaining required quantity: ${current.value.remainingGoodQuantity}\n\nNo changes have been made yet.`,[{type:"production_work",id:input.productionWorkId},{type:"production_attempt",id:input.productionAttemptId}]);},
  execute:async(context,raw)=>{const input=productionComplete(raw);const saved=await service.complete(execution(context,"production.complete"),{productionAttemptId:input.productionAttemptId,businessRequestId:context.businessRequestId} as never);if(!saved.ok)throw saved.error;return saved.value;},
});

type FulfillmentHandoff=Readonly<{orderId:string;allocations:readonly Readonly<{orderLineId:string;quantity:number}>[];customerId?:string;contactId?:string}>;
const fulfillment=(raw:unknown):FulfillmentHandoff=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const orderId=text(value.orderId,128),customerId=value.customerId===undefined?undefined:text(value.customerId,128),contactId=value.contactId===undefined?undefined:text(value.contactId,128);if(!orderId||!Array.isArray(value.allocations)||value.allocations.length<1||value.allocations.length>25)throw new V2ApplicationError("VALIDATION_ERROR","An Order and one to 25 explicit fulfillment allocations are required.");const allocations=value.allocations.map(item=>{const record=item&&typeof item==="object"&&!Array.isArray(item)?item as Record<string,unknown>:{};const orderLineId=text(record.orderLineId,128),quantity=positive(record.quantity);if(!orderLineId||quantity===undefined)throw new V2ApplicationError("VALIDATION_ERROR","Each fulfillment allocation needs an exact line and positive quantity.");return {orderLineId,quantity};});if(new Set(allocations.map(item=>item.orderLineId)).size!==allocations.length)throw new V2ApplicationError("VALIDATION_ERROR","A fulfillment line may appear only once.");return {orderId,allocations,...(customerId?{customerId}:{}),...(contactId?{contactId}:{})};};
const handoff=(name:"fulfillment.record_pickup"|"fulfillment.record_shipment",capability:"fulfillment.pickup"|"fulfillment.ship",service:FulfillmentApplicationService):AiCommandHandler=>({
  name,capability,
  prepare:async(context,raw)=>{const input=fulfillment(raw);const available=await service.getAvailability(operation(context,name),input.orderId as never);if(!available.ok)throw available.error;for(const allocation of input.allocations){const line=available.value.find(item=>item.orderLineId===allocation.orderLineId);if(!line||allocation.quantity>line.availableFulfillmentQuantity)throw new V2ApplicationError("CONFLICT","One or more fulfillment quantities are no longer available.");}return prepared(name,capability,input,`${name==="fulfillment.record_pickup"?"Record pickup":"Record shipment"}\n\nOrder: ${input.orderId}\nAllocations: ${input.allocations.map(item=>`${item.orderLineId}: ${item.quantity}`).join(", ")}\n\nCurrent availability will be revalidated. No changes have been made yet.`,[{type:"order",id:input.orderId},...input.allocations.map(item=>({type:"order_line",id:item.orderLineId}))]);},
  execute:async(context,raw)=>{const input=fulfillment(raw);const command={...input,businessRequestId:context.businessRequestId};const saved=name==="fulfillment.record_pickup"?await service.recordPickup(execution(context,name),command as never):await service.recordShipment(execution(context,name),command as never);if(!saved.ok)throw saved.error;return saved.value;},
});
export const fulfillmentPickupAiCommand=(service:FulfillmentApplicationService)=>handoff("fulfillment.record_pickup","fulfillment.pickup",service);
export const fulfillmentShipmentAiCommand=(service:FulfillmentApplicationService)=>handoff("fulfillment.record_shipment","fulfillment.ship",service);

type ProofIssue=Readonly<{proofWorkId:string;proofVersionId:string;recipientContactId:string}>;
const proofIssue=(raw:unknown):ProofIssue=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const proofWorkId=text(value.proofWorkId,128),proofVersionId=text(value.proofVersionId,128),recipientContactId=text(value.recipientContactId,128);if(!proofWorkId||!proofVersionId||!recipientContactId)throw new V2ApplicationError("VALIDATION_ERROR","Exact Proof work, version, and recipient contact are required.");return {proofWorkId,proofVersionId,recipientContactId};};
export const proofIssueAiCommand=(service:ProofingApplicationService):AiCommandHandler=>({
  name:"proof.issue",capability:"proof.issue",
  prepare:async(context,raw)=>{const input=proofIssue(raw);const work=await service.getWork(operation(context,"proof.issue"),input.proofWorkId as never);if(!work.ok)throw work.error;const version=work.value.versions.find(item=>item.version.proofVersionId===input.proofVersionId);if(!version||!work.value.recipients.some(item=>item.contactId===input.recipientContactId))throw new V2ApplicationError("CONFLICT","The exact current Proof version or recipient is no longer valid.");return prepared("proof.issue","proof.issue",input,`Send Proof\n\nProof work: ${input.proofWorkId}\nProof version: ${input.proofVersionId}\nArtwork artifacts: ${version.version.artwork.length}\nRecipient contact: ${input.recipientContactId}\n\nThe canonical delivery queue will be used. No changes have been made yet.`,[{type:"proof_work",id:input.proofWorkId},{type:"proof_version",id:input.proofVersionId},{type:"contact",id:input.recipientContactId}]);},
  execute:async(context,raw)=>{const input=proofIssue(raw);const saved=await service.issue(execution(context,"proof.issue"),{proofVersionId:input.proofVersionId,recipientContactId:input.recipientContactId,businessRequestId:context.businessRequestId} as never);if(!saved.ok)throw saved.error;return saved.value;},
});
type ProofRetry=Readonly<{proofWorkId:string;proofVersionId:string}>;
const proofRetry=(raw:unknown):ProofRetry=>{const value=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const proofWorkId=text(value.proofWorkId,128),proofVersionId=text(value.proofVersionId,128);if(!proofWorkId||!proofVersionId)throw new V2ApplicationError("VALIDATION_ERROR","Exact Proof work and version are required.");return {proofWorkId,proofVersionId};};
export const proofRetryDeliveryAiCommand=(service:ProofingApplicationService):AiCommandHandler=>({
  name:"proof.retry_delivery",capability:"proof.issue",
  prepare:async(context,raw)=>{const input=proofRetry(raw);const work=await service.getWork(operation(context,"proof.retry_delivery"),input.proofWorkId as never);if(!work.ok)throw work.error;const version=work.value.versions.find(item=>item.version.proofVersionId===input.proofVersionId);if(!version||!version.delivery||!["failed","ambiguous"].includes(version.delivery.state))throw new V2ApplicationError("CONFLICT","Only a failed or ambiguous canonical Proof delivery can be retried.");return prepared("proof.retry_delivery","proof.issue",input,`Retry Proof delivery\n\nProof work: ${input.proofWorkId}\nProof version: ${input.proofVersionId}\nCurrent delivery state: ${version.delivery.state}\n\nThe canonical delivery queue will be retried. No changes have been made yet.`,[{type:"proof_work",id:input.proofWorkId},{type:"proof_version",id:input.proofVersionId}]);},
  execute:async(context,raw)=>{const input=proofRetry(raw);const saved=await service.retryDelivery(execution(context,"proof.retry_delivery"),{proofVersionId:input.proofVersionId,businessRequestId:context.businessRequestId} as never);if(!saved.ok)throw saved.error;return saved.value;},
});
