import { randomUUID } from "node:crypto";
import type { Pool } from "pg";
import type { AiAssistantStore } from "../../src/modules/ai/assistantApplication.js";
import type { AiConversation, AiConversationMessage, AiPendingCommand } from "../../src/modules/ai/contracts.js";

const conversation = (row: any): AiConversation => ({ id: row.id, organizationId: row.organization_id, userId: row.user_id, ...(row.title ? { title: row.title } : {}), createdAt: row.created_at, updatedAt: row.updated_at });
const message = (row: any): AiConversationMessage => ({ id: row.id, conversationId: row.conversation_id, organizationId: row.organization_id, userId: row.user_id, role: row.role, content: row.content, ...(row.tool_name ? { toolName: row.tool_name } : {}), createdAt: row.created_at });
const pending = (row: any): AiPendingCommand => ({ id: row.id, organizationId: row.organization_id, userId: row.user_id, conversationId: row.conversation_id, commandName: row.command_name, capability: row.capability, normalizedInput: row.normalized_input, proposal: row.proposal, proposalFingerprint: row.proposal_fingerprint, state: row.state, expiresAt: row.expires_at, businessRequestId: row.business_request_id, createdAt: row.created_at, updatedAt: row.updated_at, ...(row.result ? { result: row.result } : {}), ...(row.failure_code ? { failureCode: row.failure_code } : {}) });

/** Durable state repository; it contains AI evidence only, never business SQL. */
export class PostgresAiAssistantStore implements AiAssistantStore {
  constructor(private readonly pool: Pool) {}
  async createConversation(input: Omit<AiConversation,"createdAt"|"updatedAt">) { const r=await this.pool.query("INSERT INTO v2_ai_conversations(id,organization_id,user_id,title) VALUES($1,$2,$3,$4) RETURNING *",[input.id,input.organizationId,input.userId,input.title??null]);return conversation(r.rows[0]); }
  async listConversations(organizationId:string,userId:string,limit:number) { const r=await this.pool.query("SELECT * FROM v2_ai_conversations WHERE organization_id=$1 AND user_id=$2 ORDER BY updated_at DESC LIMIT $3",[organizationId,userId,limit]);return r.rows.map(conversation); }
  async messages(organizationId:string,userId:string,conversationId:string,limit:number) { const r=await this.pool.query("SELECT m.* FROM v2_ai_conversation_messages m JOIN v2_ai_conversations c ON c.id=m.conversation_id AND c.organization_id=m.organization_id WHERE m.organization_id=$1 AND m.user_id=$2 AND m.conversation_id=$3 AND c.user_id=$2 ORDER BY m.created_at ASC LIMIT $4",[organizationId,userId,conversationId,limit]);return r.rows.map(message); }
  async appendMessage(input: Omit<AiConversationMessage,"id"|"createdAt">) { const r=await this.pool.query("INSERT INTO v2_ai_conversation_messages(id,conversation_id,organization_id,user_id,role,content,tool_name) SELECT $1,$2,$3,$4,$5,$6,$7 WHERE EXISTS(SELECT 1 FROM v2_ai_conversations WHERE id=$2 AND organization_id=$3 AND user_id=$4) RETURNING *",[randomUUID(),input.conversationId,input.organizationId,input.userId,input.role,input.content.slice(0,16000),input.toolName??null]);if(!r.rows[0])throw new Error("AI conversation owner mismatch");await this.pool.query("UPDATE v2_ai_conversations SET updated_at=now() WHERE id=$1",[input.conversationId]);return message(r.rows[0]); }
  async cancelOtherPending(org:string,user:string,conversation:string,reason:string) { await this.pool.query("UPDATE v2_ai_pending_commands SET state='cancelled',failure_code=$4,updated_at=now() WHERE organization_id=$1 AND user_id=$2 AND conversation_id=$3 AND state IN ('pending_confirmation','confirmed')",[org,user,conversation,reason]); }
  async createPending(input:AiPendingCommand) { const r=await this.pool.query("INSERT INTO v2_ai_pending_commands(id,conversation_id,organization_id,user_id,command_name,capability,normalized_input,proposal,proposal_fingerprint,business_request_id,state,expires_at) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12 WHERE EXISTS(SELECT 1 FROM v2_ai_conversations WHERE id=$2 AND organization_id=$3 AND user_id=$4) RETURNING *",[input.id,input.conversationId,input.organizationId,input.userId,input.commandName,input.capability,input.normalizedInput,input.proposal,input.proposalFingerprint,input.businessRequestId,input.state,input.expiresAt]);if(!r.rows[0])throw new Error("AI conversation owner mismatch");return pending(r.rows[0]); }
  async pending(org:string,user:string,conversationId:string) { const r=await this.pool.query("SELECT * FROM v2_ai_pending_commands WHERE organization_id=$1 AND user_id=$2 AND conversation_id=$3 AND state IN ('pending_confirmation','confirmed','executing') ORDER BY created_at DESC LIMIT 1",[org,user,conversationId]);return r.rows[0]?pending(r.rows[0]):null; }
  async claimForGo(input:Readonly<{organizationId:string;userId:string;conversationId:string;now:Date}>) { const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("UPDATE v2_ai_pending_commands SET state='expired',updated_at=now() WHERE organization_id=$1 AND user_id=$2 AND conversation_id=$3 AND state='pending_confirmation' AND expires_at<=$4",[input.organizationId,input.userId,input.conversationId,input.now]);const r=await client.query("UPDATE v2_ai_pending_commands SET state='executing',updated_at=now() WHERE id=(SELECT id FROM v2_ai_pending_commands WHERE organization_id=$1 AND user_id=$2 AND conversation_id=$3 AND state='pending_confirmation' AND expires_at>$4 ORDER BY created_at DESC LIMIT 1 FOR UPDATE) RETURNING *",[input.organizationId,input.userId,input.conversationId,input.now]);await client.query("COMMIT");return r.rows[0]?pending(r.rows[0]):null;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();} }
  async complete(input:Readonly<{id:string;organizationId:string;state:"succeeded"|"failed";result?:unknown;failureCode?:string}>) { await this.pool.query("UPDATE v2_ai_pending_commands SET state=$3,result=$4,failure_code=$5,updated_at=now() WHERE id=$1 AND organization_id=$2 AND state='executing'",[input.id,input.organizationId,input.state,input.result??null,input.failureCode??null]); }
  async cancel(input:Readonly<{organizationId:string;userId:string;conversationId:string;now:Date}>) { const r=await this.pool.query("UPDATE v2_ai_pending_commands SET state='cancelled',updated_at=now() WHERE id=(SELECT id FROM v2_ai_pending_commands WHERE organization_id=$1 AND user_id=$2 AND conversation_id=$3 AND state='pending_confirmation' ORDER BY created_at DESC LIMIT 1) RETURNING *",[input.organizationId,input.userId,input.conversationId]);return r.rows[0]?pending(r.rows[0]):null; }
  async audit(input:Readonly<{organizationId:string;userId:string;conversationId:string;pendingCommandId?:string;eventType:string;toolName?:string;capability?:string;result:"succeeded"|"failed"|"denied";detail:unknown}>) { await this.pool.query("INSERT INTO v2_ai_tool_audit(id,organization_id,user_id,conversation_id,pending_command_id,event_type,tool_name,capability,result,detail) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),input.organizationId,input.userId,input.conversationId,input.pendingCommandId??null,input.eventType,input.toolName??null,input.capability??null,input.result,input.detail]); }
}
