import { createHash, randomUUID } from "node:crypto";
import { requireOperationPrincipalScope, type OperationContext } from "../../application/operation.js";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import { principalSubject, staffActorId } from "../../authorization/principals.js";
import { failure, success, type ApplicationResult, V2ApplicationError } from "../../errors/applicationError.js";
import { brandedId, canonicalJson, type ArtworkAssignmentId, type OrderId, type OrganizationId, type ProductionAttemptId, type ProductionWorkId } from "../shared/commercialValues.js";
import { normalizeOperationalQueuePage, type OperationalQueuePage, type OperationalQueuePageRequest } from "../shared/operationalQueue.js";
import type { OrderAutomaticLifecycle } from "../sales/orderAutomaticLifecycle.js";
import type { CompleteProductionAttemptInput, HoldProductionWorkInput, NoteProductionWorkInput, OpenProductionWorkInput, ProductionAttempt, ProductionStationQueueItem, ProductionWork, ProductionWorkEvent, ProductionWorkProjection, RecordProductionOutputInput, RequestProductionReworkInput, ResumeProductionWorkInput, StartProductionAttemptInput } from "./contracts.js";

type Actor=Readonly<{principalKind:OperationContext["principal"]["kind"];principalSubject:string;staffActorUserId?:string}>;
type Reservation=Readonly<{kind:"new"|"resumed"|"replay";request:Readonly<{id:string;resultJson:unknown|null}>}>;
export type ProductionMutationResult=Readonly<{work:ProductionWork;attempt?:ProductionAttempt;event?:ProductionWorkEvent}>;
export interface ProductionTransaction {
 reserve(input:Readonly<{organizationId:string;operation:string;businessRequestId:string;payloadFingerprint:string}&Actor>):Promise<Reservation>;
 succeed(organizationId:string,requestId:string,result:ProductionMutationResult):Promise<void>;
 attribute(input:Readonly<{organizationId:string;requestId:string;operation:string;resourceType:"production_work"|"production_attempt";resourceId:string}&Actor>):Promise<void>;
 audit(input:Readonly<{organizationId:string;requestId:string;operation:string;eventType:"production_work_opened"|"production_attempt_started"|"production_output_recorded"|"production_attempt_completed"|"production_work_held"|"production_work_resumed"|"production_work_noted"|"production_work_rework_requested";resourceId:string;summary:string}&Actor>):Promise<void>;
 eligibleProductionAssignment(org:OrganizationId,assignment:ArtworkAssignmentId):Promise<boolean>;
 createOrGetWork(input:Readonly<{id:ProductionWorkId;organizationId:OrganizationId;artworkAssignmentId:ArtworkAssignmentId}&Actor>):Promise<ProductionWork>;
 findWork(org:OrganizationId,id:ProductionWorkId):Promise<ProductionWork|null>;
 lockWork(org:OrganizationId,id:ProductionWorkId):Promise<ProductionWork|null>;
 readWork(org:OrganizationId,id:ProductionWorkId):Promise<ProductionWorkProjection|null>;
 listStationQueue(org:OrganizationId,station:"flatbed"|"roll",request:OperationalQueuePageRequest):Promise<OperationalQueuePage<ProductionStationQueueItem>>;
 listOrderWorks(org:OrganizationId,orderId:OrderId):Promise<readonly ProductionWorkProjection[]>;
 lockAttempt(org:OrganizationId,id:ProductionAttemptId):Promise<ProductionAttempt|null>;
 startAttempt(input:Readonly<{id:ProductionAttemptId;organizationId:OrganizationId;productionWorkId:ProductionWorkId;stationKey:"flatbed"|"roll";kind:"initial"|"reprint"|"correction"}&Actor>):Promise<ProductionAttempt>;
 recordOutput(input:Readonly<{organizationId:OrganizationId;productionAttemptId:ProductionAttemptId;goodQuantityDelta:number;wasteQuantityDelta:number}&Actor>):Promise<ProductionAttempt>;
 completeAttempt(input:Readonly<{organizationId:OrganizationId;productionAttemptId:ProductionAttemptId}&Actor>):Promise<ProductionAttempt>;
 appendWorkEvent(input:Readonly<{id:string;organizationId:OrganizationId;productionWorkId:ProductionWorkId;kind:ProductionWorkEvent["kind"];category?:string;reason?:string;note?:string;productionAttemptId?:ProductionAttemptId;recordedGoodQuantity?:number;recordedWasteQuantity?:number}&Actor>):Promise<ProductionWorkEvent>;
}
export interface ProductionTransactionRunner { transaction<T>(action:(tx:ProductionTransaction)=>Promise<T>):Promise<T>; }
const actor=(c:OperationContext):Actor=>({principalKind:c.principal.kind,principalSubject:principalSubject(c.principal),...(staffActorId(c.principal)?{staffActorUserId:staffActorId(c.principal)}:{})});
const fingerprint=(x:unknown)=>`sha256:${createHash("sha256").update(canonicalJson(x)).digest("hex")}`;

/** Production records attempts and output; it never writes Routing or Fulfillment state. */
export class ProductionApplicationService {
 constructor(private readonly runner:ProductionTransactionRunner,private readonly authority=new AuthorityPolicy(),private readonly orderLifecycle?:OrderAutomaticLifecycle){}
 async getWork(c:OperationContext,id:ProductionWorkId):Promise<ApplicationResult<ProductionWorkProjection>>{try{requireOperationPrincipalScope(c);this.require(c,"production.view");const value=await this.runner.transaction(tx=>tx.readWork(brandedId<"OrganizationId">(c.organizationId),id));if(!value)throw new V2ApplicationError("NOT_FOUND","Production work was not found.");return success(value);}catch(e){return failure(this.error(e));}}
 async listStationQueue(c:OperationContext,station:"flatbed"|"roll",request:OperationalQueuePageRequest={}):Promise<ApplicationResult<OperationalQueuePage<ProductionStationQueueItem>>>{try{requireOperationPrincipalScope(c);this.require(c,"production.view");const page=normalizeOperationalQueuePage(request);return success(await this.runner.transaction(tx=>tx.listStationQueue(brandedId<"OrganizationId">(c.organizationId),station,page)));}catch(e){return failure(this.error(e));}}
 async listOrderWorks(c:OperationContext,orderId:OrderId):Promise<ApplicationResult<readonly ProductionWorkProjection[]>>{try{requireOperationPrincipalScope(c);this.require(c,"production.view");return success(await this.runner.transaction(tx=>tx.listOrderWorks(brandedId<"OrganizationId">(c.organizationId),orderId)));}catch(e){return failure(this.error(e));}}
 async open(c:OperationContext,input:OpenProductionWorkInput){const result=await this.mutate(c,"production.work.open.v1",input,"production.work","production_work_opened","Production work opened for eligible production Artwork.",async tx=>{const org=brandedId<"OrganizationId">(c.organizationId);if(!await tx.eligibleProductionAssignment(org,input.artworkAssignmentId))throw new V2ApplicationError("CONFLICT","Production Artwork is not eligible for Production.");return {work:await tx.createOrGetWork({id:brandedId<"ProductionWorkId">(randomUUID()),organizationId:org,artworkAssignmentId:input.artworkAssignmentId,...actor(c)})};});if(result.ok)await this.orderLifecycle?.reconcileOrder(brandedId<"OrganizationId">(c.organizationId),result.value.work.orderId);return result;}
 async start(c:OperationContext,input:StartProductionAttemptInput){return this.mutate(c,"production.attempt.start.v1",input,"production.work","production_attempt_started","Production attempt started.",async tx=>{const work=await tx.lockWork(brandedId<"OrganizationId">(c.organizationId),input.productionWorkId);if(!work)throw new V2ApplicationError("NOT_FOUND","Production work was not found.");const current=await tx.readWork(work.organizationId,work.productionWorkId);if(!current)throw new V2ApplicationError("NOT_FOUND","Production work was not found.");if(current.state==="held")throw new V2ApplicationError("CONFLICT","Held Production work must be resumed before a new attempt starts.");if(current.state==="rework_requested")throw new V2ApplicationError("CONFLICT","Production is blocked pending Prepress rework review.");if(current.unitQuantitySatisfied)throw new V2ApplicationError("CONFLICT","Required Production quantity is already satisfied.");const active=current.attempts.some(attempt=>!attempt.completedAt);if(active)throw new V2ApplicationError("CONFLICT","An active Production attempt already owns this Production work.");if(input.kind==="initial"&&current.attempts.length>0)throw new V2ApplicationError("CONFLICT","The initial Production attempt has already established this work's station.");if(input.kind!=="initial"&&current.attempts.length===0)throw new V2ApplicationError("CONFLICT","A reprint or correction requires a completed initial Production attempt.");return {work,attempt:await tx.startAttempt({id:brandedId<"ProductionAttemptId">(randomUUID()),organizationId:work.organizationId,productionWorkId:work.productionWorkId,stationKey:input.stationKey,kind:input.kind,...actor(c)})};});}
 async recordOutput(c:OperationContext,input:RecordProductionOutputInput){return this.mutate(c,"production.attempt.output.v1",input,"production.work","production_output_recorded","Production output recorded.",async tx=>{if(!Number.isSafeInteger(input.goodQuantityDelta)||input.goodQuantityDelta<0||!Number.isSafeInteger(input.wasteQuantityDelta??0)||(input.wasteQuantityDelta??0)<0||input.goodQuantityDelta+(input.wasteQuantityDelta??0)===0)throw new V2ApplicationError("VALIDATION_ERROR","Output deltas must be non-negative integers and cannot both be zero.");const attempt=await tx.lockAttempt(brandedId<"OrganizationId">(c.organizationId),input.productionAttemptId);if(!attempt)throw new V2ApplicationError("NOT_FOUND","Production attempt was not found.");if(attempt.completedAt)throw new V2ApplicationError("CONFLICT","Completed Production attempts are immutable.");const work=await tx.findWork(attempt.organizationId,attempt.productionWorkId);if(!work)throw new V2ApplicationError("NOT_FOUND","Production work was not found.");const projection=await tx.readWork(work.organizationId,work.productionWorkId);if(!projection)throw new V2ApplicationError("NOT_FOUND","Production work was not found.");if(projection.state!=="active")throw new V2ApplicationError("CONFLICT","Production output can only be recorded on an active, unheld work item.");if(input.goodQuantityDelta>projection.remainingGoodQuantity)throw new V2ApplicationError("CONFLICT","Good output exceeds the remaining required Production quantity.");return {work,attempt:await tx.recordOutput({organizationId:attempt.organizationId,productionAttemptId:attempt.productionAttemptId,goodQuantityDelta:input.goodQuantityDelta,wasteQuantityDelta:input.wasteQuantityDelta??0,...actor(c)})};});}
 async complete(c:OperationContext,input:CompleteProductionAttemptInput){const result=await this.mutate(c,"production.attempt.complete.v1",input,"production.complete","production_attempt_completed","Production attempt completed; this does not advance Routing or authorize Fulfillment.",async tx=>{const attempt=await tx.lockAttempt(brandedId<"OrganizationId">(c.organizationId),input.productionAttemptId);if(!attempt)throw new V2ApplicationError("NOT_FOUND","Production attempt was not found.");const work=await tx.findWork(attempt.organizationId,attempt.productionWorkId);if(!work)throw new V2ApplicationError("NOT_FOUND","Production work was not found.");const projection=await tx.readWork(work.organizationId,work.productionWorkId);if(!projection||projection.state==="held"||projection.state==="rework_requested")throw new V2ApplicationError("CONFLICT","Held or rework-blocked Production work cannot be completed.");return {work,attempt:attempt.completedAt?attempt:await tx.completeAttempt({organizationId:attempt.organizationId,productionAttemptId:attempt.productionAttemptId,...actor(c)})};});if(result.ok)await this.orderLifecycle?.reconcileOrder(brandedId<"OrganizationId">(c.organizationId),result.value.work.orderId);return result;}
 async hold(c:OperationContext,input:HoldProductionWorkInput){return this.exception(c,"production.work.hold.v1",input,"production.hold","production_work_held","Production work was placed on hold.","hold",async(tx,work)=>{const state=await tx.readWork(work.organizationId,work.productionWorkId);if(!state||state.unitQuantitySatisfied||state.state==="held"||state.state==="rework_requested")throw new V2ApplicationError("CONFLICT","This Production work cannot be placed on hold.");return tx.appendWorkEvent({id:randomUUID(),organizationId:work.organizationId,productionWorkId:work.productionWorkId,kind:"hold",category:requiredText(input.category,"A hold category"),note:optionalText(input.note),productionAttemptId:state.activeAttempt?.productionAttemptId,...actor(c)});});}
 async resume(c:OperationContext,input:ResumeProductionWorkInput){return this.exception(c,"production.work.resume.v1",input,"production.hold","production_work_resumed","Production work was resumed.","resume",async(tx,work)=>{const state=await tx.readWork(work.organizationId,work.productionWorkId);if(!state||state.state!=="held")throw new V2ApplicationError("CONFLICT","Only held Production work can be resumed.");return tx.appendWorkEvent({id:randomUUID(),organizationId:work.organizationId,productionWorkId:work.productionWorkId,kind:"resume",note:optionalText(input.note),productionAttemptId:state.activeAttempt?.productionAttemptId,...actor(c)});});}
 async note(c:OperationContext,input:NoteProductionWorkInput){return this.exception(c,"production.work.note.v1",input,"production.note","production_work_noted","Production note recorded.","note",async(tx,work)=>tx.appendWorkEvent({id:randomUUID(),organizationId:work.organizationId,productionWorkId:work.productionWorkId,kind:"note",note:requiredText(input.note,"A Production note"),...actor(c)}));}
 async requestRework(c:OperationContext,input:RequestProductionReworkInput){return this.exception(c,"production.work.rework-request.v1",input,"production.rework","production_work_rework_requested","Prepress rework was requested; no Route, attempt, output, or Fulfillment fact was changed.","rework_requested",async(tx,work)=>{const state=await tx.readWork(work.organizationId,work.productionWorkId);if(!state||state.unitQuantitySatisfied||state.state==="rework_requested")throw new V2ApplicationError("CONFLICT","Only incomplete, non-rework-blocked Production work can request Prepress review.");return tx.appendWorkEvent({id:randomUUID(),organizationId:work.organizationId,productionWorkId:work.productionWorkId,kind:"rework_requested",reason:requiredText(input.reason,"A rework reason"),category:optionalText(input.category),note:optionalText(input.note),productionAttemptId:state.activeAttempt?.productionAttemptId,recordedGoodQuantity:state.recordedGoodQuantity,recordedWasteQuantity:state.attempts.reduce((total,attempt)=>total+attempt.wasteQuantity,0),...actor(c)});});}
 private async exception(c:OperationContext,operation:string,input:{businessRequestId:string;productionWorkId:ProductionWorkId},cap:"production.hold"|"production.rework"|"production.note",eventType:Parameters<ProductionTransaction["audit"]>[0]["eventType"],summary:string,_kind:ProductionWorkEvent["kind"],create:(tx:ProductionTransaction,work:ProductionWork)=>Promise<ProductionWorkEvent>):Promise<ApplicationResult<ProductionMutationResult>>{return this.mutate(c,operation,input,cap,eventType,summary,async tx=>{const work=await tx.lockWork(brandedId<"OrganizationId">(c.organizationId),input.productionWorkId);if(!work)throw new V2ApplicationError("NOT_FOUND","Production work was not found.");return {work,event:await create(tx,work)};});}
 private async mutate(c:OperationContext,operation:string,input:{businessRequestId:string},cap:"production.work"|"production.complete"|"production.hold"|"production.rework"|"production.note",eventType:Parameters<ProductionTransaction["audit"]>[0]["eventType"],summary:string,work:(tx:ProductionTransaction)=>Promise<ProductionMutationResult>):Promise<ApplicationResult<ProductionMutationResult>>{try{requireOperationPrincipalScope(c);this.require(c,cap);if(!c.businessRequest||c.businessRequest.id!==input.businessRequestId)throw new V2ApplicationError("VALIDATION_ERROR","A matching business request identity is required.");return success(await this.runner.transaction(async tx=>{const reserved=await tx.reserve({organizationId:c.organizationId,operation,businessRequestId:input.businessRequestId,payloadFingerprint:fingerprint(input),...actor(c)});if(reserved.kind==="replay")return reserved.request.resultJson as ProductionMutationResult;const result=await work(tx);const target=result.attempt?["production_attempt",result.attempt.productionAttemptId] as const:["production_work",result.work.productionWorkId] as const;await tx.attribute({organizationId:c.organizationId,requestId:reserved.request.id,operation,resourceType:target[0],resourceId:target[1],...actor(c)});await tx.audit({organizationId:c.organizationId,requestId:reserved.request.id,operation,eventType,resourceId:target[1],summary,...actor(c)});await tx.succeed(c.organizationId,reserved.request.id,result);return result;}));}catch(e){return failure(this.error(e));}}
 private require(c:OperationContext,cap:"production.view"|"production.work"|"production.complete"|"production.hold"|"production.rework"|"production.note"){if(!this.authority.decide(c.principal,{capability:cap,resource:{organizationId:c.organizationId}}).allowed)throw new V2ApplicationError("FORBIDDEN","The principal does not have authority for this Production operation.");}
 private error(e:unknown){return e instanceof V2ApplicationError?e:new V2ApplicationError("VALIDATION_ERROR",e instanceof Error?e.message:"Production operation could not be completed.");}
}
const requiredText=(value:string,label:string)=>{const normalized=value?.trim();if(!normalized)throw new V2ApplicationError("VALIDATION_ERROR",`${label} is required.`);if(normalized.length>1_000)throw new V2ApplicationError("VALIDATION_ERROR",`${label} is too long.`);return normalized;};
const optionalText=(value?:string)=>{if(value===undefined)return undefined;return requiredText(value,"The note");};
