import { z } from "zod";
import type { AssistantCanonicalCommandAdapter, AssistantCommandDefinition, AssistantCommandExecutionContext } from "./commandRegistry";
import { ExecutionPlanError } from "./types";
import type { ExecutionCommandDefinition, ExecutionCommandResult, ExecutionPlanPreview } from "./types";
import { fulfillmentOperationCommandNames, type FulfillmentOperationCommandName, type FulfillmentOperationsService } from "../fulfillmentOperationsService";
const fingerprint = z.string().regex(/^[a-f0-9]{64}$/i);
export const fulfillmentOperationInputSchema = z.object({ fulfillmentIntakeSessionId: z.string().min(1), proposalFingerprint: fingerprint }).strict();
const resultSchema = z.object({ sourceLinks: z.array(z.object({ label: z.string(), href: z.string() })), summary: z.string() }).strict();
function label(name: FulfillmentOperationCommandName) { return ({ "fulfillment.create_shipment": "Create draft shipment", "fulfillment.update_shipment_details": "Update draft shipment details", "fulfillment.mark_shipped": "Mark shipment shipped", "fulfillment.create_pickup_ticket": "Create pickup ticket", "fulfillment.add_note": "Add fulfillment note" } as const)[name]; }
export function createFulfillmentOperationCommandDefinition(name: FulfillmentOperationCommandName, service: FulfillmentOperationsService): AssistantCommandDefinition { const adapter: AssistantCanonicalCommandAdapter = { async execute(raw, context: AssistantCommandExecutionContext) { const input = fulfillmentOperationInputSchema.parse(raw); return resultSchema.parse(await service.executeConfirmed({ organizationId: context.organizationId, actorUserId: context.actorUserId, ...input })); } }; return { name, version: "v1", domain: "fulfillment", mode: "write", description: `${label(name)} through the canonical fulfillment service.`, risk: "high", requiredCapability: `assistant.${name}`, allowedRoles: ["owner", "admin", "manager", "employee"], inputSchema: fulfillmentOperationInputSchema, previewSchema: z.object({}).passthrough(), resultSchema, maxAffectedRecords: 10, bulkAllowed: name === "fulfillment.create_shipment", confirmationRequired: true, reauthenticationRequired: false, confirmationExpiresInMs: 5 * 60_000, idempotencyPolicy: "server_generated_with_request_hash", recordFingerprintStrategy: "updated_at_and_critical_fields", transactionPolicy: "required", partialFailurePolicy: "forbid", auditCategory: `assistant_${name.replaceAll(".", "_")}`, undoSupport: "metadata_only", abandonmentPolicy: "session_abandonment_only", testOnly: false, devEnabled: true, mainEnabled: true, adapter }; }
export function createFulfillmentOperationExecutionCommand(name: FulfillmentOperationCommandName, service: FulfillmentOperationsService): ExecutionCommandDefinition { const command = createFulfillmentOperationCommandDefinition(name, service); return { name, version: "v1", testOnly: false, riskLevel: "high", confirmationTtlMs: command.confirmationExpiresInMs, maxAffectedRecords: command.maxAffectedRecords, requiredPermissions: [command.requiredCapability], async buildPreview({ scope, arguments: raw }) { const input = fulfillmentOperationInputSchema.parse(raw); const validation = await service.revalidateProposal({ organizationId: scope.organizationId, fulfillmentIntakeSessionId: input.fulfillmentIntakeSessionId, expectedProposalFingerprint: input.proposalFingerprint }); if (!validation.valid) throw new ExecutionPlanError(validation.code, validation.summary); return { arguments: input, preview: { title: label(name), summary: validation.proposal.summary, sideEffects: [validation.proposal.summary, "No production, invoice, payment, or accounting state will change."], affectedRecords: [{ entityType: "assistant_fulfillment_intake_session", entityId: input.fulfillmentIntakeSessionId, fingerprint: input.proposalFingerprint }] } as ExecutionPlanPreview }; }, async revalidate({ plan, scope }) { const input = fulfillmentOperationInputSchema.parse(plan.sanitizedArguments); const result = await service.revalidateProposal({ organizationId: scope.organizationId, fulfillmentIntakeSessionId: input.fulfillmentIntakeSessionId, expectedProposalFingerprint: input.proposalFingerprint }); return result.valid ? { valid: true as const } : { valid: false as const, code: result.code, summary: result.summary }; }, async execute({ plan, scope }): Promise<ExecutionCommandResult> { const result = resultSchema.parse(await command.adapter.execute(fulfillmentOperationInputSchema.parse(plan.sanitizedArguments), { organizationId: scope.organizationId, actorUserId: scope.userId, planId: plan.id, idempotencyKey: plan.idempotencyKey, correlationId: plan.correlationId, signal: new AbortController().signal })); return { status: "succeeded", summary: result.summary, steps: [{ commandName: `${name}@v1`, status: "succeeded", summary: `${label(name)} succeeded.` }] }; } }; }
