import { z } from "zod";
import type { AssistantCanonicalCommandAdapter, AssistantCommandDefinition, AssistantCommandExecutionContext } from "./commandRegistry";
import { ExecutionPlanError } from "./types";
import type { ExecutionCommandDefinition, ExecutionCommandResult, ExecutionPlanPreview } from "./types";
import { productionOperationCommandNames, type ProductionOperationCommandName, type ProductionOperationsService } from "../productionOperationsService";

const fingerprint = z.string().regex(/^[a-f0-9]{64}$/i);
export const productionOperationInputSchema = z.object({ productionIntakeSessionId: z.string().min(1), proposalFingerprint: fingerprint }).strict();
const resultSchema = z.object({ sourceLinks: z.array(z.object({ label: z.string(), href: z.string() })), summary: z.string().optional() }).strict();
function label(name: ProductionOperationCommandName) { return ({ "production.intake_line_items": "Route line items to production", "production.send_to_prepress": "Send line item to Prepress", "production.update_job_status": "Start production job", "production.add_job_note": "Add production note" } as const)[name]; }
export function createProductionOperationCommandDefinition(name: ProductionOperationCommandName, service: ProductionOperationsService): AssistantCommandDefinition { const adapter: AssistantCanonicalCommandAdapter = { async execute(raw, context: AssistantCommandExecutionContext) { const input = productionOperationInputSchema.parse(raw); return resultSchema.parse(await service.executeConfirmed({ organizationId: context.organizationId, actorUserId: context.actorUserId, ...input })); } }; return { name, version: "v1", domain: "production", mode: "write", description: `${label(name)} using canonical production workflow services.`, risk: "high", requiredCapability: `assistant.${name}`, allowedRoles: ["owner", "admin", "manager", "employee"], inputSchema: productionOperationInputSchema, previewSchema: z.object({}).passthrough(), resultSchema, maxAffectedRecords: name === "production.intake_line_items" ? 25 : 1, bulkAllowed: name === "production.intake_line_items", confirmationRequired: true, reauthenticationRequired: false, confirmationExpiresInMs: 5 * 60_000, idempotencyPolicy: "server_generated_with_request_hash", recordFingerprintStrategy: "updated_at_and_critical_fields", transactionPolicy: "required", partialFailurePolicy: "forbid", auditCategory: `assistant_${name.replaceAll(".", "_")}`, undoSupport: "metadata_only", abandonmentPolicy: "session_abandonment_only", testOnly: false, devEnabled: true, mainEnabled: true, adapter }; }
export function createProductionOperationExecutionCommand(name: ProductionOperationCommandName, service: ProductionOperationsService): ExecutionCommandDefinition { const command = createProductionOperationCommandDefinition(name, service); return { name, version: "v1", testOnly: false, riskLevel: "high", confirmationTtlMs: command.confirmationExpiresInMs, maxAffectedRecords: command.maxAffectedRecords, requiredPermissions: [command.requiredCapability], async buildPreview({ scope, arguments: raw }) { const input = productionOperationInputSchema.parse(raw); const validation = await service.revalidateProposal({ organizationId: scope.organizationId, productionIntakeSessionId: input.productionIntakeSessionId, expectedProposalFingerprint: input.proposalFingerprint }); if (!validation.valid) throw new ExecutionPlanError(validation.code, validation.summary); const p = validation.proposal; const preview: ExecutionPlanPreview = { title: label(name), summary: p.summary, sideEffects: [p.summary, "No fulfillment, shipment, invoice, payment, customer, or order financial state will change."], affectedRecords: [{ entityType: "assistant_production_intake_session", entityId: p.productionIntakeSessionId, fingerprint: p.proposalFingerprint }] }; return { arguments: input, preview }; }, async revalidate({ plan, scope }) { const input = productionOperationInputSchema.parse(plan.sanitizedArguments); const result = await service.revalidateProposal({ organizationId: scope.organizationId, productionIntakeSessionId: input.productionIntakeSessionId, expectedProposalFingerprint: input.proposalFingerprint }); return result.valid ? { valid: true as const } : { valid: false as const, code: result.code, summary: result.summary }; }, async execute({ plan, scope }): Promise<ExecutionCommandResult> { const result = resultSchema.parse(await command.adapter.execute(productionOperationInputSchema.parse(plan.sanitizedArguments), { organizationId: scope.organizationId, actorUserId: scope.userId, planId: plan.id, idempotencyKey: plan.idempotencyKey, correlationId: plan.correlationId, signal: new AbortController().signal })); return { status: "succeeded", summary: result.summary ?? `${label(name)} succeeded.`, steps: [{ commandName: `${name}@v1`, status: "succeeded", summary: `${label(name)} succeeded.` }] }; } }; }
