import { ExecutionPlanError, type ExecutionCommandDefinition, type ExecutionCommandResult, type ExecutionPlanPreview } from "./types";
import { createProductPricingChangeSetCommandDefinition, createProductPricingRollbackCommandDefinition, productPricingChangeSetCommandInputSchema, productPricingChangeSetCommandName, productPricingRollbackCommandInputSchema, productPricingRollbackCommandName, type ProductPricingChangeSetCommandInput, type ProductPricingChangeSetCommandService } from "./productPricingChangeSetCommand";

type ChangeSetHistory = { get(organizationId: string, id: string): Promise<any> };
export function createProductPricingChangeSetExecutionCommand(service: ProductPricingChangeSetCommandService, history: ChangeSetHistory): ExecutionCommandDefinition {
  const command = createProductPricingChangeSetCommandDefinition(service);
  const load = async (organizationId: string, input: ProductPricingChangeSetCommandInput) => {
    const changeSet = await history.get(organizationId, input.changeSetId);
    if (!changeSet || changeSet.fingerprint !== input.fingerprint) throw new ExecutionPlanError("CHANGE_SET_CHANGED", "The persisted product pricing change set was not found or changed.");
    return changeSet;
  };
  return { name: command.name, version: command.version, testOnly: false, riskLevel: command.risk, confirmationTtlMs: command.confirmationExpiresInMs, maxAffectedRecords: command.maxAffectedRecords, requiredPermissions: [command.requiredCapability],
    async buildPreview({ scope, arguments: rawArguments }) {
      const input = productPricingChangeSetCommandInputSchema.parse(rawArguments); const changeSet = await load(scope.organizationId, input);
      const rows = changeSet.rows as any[]; const eligible = rows.filter((row) => row.executionState === "pending");
      if (!eligible.length) throw new ExecutionPlanError("NO_ELIGIBLE_ROWS", "No product rows remain eligible for this pricing change set.");
      const preview: ExecutionPlanPreview = { title: `Adjust pricing for ${eligible.length} product${eligible.length === 1 ? "" : "s"}`, summary: "Applies only the persisted scalar pricing values. Product lifecycle, publication, visibility, routing, options, quotes, orders, and historical snapshots remain unchanged.", sideEffects: eligible.map((row) => `Update ${row.productName} (${row.productId}).`), affectedRecords: rows.map((row) => ({ entityType: "product", entityId: row.productId, fingerprint: row.sourceFingerprint })), productPricingChangeSet: { changeSetId: changeSet.id, selector: changeSet.selector, operation: changeSet.operation, targetCount: rows.length, eligibleCount: eligible.length, excluded: rows.filter((row) => row.executionState === "excluded").map((row) => ({ productId: row.productId, productName: row.productName, reason: row.exclusionReason ?? "Unsupported pricing" })), rows: rows.map((row) => ({ productId: row.productId, productName: row.productName, active: row.activeSnapshot, before: row.beforeValues, after: row.proposedValues, state: row.executionState })), unchanged: ["product_lifecycle", "publication_visibility", "routing_options", "quotes_orders_invoices", "historical_snapshots"] } };
      return { arguments: input, preview };
    },
    async revalidate({ plan, scope }) { try { await load(scope.organizationId, productPricingChangeSetCommandInputSchema.parse(plan.sanitizedArguments)); return { valid: true as const }; } catch (error) { return { valid: false as const, code: "CHANGE_SET_CHANGED", summary: error instanceof Error ? error.message : "The pricing change set changed." }; } },
    async execute({ plan, scope }): Promise<ExecutionCommandResult> { const input = productPricingChangeSetCommandInputSchema.parse(plan.sanitizedArguments); try { const result = await command.adapter.execute(input, { organizationId: scope.organizationId, actorUserId: scope.userId, planId: plan.id, idempotencyKey: plan.idempotencyKey, correlationId: plan.correlationId, signal: new AbortController().signal }); const partial = result.failed || result.conflicted; return { status: partial ? "partially_failed" : "succeeded", summary: partial ? `Pricing change set completed with ${result.succeeded} updated, ${result.conflicted} stale/conflicted, and ${result.failed} failed product(s).` : `Pricing change set completed for ${result.succeeded} product(s).`, steps: [{ commandName: `${productPricingChangeSetCommandName}@v1`, status: partial ? "failed" : "succeeded", summary: "Only the confirmed scalar pricing fields were changed; lifecycle and visibility were preserved." }] }; } catch (error) { return { status: "failed", summary: error instanceof Error ? `Pricing change set stopped safely: ${error.message}` : "Pricing change set stopped safely.", steps: [{ commandName: `${productPricingChangeSetCommandName}@v1`, status: "failed", summary: "No replacement targets were selected." }] }; } },
  };
}

export function createProductPricingRollbackExecutionCommand(service: ProductPricingChangeSetCommandService, history: ChangeSetHistory): ExecutionCommandDefinition {
  const command = createProductPricingRollbackCommandDefinition(service);
  const load = async (organizationId: string, input: ProductPricingChangeSetCommandInput) => {
    const changeSet = await history.get(organizationId, input.changeSetId);
    if (!changeSet || changeSet.fingerprint !== input.fingerprint) throw new ExecutionPlanError("CHANGE_SET_CHANGED", "The persisted product pricing change set was not found or changed.");
    return changeSet;
  };
  return { name: command.name, version: command.version, testOnly: false, riskLevel: command.risk, confirmationTtlMs: command.confirmationExpiresInMs, maxAffectedRecords: command.maxAffectedRecords, requiredPermissions: [command.requiredCapability],
    async buildPreview({ scope, arguments: rawArguments }) {
      const input = productPricingRollbackCommandInputSchema.parse(rawArguments); const changeSet = await load(scope.organizationId, input); const rows = changeSet.rows as any[];
      const rollbackRows = rows.filter((row) => row.executionState === "succeeded");
      const eligible = rollbackRows.filter((row) => row.rollbackState !== "rolled_back");
      if (!eligible.length) throw new ExecutionPlanError("NO_ELIGIBLE_ROWS", "No successfully applied product values remain eligible for rollback.");
      const preview: ExecutionPlanPreview = { title: `Roll back pricing change set ${changeSet.id}`, summary: "Restores only original scalar fields whose current values still match the executed pricing change. Product lifecycle, publication, visibility, routing, options, and historical snapshots remain unchanged.", sideEffects: eligible.map((row) => `Restore ${row.productName} (${row.productId}).`), affectedRecords: eligible.map((row) => ({ entityType: "product", entityId: row.productId, fingerprint: row.sourceFingerprint })), productPricingRollback: { changeSetId: changeSet.id, requestSummary: changeSet.requestSummary, targetCount: rows.length, eligibleCount: eligible.length, alreadyRolledBackCount: rollbackRows.filter((row) => row.rollbackState === "rolled_back").length, conflictCount: rollbackRows.filter((row) => row.rollbackState === "conflicted").length, rows: rollbackRows.map((row) => ({ productId: row.productId, productName: row.productName, active: row.activeSnapshot, before: row.beforeValues, current: row.executedValues ?? row.proposedValues, proposedRestore: row.beforeValues, state: row.rollbackState ?? "not_requested", ...(row.rollbackConflictReason ? { reason: row.rollbackConflictReason } : {}) })) } };
      return { arguments: input, preview };
    },
    async revalidate({ plan, scope }) { try { await load(scope.organizationId, productPricingRollbackCommandInputSchema.parse(plan.sanitizedArguments)); return { valid: true as const }; } catch (error) { return { valid: false as const, code: "CHANGE_SET_CHANGED", summary: error instanceof Error ? error.message : "The pricing change set changed." }; } },
    async execute({ plan, scope }): Promise<ExecutionCommandResult> { const input = productPricingRollbackCommandInputSchema.parse(plan.sanitizedArguments); try { const result = await command.adapter.execute(input, { organizationId: scope.organizationId, actorUserId: scope.userId, planId: plan.id, idempotencyKey: plan.idempotencyKey, correlationId: plan.correlationId, signal: new AbortController().signal }); const partial = result.failed || result.conflicted; return { status: partial ? "partially_failed" : "succeeded", summary: partial ? `Rollback completed with ${result.restored} restored, ${result.conflicted} conflicted, and ${result.failed} failed product(s).` : `Rollback restored ${result.restored} product(s).`, steps: [{ commandName: `${productPricingRollbackCommandName}@v1`, status: partial ? "failed" : "succeeded", summary: "Only still-matching scalar fields were restored; lifecycle and visibility were preserved." }] }; } catch (error) { return { status: "failed", summary: error instanceof Error ? `Pricing rollback stopped safely: ${error.message}` : "Pricing rollback stopped safely.", steps: [{ commandName: `${productPricingRollbackCommandName}@v1`, status: "failed", summary: "No product values were force-restored." }] }; } },
  };
}
