import { ExecutionPlanError } from "./types";
import type { ExecutionCommandDefinition, ExecutionCommandResult, ExecutionPlanPreview } from "./types";
import { createProductInactiveDraftBulkUpdateCommandDefinition, productInactiveDraftBulkUpdateCommandInputSchema, productInactiveDraftBulkUpdateCommandName, type ProductInactiveDraftBulkUpdateCanonicalService, type ProductInactiveDraftBulkUpdateCommandInput } from "./productInactiveDraftBulkUpdateCommand";
import type { ProductInactiveDraftUpdateCommandInput } from "./productInactiveDraftUpdateCommand";
import type { ProductInactiveDraftUpdatePlanningService } from "./productInactiveDraftUpdateExecutionCommand";
import { classifyProductDraftBulkUpdateFailure, productDraftBulkUpdateResumeEligibility, resumableProductDraftBulkUpdateRows } from "../productInactiveDraftBulkUpdateRecovery";

type History = { getDetail(organizationId: string, id: string): Promise<any>; bindConfirmation(input: any): Promise<void>; markRowRunning(input: any): Promise<void>; markRowSuccess(input: any): Promise<void>; markRowFailure(input: any): Promise<void>; complete(organizationId: string, id: string): Promise<void> };
export interface ProductInactiveDraftBulkUpdatePlanningService extends ProductInactiveDraftBulkUpdateCanonicalService { single: ProductInactiveDraftUpdatePlanningService; history: History; }

export function createProductInactiveDraftBulkUpdateCanonicalService(single: ProductInactiveDraftUpdatePlanningService, history: History): ProductInactiveDraftBulkUpdatePlanningService {
  const resolvedHistory = history;
  return { single, history: resolvedHistory, async updateInactiveDraftBatch(input) {
    const detail = await resolvedHistory.getDetail(input.organizationId, input.bulkUpdateId);
    if (!detail || detail.proposal.fingerprint !== input.bulkFingerprint) throw new ExecutionPlanError("BULK_PROPOSAL_CHANGED", "The persisted bulk proposal was not found or changed.");
    const rows = resumableProductDraftBulkUpdateRows(detail.rows as any[]) as any[];
    for (const row of rows) {
      try {
        await resolvedHistory.markRowRunning({ organizationId: input.organizationId, bulkUpdateId: input.bulkUpdateId, rowId: row.id });
        const patch = row.patch as ProductInactiveDraftUpdateCommandInput["patch"];
        const revalidated = await single.revalidateProposal({ organizationId: input.organizationId, sessionId: row.sessionId, patch, expectedFingerprint: row.beforeFingerprint });
        if (!revalidated.valid) { await resolvedHistory.markRowFailure({ organizationId: input.organizationId, bulkUpdateId: input.bulkUpdateId, rowId: row.id, state: "stale", code: revalidated.code, message: revalidated.summary, retryable: false }); continue; }
        const result = await single.updateInactiveDraft({ organizationId: input.organizationId, actorUserId: input.actorUserId, assistantPlanId: `${input.assistantPlanId}:row:${row.sourceOrder}`, idempotencyKey: row.idempotencyKey, correlationId: input.correlationId, productIntakeSessionId: row.sessionId, proposalFingerprint: row.beforeFingerprint, patch });
        if (result.product.active || !result.pbv2DraftTreeVersionId) throw new ExecutionPlanError("POST_UPDATE_SAFETY_CHECK_FAILED", "The update did not retain an inactive PBV2 DRAFT product.");
        await resolvedHistory.markRowSuccess({ organizationId: input.organizationId, bulkUpdateId: input.bulkUpdateId, rowId: row.id, readinessAfter: { status: result.readiness }, afterSnapshot: { productId: result.product.id, active: result.product.active, pbv2DraftTreeVersionId: result.pbv2DraftTreeVersionId } });
      } catch (error) { const failure = classifyProductDraftBulkUpdateFailure(error); await resolvedHistory.markRowFailure({ organizationId: input.organizationId, bulkUpdateId: input.bulkUpdateId, rowId: row.id, ...failure }); }
    }
    await resolvedHistory.complete(input.organizationId, input.bulkUpdateId);
    const completed = await resolvedHistory.getDetail(input.organizationId, input.bulkUpdateId); const resume = productDraftBulkUpdateResumeEligibility(completed.rows);
    return { updated: completed.rows.filter((row: any) => row.executionState === "updated").length, noChange: resume.noChangeCount, failures: resume.retryableCount + resume.terminalCount, stale: resume.staleCount, pending: resume.pendingCount };
  } };
}

export function createProductInactiveDraftBulkUpdateExecutionCommand(service: ProductInactiveDraftBulkUpdatePlanningService): ExecutionCommandDefinition {
  const command = createProductInactiveDraftBulkUpdateCommandDefinition(service);
  const load = async (organizationId: string, input: ProductInactiveDraftBulkUpdateCommandInput) => { const detail = await service.history.getDetail(organizationId, input.bulkUpdateId); if (!detail) throw new ExecutionPlanError("BULK_NOT_FOUND", "The persisted bulk update proposal was not found."); if (detail.proposal.fingerprint !== input.bulkFingerprint) throw new ExecutionPlanError("BULK_PROPOSAL_CHANGED", "The persisted bulk proposal fingerprint changed."); return detail; };
  return { name: command.name, version: command.version, testOnly: false, riskLevel: command.risk, confirmationTtlMs: command.confirmationExpiresInMs, maxAffectedRecords: command.maxAffectedRecords, requiredPermissions: [command.requiredCapability],
    async buildPreview({ scope, arguments: rawArguments }) { const input = productInactiveDraftBulkUpdateCommandInputSchema.parse(rawArguments); const detail = await load(scope.organizationId, input); const resume = productDraftBulkUpdateResumeEligibility(detail.rows); const preview: ExecutionPlanPreview = { title: `Update ${detail.proposal.eligibleCount} inactive product drafts`, summary: "Applies only the persisted patch to inactive PBV2 DRAFT products. Activation, publication, and live quoting are excluded.", sideEffects: detail.rows.filter((row: any) => row.executionState === "pending").map((row: any) => `Update ${row.productName} (${row.productId}).`), affectedRecords: detail.rows.map((row: any) => ({ entityType: "product", entityId: row.productId, fingerprint: row.beforeFingerprint })), productInactiveDraftBatch: { batchFingerprint: input.bulkFingerprint, children: detail.rows.map((row: any) => ({ rowNumber: row.sourceOrder, productName: row.productName, intakeSessionId: row.sessionId })), unchanged: ["product_activation", "publication", "live_quoting", "quotes_orders_invoices", "production_jobs"] } }; if (!resume.available && detail.proposal.eligibleCount) throw new ExecutionPlanError("NO_ELIGIBLE_ROWS", "No pending or retryable bulk-update rows remain."); return { arguments: input, preview }; },
    async revalidate({ plan, scope }) { try { await load(scope.organizationId, productInactiveDraftBulkUpdateCommandInputSchema.parse(plan.sanitizedArguments)); return { valid: true as const }; } catch (error) { return { valid: false as const, code: error instanceof ExecutionPlanError ? error.code : "BULK_PROPOSAL_CHANGED", summary: error instanceof Error ? error.message : "The bulk proposal changed." }; } },
    async execute({ plan, scope }): Promise<ExecutionCommandResult> { const input = productInactiveDraftBulkUpdateCommandInputSchema.parse(plan.sanitizedArguments); try { await service.history.bindConfirmation({ organizationId: scope.organizationId, bulkUpdateId: input.bulkUpdateId, planId: plan.id, correlationId: plan.correlationId, idempotencyKey: plan.idempotencyKey }); const result = await command.adapter.execute(input, { organizationId: scope.organizationId, actorUserId: scope.userId, planId: plan.id, idempotencyKey: plan.idempotencyKey, correlationId: plan.correlationId, signal: new AbortController().signal }); const status = result.failures || result.stale || result.pending ? "partially_failed" : "succeeded"; return { status, summary: status === "succeeded" ? `Bulk update completed successfully for ${result.updated} inactive PBV2 DRAFT products.` : `Bulk update completed with ${result.updated} update(s), ${result.failures} failure(s), and ${result.stale} stale row(s).`, steps: [{ commandName: `${productInactiveDraftBulkUpdateCommandName}@v1`, status: status === "succeeded" ? "succeeded" : "failed", summary: "Updated products remain inactive PBV2 DRAFT; no activation or publication occurred." }] }; } catch (error) { return { status: "failed", summary: error instanceof Error ? `Bulk update stopped safely: ${error.message}` : "Bulk update stopped safely.", steps: [{ commandName: `${productInactiveDraftBulkUpdateCommandName}@v1`, status: "failed", summary: "No replacement targets or patches were accepted." }] }; } },
  };
}
