import type { Pool } from "pg";
import type { PortalPrincipal } from "../../src/authorization/principals.js";
import type { PortalCommercialRead, PortalOrderDetail, PortalOrderSummary, PortalPage, PortalQuoteDetail, PortalQuoteSummary } from "../../src/modules/portal/commercialReads.js";

const pageSize = 30;
const money = (cents: string | number, currency: string) => ({ cents: Number(cents), currency });
const commercialStatus = (value: string): "open" | "completed" | "cancelled" => value === "completed" ? "completed" : value === "cancelled" ? "cancelled" : "open";

/** Queries bind their Customer predicate exclusively from the portal principal. */
export class PostgresPortalCommercialRead implements PortalCommercialRead {
  constructor(private readonly pool: Pool) {}
  async listOrders(principal: PortalPrincipal): Promise<PortalPage<PortalOrderSummary>> {
    const result = await this.pool.query<any>(`SELECT d.id,d.display_number,d.purchase_order_number,d.created_at,d.requested_due_date,o.commercial_state,d.currency,COALESCE((SELECT sum(l.selling_line_cents) FROM v2_sales_document_lines l WHERE l.organization_id=d.organization_id AND l.document_id=d.id),0)::text total_cents,COALESCE((SELECT sum(i.total_cents-COALESCE((SELECT sum(a.amount_cents) FROM v2_billing_payment_allocations a WHERE a.organization_id=i.organization_id AND a.invoice_id=i.id),0)+COALESCE((SELECT sum(r.amount_cents) FROM v2_billing_refunds r WHERE r.organization_id=i.organization_id AND r.invoice_id=i.id),0)) FROM v2_billing_invoices i WHERE i.organization_id=d.organization_id AND i.sales_order_document_id=d.id AND i.invoice_state<>'void'),0)::text balance_cents,(SELECT count(*) FROM v2_sales_document_lines l WHERE l.organization_id=d.organization_id AND l.document_id=d.id)::int line_count,(SELECT count(*) FROM v2_sales_document_lines l WHERE l.organization_id=d.organization_id AND l.document_id=d.id AND COALESCE((SELECT sum(h.quantity) FROM v2_fulfillment_handoff_lines h WHERE h.organization_id=l.organization_id AND h.order_line_id=l.id),0)>=l.quantity)::int fulfilled_count FROM v2_sales_documents d JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id WHERE d.organization_id=$1 AND d.customer_id=$2 AND d.document_kind='order' ORDER BY d.updated_at DESC,d.id DESC LIMIT $3`, [principal.organizationId, principal.customerId, pageSize]);
    return { items: result.rows.map((row: any): PortalOrderSummary => ({ orderId: row.id, number: row.display_number, ...(row.purchase_order_number ? { purchaseOrderNumber: row.purchase_order_number } : {}), createdAt: row.created_at.toISOString(), ...(row.requested_due_date ? { requestedDueDate: String(row.requested_due_date) } : {}), status: commercialStatus(row.commercial_state), total: money(row.total_cents, row.currency), payment: Number(row.balance_cents) > 0 ? "open_balance" : Number(row.balance_cents) === 0 ? "settled" : "settled", fulfillment: Number(row.line_count) === 0 ? "not_required" : Number(row.fulfilled_count) === 0 ? "required" : Number(row.fulfilled_count) < Number(row.line_count) ? "partial" : "fulfilled" })) };
  }
  async getOrder(principal: PortalPrincipal, orderId: string): Promise<PortalOrderDetail | null> {
    const result=await this.pool.query<any>(`SELECT d.id,d.display_number,d.purchase_order_number,d.created_at,d.requested_due_date,o.commercial_state,d.currency,COALESCE((SELECT sum(l.selling_line_cents) FROM v2_sales_document_lines l WHERE l.organization_id=d.organization_id AND l.document_id=d.id),0)::text total_cents,COALESCE((SELECT sum(i.total_cents-COALESCE((SELECT sum(a.amount_cents) FROM v2_billing_payment_allocations a WHERE a.organization_id=i.organization_id AND a.invoice_id=i.id),0)+COALESCE((SELECT sum(r.amount_cents) FROM v2_billing_refunds r WHERE r.organization_id=i.organization_id AND r.invoice_id=i.id),0)) FROM v2_billing_invoices i WHERE i.organization_id=d.organization_id AND i.sales_order_document_id=d.id AND i.invoice_state<>'void'),0)::text balance_cents FROM v2_sales_documents d JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id WHERE d.organization_id=$1 AND d.customer_id=$2 AND d.id=$3 AND d.document_kind='order'`,[principal.organizationId,principal.customerId,orderId]); const row=result.rows[0];if(!row)return null;
    const [lines, shipments, fulfillment]=await Promise.all([this.pool.query<any>("SELECT id,description,quantity,selling_unit_cents,selling_line_cents FROM v2_sales_document_lines WHERE organization_id=$1 AND document_id=$2 ORDER BY position",[principal.organizationId,orderId]),this.pool.query<any>(`SELECT s.id,s.shipment_status,s.manual_carrier_name,s.manual_carrier_service,s.manual_tracking_number,s.shipped_at,COALESCE(sum(hl.quantity),0)::int quantity FROM v2_fulfillment_handoffs h JOIN v2_fulfillment_shipment_handoffs sh ON sh.organization_id=h.organization_id AND sh.handoff_id=h.id JOIN v2_fulfillment_shipments s ON s.organization_id=sh.organization_id AND s.id=sh.shipment_id JOIN v2_fulfillment_handoff_lines hl ON hl.organization_id=h.organization_id AND hl.handoff_id=h.id WHERE h.organization_id=$1 AND h.customer_id=$2 AND h.order_document_id=$3 GROUP BY s.id,s.shipment_status,s.manual_carrier_name,s.manual_carrier_service,s.manual_tracking_number,s.shipped_at`,[principal.organizationId,principal.customerId,orderId]),this.pool.query<{total:string;done:string}>("SELECT count(*)::text total,count(*) FILTER (WHERE COALESCE((SELECT sum(h.quantity) FROM v2_fulfillment_handoff_lines h WHERE h.organization_id=l.organization_id AND h.order_line_id=l.id),0)>=l.quantity)::text done FROM v2_sales_document_lines l WHERE l.organization_id=$1 AND l.document_id=$2",[principal.organizationId,orderId])]); const total=Number(fulfillment.rows[0]?.total??0),done=Number(fulfillment.rows[0]?.done??0);
    return {orderId:row.id,number:row.display_number,...(row.purchase_order_number?{purchaseOrderNumber:row.purchase_order_number}:{}),createdAt:row.created_at.toISOString(),...(row.requested_due_date?{requestedDueDate:String(row.requested_due_date)}:{}),status:commercialStatus(row.commercial_state),total:money(row.total_cents,row.currency),payment:Number(row.balance_cents)>0?"open_balance":"settled",fulfillment:total===0?"not_required":done===0?"required":done<total?"partial":"fulfilled",lines:lines.rows.map((line:any)=>({lineId:line.id,description:line.description,quantity:Number(line.quantity),unitPrice:money(line.selling_unit_cents,row.currency),lineTotal:money(line.selling_line_cents,row.currency)})),shipments:shipments.rows.map((shipment:any)=>({shipmentId:shipment.id,status:shipment.shipment_status,...(shipment.manual_carrier_name?{carrier:shipment.manual_carrier_name}:{}),...(shipment.manual_carrier_service?{service:shipment.manual_carrier_service}:{}),...(shipment.manual_tracking_number?{trackingNumber:shipment.manual_tracking_number}:{}),...(shipment.shipped_at?{shippedAt:shipment.shipped_at.toISOString()}:{}),quantity:Number(shipment.quantity)}))};
  }
  async listQuotes(principal: PortalPrincipal): Promise<PortalPage<PortalQuoteSummary>> { const result=await this.pool.query<any>(`SELECT d.id,d.display_number,d.created_at,d.requested_due_date,d.currency,q.acceptance_state,q.delivery_state,conversion.order_document_id,COALESCE((SELECT sum(l.selling_line_cents) FROM v2_sales_document_lines l WHERE l.organization_id=d.organization_id AND l.document_id=d.id),0)::text total_cents FROM v2_sales_documents d JOIN v2_sales_quote_details q ON q.organization_id=d.organization_id AND q.document_id=d.id LEFT JOIN v2_sales_quote_conversions conversion ON conversion.organization_id=d.organization_id AND conversion.quote_document_id=d.id WHERE d.organization_id=$1 AND d.customer_id=$2 AND d.document_kind='quote' ORDER BY d.updated_at DESC,d.id DESC LIMIT $3`,[principal.organizationId,principal.customerId,pageSize]);return{items:result.rows.map((row:any)=>({quoteId:row.id,number:row.display_number,createdAt:row.created_at.toISOString(),...(row.requested_due_date?{requestedDueDate:String(row.requested_due_date)}:{}),status:row.order_document_id?"converted":row.acceptance_state??row.delivery_state,total:money(row.total_cents,row.currency),...(row.order_document_id?{convertedOrderId:row.order_document_id}:{})}))}; }
  async getQuote(principal: PortalPrincipal, quoteId: string): Promise<PortalQuoteDetail | null> { const result=await this.pool.query<any>(`SELECT d.id,d.display_number,d.created_at,d.requested_due_date,d.currency,q.acceptance_state,q.delivery_state,conversion.order_document_id,COALESCE((SELECT sum(l.selling_line_cents) FROM v2_sales_document_lines l WHERE l.organization_id=d.organization_id AND l.document_id=d.id),0)::text total_cents FROM v2_sales_documents d JOIN v2_sales_quote_details q ON q.organization_id=d.organization_id AND q.document_id=d.id LEFT JOIN v2_sales_quote_conversions conversion ON conversion.organization_id=d.organization_id AND conversion.quote_document_id=d.id WHERE d.organization_id=$1 AND d.customer_id=$2 AND d.id=$3 AND d.document_kind='quote'`,[principal.organizationId,principal.customerId,quoteId]);const row=result.rows[0];if(!row)return null;const lines=await this.pool.query<any>("SELECT id,description,quantity,selling_unit_cents,selling_line_cents FROM v2_sales_document_lines WHERE organization_id=$1 AND document_id=$2 ORDER BY position",[principal.organizationId,quoteId]);return{quoteId:row.id,number:row.display_number,createdAt:row.created_at.toISOString(),...(row.requested_due_date?{requestedDueDate:String(row.requested_due_date)}:{}),status:row.order_document_id?"converted":row.acceptance_state??row.delivery_state,total:money(row.total_cents,row.currency),...(row.order_document_id?{convertedOrderId:row.order_document_id}:{}),lines:lines.rows.map((line:any)=>({lineId:line.id,description:line.description,quantity:Number(line.quantity),unitPrice:money(line.selling_unit_cents,row.currency),lineTotal:money(line.selling_line_cents,row.currency)}))}; }
}
