import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const root = new URL("../../..", import.meta.url);
const source = (path: string) => readFileSync(new URL(path, root), "utf8");
const adapter = source("v2/infrastructure/organization/postgresOrganizationSettings.ts");
const documentBranding = source("v2/infrastructure/documents/postgresTenantBranding.ts");
const salesDocuments = source("v2/infrastructure/sales/postgresCustomerDocuments.ts");
const quoteDelivery = source("v2/infrastructure/sales/postgresQuoteDelivery.ts");
const quoteApplication = source("v2/src/modules/sales/quoteApplication.ts");
const invoiceTransaction = source("v2/infrastructure/billing/postgresBillingInvoiceTransaction.ts");
const invoiceDocuments = source("v2/infrastructure/billing/postgresInvoiceDocuments.ts");
const migration = source("server/db/migrations_v2/0234_v2_organization_settings_capability.sql");
assert.match(adapter, /FROM company_settings WHERE organization_id=\$1/u);
assert.match(adapter, /FOR UPDATE/u);
assert.match(adapter, /PostgresOperationRequestRepository/u);
assert.match(adapter, /v2_audit_events/u);
assert.match(adapter, /STALE_STATE/u);
assert.ok(!adapter.includes("UPDATE company_settings SET") || adapter.includes("BEGIN"));
assert.match(documentBranding, /physical_address/u);
assert.match(documentBranding, /remittance_address/u);
assert.match(salesDocuments, /readTenantBranding/u);
assert.match(salesDocuments, /organizationIdentity\(payload\.organizationPresentation\) \?\? branding/u);
assert.match(quoteDelivery, /documentOrganizationIdentity: document\.organization/u);
assert.match(quoteApplication, /documentOrganizationIdentity/u);
assert.match(quoteApplication, /organizationPresentation/u);
assert.match(invoiceTransaction, /readTenantBranding/u);
assert.match(invoiceTransaction, /organizationPresentation:input\.organizationPresentation/u);
assert.match(invoiceDocuments, /issued\?\.organizationPresentation \?\? branding/u);
assert.match(migration, /organization\.configure/u);
assert.doesNotMatch(migration, /CREATE TABLE company_settings/u);
console.log("Organization settings adoption and shared document identity contracts passed.");
