import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { randomUUID,createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { requireV2M0CloneDatabaseUrl } from "../../infrastructure/persistence/cloneSafety.js";
import { reportNativeProductionProgress } from "../../scripts/native-owner-entry.mjs";

// Public source contract only. Counts are queried and asserted by scenario(),
// never substituted for observed values in a receipt.
const caseManifest = [
 {name:"owner create/create: commit winner, conflicting membership and loser ledger rollback",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:1,outputEvents:0,reworkCycles:0}},
 {name:"owner create/create: rollback winner permits reversed-order retry",kind:"concurrency",expectedCounts:{runs:1,allocations:2,activeMemberships:2,operationReceipts:1,outputEvents:0,reworkCycles:0}},
 {name:"concurrent same M0 identity replays exactly one owner result",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:1,outputEvents:0,reworkCycles:0}},
 {name:"concurrent same Run identity under distinct requests cannot duplicate members",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:2,outputEvents:0,reworkCycles:0}},
 {name:"same request changed payload rejects without effects",kind:"admission",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:1,outputEvents:0,reworkCycles:0}},
 {name:"duplicate Work input rejects before creation",kind:"admission",expectedCounts:{runs:0,allocations:0,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"raw duplicate same Run member is physically rejected",kind:"schema",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"raw conflicting Run membership is physically rejected",kind:"schema",expectedCounts:{runs:2,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"empty-parent state/INSERT serialized draft->cancelled (database derivation, not reopen authorization)",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"empty-parent state/INSERT serialized cancelled->ready (database derivation, not reopen authorization)",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"allocation UPDATE versus parent state takes parent before member tuple",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"parent state versus prior allocation UPDATE avoids opposing tuple cycle",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"permitted opposing owner hold/cancel transitions serialize",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"owner terminal release versus new owner creation serializes",kind:"concurrency",expectedCounts:{runs:2,allocations:2,activeMemberships:1,operationReceipts:2,outputEvents:0,reworkCycles:0}},
 {name:"multi-member terminal release and reversed Work creation use the complete ordered set",kind:"concurrency",expectedCounts:{runs:2,allocations:4,activeMemberships:2,operationReceipts:2,outputEvents:0,reworkCycles:0}},
 {name:"completed derivation includes unreleased fully produced members",kind:"schema",expectedCounts:{runs:1,allocations:1,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"cancelled derivation includes unreleased fully produced members",kind:"schema",expectedCounts:{runs:1,allocations:1,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"pre-start old/new Work updates serialize with ordered affected Work locks",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"allocation Run identity updates are rejected, not silently transferred",kind:"admission",expectedCounts:{runs:2,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"started allocation Work identity cannot be moved by raw UPDATE",kind:"admission",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"unsupported owner API reopen rejects without state mutation",kind:"admission",expectedCounts:{runs:1,allocations:0,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"historical active overlap makes forward invariant fail without silent de-duplication",kind:"schema",expectedCounts:{runs:0,allocations:0,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0,historicalAllocations:2}},
 {name:"pre-held Work lock releases on rollback before owner creation retry",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:1,outputEvents:0,reworkCycles:0}},
 {name:"pre-held Run lock releases on rollback before owner transition retry",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"pre-held Run then statement gate cycle produces rollback and safe owner retry",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"pre-held Work then statement gate cycle rolls back without membership drift",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"existing rework reservation guard under pre-held Work cycle rejects after rollback retry",kind:"concurrency",expectedCounts:{runs:1,allocations:1,activeMemberships:1,operationReceipts:0,outputEvents:0,reworkCycles:0}},
 {name:"runtime creation remains default disabled after all native scenarios",kind:"admission",expectedCounts:{runs:0,allocations:0,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0}},
] as const;

if(process.env.V2_L0_LANE_F_NATIVE_APPROVED!=="1")throw Error("Lane F native clone approval is required; no connection was opened.");
const url=requireV2M0CloneDatabaseUrl(),name=decodeURIComponent(new URL(url).pathname.slice(1));
if(!/(?:^|[-_])(test|testing|ci)(?:$|[-_])/i.test(name)||/(?:^|[-_])(dev|development|main|prod|production|live|shared|business)(?:$|[-_])/i.test(name)||name.includes("/")||process.env.V2_L0_LANE_F_APPROVED_NAME!==name)throw Error("Lane F must approve the exact safe native test database name; no connection was opened.");
const sourceRoot=fileURLToPath(new URL("../../../",import.meta.url));
const sourceCommit=execFileSync("git",["rev-parse","HEAD"],{cwd:sourceRoot,encoding:"utf8",timeout:5000}).trim();
const sourceCleanBefore=!execFileSync("git",["status","--porcelain","--untracked-files=normal"],{cwd:sourceRoot,encoding:"utf8",timeout:5000}).trim();
const expectedCommit=process.env.V2_L0_NATIVE_EXPECTED_COMMIT,githubSha=process.env.GITHUB_SHA;
for(const sha of [expectedCommit,githubSha])if(sha!==undefined&&(!/^[a-f0-9]{40}$/i.test(sha)||sourceCommit!==sha||!sourceCleanBefore))throw Error("Native proof requires the exact clean reviewed checkout; no connection was opened.");
reportNativeProductionProgress("setup");
const {Pool}=await import("pg");
const {PostgresProductionRunTransaction}=await import("../../infrastructure/production/postgresProductionRunTransaction.js");
const {PostgresProductionTransaction}=await import("../../infrastructure/production/postgresProductionTransaction.js");
const {ProductionRunApplicationService}=await import("../../src/modules/production/productionRunApplication.js");
const {productionRecoveryFixture}=await import("./productionRecoveryFixture.js");
const {brandedId}=await import("../../src/modules/shared/commercialValues.js");
const invariant=await readFile(new URL("./productionExclusiveMembership.request.sql",import.meta.url),"utf8");
const suiteHash=createHash("sha256").update(await readFile(new URL(import.meta.url))).update(invariant).digest("hex");
reportNativeProductionProgress("db-connect");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:10000,query_timeout:15000,statement_timeout:15000,lock_timeout:10000});
const a=await pool.connect().catch(error=>{reportNativeProductionProgress("db-connect",0,error);throw error;}),b=await pool.connect().catch(async error=>{reportNativeProductionProgress("db-connect",0,error);a.release();await pool.end();throw error;});
reportNativeProductionProgress("fixture");
const schema=`l0_production_test_${randomUUID().replaceAll("-","")}`;
let created=false,namespaceDropped=false,contender:Promise<unknown>|undefined;
type Counts={runs:number;allocations:number;activeMemberships:number;operationReceipts:number;outputEvents:number;reworkCycles:number;historicalAllocations?:number};
type CaseEvidence={name:string;kind:string;status:"pass";expectedCounts:Counts;measuredCounts:Counts;cleanupCounts:Counts;namespaceIdentifiers:string[];executingBackendPids:number[];contenders:"not_applicable"|{backendPidA:number;backendPidB:number;distinct:true;blockedWaits:{backendPid:number;waitEventType:"Lock";waitEvent:string|null}[]}};
const passed:string[]=[],caseEvidence:CaseEvidence[]=[],waits:{scenario:string;backendPid:number;waitEvent:string|null}[]=[];
let collectingExecution=false;
const executionSlots=new Set<"a"|"b">();
let casePids:{a:number;b:number}|undefined;
let caseNamespaces:string[]=[],caseSpecificCounts:Partial<Counts>={};
const removedNamespaces=new Set<string>();
for(const [client,slot] of [[a,"a"],[b,"b"]] as const){
 const original=client.query;
 client.query=function(this:typeof client,...args:unknown[]){
  const sql=typeof args[0]==="string"?args[0]:(args[0] as {text?:string}|undefined)?.text??"";
  // Record real mutation/row-lock sessions, never pg_stat_activity observers.
  if(collectingExecution&&/\b(?:INSERT|UPDATE|DELETE)\b|\bFOR\s+(?:NO\s+KEY\s+)?UPDATE\b|pg_advisory_xact_lock/i.test(sql))executionSlots.add(slot);
  return Reflect.apply(original,this,args);
 } as typeof client.query;
}
let scenarioName="",connectionPids:readonly number[]=[],serverVersion:number|undefined;
const org=brandedId<"OrganizationId">("org-a"),actor={organizationId:org,principalKind:"staff" as const,principalSubject:"actor-a",staffActorUserId:"actor-a"};
const ownerA=new PostgresProductionRunTransaction(a,true),ownerB=new PostgresProductionRunTransaction(b,true);
const create=async(owner:InstanceType<typeof PostgresProductionRunTransaction>,id:string,ids:string[],businessRequestId:string)=>{
 const reserved=await owner.reserve({...actor,operation:"production.run.create.v1",businessRequestId,payloadFingerprint:`exact:${ids.slice().sort().join(",")}`});
 if(reserved.kind==="replay")return reserved.resultJson;
 const members=await owner.lockCandidates(org,ids.map(id=>brandedId<"ProductionWorkId">(id)));
 const result=await owner.create({id:brandedId<"ProductionRunId">(id),stationKey:"roll",materialFingerprint:null,layoutMetadata:{},members,quantities:new Map(ids.map(id=>[id,5])),...actor});await owner.succeed(org,reserved.requestId,result);return result;
};
const rawRun=async(id:string,state="draft")=>a.query("INSERT INTO v2_production_runs(id,organization_id,station_key,state,created_principal_kind,created_principal_subject,completed_at,cancelled_at) VALUES($1,'org-a','roll',$2,'staff','actor-a',CASE WHEN $2='completed' THEN now() END,CASE WHEN $2='cancelled' THEN now() END)",[id,state]);
const memberSql="INSERT INTO v2_production_run_allocations(id,organization_id,production_run_id,production_work_id,allocated_quantity,artwork_assignment_id,artwork_file_id,artwork_identity_fingerprint,artwork_object_version,position) VALUES($1,'org-a',$2,$3,5,$4,$5,$6,'version-a',0)";
const rawMember=(client:typeof a,id:string,run:string,work="work-a")=>client.query(memberSql,[id,run,work,`art-${work}`,`file-${work}`,`sha256:${"a".repeat(64)}`]);
const begin=async()=>{await a.query("BEGIN");await b.query("BEGIN");};
const outcome=async<T>(work:Promise<T>)=>{try{return {value:await work,error:undefined};}catch(error){return {value:undefined,error};}};
const track=<T>(promise:Promise<T>)=>{contender=promise;void promise.catch(()=>undefined);return promise;};
const blocked=async()=>{assert.ok(casePids);const deadline=Date.now()+5000;while(Date.now()<deadline){await a.query("SELECT pg_stat_clear_snapshot()");const row=(await a.query<{wait_event_type:string|null;wait_event:string|null}>("SELECT wait_event_type,wait_event FROM pg_stat_activity WHERE pid=$1",[casePids.b])).rows[0];if(row?.wait_event_type==="Lock"){waits.push({scenario:scenarioName,backendPid:casePids.b,waitEvent:row.wait_event});return;}await new Promise(resolve=>setTimeout(resolve,10));}throw Error("Competing independent owner connection did not reach its real native lock.");};
const cleanRows=async()=>{await a.query("DELETE FROM v2_production_run_events;DELETE FROM v2_production_run_allocations;DELETE FROM v2_production_runs;DELETE FROM v2_operation_requests;DELETE FROM v2_production_attempts");};
const measureCounts=async():Promise<Counts>=>(await a.query<Counts>(`SELECT
 (SELECT count(*)::integer FROM v2_production_runs) runs,
 (SELECT count(*)::integer FROM v2_production_run_allocations) allocations,
 (SELECT count(*)::integer FROM v2_production_run_allocations WHERE membership_active) "activeMemberships",
 (SELECT count(*)::integer FROM v2_operation_requests) "operationReceipts",
 (SELECT count(*)::integer FROM v2_production_run_events WHERE event_kind IN ('good_output','waste_output')) "outputEvents",
 (SELECT count(*)::integer FROM v2_production_rework_cycles) "reworkCycles"`)).rows[0]!;
const zeroCounts:Counts={runs:0,allocations:0,activeMemberships:0,operationReceipts:0,outputEvents:0,reworkCycles:0};
const scenario=async(label:string,action:()=>Promise<void>)=>{
  const spec=caseManifest.find(item=>item.name===label);assert.ok(spec,"Every executed case must have an exact public manifest row");assert.ok(!passed.includes(label));
  reportNativeProductionProgress("scenario",passed.length+1);
 scenarioName=label;await cleanRows();executionSlots.clear();caseNamespaces=[schema];caseSpecificCounts={};
 casePids={a:(await a.query<{pid:number}>("SELECT pg_backend_pid() pid")).rows[0]!.pid,b:(await b.query<{pid:number}>("SELECT pg_backend_pid() pid")).rows[0]!.pid};
 assert.equal(casePids.a,connectionPids[0]);assert.equal(casePids.b,connectionPids[1]);
 let measured:Counts|undefined,cleanup:Counts|undefined;
 collectingExecution=true;
   try{await action();collectingExecution=false;if(passed.length===6)reportNativeProductionProgress("scenario",7,null,"post-action-counts");measured={...await measureCounts(),...caseSpecificCounts};assert.deepEqual(measured,spec.expectedCounts);
    const bad=(await a.query<{n:number}>("SELECT count(*)::integer n FROM v2_production_run_allocations x JOIN v2_production_runs r ON r.organization_id=x.organization_id AND r.id=x.production_run_id WHERE x.membership_active IS DISTINCT FROM (x.released_at IS NULL AND r.state IN ('draft','ready','active','held'))")).rows[0]!.n;assert.equal(bad,0);
    if(passed.length===6)reportNativeProductionProgress("scenario",7,null,"cleanup-evidence");
  }catch(error){reportNativeProductionProgress("scenario",passed.length+1,error);throw error;
  }finally{collectingExecution=false;await a.query("ROLLBACK");if(contender)await contender.catch(()=>undefined);contender=undefined;await b.query("ROLLBACK");await cleanRows();cleanup=await measureCounts();assert.deepEqual(cleanup,zeroCounts);}
 assert.ok(measured&&cleanup);const observed=waits.filter(wait=>wait.scenario===label);
 const executingBackendPids=[...executionSlots].sort().map(slot=>casePids![slot]);assert.ok(executingBackendPids.length>0,"Case must execute on a measured backend");
 if(spec.kind==="concurrency"){assert.ok(executionSlots.has("a")&&executionSlots.has("b"));assert.notEqual(casePids.a,casePids.b);assert.ok(observed.length>0);}
 caseEvidence.push({name:label,kind:spec.kind,status:"pass",expectedCounts:spec.expectedCounts,measuredCounts:measured,cleanupCounts:cleanup,namespaceIdentifiers:[...caseNamespaces],executingBackendPids,contenders:spec.kind!=="concurrency"?"not_applicable":{backendPidA:casePids.a,backendPidB:casePids.b,distinct:true,blockedWaits:observed.map(wait=>({backendPid:wait.backendPid,waitEventType:"Lock",waitEvent:wait.waitEvent}))}});
  passed.push(label);
  reportNativeProductionProgress("passed",passed.length);
};
try{
  try{
  const ia=(await a.query<{pid:number;db:string}>("SELECT pg_backend_pid() pid,current_database() db")).rows[0]!,ib=(await b.query<{pid:number;db:string}>("SELECT pg_backend_pid() pid,current_database() db")).rows[0]!;
  if(ia.db!==name||ib.db!==name)throw Error("Native target does not match approved clone; no schema created.");assert.notEqual(ia.pid,ib.pid);connectionPids=[ia.pid,ib.pid];serverVersion=Number((await a.query("SHOW server_version_num")).rows[0].server_version_num);assert.ok(serverVersion>=160000);
   await a.query(`CREATE SCHEMA ${schema}`);created=true;await a.query(`SET search_path TO ${schema},public`);await b.query(`SET search_path TO ${schema},public`);await productionRecoveryFixture(a,invariant);
  }catch(error){reportNativeProductionProgress("fixture",0,error);throw error;}
 await scenario("owner create/create: commit winner, conflicting membership and loser ledger rollback",async()=>{await begin();await create(ownerA,"a",["work-a"],"a");const denied=track(assert.rejects(()=>create(ownerB,"b",["work-a"],"b"),/already belongs/));await blocked();await a.query("COMMIT");await denied;await b.query("ROLLBACK");assert.equal((await a.query("SELECT count(*)::integer n FROM v2_production_runs")).rows[0].n,1);assert.equal((await a.query("SELECT count(*)::integer n FROM v2_operation_requests WHERE business_request_id='b'")).rows[0].n,0);});
 await scenario("owner create/create: rollback winner permits reversed-order retry",async()=>{await begin();await create(ownerA,"a",["work-b","work-a"],"a");const winner=track(create(ownerB,"b",["work-a","work-b"],"b"));await blocked();await a.query("ROLLBACK");await winner;await b.query("COMMIT");assert.equal((await a.query("SELECT count(*)::integer n FROM v2_production_run_allocations WHERE membership_active")).rows[0].n,2);});
 await scenario("concurrent same M0 identity replays exactly one owner result",async()=>{await begin();const first=await create(ownerA,"a",["work-a"],"same");const replay=track(create(ownerB,"alias",["work-a"],"same"));await blocked();await a.query("COMMIT");assert.deepEqual(await replay,JSON.parse(JSON.stringify(first)));await b.query("COMMIT");assert.equal((await a.query("SELECT count(*)::integer n FROM v2_production_runs")).rows[0].n,1);});
 await scenario("concurrent same Run identity under distinct requests cannot duplicate members",async()=>{await begin();await create(ownerA,"same-run",["work-a"],"a");const second=track(create(ownerB,"same-run",["work-a"],"b"));await blocked();await a.query("COMMIT");await second;await b.query("COMMIT");assert.equal((await a.query("SELECT count(*)::integer n FROM v2_production_run_allocations")).rows[0].n,1);});
 await scenario("same request changed payload rejects without effects",async()=>{await a.query("BEGIN");await create(ownerA,"a",["work-a"],"same");await a.query("COMMIT");await b.query("BEGIN");await assert.rejects(()=>create(ownerB,"b",["work-b"],"same"),/different payload/);await b.query("ROLLBACK");});
  await scenario("duplicate Work input rejects before creation",async()=>{
   const calls:string[]=[];let reservedRows:number|undefined;
   // Observe calls while forwarding validation and reservation to the actual owner.
   const observedOwner=new Proxy(ownerA,{get(target,key){const value=Reflect.get(target,key);if(key==="reserve"||key==="lockCandidates"||key==="create"||key==="succeed")return (...args:unknown[])=>{calls.push(key);return Reflect.apply(value,target,args);};return value;}});
   const service=new ProductionRunApplicationService({transaction:async work=>{
    await a.query("BEGIN");calls.push("BEGIN");
    try{const result=await work(observedOwner);await a.query("COMMIT");calls.push("COMMIT");return result;}
    catch(error){calls.push("rejection");try{reservedRows=(await a.query<{n:number}>("SELECT count(*)::integer n FROM v2_operation_requests")).rows[0]!.n;}finally{await a.query("ROLLBACK");calls.push("ROLLBACK");}throw error;}
   }});
   const businessRequestId=randomUUID();
   const result=await service.create({organizationId:org,operationId:randomUUID(),businessRequest:{id:businessRequestId,payloadFingerprint:"native-duplicate-input"},principal:{kind:"staff",organizationId:org,userId:"actor-a",authority:{membershipId:"native",capabilities:["production.run.create"]}}},{businessRequestId,stationKey:"roll",members:[{productionWorkId:brandedId<"ProductionWorkId">("work-a"),quantity:5},{productionWorkId:brandedId<"ProductionWorkId">("work-a"),quantity:5}]});
   assert.equal(result.ok,false);if(result.ok)throw Error("Duplicate Work input unexpectedly created a Run.");
   assert.equal(result.error.code,"VALIDATION_ERROR");assert.equal(result.error.publicMessage,"A Production work item cannot be selected twice.");
   assert.deepEqual(calls,["BEGIN","reserve","rejection","ROLLBACK"]);assert.equal(reservedRows,1,"The real reservation is visible before rollback, not retained afterward.");
   assert.deepEqual(await measureCounts(),zeroCounts);
  });
  await scenario("raw duplicate same Run member is physically rejected",async()=>{reportNativeProductionProgress("scenario",7,null,"raw-parent-insert");await rawRun("r");reportNativeProductionProgress("scenario",7,null,"first-member-insert");await rawMember(a,"x","r");reportNativeProductionProgress("scenario",7,null,"duplicate-insert");await assert.rejects(()=>rawMember(b,"y","r"),error=>{reportNativeProductionProgress("scenario",7,error,"duplicate-rejection");return (error as {code:string}).code==="23505";});});
 await scenario("raw conflicting Run membership is physically rejected",async()=>{await rawRun("r");await rawRun("s");await rawMember(a,"x","r");await assert.rejects(()=>rawMember(b,"y","s"),error=>(error as {code:string}).code==="23505");});
 for(const [from,to,active] of [["draft","cancelled",false],["cancelled","ready",true]] as const)await scenario(`empty-parent state/INSERT serialized ${from}->${to} (database derivation, not reopen authorization)`,async()=>{await rawRun("r",from);await begin();await a.query("UPDATE v2_production_runs SET state=$1,cancelled_at=CASE WHEN $1='cancelled' THEN now() ELSE cancelled_at END WHERE id='r'",[to]);const insertion=track(rawMember(b,"x","r"));await blocked();await a.query("COMMIT");await insertion;await b.query("COMMIT");assert.equal((await a.query("SELECT membership_active FROM v2_production_run_allocations WHERE id='x'")).rows[0].membership_active,active);});
 await scenario("allocation UPDATE versus parent state takes parent before member tuple",async()=>{await rawRun("r","active");await rawMember(a,"x","r");await begin();await ownerA.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"});const update=track(b.query("UPDATE v2_production_run_allocations SET released_at=now() WHERE id='x'"));await blocked();await a.query("COMMIT");await update;await b.query("COMMIT");assert.equal((await a.query("SELECT membership_active FROM v2_production_run_allocations WHERE id='x'")).rows[0].membership_active,false);});
 await scenario("parent state versus prior allocation UPDATE avoids opposing tuple cycle",async()=>{await rawRun("r","active");await rawMember(a,"x","r");await begin();await a.query("UPDATE v2_production_run_allocations SET released_at=now() WHERE id='x'");const state=track(ownerB.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"}));await blocked();await a.query("COMMIT");await state;await b.query("COMMIT");});
 await scenario("permitted opposing owner hold/cancel transitions serialize",async()=>{await rawRun("r","active");await rawMember(a,"x","r");await begin();await ownerA.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"});const cancel=track(ownerB.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"cancelled",transition:"cancel",reason:"Native fixture"}));await blocked();await a.query("COMMIT");await cancel;await b.query("COMMIT");assert.equal((await a.query("SELECT state FROM v2_production_runs WHERE id='r'")).rows[0].state,"cancelled");});
 await scenario("owner terminal release versus new owner creation serializes",async()=>{await a.query("BEGIN");await create(ownerA,"a",["work-a"],"a");await a.query("COMMIT");await begin();await ownerA.transition({...actor,productionRunId:brandedId<"ProductionRunId">("a"),state:"cancelled",transition:"cancel",reason:"Native fixture"});const successor=track(create(ownerB,"b",["work-a"],"b"));await blocked();await a.query("COMMIT");await successor;await b.query("COMMIT");assert.equal((await a.query("SELECT count(*)::integer n FROM v2_production_run_allocations WHERE membership_active")).rows[0].n,1);});
 await scenario("multi-member terminal release and reversed Work creation use the complete ordered set",async()=>{await a.query("BEGIN");await create(ownerA,"a",["work-a","work-b"],"a");await a.query("COMMIT");await begin();await ownerA.transition({...actor,productionRunId:brandedId<"ProductionRunId">("a"),state:"cancelled",transition:"cancel",reason:"Native fixture"});const successor=track(create(ownerB,"b",["work-b","work-a"],"b"));await blocked();await a.query("COMMIT");await successor;await b.query("COMMIT");assert.equal((await a.query("SELECT count(*)::integer n FROM v2_production_run_allocations WHERE membership_active")).rows[0].n,2);});
 for(const terminal of ["completed","cancelled"] as const)await scenario(`${terminal} derivation includes unreleased fully produced members`,async()=>{await rawRun("r","active");await rawMember(a,"x","r");await a.query("UPDATE v2_production_run_allocations SET good_quantity=allocated_quantity WHERE id='x'");await a.query("UPDATE v2_production_runs SET state=$1,completed_at=CASE WHEN $1='completed' THEN now() ELSE completed_at END,cancelled_at=CASE WHEN $1='cancelled' THEN now() ELSE cancelled_at END WHERE id='r'",[terminal]);assert.equal((await a.query("SELECT membership_active FROM v2_production_run_allocations WHERE id='x'")).rows[0].membership_active,false);});
 await scenario("pre-start old/new Work updates serialize with ordered affected Work locks",async()=>{await rawRun("r");await rawMember(a,"x","r");await begin();await a.query("UPDATE v2_production_run_allocations SET production_work_id='work-b' WHERE id='x'");const move=track(b.query("UPDATE v2_production_run_allocations SET production_work_id='work-a' WHERE id='x'"));await blocked();await a.query("COMMIT");await move;await b.query("COMMIT");assert.equal((await a.query("SELECT production_work_id FROM v2_production_run_allocations WHERE id='x'")).rows[0].production_work_id,"work-a");});
 await scenario("allocation Run identity updates are rejected, not silently transferred",async()=>{await rawRun("r");await rawRun("s");await rawMember(a,"x","r");await assert.rejects(()=>b.query("UPDATE v2_production_run_allocations SET production_run_id='s' WHERE id='x'"),/identity is immutable/);});
 await scenario("started allocation Work identity cannot be moved by raw UPDATE",async()=>{await rawRun("r","active");await rawMember(a,"x","r");await assert.rejects(()=>b.query("UPDATE v2_production_run_allocations SET production_work_id='work-b' WHERE id='x'"),/work identity is immutable/);});
 await scenario("unsupported owner API reopen rejects without state mutation",async()=>{await rawRun("r","cancelled");const service=new ProductionRunApplicationService({transaction:async work=>{await a.query("BEGIN");try{const result=await work(ownerA);await a.query("COMMIT");return result;}catch(error){await a.query("ROLLBACK");throw error;}}});const result=await service.transition({organizationId:org,operationId:"native-reopen",businessRequest:{id:"reopen",payloadFingerprint:"unused"},principal:{kind:"staff",organizationId:org,userId:"actor-a",authority:{membershipId:"native",capabilities:["production.run.execute"]}}},{businessRequestId:"reopen",productionRunId:brandedId<"ProductionRunId">("r"),transition:"ready"});assert.equal(result.ok,false);assert.equal((await a.query("SELECT state FROM v2_production_runs WHERE id='r'")).rows[0].state,"cancelled");});
 await scenario("historical active overlap makes forward invariant fail without silent de-duplication",async()=>{const old=`l0_production_history_${randomUUID().replaceAll("-","")}`;caseNamespaces.push(old);await a.query(`CREATE SCHEMA ${old}`);try{await a.query(`SET search_path TO ${old},public`);await productionRecoveryFixture(a,"");await rawRun("r");await rawRun("s");await rawMember(a,"x","r");await rawMember(a,"y","s");await a.query("BEGIN");await assert.rejects(()=>a.query(invariant),error=>(error as {code:string}).code==="23505");await a.query("ROLLBACK");caseSpecificCounts.historicalAllocations=(await a.query<{n:number}>("SELECT count(*)::integer n FROM v2_production_run_allocations")).rows[0]!.n;assert.equal(caseSpecificCounts.historicalAllocations,2);}finally{await a.query("ROLLBACK");await a.query(`SET search_path TO ${schema},public`);await a.query(`DROP SCHEMA ${old} CASCADE`);assert.equal((await a.query<{removed:boolean}>("SELECT to_regnamespace($1) IS NULL removed",[old])).rows[0]!.removed,true);removedNamespaces.add(old);}});
 await scenario("pre-held Work lock releases on rollback before owner creation retry",async()=>{await begin();await a.query("SELECT id FROM v2_production_works WHERE id='work-a' FOR UPDATE");const owner=track(create(ownerB,"after-work-lock",["work-a"],"after-work-lock"));await blocked();await a.query("ROLLBACK");await owner;await b.query("COMMIT");assert.equal((await a.query("SELECT count(*)::integer n FROM v2_production_run_allocations WHERE membership_active")).rows[0].n,1);});
 await scenario("pre-held Run lock releases on rollback before owner transition retry",async()=>{await rawRun("r","active");await rawMember(a,"x","r");await begin();await a.query("SELECT id FROM v2_production_runs WHERE id='r' FOR UPDATE");const owner=track(ownerB.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"}));await blocked();await a.query("ROLLBACK");await owner;await b.query("COMMIT");assert.equal((await a.query("SELECT state FROM v2_production_runs WHERE id='r'")).rows[0].state,"held");});
 await scenario("pre-held Run then statement gate cycle produces rollback and safe owner retry",async()=>{await rawRun("r","active");await rawMember(a,"x","r");await begin();await a.query("SELECT id FROM v2_production_runs WHERE id='r' FOR UPDATE");const other=track(outcome(ownerB.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"})));await blocked();const first=await outcome(a.query("UPDATE v2_production_runs SET revision=revision+1 WHERE id='r'"));if(first.error)await a.query("ROLLBACK");const second=await other;assert.equal([first.error,second.error].filter(error=>(error as {code?:string}|undefined)?.code==="40P01").length,1);await a.query("ROLLBACK");await b.query("ROLLBACK");await b.query("BEGIN");await ownerB.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"});await b.query("COMMIT");assert.equal((await a.query("SELECT state FROM v2_production_runs WHERE id='r'")).rows[0].state,"held");});
 await scenario("pre-held Work then statement gate cycle rolls back without membership drift",async()=>{await rawRun("r","active");await rawMember(a,"x","r");await begin();await a.query("SELECT id FROM v2_production_works WHERE id='work-a' FOR UPDATE");const other=track(outcome(ownerB.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"})));await blocked();const first=await outcome(a.query("UPDATE v2_production_run_allocations SET position=position WHERE id='x'"));if(first.error)await a.query("ROLLBACK");const second=await other;assert.equal([first.error,second.error].filter(error=>(error as {code?:string}|undefined)?.code==="40P01").length,1);await a.query("ROLLBACK");await b.query("ROLLBACK");await b.query("BEGIN");await ownerB.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"});await b.query("COMMIT");});
 await scenario("existing rework reservation guard under pre-held Work cycle rejects after rollback retry",async()=>{await rawRun("r","active");await rawMember(a,"x","r");await begin();await a.query("SELECT id FROM v2_production_works WHERE id='work-a' FOR UPDATE");const other=track(outcome(ownerB.transition({...actor,productionRunId:brandedId<"ProductionRunId">("r"),state:"held",transition:"hold"})));await blocked();const rework=new PostgresProductionTransaction(a);const input={...actor,productionWorkId:brandedId<"ProductionWorkId">("work-a"),reason:"Native existing rework lock interaction",recordedGoodQuantity:0,recordedWasteQuantity:0};const first=await outcome(rework.createReworkSuccessor(input));if(first.error)await a.query("ROLLBACK");const second=await other;assert.equal([first.error,second.error].filter(error=>(error as {code?:string}|undefined)?.code==="40P01").length,1);await a.query("ROLLBACK");await b.query("ROLLBACK");await a.query("BEGIN");await assert.rejects(()=>rework.createReworkSuccessor(input),/Release the active Production Run member/);await a.query("ROLLBACK");assert.equal((await a.query("SELECT count(*)::integer n FROM v2_production_rework_cycles")).rows[0].n,0,"no new lineage or quantity policy is exercised");});
 await scenario("runtime creation remains default disabled after all native scenarios",async()=>{await a.query("BEGIN");const members=await ownerA.lockCandidates(org,[brandedId<"ProductionWorkId">("work-a")]);await assert.rejects(()=>new PostgresProductionRunTransaction(a).create({id:brandedId<"ProductionRunId">("off"),stationKey:"roll",materialFingerprint:null,layoutMetadata:{},members,quantities:new Map([["work-a",5]]),...actor}),/disabled/);await a.query("ROLLBACK");});
}finally{try{collectingExecution=false;await a.query("ROLLBACK");if(contender)await contender.catch(()=>undefined);await b.query("ROLLBACK");if(created){await a.query(`DROP SCHEMA ${schema} CASCADE`);namespaceDropped=(await a.query<{removed:boolean}>("SELECT to_regnamespace($1) IS NULL removed",[schema])).rows[0]!.removed;assert.equal(namespaceDropped,true);removedNamespaces.add(schema);}}finally{a.release();b.release();await pool.end();}}
assert.equal(caseManifest.length,28);assert.deepEqual(passed,caseManifest.map(item=>item.name));assert.equal(caseEvidence.length,28);
const sourceCommitAfter=execFileSync("git",["rev-parse","HEAD"],{cwd:sourceRoot,encoding:"utf8",timeout:5000}).trim();
const sourceCleanAfter=!execFileSync("git",["status","--porcelain","--untracked-files=normal"],{cwd:sourceRoot,encoding:"utf8",timeout:5000}).trim();
assert.equal(sourceCommitAfter,sourceCommit);assert.equal(sourceCleanAfter,sourceCleanBefore);
const caseReceipts=caseEvidence.map(item=>{const namespaces=item.namespaceIdentifiers.map(identifier=>{assert.ok(removedNamespaces.has(identifier));return {identifier,removed:true as const};});return {...item,namespaces};});
console.log(JSON.stringify({receiptVersion:1,lane:"production",gate:"OPS12-native",suite:"production-exclusive-membership",runner:"tsx",status:"pass",sourceCommit,GITHUB_SHA:githubSha??null,sourceCommitAfter,sourceCleanBefore,sourceCleanAfter,serverVersionNum:serverVersion,suiteHash,manifest:caseManifest,passedCases:caseReceipts.length,failedCases:0,skippedCases:0,pendingCases:0,cases:caseReceipts,runtimeCreationEnabled:false}));
