import { describe, expect, test } from "@jest/globals";
import { readFile } from "node:fs/promises";
import { PostgresProductVersionLifecycleReader, createInitialProductDraftTree } from "../../infrastructure/products/postgresProductVersionLifecycle";
import { optionTreeV2Schema } from "../../../shared/optionTreeV2";
import { validateOptionTreeV2 } from "../../../shared/optionTreeV2Runtime";

const version=(id:string,status:"ACTIVE"|"DRAFT"|"DEPRECATED"|"ARCHIVED",updated:string)=>({id,status,schema_version:2,tree_json:{nodes:{}},created_at:new Date("2026-08-01T00:00:00.000Z"),updated_at:new Date(updated),published_at:status==="ACTIVE"?new Date("2026-08-02T00:00:00.000Z"):null});
describe("P2 Product version lifecycle read",()=>{
  test("initializes a structurally valid Draft tree for a new Product identity",()=>{
    const tree=createInitialProductDraftTree("New Product");
    expect(validateOptionTreeV2(tree)).toEqual({ok:true});
    expect(optionTreeV2Schema.safeParse(tree).success).toBe(true);
    expect(tree.rootNodeIds).toEqual(["product_configuration"]);
    expect(tree.nodes.product_configuration).toMatchObject({id:"product_configuration",kind:"group"});
  });
  test("persists a new identity with a single text type for name and description",async()=>{
    const source=await readFile("v2/infrastructure/products/postgresProductVersionLifecycle.ts","utf8");
    const create=source.slice(source.indexOf("async createProductWithInitialDraft"),source.indexOf("async succeed"));
    expect(create).toContain("VALUES($1,$2,$3::text,$3::text,FALSE");
  });
  test("is tenant-scoped, bounded, deterministic, and separates Active, Draft, and history",async()=>{const calls:any[]=[];const reader=new PostgresProductVersionLifecycleReader({query:async<T>(text:string,values?:readonly unknown[])=>{calls.push({text,values});return {rows:(text.startsWith("SELECT pbv2")?[{pbv2_active_tree_version_id:"active-a"}]:[version("draft-a","DRAFT","2026-08-04T00:00:00.000Z"),version("active-a","ACTIVE","2026-08-03T00:00:00.000Z"),version("old-a","DEPRECATED","2026-08-02T00:00:00.000Z")])as T[]};}}as any);await expect(reader.read("org-a","product-a")).resolves.toMatchObject({active:{status:"active",editable:false},draft:{status:"draft",editable:true},history:[{status:"deprecated"}],historyLimit:25,historyHasMore:false,canCreateDraft:false});expect(calls[0].text).toContain("organization_id=$1 AND id=$2");expect(calls[0].values).toEqual(["org-a","product-a"]);expect(calls[1].text).toContain("organization_id=$1 AND product_id=$2");expect(calls[1].text).toContain("ORDER BY updated_at DESC,id DESC LIMIT $3");expect(calls[1].values).toEqual(["org-a","product-a",28]);});
  test("includes the pointed Active version when it is older than the bounded history window",async()=>{const calls:any[]=[];const reader=new PostgresProductVersionLifecycleReader({query:async<T>(_text:string,values?:readonly unknown[])=>{calls.push(values);if(calls.length===1)return {rows:[{pbv2_active_tree_version_id:"active-old"}]as T[]};if(calls.length===2)return {rows:[version("draft-current","DRAFT","2026-08-04T00:00:00.000Z"),version("new-history","DEPRECATED","2026-08-03T00:00:00.000Z")]as T[]};return {rows:[version("active-old","ACTIVE","2026-07-01T00:00:00.000Z")]as T[]};}}as any);await expect(reader.read("org-a","product-a")).resolves.toMatchObject({active:{productVersionId:"active-old",status:"active"},draft:{productVersionId:"draft-current",status:"draft"},canCreateDraft:false});expect(calls[2]).toEqual(["org-a","product-a","active-old"]);});
  test("returns a truthful empty lifecycle for a Product with no PBV2 configuration",async()=>{const reader=new PostgresProductVersionLifecycleReader({query:async<T>(text:string)=>({rows:(text.startsWith("SELECT pbv2")?[{pbv2_active_tree_version_id:null}]:[])as T[]})}as any);await expect(reader.read("org-a","product-a")).resolves.toEqual({history:[],historyLimit:25,historyHasMore:false,canCreateDraft:false});});
  test("serializes draft creation on the Product row and never updates the Active pointer",async()=>{const source=await readFile("v2/infrastructure/products/postgresProductVersionLifecycle.ts","utf8");const create=source.slice(source.indexOf("async createDraftFromActive"),source.indexOf("async succeed"));expect(create).toContain("FROM products WHERE organization_id=$1 AND id=$2 FOR UPDATE");expect(create).toContain("status='ACTIVE' FOR UPDATE");expect(create).toContain("status='DRAFT' ORDER BY updated_at DESC,id DESC LIMIT 1 FOR UPDATE");expect(create).toContain("INSERT INTO pbv2_tree_versions");expect(create).not.toMatch(/UPDATE products/);expect(create).not.toMatch(/UPDATE pbv2_tree_versions/);});
  test("locks and patches only the current Draft General section",async()=>{const source=await readFile("v2/infrastructure/products/postgresProductVersionLifecycle.ts","utf8");const update=source.slice(source.indexOf("async updateDraftGeneral"),source.indexOf("async auditDraftGeneral"));expect(update).toContain("FROM products WHERE organization_id=$1 AND id=$2 FOR UPDATE");expect(update).toContain("AND d.id=$3 FOR UPDATE");expect(update).toContain("row.status !== \"DRAFT\"");expect(update).toContain("UPDATE pbv2_tree_versions SET tree_json");expect(update).not.toMatch(/UPDATE products/);});
});
