import assert from "node:assert/strict";
import {readFileSync} from "node:fs";

const queue=readFileSync("v2/infrastructure/communications/proofEmailDeliveryQueue.ts","utf8");
const portal=readFileSync("v2/infrastructure/proofing/postgresPortalProofRead.ts","utf8");
const migration=readFileSync("server/db/migrations_v2/0259_v2_customer_proof_delivery.sql","utf8");
const proofing=readFileSync("v2/infrastructure/proofing/postgresProofingTransaction.ts","utf8");
const recipientAccess=readFileSync("v2/infrastructure/authorization/postgresProofRecipientAccess.ts","utf8");
assert.match(queue,/FOR UPDATE SKIP LOCKED/u);
assert.match(queue,/provider_attempted_at IS NOT NULL/u);
assert.match(queue,/state='ambiguous'/u);
assert.match(queue,/status>=500\)return"ambiguous"/u);
assert.match(queue,/Review Proof/u);
assert.match(queue,/\/portal\/setup\?token=/u);
assert.doesNotMatch(queue,/object_key|storage_provider/u);
assert.match(portal,/d\.customer_id=\$2/u);
assert.match(portal,/v\.issued_at IS NOT NULL/u);
assert.match(portal,/sequence<row\.latest_sequence/u);
assert.match(portal,/cache|viewUrl/u);
assert.match(migration,/UNIQUE \(organization_id, proof_version_id\)/u);
assert.match(migration,/proof_response\.outcome='revision_requested'/u,"Only a canonical request for changes may unlock corrected artwork");
assert.match(migration,/Proof-bound artwork can be replaced only after the current Proof requests changes/u);
assert.match(proofing,/new PostgresProofRecipientAccess\(this.client\).ensureForProofIssue\(input\)/u,"Auth participates through its named operation on the existing Proof transaction client");
assert.doesNotMatch(proofing,/(?:INSERT INTO|UPDATE) (?:customer_portal_access|v2_portal_permission_set_assignments|v2_permission_organization_state)/u,"Proofing owns delivery intent, not access or permission writes");
assert.match(proofing,/INSERT INTO v2_proof_delivery_jobs/u);
assert.match(recipientAccess,/INSERT INTO v2_portal_permission_set_assignments/u);
assert.match(recipientAccess,/UPDATE v2_permission_organization_state/u);
assert.doesNotMatch(recipientAccess,/(?:BEGIN|COMMIT|ROLLBACK|\.connect\()/u,"The Auth operation must not start a separate transaction");
console.log("V2 proof delivery reliability and portal scope contracts passed.");
