import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { quickBooksQueueFailureState, v2QuickBooksQueueWorkerEnabled } from "../../infrastructure/accounting/quickBooksQueuePolicy.js";

const migration = readFileSync(resolve("server/db/migrations_v2/0248_v2_quickbooks_billing_queue.sql"), "utf8");
const refundMigration = readFileSync(resolve("server/db/migrations_v2/0249_v2_quickbooks_refund_projection.sql"), "utf8");
const liveRevisionMigration = readFileSync(resolve("server/db/migrations_v2/0251_v2_quickbooks_live_invoice_revisions.sql"), "utf8");
const queue = readFileSync(resolve("v2/infrastructure/accounting/quickBooksBillingQueue.ts"), "utf8");
const provider = readFileSync(resolve("server/quickbooksService.ts"), "utf8");
const invoice = readFileSync(resolve("v2/infrastructure/billing/postgresBillingInvoiceTransaction.ts"), "utf8");
const payment = readFileSync(resolve("v2/infrastructure/billing/postgresBillingPaymentsTransaction.ts"), "utf8");
const routes = readFileSync(resolve("v2/src/interfaces/http/quickBooksIntegrationRoutes.ts"), "utf8");
const financeRoutes = readFileSync(resolve("v2/src/interfaces/http/financeRoutes.ts"), "utf8");
const consoleUi = readFileSync(resolve("v2/ui/src/QuickBooksSettingsWorkspace.tsx"), "utf8");
const settingsUi = readFileSync(resolve("v2/ui/src/SettingsWorkspace.tsx"), "utf8");
const financeUi = readFileSync(resolve("v2/ui/src/FinanceWorkspace.tsx"), "utf8");
const historical = readFileSync(resolve("shared/quickBooksHistoricalNumbering.ts"), "utf8");

assert.match(migration, /v2_quickbooks_sync_jobs/);
assert.match(migration, /UNIQUE \(organization_id, subject_kind, subject_id\)/);
assert.match(queue, /FOR UPDATE SKIP LOCKED/);
assert.match(queue, /lease_expires_at < now\(\)/);
assert.match(queue, /quickBooksInvoiceProjectionFingerprint/);
assert.match(queue, /projection_fingerprint/);
assert.match(queue, /projection_version/);
assert.match(queue, /projection_json/);
assert.match(queue, /storedProjectionLines/);
assert.doesNotMatch(queue, /JOIN v2_billing_invoice_checkpoints/);
assert.doesNotMatch(queue, /invoice_state='issued'/);
assert.match(queue, /v2_billing_payments/);
assert.match(queue, /v2_billing_refunds/);
assert.match(queue, /refund_credit_memo/);
assert.match(queue, /refund_disbursement/);
assert.match(queue, /v2_quickbooks_refund_sync_workflows/);
assert.match(queue, /CASE WHEN \$5::boolean THEN now\(\) ELSE NULL END/);
assert.match(queue, /enqueueInvoices/);
assert.match(queue, /Select between 1 and 100 eligible V2 Order-backed Invoices/);
assert.match(queue, /async enqueueFinancialFacts/);
assert.match(queue, /Select between 1 and 100 eligible V2 Payments or Refunds/);
assert.match(queue, /async unsyncedFinancialFacts/);
assert.match(queue, /refund_disbursement/);
assert.match(queue, /async retryPayment\(organizationId: string, invoiceId: string, paymentId: string\)/);
assert.match(queue, /state IN \('blocked','retry'\)/);
assert.match(queue, /requires provider reconciliation before it can be retried/);
assert.match(queue, /quickBooksCredentialInterruptedRecoveryEligible/);
assert.match(queue, /failed to get valid access token/);
assert.match(queue, /async resumeAfterCredentialReauth/);
assert.match(queue, /already synchronized/);
assert.match(routes, /\/queue\/:subjectKind\/:subjectId\/retry/);
assert.match(routes, /quickBooksSync\.retry\(organizationId,kind,req\.params\.subjectId\)/);
assert.match(routes, /\/queue\/:subjectKind\/:subjectId\/reconcile/);
assert.match(routes, /quickBooksSync\.resumeAfterCredentialReauth\(organizationId,kind,req\.params\.subjectId\)/);
assert.match(queue, /id = ANY\(\$2::varchar\[\]\)/);
assert.doesNotMatch(queue, /id = ANY\(\$2::uuid\[\]\)/);
assert.match(queue, /SET state=\$2::varchar/);
assert.match(queue, /\$2::varchar='succeeded'/);
assert.match(queue, /state === "uncertain"/);
assert.match(queue, /enqueueV2QuickBooksAutoSync/);
assert.match(queue, /\{preferences,quickBooks,autoSync\}/);
assert.match(queue, /COALESCE\(settings #>>/);
assert.match(queue, /COALESCE\(i\.invoice_display_number,d\.display_number\)/);
assert.match(queue, /l\.projection_version IS DISTINCT FROM i\.synchronization_version/);
assert.match(queue, /existingInvoice\?\.projectionFingerprint === fingerprint/);
assert.match(queue, /stale queue job intentionally reads the newest live V2 projection/);
assert.match(queue, /invoiceLink\.projectionVersion !== row\.synchronization_version/);
assert.match(invoice, /enqueueV2QuickBooksAutoSync\(this\.client,input\.organizationId,"invoice",input\.invoiceId\)/);
const draftInvoice = readFileSync(resolve("v2/infrastructure/billing/postgresBillingDraftInvoiceTransaction.ts"), "utf8");
assert.match(draftInvoice, /enqueueV2QuickBooksAutoSync\(this\.client, input\.organizationId, "invoice", row\.id\)/);
assert.match(draftInvoice, /enqueueV2QuickBooksAutoSync\(this\.client, input\.organizationId, "invoice", draft\.id\)/);
assert.match(payment, /enqueueV2QuickBooksAutoSync\(this\.client,input\.organizationId,"payment",id\)/);
assert.match(payment, /enqueueV2QuickBooksAutoSync\(this\.client,input\.organizationId,"refund",id\)/);
assert.match(provider, /syncV2InvoiceToQuickBooks/);
assert.match(provider, /quickBooksInvoiceId: string/);
assert.match(provider, /QUICKBOOKS_INVOICE_UPDATE_CONFLICT/);
assert.match(provider, /POST", "\/invoice", \{ \.\.\.payload, Id/);
assert.match(provider, /syncV2PaymentToQuickBooks/);
assert.match(provider, /function shouldLatchQuickBooksReauth/);
assert.match(provider, /refresh token is invalid/);
assert.match(provider, /await latchQuickBooksNeedsReauth\(\{ organizationId: orgId, connection, error \}\)/);
assert.match(provider, /const v2PaymentReference = \(paymentId: string\) => `PHV2-\$\{crypto\.createHash/);
assert.match(provider, /const paymentRefNum = v2PaymentReference\(input\.paymentId\)/);
assert.doesNotMatch(provider, /const paymentRefNum = `PHV2-\$\{input\.paymentId\}`/);
assert.match(provider, /syncV2RefundCreditMemoToQuickBooks/);
assert.match(provider, /syncV2RefundDisbursementToQuickBooks/);
assert.match(provider, /\/creditmemo/);
assert.match(provider, /\/purchase/);
assert.match(provider, /PaymentType: "Check"/);
assert.match(provider, /AccountRef: \{ value: bankAccountId \}/);
assert.match(provider, /FROM Purchase WHERE DocNumber/);
assert.doesNotMatch(provider, /\/refundreceipt/iu);
assert.match(provider, /getQuickBooksRefundDisbursementConfiguration/);
assert.match(provider, /resolveQuickBooksRefundReceivableAccount/);
assert.match(provider, /creditMemoResponse\?\.CreditMemo, invoiceResponse\?\.Invoice/);
assert.match(provider, /AccountType = 'Accounts Receivable'/);
assert.match(provider, /ids\.length === 1/);
assert.match(provider, /QUICKBOOKS_REFUND_AR_ACCOUNT_REQUIRED/);
assert.doesNotMatch(provider, /QUICKBOOKS_REFUND_BANK_ACCOUNT_ID/);
assert.match(refundMigration, /subject_kind IN \('invoice','payment','refund'\)/);
assert.match(refundMigration, /v2_quickbooks_refund_sync_workflows/);
assert.match(liveRevisionMigration, /projection_fingerprint/);
assert.match(liveRevisionMigration, /projection_version/);
assert.match(liveRevisionMigration, /projection_json/);
assert.match(liveRevisionMigration, /v2_quickbooks_sync_links_invoice_revision_idx/);
assert.match(provider, /QUICKBOOKS_CUSTOMER_REVIEW_REQUIRED/);
assert.match(provider, /QUICKBOOKS_INVOICE_REVIEW_REQUIRED/);
assert.match(routes, /\/sync-selected/);
assert.match(routes, /enqueueInvoices\(organizationId,ids\)/);
assert.match(routes, /\/unsynced-financial-facts/);
assert.match(routes, /\/sync-financial/);
assert.match(routes, /enqueueFinancialFacts\(organizationId,subjects\)/);
assert.match(routes, /router\.put\("\/policy"/);
assert.match(routes, /router\.get\("\/unsynced-invoices"/);
assert.match(routes, /router\.get\("\/queue"/);
assert.match(routes, /import-preview\/invoices/);
assert.match(routes, /import\/invoices/);
assert.match(settingsUi, /label: "QuickBooks"/);
assert.match(consoleUi, /QuickBooks operational health/);
assert.match(consoleUi, /Connection & refund configuration/);
assert.match(consoleUi, /Auto Sync/);
assert.match(consoleUi, /Import/);
assert.match(consoleUi, /Invoices to sync/);
assert.match(consoleUi, /Payments & refunds/);
assert.match(consoleUi, /Queue & activity/);
assert.match(consoleUi, /Action required/);
assert.match(consoleUi, /Live V2 Order-backed invoices/);
assert.match(consoleUi, /Never synced/);
assert.match(consoleUi, /Changed since sync/);
assert.match(consoleUi, /Select visible/);
assert.match(consoleUi, /Clear selection/);
assert.match(consoleUi, /selection\.size > 100/);
assert.match(consoleUi, /financialSelection\.size > 100/);
assert.match(consoleUi, /Open financial facts/);
assert.match(consoleUi, /Reconciliation required/);
assert.match(consoleUi, /Reconcile & resume/);
assert.match(queue, /async queueActivity/);
assert.match(queue, /actionRequiredOnly/);
assert.doesNotMatch(financeUi, /Sync to QuickBooks/);
assert.doesNotMatch(financeUi, /Retry Payment Sync/);
assert.doesNotMatch(financeRoutes, /quickbooks-sync-selected/);
assert.match(historical, /QuickBooks historical invoice is missing DocNumber/);
assert.match(historical, /native_number_collision/);
assert.equal(v2QuickBooksQueueWorkerEnabled({ QUICKBOOKS_AUTOMATION_OWNER: "queue" }), true);
assert.equal(v2QuickBooksQueueWorkerEnabled({ QUICKBOOKS_AUTOMATION_OWNER: "legacy_jobs" }), false);
assert.equal(quickBooksQueueFailureState({ statusCode: 409 }), "blocked");
assert.equal(quickBooksQueueFailureState({ code: "ECONNRESET" }), "uncertain");
assert.equal(quickBooksQueueFailureState({ code: "ETIMEDOUT" }), "uncertain");
assert.equal(quickBooksQueueFailureState(new Error("validation failed")), "retry");
console.log("QuickBooks V2 Billing queue contracts passed.");
