import express from "express";
import request from "supertest";
import { describe, expect, test } from "@jest/globals";
import { createProductRouter, type ProductHttpDependencies } from "../../src/interfaces/http/productRoutes";
import type { StaffPrincipal } from "../../src/authorization/principals";
const staff=(organizationId:string,capabilities:readonly("product.view")[]=["product.view"]):StaffPrincipal=>({kind:"staff",organizationId,userId:"staff-a",authority:{membershipId:"membership-a",capabilities}});
const catalog={productId:"product-a",displayName:"Rigid Sign",category:"Signs",lifecycle:"active" as const,measurementMode:"dimensions_required" as const,pricingSummary:"Per sq ft",hasDraft:false};
const versions={active:{status:"active" as const,createdAt:"2026-08-17T00:00:00.000Z",updatedAt:"2026-08-18T00:00:00.000Z",editable:false},history:[],historyLimit:25,historyHasMore:false,canCreateDraft:true};
const detail={...catalog,workflowIntent:"standard_production" as const,requiresProductionJob:true,requiresProofApproval:false,configurableOptionCount:1,versions};
const draftGeneral={productId:"product-a",draftVersionId:"draft-a",draftUpdatedAt:"2026-08-18T01:00:00.000Z",lifecycle:"draft" as const,general:{displayName:"Rigid Sign",category:"Signs",description:null,storefrontVisible:false,measurementMode:"dimensions_required" as const,workflowIntent:"standard_production" as const,requiresProofApproval:false,requiresProductionJob:true}};
const app=(principal:StaffPrincipal,lifecycle:any={createDraft:async()=>({ok:true,value:{...versions,draft:{status:"draft",createdAt:"2026-08-18T01:00:00.000Z",updatedAt:"2026-08-18T01:00:00.000Z",editable:true},canCreateDraft:false}}),updateDraftGeneral:async()=>({ok:true,value:draftGeneral})})=>express().use(express.json()).use("/v2/organizations/:organizationId/products",createProductRouter({principals:{principal:async()=>principal},lifecycle,draftGeneral:{read:async(org,id)=>org==="org-a"&&id==="product-a"?draftGeneral:null},workspace:{list:async(org,input)=>org==="org-a"?{items:[catalog],page:input?.page??1,pageSize:input?.pageSize??50,total:1,hasMore:false}:{items:[],page:1,pageSize:50,total:0,hasMore:false},get:async(org,id)=>org==="org-a"&&id==="product-a"?detail:null} satisfies ProductHttpDependencies));
describe("P1 Product workspace HTTP projection",()=>{
 test("returns a tenant-scoped page and detail",async()=>{const server=app(staff("org-a"));await request(server).get("/v2/organizations/org-a/products?q=Rigid&page=2&pageSize=20").expect(200,{ok:true,data:{items:[catalog],page:2,pageSize:20,total:1,hasMore:false}});await request(server).get("/v2/organizations/org-a/products/product-a").expect(200,{ok:true,data:detail});});
 test("fails closed for a foreign organization, missing id, malformed id, and absent permission",async()=>{const server=app(staff("org-a"));await request(server).get("/v2/organizations/org-b/products").expect(403);await request(server).get("/v2/organizations/org-a/products/product-b").expect(404);await request(server).get("/v2/organizations/org-a/products/%2Fbad").expect(404);await request(app(staff("org-a",[]))).get("/v2/organizations/org-a/products").expect(403);});
 test("requires Product edit authority and a current Active state to create a Draft",async()=>{const denied=app(staff("org-a",["product.view"]));await request(denied).post("/v2/organizations/org-a/products/product-a/drafts").send({businessRequestId:"draft-1",expectedActiveVersionUpdatedAt:"2026-08-18T00:00:00.000Z"}).expect(403);const editable=staff("org-a",["product.view","product.edit"] as any);const server=app(editable);await request(server).post("/v2/organizations/org-a/products/product-a/drafts").send({businessRequestId:"draft-1",expectedActiveVersionUpdatedAt:"2026-08-18T00:00:00.000Z"}).expect(200).expect(({body})=>expect(body.data.draft.status).toBe("draft"));});
 test("reads Draft General settings and requires Product edit authority to save",async()=>{const denied=app(staff("org-a",["product.view"]));await request(denied).get("/v2/organizations/org-a/products/product-a/draft/general").expect(200,{ok:true,data:draftGeneral});await request(denied).patch("/v2/organizations/org-a/products/product-a/draft/general").send({businessRequestId:"save-1",draftVersionId:"draft-a",expectedDraftUpdatedAt:draftGeneral.draftUpdatedAt,general:draftGeneral.general}).expect(403);const server=app(staff("org-a",["product.view","product.edit"] as any));await request(server).patch("/v2/organizations/org-a/products/product-a/draft/general").send({businessRequestId:"save-1",draftVersionId:"draft-a",expectedDraftUpdatedAt:draftGeneral.draftUpdatedAt,general:draftGeneral.general}).expect(200,{ok:true,data:draftGeneral});});
});
