import assert from "node:assert/strict";
import express from "express";
import request from "supertest";
import { createTaxSettingsRouter, type TaxSettingsHttpDependencies } from "../../src/interfaces/http/taxSettingsRoutes.js";
import type { StaffPrincipal } from "../../src/authorization/principals.js";

const staff=(organizationId="org-a",capabilities=["pricing.configure"]):StaffPrincipal=>({kind:"staff",organizationId,userId:"staff-a",authority:{membershipId:"membership-a",capabilities}});
const settings={homeBusiness:{jurisdictionId:"tax-a",name:"Indiana",countryCode:"US",regionCode:"IN",rateBasisPoints:725,active:true,homeBusiness:true,updatedAt:"2026-01-01T00:00:00.000Z"}};
const calls:unknown[]=[];
const events:unknown[]=[];
const app=(actor:StaffPrincipal,fail=false)=>express().use(express.json()).use("/v2/organizations/:organizationId/settings/sales-tax",createTaxSettingsRouter({logger:{log:(level,event,context)=>events.push({level,event,context})},principals:{principal:async()=>actor},settings:{read:async()=>settings,save:async(org,input,principal,id,trace)=>{calls.push({org,input,principal:principal.organizationId,id});trace?.("repository_transaction_started");trace?.("durable_request_started");if(fail)throw new Error("transaction failed");trace?.("jurisdiction_upserted",{resourceId:"tax-a"});trace?.("audit_written",{resourceId:"tax-a"});trace?.("durable_request_completed",{resourceId:"tax-a"});trace?.("transaction_committed",{resourceId:"tax-a"});return settings;}}} satisfies TaxSettingsHttpDependencies));
await request(app(staff())).get("/v2/organizations/org-a/settings/sales-tax").expect(200,{ok:true,data:settings});
await request(app(staff())).put("/v2/organizations/org-a/settings/sales-tax/home-business").set("x-v2-csrf-token","csrf-do-not-log").send({businessRequestId:"tax-save-a",name:" Indiana ",countryCode:"us",regionCode:"in",ratePercent:"7.25",active:true,organizationId:"org-b"}).expect(200,{ok:true,data:settings});
assert.deepEqual(calls,[{org:"org-a",input:{name:"Indiana",countryCode:"US",regionCode:"IN",rateBasisPoints:725,active:true},principal:"org-a",id:"tax-save-a"}]);
assert.deepEqual(events.map((entry:any)=>entry.event),["v2.sales_tax_settings.save.request_received","v2.sales_tax_settings.save.authenticated","v2.sales_tax_settings.save.authorized","v2.sales_tax_settings.save.validated","v2.sales_tax_settings.save.repository_transaction_started","v2.sales_tax_settings.save.durable_request_started","v2.sales_tax_settings.save.jurisdiction_upserted","v2.sales_tax_settings.save.audit_written","v2.sales_tax_settings.save.durable_request_completed","v2.sales_tax_settings.save.transaction_committed","v2.sales_tax_settings.save.response_sent"]);
assert.equal(JSON.stringify(events).includes("7.25"),false);
assert.equal(JSON.stringify(events).includes("csrf-do-not-log"),false);
await request(app(staff())).put("/v2/organizations/org-a/settings/sales-tax/home-business").send({businessRequestId:"bad",name:"Indiana",countryCode:"US",regionCode:"IN",ratePercent:"7.255",active:true}).expect(400);
assert.equal((events as any[]).some((entry:any)=>entry.event==="v2.sales_tax_settings.save.validation_rejected"),true);
await request(app(staff("org-a",[]))).get("/v2/organizations/org-a/settings/sales-tax").expect(403);
await request(app(staff("org-b"))).put("/v2/organizations/org-a/settings/sales-tax/home-business").send({businessRequestId:"foreign",name:"Indiana",countryCode:"US",regionCode:"IN",ratePercent:"7",active:true}).expect(403);
assert.equal((events as any[]).some((entry:any)=>entry.event==="v2.sales_tax_settings.save.capability_rejected"),true);
await request(app(staff(),true)).put("/v2/organizations/org-a/settings/sales-tax/home-business").send({businessRequestId:"transaction-failure",name:"Indiana",countryCode:"US",regionCode:"IN",ratePercent:"7",active:true}).expect(500);
const failed=(events as any[]).filter((entry:any)=>entry.context?.businessRequestId==="transaction-failure").map((entry:any)=>entry.event);
assert.equal(failed.includes("v2.sales_tax_settings.save.transaction_committed"),false);
console.log("Sales Tax settings HTTP scope and validation tests passed.");
