import { createHash } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { PostgresOperationRequestRepository } from "../persistence/postgresOperationRequests.js";
import type { QuoteArtworkAssignment, QuoteArtworkProjection, QuoteArtworkTransaction, QuoteArtworkTransactionRunner, QuoteArtworkUsage } from "../../src/modules/artwork/quoteArtworkApplication.js";
import type { ArtworkFile, ArtworkFileInput } from "../../src/modules/artwork/contracts.js";
import { brandedId, type ArtworkFileId, type OrganizationId, type QuoteArtworkAssignmentId, type QuoteId } from "../../src/modules/shared/commercialValues.js";
import { V2ApplicationError } from "../../src/errors/applicationError.js";

type FileRow = Readonly<{ id:string; organization_id:string; storage_provider:string; object_key:string; object_version:string; original_filename:string; display_filename:string; content_type:string; byte_size:string; checksum_algorithm:"sha256"|null; checksum_value:string|null; source_kind:"customer_upload"|"prepress_derived"|"imported"; page_count:number|null; detected_width_microns:number|null; detected_height_microns:number|null; derived_from_artwork_file_id:string|null; created_at:Date }>;
type AssignmentRow = Readonly<{ id:string; organization_id:string; quote_document_id:string; quote_line_id:string; artwork_file_id:string; purpose:"customer_supplied"|"production"|"proof"|"reference"; side:"front"|"back"|null; source_page_index:number|null; layer_key:string|null; layer_order:number|null; created_at:Date }>;
type ProjectionRow = FileRow & Readonly<{ assignment_id:string; assignment_organization_id:string; quote_document_id:string; quote_line_id:string; assignment_artwork_file_id:string; purpose:AssignmentRow["purpose"]; side:AssignmentRow["side"]; source_page_index:number|null; layer_key:string|null; layer_order:number|null; assignment_created_at:Date }>;
const sha = (value: unknown): string => `sha256:${createHash("sha256").update(JSON.stringify(value)).digest("hex")}`;
const file = (row: FileRow): ArtworkFile => ({ id:brandedId<"ArtworkFileId">(row.id), organizationId:brandedId<"OrganizationId">(row.organization_id), objectReference:{storageProvider:row.storage_provider,objectKey:row.object_key,...(row.object_version?{objectVersion:row.object_version}:{})}, originalFilename:row.original_filename, displayFilename:row.display_filename, contentType:row.content_type, byteSize:Number(row.byte_size), ...(row.checksum_algorithm&&row.checksum_value?{checksum:{algorithm:row.checksum_algorithm,value:row.checksum_value}}:{}), source:row.source_kind, ...(row.page_count!==null?{pageCount:row.page_count}:{}), ...(row.detected_width_microns!==null?{detectedWidthMicrons:row.detected_width_microns}:{}), ...(row.detected_height_microns!==null?{detectedHeightMicrons:row.detected_height_microns}:{}), ...(row.derived_from_artwork_file_id?{derivedFromArtworkFileId:brandedId<"ArtworkFileId">(row.derived_from_artwork_file_id)}:{}), createdAt:row.created_at.toISOString() });
const assignment = (row: AssignmentRow): QuoteArtworkAssignment => ({ id:brandedId<"QuoteArtworkAssignmentId">(row.id),organizationId:brandedId<"OrganizationId">(row.organization_id),quoteId:brandedId<"QuoteId">(row.quote_document_id),quoteLineId:brandedId<"SalesLineId">(row.quote_line_id),artworkFileId:brandedId<"ArtworkFileId">(row.artwork_file_id),purpose:row.purpose,...(row.side?{side:row.side}:{}),...(row.source_page_index!==null?{sourcePageIndex:row.source_page_index}:{}),...(row.layer_key!==null?{layerKey:row.layer_key}:{}),...(row.layer_order!==null?{layerOrder:row.layer_order}:{}),createdAt:row.created_at.toISOString() });

export class PostgresQuoteArtworkTransaction implements QuoteArtworkTransaction {
  private readonly requests = new PostgresOperationRequestRepository();
  constructor(private readonly client: PoolClient) {}
  async reserve(input: Parameters<QuoteArtworkTransaction["reserve"]>[0]) { const r=await this.requests.reserve(this.client,input); return {kind:r.kind,request:{id:r.request.id,resultJson:r.request.resultJson}}; }
  async succeed(org:string,id:string,result:unknown,resourceId:string){ await this.requests.succeed(this.client,org,id,{resourceType:"quote_artwork_assignment",resourceId,resultJson:result}); }
  async audit(input: Parameters<QuoteArtworkTransaction["audit"]>[0]) { await this.client.query("INSERT INTO v2_audit_events(organization_id,operation_request_id,operation,event_type,resource_type,resource_id,principal_kind,principal_subject,staff_actor_user_id,changes) VALUES($1,$2,$3,$4,'quote_artwork_assignment',$5,$6,$7,$8,$9::jsonb)",[input.organizationId,input.requestId,input.operation,input.eventType,input.resourceId,input.principalKind,input.principalSubject,input.staffActorUserId??null,JSON.stringify([{kind:input.eventType,summary:"Quote line artwork changed."}])]); }
  async lockEditableQuote(org:OrganizationId,quoteId:QuoteId,expected:string){ const r=await this.client.query<{revision:string;delivery_state:string;acceptance_state:string;lifecycle_state:string}>("SELECT d.revision::text,q.delivery_state,q.acceptance_state,q.lifecycle_state FROM v2_sales_documents d JOIN v2_sales_quote_details q ON q.organization_id=d.organization_id AND q.document_id=d.id WHERE d.organization_id=$1 AND d.id=$2 AND d.document_kind='quote' FOR UPDATE OF d,q",[org,quoteId]); const quote=r.rows[0]; if(!quote)throw new V2ApplicationError("NOT_FOUND","Quote was not found."); if(quote.revision!==expected)throw new V2ApplicationError("STALE_STATE","Quote has changed; reload before changing artwork."); if(quote.delivery_state!=="not_sent"||quote.acceptance_state!=="not_accepted"||quote.lifecycle_state!=="open")throw new V2ApplicationError("CONFLICT","Quote artwork is immutable after the Quote lifecycle advances."); }
  async bumpQuoteRevision(org:OrganizationId,quoteId:QuoteId,expected:string){ const r=await this.client.query<{revision:string}>("UPDATE v2_sales_documents SET revision=revision+1,updated_at=now() WHERE organization_id=$1 AND id=$2 AND revision=$3::bigint RETURNING revision::text AS revision",[org,quoteId,expected]); if(!r.rows[0])throw new V2ApplicationError("STALE_STATE","Quote has changed; reload before changing artwork."); return r.rows[0].revision; }
  async findFile(org:OrganizationId,id:ArtworkFileId){ const r=await this.client.query<FileRow>("SELECT * FROM v2_artwork_files WHERE organization_id=$1 AND id=$2",[org,id]);return r.rows[0]?file(r.rows[0]):null; }
  async createOrGetFile(input:Parameters<QuoteArtworkTransaction["createOrGetFile"]>[0]){const f=input.file; const inserted=await this.client.query<FileRow>(`INSERT INTO v2_artwork_files(id,organization_id,storage_provider,object_key,object_version,original_filename,display_filename,content_type,byte_size,checksum_algorithm,checksum_value,source_kind,page_count,detected_width_microns,detected_height_microns) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(organization_id,storage_provider,object_key,object_version) DO NOTHING RETURNING *`,[input.id,input.organizationId,f.objectReference.storageProvider,f.objectReference.objectKey,f.objectReference.objectVersion??"",f.originalFilename,f.displayFilename??f.originalFilename,f.contentType,f.byteSize,f.checksum?.algorithm??null,f.checksum?.value??null,f.source,f.pageCount??null,f.detectedWidthMicrons??null,f.detectedHeightMicrons??null]); if(inserted.rows[0])return file(inserted.rows[0]); const found=await this.client.query<FileRow>("SELECT * FROM v2_artwork_files WHERE organization_id=$1 AND storage_provider=$2 AND object_key=$3 AND object_version=$4",[input.organizationId,f.objectReference.storageProvider,f.objectReference.objectKey,f.objectReference.objectVersion??""]);if(!found.rows[0])throw new Error("Artwork file adoption could not read its canonical record.");return file(found.rows[0]);}
  async createOrGetAssignment(input:Parameters<QuoteArtworkTransaction["createOrGetAssignment"]>[0]){const u=input.usage; const identity=sha({file:input.artworkFileId,line:u.quoteLineId,purpose:u.purpose,side:u.side??null,page:u.sourcePageIndex??null,layer:u.layerKey??null,order:u.layerOrder??null});
    // A Quote has one current source file per semantic side/page/layer slot.
    // The header lock was acquired before this call, so delete+insert is an
    // atomic pre-accept replacement; accepted rows are FK-protected anyway.
    await this.client.query(`DELETE FROM v2_quote_artwork_assignments WHERE organization_id=$1 AND quote_document_id=$2 AND quote_line_id=$3 AND purpose=$4 AND side IS NOT DISTINCT FROM $5 AND source_page_index IS NOT DISTINCT FROM $6 AND layer_key IS NOT DISTINCT FROM $7 AND layer_order IS NOT DISTINCT FROM $8 AND identity_fingerprint<>$9`,[input.organizationId,u.quoteId,u.quoteLineId,u.purpose,u.side??null,u.sourcePageIndex??null,u.layerKey??null,u.layerOrder??null,identity]);
    const inserted=await this.client.query<AssignmentRow>(`INSERT INTO v2_quote_artwork_assignments(id,organization_id,quote_document_id,quote_line_id,artwork_file_id,purpose,side,source_page_index,layer_key,layer_order,identity_fingerprint,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(organization_id,quote_line_id,identity_fingerprint) DO NOTHING RETURNING *`,[input.id,input.organizationId,u.quoteId,u.quoteLineId,input.artworkFileId,u.purpose,u.side??null,u.sourcePageIndex??null,u.layerKey??null,u.layerOrder??null,identity,input.principalKind,input.principalSubject,input.staffActorUserId??null]); if(inserted.rows[0])return assignment(inserted.rows[0]); const found=await this.client.query<AssignmentRow>("SELECT * FROM v2_quote_artwork_assignments WHERE organization_id=$1 AND quote_line_id=$2 AND identity_fingerprint=$3",[input.organizationId,u.quoteLineId,identity]);if(!found.rows[0])throw new Error("Quote artwork assignment could not be read.");return assignment(found.rows[0]);}
  async list(org:OrganizationId,quote:QuoteId){const r=await this.client.query<ProjectionRow>(`SELECT a.id assignment_id,a.organization_id assignment_organization_id,a.quote_document_id,a.quote_line_id,a.artwork_file_id assignment_artwork_file_id,a.purpose,a.side,a.source_page_index,a.layer_key,a.layer_order,a.created_at assignment_created_at,f.* FROM v2_quote_artwork_assignments a JOIN v2_artwork_files f ON f.organization_id=a.organization_id AND f.id=a.artwork_file_id WHERE a.organization_id=$1 AND a.quote_document_id=$2 ORDER BY a.quote_line_id,a.created_at,a.id`,[org,quote]);return r.rows.map(row=>({file:file(row),assignment:assignment({id:row.assignment_id,organization_id:row.assignment_organization_id,quote_document_id:row.quote_document_id,quote_line_id:row.quote_line_id,artwork_file_id:row.assignment_artwork_file_id,purpose:row.purpose,side:row.side,source_page_index:row.source_page_index,layer_key:row.layer_key,layer_order:row.layer_order,created_at:row.assignment_created_at})}));}
  async remove(org:OrganizationId,quote:QuoteId,id:QuoteArtworkAssignmentId){const r=await this.client.query("DELETE FROM v2_quote_artwork_assignments WHERE organization_id=$1 AND quote_document_id=$2 AND id=$3",[org,quote,id]);return r.rowCount===1;}
}
export class PostgresQuoteArtworkTransactionRunner implements QuoteArtworkTransactionRunner { constructor(private readonly pool:Pool){} async transaction<T>(action:(tx:QuoteArtworkTransaction)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");const result=await action(new PostgresQuoteArtworkTransaction(client));await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}} }

/** Conversion-only adapter sharing the caller's Quote→Order transaction. */
export class PostgresQuoteArtworkConversionPort {
  constructor(private readonly client: PoolClient) {}
  async snapshotAccepted(org:string, quoteId:string, checkpointId:string):Promise<void>{await this.client.query(`INSERT INTO v2_quote_accepted_artwork_snapshots(id,organization_id,quote_document_id,acceptance_checkpoint_id,quote_line_id,quote_artwork_assignment_id,artwork_file_id,purpose,side,source_page_index,layer_key,layer_order,evidence_fingerprint) SELECT gen_random_uuid()::text,a.organization_id,a.quote_document_id,$3,a.quote_line_id,a.id,a.artwork_file_id,a.purpose,a.side,a.source_page_index,a.layer_key,a.layer_order,'sha256:'||encode(digest(concat_ws('|',a.id,a.artwork_file_id,a.quote_line_id,coalesce(a.side,''),coalesce(a.source_page_index::text,''),coalesce(a.layer_key,''),coalesce(a.layer_order::text,'')),'sha256'),'hex') FROM v2_quote_artwork_assignments a WHERE a.organization_id=$1 AND a.quote_document_id=$2 ON CONFLICT(organization_id,acceptance_checkpoint_id,quote_artwork_assignment_id) DO NOTHING`,[org,quoteId,checkpointId]);}
  async carryAcceptedToOrder(input:Readonly<{organizationId:string;quoteId:string;acceptanceCheckpointId:string;orderId:string;lineMap:ReadonlyMap<string,string>}>):Promise<void>{const rows=await this.client.query<{id:string;quote_line_id:string}>("SELECT id,quote_line_id FROM v2_quote_accepted_artwork_snapshots WHERE organization_id=$1 AND quote_document_id=$2 AND acceptance_checkpoint_id=$3 ORDER BY id",[input.organizationId,input.quoteId,input.acceptanceCheckpointId]);for(const snapshot of rows.rows){const orderLineId=input.lineMap.get(snapshot.quote_line_id);if(!orderLineId)throw new V2ApplicationError("CONFLICT","Accepted Quote artwork could not be mapped to the Order line.");await this.client.query(`INSERT INTO v2_artwork_assignments(id,organization_id,artwork_file_id,order_document_id,order_line_id,purpose,side,source_page_index,layer_key,layer_order,identity_fingerprint,source_quote_accepted_artwork_snapshot_id) SELECT gen_random_uuid()::text,s.organization_id,s.artwork_file_id,$4,$5,'customer_supplied',s.side,s.source_page_index,s.layer_key,s.layer_order,'sha256:'||encode(digest(concat_ws('|',s.id,$4::varchar,$5::varchar),'sha256'),'hex'),s.id FROM v2_quote_accepted_artwork_snapshots s WHERE s.organization_id=$1 AND s.id=$2 AND s.quote_document_id=$3 ON CONFLICT(organization_id,source_quote_accepted_artwork_snapshot_id) WHERE source_quote_accepted_artwork_snapshot_id IS NOT NULL DO NOTHING`,[input.organizationId,snapshot.id,input.quoteId,input.orderId,orderLineId]);}}
}
