import type { Pool, PoolClient } from "pg";
import type { ShipmentContainerRunner, ShipmentContainerTransaction } from "../../src/modules/fulfillment/shipmentContainerApplication.js";
import type { FulfillmentShipmentContainer } from "../../src/modules/fulfillment/shipmentContainer.js";
import type { ManualCarrierShipment } from "../../src/modules/fulfillment/carrierShipment.js";
import { brandedId } from "../../src/modules/shared/commercialValues.js";
type Row={id:string;organization_id:string;customer_id:string|null;destination:unknown;shipment_status:"prepared"|"shipped";manual_carrier_name:string|null;manual_carrier_service:string|null;manual_tracking_number:string|null;notes:string|null;package_count:number|null;created_at:Date;created_principal_kind:any;created_principal_subject:string;shipped_at:Date|null;shipped_principal_kind:any;shipped_principal_subject:string|null};
const map=(r:Row):FulfillmentShipmentContainer=>({shipmentId:r.id,organizationId:brandedId<"OrganizationId">(r.organization_id),status:r.shipment_status,...(r.customer_id?{customerId:brandedId<"CustomerId">(r.customer_id)}:{}),...(r.destination?{destination:r.destination}:{}),carrier:{status:r.shipment_status,...(r.manual_carrier_name?{carrierName:r.manual_carrier_name}:{}),...(r.manual_carrier_service?{carrierService:r.manual_carrier_service}:{}),...(r.manual_tracking_number?{trackingNumber:r.manual_tracking_number}:{}),...(r.notes?{notes:r.notes}:{}),...(r.package_count?{packageCount:r.package_count}:{}),...(r.shipped_at?{shippedAt:r.shipped_at.toISOString()}:{} )},createdAt:r.created_at.toISOString(),createdPrincipalKind:r.created_principal_kind,createdPrincipalSubject:r.created_principal_subject,...(r.shipped_at?{shippedAt:r.shipped_at.toISOString()}:{}),...(r.shipped_principal_kind?{shippedPrincipalKind:r.shipped_principal_kind}:{}),...(r.shipped_principal_subject?{shippedPrincipalSubject:r.shipped_principal_subject}:{})});
const values=(carrier:ManualCarrierShipment)=>[carrier.carrierName??null,carrier.carrierService??null,carrier.trackingNumber??null,carrier.notes??null,carrier.packageCount??null];
export class PostgresShipmentContainerTransaction implements ShipmentContainerTransaction {constructor(private readonly client:PoolClient){} async create(input:Parameters<ShipmentContainerTransaction["create"]>[0]){const r=await this.client.query<Row>("INSERT INTO v2_fulfillment_shipments(id,organization_id,customer_id,destination,manual_carrier_name,manual_carrier_service,manual_tracking_number,notes,package_count,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *",[input.id,input.organizationId,input.customerId??null,input.destination?JSON.stringify(input.destination):null,...values(input.carrier),input.principalKind,input.principalSubject,input.staffActorUserId??null]);return map(r.rows[0]!)} async markShipped(input:Parameters<ShipmentContainerTransaction["markShipped"]>[0]){const r=await this.client.query<Row>("UPDATE v2_fulfillment_shipments SET shipment_status='shipped',manual_carrier_name=$3,manual_carrier_service=$4,manual_tracking_number=$5,notes=$6,package_count=$7,shipped_at=COALESCE(shipped_at,now()),shipped_principal_kind=COALESCE(shipped_principal_kind,$8),shipped_principal_subject=COALESCE(shipped_principal_subject,$9),shipped_staff_actor_user_id=COALESCE(shipped_staff_actor_user_id,$10) WHERE organization_id=$1 AND id=$2 RETURNING *",[input.organizationId,input.shipmentId,...values(input.carrier),input.principalKind,input.principalSubject,input.staffActorUserId??null]);return r.rows[0]?map(r.rows[0]):null} async attach(input:Parameters<ShipmentContainerTransaction["attach"]>[0]){const compatible=await this.client.query<{count:string}>("SELECT count(*) FROM v2_fulfillment_handoffs h JOIN v2_fulfillment_shipments s ON s.organization_id=h.organization_id AND s.id=$2 JOIN v2_sales_order_details o ON o.organization_id=h.organization_id AND o.document_id=h.order_document_id LEFT JOIN v2_fulfillment_shipment_handoffs already ON already.organization_id=h.organization_id AND already.handoff_id=h.id WHERE h.organization_id=$1 AND h.id=ANY($3::text[]) AND h.handoff_method='shipment' AND s.shipment_status='shipped' AND h.customer_id IS NOT DISTINCT FROM s.customer_id AND o.requested_destination IS NOT DISTINCT FROM s.destination AND already.handoff_id IS NULL",[input.organizationId,input.shipmentId,input.handoffIds]);if(Number(compatible.rows[0]?.count)!==input.handoffIds.length)return false;for(const handoffId of input.handoffIds)await this.client.query("INSERT INTO v2_fulfillment_shipment_handoffs(organization_id,shipment_id,handoff_id) VALUES($1,$2,$3)",[input.organizationId,input.shipmentId,handoffId]);return true}}
export class PostgresShipmentContainerRunner implements ShipmentContainerRunner {constructor(private readonly pool:Pool){}async transaction<T>(work:(tx:ShipmentContainerTransaction)=>Promise<T>){const c=await this.pool.connect();try{await c.query("BEGIN");const r=await work(new PostgresShipmentContainerTransaction(c));await c.query("COMMIT");return r}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}}
