import type { Pool, PoolClient } from "pg";
import { brandedId, type OrganizationId, type OrderId } from "../../src/modules/shared/commercialValues.js";
import { fulfillmentPhysicalIntegrityAnomaly, fulfillmentSupplyQuantity, type FulfillmentAvailability, type FulfillmentHandoff, type FulfillmentHandoffLine, type FulfillmentOrderWorkspace, type FulfillmentWorkspacePage, type FulfillmentWorkspaceReadPort } from "../../src/modules/fulfillment/contracts.js";

type OrderRow={id:string;display_number:string;commercial_state:"open"|"completed"|"cancelled";customer_id:string|null;contact_id:string|null;customer_name:string;requested_due_date:string|null;requested_fulfillment_method:"pickup"|"shipping"|"local_delivery"|null;requested_destination:unknown;fulfillment_instructions:string|null};
type LineRow={id:string;document_id:string;description:string;quantity:number;pickup_quantity:string;shipment_quantity:string;completed_production_quantity:string;workflow_intent:"standard_production"|"fulfillment_only"|"service_fee"|null;requires_production:boolean};
type HandoffRow={id:string;organization_id:string;order_document_id:string;handoff_method:"pickup"|"shipment";completed_at:Date;customer_id:string|null;contact_id:string|null;completed_principal_kind:FulfillmentHandoff["completedPrincipalKind"];completed_principal_subject:string;completed_staff_actor_user_id:string|null};
type AllocationRow={id:string;organization_id:string;handoff_id:string;order_document_id:string;order_line_id:string;quantity:number};
type MutableHandoffHistory={handoff:FulfillmentHandoff;allocations:readonly FulfillmentHandoffLine[];documentAvailable?:boolean}[];
const handoff=(r:HandoffRow):FulfillmentHandoff=>({handoffId:brandedId<"FulfillmentHandoffId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),orderId:brandedId<"OrderId">(r.order_document_id),method:r.handoff_method,completedAt:r.completed_at.toISOString(),...(r.customer_id?{customerId:brandedId<"CustomerId">(r.customer_id)}:{}),...(r.contact_id?{contactId:brandedId<"ContactId">(r.contact_id)}:{}),completedPrincipalKind:r.completed_principal_kind,completedPrincipalSubject:r.completed_principal_subject,...(r.completed_staff_actor_user_id?{completedStaffActorUserId:r.completed_staff_actor_user_id}:{})});
const allocation=(r:AllocationRow):FulfillmentHandoffLine=>({handoffLineId:brandedId<"FulfillmentHandoffLineId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),handoffId:brandedId<"FulfillmentHandoffId">(r.handoff_id),orderId:brandedId<"OrderId">(r.order_document_id),orderLineId:brandedId<"OrderLineId">(r.order_line_id),quantity:r.quantity});
const availability=(r:LineRow):FulfillmentAvailability=>{const pickup=Number(r.pickup_quantity),shipment=Number(r.shipment_quantity),completedFulfillment=pickup+shipment,completedProduction=Math.min(r.quantity,Math.max(0,Number(r.completed_production_quantity))),supplyQuantity=fulfillmentSupplyQuantity({orderedQuantity:r.quantity,completedProductionQuantity:completedProduction,productionRequired:r.requires_production,workflowIntent:r.workflow_intent}),anomaly=fulfillmentPhysicalIntegrityAnomaly(supplyQuantity,completedFulfillment);return {orderId:brandedId<"OrderId">(r.document_id),orderLineId:brandedId<"OrderLineId">(r.id),orderedQuantity:r.quantity,completedPickupQuantity:pickup,completedShipmentQuantity:shipment,completedFulfillmentQuantity:completedFulfillment,completedProductionQuantity:completedProduction,productionRequired:r.requires_production,availableFulfillmentQuantity:Math.max(0,supplyQuantity-completedFulfillment),remainingProductionQuantity:r.requires_production?Math.max(0,r.quantity-completedProduction):0,remainingFulfillmentQuantity:Math.max(0,r.quantity-completedFulfillment),...(anomaly?{physicalIntegrityAnomaly:anomaly}:{})};};
const decode=(cursor?:string)=>{if(!cursor)return undefined;try{const x=JSON.parse(Buffer.from(cursor,"base64url").toString("utf8"));return typeof x?.number==="string"&&typeof x?.id==="string"?x as {number:string;id:string}:undefined;}catch{return undefined;}};
const encode=(x:{number:string;id:string})=>Buffer.from(JSON.stringify(x),"utf8").toString("base64url");
const linesSql=`WITH production_output AS (
  SELECT l.id order_line_id,
    COALESCE(MIN(COALESCE(unit_output.completed_good_quantity,0)),0)::text completed_production_quantity
  FROM v2_sales_document_lines l
  LEFT JOIN v2_sales_line_production_requirements r ON r.organization_id=l.organization_id AND r.order_line_id=l.id
  LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(a.good_quantity) FILTER (WHERE a.completed_at IS NOT NULL),0) completed_good_quantity
    FROM v2_production_works w
    LEFT JOIN v2_production_attempts a ON a.organization_id=w.organization_id AND a.production_work_id=w.id
    WHERE w.organization_id=l.organization_id AND w.order_line_id=l.id AND w.requirement_key=r.requirement_key
  ) unit_output ON r.requirement_key IS NOT NULL
  WHERE l.organization_id=$1 AND l.document_id=ANY($2::text[])
  GROUP BY l.id
), fulfillment_output AS (
  SELECT l.id order_line_id,
    COALESCE(SUM(fhl.quantity) FILTER (WHERE fh.handoff_method='pickup'),0)::text pickup_quantity,
    COALESCE(SUM(fhl.quantity) FILTER (WHERE fh.handoff_method='shipment'),0)::text shipment_quantity
  FROM v2_sales_document_lines l
  LEFT JOIN v2_fulfillment_handoff_lines fhl ON fhl.organization_id=l.organization_id AND fhl.order_document_id=l.document_id AND fhl.order_line_id=l.id
  LEFT JOIN v2_fulfillment_handoffs fh ON fh.organization_id=fhl.organization_id AND fh.id=fhl.handoff_id
  WHERE l.organization_id=$1 AND l.document_id=ANY($2::text[])
  GROUP BY l.id
) SELECT l.id,l.document_id,l.description,l.quantity,f.pickup_quantity,f.shipment_quantity,p.completed_production_quantity,
    CASE WHEN COALESCE(l.resolved_configuration#>>'{productFacts,workflowIntent}',v.tree_json#>>'{meta,general,workflowIntent}') IN ('standard_production','fulfillment_only','service_fee') THEN COALESCE(l.resolved_configuration#>>'{productFacts,workflowIntent}',v.tree_json#>>'{meta,general,workflowIntent}') ELSE NULL END workflow_intent,
    COALESCE((l.resolved_configuration#>>'{productFacts,requiresProductionJob}')::boolean,(v.tree_json#>>'{meta,general,requiresProductionJob}')::boolean,false) requires_production
  FROM v2_sales_document_lines l
  JOIN production_output p ON p.order_line_id=l.id
  JOIN fulfillment_output f ON f.order_line_id=l.id
  LEFT JOIN pbv2_tree_versions v ON v.organization_id=l.organization_id AND v.product_id=l.product_id AND v.id=l.resolved_configuration->>'pricingConfigurationId'
  WHERE l.organization_id=$1 AND l.document_id=ANY($2::text[]) ORDER BY l.document_id,l.id`;

/** Read-only composition of Sales commercial context, Production output, and Fulfillment handoff facts. */
export class PostgresFulfillmentWorkspaceReads implements FulfillmentWorkspaceReadPort {
 constructor(private readonly pool:Pool){}
 private async read<T>(action:(client:PoolClient)=>Promise<T>){const client=await this.pool.connect();try{await client.query("BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");const result=await action(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
 async list(org:OrganizationId,request:Readonly<{limit?:number;search?:string;cursor?:string}>):Promise<FulfillmentWorkspacePage>{return this.read(async client=>{const limit=Number.isInteger(request.limit)?Math.max(1,Math.min(request.limit!,50)):25,cursor=decode(request.cursor);const orders=await client.query<OrderRow>(`SELECT d.id,d.display_number,o.commercial_state,d.customer_id,d.contact_id,COALESCE(c.display_name,c.company_name,'Customer unavailable') customer_name,d.requested_due_date::text,o.requested_fulfillment_method,o.requested_destination,o.fulfillment_instructions FROM v2_sales_documents d JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id LEFT JOIN customers c ON c.organization_id=d.organization_id AND c.id=d.customer_id WHERE d.organization_id=$1 AND d.document_kind='order' AND o.archived_at IS NULL AND ($2::text IS NULL OR d.display_number ILIKE '%'||$2||'%' OR COALESCE(c.display_name,c.company_name,'') ILIKE '%'||$2||'%') AND ($3::text IS NULL OR (d.display_number,d.id)>($3::text,$4::text)) ORDER BY d.display_number,d.id LIMIT $5`,[org,request.search?.trim()||null,cursor?.number??null,cursor?.id??null,limit+1]);const visible=orders.rows.slice(0,limit),items=await this.load(client,org,visible),last=visible.at(-1);return {items,...(orders.rows.length>limit&&last?{nextCursor:encode({number:last.display_number,id:last.id})}:{})};});}
 async get(org:OrganizationId,orderId:OrderId):Promise<FulfillmentOrderWorkspace|null>{return this.read(async client=>{const order=await client.query<OrderRow>("SELECT d.id,d.display_number,o.commercial_state,d.customer_id,d.contact_id,COALESCE(c.display_name,c.company_name,'Customer unavailable') customer_name,d.requested_due_date::text,o.requested_fulfillment_method,o.requested_destination,o.fulfillment_instructions FROM v2_sales_documents d JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id LEFT JOIN customers c ON c.organization_id=d.organization_id AND c.id=d.customer_id WHERE d.organization_id=$1 AND d.id=$2 AND d.document_kind='order'",[org,orderId]);if(!order.rows[0])return null;return (await this.load(client,org,order.rows))[0]!;});}
 private async load(client:PoolClient,org:OrganizationId,orders:readonly OrderRow[]):Promise<readonly FulfillmentOrderWorkspace[]>{if(!orders.length)return [];const ids=orders.map(x=>x.id);const [lines,handoffs,allocations,snapshots]=await Promise.all([client.query<LineRow>(linesSql,[org,ids]),client.query<HandoffRow>("SELECT * FROM v2_fulfillment_handoffs WHERE organization_id=$1 AND order_document_id=ANY($2::text[]) ORDER BY completed_at,id",[org,ids]),client.query<AllocationRow>("SELECT * FROM v2_fulfillment_handoff_lines WHERE organization_id=$1 AND order_document_id=ANY($2::text[]) ORDER BY handoff_id,order_line_id",[org,ids]),client.query<{handoff_id:string}>("SELECT s.handoff_id FROM v2_fulfillment_handoff_document_snapshots s JOIN v2_fulfillment_handoffs h ON h.organization_id=s.organization_id AND h.id=s.handoff_id WHERE s.organization_id=$1 AND h.order_document_id=ANY($2::text[])",[org,ids])]);const allocByHandoff=new Map<string,FulfillmentHandoffLine[]>();for(const row of allocations.rows){const list=allocByHandoff.get(row.handoff_id)??[];list.push(allocation(row));allocByHandoff.set(row.handoff_id,list);}const snapshotHandoffs=new Set(snapshots.rows.map(row=>row.handoff_id));const handoffsByOrder=new Map<string,MutableHandoffHistory>();for(const row of handoffs.rows){const list=handoffsByOrder.get(row.order_document_id)??[];list.push({handoff:handoff(row),allocations:allocByHandoff.get(row.id)??[],...(snapshotHandoffs.has(row.id)?{documentAvailable:true}:{})});handoffsByOrder.set(row.order_document_id,list);}return orders.map(order=>({orderId:brandedId<"OrderId">(order.id),number:order.display_number,commercialState:order.commercial_state,customerName:order.customer_name,...(order.customer_id?{customerId:brandedId<"CustomerId">(order.customer_id)}:{}),...(order.contact_id?{contactId:brandedId<"ContactId">(order.contact_id)}:{}),...(order.requested_due_date?{requestedDueDate:order.requested_due_date}:{}),...(order.requested_fulfillment_method?{requestedFulfillment:{method:order.requested_fulfillment_method,...(order.requested_destination?{destination:order.requested_destination as any}:{}),...(order.fulfillment_instructions?{instructions:order.fulfillment_instructions}:{})}}:{}),lines:lines.rows.filter(line=>line.document_id===order.id).map(line=>({description:line.description,...availability(line)})),handoffs:handoffsByOrder.get(order.id)??[]}));}
}
