import { createHash, randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { AuthorityPolicy } from "../../src/authorization/authorityPolicy.js";
import { principalSubject, staffActorId } from "../../src/authorization/principals.js";
import { requireOperationPrincipalScope, type OperationContext } from "../../src/application/operation.js";
import { V2ApplicationError } from "../../src/errors/applicationError.js";
import { applyShippingChargeInTransaction } from "../billing/postgresShippingCharge.js";

type AuthorityRow={order_document_id:string;replacement_obligation_id:string|null;display_number:string;billing_treatment:"no_charge"|"billable"|"pending"|null};
type AllocationRow={id:string;order_document_id:string;customer_shipping_price_cents:string;allocation_kind:"equal_split"|"manual";invoiced_invoice_id:string|null;membership_fingerprint:string|null};
type Actor=Readonly<{principalKind:string;principalSubject:string;staffActorUserId?:string}>;
export type ShipmentShippingAllocation=Readonly<{orderId:string;orderNumber:string;customerShippingPriceCents:number;allocationKind:"equal_split"|"manual";invoicedInvoiceId?:string}>;
export type ShipmentShippingAllocationRead=Readonly<{shipmentId:string;customerShippingPriceCents:number;membershipFingerprint:string;allocationState:"default"|"manual"|"review_required"|"projected";allocations:readonly ShipmentShippingAllocation[]}>;

const actor=(context:OperationContext):Actor=>({principalKind:context.principal.kind,principalSubject:principalSubject(context.principal),...(staffActorId(context.principal)?{staffActorUserId:staffActorId(context.principal)}:{})});
const cents=(value:number,label:string)=>{if(!Number.isSafeInteger(value)||value<0)throw new V2ApplicationError("VALIDATION_ERROR",`${label} must be a non-negative whole-cent amount.`);return value;};
const fingerprint=(values:readonly AuthorityRow[])=>`sha256:${createHash("sha256").update(values.map(value=>`${value.order_document_id}:${value.replacement_obligation_id??"original"}`).sort().join("|"),"utf8").digest("hex")}`;
const equal=(total:number,authorities:readonly AuthorityRow[])=>{const ordered=[...authorities].sort((a,b)=>a.display_number.localeCompare(b.display_number)||a.order_document_id.localeCompare(b.order_document_id));const base=Math.floor(total/ordered.length), remainder=total%ordered.length;return ordered.map((value,index)=>({orderId:value.order_document_id,cents:base+(index<remainder?1:0)}));};

export class PostgresShipmentShippingAllocationService {
  constructor(private readonly pool:Pool,private readonly authority=new AuthorityPolicy()){}
  private require(context:OperationContext){requireOperationPrincipalScope(context);if(context.principal.kind!=="staff"||!this.authority.decide(context.principal,{capability:"fulfillment.shipping.price",resource:{organizationId:context.organizationId}}).allowed)throw new V2ApplicationError("FORBIDDEN","Shipment shipping allocation access is unavailable.");}
  async read(context:OperationContext,shipmentId:string):Promise<ShipmentShippingAllocationRead>{this.require(context);const client=await this.pool.connect();try{return await this.readIn(client,context.organizationId,shipmentId);}finally{client.release();}}
  async establishEqual(context:OperationContext,shipmentId:string):Promise<ShipmentShippingAllocationRead>{return this.transaction(context,shipmentId,async(client,authorities,total,member)=>{await this.replace(client,context.organizationId,shipmentId,equal(total,authorities),"equal_split",member,actor(context));return this.readIn(client,context.organizationId,shipmentId);});}
  async setManual(context:OperationContext,shipmentId:string,values:readonly Readonly<{orderId:string;customerShippingPriceCents:number}>[]):Promise<ShipmentShippingAllocationRead>{return this.transaction(context,shipmentId,async(client,authorities,total,member)=>{const expected=new Set(authorities.map(value=>value.order_document_id));if(values.length!==expected.size||new Set(values.map(value=>value.orderId)).size!==values.length||values.some(value=>!expected.has(value.orderId)))throw new V2ApplicationError("VALIDATION_ERROR","Manual shipping allocations must contain every participating Order exactly once.");const allocated=values.reduce((sum,value)=>sum+cents(value.customerShippingPriceCents,"Manual shipping allocation"),0);if(allocated!==total)throw new V2ApplicationError("VALIDATION_ERROR","Manual shipping allocations must equal the frozen customer shipping price exactly.");await this.replace(client,context.organizationId,shipmentId,values.map(value=>({orderId:value.orderId,cents:value.customerShippingPriceCents})),"manual",member,actor(context));return this.readIn(client,context.organizationId,shipmentId);});}
  async project(context:OperationContext,shipmentId:string):Promise<ShipmentShippingAllocationRead>{return this.transaction(context,shipmentId,async(client,authorities,total,member)=>{let allocations=await this.allocations(client,context.organizationId,shipmentId,true);if(!allocations.length){await this.replace(client,context.organizationId,shipmentId,equal(total,authorities),"equal_split",member,actor(context));allocations=await this.allocations(client,context.organizationId,shipmentId,true);}if(allocations.some(value=>value.membership_fingerprint!==member)){throw new V2ApplicationError("CONFLICT","Shipment membership changed after a shipping allocation was established; re-establish the allocation before projection.");}for(const allocation of allocations.filter(value=>!value.invoiced_invoice_id)){const authority=authorities.find(value=>value.order_document_id===allocation.order_document_id)!;const amount=Number(allocation.customer_shipping_price_cents);const target=await this.destination(client,context.organizationId,authority,amount);if(!target)continue;await this.addCharge(client,context.organizationId,shipmentId,allocation,target,authorities.map(value=>value.display_number),actor(context));await client.query("UPDATE v2_fulfillment_shipment_shipping_allocations SET invoiced_invoice_id=$4,projected_at=now() WHERE organization_id=$1 AND shipment_id=$2 AND id=$3",[context.organizationId,shipmentId,allocation.id,target.id]);}return this.readIn(client,context.organizationId,shipmentId);});}
  private async transaction<T>(context:OperationContext,shipmentId:string,work:(client:PoolClient,authorities:AuthorityRow[],total:number,member:string)=>Promise<T>):Promise<T>{this.require(context);const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':' || $2::text,0))",[context.organizationId,shipmentId]);const shipment=await client.query<{customer_shipping_price_cents:string|null;customer_shipping_price_frozen_at:Date|null}>("SELECT customer_shipping_price_cents::text,customer_shipping_price_frozen_at FROM v2_fulfillment_shipments WHERE organization_id=$1 AND id=$2 AND shipment_status='shipped' FOR UPDATE",[context.organizationId,shipmentId]);const row=shipment.rows[0];if(!row)throw new V2ApplicationError("NOT_FOUND","A shipped shipment is required for shipping allocation.");if(row.customer_shipping_price_frozen_at===null||row.customer_shipping_price_cents===null)throw new V2ApplicationError("CONFLICT","Freeze the customer shipping price before allocating it.");const authorities=await this.authorities(client,context.organizationId,shipmentId);const member=fingerprint(authorities);const value=await work(client,authorities,Number(row.customer_shipping_price_cents),member);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  private async authorities(client:PoolClient,organizationId:string,shipmentId:string):Promise<AuthorityRow[]>{const rows=await client.query<AuthorityRow>(`SELECT h.order_document_id,h.replacement_obligation_id,d.display_number,o.billing_treatment FROM v2_fulfillment_shipment_handoffs sh JOIN v2_fulfillment_handoffs h ON h.organization_id=sh.organization_id AND h.id=sh.handoff_id JOIN v2_sales_documents d ON d.organization_id=h.organization_id AND d.id=h.order_document_id LEFT JOIN v2_order_replacement_obligations o ON o.organization_id=h.organization_id AND o.id=h.replacement_obligation_id WHERE sh.organization_id=$1 AND sh.shipment_id=$2 ORDER BY d.display_number,h.order_document_id,h.replacement_obligation_id`,[organizationId,shipmentId]);if(!rows.rows.length)throw new V2ApplicationError("CONFLICT","The shipment has no finalized Order authority.");const perOrder=new Map<string,AuthorityRow>();for(const row of rows.rows){const prior=perOrder.get(row.order_document_id);if(prior&&(prior.replacement_obligation_id??null)!==(row.replacement_obligation_id??null))throw new V2ApplicationError("CONFLICT","One Order has both original and replacement fulfillment authority in this shipment; shipping routing is ambiguous.");perOrder.set(row.order_document_id,row);}return [...perOrder.values()];}
  private async allocations(client:PoolClient,organizationId:string,shipmentId:string,lock=false){return (await client.query<AllocationRow>(`SELECT id,order_document_id,customer_shipping_price_cents::text,allocation_kind,invoiced_invoice_id,membership_fingerprint FROM v2_fulfillment_shipment_shipping_allocations WHERE organization_id=$1 AND shipment_id=$2 ORDER BY order_document_id${lock?" FOR UPDATE":""}`,[organizationId,shipmentId])).rows;}
  private async replace(client:PoolClient,organizationId:string,shipmentId:string,values:readonly Readonly<{orderId:string;cents:number}>[],kind:"equal_split"|"manual",member:string,a:Actor){const existing=await this.allocations(client,organizationId,shipmentId,true);if(existing.some(value=>value.invoiced_invoice_id))throw new V2ApplicationError("CONFLICT","Projected shipping allocations are immutable.");await client.query("DELETE FROM v2_fulfillment_shipment_shipping_allocations WHERE organization_id=$1 AND shipment_id=$2",[organizationId,shipmentId]);for(const value of values)await client.query("INSERT INTO v2_fulfillment_shipment_shipping_allocations(id,organization_id,shipment_id,order_document_id,customer_shipping_price_cents,allocation_kind,membership_fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7)",[randomUUID(),organizationId,shipmentId,value.orderId,value.cents,kind,member]);await client.query("INSERT INTO v2_fulfillment_shipment_economics_events(id,organization_id,shipment_id,event_kind,detail,principal_kind,principal_subject,staff_actor_user_id) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8)",[randomUUID(),organizationId,shipmentId,kind==="manual"?"shipping_allocation_manual":"shipping_allocation_equal",JSON.stringify({membershipFingerprint:member,allocations:values}),a.principalKind,a.principalSubject,a.staffActorUserId??null]);}
  private async destination(client:PoolClient,organizationId:string,authority:AuthorityRow,amount:number):Promise<{id:string}|undefined>{if(authority.replacement_obligation_id){if(authority.billing_treatment==="no_charge"){if(amount>0)throw new V2ApplicationError("CONFLICT","A no-charge replacement cannot receive a positive shipping Invoice charge.");return undefined;}if(authority.billing_treatment!=="billable")throw new V2ApplicationError("CONFLICT","Replacement billing treatment must be resolved before shipping projection.");const invoice=await client.query<{id:string}>("SELECT id FROM v2_billing_invoices WHERE organization_id=$1 AND replacement_obligation_id=$2 AND invoice_state<>'void' FOR UPDATE",[organizationId,authority.replacement_obligation_id]);if(!invoice.rows[0])throw new V2ApplicationError("CONFLICT","The billable replacement Invoice is unavailable.");return invoice.rows[0];}const invoice=await client.query<{id:string}>("SELECT id FROM v2_billing_invoices WHERE organization_id=$1 AND sales_order_document_id=$2 AND replacement_obligation_id IS NULL AND invoice_sequence=1 AND invoice_state<>'void' FOR UPDATE",[organizationId,authority.order_document_id]);if(!invoice.rows[0])throw new V2ApplicationError("CONFLICT","The canonical base Invoice is unavailable.");return invoice.rows[0];}
  private async addCharge(client:PoolClient,organizationId:string,shipmentId:string,allocation:AllocationRow,target:{id:string},orderNumbers:readonly string[],a:Actor){await applyShippingChargeInTransaction(client,{organizationId,invoiceId:target.id,orderId:allocation.order_document_id,shipmentId,shipmentAllocationId:allocation.id,customerChargeCents:Number(allocation.customer_shipping_price_cents),orderNumbers,actor:a});}
  private async readIn(client:PoolClient,organizationId:string,shipmentId:string):Promise<ShipmentShippingAllocationRead>{const shipment=await client.query<{customer_shipping_price_cents:string|null}>("SELECT customer_shipping_price_cents::text FROM v2_fulfillment_shipments WHERE organization_id=$1 AND id=$2",[organizationId,shipmentId]);const amount=shipment.rows[0]?.customer_shipping_price_cents;if(amount===undefined||amount===null)throw new V2ApplicationError("NOT_FOUND","Shipment was not found.");const authorities=await this.authorities(client,organizationId,shipmentId),member=fingerprint(authorities),rows=await this.allocations(client,organizationId,shipmentId);const stale=rows.length>0&&rows.some(row=>row.membership_fingerprint!==member),projected=rows.some(row=>row.invoiced_invoice_id),manual=rows.some(row=>row.allocation_kind==="manual");return {shipmentId,customerShippingPriceCents:Number(amount),membershipFingerprint:member,allocationState:projected?"projected":stale?"review_required":manual?"manual":"default",allocations:rows.map(row=>({orderId:row.order_document_id,orderNumber:authorities.find(value=>value.order_document_id===row.order_document_id)?.display_number??row.order_document_id,customerShippingPriceCents:Number(row.customer_shipping_price_cents),allocationKind:row.allocation_kind,...(row.invoiced_invoice_id?{invoicedInvoiceId:row.invoiced_invoice_id}:{})}))};}
}
