import { randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import type { ShippingEconomicsPort, ShippingEconomicsRunner, ShippingPolicyRead, ShippingPricingPolicyInput, StaffShippingEconomics } from "../../src/modules/fulfillment/shippingEconomicsApplication.js";
import type { ShippingPricingPolicy, ShippingResponsibility } from "../../src/modules/fulfillment/replacementShippingEconomics.js";
import type { CustomerId, OrganizationId } from "../../src/modules/shared/commercialValues.js";

type PolicyRow={customer_id:string|null;mode:"pass_through"|"flat"|"percent"|"no_charge"|"manual";flat_amount_cents:string|null;percentage_basis_points:number|null;currency:string;version:number};
type ShipmentRow={id:string;customer_id:string|null;estimated_carrier_cost_cents:string|null;customer_shipping_price_cents:string|null;customer_shipping_price_frozen_at:Date|null;shipping_pricing_policy_snapshot:unknown;actual_cost:string|null};
const policy=(row:PolicyRow):ShippingPricingPolicy=>({mode:row.mode,currency:row.currency,version:row.version,...(row.flat_amount_cents===null?{}:{flatAmountCents:Number(row.flat_amount_cents)}),...(row.percentage_basis_points===null?{}:{percentageBasisPoints:row.percentage_basis_points})});
const snapshot=(value:unknown):StaffShippingEconomics["pricingPolicySnapshot"]|undefined=>value&&typeof value==="object"?value as StaffShippingEconomics["pricingPolicySnapshot"]:undefined;
const economics=(row:ShipmentRow):StaffShippingEconomics=>({shipmentId:row.id,...(row.customer_id?{customerId:row.customer_id}:{}),...(row.estimated_carrier_cost_cents===null?{}:{estimatedCarrierCostCents:Number(row.estimated_carrier_cost_cents)}),...(row.actual_cost===null?{}:{actualCarrierCostCents:Number(row.actual_cost)}),...(row.customer_shipping_price_cents===null?{}:{customerShippingPriceCents:Number(row.customer_shipping_price_cents)}),customerPriceFrozen:row.customer_shipping_price_frozen_at!==null,...(snapshot(row.shipping_pricing_policy_snapshot)?{pricingPolicySnapshot:snapshot(row.shipping_pricing_policy_snapshot)}:{})});
export class PostgresShippingEconomics implements ShippingEconomicsPort {
  constructor(private readonly client:PoolClient){}
  async policy(organizationId:OrganizationId,customerId?:CustomerId):Promise<ShippingPolicyRead>{const rows=await this.client.query<PolicyRow>("SELECT customer_id,mode,flat_amount_cents::text,percentage_basis_points,currency,version FROM v2_shipping_pricing_policies WHERE organization_id=$1 AND active AND (customer_id IS NULL OR customer_id=$2) ORDER BY customer_id NULLS FIRST",[organizationId,customerId??null]);const organization=rows.rows.find(row=>row.customer_id===null);const customer=rows.rows.find(row=>row.customer_id!==null);return { ...(organization?{organizationDefault:policy(organization)}:{}),...(customer?{customerOverride:policy(customer)}:{})};}
  async savePolicy(input:Parameters<ShippingEconomicsPort["savePolicy"]>[0]):Promise<ShippingPolicyRead>{
    await this.client.query("SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':' || COALESCE($2::text,''),0))",[input.organizationId,input.customerId??null]);
    if(input.customerId){const customer=await this.client.query<{id:string}>("SELECT id FROM customers WHERE organization_id=$1 AND id=$2 FOR UPDATE",[input.organizationId,input.customerId]);if(!customer.rows[0])throw Error("Customer shipping policy is outside this organization.");}
    await this.client.query("UPDATE v2_shipping_pricing_policies SET active=false WHERE organization_id=$1 AND customer_id IS NOT DISTINCT FROM $2 AND active",[input.organizationId,input.customerId??null]);
    if(input.policy)await this.client.query("INSERT INTO v2_shipping_pricing_policies(id,organization_id,customer_id,mode,flat_amount_cents,percentage_basis_points,currency,active,version,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,true,(SELECT COALESCE(max(version),0)+1 FROM v2_shipping_pricing_policies WHERE organization_id=$2 AND customer_id IS NOT DISTINCT FROM $3),$8,$9,$10)",[randomUUID(),input.organizationId,input.customerId??null,input.policy.mode,input.policy.flatAmountCents??null,input.policy.percentageBasisPoints??null,input.policy.currency,input.principalKind,input.principalSubject,input.staffActorUserId??null]);
    await this.client.query("INSERT INTO v2_shipping_pricing_policy_events(id,organization_id,customer_id,event_kind,detail,principal_kind,principal_subject,staff_actor_user_id) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8)",[randomUUID(),input.organizationId,input.customerId??null,input.customerId?(input.policy?"customer_override_set":"customer_override_cleared"):"organization_default_set",JSON.stringify(input.policy??{}),input.principalKind,input.principalSubject,input.staffActorUserId??null]);
    return this.policy(input.organizationId,input.customerId);
  }
  async shipment(organizationId:OrganizationId,shipmentId:string,lock=false):Promise<StaffShippingEconomics|null>{const row=await this.client.query<ShipmentRow>(`SELECT s.id,s.customer_id,s.estimated_carrier_cost_cents::text,s.customer_shipping_price_cents::text,s.customer_shipping_price_frozen_at,s.shipping_pricing_policy_snapshot,
    (SELECT u.actual_carrier_cost_cents::text FROM v2_fulfillment_shipment_actual_cost_updates u WHERE u.organization_id=s.organization_id AND u.shipment_id=s.id ORDER BY u.created_at DESC,u.id DESC LIMIT 1) actual_cost
    FROM v2_fulfillment_shipments s WHERE s.organization_id=$1 AND s.id=$2${lock?" FOR UPDATE":""}`,[organizationId,shipmentId]);return row.rows[0]?economics(row.rows[0]):null;}
  async setEstimated(input:Parameters<ShippingEconomicsPort["setEstimated"]>[0]){const prior=await this.shipment(input.organizationId,input.shipmentId,true);if(!prior)return null;await this.client.query("UPDATE v2_fulfillment_shipments SET estimated_carrier_cost_cents=$3 WHERE organization_id=$1 AND id=$2",[input.organizationId,input.shipmentId,input.estimatedCarrierCostCents]);await this.event(input.organizationId,input.shipmentId,"estimated_cost_set",{estimatedCarrierCostCents:input.estimatedCarrierCostCents},input);return this.shipment(input.organizationId,input.shipmentId);}
  async setActual(input:Parameters<ShippingEconomicsPort["setActual"]>[0]){const prior=await this.shipment(input.organizationId,input.shipmentId,true);if(!prior)return null;await this.client.query("INSERT INTO v2_fulfillment_shipment_actual_cost_updates(id,organization_id,shipment_id,actual_carrier_cost_cents,responsibility,reason,note,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),input.organizationId,input.shipmentId,input.actualCarrierCostCents,input.responsibility,input.reason,input.note??null,input.principalKind,input.principalSubject,input.staffActorUserId??null]);await this.event(input.organizationId,input.shipmentId,"actual_cost_set",{actualCarrierCostCents:input.actualCarrierCostCents,responsibility:input.responsibility,reason:input.reason},input);return this.shipment(input.organizationId,input.shipmentId);}
  async freezeCustomerPrice(input:Parameters<ShippingEconomicsPort["freezeCustomerPrice"]>[0]){const updated=await this.client.query<ShipmentRow>(`UPDATE v2_fulfillment_shipments SET customer_shipping_price_cents=$3,customer_shipping_price_frozen_at=now(),shipping_pricing_policy_snapshot=$4::jsonb
    WHERE organization_id=$1 AND id=$2 AND customer_shipping_price_frozen_at IS NULL RETURNING id,customer_id,estimated_carrier_cost_cents::text,customer_shipping_price_cents::text,customer_shipping_price_frozen_at,shipping_pricing_policy_snapshot,NULL::text actual_cost`,[input.organizationId,input.shipmentId,input.customerShippingPriceCents,JSON.stringify(input.snapshot)]);if(!updated.rows[0])return null;await this.event(input.organizationId,input.shipmentId,"customer_price_frozen",{customerShippingPriceCents:input.customerShippingPriceCents,pricingPolicySnapshot:input.snapshot},input);return economics(updated.rows[0]);}
  private async event(organizationId:OrganizationId,shipmentId:string,eventKind:string,detail:unknown,actor:Readonly<{principalKind:string;principalSubject:string;staffActorUserId?:string}>){await this.client.query("INSERT INTO v2_fulfillment_shipment_economics_events(id,organization_id,shipment_id,event_kind,detail,principal_kind,principal_subject,staff_actor_user_id) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8)",[randomUUID(),organizationId,shipmentId,eventKind,JSON.stringify(detail),actor.principalKind,actor.principalSubject,actor.staffActorUserId??null]);}
}
export class PostgresShippingEconomicsRunner implements ShippingEconomicsRunner {constructor(private readonly pool:Pool){}async transaction<T>(work:(port:ShippingEconomicsPort)=>Promise<T>){const client=await this.pool.connect();try{await client.query("BEGIN");const value=await work(new PostgresShippingEconomics(client));await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}}
