import type { Pool, PoolClient } from "pg";
import { PostgresOperationRequestRepository } from "../persistence/postgresOperationRequests.js";
import type { ShipmentContainerRunner, ShipmentContainerTransaction } from "../../src/modules/fulfillment/shipmentContainerApplication.js";
import { randomUUID } from "node:crypto";
import type { FulfillmentShipmentContainer, FulfillmentShipmentContainerDetail, ShipmentContainerEvent, ShipmentContainerStatus, ShipmentPreparedAllocation, ShipmentPreparedRevision } from "../../src/modules/fulfillment/shipmentContainer.js";
import type { ManualCarrierShipment } from "../../src/modules/fulfillment/carrierShipment.js";
import { fulfillmentSupplyQuantity } from "../../src/modules/fulfillment/contracts.js";
import { brandedId, canonicalJson, type OrganizationId } from "../../src/modules/shared/commercialValues.js";
type Row={id:string;organization_id:string;customer_id:string|null;destination:unknown;shipment_status:ShipmentContainerStatus;manual_carrier_name:string|null;manual_carrier_service:string|null;manual_tracking_number:string|null;notes:string|null;package_count:number|null;prepared_revision_id:string|null;created_at:Date;created_principal_kind:any;created_principal_subject:string;shipped_at:Date|null;shipped_principal_kind:any;shipped_principal_subject:string|null;voided_at:Date|null;voided_principal_kind:any;voided_principal_subject:string|null;void_reason:string|null};
type RevisionRow={id:string;organization_id:string;shipment_id:string;revision_number:number;revision_kind:"initial"|"correction";supersedes_revision_id:string|null;correction_reason:string|null;customer_id:string|null;destination:unknown;manual_carrier_name:string|null;manual_carrier_service:string|null;manual_tracking_number:string|null;notes:string|null;package_count:number|null;created_at:Date;created_principal_kind:any;created_principal_subject:string};
type EventRow={id:string;organization_id:string;shipment_id:string;sequence_number:number;event_type:ShipmentContainerEvent["type"];prepared_revision_id:string|null;reason:string|null;created_at:Date;principal_kind:any;principal_subject:string};
type PreparedOrderLineRow={order_document_id:string;order_line_id:string;customer_id:string|null;requested_destination:unknown};
type AvailabilityRow={order_document_id:string;order_line_id:string;ordered_quantity:number;pickup_quantity:string;shipment_quantity:string;completed_production_quantity:string;workflow_intent:"standard_production"|"fulfillment_only"|"service_fee"|null;requires_production:boolean};
const map=(r:Row):FulfillmentShipmentContainer=>({shipmentId:r.id,organizationId:brandedId<"OrganizationId">(r.organization_id),status:r.shipment_status,...(r.customer_id?{customerId:brandedId<"CustomerId">(r.customer_id)}:{}),...(r.destination?{destination:r.destination}:{}),carrier:{status:r.shipment_status,...(r.manual_carrier_name?{carrierName:r.manual_carrier_name}:{}),...(r.manual_carrier_service?{carrierService:r.manual_carrier_service}:{}),...(r.manual_tracking_number?{trackingNumber:r.manual_tracking_number}:{}),...(r.notes?{notes:r.notes}:{}),...(r.package_count?{packageCount:r.package_count}:{}),...(r.shipped_at?{shippedAt:r.shipped_at.toISOString()}:{} )},...(r.prepared_revision_id?{preparedRevisionId:r.prepared_revision_id}:{}),createdAt:r.created_at.toISOString(),createdPrincipalKind:r.created_principal_kind,createdPrincipalSubject:r.created_principal_subject,...(r.shipped_at?{shippedAt:r.shipped_at.toISOString()}:{}),...(r.shipped_principal_kind?{shippedPrincipalKind:r.shipped_principal_kind}:{}),...(r.shipped_principal_subject?{shippedPrincipalSubject:r.shipped_principal_subject}:{}),...(r.voided_at?{voidedAt:r.voided_at.toISOString()}:{}),...(r.voided_principal_kind?{voidedPrincipalKind:r.voided_principal_kind}:{}),...(r.voided_principal_subject?{voidedPrincipalSubject:r.voided_principal_subject}:{}),...(r.void_reason?{voidReason:r.void_reason}:{})});
const values=(carrier:ManualCarrierShipment)=>[carrier.carrierName??null,carrier.carrierService??null,carrier.trackingNumber??null,carrier.notes??null,carrier.packageCount??null];
const availabilitySql=`WITH production_output AS (
  SELECT l.id order_line_id,COALESCE(MIN(COALESCE(unit_output.completed_good_quantity,0)),0)::text completed_production_quantity
  FROM v2_sales_document_lines l
  LEFT JOIN v2_sales_line_production_requirements r ON r.organization_id=l.organization_id AND r.order_line_id=l.id
  LEFT JOIN LATERAL (SELECT COALESCE(SUM(a.good_quantity) FILTER (WHERE a.completed_at IS NOT NULL),0) completed_good_quantity FROM v2_production_works w LEFT JOIN v2_production_attempts a ON a.organization_id=w.organization_id AND a.production_work_id=w.id WHERE w.organization_id=l.organization_id AND w.order_line_id=l.id AND w.requirement_key=r.requirement_key) unit_output ON r.requirement_key IS NOT NULL
  WHERE l.organization_id=$1 AND l.document_id=$2 GROUP BY l.id
), fulfillment_output AS (
  SELECT l.id order_line_id,COALESCE(SUM(fhl.quantity) FILTER (WHERE fh.handoff_method='pickup'),0)::text pickup_quantity,COALESCE(SUM(fhl.quantity) FILTER (WHERE fh.handoff_method='shipment'),0)::text shipment_quantity
  FROM v2_sales_document_lines l LEFT JOIN v2_fulfillment_handoff_lines fhl ON fhl.organization_id=l.organization_id AND fhl.order_document_id=l.document_id AND fhl.order_line_id=l.id LEFT JOIN v2_fulfillment_handoffs fh ON fh.organization_id=fhl.organization_id AND fh.id=fhl.handoff_id
  WHERE l.organization_id=$1 AND l.document_id=$2 GROUP BY l.id
) SELECT l.document_id order_document_id,l.id order_line_id,l.quantity ordered_quantity,f.pickup_quantity,f.shipment_quantity,p.completed_production_quantity,CASE WHEN COALESCE(l.resolved_configuration#>>'{productFacts,workflowIntent}',v.tree_json#>>'{meta,general,workflowIntent}') IN ('standard_production','fulfillment_only','service_fee') THEN COALESCE(l.resolved_configuration#>>'{productFacts,workflowIntent}',v.tree_json#>>'{meta,general,workflowIntent}') ELSE NULL END workflow_intent,COALESCE((l.resolved_configuration#>>'{productFacts,requiresProductionJob}')::boolean,(v.tree_json#>>'{meta,general,requiresProductionJob}')::boolean,false) requires_production
  FROM v2_sales_document_lines l JOIN production_output p ON p.order_line_id=l.id JOIN fulfillment_output f ON f.order_line_id=l.id LEFT JOIN pbv2_tree_versions v ON v.organization_id=l.organization_id AND v.product_id=l.product_id AND v.id=l.resolved_configuration->>'pricingConfigurationId' WHERE l.organization_id=$1 AND l.document_id=$2 ORDER BY l.id`;
export class PostgresShipmentContainerTransaction implements ShipmentContainerTransaction {
  private readonly requests=new PostgresOperationRequestRepository();
  constructor(private readonly client:PoolClient){}
  async reserve(input:Parameters<ShipmentContainerTransaction["reserve"]>[0]){const r=await this.requests.reserve(this.client,input);return {kind:r.kind,request:{id:r.request.id,resultJson:r.request.resultJson}}}
  async succeed(organizationId:string,requestId:string,result:FulfillmentShipmentContainer){await this.requests.succeed(this.client,organizationId,requestId,{resourceType:"fulfillment_shipment",resourceId:result.shipmentId,resultJson:result})}
  async create(input:Parameters<ShipmentContainerTransaction["create"]>[0]){
    const r=await this.client.query<Row>("INSERT INTO v2_fulfillment_shipments(id,organization_id,customer_id,destination,manual_carrier_name,manual_carrier_service,manual_tracking_number,notes,package_count,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *",[input.id,input.organizationId,input.customerId??null,input.destination===undefined?null:JSON.stringify(input.destination),...values(input.carrier),input.principalKind,input.principalSubject,input.staffActorUserId??null]);
    const shipment=map(r.rows[0]!); await this.insertInitialRevision({organizationId:input.organizationId,shipmentId:shipment.shipmentId,customerId:input.customerId,destination:input.destination,carrier:input.carrier,principalKind:input.principalKind,principalSubject:input.principalSubject,staffActorUserId:input.staffActorUserId,allocations:[]}); return shipment;
  }
  /** New recovery callers create the container and first reservation revision in one transaction. */
  async createPrepared(input:Readonly<{id:string;organizationId:OrganizationId;customerId?:string;destination?:unknown;carrier:ManualCarrierShipment;allocations:readonly ShipmentPreparedAllocation[];principalKind:any;principalSubject:string;staffActorUserId?:string}>):Promise<FulfillmentShipmentContainerDetail>{
    this.validateAllocations(input.allocations); const scope=await this.validatePreparedOrderScope(input.organizationId,input.allocations,input.customerId,input.destination); await this.validatePreparedReservationCapacity(input.organizationId,input.allocations); const r=await this.client.query<Row>("INSERT INTO v2_fulfillment_shipments(id,organization_id,customer_id,destination,manual_carrier_name,manual_carrier_service,manual_tracking_number,notes,package_count,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *",[input.id,input.organizationId,scope.customerId,JSON.stringify(scope.destination),...values(input.carrier),input.principalKind,input.principalSubject,input.staffActorUserId??null]);
    await this.insertInitialRevision({...input,shipmentId:input.id,customerId:scope.customerId,destination:scope.destination}); const detail=await this.get(input.organizationId,map(r.rows[0]!).shipmentId); if(!detail)throw Error("Prepared shipment was not readable after creation."); return detail;
  }
  /** A correction appends a full replacement draft; old allocations remain immutable evidence. */
  async correctPrepared(input:Readonly<{organizationId:OrganizationId;shipmentId:string;carrier:ManualCarrierShipment;allocations:readonly ShipmentPreparedAllocation[];correctionReason:string;principalKind:any;principalSubject:string;staffActorUserId?:string}>):Promise<FulfillmentShipmentContainerDetail|null>{
    this.validateAllocations(input.allocations); const current=await this.get(input.organizationId,input.shipmentId,{forUpdate:true}); if(!current||current.status!=="prepared"||!current.currentPreparedRevision)return null; const prior=current.currentPreparedRevision; await this.lockPreparedOrderLines(input.organizationId,[...prior.allocations,...input.allocations]); const scope=await this.validatePreparedOrderScope(input.organizationId,input.allocations,prior.customerId,prior.destination); if(scope.customerId!==prior.customerId||canonicalJson(scope.destination)!==canonicalJson(prior.destination))throw Error("Prepared shipment corrections must preserve the canonical customer and destination."); await this.validatePreparedReservationCapacity(input.organizationId,input.allocations,input.shipmentId); const reason=input.correctionReason.trim(); if(!reason)throw Error("Prepared shipment correction requires a reason."); const revisionId=randomUUID();
    await this.client.query("INSERT INTO v2_fulfillment_shipment_prepared_revisions(id,organization_id,shipment_id,revision_number,revision_kind,supersedes_revision_id,customer_id,destination,manual_carrier_name,manual_carrier_service,manual_tracking_number,notes,package_count,correction_reason,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,'correction',$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14,$15,$16)",[revisionId,input.organizationId,input.shipmentId,prior.revisionNumber+1,prior.revisionId,prior.customerId??null,prior.destination===undefined?null:JSON.stringify(prior.destination),...values(input.carrier),reason,input.principalKind,input.principalSubject,input.staffActorUserId??null]);
    await this.insertRevisionLines(input.organizationId,input.shipmentId,revisionId,input.allocations); await this.client.query("UPDATE v2_fulfillment_shipments SET prepared_revision_id=$3 WHERE organization_id=$1 AND id=$2 AND shipment_status='prepared'",[input.organizationId,input.shipmentId,revisionId]); await this.insertEvent({organizationId:input.organizationId,shipmentId:input.shipmentId,eventType:"corrected",preparedRevisionId:revisionId,reason,principalKind:input.principalKind,principalSubject:input.principalSubject,staffActorUserId:input.staffActorUserId}); return this.get(input.organizationId,input.shipmentId);
  }
  /** Cancellation never deletes allocations or rewrites an immutable draft revision. */
  async voidPrepared(input:Readonly<{organizationId:OrganizationId;shipmentId:string;reason:string;principalKind:any;principalSubject:string;staffActorUserId?:string}>):Promise<FulfillmentShipmentContainer|null>{
    const locked=await this.lock(input.organizationId,input.shipmentId); if(!locked||locked.shipment_status!=="prepared")return null; const reason=input.reason.trim(); if(!reason)throw Error("Prepared shipment cancellation requires a reason."); const r=await this.client.query<Row>("UPDATE v2_fulfillment_shipments SET shipment_status='voided',voided_at=now(),voided_principal_kind=$3,voided_principal_subject=$4,voided_staff_actor_user_id=$5,void_reason=$6 WHERE organization_id=$1 AND id=$2 AND shipment_status='prepared' RETURNING *",[input.organizationId,input.shipmentId,input.principalKind,input.principalSubject,input.staffActorUserId??null,reason]); if(!r.rows[0])return null; await this.insertEvent({organizationId:input.organizationId,shipmentId:input.shipmentId,eventType:"voided",preparedRevisionId:r.rows[0].prepared_revision_id??undefined,reason,principalKind:input.principalKind,principalSubject:input.principalSubject,staffActorUserId:input.staffActorUserId}); return map(r.rows[0]);
  }
  /**
   * Finalization is deliberately one database transaction (provided by the
   * runner): no completed handoff, immutable snapshot, shipment attachment,
   * or SHIPPED event can survive if any later write fails.  Sales row locks
   * serialize competing prepared containers before fulfillment availability is
   * re-read.
   */
  async finalizePrepared(input:Readonly<{organizationId:OrganizationId;shipmentId:string;expectedPreparedRevisionId:string;principalKind:any;principalSubject:string;staffActorUserId?:string}>):Promise<FulfillmentShipmentContainerDetail|null>{
    const current=await this.get(input.organizationId,input.shipmentId,{forUpdate:true});
    if(!current||current.status!=="prepared"||!current.currentPreparedRevision)return null;
    const revision=current.currentPreparedRevision;
    if(revision.revisionId!==input.expectedPreparedRevisionId)throw Error("The prepared shipment revision is stale. Refresh before finalizing.");
    this.validateAllocations(revision.allocations);

    // Use the frozen revision as the only finalization input.  The browser
    // cannot replace customer, destination, carrier metadata, or quantities.
    await this.lockPreparedOrderLines(input.organizationId,revision.allocations);
    const scope=await this.validatePreparedOrderScope(input.organizationId,revision.allocations,revision.customerId,revision.destination);
    if(scope.customerId!==revision.customerId||canonicalJson(scope.destination)!==canonicalJson(revision.destination))throw Error("The active prepared revision no longer matches canonical shipment scope.");
    await this.validatePreparedReservationCapacity(input.organizationId,revision.allocations,input.shipmentId);

    const contacts=await this.lockOrderContacts(input.organizationId,[...new Set(revision.allocations.map(allocation=>allocation.orderId))]);
    const handoffs:readonly Readonly<{handoffId:string;orderId:string}>[]=await Promise.all([...new Set(revision.allocations.map(allocation=>allocation.orderId))].sort().map(async orderId=>{
      const contact=contacts.get(orderId); if(!contact)throw Error("Prepared shipment Order is no longer an open canonical Order.");
      const handoffId=randomUUID();
      await this.client.query("INSERT INTO v2_fulfillment_handoffs(id,organization_id,order_document_id,handoff_method,customer_id,contact_id,completed_principal_kind,completed_principal_subject,completed_staff_actor_user_id) VALUES($1,$2,$3,'shipment',$4,$5,$6,$7,$8)",[handoffId,input.organizationId,orderId,scope.customerId,contact.contactId,input.principalKind,input.principalSubject,input.staffActorUserId??null]);
      const allocations=revision.allocations.filter(allocation=>allocation.orderId===orderId);
      for(const allocation of allocations)await this.client.query("INSERT INTO v2_fulfillment_handoff_lines(id,organization_id,handoff_id,order_document_id,order_line_id,quantity) VALUES($1,$2,$3,$4,$5,$6)",[randomUUID(),input.organizationId,handoffId,orderId,allocation.orderLineId,allocation.quantity]);
      await this.writeFinalizedHandoffSnapshot({organizationId:input.organizationId,handoffId,shipmentId:input.shipmentId,carrier:revision.carrier});
      return {handoffId,orderId};
    }));

    // 0275 makes the shipment/handoff invariant a deferred constraint trigger:
    // attach immutable evidence before the terminal state is visible, then make
    // PREPARED -> SHIPPED the final domain-state write.  If either later write
    // fails, transaction rollback removes every handoff, snapshot, and link.
    for(const handoff of handoffs)await this.client.query("INSERT INTO v2_fulfillment_shipment_handoffs(organization_id,shipment_id,handoff_id) VALUES($1,$2,$3)",[input.organizationId,input.shipmentId,handoff.handoffId]);
    await this.insertEvent({organizationId:input.organizationId,shipmentId:input.shipmentId,eventType:"shipped",preparedRevisionId:revision.revisionId,principalKind:input.principalKind,principalSubject:input.principalSubject,staffActorUserId:input.staffActorUserId});
    const shipped=await this.client.query<Row>("UPDATE v2_fulfillment_shipments SET shipment_status='shipped',manual_carrier_name=$3,manual_carrier_service=$4,manual_tracking_number=$5,notes=$6,package_count=$7,shipped_at=now(),shipped_principal_kind=$8,shipped_principal_subject=$9,shipped_staff_actor_user_id=$10 WHERE organization_id=$1 AND id=$2 AND shipment_status='prepared' AND prepared_revision_id=$11 RETURNING *",[input.organizationId,input.shipmentId,...values(revision.carrier),input.principalKind,input.principalSubject,input.staffActorUserId??null,revision.revisionId]);
    if(!shipped.rows[0])throw Error("Prepared shipment changed before finalization could complete.");
    const finalized=await this.get(input.organizationId,input.shipmentId);
    if(!finalized)throw Error("Finalized shipment was not readable.");
    return finalized;
  }
  /** Strict prepared predicate and row lock prevent a duplicate ship request from rewriting carrier metadata. */
  async markShipped(input:Parameters<ShipmentContainerTransaction["markShipped"]>[0]){
    void input;
    throw Error("Direct shipment transition is disabled; finalize the prepared shipment atomically.");
    return null;
  }
  /** Tenant-scoped detail read. Transition writers opt into the same row lock. */
  async get(organizationId:OrganizationId,shipmentId:string,options:Readonly<{forUpdate?:boolean}>={}):Promise<FulfillmentShipmentContainerDetail|null>{
    const r=await this.client.query<Row>(`SELECT * FROM v2_fulfillment_shipments WHERE organization_id=$1 AND id=$2${options.forUpdate?" FOR UPDATE":""}`,[organizationId,shipmentId]); const shipment=r.rows[0]; if(!shipment)return null; const [events,revisions]=await Promise.all([this.client.query<EventRow>("SELECT * FROM v2_fulfillment_shipment_events WHERE organization_id=$1 AND shipment_id=$2 ORDER BY sequence_number",[organizationId,shipmentId]),shipment.prepared_revision_id?this.client.query<RevisionRow>("SELECT * FROM v2_fulfillment_shipment_prepared_revisions WHERE organization_id=$1 AND shipment_id=$2 AND id=$3",[organizationId,shipmentId,shipment.prepared_revision_id]):Promise.resolve({rows:[] as RevisionRow[]})]); const revision=revisions.rows[0]; const lines=revision?await this.client.query<{order_document_id:string;order_line_id:string;quantity:number}>("SELECT order_document_id,order_line_id,quantity FROM v2_fulfillment_shipment_prepared_revision_lines WHERE organization_id=$1 AND shipment_id=$2 AND revision_id=$3 ORDER BY order_document_id,order_line_id",[organizationId,shipmentId,revision.id]):{rows:[] as {order_document_id:string;order_line_id:string;quantity:number}[]}; return {...map(shipment),...(revision?{currentPreparedRevision:{revisionId:revision.id,shipmentId:revision.shipment_id,organizationId:brandedId<"OrganizationId">(revision.organization_id),revisionNumber:revision.revision_number,kind:revision.revision_kind,...(revision.supersedes_revision_id?{supersedesRevisionId:revision.supersedes_revision_id}:{}),...(revision.correction_reason?{correctionReason:revision.correction_reason}:{}),...(revision.customer_id?{customerId:brandedId<"CustomerId">(revision.customer_id)}:{}),...(revision.destination?{destination:revision.destination}:{}),carrier:{status:"prepared",...(revision.manual_carrier_name?{carrierName:revision.manual_carrier_name}:{}),...(revision.manual_carrier_service?{carrierService:revision.manual_carrier_service}:{}),...(revision.manual_tracking_number?{trackingNumber:revision.manual_tracking_number}:{}),...(revision.notes?{notes:revision.notes}:{}),...(revision.package_count?{packageCount:revision.package_count}:{})},allocations:lines.rows.map(line=>({orderId:line.order_document_id,orderLineId:line.order_line_id,quantity:line.quantity})),createdAt:revision.created_at.toISOString(),createdPrincipalKind:revision.created_principal_kind,createdPrincipalSubject:revision.created_principal_subject}}:{}),events:events.rows.map(event=>({eventId:event.id,organizationId:brandedId<"OrganizationId">(event.organization_id),shipmentId:event.shipment_id,sequenceNumber:event.sequence_number,type:event.event_type,...(event.prepared_revision_id?{preparedRevisionId:event.prepared_revision_id}:{}),...(event.reason?{reason:event.reason}:{}),createdAt:event.created_at.toISOString(),principalKind:event.principal_kind,principalSubject:event.principal_subject}))};
  }
  async list(organizationId:OrganizationId,request:Readonly<{status?:ShipmentContainerStatus;limit?:number}>={}):Promise<readonly FulfillmentShipmentContainer[]>{const limit=Math.max(1,Math.min(request.limit??50,100));const r=await this.client.query<Row>(`SELECT * FROM v2_fulfillment_shipments WHERE organization_id=$1${request.status?" AND shipment_status=$2":""} ORDER BY created_at DESC,id DESC LIMIT $${request.status?3:2}`,request.status?[organizationId,request.status,limit]:[organizationId,limit]);return r.rows.map(map)}
  async attach(input:Parameters<ShipmentContainerTransaction["attach"]>[0]){const ids=[...input.handoffIds].sort();if(!ids.length)return false;const shipment=await this.lock(input.organizationId,input.shipmentId);if(!shipment||shipment.shipment_status!=="shipped")return false;const r=await this.client.query<{id:string;customer_id:string|null;requested_destination:unknown;existing_shipment_id:string|null}>("SELECT h.id,h.customer_id,o.requested_destination,already.shipment_id existing_shipment_id FROM v2_fulfillment_handoffs h JOIN v2_sales_order_details o ON o.organization_id=h.organization_id AND o.document_id=h.order_document_id LEFT JOIN v2_fulfillment_shipment_handoffs already ON already.organization_id=h.organization_id AND already.handoff_id=h.id WHERE h.organization_id=$1 AND h.id=ANY($2::text[]) AND h.handoff_method='shipment' ORDER BY h.id FOR UPDATE OF h",[input.organizationId,ids]);if(r.rows.length!==ids.length||r.rows.some(row=>row.customer_id!==shipment.customer_id||JSON.stringify(row.requested_destination)!==JSON.stringify(shipment.destination)||(row.existing_shipment_id!==null&&row.existing_shipment_id!==input.shipmentId)))return false;for(const row of r.rows.filter(row=>row.existing_shipment_id===null))await this.client.query("INSERT INTO v2_fulfillment_shipment_handoffs(organization_id,shipment_id,handoff_id) VALUES($1,$2,$3) ON CONFLICT (organization_id,handoff_id) DO NOTHING",[input.organizationId,input.shipmentId,row.id]);return true}
  private async lock(org:OrganizationId,id:string){const r=await this.client.query<Row>("SELECT * FROM v2_fulfillment_shipments WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,id]);return r.rows[0]??null}
  private validateAllocations(allocations:readonly ShipmentPreparedAllocation[]){if(!allocations.length)throw Error("A prepared shipment requires one or more allocations.");const seen=new Set<string>();for(const allocation of allocations){if(!allocation.orderId||!allocation.orderLineId||!Number.isSafeInteger(allocation.quantity)||allocation.quantity<=0)throw Error("Shipment reservation quantities must be positive whole numbers.");const key=`${allocation.orderId}:${allocation.orderLineId}`;if(seen.has(key))throw Error("A prepared shipment revision may reserve an OrderLine only once.");seen.add(key)}}
  /** Locks the exact canonical Sales rows before an append-only draft is persisted. Quantity availability is a separate canonical Fulfillment concern. */
  private async validatePreparedOrderScope(organizationId:OrganizationId,allocations:readonly ShipmentPreparedAllocation[],requestedCustomerId?:string,requestedDestination?:unknown):Promise<Readonly<{customerId:string;destination:unknown}>>{
    const rows=await this.lockPreparedOrderLines(organizationId,allocations);
    if(rows.length!==allocations.length||rows.some(row=>!allocations.some(allocation=>allocation.orderId===row.order_document_id&&allocation.orderLineId===row.order_line_id)))throw Error("Every prepared shipment allocation must reference an active Order and an OrderLine owned by that Order."); const first=rows[0]; if(!first?.customer_id)throw Error("Prepared shipment allocations require a canonical Customer."); const destination=first.requested_destination; if(destination===null||destination===undefined)throw Error("Prepared shipment allocations require a canonical shipping destination."); if(rows.some(row=>row.customer_id!==first.customer_id||canonicalJson(row.requested_destination)!==canonicalJson(destination)))throw Error("Prepared shipment allocations must share one canonical Customer and destination."); if(requestedCustomerId!==undefined&&requestedCustomerId!==first.customer_id)throw Error("Requested shipment Customer does not match the canonical Sales Orders."); if(requestedDestination!==undefined&&canonicalJson(requestedDestination)!==canonicalJson(destination))throw Error("Requested shipment destination does not match the canonical Sales Orders."); return {customerId:first.customer_id,destination};
  }
  /** All prepare/correct writers lock the same Sales rows in lexical order before reading reservations. */
  private async lockPreparedOrderLines(organizationId:OrganizationId,allocations:readonly ShipmentPreparedAllocation[]):Promise<readonly PreparedOrderLineRow[]>{
    const orderIds=[...new Set(allocations.map(allocation=>allocation.orderId))].sort(),lineIds=[...new Set(allocations.map(allocation=>allocation.orderLineId))].sort(); const rows=await this.client.query<PreparedOrderLineRow>("SELECT d.id order_document_id,l.id order_line_id,d.customer_id,o.requested_destination FROM v2_sales_documents d JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id JOIN v2_sales_document_lines l ON l.organization_id=d.organization_id AND l.document_id=d.id WHERE d.organization_id=$1 AND d.document_kind='order' AND o.commercial_state='open' AND d.id=ANY($2::text[]) AND l.id=ANY($3::text[]) ORDER BY d.id,l.id FOR UPDATE OF d,o,l",[organizationId,orderIds,lineIds]); return rows.rows;
  }
  private async lockOrderContacts(organizationId:OrganizationId,orderIds:readonly string[]):Promise<ReadonlyMap<string,Readonly<{contactId?:string}>>>{
    if(!orderIds.length)return new Map();
    const rows=await this.client.query<{order_document_id:string;customer_id:string|null;contact_id:string|null}>("SELECT d.id order_document_id,d.customer_id,d.contact_id FROM v2_sales_documents d JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id WHERE d.organization_id=$1 AND d.document_kind='order' AND o.commercial_state='open' AND d.id=ANY($2::text[]) ORDER BY d.id FOR UPDATE OF d,o",[organizationId,[...orderIds].sort()]);
    if(rows.rows.length!==orderIds.length)throw Error("Prepared shipment references an Order that is no longer open.");
    return new Map(rows.rows.map(row=>[row.order_document_id,{...(row.contact_id?{contactId:row.contact_id}:{})}]));
  }
  /** Prepared reservations consume current physical availability without becoming immutable fulfillment facts. */
  private async validatePreparedReservationCapacity(organizationId:OrganizationId,allocations:readonly ShipmentPreparedAllocation[],excludeShipmentId?:string){
    const availability=new Map<string,AvailabilityRow>(); for(const orderId of [...new Set(allocations.map(allocation=>allocation.orderId))].sort()){const rows=await this.client.query<AvailabilityRow>(availabilitySql,[organizationId,orderId]); for(const row of rows.rows)availability.set(`${row.order_document_id}:${row.order_line_id}`,row);}
    const lineIds=[...new Set(allocations.map(allocation=>allocation.orderLineId))].sort(); const reservations=await this.client.query<{order_line_id:string;reserved_quantity:string}>("SELECT line.order_line_id,COALESCE(sum(line.quantity),0)::text reserved_quantity FROM v2_fulfillment_shipment_prepared_revision_lines line JOIN v2_fulfillment_shipments shipment ON shipment.organization_id=line.organization_id AND shipment.id=line.shipment_id WHERE line.organization_id=$1 AND line.order_line_id=ANY($2::text[]) AND shipment.shipment_status='prepared' AND shipment.prepared_revision_id=line.revision_id AND ($3::text IS NULL OR shipment.id<>$3) GROUP BY line.order_line_id",[organizationId,lineIds,excludeShipmentId??null]); const reserved=new Map(reservations.rows.map(row=>[row.order_line_id,Number(row.reserved_quantity)]));
    for(const allocation of allocations){const row=availability.get(`${allocation.orderId}:${allocation.orderLineId}`); if(!row)throw Error("Prepared shipment availability could not be read for an active OrderLine."); const completedProduction=Math.min(row.ordered_quantity,Math.max(0,Number(row.completed_production_quantity))); const supply=fulfillmentSupplyQuantity({orderedQuantity:row.ordered_quantity,completedProductionQuantity:completedProduction,productionRequired:row.requires_production,workflowIntent:row.workflow_intent}); const available=supply-Number(row.pickup_quantity)-Number(row.shipment_quantity)-(reserved.get(allocation.orderLineId)??0); if(allocation.quantity>available)throw Error("Prepared shipment quantity exceeds the currently available output after active prepared reservations.");}
  }
  private async insertInitialRevision(input:Readonly<{organizationId:OrganizationId;shipmentId:string;customerId?:string;destination?:unknown;carrier:ManualCarrierShipment;principalKind:any;principalSubject:string;staffActorUserId?:string;allocations:readonly ShipmentPreparedAllocation[]}>){const id=randomUUID();await this.client.query("INSERT INTO v2_fulfillment_shipment_prepared_revisions(id,organization_id,shipment_id,revision_number,revision_kind,customer_id,destination,manual_carrier_name,manual_carrier_service,manual_tracking_number,notes,package_count,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,1,'initial',$4,$5::jsonb,$6,$7,$8,$9,$10,$11,$12,$13)",[id,input.organizationId,input.shipmentId,input.customerId??null,input.destination===undefined?null:JSON.stringify(input.destination),...values(input.carrier),input.principalKind,input.principalSubject,input.staffActorUserId??null]);if(input.allocations.length)await this.insertRevisionLines(input.organizationId,input.shipmentId,id,input.allocations);await this.client.query("UPDATE v2_fulfillment_shipments SET prepared_revision_id=$3 WHERE organization_id=$1 AND id=$2",[input.organizationId,input.shipmentId,id]);await this.insertEvent({organizationId:input.organizationId,shipmentId:input.shipmentId,eventType:"prepared",preparedRevisionId:id,principalKind:input.principalKind,principalSubject:input.principalSubject,staffActorUserId:input.staffActorUserId})}
  private async insertRevisionLines(org:OrganizationId,shipment:string,revision:string,allocations:readonly ShipmentPreparedAllocation[]){for(const allocation of allocations)await this.client.query("INSERT INTO v2_fulfillment_shipment_prepared_revision_lines(id,organization_id,shipment_id,revision_id,order_document_id,order_line_id,quantity) VALUES($1,$2,$3,$4,$5,$6,$7)",[randomUUID(),org,shipment,revision,allocation.orderId,allocation.orderLineId,allocation.quantity])}
  /** Reuses the canonical handoff snapshot table while pinning physical-container facts to this finalized shipment. */
  private async writeFinalizedHandoffSnapshot(input:Readonly<{organizationId:OrganizationId;handoffId:string;shipmentId:string;carrier:ManualCarrierShipment}>){
    const result=await this.client.query<{snapshot:unknown}>(`INSERT INTO v2_fulfillment_handoff_document_snapshots(organization_id,handoff_id,snapshot)
      SELECT h.organization_id,h.id,jsonb_build_object(
        'orderNumber',d.display_number,
        'customer',COALESCE(NULLIF(btrim(c.display_name),''),NULLIF(btrim(c.company_name),''),'Customer unavailable'),
        'purchaseOrder',d.purchase_order_number,
        'requestedMethod',o.requested_fulfillment_method,
        'destination',o.requested_destination,
        'instructions',o.fulfillment_instructions,
        'method',h.handoff_method,
        'completedAt',h.completed_at,
        'shipment',jsonb_build_object('shipmentId',$3,'carrierName',$4,'carrierService',$5,'trackingNumber',$6,'notes',$7,'packageCount',$8),
        'lines',COALESCE(jsonb_agg(jsonb_build_object('description',l.description,'quantity',hl.quantity) ORDER BY l.position), '[]'::jsonb)
      )
      FROM v2_fulfillment_handoffs h
      JOIN v2_sales_documents d ON d.organization_id=h.organization_id AND d.id=h.order_document_id
      JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id
      LEFT JOIN customers c ON c.organization_id=d.organization_id AND c.id=d.customer_id
      JOIN v2_fulfillment_handoff_lines hl ON hl.organization_id=h.organization_id AND hl.handoff_id=h.id
      JOIN v2_sales_document_lines l ON l.organization_id=hl.organization_id AND l.id=hl.order_line_id AND l.document_id=hl.order_document_id
      WHERE h.organization_id=$1 AND h.id=$2
      GROUP BY h.organization_id,h.id,d.display_number,d.purchase_order_number,c.display_name,c.company_name,o.requested_fulfillment_method,o.requested_destination,o.fulfillment_instructions,h.handoff_method,h.completed_at
      ON CONFLICT (organization_id,handoff_id) DO NOTHING RETURNING snapshot`,[input.organizationId,input.handoffId,input.shipmentId,input.carrier.carrierName??null,input.carrier.carrierService??null,input.carrier.trackingNumber??null,input.carrier.notes??null,input.carrier.packageCount??null]);
    if(!result.rows[0])throw Error("Finalized shipment handoff snapshot was not available.");
  }
  private async insertEvent(input:Readonly<{organizationId:OrganizationId;shipmentId:string;eventType:ShipmentContainerEvent["type"];preparedRevisionId?:string;reason?:string;principalKind:any;principalSubject:string;staffActorUserId?:string}>){const next=await this.client.query<{sequence_number:number}>("SELECT COALESCE(max(sequence_number),0)+1 sequence_number FROM v2_fulfillment_shipment_events WHERE organization_id=$1 AND shipment_id=$2",[input.organizationId,input.shipmentId]);await this.client.query("INSERT INTO v2_fulfillment_shipment_events(id,organization_id,shipment_id,sequence_number,event_type,prepared_revision_id,reason,principal_kind,principal_subject,staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),input.organizationId,input.shipmentId,next.rows[0]!.sequence_number,input.eventType,input.preparedRevisionId??null,input.reason??null,input.principalKind,input.principalSubject,input.staffActorUserId??null])}
}
export class PostgresShipmentContainerRunner implements ShipmentContainerRunner {constructor(private readonly pool:Pool){}async transaction<T>(work:(tx:ShipmentContainerTransaction)=>Promise<T>){const c=await this.pool.connect();try{await c.query("BEGIN");const r=await work(new PostgresShipmentContainerTransaction(c));await c.query("COMMIT");return r}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}}
