import { createHash, randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { requireOperationPrincipalScope, type OperationContext } from "../../src/application/operation.js";
import { AuthorityPolicy } from "../../src/authorization/authorityPolicy.js";
import { principalSubject, staffActorId } from "../../src/authorization/principals.js";
import { failure, success, type ApplicationResult, V2ApplicationError } from "../../src/errors/applicationError.js";
import type { OrderAutomaticLifecycle } from "../../src/modules/sales/orderAutomaticLifecycle.js";
import { brandedId, canonicalJson, type OrderId, type OrganizationId, type ReplacementObligationId } from "../../src/modules/shared/commercialValues.js";
import { replacementRemainingQuantity, type ReplacementBillingTreatment, type ShippingResponsibility } from "../../src/modules/fulfillment/replacementShippingEconomics.js";
import { replacementReasons, validReplacementInput, type CreateReplacementObligationInput, type ReplacementObligation, type ReplacementObligationEvent, type ReplacementObligationProjection, type ReplacementObligationStatus } from "../../src/modules/fulfillment/replacementObligations.js";
import { PostgresOperationRequestRepository } from "../persistence/postgresOperationRequests.js";
import { createOrReadReplacementInvoice, type ReplacementInvoiceProjection } from "../billing/postgresReplacementInvoice.js";

type Actor = Readonly<{ kind: OperationContext["principal"]["kind"]; subject:string; staffActorUserId?:string }>;
type ObligationRow = { id:string; organization_id:string; order_document_id:string; order_line_id:string; source_fulfillment_handoff_id:string|null; source_shipment_id:string|null; predecessor_replacement_obligation_id:string|null; replacement_quantity:number; reason:string; responsibility:ShippingResponsibility; billing_treatment:ReplacementBillingTreatment; note:string|null; status:ReplacementObligationStatus; created_at:Date; created_principal_kind:ReplacementObligation["createdPrincipalKind"]; created_principal_subject:string };
type SourceWork = { id:string; order_document_id:string; order_line_id:string; requirement_key:string; artwork_assignment_id:string; artwork_file_id:string; prepress_unit_id:string|null; side:"front"|"back"|null; source_page_index:number|null; layer_key:string|null; layer_order:number|null };
const actor = (c:OperationContext):Actor => ({ kind:c.principal.kind, subject:principalSubject(c.principal), ...(staffActorId(c.principal)?{staffActorUserId:staffActorId(c.principal)}:{}) });
const fingerprint=(value:unknown)=>`sha256:${createHash("sha256").update(canonicalJson(value)).digest("hex")}`;
const obligation = (row:ObligationRow, works:readonly string[]=[]):ReplacementObligation => ({ replacementObligationId:brandedId<"ReplacementObligationId">(row.id), organizationId:brandedId<"OrganizationId">(row.organization_id), orderId:brandedId<"OrderId">(row.order_document_id), orderLineId:brandedId<"OrderLineId">(row.order_line_id), ...(row.source_fulfillment_handoff_id?{sourceFulfillmentHandoffId:brandedId<"FulfillmentHandoffId">(row.source_fulfillment_handoff_id)}:{}), ...(row.source_shipment_id?{sourceShipmentId:row.source_shipment_id}:{}), ...(row.predecessor_replacement_obligation_id?{predecessorReplacementObligationId:row.predecessor_replacement_obligation_id}:{}), replacementQuantity:row.replacement_quantity, reason:row.reason as ReplacementObligation["reason"], responsibility:row.responsibility, billingTreatment:row.billing_treatment, ...(row.note?{note:row.note}:{}), status:row.status, successorProductionWorkIds:works.map(value=>brandedId<"ProductionWorkId">(value)), createdAt:row.created_at.toISOString(), createdPrincipalKind:row.created_principal_kind, createdPrincipalSubject:row.created_principal_subject });

/** Replacement writes are deliberately isolated from rejected-output and billing flows. */
export class PostgresReplacementObligationService {
  private readonly requests=new PostgresOperationRequestRepository();
  constructor(private readonly pool:Pool, private readonly lifecycle?:OrderAutomaticLifecycle, private readonly authority=new AuthorityPolicy()) {}

  async create(c:OperationContext, input:CreateReplacementObligationInput):Promise<ApplicationResult<ReplacementObligationProjection>> {
    try {
      requireOperationPrincipalScope(c); this.require(c);
      if(!c.businessRequest||c.businessRequest.id!==input.businessRequestId) throw new V2ApplicationError("VALIDATION_ERROR","A matching business request identity is required.");
      if (!validReplacementInput(input) || (input.billingTreatment!=="no_charge" && input.billingTreatment!=="billable")) throw new V2ApplicationError("VALIDATION_ERROR","Replacement input is invalid.");
      const result=await this.transaction(async client => {
        const org=brandedId<"OrganizationId">(c.organizationId), a=actor(c);
        const request=await this.requests.reserve(client,{organizationId:org,operation:"fulfillment.replacement.create.v1",businessRequestId:input.businessRequestId,payloadFingerprint:fingerprint(input),principalKind:a.kind,principalSubject:a.subject,staffActorUserId:a.staffActorUserId});
        if(request.kind==="replay") { if(!request.request.resultJson) throw new V2ApplicationError("STALE_STATE","The replacement request is still being completed."); return request.request.resultJson as ReplacementObligationProjection; }
        const line=await client.query<{id:string}>("SELECT l.id FROM v2_sales_documents d JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id JOIN v2_sales_document_lines l ON l.organization_id=o.organization_id AND l.document_id=o.document_id WHERE o.organization_id=$1 AND o.document_id=$2 AND d.document_kind='order' AND o.commercial_state IN ('open','completed') AND l.id=$3 FOR UPDATE OF d,o,l",[org,input.orderId,input.orderLineId]);
        if(!line.rows[0]) throw new V2ApplicationError("NOT_FOUND","The Order line is not available for replacement.");
        const source=await client.query<{id:string}>(`SELECT h.id FROM v2_fulfillment_handoffs h JOIN v2_fulfillment_handoff_lines hl ON hl.organization_id=h.organization_id AND hl.handoff_id=h.id
          WHERE h.organization_id=$1 AND h.order_document_id=$2 AND hl.order_line_id=$3 AND h.replacement_obligation_id IS NULL AND ($4::varchar IS NULL OR h.id=$4) ORDER BY h.completed_at DESC,h.id DESC LIMIT 1 FOR UPDATE OF h,hl`,[org,input.orderId,input.orderLineId,input.sourceFulfillmentHandoffId??null]);
        if(!source.rows[0]) throw new V2ApplicationError("CONFLICT","A replacement requires immutable original fulfillment history for this Order line.");
        const sources=await client.query<SourceWork>(`SELECT DISTINCT ON (w.requirement_key) w.id,w.order_document_id,w.order_line_id,w.requirement_key,w.artwork_assignment_id,w.artwork_file_id,w.prepress_unit_id,w.side,w.source_page_index,w.layer_key,w.layer_order
          FROM v2_production_works w WHERE w.organization_id=$1 AND w.order_document_id=$2 AND w.order_line_id=$3 AND w.replacement_obligation_id IS NULL
          ORDER BY w.requirement_key,w.created_at DESC,w.id DESC`,[org,input.orderId,input.orderLineId]);
        if(!sources.rows.length) throw new V2ApplicationError("CONFLICT","A replacement requires canonical completed Production work to establish new authority.");
        const id=randomUUID();
        const created=await client.query<ObligationRow>(`INSERT INTO v2_order_replacement_obligations(id,organization_id,order_document_id,order_line_id,source_fulfillment_handoff_id,source_shipment_id,predecessor_replacement_obligation_id,replacement_quantity,reason,responsibility,billing_treatment,note,status,created_principal_kind,created_principal_subject,created_staff_actor_user_id)
          VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'open',$13,$14,$15) RETURNING *`,[id,org,input.orderId,input.orderLineId,source.rows[0].id,input.sourceShipmentId??null,input.predecessorReplacementObligationId??null,input.replacementQuantity,input.reason,input.responsibility,input.billingTreatment,input.note??null,a.kind,a.subject,a.staffActorUserId??null]);
        const workIds:string[]=[];
        for(const sourceWork of sources.rows){const workId=randomUUID(); await client.query(`INSERT INTO v2_production_works(id,organization_id,order_document_id,order_line_id,requirement_key,artwork_assignment_id,artwork_file_id,prepress_unit_id,side,source_page_index,layer_key,layer_order,ordered_quantity,replacement_obligation_id,replacement_origin_production_work_id,created_principal_kind,created_principal_subject,created_staff_actor_user_id)
          VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)`,[workId,org,sourceWork.order_document_id,sourceWork.order_line_id,sourceWork.requirement_key,sourceWork.artwork_assignment_id,sourceWork.artwork_file_id,sourceWork.prepress_unit_id,sourceWork.side,sourceWork.source_page_index,sourceWork.layer_key,sourceWork.layer_order,input.replacementQuantity,id,sourceWork.id,a.kind,a.subject,a.staffActorUserId??null]);workIds.push(workId);}
        await this.event(client,org,id,1,"created",{ reason:input.reason, responsibility:input.responsibility, billingTreatment:input.billingTreatment, sourceFulfillmentHandoffId:source.rows[0].id },a);
        await this.event(client,org,id,2,"production_authority_created",{ productionWorkIds:workIds },a);
        const billingInvoice=input.billingTreatment==="billable"?await createOrReadReplacementInvoice(client,{organizationId:org,orderId:input.orderId,orderLineId:input.orderLineId,replacementObligationId:brandedId<"ReplacementObligationId">(id),replacementQuantity:input.replacementQuantity}):undefined;
        if(billingInvoice) await this.event(client,org,id,3,"billable_invoice_created",{invoiceId:billingInvoice.invoiceId,invoiceNumber:billingInvoice.invoiceNumber,totalCents:billingInvoice.totalCents,currency:billingInvoice.currency},a);
        const projected=await this.project(client,created.rows[0]!,workIds,billingInvoice);
        await this.requests.recordAttribution(client,{organizationId:org,operationRequestId:request.request.id,operation:"fulfillment.replacement.create.v1",resourceType:"replacement_obligation",resourceId:id,principalKind:a.kind,principalSubject:a.subject,staffActorUserId:a.staffActorUserId});
        await this.requests.succeed(client,org,request.request.id,{resourceType:"replacement_obligation",resourceId:id,resultJson:projected});
        return projected;
      });
      await this.lifecycle?.reconcileOrder(brandedId<"OrganizationId">(c.organizationId),input.orderId);
      return success(result);
    } catch(error) { return failure(this.error(error)); }
  }

  async list(c:OperationContext, orderId:OrderId):Promise<ApplicationResult<readonly ReplacementObligationProjection[]>> { try { requireOperationPrincipalScope(c); this.require(c); return success(await this.transaction(async client=>{const rows=await client.query<ObligationRow>("SELECT * FROM v2_order_replacement_obligations WHERE organization_id=$1 AND order_document_id=$2 ORDER BY created_at,id",[c.organizationId,orderId]); return Promise.all(rows.rows.map(row=>this.project(client,row)));})); } catch(error) { return failure(this.error(error)); } }

  async cancel(c:OperationContext, input:Readonly<{businessRequestId:string;replacementObligationId:ReplacementObligationId}>):Promise<ApplicationResult<ReplacementObligationProjection>> { try { requireOperationPrincipalScope(c); this.require(c); if(!input.businessRequestId)throw new V2ApplicationError("VALIDATION_ERROR","businessRequestId is required."); const result=await this.transaction(async client=>{const a=actor(c),row=await client.query<ObligationRow>("SELECT * FROM v2_order_replacement_obligations WHERE organization_id=$1 AND id=$2 FOR UPDATE",[c.organizationId,input.replacementObligationId]);const current=row.rows[0];if(!current)throw new V2ApplicationError("NOT_FOUND","Replacement obligation was not found.");if(current.status!=="open")throw new V2ApplicationError("CONFLICT","Only an unproduced replacement obligation can be cancelled.");const invoice=await client.query<{id:string}>("SELECT id FROM v2_billing_invoices WHERE organization_id=$1 AND replacement_obligation_id=$2 FOR UPDATE",[c.organizationId,current.id]);if(invoice.rows[0])throw new V2ApplicationError("CONFLICT","A billable replacement Invoice already exists and cannot be cancelled or converted to no-charge here.");const active=await client.query<{exists:boolean}>(`SELECT EXISTS(SELECT 1 FROM v2_production_works w LEFT JOIN v2_production_attempts a ON a.organization_id=w.organization_id AND a.production_work_id=w.id WHERE w.organization_id=$1 AND w.replacement_obligation_id=$2 AND a.id IS NOT NULL) exists`,[c.organizationId,current.id]);if(active.rows[0]?.exists)throw new V2ApplicationError("CONFLICT","Replacement Production history exists and cannot be cancelled.");const reserved=await client.query<{exists:boolean}>(`SELECT EXISTS(SELECT 1 FROM v2_fulfillment_shipment_prepared_revision_lines line JOIN v2_fulfillment_shipments shipment ON shipment.organization_id=line.organization_id AND shipment.id=line.shipment_id WHERE line.organization_id=$1 AND line.replacement_obligation_id=$2 AND shipment.shipment_status='prepared' AND shipment.prepared_revision_id=line.revision_id) exists`,[c.organizationId,current.id]);if(reserved.rows[0]?.exists)throw new V2ApplicationError("CONFLICT","Void or correct the prepared replacement shipment reservation before cancelling this obligation.");await client.query("UPDATE v2_order_replacement_obligations SET status='cancelled' WHERE organization_id=$1 AND id=$2",[c.organizationId,current.id]);await this.event(client,c.organizationId,current.id,await this.nextSequence(client,c.organizationId,current.id),"cancelled",{},a);return this.project(client,{...current,status:"cancelled"});});await this.lifecycle?.reconcileOrder(brandedId<"OrganizationId">(c.organizationId),result.obligation.orderId);return success(result);}catch(error){return failure(this.error(error));} }

  private async project(client:PoolClient,row:ObligationRow,knownWorkIds?:readonly string[],knownInvoice?:ReplacementInvoiceProjection):Promise<ReplacementObligationProjection>{const works=knownWorkIds?[...knownWorkIds]:(await client.query<{id:string}>("SELECT id FROM v2_production_works WHERE organization_id=$1 AND replacement_obligation_id=$2 ORDER BY id",[row.organization_id,row.id])).rows.map(value=>value.id);const quantities=await client.query<{produced:string;fulfilled:string}>(`SELECT COALESCE((SELECT min(v2_usable_production_good_quantity(w.organization_id,w.id)) FROM v2_production_works w WHERE w.organization_id=$1 AND w.replacement_obligation_id=$2),0)::text produced,COALESCE((SELECT sum(hl.quantity) FROM v2_fulfillment_handoffs h JOIN v2_fulfillment_handoff_lines hl ON hl.organization_id=h.organization_id AND hl.handoff_id=h.id WHERE h.organization_id=$1 AND h.replacement_obligation_id=$2),0)::text fulfilled`,[row.organization_id,row.id]);const invoice=knownInvoice??(await client.query<{id:string;invoice_display_number:string;invoice_state:"draft"|"issued"|"void";currency:string;total_cents:string}>("SELECT id,invoice_display_number,invoice_state,currency,total_cents FROM v2_billing_invoices WHERE organization_id=$1 AND replacement_obligation_id=$2",[row.organization_id,row.id])).rows[0];const replacementInvoice=invoice?"invoiceId" in invoice?invoice:{invoiceId:brandedId<"InvoiceId">(invoice.id),invoiceNumber:invoice.invoice_display_number,lifecycle:invoice.invoice_state,currency:invoice.currency,totalCents:Number(invoice.total_cents)}:undefined;const remaining=replacementRemainingQuantity(row.replacement_quantity,Number(quantities.rows[0]?.produced??0),Number(quantities.rows[0]?.fulfilled??0));const events=await client.query<{sequence:number;event_kind:ReplacementObligationEvent["kind"];detail:Record<string,unknown>;created_at:Date;created_principal_kind:ReplacementObligationEvent["createdPrincipalKind"];created_principal_subject:string}>("SELECT sequence,event_kind,detail,created_at,created_principal_kind,created_principal_subject FROM v2_order_replacement_obligation_events WHERE organization_id=$1 AND replacement_obligation_id=$2 ORDER BY sequence",[row.organization_id,row.id]);return {obligation:obligation(row,works),...remaining,billingPending:row.billing_treatment==="billable"&&!replacementInvoice,...(replacementInvoice?{billingInvoice:replacementInvoice}:{}),events:events.rows.map(value=>({sequence:value.sequence,kind:value.event_kind,detail:value.detail,createdAt:value.created_at.toISOString(),createdPrincipalKind:value.created_principal_kind,createdPrincipalSubject:value.created_principal_subject}))};}
  private async nextSequence(client:PoolClient,org:string,id:string){const row=await client.query<{n:string}>("SELECT COALESCE(max(sequence),0)+1 n FROM v2_order_replacement_obligation_events WHERE organization_id=$1 AND replacement_obligation_id=$2",[org,id]);return Number(row.rows[0]!.n);}
  private async event(client:PoolClient,org:string,id:string,sequence:number,kind:ReplacementObligationEvent["kind"],detail:Record<string,unknown>,a:Actor){await client.query("INSERT INTO v2_order_replacement_obligation_events(organization_id,replacement_obligation_id,sequence,event_kind,detail,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8)",[org,id,sequence,kind,JSON.stringify(detail),a.kind,a.subject,a.staffActorUserId??null]);}
  private async transaction<T>(work:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");const result=await work(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  private require(c:OperationContext){if(c.principal.kind!=="staff"||!this.authority.decide(c.principal,{capability:"fulfillment.replace",resource:{organizationId:c.organizationId}}).allowed)throw new V2ApplicationError("FORBIDDEN","The principal does not have authority to manage replacements.");}
  private error(error:unknown){return error instanceof V2ApplicationError?error:new V2ApplicationError("VALIDATION_ERROR",error instanceof Error?error.message:"Replacement obligation is unavailable.");}
}
