/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAppearanceRouteImport } from './routes/_shell.appearance'
import { Route as ShellArtworkRouteImport } from './routes/_shell.artwork'
import { Route as ShellAssistantRouteImport } from './routes/_shell.assistant'
import { Route as ShellBugsRouteImport } from './routes/_shell.bugs'
import { Route as ShellCommunicationsRouteImport } from './routes/_shell.communications'
import { Route as ShellContactsRouteImport } from './routes/_shell.contacts'
import { Route as ShellCustomersRouteImport } from './routes/_shell.customers'
import { Route as ShellDesignRouteImport } from './routes/_shell.design'
import { Route as ShellFormulaLibraryRouteImport } from './routes/_shell.formula-library'
import { Route as ShellFulfillmentRouteImport } from './routes/_shell.fulfillment'
import { Route as ShellInboundRouteImport } from './routes/_shell.inbound'
import { Route as ShellIntegrationsRouteImport } from './routes/_shell.integrations'
import { Route as ShellInventoryRouteImport } from './routes/_shell.inventory'
import { Route as ShellInvoicesRouteImport } from './routes/_shell.invoices'
import { Route as ShellMaterialsRouteImport } from './routes/_shell.materials'
import { Route as ShellNestingRouteImport } from './routes/_shell.nesting'
import { Route as ShellOrdersRouteImport } from './routes/_shell.orders'
import { Route as ShellPaymentsRouteImport } from './routes/_shell.payments'
import { Route as ShellPrepressRouteImport } from './routes/_shell.prepress'
import { Route as ShellProcurementRouteImport } from './routes/_shell.procurement'
import { Route as ShellProductBuilderRouteImport } from './routes/_shell.product-builder'
import { Route as ShellProductionRouteImport } from './routes/_shell.production'
import { Route as ShellProductsRouteImport } from './routes/_shell.products'
import { Route as ShellProofingRouteImport } from './routes/_shell.proofing'
import { Route as ShellQuotesRouteImport } from './routes/_shell.quotes'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellRoutingRouteImport } from './routes/_shell.routing'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellShippingRouteImport } from './routes/_shell.shipping'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as StorefrontSlugRouteImport } from './routes/storefront.$slug'
import { Route as ShellContactsIndexRouteImport } from './routes/_shell.contacts.index'
import { Route as ShellContactsIdRouteImport } from './routes/_shell.contacts.$id'
import { Route as ShellCustomersIndexRouteImport } from './routes/_shell.customers.index'
import { Route as ShellCustomersIdRouteImport } from './routes/_shell.customers.$id'
import { Route as ShellFormulaLibraryIndexRouteImport } from './routes/_shell.formula-library.index'
import { Route as ShellFormulaLibraryIdRouteImport } from './routes/_shell.formula-library.$id'
import { Route as ShellInvoicesIndexRouteImport } from './routes/_shell.invoices.index'
import { Route as ShellInvoicesIdRouteImport } from './routes/_shell.invoices.$id'
import { Route as ShellProductsIdRouteImport } from './routes/_shell.products.$id'
import { Route as ShellSalesIdRouteImport } from './routes/_shell.sales.$id'
import { Route as ShellSettingsIndexRouteImport } from './routes/_shell.settings.index'
import { Route as ShellSettingsAccountingRouteImport } from './routes/_shell.settings.accounting'
import { Route as ShellSettingsBusinessProfileRouteImport } from './routes/_shell.settings.business-profile'
import { Route as ShellSettingsDocumentsRouteImport } from './routes/_shell.settings.documents'
import { Route as ShellSettingsEmailRouteImport } from './routes/_shell.settings.email'
import { Route as ShellSettingsInvoiceDefaultsRouteImport } from './routes/_shell.settings.invoice-defaults'
import { Route as ShellSettingsNotificationsRouteImport } from './routes/_shell.settings.notifications'
import { Route as ShellSettingsNumberingRouteImport } from './routes/_shell.settings.numbering'
import { Route as ShellSettingsPaymentsRouteImport } from './routes/_shell.settings.payments'
import { Route as ShellSettingsPermissionSetsRouteImport } from './routes/_shell.settings.permission-sets'
import { Route as ShellSettingsPortalAccessRouteImport } from './routes/_shell.settings.portal-access'
import { Route as ShellSettingsPreferencesRouteImport } from './routes/_shell.settings.preferences'
import { Route as ShellSettingsProductionConnectionsRouteImport } from './routes/_shell.settings.production-connections'
import { Route as ShellSettingsSalesTaxRouteImport } from './routes/_shell.settings.sales-tax'
import { Route as ShellSettingsShippingRouteImport } from './routes/_shell.settings.shipping'
import { Route as ShellSettingsStaffRouteImport } from './routes/_shell.settings.staff'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppearanceRoute = ShellAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArtworkRoute = ShellArtworkRouteImport.update({
  id: '/artwork',
  path: '/artwork',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssistantRoute = ShellAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBugsRoute = ShellBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCommunicationsRoute = ShellCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContactsRoute = ShellContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCustomersRoute = ShellCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDesignRoute = ShellDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFormulaLibraryRoute = ShellFormulaLibraryRouteImport.update({
  id: '/formula-library',
  path: '/formula-library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFulfillmentRoute = ShellFulfillmentRouteImport.update({
  id: '/fulfillment',
  path: '/fulfillment',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInboundRoute = ShellInboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsRoute = ShellIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInventoryRoute = ShellInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInvoicesRoute = ShellInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMaterialsRoute = ShellMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNestingRoute = ShellNestingRouteImport.update({
  id: '/nesting',
  path: '/nesting',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrdersRoute = ShellOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPaymentsRoute = ShellPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPrepressRoute = ShellPrepressRouteImport.update({
  id: '/prepress',
  path: '/prepress',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProcurementRoute = ShellProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductBuilderRoute = ShellProductBuilderRouteImport.update({
  id: '/product-builder',
  path: '/product-builder',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductionRoute = ShellProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductsRoute = ShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProofingRoute = ShellProofingRouteImport.update({
  id: '/proofing',
  path: '/proofing',
  getParentRoute: () => ShellRoute,
} as any)
const ShellQuotesRoute = ShellQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRoutingRoute = ShellRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellShippingRoute = ShellShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const StorefrontSlugRoute = StorefrontSlugRouteImport.update({
  id: '/storefront/$slug',
  path: '/storefront/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellContactsIndexRoute = ShellContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellContactsRoute,
} as any)
const ShellContactsIdRoute = ShellContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellContactsRoute,
} as any)
const ShellCustomersIndexRoute = ShellCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellCustomersRoute,
} as any)
const ShellCustomersIdRoute = ShellCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellCustomersRoute,
} as any)
const ShellFormulaLibraryIndexRoute =
  ShellFormulaLibraryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellFormulaLibraryRoute,
  } as any)
const ShellFormulaLibraryIdRoute = ShellFormulaLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellFormulaLibraryRoute,
} as any)
const ShellInvoicesIndexRoute = ShellInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellInvoicesRoute,
} as any)
const ShellInvoicesIdRoute = ShellInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellInvoicesRoute,
} as any)
const ShellProductsIdRoute = ShellProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellProductsRoute,
} as any)
const ShellSalesIdRoute = ShellSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsIndexRoute = ShellSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsAccountingRoute = ShellSettingsAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsBusinessProfileRoute =
  ShellSettingsBusinessProfileRouteImport.update({
    id: '/business-profile',
    path: '/business-profile',
    getParentRoute: () => ShellSettingsRoute,
  } as any)
const ShellSettingsDocumentsRoute = ShellSettingsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsEmailRoute = ShellSettingsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsInvoiceDefaultsRoute =
  ShellSettingsInvoiceDefaultsRouteImport.update({
    id: '/invoice-defaults',
    path: '/invoice-defaults',
    getParentRoute: () => ShellSettingsRoute,
  } as any)
const ShellSettingsNotificationsRoute =
  ShellSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ShellSettingsRoute,
  } as any)
const ShellSettingsNumberingRoute = ShellSettingsNumberingRouteImport.update({
  id: '/numbering',
  path: '/numbering',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsPaymentsRoute = ShellSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsPermissionSetsRoute =
  ShellSettingsPermissionSetsRouteImport.update({
    id: '/permission-sets',
    path: '/permission-sets',
    getParentRoute: () => ShellSettingsRoute,
  } as any)
const ShellSettingsPortalAccessRoute =
  ShellSettingsPortalAccessRouteImport.update({
    id: '/portal-access',
    path: '/portal-access',
    getParentRoute: () => ShellSettingsRoute,
  } as any)
const ShellSettingsPreferencesRoute =
  ShellSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => ShellSettingsRoute,
  } as any)
const ShellSettingsProductionConnectionsRoute =
  ShellSettingsProductionConnectionsRouteImport.update({
    id: '/production-connections',
    path: '/production-connections',
    getParentRoute: () => ShellSettingsRoute,
  } as any)
const ShellSettingsSalesTaxRoute = ShellSettingsSalesTaxRouteImport.update({
  id: '/sales-tax',
  path: '/sales-tax',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsShippingRoute = ShellSettingsShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsStaffRoute = ShellSettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ShellSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/appearance': typeof ShellAppearanceRoute
  '/artwork': typeof ShellArtworkRoute
  '/assistant': typeof ShellAssistantRoute
  '/bugs': typeof ShellBugsRoute
  '/communications': typeof ShellCommunicationsRoute
  '/contacts': typeof ShellContactsRouteWithChildren
  '/customers': typeof ShellCustomersRouteWithChildren
  '/design': typeof ShellDesignRoute
  '/formula-library': typeof ShellFormulaLibraryRouteWithChildren
  '/fulfillment': typeof ShellFulfillmentRoute
  '/inbound': typeof ShellInboundRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/inventory': typeof ShellInventoryRoute
  '/invoices': typeof ShellInvoicesRouteWithChildren
  '/materials': typeof ShellMaterialsRoute
  '/nesting': typeof ShellNestingRoute
  '/orders': typeof ShellOrdersRoute
  '/payments': typeof ShellPaymentsRoute
  '/prepress': typeof ShellPrepressRoute
  '/procurement': typeof ShellProcurementRoute
  '/product-builder': typeof ShellProductBuilderRoute
  '/production': typeof ShellProductionRoute
  '/products': typeof ShellProductsRouteWithChildren
  '/proofing': typeof ShellProofingRoute
  '/quotes': typeof ShellQuotesRoute
  '/reports': typeof ShellReportsRoute
  '/routing': typeof ShellRoutingRoute
  '/settings': typeof ShellSettingsRouteWithChildren
  '/shipping': typeof ShellShippingRoute
  '/users': typeof ShellUsersRoute
  '/storefront/$slug': typeof StorefrontSlugRoute
  '/contacts/$id': typeof ShellContactsIdRoute
  '/customers/$id': typeof ShellCustomersIdRoute
  '/formula-library/$id': typeof ShellFormulaLibraryIdRoute
  '/invoices/$id': typeof ShellInvoicesIdRoute
  '/products/$id': typeof ShellProductsIdRoute
  '/sales/$id': typeof ShellSalesIdRoute
  '/settings/accounting': typeof ShellSettingsAccountingRoute
  '/settings/business-profile': typeof ShellSettingsBusinessProfileRoute
  '/settings/documents': typeof ShellSettingsDocumentsRoute
  '/settings/email': typeof ShellSettingsEmailRoute
  '/settings/invoice-defaults': typeof ShellSettingsInvoiceDefaultsRoute
  '/settings/notifications': typeof ShellSettingsNotificationsRoute
  '/settings/numbering': typeof ShellSettingsNumberingRoute
  '/settings/payments': typeof ShellSettingsPaymentsRoute
  '/settings/permission-sets': typeof ShellSettingsPermissionSetsRoute
  '/settings/portal-access': typeof ShellSettingsPortalAccessRoute
  '/settings/preferences': typeof ShellSettingsPreferencesRoute
  '/settings/production-connections': typeof ShellSettingsProductionConnectionsRoute
  '/settings/sales-tax': typeof ShellSettingsSalesTaxRoute
  '/settings/shipping': typeof ShellSettingsShippingRoute
  '/settings/staff': typeof ShellSettingsStaffRoute
  '/contacts/': typeof ShellContactsIndexRoute
  '/customers/': typeof ShellCustomersIndexRoute
  '/formula-library/': typeof ShellFormulaLibraryIndexRoute
  '/invoices/': typeof ShellInvoicesIndexRoute
  '/settings/': typeof ShellSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/appearance': typeof ShellAppearanceRoute
  '/artwork': typeof ShellArtworkRoute
  '/assistant': typeof ShellAssistantRoute
  '/bugs': typeof ShellBugsRoute
  '/communications': typeof ShellCommunicationsRoute
  '/design': typeof ShellDesignRoute
  '/fulfillment': typeof ShellFulfillmentRoute
  '/inbound': typeof ShellInboundRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/inventory': typeof ShellInventoryRoute
  '/materials': typeof ShellMaterialsRoute
  '/nesting': typeof ShellNestingRoute
  '/orders': typeof ShellOrdersRoute
  '/payments': typeof ShellPaymentsRoute
  '/prepress': typeof ShellPrepressRoute
  '/procurement': typeof ShellProcurementRoute
  '/product-builder': typeof ShellProductBuilderRoute
  '/production': typeof ShellProductionRoute
  '/products': typeof ShellProductsRouteWithChildren
  '/proofing': typeof ShellProofingRoute
  '/quotes': typeof ShellQuotesRoute
  '/reports': typeof ShellReportsRoute
  '/routing': typeof ShellRoutingRoute
  '/shipping': typeof ShellShippingRoute
  '/users': typeof ShellUsersRoute
  '/storefront/$slug': typeof StorefrontSlugRoute
  '/': typeof ShellIndexRoute
  '/contacts/$id': typeof ShellContactsIdRoute
  '/customers/$id': typeof ShellCustomersIdRoute
  '/formula-library/$id': typeof ShellFormulaLibraryIdRoute
  '/invoices/$id': typeof ShellInvoicesIdRoute
  '/products/$id': typeof ShellProductsIdRoute
  '/sales/$id': typeof ShellSalesIdRoute
  '/settings/accounting': typeof ShellSettingsAccountingRoute
  '/settings/business-profile': typeof ShellSettingsBusinessProfileRoute
  '/settings/documents': typeof ShellSettingsDocumentsRoute
  '/settings/email': typeof ShellSettingsEmailRoute
  '/settings/invoice-defaults': typeof ShellSettingsInvoiceDefaultsRoute
  '/settings/notifications': typeof ShellSettingsNotificationsRoute
  '/settings/numbering': typeof ShellSettingsNumberingRoute
  '/settings/payments': typeof ShellSettingsPaymentsRoute
  '/settings/permission-sets': typeof ShellSettingsPermissionSetsRoute
  '/settings/portal-access': typeof ShellSettingsPortalAccessRoute
  '/settings/preferences': typeof ShellSettingsPreferencesRoute
  '/settings/production-connections': typeof ShellSettingsProductionConnectionsRoute
  '/settings/sales-tax': typeof ShellSettingsSalesTaxRoute
  '/settings/shipping': typeof ShellSettingsShippingRoute
  '/settings/staff': typeof ShellSettingsStaffRoute
  '/contacts': typeof ShellContactsIndexRoute
  '/customers': typeof ShellCustomersIndexRoute
  '/formula-library': typeof ShellFormulaLibraryIndexRoute
  '/invoices': typeof ShellInvoicesIndexRoute
  '/settings': typeof ShellSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/appearance': typeof ShellAppearanceRoute
  '/_shell/artwork': typeof ShellArtworkRoute
  '/_shell/assistant': typeof ShellAssistantRoute
  '/_shell/bugs': typeof ShellBugsRoute
  '/_shell/communications': typeof ShellCommunicationsRoute
  '/_shell/contacts': typeof ShellContactsRouteWithChildren
  '/_shell/customers': typeof ShellCustomersRouteWithChildren
  '/_shell/design': typeof ShellDesignRoute
  '/_shell/formula-library': typeof ShellFormulaLibraryRouteWithChildren
  '/_shell/fulfillment': typeof ShellFulfillmentRoute
  '/_shell/inbound': typeof ShellInboundRoute
  '/_shell/integrations': typeof ShellIntegrationsRoute
  '/_shell/inventory': typeof ShellInventoryRoute
  '/_shell/invoices': typeof ShellInvoicesRouteWithChildren
  '/_shell/materials': typeof ShellMaterialsRoute
  '/_shell/nesting': typeof ShellNestingRoute
  '/_shell/orders': typeof ShellOrdersRoute
  '/_shell/payments': typeof ShellPaymentsRoute
  '/_shell/prepress': typeof ShellPrepressRoute
  '/_shell/procurement': typeof ShellProcurementRoute
  '/_shell/product-builder': typeof ShellProductBuilderRoute
  '/_shell/production': typeof ShellProductionRoute
  '/_shell/products': typeof ShellProductsRouteWithChildren
  '/_shell/proofing': typeof ShellProofingRoute
  '/_shell/quotes': typeof ShellQuotesRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/routing': typeof ShellRoutingRoute
  '/_shell/settings': typeof ShellSettingsRouteWithChildren
  '/_shell/shipping': typeof ShellShippingRoute
  '/_shell/users': typeof ShellUsersRoute
  '/storefront/$slug': typeof StorefrontSlugRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/contacts/$id': typeof ShellContactsIdRoute
  '/_shell/customers/$id': typeof ShellCustomersIdRoute
  '/_shell/formula-library/$id': typeof ShellFormulaLibraryIdRoute
  '/_shell/invoices/$id': typeof ShellInvoicesIdRoute
  '/_shell/products/$id': typeof ShellProductsIdRoute
  '/_shell/sales/$id': typeof ShellSalesIdRoute
  '/_shell/settings/accounting': typeof ShellSettingsAccountingRoute
  '/_shell/settings/business-profile': typeof ShellSettingsBusinessProfileRoute
  '/_shell/settings/documents': typeof ShellSettingsDocumentsRoute
  '/_shell/settings/email': typeof ShellSettingsEmailRoute
  '/_shell/settings/invoice-defaults': typeof ShellSettingsInvoiceDefaultsRoute
  '/_shell/settings/notifications': typeof ShellSettingsNotificationsRoute
  '/_shell/settings/numbering': typeof ShellSettingsNumberingRoute
  '/_shell/settings/payments': typeof ShellSettingsPaymentsRoute
  '/_shell/settings/permission-sets': typeof ShellSettingsPermissionSetsRoute
  '/_shell/settings/portal-access': typeof ShellSettingsPortalAccessRoute
  '/_shell/settings/preferences': typeof ShellSettingsPreferencesRoute
  '/_shell/settings/production-connections': typeof ShellSettingsProductionConnectionsRoute
  '/_shell/settings/sales-tax': typeof ShellSettingsSalesTaxRoute
  '/_shell/settings/shipping': typeof ShellSettingsShippingRoute
  '/_shell/settings/staff': typeof ShellSettingsStaffRoute
  '/_shell/contacts/': typeof ShellContactsIndexRoute
  '/_shell/customers/': typeof ShellCustomersIndexRoute
  '/_shell/formula-library/': typeof ShellFormulaLibraryIndexRoute
  '/_shell/invoices/': typeof ShellInvoicesIndexRoute
  '/_shell/settings/': typeof ShellSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appearance'
    | '/artwork'
    | '/assistant'
    | '/bugs'
    | '/communications'
    | '/contacts'
    | '/customers'
    | '/design'
    | '/formula-library'
    | '/fulfillment'
    | '/inbound'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/materials'
    | '/nesting'
    | '/orders'
    | '/payments'
    | '/prepress'
    | '/procurement'
    | '/product-builder'
    | '/production'
    | '/products'
    | '/proofing'
    | '/quotes'
    | '/reports'
    | '/routing'
    | '/settings'
    | '/shipping'
    | '/users'
    | '/storefront/$slug'
    | '/contacts/$id'
    | '/customers/$id'
    | '/formula-library/$id'
    | '/invoices/$id'
    | '/products/$id'
    | '/sales/$id'
    | '/settings/accounting'
    | '/settings/business-profile'
    | '/settings/documents'
    | '/settings/email'
    | '/settings/invoice-defaults'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payments'
    | '/settings/permission-sets'
    | '/settings/portal-access'
    | '/settings/preferences'
    | '/settings/production-connections'
    | '/settings/sales-tax'
    | '/settings/shipping'
    | '/settings/staff'
    | '/contacts/'
    | '/customers/'
    | '/formula-library/'
    | '/invoices/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/appearance'
    | '/artwork'
    | '/assistant'
    | '/bugs'
    | '/communications'
    | '/design'
    | '/fulfillment'
    | '/inbound'
    | '/integrations'
    | '/inventory'
    | '/materials'
    | '/nesting'
    | '/orders'
    | '/payments'
    | '/prepress'
    | '/procurement'
    | '/product-builder'
    | '/production'
    | '/products'
    | '/proofing'
    | '/quotes'
    | '/reports'
    | '/routing'
    | '/shipping'
    | '/users'
    | '/storefront/$slug'
    | '/'
    | '/contacts/$id'
    | '/customers/$id'
    | '/formula-library/$id'
    | '/invoices/$id'
    | '/products/$id'
    | '/sales/$id'
    | '/settings/accounting'
    | '/settings/business-profile'
    | '/settings/documents'
    | '/settings/email'
    | '/settings/invoice-defaults'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payments'
    | '/settings/permission-sets'
    | '/settings/portal-access'
    | '/settings/preferences'
    | '/settings/production-connections'
    | '/settings/sales-tax'
    | '/settings/shipping'
    | '/settings/staff'
    | '/contacts'
    | '/customers'
    | '/formula-library'
    | '/invoices'
    | '/settings'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/appearance'
    | '/_shell/artwork'
    | '/_shell/assistant'
    | '/_shell/bugs'
    | '/_shell/communications'
    | '/_shell/contacts'
    | '/_shell/customers'
    | '/_shell/design'
    | '/_shell/formula-library'
    | '/_shell/fulfillment'
    | '/_shell/inbound'
    | '/_shell/integrations'
    | '/_shell/inventory'
    | '/_shell/invoices'
    | '/_shell/materials'
    | '/_shell/nesting'
    | '/_shell/orders'
    | '/_shell/payments'
    | '/_shell/prepress'
    | '/_shell/procurement'
    | '/_shell/product-builder'
    | '/_shell/production'
    | '/_shell/products'
    | '/_shell/proofing'
    | '/_shell/quotes'
    | '/_shell/reports'
    | '/_shell/routing'
    | '/_shell/settings'
    | '/_shell/shipping'
    | '/_shell/users'
    | '/storefront/$slug'
    | '/_shell/'
    | '/_shell/contacts/$id'
    | '/_shell/customers/$id'
    | '/_shell/formula-library/$id'
    | '/_shell/invoices/$id'
    | '/_shell/products/$id'
    | '/_shell/sales/$id'
    | '/_shell/settings/accounting'
    | '/_shell/settings/business-profile'
    | '/_shell/settings/documents'
    | '/_shell/settings/email'
    | '/_shell/settings/invoice-defaults'
    | '/_shell/settings/notifications'
    | '/_shell/settings/numbering'
    | '/_shell/settings/payments'
    | '/_shell/settings/permission-sets'
    | '/_shell/settings/portal-access'
    | '/_shell/settings/preferences'
    | '/_shell/settings/production-connections'
    | '/_shell/settings/sales-tax'
    | '/_shell/settings/shipping'
    | '/_shell/settings/staff'
    | '/_shell/contacts/'
    | '/_shell/customers/'
    | '/_shell/formula-library/'
    | '/_shell/invoices/'
    | '/_shell/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  StorefrontSlugRoute: typeof StorefrontSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/appearance': {
      id: '/_shell/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof ShellAppearanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/artwork': {
      id: '/_shell/artwork'
      path: '/artwork'
      fullPath: '/artwork'
      preLoaderRoute: typeof ShellArtworkRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assistant': {
      id: '/_shell/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof ShellAssistantRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bugs': {
      id: '/_shell/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof ShellBugsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/communications': {
      id: '/_shell/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof ShellCommunicationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contacts': {
      id: '/_shell/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ShellContactsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/customers': {
      id: '/_shell/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ShellCustomersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/design': {
      id: '/_shell/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof ShellDesignRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/formula-library': {
      id: '/_shell/formula-library'
      path: '/formula-library'
      fullPath: '/formula-library'
      preLoaderRoute: typeof ShellFormulaLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fulfillment': {
      id: '/_shell/fulfillment'
      path: '/fulfillment'
      fullPath: '/fulfillment'
      preLoaderRoute: typeof ShellFulfillmentRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inbound': {
      id: '/_shell/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof ShellInboundRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations': {
      id: '/_shell/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ShellIntegrationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inventory': {
      id: '/_shell/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ShellInventoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/invoices': {
      id: '/_shell/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof ShellInvoicesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/materials': {
      id: '/_shell/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof ShellMaterialsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/nesting': {
      id: '/_shell/nesting'
      path: '/nesting'
      fullPath: '/nesting'
      preLoaderRoute: typeof ShellNestingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders': {
      id: '/_shell/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShellOrdersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/payments': {
      id: '/_shell/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ShellPaymentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/prepress': {
      id: '/_shell/prepress'
      path: '/prepress'
      fullPath: '/prepress'
      preLoaderRoute: typeof ShellPrepressRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/procurement': {
      id: '/_shell/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ShellProcurementRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/product-builder': {
      id: '/_shell/product-builder'
      path: '/product-builder'
      fullPath: '/product-builder'
      preLoaderRoute: typeof ShellProductBuilderRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/production': {
      id: '/_shell/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ShellProductionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/products': {
      id: '/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShellProductsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/proofing': {
      id: '/_shell/proofing'
      path: '/proofing'
      fullPath: '/proofing'
      preLoaderRoute: typeof ShellProofingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/quotes': {
      id: '/_shell/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof ShellQuotesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/routing': {
      id: '/_shell/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof ShellRoutingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/shipping': {
      id: '/_shell/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShellShippingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/storefront/$slug': {
      id: '/storefront/$slug'
      path: '/storefront/$slug'
      fullPath: '/storefront/$slug'
      preLoaderRoute: typeof StorefrontSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/contacts/': {
      id: '/_shell/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ShellContactsIndexRouteImport
      parentRoute: typeof ShellContactsRoute
    }
    '/_shell/contacts/$id': {
      id: '/_shell/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ShellContactsIdRouteImport
      parentRoute: typeof ShellContactsRoute
    }
    '/_shell/customers/': {
      id: '/_shell/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof ShellCustomersIndexRouteImport
      parentRoute: typeof ShellCustomersRoute
    }
    '/_shell/customers/$id': {
      id: '/_shell/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof ShellCustomersIdRouteImport
      parentRoute: typeof ShellCustomersRoute
    }
    '/_shell/formula-library/': {
      id: '/_shell/formula-library/'
      path: '/'
      fullPath: '/formula-library/'
      preLoaderRoute: typeof ShellFormulaLibraryIndexRouteImport
      parentRoute: typeof ShellFormulaLibraryRoute
    }
    '/_shell/formula-library/$id': {
      id: '/_shell/formula-library/$id'
      path: '/$id'
      fullPath: '/formula-library/$id'
      preLoaderRoute: typeof ShellFormulaLibraryIdRouteImport
      parentRoute: typeof ShellFormulaLibraryRoute
    }
    '/_shell/invoices/': {
      id: '/_shell/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof ShellInvoicesIndexRouteImport
      parentRoute: typeof ShellInvoicesRoute
    }
    '/_shell/invoices/$id': {
      id: '/_shell/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof ShellInvoicesIdRouteImport
      parentRoute: typeof ShellInvoicesRoute
    }
    '/_shell/products/$id': {
      id: '/_shell/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ShellProductsIdRouteImport
      parentRoute: typeof ShellProductsRoute
    }
    '/_shell/sales/$id': {
      id: '/_shell/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof ShellSalesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/': {
      id: '/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ShellSettingsIndexRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/accounting': {
      id: '/_shell/settings/accounting'
      path: '/accounting'
      fullPath: '/settings/accounting'
      preLoaderRoute: typeof ShellSettingsAccountingRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/business-profile': {
      id: '/_shell/settings/business-profile'
      path: '/business-profile'
      fullPath: '/settings/business-profile'
      preLoaderRoute: typeof ShellSettingsBusinessProfileRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/documents': {
      id: '/_shell/settings/documents'
      path: '/documents'
      fullPath: '/settings/documents'
      preLoaderRoute: typeof ShellSettingsDocumentsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/email': {
      id: '/_shell/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof ShellSettingsEmailRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/invoice-defaults': {
      id: '/_shell/settings/invoice-defaults'
      path: '/invoice-defaults'
      fullPath: '/settings/invoice-defaults'
      preLoaderRoute: typeof ShellSettingsInvoiceDefaultsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/notifications': {
      id: '/_shell/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ShellSettingsNotificationsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/numbering': {
      id: '/_shell/settings/numbering'
      path: '/numbering'
      fullPath: '/settings/numbering'
      preLoaderRoute: typeof ShellSettingsNumberingRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/payments': {
      id: '/_shell/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof ShellSettingsPaymentsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/permission-sets': {
      id: '/_shell/settings/permission-sets'
      path: '/permission-sets'
      fullPath: '/settings/permission-sets'
      preLoaderRoute: typeof ShellSettingsPermissionSetsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/portal-access': {
      id: '/_shell/settings/portal-access'
      path: '/portal-access'
      fullPath: '/settings/portal-access'
      preLoaderRoute: typeof ShellSettingsPortalAccessRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/preferences': {
      id: '/_shell/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof ShellSettingsPreferencesRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/production-connections': {
      id: '/_shell/settings/production-connections'
      path: '/production-connections'
      fullPath: '/settings/production-connections'
      preLoaderRoute: typeof ShellSettingsProductionConnectionsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/sales-tax': {
      id: '/_shell/settings/sales-tax'
      path: '/sales-tax'
      fullPath: '/settings/sales-tax'
      preLoaderRoute: typeof ShellSettingsSalesTaxRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/shipping': {
      id: '/_shell/settings/shipping'
      path: '/shipping'
      fullPath: '/settings/shipping'
      preLoaderRoute: typeof ShellSettingsShippingRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/staff': {
      id: '/_shell/settings/staff'
      path: '/staff'
      fullPath: '/settings/staff'
      preLoaderRoute: typeof ShellSettingsStaffRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
  }
}

interface ShellContactsRouteChildren {
  ShellContactsIdRoute: typeof ShellContactsIdRoute
  ShellContactsIndexRoute: typeof ShellContactsIndexRoute
}

const ShellContactsRouteChildren: ShellContactsRouteChildren = {
  ShellContactsIdRoute: ShellContactsIdRoute,
  ShellContactsIndexRoute: ShellContactsIndexRoute,
}

const ShellContactsRouteWithChildren = ShellContactsRoute._addFileChildren(
  ShellContactsRouteChildren,
)

interface ShellCustomersRouteChildren {
  ShellCustomersIdRoute: typeof ShellCustomersIdRoute
  ShellCustomersIndexRoute: typeof ShellCustomersIndexRoute
}

const ShellCustomersRouteChildren: ShellCustomersRouteChildren = {
  ShellCustomersIdRoute: ShellCustomersIdRoute,
  ShellCustomersIndexRoute: ShellCustomersIndexRoute,
}

const ShellCustomersRouteWithChildren = ShellCustomersRoute._addFileChildren(
  ShellCustomersRouteChildren,
)

interface ShellFormulaLibraryRouteChildren {
  ShellFormulaLibraryIdRoute: typeof ShellFormulaLibraryIdRoute
  ShellFormulaLibraryIndexRoute: typeof ShellFormulaLibraryIndexRoute
}

const ShellFormulaLibraryRouteChildren: ShellFormulaLibraryRouteChildren = {
  ShellFormulaLibraryIdRoute: ShellFormulaLibraryIdRoute,
  ShellFormulaLibraryIndexRoute: ShellFormulaLibraryIndexRoute,
}

const ShellFormulaLibraryRouteWithChildren =
  ShellFormulaLibraryRoute._addFileChildren(ShellFormulaLibraryRouteChildren)

interface ShellInvoicesRouteChildren {
  ShellInvoicesIdRoute: typeof ShellInvoicesIdRoute
  ShellInvoicesIndexRoute: typeof ShellInvoicesIndexRoute
}

const ShellInvoicesRouteChildren: ShellInvoicesRouteChildren = {
  ShellInvoicesIdRoute: ShellInvoicesIdRoute,
  ShellInvoicesIndexRoute: ShellInvoicesIndexRoute,
}

const ShellInvoicesRouteWithChildren = ShellInvoicesRoute._addFileChildren(
  ShellInvoicesRouteChildren,
)

interface ShellProductsRouteChildren {
  ShellProductsIdRoute: typeof ShellProductsIdRoute
}

const ShellProductsRouteChildren: ShellProductsRouteChildren = {
  ShellProductsIdRoute: ShellProductsIdRoute,
}

const ShellProductsRouteWithChildren = ShellProductsRoute._addFileChildren(
  ShellProductsRouteChildren,
)

interface ShellSettingsRouteChildren {
  ShellSettingsAccountingRoute: typeof ShellSettingsAccountingRoute
  ShellSettingsBusinessProfileRoute: typeof ShellSettingsBusinessProfileRoute
  ShellSettingsDocumentsRoute: typeof ShellSettingsDocumentsRoute
  ShellSettingsEmailRoute: typeof ShellSettingsEmailRoute
  ShellSettingsInvoiceDefaultsRoute: typeof ShellSettingsInvoiceDefaultsRoute
  ShellSettingsNotificationsRoute: typeof ShellSettingsNotificationsRoute
  ShellSettingsNumberingRoute: typeof ShellSettingsNumberingRoute
  ShellSettingsPaymentsRoute: typeof ShellSettingsPaymentsRoute
  ShellSettingsPermissionSetsRoute: typeof ShellSettingsPermissionSetsRoute
  ShellSettingsPortalAccessRoute: typeof ShellSettingsPortalAccessRoute
  ShellSettingsPreferencesRoute: typeof ShellSettingsPreferencesRoute
  ShellSettingsProductionConnectionsRoute: typeof ShellSettingsProductionConnectionsRoute
  ShellSettingsSalesTaxRoute: typeof ShellSettingsSalesTaxRoute
  ShellSettingsShippingRoute: typeof ShellSettingsShippingRoute
  ShellSettingsStaffRoute: typeof ShellSettingsStaffRoute
  ShellSettingsIndexRoute: typeof ShellSettingsIndexRoute
}

const ShellSettingsRouteChildren: ShellSettingsRouteChildren = {
  ShellSettingsAccountingRoute: ShellSettingsAccountingRoute,
  ShellSettingsBusinessProfileRoute: ShellSettingsBusinessProfileRoute,
  ShellSettingsDocumentsRoute: ShellSettingsDocumentsRoute,
  ShellSettingsEmailRoute: ShellSettingsEmailRoute,
  ShellSettingsInvoiceDefaultsRoute: ShellSettingsInvoiceDefaultsRoute,
  ShellSettingsNotificationsRoute: ShellSettingsNotificationsRoute,
  ShellSettingsNumberingRoute: ShellSettingsNumberingRoute,
  ShellSettingsPaymentsRoute: ShellSettingsPaymentsRoute,
  ShellSettingsPermissionSetsRoute: ShellSettingsPermissionSetsRoute,
  ShellSettingsPortalAccessRoute: ShellSettingsPortalAccessRoute,
  ShellSettingsPreferencesRoute: ShellSettingsPreferencesRoute,
  ShellSettingsProductionConnectionsRoute:
    ShellSettingsProductionConnectionsRoute,
  ShellSettingsSalesTaxRoute: ShellSettingsSalesTaxRoute,
  ShellSettingsShippingRoute: ShellSettingsShippingRoute,
  ShellSettingsStaffRoute: ShellSettingsStaffRoute,
  ShellSettingsIndexRoute: ShellSettingsIndexRoute,
}

const ShellSettingsRouteWithChildren = ShellSettingsRoute._addFileChildren(
  ShellSettingsRouteChildren,
)

interface ShellRouteChildren {
  ShellAppearanceRoute: typeof ShellAppearanceRoute
  ShellArtworkRoute: typeof ShellArtworkRoute
  ShellAssistantRoute: typeof ShellAssistantRoute
  ShellBugsRoute: typeof ShellBugsRoute
  ShellCommunicationsRoute: typeof ShellCommunicationsRoute
  ShellContactsRoute: typeof ShellContactsRouteWithChildren
  ShellCustomersRoute: typeof ShellCustomersRouteWithChildren
  ShellDesignRoute: typeof ShellDesignRoute
  ShellFormulaLibraryRoute: typeof ShellFormulaLibraryRouteWithChildren
  ShellFulfillmentRoute: typeof ShellFulfillmentRoute
  ShellInboundRoute: typeof ShellInboundRoute
  ShellIntegrationsRoute: typeof ShellIntegrationsRoute
  ShellInventoryRoute: typeof ShellInventoryRoute
  ShellInvoicesRoute: typeof ShellInvoicesRouteWithChildren
  ShellMaterialsRoute: typeof ShellMaterialsRoute
  ShellNestingRoute: typeof ShellNestingRoute
  ShellOrdersRoute: typeof ShellOrdersRoute
  ShellPaymentsRoute: typeof ShellPaymentsRoute
  ShellPrepressRoute: typeof ShellPrepressRoute
  ShellProcurementRoute: typeof ShellProcurementRoute
  ShellProductBuilderRoute: typeof ShellProductBuilderRoute
  ShellProductionRoute: typeof ShellProductionRoute
  ShellProductsRoute: typeof ShellProductsRouteWithChildren
  ShellProofingRoute: typeof ShellProofingRoute
  ShellQuotesRoute: typeof ShellQuotesRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellRoutingRoute: typeof ShellRoutingRoute
  ShellSettingsRoute: typeof ShellSettingsRouteWithChildren
  ShellShippingRoute: typeof ShellShippingRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellSalesIdRoute: typeof ShellSalesIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAppearanceRoute: ShellAppearanceRoute,
  ShellArtworkRoute: ShellArtworkRoute,
  ShellAssistantRoute: ShellAssistantRoute,
  ShellBugsRoute: ShellBugsRoute,
  ShellCommunicationsRoute: ShellCommunicationsRoute,
  ShellContactsRoute: ShellContactsRouteWithChildren,
  ShellCustomersRoute: ShellCustomersRouteWithChildren,
  ShellDesignRoute: ShellDesignRoute,
  ShellFormulaLibraryRoute: ShellFormulaLibraryRouteWithChildren,
  ShellFulfillmentRoute: ShellFulfillmentRoute,
  ShellInboundRoute: ShellInboundRoute,
  ShellIntegrationsRoute: ShellIntegrationsRoute,
  ShellInventoryRoute: ShellInventoryRoute,
  ShellInvoicesRoute: ShellInvoicesRouteWithChildren,
  ShellMaterialsRoute: ShellMaterialsRoute,
  ShellNestingRoute: ShellNestingRoute,
  ShellOrdersRoute: ShellOrdersRoute,
  ShellPaymentsRoute: ShellPaymentsRoute,
  ShellPrepressRoute: ShellPrepressRoute,
  ShellProcurementRoute: ShellProcurementRoute,
  ShellProductBuilderRoute: ShellProductBuilderRoute,
  ShellProductionRoute: ShellProductionRoute,
  ShellProductsRoute: ShellProductsRouteWithChildren,
  ShellProofingRoute: ShellProofingRoute,
  ShellQuotesRoute: ShellQuotesRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellRoutingRoute: ShellRoutingRoute,
  ShellSettingsRoute: ShellSettingsRouteWithChildren,
  ShellShippingRoute: ShellShippingRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellSalesIdRoute: ShellSalesIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  StorefrontSlugRoute: StorefrontSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
