import type { TransactionalClient } from "../persistence/types.js";

export type PermissionPhysicalPostcondition = Readonly<{ id: string; passed: boolean; detail: string }>;
const tables = ["v2_permission_capabilities","v2_permission_set_templates","v2_permission_set_template_capabilities","v2_permission_organization_state","v2_permission_sets","v2_permission_set_capabilities","v2_staff_permission_set_assignments","v2_portal_permission_set_assignments","v2_organization_portal_capability_defaults","v2_customer_portal_ceiling_policies","v2_customer_portal_ceiling_capabilities","v2_permission_audit_events"] as const;
const indexes = ["v2_permission_sets_template_org_uidx","v2_permission_sets_org_active_idx","v2_staff_permission_set_assignments_lookup_idx","v2_portal_permission_set_assignments_lookup_idx","v2_permission_audit_events_org_created_idx"] as const;
const constraints = ["v2_permission_sets_id_org_uidx","v2_permission_sets_name_uidx","v2_staff_permission_set_assignments_uidx","v2_portal_permission_set_assignments_uidx","v2_staff_permission_set_assignments_member_org_fk","v2_staff_permission_set_assignments_set_org_fk","v2_portal_permission_set_assignments_access_org_fk","v2_portal_permission_set_assignments_set_org_fk","v2_customer_portal_ceiling_customer_org_fk"] as const;
const triggers = ["v2_permission_admin_floor_assignment","v2_permission_admin_floor_set","v2_permission_admin_floor_capability","v2_permission_admin_floor_membership","v2_permission_membership_authority_revision"] as const;
const functions = ["v2_assert_permission_admin_floor","v2_advance_permission_membership_revision"] as const;

/** Read-only proof that the M1.5 normalized authority storage is physically present. */
export async function checkV2M15PermissionPhysicalPostconditions(client: TransactionalClient): Promise<PermissionPhysicalPostcondition[]> {
  const [foundTables,foundIndexes,foundConstraints,columns,foundTriggers,foundFunctions] = await Promise.all([
    client.query<{table_name:string}>("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name=ANY($1::text[])",[tables]),
    client.query<{indexname:string;indexdef:string}>("SELECT indexname,indexdef FROM pg_indexes WHERE schemaname='public' AND indexname=ANY($1::text[])",[indexes]),
    client.query<{conname:string}>("SELECT conname FROM pg_constraint WHERE conname=ANY($1::text[])",[constraints]),
    client.query<{table_name:string;column_name:string;is_nullable:string}>("SELECT table_name,column_name,is_nullable FROM information_schema.columns WHERE table_schema='public' AND (table_name,column_name) IN (('v2_permission_sets','organization_id'),('v2_permission_sets','active'),('v2_permission_sets','principal_kind'),('v2_staff_permission_set_assignments','organization_id'),('v2_portal_permission_set_assignments','organization_id'),('v2_permission_organization_state','authority_revision'),('v2_permission_organization_state','admin_floor_enforced'),('v2_permission_audit_events','detail'))"),
    client.query<{tgname:string}>("SELECT tgname FROM pg_trigger WHERE NOT tgisinternal AND tgname=ANY($1::text[])",[triggers]),
    client.query<{proname:string}>("SELECT proname FROM pg_proc JOIN pg_namespace n ON n.oid=pronamespace WHERE n.nspname='public' AND proname=ANY($1::text[])",[functions]),
  ]);
  const tableSet=new Set(foundTables.rows.map(row=>row.table_name)); const indexMap=new Map(foundIndexes.rows.map(row=>[row.indexname,row.indexdef])); const constraintSet=new Set(foundConstraints.rows.map(row=>row.conname)); const columnMap=new Map(columns.rows.map(row=>[`${row.table_name}.${row.column_name}`,row.is_nullable]));const triggerSet=new Set(foundTriggers.rows.map(row=>row.tgname));const functionSet=new Set(foundFunctions.rows.map(row=>row.proname));
  const requiredColumns=["v2_permission_sets.organization_id","v2_permission_sets.active","v2_permission_sets.principal_kind","v2_staff_permission_set_assignments.organization_id","v2_portal_permission_set_assignments.organization_id","v2_permission_organization_state.authority_revision","v2_permission_organization_state.admin_floor_enforced","v2_permission_audit_events.detail"];
  return [...tables.map(id=>({id:`table:${id}`,passed:tableSet.has(id),detail:"required M1.5 permission table"})),...indexes.map(id=>({id:`index:${id}`,passed:indexMap.has(id),detail:"required organization-scoped index"})),...indexes.filter(id=>id.endsWith("uidx")).map(id=>({id:`unique-index:${id}`,passed:/\bUNIQUE\b/i.test(indexMap.get(id)??""),detail:"required scoped unique index"})),...constraints.map(id=>({id:`constraint:${id}`,passed:constraintSet.has(id),detail:"required tenant integrity constraint"})),...requiredColumns.map(id=>({id:`not-null:${id}`,passed:columnMap.get(id)==="NO",detail:"required non-null authority column"})),...triggers.map(id=>({id:`trigger:${id}`,passed:triggerSet.has(id),detail:"required deferred authority invariant trigger"})),...functions.map(id=>({id:`function:${id}`,passed:functionSet.has(id),detail:"required authority invariant function"}))];
}
export function assertV2M15PermissionPhysicalPostconditions(findings: readonly PermissionPhysicalPostcondition[]): void { const failed=findings.filter(f=>!f.passed); if(failed.length) throw new Error(`V2 M1.5 permission physical postconditions failed: ${failed.map(f=>f.id).join(", ")}`); }
