import type { TransactionalClient } from "../persistence/types.js";

export type PermissionPhysicalPostcondition = Readonly<{ id: string; passed: boolean; detail: string }>;
const tables = ["v2_permission_capabilities","v2_permission_set_templates","v2_permission_set_template_capabilities","v2_permission_organization_state","v2_permission_sets","v2_permission_set_capabilities","v2_staff_permission_set_assignments","v2_portal_permission_set_assignments","v2_organization_portal_capability_defaults","v2_customer_portal_ceiling_policies","v2_customer_portal_ceiling_capabilities","v2_permission_audit_events"] as const;
const indexes = ["v2_permission_sets_template_org_uidx","v2_permission_sets_org_active_idx","v2_permission_sets_live_name_uidx","v2_staff_permission_set_assignments_lookup_idx","v2_portal_permission_set_assignments_lookup_idx","v2_permission_audit_events_org_created_idx"] as const;
const constraints = ["v2_permission_sets_id_org_uidx","v2_permission_sets_archive_inactive_chk","v2_staff_permission_set_assignments_uidx","v2_portal_permission_set_assignments_uidx","v2_staff_permission_set_assignments_member_org_fk","v2_staff_permission_set_assignments_set_org_fk","v2_portal_permission_set_assignments_access_org_fk","v2_portal_permission_set_assignments_set_org_fk","v2_customer_portal_ceiling_customer_org_fk"] as const;
const triggers = ["v2_authority_entry_statement","v2_authority_scope_row","v2_structural_floor","v2_authority_fact_revision","v2_authority_access_revision","v2_authority_org_entry","v2_authority_org_scope","v2_authority_org_truncate"] as const;
const functions = ["v2_assert_permission_admin_floor","v2_authority_entry","v2_assert_authority_entry","v2_staff_login_ready","v2_staff_login_email_ready","v2_usable_structural_administrators","v2_assert_structural_authority","v2_authority_changed"] as const;
const guardedTables = ["users","auth_identities","user_organizations","v2_permission_organization_state","v2_permission_sets","v2_permission_set_capabilities","v2_staff_permission_set_assignments","v2_permission_capabilities","v2_staff_authority_enrollments","v2_organization_authority_enrollments","customer_portal_access","customer_portal_invite_tokens","v2_portal_password_reset_tokens","v2_portal_permission_set_assignments","v2_customer_portal_ceiling_policies","v2_customer_portal_ceiling_capabilities","v2_organization_portal_capability_defaults","org_invites"] as const;

/** Read-only proof that the M1.5 normalized authority storage is physically present. */
export async function checkV2M15PermissionPhysicalPostconditions(client: TransactionalClient): Promise<PermissionPhysicalPostcondition[]> {
  const [foundTables,foundIndexes,foundConstraints,columns,foundTriggers,foundFunctions,guards] = await Promise.all([
    client.query<{table_name:string}>("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name=ANY($1::text[])",[tables]),
    client.query<{indexname:string;indexdef:string}>("SELECT indexname,indexdef FROM pg_indexes WHERE schemaname='public' AND indexname=ANY($1::text[])",[indexes]),
    client.query<{conname:string}>("SELECT conname FROM pg_constraint WHERE conname=ANY($1::text[])",[constraints]),
    client.query<{table_name:string;column_name:string;is_nullable:string}>("SELECT table_name,column_name,is_nullable FROM information_schema.columns WHERE table_schema='public' AND (table_name,column_name) IN (('v2_permission_sets','organization_id'),('v2_permission_sets','active'),('v2_permission_sets','principal_kind'),('v2_permission_sets','archived_at'),('v2_staff_permission_set_assignments','organization_id'),('v2_portal_permission_set_assignments','organization_id'),('v2_permission_organization_state','authority_revision'),('v2_permission_organization_state','admin_floor_enforced'),('v2_permission_audit_events','detail'))"),
    client.query<{tgname:string}>("SELECT tgname FROM pg_trigger WHERE NOT tgisinternal AND tgname=ANY($1::text[])",[triggers]),
    client.query<{proname:string}>("SELECT proname FROM pg_proc JOIN pg_namespace n ON n.oid=pronamespace WHERE n.nspname='public' AND proname=ANY($1::text[])",[functions]),
    client.query<{table_name:string;tgname:string;tgdeferrable:boolean;tginitdeferred:boolean;tgenabled:string}>("SELECT c.relname table_name,t.tgname,t.tgdeferrable,t.tginitdeferred,t.tgenabled FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND NOT t.tgisinternal AND c.relname=ANY($1::text[])",[[...guardedTables,"organizations"]]),
  ]);
  const tableSet=new Set(foundTables.rows.map(row=>row.table_name)); const indexMap=new Map(foundIndexes.rows.map(row=>[row.indexname,row.indexdef])); const constraintSet=new Set(foundConstraints.rows.map(row=>row.conname)); const columnMap=new Map(columns.rows.map(row=>[`${row.table_name}.${row.column_name}`,row.is_nullable]));const triggerSet=new Set(foundTriggers.rows.map(row=>row.tgname));const functionSet=new Set(foundFunctions.rows.map(row=>row.proname));
  const requiredColumns=["v2_permission_sets.organization_id","v2_permission_sets.active","v2_permission_sets.principal_kind","v2_staff_permission_set_assignments.organization_id","v2_portal_permission_set_assignments.organization_id","v2_permission_organization_state.authority_revision","v2_permission_organization_state.admin_floor_enforced","v2_permission_audit_events.detail"];
  const nullableColumns=["v2_permission_sets.archived_at"];
  const guardChecks=[...guardedTables,"organizations"].map(table=>{
    const names=table==="organizations"?["v2_authority_org_entry","v2_authority_org_scope","v2_authority_org_truncate","v2_structural_floor"]:["v2_authority_entry_statement","v2_authority_scope_row","v2_structural_floor",...(table==="customer_portal_access"?["v2_authority_access_revision"]:[])];
    return{id:`authority-guards:${table}`,passed:names.every(name=>guards.rows.some(row=>row.table_name===table&&row.tgname===name&&row.tgenabled==="O"&&(name!=="v2_structural_floor"||(row.tgdeferrable&&row.tginitdeferred)))),detail:"enabled entry/scope and initially deferred structural-floor guards"};
  });
  return [...guardChecks,...tables.map(id=>({id:`table:${id}`,passed:tableSet.has(id),detail:"required M1.5 permission table"})),...indexes.map(id=>({id:`index:${id}`,passed:indexMap.has(id),detail:"required organization-scoped index"})),...indexes.filter(id=>id.endsWith("uidx")).map(id=>({id:`unique-index:${id}`,passed:/\bUNIQUE\b/i.test(indexMap.get(id)??""),detail:"required scoped unique index"})),...constraints.map(id=>({id:`constraint:${id}`,passed:constraintSet.has(id),detail:"required tenant integrity constraint"})),...requiredColumns.map(id=>({id:`not-null:${id}`,passed:columnMap.get(id)==="NO",detail:"required non-null authority column"})),...nullableColumns.map(id=>({id:`nullable:${id}`,passed:columnMap.get(id)==="YES",detail:"required archive lifecycle column"})),...triggers.map(id=>({id:`trigger:${id}`,passed:triggerSet.has(id),detail:"required deferred authority invariant trigger"})),...functions.map(id=>({id:`function:${id}`,passed:functionSet.has(id),detail:"required authority invariant function"}))];
}
export function assertV2M15PermissionPhysicalPostconditions(findings: readonly PermissionPhysicalPostcondition[]): void { const failed=findings.filter(f=>!f.passed); if(failed.length) throw new Error(`V2 M1.5 permission physical postconditions failed: ${failed.map(f=>f.id).join(", ")}`); }
