import type { Pool } from "pg";
import { AuthorityPolicy } from "../../src/authorization/authorityPolicy.js";
import type { PortalPrincipal } from "../../src/authorization/principals.js";
import { V2ApplicationError } from "../../src/errors/applicationError.js";
import { brandedId } from "../../src/modules/shared/commercialValues.js";

export type PortalProofArtifact=Readonly<{artworkFileId:string;position:number;filename:string;contentType:string;viewUrl:string}>;
export type PortalProof=Readonly<{proofVersionId:string;proofWorkId:string;orderId:string;orderNumber:string;lineDescription:string;revision:number;issuedAt:string;status:"awaiting_response"|"approved"|"revision_requested"|"superseded";actionable:boolean;response?:Readonly<{outcome:"approved"|"revision_requested";comment?:string;respondedAt:string}>;artifacts:readonly PortalProofArtifact[]}>;
type Header={proof_version_id:string;proof_work_id:string;order_id:string;display_number:string;line_description:string;sequence:number;issued_at:Date;latest_sequence:number;outcome:"approved"|"revision_requested"|null;comment:string|null;responded_at:Date|null};

/** Authenticated customer projection. Organization/customer identity comes
 * exclusively from the freshly verified portal principal. */
export class PostgresPortalProofRead{
  constructor(private readonly pool:Pool,private readonly files:Readonly<{file(organizationId:string,artworkFileId:string):Promise<Readonly<{contentType:string;bytes:Uint8Array}>>}>,private readonly authority=new AuthorityPolicy()){}
  async list(principal:PortalPrincipal):Promise<readonly PortalProof[]>{this.require(principal);const rows=await this.pool.query<Header>(`${this.base()} WHERE v.organization_id=$1 AND d.customer_id=$2 AND v.issued_at IS NOT NULL ORDER BY v.issued_at DESC,v.id DESC`,[principal.organizationId,principal.customerId]);return Promise.all(rows.rows.map(row=>this.project(principal,row)));}
  async get(principal:PortalPrincipal,proofVersionId:string):Promise<PortalProof>{this.require(principal);const rows=await this.pool.query<Header>(`${this.base()} WHERE v.organization_id=$1 AND d.customer_id=$2 AND v.id=$3 AND v.issued_at IS NOT NULL`,[principal.organizationId,principal.customerId,proofVersionId]);if(!rows.rows[0])throw new V2ApplicationError("NOT_FOUND","Proof was not found.");return this.project(principal,rows.rows[0]);}
  async file(principal:PortalPrincipal,proofVersionId:string,artworkFileId:string):Promise<Readonly<{filename:string;contentType:string;bytes:Uint8Array}>>{await this.get(principal,proofVersionId);const found=await this.pool.query<{display_filename:string;content_type:string}>(`SELECT f.display_filename,f.content_type FROM v2_proof_version_artwork p JOIN v2_artwork_files f ON f.organization_id=p.organization_id AND f.id=p.artwork_file_id JOIN v2_proof_versions v ON v.organization_id=p.organization_id AND v.id=p.proof_version_id JOIN v2_proof_works w ON w.organization_id=v.organization_id AND w.id=v.proof_work_id JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id WHERE p.organization_id=$1 AND p.proof_version_id=$2 AND p.artwork_file_id=$3 AND d.customer_id=$4 AND v.issued_at IS NOT NULL`,[principal.organizationId,proofVersionId,artworkFileId,principal.customerId]);if(!found.rows[0])throw new V2ApplicationError("NOT_FOUND","Proof file was not found.");const content=await this.files.file(principal.organizationId,brandedId<"ArtworkFileId">(artworkFileId));return{filename:found.rows[0].display_filename,contentType:content.contentType||found.rows[0].content_type,bytes:content.bytes};}
  private require(principal:PortalPrincipal){if(!this.authority.decide(principal,{capability:"proof.view",resource:{organizationId:principal.organizationId,customerId:principal.customerId}}).allowed)throw new V2ApplicationError("NOT_FOUND","Proof was not found.");}
  private base(){return`SELECT v.id proof_version_id,w.id proof_work_id,d.id order_id,d.display_number,l.description line_description,v.sequence,v.issued_at,latest.latest_sequence,r.outcome,r.comment,r.responded_at FROM v2_proof_versions v JOIN v2_proof_works w ON w.organization_id=v.organization_id AND w.id=v.proof_work_id JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id JOIN v2_sales_document_lines l ON l.organization_id=w.organization_id AND l.id=w.order_line_id JOIN LATERAL (SELECT max(sequence)::int latest_sequence FROM v2_proof_versions WHERE organization_id=v.organization_id AND proof_work_id=v.proof_work_id AND issued_at IS NOT NULL) latest ON true LEFT JOIN v2_proof_responses r ON r.organization_id=v.organization_id AND r.proof_version_id=v.id`;}
  private async project(principal:PortalPrincipal,row:Header):Promise<PortalProof>{const artifacts=await this.pool.query<{artwork_file_id:string;position:number;display_filename:string;content_type:string}>("SELECT p.artwork_file_id,p.position,f.display_filename,f.content_type FROM v2_proof_version_artwork p JOIN v2_artwork_files f ON f.organization_id=p.organization_id AND f.id=p.artwork_file_id WHERE p.organization_id=$1 AND p.proof_version_id=$2 ORDER BY p.position",[principal.organizationId,row.proof_version_id]);const superseded=row.sequence<row.latest_sequence,status:PortalProof["status"]=superseded?"superseded":row.outcome??"awaiting_response";return{proofVersionId:row.proof_version_id,proofWorkId:row.proof_work_id,orderId:row.order_id,orderNumber:row.display_number,lineDescription:row.line_description,revision:row.sequence,issuedAt:row.issued_at.toISOString(),status,actionable:!superseded&&!row.outcome,...(row.outcome&&row.responded_at?{response:{outcome:row.outcome,...(row.comment?{comment:row.comment}:{}),respondedAt:row.responded_at.toISOString()}}:{}),artifacts:artifacts.rows.map(file=>({artworkFileId:file.artwork_file_id,position:file.position,filename:file.display_filename,contentType:file.content_type,viewUrl:`/v2/portal/proofs/${encodeURIComponent(row.proof_version_id)}/files/${encodeURIComponent(file.artwork_file_id)}`}))};}
}
