import type { Pool, PoolClient } from "pg";
import { PostgresOperationRequestRepository } from "../persistence/postgresOperationRequests.js";
import type { ProofingTransaction, ProofingTransactionRunner } from "../../src/modules/proofing/proofingApplication.js";
import type { ProofResponse, ProofVersion, ProofVersionArtwork, ProofVersionProjection, ProofWork, ProofWorkProjection, ProofWorkQueueItem } from "../../src/modules/proofing/contracts.js";
import { brandedId, type ArtworkAssignmentId, type OrganizationId, type ProofVersionId, type ProofWorkId } from "../../src/modules/shared/commercialValues.js";

type WorkRow = { id:string; organization_id:string; order_document_id:string; order_line_id:string; created_at:Date; created_principal_kind:ProofWork["createdPrincipalKind"]; created_principal_subject:string; created_staff_actor_user_id:string|null };
type VersionRow = { id:string; organization_id:string; proof_work_id:string; sequence:number; created_at:Date; created_principal_kind:ProofVersion["createdPrincipalKind"]; created_principal_subject:string; created_staff_actor_user_id:string|null; issued_at:Date|null; issued_principal_kind:ProofVersion["issuedPrincipalKind"]|null; issued_principal_subject:string|null; issued_staff_actor_user_id:string|null };
type ArtRow = { proof_version_id:string; position:number; artwork_assignment_id:string; artwork_file_id:string };
type ResponseRow = { id:string; organization_id:string; proof_version_id:string; outcome:ProofResponse["outcome"]; comment:string|null; response_origin:ProofResponse["origin"]; recorded_customer_id:string|null; responder_principal_kind:ProofResponse["responderPrincipalKind"]; responder_principal_subject:string; responder_staff_actor_user_id:string|null; responded_at:Date };
const work = (r:WorkRow): ProofWork => ({ proofWorkId:brandedId<"ProofWorkId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),orderId:brandedId<"OrderId">(r.order_document_id),orderLineId:brandedId<"OrderLineId">(r.order_line_id),createdAt:r.created_at.toISOString(),createdPrincipalKind:r.created_principal_kind,createdPrincipalSubject:r.created_principal_subject,...(r.created_staff_actor_user_id?{createdStaffActorUserId:r.created_staff_actor_user_id}:{}) });
const response = (r:ResponseRow): ProofResponse => ({ proofResponseId:brandedId<"ProofResponseId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),proofVersionId:brandedId<"ProofVersionId">(r.proof_version_id),outcome:r.outcome,...(r.comment?{comment:r.comment}:{}),origin:r.response_origin,...(r.recorded_customer_id?{recordedCustomerId:brandedId<"CustomerId">(r.recorded_customer_id)}:{}),respondedAt:r.responded_at.toISOString(),responderPrincipalKind:r.responder_principal_kind,responderPrincipalSubject:r.responder_principal_subject,...(r.responder_staff_actor_user_id?{responderStaffActorUserId:r.responder_staff_actor_user_id}:{}) });
const version = (r:VersionRow, artwork:readonly ProofVersionArtwork[]): ProofVersion => ({ proofVersionId:brandedId<"ProofVersionId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),proofWorkId:brandedId<"ProofWorkId">(r.proof_work_id),sequence:r.sequence,artwork,createdAt:r.created_at.toISOString(),createdPrincipalKind:r.created_principal_kind,createdPrincipalSubject:r.created_principal_subject,...(r.created_staff_actor_user_id?{createdStaffActorUserId:r.created_staff_actor_user_id}:{}),...(r.issued_at?{issuedAt:r.issued_at.toISOString(),issuedPrincipalKind:r.issued_principal_kind!,issuedPrincipalSubject:r.issued_principal_subject!,...(r.issued_staff_actor_user_id?{issuedStaffActorUserId:r.issued_staff_actor_user_id}:{})}:{}) });

export type ProofingPersistenceTestHooks = Readonly<{ afterWork?:()=>Promise<void>; afterVersion?:()=>Promise<void>; afterIssue?:()=>Promise<void>; afterResponse?:()=>Promise<void>; afterAudit?:()=>Promise<void> }>;
export class PostgresProofingTransaction implements ProofingTransaction {
  private readonly requests=new PostgresOperationRequestRepository();
  constructor(private readonly client:PoolClient,private readonly hooks?:ProofingPersistenceTestHooks) {}
  async reserve(input:Parameters<ProofingTransaction["reserve"]>[0]) { const r=await this.requests.reserve(this.client,input);return {kind:r.kind,request:{id:r.request.id,resultJson:r.request.resultJson}}; }
  async succeed(org:string,id:string,result:Parameters<ProofingTransaction["succeed"]>[2]) { const target=result.response?result.response.proofResponseId:result.version?result.version.proofVersionId:result.work.proofWorkId;await this.requests.succeed(this.client,org,id,{resourceType:result.response?"proof_response":result.version?"proof_version":"proof_work",resourceId:target,resultJson:result}); }
  async attribute(input:Parameters<ProofingTransaction["attribute"]>[0]) { await this.requests.recordAttribution(this.client,{organizationId:input.organizationId,operationRequestId:input.requestId,operation:input.operation,resourceType:input.resourceType,resourceId:input.resourceId,principalKind:input.principalKind,principalSubject:input.principalSubject,staffActorUserId:input.staffActorUserId}); }
  async audit(input:Parameters<ProofingTransaction["audit"]>[0]) { const type=input.eventType==="proof_work_started"?"proof_work":input.eventType==="proof_version_created"||input.eventType==="proof_issued"?"proof_version":"proof_response";await this.client.query("INSERT INTO v2_audit_events(organization_id,operation_request_id,operation,event_type,resource_type,resource_id,principal_kind,principal_subject,staff_actor_user_id,changes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)",[input.organizationId,input.requestId,input.operation,input.eventType,type,input.resourceId,input.principalKind,input.principalSubject,input.staffActorUserId??null,JSON.stringify([{kind:input.eventType,summary:input.summary}])]);await this.hooks?.afterAudit?.(); }
  async findWork(org:OrganizationId,id:ProofWorkId){const r=await this.client.query<WorkRow>("SELECT * FROM v2_proof_works WHERE organization_id=$1 AND id=$2",[org,id]);return r.rows[0]?work(r.rows[0]):null;}
  async lockWork(org:OrganizationId,id:ProofWorkId){const r=await this.client.query<WorkRow>("SELECT * FROM v2_proof_works WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,id]);return r.rows[0]?work(r.rows[0]):null;}
  async createOrGetWork(input:Parameters<ProofingTransaction["createOrGetWork"]>[0]) { const r=await this.client.query<WorkRow>("INSERT INTO v2_proof_works(id,organization_id,order_document_id,order_line_id,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(organization_id,order_line_id) DO NOTHING RETURNING *",[input.id,input.organizationId,input.orderId,input.orderLineId,input.principalKind,input.principalSubject,input.staffActorUserId??null]);if(r.rows[0]){await this.hooks?.afterWork?.();return work(r.rows[0]);}const prior=await this.client.query<WorkRow>("SELECT * FROM v2_proof_works WHERE organization_id=$1 AND order_line_id=$2 FOR UPDATE",[input.organizationId,input.orderLineId]);if(!prior.rows[0])throw Error("Proof Work race could not reload its authoritative row.");return work(prior.rows[0]); }
  async readWork(org:OrganizationId,id:ProofWorkId):Promise<ProofWorkProjection|null>{const w=await this.findWork(org,id);if(!w)return null;const rows=await this.versions(org,id);return {work:w,versions:rows};}
  async listWorkQueue(org:OrganizationId,limit:number):Promise<readonly ProofWorkQueueItem[]>{
    const rows=await this.client.query<WorkRow & {display_number:string;customer_display_name:string;line_description:string;latest_sequence:number|null;latest_issued_at:Date|null;latest_outcome:ProofResponse["outcome"]|null}>("SELECT w.*,d.display_number,COALESCE(c.display_name,c.company_name,'Customer') customer_display_name,l.description line_description,v.sequence latest_sequence,v.issued_at latest_issued_at,r.outcome latest_outcome FROM v2_proof_works w JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id AND o.commercial_state='open' AND o.archived_at IS NULL JOIN v2_sales_document_lines l ON l.organization_id=w.organization_id AND l.id=w.order_line_id JOIN customers c ON c.organization_id=d.organization_id AND c.id=d.customer_id LEFT JOIN LATERAL (SELECT * FROM v2_proof_versions WHERE organization_id=w.organization_id AND proof_work_id=w.id ORDER BY sequence DESC LIMIT 1) v ON true LEFT JOIN v2_proof_responses r ON r.organization_id=v.organization_id AND r.proof_version_id=v.id WHERE w.organization_id=$1 ORDER BY w.created_at DESC LIMIT $2",[org,limit]);
    return rows.rows.map((row)=>({work:work(row),orderNumber:row.display_number,customerDisplayName:row.customer_display_name,lineDescription:row.line_description,...(row.latest_sequence===null?{}:{latest:{sequence:row.latest_sequence,...(row.latest_issued_at?{issuedAt:row.latest_issued_at.toISOString()}:{}),...(row.latest_outcome?{outcome:row.latest_outcome}:{})}})}));
  }
  async listOrderWorks(org:OrganizationId,orderId:any):Promise<readonly ProofWorkProjection[]>{
    const rows=await this.client.query<{id:string}>("SELECT id FROM v2_proof_works WHERE organization_id=$1 AND order_document_id=$2 ORDER BY created_at DESC,id DESC",[org,orderId]);
    return Promise.all(rows.rows.map((row)=>this.readWork(org,brandedId<"ProofWorkId">(row.id)).then((value)=>value!)));
  }
  async latestVersion(org:OrganizationId,workId:ProofWorkId){const r=await this.client.query<VersionRow>("SELECT * FROM v2_proof_versions WHERE organization_id=$1 AND proof_work_id=$2 ORDER BY sequence DESC LIMIT 1",[org,workId]);return r.rows[0]?this.project(r.rows[0]):null;}
  async findVersion(org:OrganizationId,id:ProofVersionId){const r=await this.client.query<VersionRow>("SELECT * FROM v2_proof_versions WHERE organization_id=$1 AND id=$2",[org,id]);return r.rows[0]?this.project(r.rows[0]):null;}
  async createVersion(input:Parameters<ProofingTransaction["createVersion"]>[0]) { const valid=await this.client.query<{id:string}>("SELECT a.id FROM v2_artwork_assignments a JOIN v2_proof_works w ON w.organization_id=a.organization_id AND w.order_document_id=a.order_document_id AND w.order_line_id=a.order_line_id WHERE w.organization_id=$1 AND w.id=$2 AND a.id=ANY($3::text[])",[input.organizationId,input.proofWorkId,input.artworkAssignmentIds]);if(valid.rows.length!==input.artworkAssignmentIds.length)throw new Error("Proof Artwork assignments must belong to the Proof Work OrderLine.");const r=await this.client.query<VersionRow>("INSERT INTO v2_proof_versions(id,organization_id,proof_work_id,sequence,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[input.id,input.organizationId,input.proofWorkId,input.sequence,input.principalKind,input.principalSubject,input.staffActorUserId??null]);for(const [position,assignmentId] of input.artworkAssignmentIds.entries())await this.client.query("INSERT INTO v2_proof_version_artwork(organization_id,proof_version_id,position,artwork_assignment_id,artwork_file_id) SELECT organization_id,$2,$3,id,artwork_file_id FROM v2_artwork_assignments WHERE organization_id=$1 AND id=$4",[input.organizationId,input.id,position,assignmentId]);await this.hooks?.afterVersion?.();return this.project(r.rows[0]! as VersionRow).then((p)=>p.version); }
  async issueVersion(input:Parameters<ProofingTransaction["issueVersion"]>[0]) { const r=await this.client.query<VersionRow>("UPDATE v2_proof_versions SET issued_at=now(),issued_principal_kind=$3,issued_principal_subject=$4,issued_staff_actor_user_id=$5 WHERE organization_id=$1 AND id=$2 AND issued_at IS NULL RETURNING *",[input.organizationId,input.proofVersionId,input.principalKind,input.principalSubject,input.staffActorUserId??null]);if(!r.rows[0])throw Error("Proof Version issuance was not available.");await this.hooks?.afterIssue?.();return (await this.project(r.rows[0])).version; }
  async createResponse(input:Parameters<ProofingTransaction["createResponse"]>[0]) { const r=await this.client.query<ResponseRow>("INSERT INTO v2_proof_responses(id,organization_id,proof_version_id,outcome,comment,response_origin,recorded_customer_id,responder_principal_kind,responder_principal_subject,responder_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *",[input.id,input.organizationId,input.proofVersionId,input.outcome,input.comment??null,input.origin,input.recordedCustomerId??null,input.principalKind,input.principalSubject,input.staffActorUserId??null]);await this.hooks?.afterResponse?.();return response(r.rows[0]!); }
  async workCustomerId(org:OrganizationId,id:ProofWorkId){const r=await this.client.query<{customer_id:string|null}>("SELECT d.customer_id FROM v2_proof_works w JOIN v2_sales_documents d ON d.id=w.order_document_id AND d.organization_id=w.organization_id WHERE w.organization_id=$1 AND w.id=$2",[org,id]);return r.rows[0]?.customer_id??null;}
  private async versions(org:OrganizationId,workId:ProofWorkId){const r=await this.client.query<VersionRow>("SELECT * FROM v2_proof_versions WHERE organization_id=$1 AND proof_work_id=$2 ORDER BY sequence DESC",[org,workId]);return Promise.all(r.rows.map((row)=>this.project(row)));}
  private async project(row:VersionRow):Promise<ProofVersionProjection>{const [arts,res]=await Promise.all([this.client.query<ArtRow>("SELECT proof_version_id,position,artwork_assignment_id,artwork_file_id FROM v2_proof_version_artwork WHERE organization_id=$1 AND proof_version_id=$2 ORDER BY position",[row.organization_id,row.id]),this.client.query<ResponseRow>("SELECT * FROM v2_proof_responses WHERE organization_id=$1 AND proof_version_id=$2",[row.organization_id,row.id])]);const artwork=arts.rows.map((a)=>({position:a.position,artworkAssignmentId:brandedId<"ArtworkAssignmentId">(a.artwork_assignment_id),artworkFileId:brandedId<"ArtworkFileId">(a.artwork_file_id)}));return {version:version(row,artwork),...(res.rows[0]?{response:response(res.rows[0])}:{})};}
}
export class PostgresProofingTransactionRunner implements ProofingTransactionRunner { constructor(private readonly pool:Pool,private readonly hooks?:ProofingPersistenceTestHooks){} async transaction<T>(action:(tx:ProofingTransaction)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");const result=await action(new PostgresProofingTransaction(client,this.hooks));await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}} }
