import type { Pool, PoolClient } from "pg";
import { PostgresOperationRequestRepository } from "../persistence/postgresOperationRequests.js";
import type { ProofingTransaction, ProofingTransactionRunner } from "../../src/modules/proofing/proofingApplication.js";
import type { ProofDelivery, ProofResponse, ProofVersion, ProofVersionArtwork, ProofVersionProjection, ProofWork, ProofWorkProjection, ProofWorkQueueItem, ProofRecipient } from "../../src/modules/proofing/contracts.js";
import { brandedId, type ArtworkAssignmentId, type OrganizationId, type ProofVersionId, type ProofWorkId } from "../../src/modules/shared/commercialValues.js";
import type { OperationalQueuePage, OperationalQueuePageRequest } from "../../src/modules/shared/operationalQueue.js";
import { V2ApplicationError } from "../../src/errors/applicationError.js";

type WorkRow = { id:string; organization_id:string; order_document_id:string; order_line_id:string; created_at:Date; created_principal_kind:ProofWork["createdPrincipalKind"]; created_principal_subject:string; created_staff_actor_user_id:string|null };
type VersionRow = { id:string; organization_id:string; proof_work_id:string; sequence:number; created_at:Date; created_principal_kind:ProofVersion["createdPrincipalKind"]; created_principal_subject:string; created_staff_actor_user_id:string|null; issued_at:Date|null; issued_principal_kind:ProofVersion["issuedPrincipalKind"]|null; issued_principal_subject:string|null; issued_staff_actor_user_id:string|null };
type ArtRow = { proof_version_id:string; position:number; artwork_assignment_id:string; artwork_file_id:string };
type ResponseRow = { id:string; organization_id:string; proof_version_id:string; outcome:ProofResponse["outcome"]; comment:string|null; response_origin:ProofResponse["origin"]; recorded_customer_id:string|null; responder_principal_kind:ProofResponse["responderPrincipalKind"]; responder_principal_subject:string; responder_staff_actor_user_id:string|null; responded_at:Date };
type DeliveryRow = { id:string; recipient_contact_id:string; recipient_email:string; recipient_name:string|null; state:ProofDelivery["state"]; attempt_count:number; provider_message_id:string|null; delivered_at:Date|null; last_error:string|null };
const work = (r:WorkRow): ProofWork => ({ proofWorkId:brandedId<"ProofWorkId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),orderId:brandedId<"OrderId">(r.order_document_id),orderLineId:brandedId<"OrderLineId">(r.order_line_id),createdAt:r.created_at.toISOString(),createdPrincipalKind:r.created_principal_kind,createdPrincipalSubject:r.created_principal_subject,...(r.created_staff_actor_user_id?{createdStaffActorUserId:r.created_staff_actor_user_id}:{}) });
const response = (r:ResponseRow): ProofResponse => ({ proofResponseId:brandedId<"ProofResponseId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),proofVersionId:brandedId<"ProofVersionId">(r.proof_version_id),outcome:r.outcome,...(r.comment?{comment:r.comment}:{}),origin:r.response_origin,...(r.recorded_customer_id?{recordedCustomerId:brandedId<"CustomerId">(r.recorded_customer_id)}:{}),respondedAt:r.responded_at.toISOString(),responderPrincipalKind:r.responder_principal_kind,responderPrincipalSubject:r.responder_principal_subject,...(r.responder_staff_actor_user_id?{responderStaffActorUserId:r.responder_staff_actor_user_id}:{}) });
const version = (r:VersionRow, artwork:readonly ProofVersionArtwork[]): ProofVersion => ({ proofVersionId:brandedId<"ProofVersionId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),proofWorkId:brandedId<"ProofWorkId">(r.proof_work_id),sequence:r.sequence,artwork,createdAt:r.created_at.toISOString(),createdPrincipalKind:r.created_principal_kind,createdPrincipalSubject:r.created_principal_subject,...(r.created_staff_actor_user_id?{createdStaffActorUserId:r.created_staff_actor_user_id}:{}),...(r.issued_at?{issuedAt:r.issued_at.toISOString(),issuedPrincipalKind:r.issued_principal_kind!,issuedPrincipalSubject:r.issued_principal_subject!,...(r.issued_staff_actor_user_id?{issuedStaffActorUserId:r.issued_staff_actor_user_id}:{})}:{}) });

export type ProofingPersistenceTestHooks = Readonly<{ afterWork?:()=>Promise<void>; afterVersion?:()=>Promise<void>; afterIssue?:()=>Promise<void>; afterResponse?:()=>Promise<void>; afterAudit?:()=>Promise<void> }>;
export class PostgresProofingTransaction implements ProofingTransaction {
  private readonly requests=new PostgresOperationRequestRepository();
  constructor(private readonly client:PoolClient,private readonly hooks?:ProofingPersistenceTestHooks) {}
  async reserve(input:Parameters<ProofingTransaction["reserve"]>[0]) { const r=await this.requests.reserve(this.client,input);return {kind:r.kind,request:{id:r.request.id,resultJson:r.request.resultJson}}; }
  async succeed(org:string,id:string,result:Parameters<ProofingTransaction["succeed"]>[2]) { const target=result.response?result.response.proofResponseId:result.version?result.version.proofVersionId:result.work.proofWorkId;await this.requests.succeed(this.client,org,id,{resourceType:result.response?"proof_response":result.version?"proof_version":"proof_work",resourceId:target,resultJson:result}); }
  async attribute(input:Parameters<ProofingTransaction["attribute"]>[0]) { await this.requests.recordAttribution(this.client,{organizationId:input.organizationId,operationRequestId:input.requestId,operation:input.operation,resourceType:input.resourceType,resourceId:input.resourceId,principalKind:input.principalKind,principalSubject:input.principalSubject,staffActorUserId:input.staffActorUserId}); }
  async audit(input:Parameters<ProofingTransaction["audit"]>[0]) { const type=input.eventType==="proof_work_started"?"proof_work":input.eventType==="proof_version_created"||input.eventType==="proof_issued"||input.eventType==="proof_delivery_retried"?"proof_version":"proof_response";await this.client.query("INSERT INTO v2_audit_events(organization_id,operation_request_id,operation,event_type,resource_type,resource_id,principal_kind,principal_subject,staff_actor_user_id,changes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)",[input.organizationId,input.requestId,input.operation,input.eventType,type,input.resourceId,input.principalKind,input.principalSubject,input.staffActorUserId??null,JSON.stringify([{kind:input.eventType,summary:input.summary}])]);await this.hooks?.afterAudit?.(); }
  async findWork(org:OrganizationId,id:ProofWorkId){const r=await this.client.query<WorkRow>("SELECT * FROM v2_proof_works WHERE organization_id=$1 AND id=$2",[org,id]);return r.rows[0]?work(r.rows[0]):null;}
  async lockWork(org:OrganizationId,id:ProofWorkId){const r=await this.client.query<WorkRow>("SELECT * FROM v2_proof_works WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,id]);return r.rows[0]?work(r.rows[0]):null;}
  async createOrGetWork(input:Parameters<ProofingTransaction["createOrGetWork"]>[0]) { const r=await this.client.query<WorkRow>("INSERT INTO v2_proof_works(id,organization_id,order_document_id,order_line_id,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(organization_id,order_line_id) DO NOTHING RETURNING *",[input.id,input.organizationId,input.orderId,input.orderLineId,input.principalKind,input.principalSubject,input.staffActorUserId??null]);if(r.rows[0]){await this.hooks?.afterWork?.();return work(r.rows[0]);}const prior=await this.client.query<WorkRow>("SELECT * FROM v2_proof_works WHERE organization_id=$1 AND order_line_id=$2 FOR UPDATE",[input.organizationId,input.orderLineId]);if(!prior.rows[0])throw Error("Proof Work race could not reload its authoritative row.");return work(prior.rows[0]); }
  async readWork(org:OrganizationId,id:ProofWorkId):Promise<ProofWorkProjection|null>{const w=await this.findWork(org,id);if(!w)return null;const [rows,recipients]=await Promise.all([this.versions(org,id),this.recipients(org,id)]);return {work:w,versions:rows,recipients};}
  async listWorkQueue(org:OrganizationId,request:OperationalQueuePageRequest):Promise<OperationalQueuePage<ProofWorkQueueItem>>{
    const page=request.page??1,pageSize=request.pageSize??25,search=request.search??"",offset=(page-1)*pageSize;
    const where=`w.organization_id=$1 AND ($2='' OR d.display_number ILIKE '%'||$2||'%' OR COALESCE(c.display_name,c.company_name,'') ILIKE '%'||$2||'%' OR l.description ILIKE '%'||$2||'%')`;
    const [count,rows]=await Promise.all([
      this.client.query<{count:string}>(`SELECT count(*) count FROM v2_proof_works w JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id AND o.commercial_state='open' AND o.archived_at IS NULL JOIN v2_sales_document_lines l ON l.organization_id=w.organization_id AND l.id=w.order_line_id JOIN customers c ON c.organization_id=d.organization_id AND c.id=d.customer_id WHERE ${where}`,[org,search]),
      this.client.query<WorkRow & {display_number:string;customer_display_name:string;line_description:string;latest_sequence:number|null;latest_issued_at:Date|null;latest_outcome:ProofResponse["outcome"]|null;latest_delivery_state:ProofDelivery["state"]|null}>(`SELECT w.*,d.display_number,COALESCE(c.display_name,c.company_name,'Customer') customer_display_name,l.description line_description,v.sequence latest_sequence,v.issued_at latest_issued_at,r.outcome latest_outcome,j.state latest_delivery_state FROM v2_proof_works w JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id JOIN v2_sales_order_details o ON o.organization_id=d.organization_id AND o.document_id=d.id AND o.commercial_state='open' AND o.archived_at IS NULL JOIN v2_sales_document_lines l ON l.organization_id=w.organization_id AND l.id=w.order_line_id JOIN customers c ON c.organization_id=d.organization_id AND c.id=d.customer_id LEFT JOIN LATERAL (SELECT * FROM v2_proof_versions WHERE organization_id=w.organization_id AND proof_work_id=w.id ORDER BY sequence DESC LIMIT 1) v ON true LEFT JOIN v2_proof_responses r ON r.organization_id=v.organization_id AND r.proof_version_id=v.id LEFT JOIN v2_proof_delivery_jobs j ON j.organization_id=v.organization_id AND j.proof_version_id=v.id WHERE ${where} ORDER BY w.created_at DESC,w.id DESC LIMIT $3 OFFSET $4`,[org,search,pageSize,offset]),
    ]);
    const totalCount=Number(count.rows[0]?.count??0),items=rows.rows.map((row)=>({work:work(row),orderNumber:row.display_number,customerDisplayName:row.customer_display_name,lineDescription:row.line_description,...(row.latest_sequence===null?{}:{latest:{sequence:row.latest_sequence,...(row.latest_issued_at?{issuedAt:row.latest_issued_at.toISOString()}:{}),...(row.latest_outcome?{outcome:row.latest_outcome}:{}),...(row.latest_delivery_state?{deliveryState:row.latest_delivery_state}:{})}})}));
    return {items,pagination:{page,pageSize:pageSize as 25|50|100,totalCount,totalPages:Math.ceil(totalCount/pageSize)}};
  }
  async listOrderWorks(org:OrganizationId,orderId:any):Promise<readonly ProofWorkProjection[]>{
    const rows=await this.client.query<{id:string}>("SELECT id FROM v2_proof_works WHERE organization_id=$1 AND order_document_id=$2 ORDER BY created_at DESC,id DESC",[org,orderId]);
    return Promise.all(rows.rows.map((row)=>this.readWork(org,brandedId<"ProofWorkId">(row.id)).then((value)=>value!)));
  }
  async latestVersion(org:OrganizationId,workId:ProofWorkId){const r=await this.client.query<VersionRow>("SELECT * FROM v2_proof_versions WHERE organization_id=$1 AND proof_work_id=$2 ORDER BY sequence DESC LIMIT 1",[org,workId]);return r.rows[0]?this.project(r.rows[0]):null;}
  async findVersion(org:OrganizationId,id:ProofVersionId){const r=await this.client.query<VersionRow>("SELECT * FROM v2_proof_versions WHERE organization_id=$1 AND id=$2",[org,id]);return r.rows[0]?this.project(r.rows[0]):null;}
  async createVersion(input:Parameters<ProofingTransaction["createVersion"]>[0]) { const valid=await this.client.query<{id:string}>("SELECT a.id FROM v2_artwork_assignments a JOIN v2_proof_works w ON w.organization_id=a.organization_id AND w.order_document_id=a.order_document_id AND w.order_line_id=a.order_line_id WHERE w.organization_id=$1 AND w.id=$2 AND a.id=ANY($3::text[]) AND NOT EXISTS(SELECT 1 FROM v2_artwork_assignments successor WHERE successor.organization_id=a.organization_id AND successor.supersedes_artwork_assignment_id=a.id)",[input.organizationId,input.proofWorkId,input.artworkAssignmentIds]);if(valid.rows.length!==input.artworkAssignmentIds.length)throw new V2ApplicationError("VALIDATION_ERROR","Proof Artwork must be the current assignments for this Order line.");const r=await this.client.query<VersionRow>("INSERT INTO v2_proof_versions(id,organization_id,proof_work_id,sequence,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[input.id,input.organizationId,input.proofWorkId,input.sequence,input.principalKind,input.principalSubject,input.staffActorUserId??null]);for(const [position,assignmentId] of input.artworkAssignmentIds.entries())await this.client.query("INSERT INTO v2_proof_version_artwork(organization_id,proof_version_id,position,artwork_assignment_id,artwork_file_id) SELECT organization_id,$2,$3,id,artwork_file_id FROM v2_artwork_assignments WHERE organization_id=$1 AND id=$4",[input.organizationId,input.id,position,assignmentId]);await this.hooks?.afterVersion?.();return this.project(r.rows[0]! as VersionRow).then((p)=>p.version); }
  async issueVersion(input:Parameters<ProofingTransaction["issueVersion"]>[0]) {
    if(!input.recipientContactId?.trim())throw new V2ApplicationError("VALIDATION_ERROR","Choose a customer contact before issuing this Proof.");
    const recipient=await this.client.query<{contact_id:string;customer_id:string;email:string;display_name:string}>(`SELECT c.id contact_id,d.customer_id,lower(btrim(c.email)) email,COALESCE(NULLIF(btrim(concat_ws(' ',c.first_name,c.last_name)),''),c.email) display_name
      FROM v2_proof_versions v JOIN v2_proof_works w ON w.organization_id=v.organization_id AND w.id=v.proof_work_id
      JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id
      JOIN customer_contacts c ON c.organization_id=d.organization_id AND c.id=$3 AND c.status='active'
      WHERE v.organization_id=$1 AND v.id=$2 AND d.customer_id IS NOT NULL
        AND (d.contact_id=c.id OR c.customer_id=d.customer_id OR EXISTS(SELECT 1 FROM customer_contact_links l WHERE l.organization_id=d.organization_id AND l.customer_id=d.customer_id AND l.contact_id=c.id AND l.status='active'))
        AND btrim(COALESCE(c.email,'')) ~* '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'`,[input.organizationId,input.proofVersionId,input.recipientContactId]);
    const contact=recipient.rows[0];if(!contact)throw new V2ApplicationError("VALIDATION_ERROR","Choose an active customer contact with a valid email address for this Order.");
    let access=await this.client.query<{id:string;status:string}>("SELECT id,status::text FROM customer_portal_access WHERE organization_id=$1 AND contact_id=$2 FOR UPDATE",[input.organizationId,contact.contact_id]);
    if(access.rows[0]&&access.rows[0].status!=="ACTIVE"&&access.rows[0].status!=="PENDING_INVITE")throw new V2ApplicationError("CONFLICT","That contact's portal access is suspended or disabled. Restore access before issuing the Proof.");
    if(!access.rows[0])access=await this.client.query<{id:string;status:string}>("INSERT INTO customer_portal_access(organization_id,customer_id,contact_id,status,email,display_name,access_role,created_by_user_id,updated_by_user_id) VALUES($1,$2,$3,'PENDING_INVITE',$4,$5,'VIEWER',$6,$6) RETURNING id,status::text",[input.organizationId,contact.customer_id,contact.contact_id,contact.email,contact.display_name,input.staffActorUserId??null]);
    else await this.client.query("UPDATE customer_portal_access SET email=$3,display_name=$4,updated_by_user_id=COALESCE($5,updated_by_user_id),updated_at=now() WHERE organization_id=$1 AND id=$2",[input.organizationId,access.rows[0].id,contact.email,contact.display_name,input.staffActorUserId??null]);
    const permission=await this.client.query<{id:string}>("SELECT id FROM v2_permission_sets WHERE organization_id=$1 AND source_template_key='customer_full_portal' AND active LIMIT 1",[input.organizationId]);
    if(!permission.rows[0])throw new V2ApplicationError("CONFLICT","Customer Portal permissions are not configured for this organization.");
    await this.client.query("INSERT INTO v2_portal_permission_set_assignments(organization_id,portal_access_id,permission_set_id,active) VALUES($1,$2,$3,true) ON CONFLICT(organization_id,portal_access_id,permission_set_id) DO UPDATE SET active=true,updated_at=now()",[input.organizationId,access.rows[0]!.id,permission.rows[0].id]);
    const r=await this.client.query<VersionRow>("UPDATE v2_proof_versions SET issued_at=now(),issued_principal_kind=$3,issued_principal_subject=$4,issued_staff_actor_user_id=$5 WHERE organization_id=$1 AND id=$2 AND issued_at IS NULL RETURNING *",[input.organizationId,input.proofVersionId,input.principalKind,input.principalSubject,input.staffActorUserId??null]);if(!r.rows[0])throw new V2ApplicationError("CONFLICT","Proof Version issuance was not available.");
    await this.client.query("INSERT INTO v2_proof_delivery_jobs(organization_id,proof_version_id,recipient_contact_id,recipient_email,recipient_name,portal_access_id) VALUES($1,$2,$3,$4,$5,$6)",[input.organizationId,input.proofVersionId,contact.contact_id,contact.email,contact.display_name,access.rows[0]!.id]);
    await this.client.query("UPDATE v2_permission_organization_state SET authority_revision=authority_revision+1,updated_at=now() WHERE organization_id=$1",[input.organizationId]);
    await this.hooks?.afterIssue?.();return (await this.project(r.rows[0])).version;
  }
  async retryDelivery(input:Parameters<ProofingTransaction["retryDelivery"]>[0]) { const queued=await this.client.query<{proof_version_id:string}>("UPDATE v2_proof_delivery_jobs SET state='queued',available_at=now(),claimed_by=NULL,lease_expires_at=NULL,provider_attempted_at=NULL,completed_at=NULL,last_error=NULL,updated_at=now() WHERE organization_id=$1 AND proof_version_id=$2 AND state IN ('failed','ambiguous') RETURNING proof_version_id",[input.organizationId,input.proofVersionId]);if(!queued.rows[0])throw new V2ApplicationError("CONFLICT","This Proof notification is not eligible for intentional retry.");const found=await this.findVersion(input.organizationId,input.proofVersionId);if(!found)throw new V2ApplicationError("NOT_FOUND","Proof Version was not found.");return found.version; }
  async createResponse(input:Parameters<ProofingTransaction["createResponse"]>[0]) { const r=await this.client.query<ResponseRow>("INSERT INTO v2_proof_responses(id,organization_id,proof_version_id,outcome,comment,response_origin,recorded_customer_id,responder_principal_kind,responder_principal_subject,responder_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *",[input.id,input.organizationId,input.proofVersionId,input.outcome,input.comment??null,input.origin,input.recordedCustomerId??null,input.principalKind,input.principalSubject,input.staffActorUserId??null]);await this.hooks?.afterResponse?.();return response(r.rows[0]!); }
  async workCustomerId(org:OrganizationId,id:ProofWorkId){const r=await this.client.query<{customer_id:string|null}>("SELECT d.customer_id FROM v2_proof_works w JOIN v2_sales_documents d ON d.id=w.order_document_id AND d.organization_id=w.organization_id WHERE w.organization_id=$1 AND w.id=$2",[org,id]);return r.rows[0]?.customer_id??null;}
  private async versions(org:OrganizationId,workId:ProofWorkId){const r=await this.client.query<VersionRow>("SELECT * FROM v2_proof_versions WHERE organization_id=$1 AND proof_work_id=$2 ORDER BY sequence DESC",[org,workId]);return Promise.all(r.rows.map((row)=>this.project(row)));}
  private async recipients(org:OrganizationId,workId:ProofWorkId):Promise<readonly ProofRecipient[]>{const result=await this.client.query<{contact_id:string;display_name:string;email:string}>(`SELECT DISTINCT c.id contact_id,COALESCE(NULLIF(btrim(concat_ws(' ',c.first_name,c.last_name)),''),c.email) display_name,lower(btrim(c.email)) email FROM v2_proof_works w JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id JOIN customer_contacts c ON c.organization_id=d.organization_id AND c.status='active' WHERE w.organization_id=$1 AND w.id=$2 AND btrim(COALESCE(c.email,'')) ~* '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' AND (d.contact_id=c.id OR c.customer_id=d.customer_id OR EXISTS(SELECT 1 FROM customer_contact_links l WHERE l.organization_id=d.organization_id AND l.customer_id=d.customer_id AND l.contact_id=c.id AND l.status='active')) ORDER BY display_name,email`,[org,workId]);return result.rows.map(row=>({contactId:row.contact_id,displayName:row.display_name,email:row.email}));}
  private async project(row:VersionRow):Promise<ProofVersionProjection>{const [arts,res,delivery]=await Promise.all([this.client.query<ArtRow>("SELECT proof_version_id,position,artwork_assignment_id,artwork_file_id FROM v2_proof_version_artwork WHERE organization_id=$1 AND proof_version_id=$2 ORDER BY position",[row.organization_id,row.id]),this.client.query<ResponseRow>("SELECT * FROM v2_proof_responses WHERE organization_id=$1 AND proof_version_id=$2",[row.organization_id,row.id]),this.client.query<DeliveryRow>("SELECT id,recipient_contact_id,recipient_email,recipient_name,state,attempt_count,provider_message_id,delivered_at,last_error FROM v2_proof_delivery_jobs WHERE organization_id=$1 AND proof_version_id=$2",[row.organization_id,row.id])]);const artwork=arts.rows.map((a)=>({position:a.position,artworkAssignmentId:brandedId<"ArtworkAssignmentId">(a.artwork_assignment_id),artworkFileId:brandedId<"ArtworkFileId">(a.artwork_file_id)}));const job=delivery.rows[0];return {version:version(row,artwork),...(res.rows[0]?{response:response(res.rows[0])}:{}),...(job?{delivery:{jobId:job.id,recipient:{contactId:job.recipient_contact_id,displayName:job.recipient_name??job.recipient_email,email:job.recipient_email},state:job.state,attemptCount:job.attempt_count,...(job.provider_message_id?{providerMessageId:job.provider_message_id}:{}),...(job.delivered_at?{deliveredAt:job.delivered_at.toISOString()}:{}),...(job.last_error?{lastError:job.last_error}:{})}}:{})};}
}
export class PostgresProofingTransactionRunner implements ProofingTransactionRunner { constructor(private readonly pool:Pool,private readonly hooks?:ProofingPersistenceTestHooks){} async transaction<T>(action:(tx:ProofingTransaction)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");const result=await action(new PostgresProofingTransaction(client,this.hooks));await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}} }
