import * as React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { apiFetchBlob, apiRequest } from '@/lib/queryClient';
import { ROUTES } from '@/config/routes';
import type { AccountsReceivableRow, AccountsReceivableSummary, ArAgingBucket } from '@shared/accountsReceivableReport';

type ReportData = { asOf: string; pageRows: AccountsReceivableRow[]; summary: AccountsReceivableSummary; page: number; pageSize: number; totalCount: number; totalPages: number; customerOptions: Array<{ id: string; name: string }> };
type Filters = { customerId: string; agingBucket: string; invoiceStatus: string; sendStatus: string; jobStatus: string };
const money = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
const agingLabels: Record<ArAgingBucket, string> = { current: 'Current', '1-30': '1–30 Days', '31-60': '31–60 Days', '61-90': '61–90 Days', '90+': '90+ Days', no_due_date: 'No Due Date' };

function query(filters: Filters, sortBy: string, sortDir: string, page: number) {
  const params = new URLSearchParams({ page: String(page), pageSize: '50', sortBy, sortDir });
  Object.entries(filters).forEach(([key, value]) => { if (value && value !== 'all') params.set(key, value); });
  return params.toString();
}

export default function AccountsReceivableReportPage() {
  const [filters, setFilters] = React.useState<Filters>({ customerId: 'all', agingBucket: 'all', invoiceStatus: 'all', sendStatus: 'all', jobStatus: 'all' });
  const [sortBy, setSortBy] = React.useState('dueDate');
  const [sortDir, setSortDir] = React.useState('asc');
  const [page, setPage] = React.useState(1);
  const [data, setData] = React.useState<ReportData | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  const [exporting, setExporting] = React.useState<string | null>(null);
  const requestQuery = React.useMemo(() => query(filters, sortBy, sortDir, page), [filters, sortBy, sortDir, page]);
  React.useEffect(() => { void (async () => { setError(null); try { const response = await apiRequest('GET', `/api/reports/accounts-receivable?${requestQuery}`); const body = await response.json() as { data?: ReportData }; setData(body.data ?? null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load Accounts Receivable'); } })(); }, [requestQuery]);
  const changeFilter = (key: keyof Filters, value: string) => { setPage(1); setFilters((current) => ({ ...current, [key]: value })); };
  const download = async (format: 'csv' | 'xlsx') => { setExporting(format); try { const blob = await apiFetchBlob(`/api/reports/accounts-receivable/export/${format}?${query(filters, sortBy, sortDir, 1)}`, { method: 'GET' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `accounts-receivable.${format}`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } finally { setExporting(null); } };
  if (error) return <main className="mx-auto max-w-7xl p-4 sm:p-6"><div className="rounded-lg border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">{error}</div></main>;
  if (!data) return <main className="mx-auto max-w-7xl p-4 sm:p-6"><p className="text-sm text-muted-foreground">Loading Accounts Receivable…</p></main>;
  const cards = [['Total Outstanding', money(data.summary.totalOutstandingCents)], ['Invoice Count', String(data.summary.invoiceCount)], ['Overdue Amount', money(data.summary.overdueOutstandingCents)], ['Overdue Invoices', String(data.summary.overdueInvoiceCount)]];
  return <main className="mx-auto max-w-7xl p-4 sm:p-6"><div className="mb-5"><Button asChild variant="ghost" size="sm"><Link to={ROUTES.reports}><ArrowLeft className="mr-2 h-4 w-4" />Reports</Link></Button></div>
    <header className="flex flex-wrap items-start justify-between gap-4 border-b pb-5"><div><p className="text-sm font-semibold text-primary">Accounts Receivable</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Outstanding Invoices</h1><p className="mt-1 text-sm text-muted-foreground">Approved invoices with an authoritative positive balance. As of {data.asOf}.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void download('csv')} disabled={!!exporting}>{exporting === 'csv' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}Export CSV</Button><Button onClick={() => void download('xlsx')} disabled={!!exporting}>{exporting === 'xlsx' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileSpreadsheet className="mr-2 h-4 w-4" />}Export Excel</Button></div></header>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <div key={label} className="rounded-lg border bg-card p-4"><div className="text-xs font-medium uppercase text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-bold tabular-nums">{value}</div></div>)}</section>
    <section className="mt-3 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{(Object.entries(data.summary.agingCents) as Array<[ArAgingBucket, number]>).map(([bucket, cents]) => <div key={bucket} className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">{agingLabels[bucket]}</div><div className="font-semibold tabular-nums">{money(cents)}</div></div>)}</section>
    <section className="mt-5 flex flex-wrap gap-2 rounded-lg border bg-card p-3"><Select value={filters.customerId} onValueChange={(value) => changeFilter('customerId', value)}><SelectTrigger className="w-[190px]"><SelectValue placeholder="Customer" /></SelectTrigger><SelectContent><SelectItem value="all">All Customers</SelectItem>{data.customerOptions.map((customer) => <SelectItem key={customer.id} value={customer.id}>{customer.name}</SelectItem>)}</SelectContent></Select><Select value={filters.agingBucket} onValueChange={(value) => changeFilter('agingBucket', value)}><SelectTrigger className="w-[155px]"><SelectValue placeholder="Aging" /></SelectTrigger><SelectContent><SelectItem value="all">All Aging</SelectItem>{Object.entries(agingLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Select value={filters.invoiceStatus} onValueChange={(value) => changeFilter('invoiceStatus', value)}><SelectTrigger className="w-[165px]"><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="all">All Statuses</SelectItem><SelectItem value="unpaid">Unpaid</SelectItem><SelectItem value="partially_paid">Partially Paid</SelectItem></SelectContent></Select><Select value={filters.sendStatus} onValueChange={(value) => changeFilter('sendStatus', value)}><SelectTrigger className="w-[165px]"><SelectValue placeholder="Send status" /></SelectTrigger><SelectContent><SelectItem value="all">All Send Status</SelectItem><SelectItem value="never_sent">Never Sent</SelectItem><SelectItem value="sent">Sent</SelectItem><SelectItem value="updated_after_sent">Updated After Sent</SelectItem></SelectContent></Select><Select value={filters.jobStatus} onValueChange={(value) => changeFilter('jobStatus', value)}><SelectTrigger className="w-[150px]"><SelectValue placeholder="Job status" /></SelectTrigger><SelectContent><SelectItem value="all">All Jobs</SelectItem><SelectItem value="open">Open Jobs</SelectItem><SelectItem value="complete">Complete Jobs</SelectItem></SelectContent></Select><Select value={`${sortBy}:${sortDir}`} onValueChange={(value) => { const [nextSort, nextDirection] = value.split(':'); setSortBy(nextSort); setSortDir(nextDirection); setPage(1); }}><SelectTrigger className="w-[170px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="dueDate:asc">Due date, oldest</SelectItem><SelectItem value="dueDate:desc">Due date, newest</SelectItem><SelectItem value="balance:desc">Balance, high to low</SelectItem><SelectItem value="customer:asc">Customer, A–Z</SelectItem></SelectContent></Select></section>
    <section className="mt-5 overflow-x-auto rounded-lg border"><table className="w-full min-w-[1750px] text-left text-sm"><thead className="bg-muted/60 text-xs uppercase text-muted-foreground"><tr>{['Customer', 'Contact', 'Invoice #', 'Order #', 'Job / Order Name', 'PO #', 'Issue', 'Due', 'Past Due', 'Aging', 'Invoice Status', 'Approval', 'Send Status', 'Terms', 'Total', 'Paid', 'Balance', 'Last Sent', 'QB Sync'].map((header) => <th key={header} className="px-3 py-3 font-semibold">{header}</th>)}</tr></thead><tbody>{data.pageRows.length ? data.pageRows.map((row) => <tr key={row.id} className="border-t"><td className="px-3 py-3">{row.customerId ? <Link className="text-primary hover:underline" to={ROUTES.customers.detail(row.customerId)}>{row.customerName || '—'}</Link> : row.customerName || '—'}</td><td className="px-3 py-3">{row.contactName || '—'}</td><td className="px-3 py-3 font-medium"><Link className="text-primary hover:underline" to={ROUTES.invoices.detail(row.id)}>{row.invoiceNumber}</Link></td><td className="px-3 py-3">{row.orderId ? <Link className="text-primary hover:underline" to={ROUTES.orders.detail(row.orderId)}>{row.orderNumber || '—'}</Link> : '—'}</td><td className="px-3 py-3">{row.jobName || '—'}</td><td className="px-3 py-3">{row.purchaseOrderNumber || '—'}</td><td className="px-3 py-3">{row.issueDate || '—'}</td><td className="px-3 py-3">{row.dueDate || '—'}</td><td className="px-3 py-3">{row.daysPastDue ?? '—'}</td><td className="px-3 py-3">{agingLabels[row.agingBucket]}</td><td className="px-3 py-3">{row.invoiceStatus}</td><td className="px-3 py-3">Approved</td><td className="px-3 py-3">{row.sendStatus}</td><td className="px-3 py-3">{row.terms || '—'}</td><td className="px-3 py-3 tabular-nums">{money(row.totalCents)}</td><td className="px-3 py-3 tabular-nums">{money(row.paidCents)}</td><td className="px-3 py-3 font-semibold tabular-nums">{money(row.remainingCents)}</td><td className="px-3 py-3">{row.lastSentAt ? new Date(row.lastSentAt).toLocaleString() : '—'}</td><td className="px-3 py-3">{row.qbSyncStatus || '—'}</td></tr>) : <tr><td colSpan={19} className="px-3 py-10 text-center text-muted-foreground">No approved outstanding invoices match these filters.</td></tr>}</tbody></table></section>
    <div className="mt-4 flex items-center justify-between text-sm"><span className="text-muted-foreground">{data.totalCount} invoice{data.totalCount === 1 ? '' : 's'} · Page {data.page} of {data.totalPages}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={data.page <= 1} onClick={() => setPage((current) => current - 1)}>Previous</Button><Button variant="outline" size="sm" disabled={data.page >= data.totalPages} onClick={() => setPage((current) => current + 1)}>Next</Button></div></div>
  </main>;
}
