import * as React from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowDown, ArrowLeft, ArrowUp, ChevronsUpDown, Download, FileSpreadsheet, Loader2, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import ColumnConfigModal from '@/components/ColumnConfigModal';
import { apiFetchBlob, apiRequest } from '@/lib/queryClient';
import { ROUTES } from '@/config/routes';
import { useAuth } from '@/hooks/useAuth';
import { useActiveOrganizationRole } from '@/hooks/useActiveOrganizationRole';
import { arReportDefaultColumns, defaultArReportTablePreferences, getArReportPreferenceStorageKey, normalizeArReportColumns, type ArReportColumn, type ArReportSort } from '@/lib/accountsReceivableTablePreferences';
import type { AccountsReceivableRow, AccountsReceivableSummary, ArAgingBucket } from '@shared/accountsReceivableReport';

type ReportData = { asOf: string; pageRows: AccountsReceivableRow[]; summary: AccountsReceivableSummary; page: number; totalCount: number; totalPages: number; customerOptions: Array<{ id: string; name: string }> };
type Filters = { customerId: string; agingBucket: string; invoiceStatus: string; sendStatus: string; jobStatus: string; overdueOnly: boolean };
const money = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
const agingLabels: Record<ArAgingBucket, string> = { current: 'Current', '1-30': '1–30 Days', '31-60': '31–60 Days', '61-90': '61–90 Days', '90+': '90+ Days', no_due_date: 'No Due Date' };
const sortableValues = new Set<ArReportSort>(arReportDefaultColumns.flatMap((column) => column.sortBy ? [column.sortBy] : []));

function query(filters: Filters, sortBy: ArReportSort, sortDir: 'asc' | 'desc', page: number) { const params = new URLSearchParams({ page: String(page), pageSize: '50', sortBy, sortDir }); Object.entries(filters).forEach(([key, value]) => { if (key === 'overdueOnly') { if (value) params.set('overdue', 'true'); } else if (value && value !== 'all') params.set(key, String(value)); }); return params.toString(); }
function width(column: ArReportColumn) { return { width: column.width, minWidth: column.minWidth, maxWidth: column.maxWidth }; }
function Cell({ row, column }: { row: AccountsReceivableRow; column: ArReportColumn }) {
  const cls = `px-3 py-3 ${column.numeric ? 'text-right tabular-nums whitespace-nowrap' : ''}`;
  const text = (value: React.ReactNode, className = '') => <td className={`${cls} ${className}`} style={width(column)}>{value}</td>;
  switch (column.id) {
    case 'customer': return text(row.customerId ? <Link className="block truncate text-primary hover:underline" to={ROUTES.customers.detail(row.customerId)}>{row.customerName || '—'}</Link> : <span className="block truncate">{row.customerName || '—'}</span>);
    case 'contact': return text(<span className="block truncate">{row.contactName || '—'}</span>);
    case 'invoiceNumber': return text(<Link className="block truncate text-primary hover:underline" to={ROUTES.invoices.detail(row.id)}>{row.invoiceNumber}</Link>, 'font-medium');
    case 'orderNumber': return text(row.orderId ? <Link className="block truncate text-primary hover:underline" to={ROUTES.orders.detail(row.orderId)}>{row.orderNumber || '—'}</Link> : '—');
    case 'jobName': return text(<span className="block truncate" title={row.jobName || undefined}>{row.jobName || '—'}</span>);
    case 'purchaseOrderNumber': return text(<span className="block truncate">{row.purchaseOrderNumber || '—'}</span>);
    case 'issueDate': return text(row.issueDate || '—', 'whitespace-nowrap'); case 'dueDate': return text(row.dueDate || '—', 'whitespace-nowrap'); case 'daysPastDue': return text(row.daysPastDue ?? '—'); case 'agingBucket': return text(agingLabels[row.agingBucket], 'whitespace-nowrap');
    case 'invoiceStatus': return text(<span className="block truncate">{row.invoiceStatus}</span>); case 'approval': return text('Approved'); case 'sendStatus': return text(<span className="block truncate">{row.sendStatus}</span>); case 'terms': return text(<span className="block truncate">{row.terms || '—'}</span>);
    case 'total': return text(money(row.totalCents)); case 'paid': return text(money(row.paidCents)); case 'balance': return text(money(row.remainingCents), 'font-semibold'); case 'lastSentAt': return text(row.lastSentAt ? new Date(row.lastSentAt).toLocaleString() : '—', 'whitespace-nowrap'); case 'qbSyncStatus': return text(<span className="block truncate">{row.qbSyncStatus || '—'}</span>);
    default: return text('—');
  }
}
function Header({ column, sortBy, sortDir, onSort, onResize }: { column: ArReportColumn; sortBy: ArReportSort; sortDir: 'asc' | 'desc'; onSort: (column: ArReportColumn) => void; onResize: (column: ArReportColumn, width: number) => void }) {
  const ref = React.useRef<HTMLTableCellElement>(null); const sorted = column.sortBy === sortBy;
  const resize = (event: React.MouseEvent) => { event.preventDefault(); event.stopPropagation(); const initial = ref.current?.offsetWidth || column.width; const x = event.clientX; const move = (next: MouseEvent) => onResize(column, Math.max(column.minWidth, Math.min(column.maxWidth, initial + next.clientX - x))); const up = () => { document.removeEventListener('mousemove', move); document.removeEventListener('mouseup', up); }; document.addEventListener('mousemove', move); document.addEventListener('mouseup', up); };
  return <th ref={ref} scope="col" style={width(column)} className={`relative select-none px-3 py-3 font-semibold ${column.numeric ? 'text-right' : ''}`}>{column.sortBy ? <button type="button" className={`flex w-full items-center gap-1 ${column.numeric ? 'justify-end' : ''}`} onClick={() => onSort(column)}>{column.label}{sorted ? sortDir === 'asc' ? <ArrowUp className="h-3.5 w-3.5" /> : <ArrowDown className="h-3.5 w-3.5" /> : <ChevronsUpDown className="h-3.5 w-3.5 text-muted-foreground" />}</button> : column.label}<span role="separator" aria-label={`Resize ${column.label} column`} className="absolute right-0 top-0 h-full w-1 cursor-col-resize hover:bg-primary/30" onMouseDown={resize} /></th>;
}

export default function AccountsReceivableReportPage() {
  const [searchParams] = useSearchParams();
  const { user } = useAuth(); const { activeOrgId } = useActiveOrganizationRole({ enabled: Boolean(user) });
  const preferenceKey = React.useMemo(() => user?.id && activeOrgId ? getArReportPreferenceStorageKey(user.id, activeOrgId) : null, [activeOrgId, user?.id]); const defaults = React.useMemo(() => defaultArReportTablePreferences(), []);
  const [filters, setFilters] = React.useState<Filters>({ customerId: 'all', agingBucket: 'all', invoiceStatus: 'all', sendStatus: 'all', jobStatus: 'all', overdueOnly: searchParams.get('overdue') === 'true' }); const [columns, setColumns] = React.useState<ArReportColumn[]>(defaults.columns); const [sortBy, setSortBy] = React.useState<ArReportSort>(defaults.sortBy); const [sortDir, setSortDir] = React.useState<'asc' | 'desc'>(defaults.sortDir); const [hydratedKey, setHydratedKey] = React.useState<string | null>(null); const [columnConfigOpen, setColumnConfigOpen] = React.useState(false); const [page, setPage] = React.useState(1); const [data, setData] = React.useState<ReportData | null>(null); const [error, setError] = React.useState<string | null>(null); const [exporting, setExporting] = React.useState<string | null>(null);
  React.useEffect(() => { if (!preferenceKey) { setHydratedKey(null); return; } const fallback = defaultArReportTablePreferences(); try { const saved = JSON.parse(localStorage.getItem(preferenceKey) || 'null'); setColumns(normalizeArReportColumns(saved?.columns)); setSortBy(sortableValues.has(saved?.sortBy) ? saved.sortBy : fallback.sortBy); setSortDir(saved?.sortDir === 'desc' ? 'desc' : 'asc'); } catch { setColumns(fallback.columns); setSortBy(fallback.sortBy); setSortDir(fallback.sortDir); } setHydratedKey(preferenceKey); }, [preferenceKey]);
  React.useEffect(() => { if (preferenceKey && hydratedKey === preferenceKey) localStorage.setItem(preferenceKey, JSON.stringify({ columns, sortBy, sortDir })); }, [columns, hydratedKey, preferenceKey, sortBy, sortDir]);
  const requestQuery = React.useMemo(() => query(filters, sortBy, sortDir, page), [filters, page, sortBy, sortDir]); React.useEffect(() => { void (async () => { setError(null); try { const response = await apiRequest('GET', `/api/reports/accounts-receivable?${requestQuery}`); const body = await response.json() as { data?: ReportData }; setData(body.data ?? null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load Accounts Receivable'); } })(); }, [requestQuery]);
  const changeFilter = (key: keyof Filters, value: string) => { setPage(1); setFilters((current) => ({ ...current, [key]: value })); }; const changeSort = (column: ArReportColumn) => { if (!column.sortBy) return; setPage(1); if (sortBy === column.sortBy) setSortDir((current) => current === 'asc' ? 'desc' : 'asc'); else { setSortBy(column.sortBy); setSortDir('asc'); } }; const resizeColumn = (column: ArReportColumn, nextWidth: number) => setColumns((current) => current.map((item) => item.id === column.id ? { ...item, width: nextWidth } : item)); const saveColumns = (configured: Array<{ id: string; enabled: boolean }>) => setColumns((current) => normalizeArReportColumns(configured.map((entry) => ({ ...current.find((column) => column.id === entry.id), ...entry }))));
  const download = async (format: 'csv' | 'xlsx') => { setExporting(format); try { const blob = await apiFetchBlob(`/api/reports/accounts-receivable/export/${format}?${query(filters, sortBy, sortDir, 1)}`, { method: 'GET' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `accounts-receivable.${format}`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } finally { setExporting(null); } };
  if (error) return <main className="w-full max-w-none px-4 py-4 sm:px-6 lg:px-8"><div className="rounded-lg border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">{error}</div></main>; if (!data) return <main className="w-full max-w-none px-4 py-4 sm:px-6 lg:px-8"><p className="text-sm text-muted-foreground">Loading Accounts Receivable…</p></main>;
  const visible = columns.filter((column) => column.enabled); const tableMinWidth = visible.reduce((total, column) => total + column.width, 0); const cards = [['Total Outstanding', money(data.summary.totalOutstandingCents)], ['Invoice Count', String(data.summary.invoiceCount)], ['Overdue Amount', money(data.summary.overdueOutstandingCents)], ['Overdue Invoices', String(data.summary.overdueInvoiceCount)]];
  return <main className="w-full max-w-none px-4 py-4 sm:px-6 lg:px-8"><div className="mb-5"><Button asChild variant="ghost" size="sm"><Link to={ROUTES.reports}><ArrowLeft className="mr-2 h-4 w-4" />Reports</Link></Button></div><header className="flex flex-wrap items-start justify-between gap-4 border-b pb-5"><div><p className="text-sm font-semibold text-primary">Accounts Receivable</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Outstanding Invoices</h1><p className="mt-1 text-sm text-muted-foreground">Approved invoices with an authoritative positive balance. As of {data.asOf}.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void download('csv')} disabled={!!exporting}>{exporting === 'csv' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}Export CSV</Button><Button onClick={() => void download('xlsx')} disabled={!!exporting}>{exporting === 'xlsx' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileSpreadsheet className="mr-2 h-4 w-4" />}Export Excel</Button></div></header>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <div key={label} className="rounded-lg border bg-card p-4"><div className="text-xs font-medium uppercase text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-bold tabular-nums">{value}</div></div>)}</section><section className="mt-3 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{(Object.entries(data.summary.agingCents) as Array<[ArAgingBucket, number]>).map(([bucket, cents]) => <div key={bucket} className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">{agingLabels[bucket]}</div><div className="font-semibold tabular-nums">{money(cents)}</div></div>)}</section>
    <section className="mt-5 flex flex-wrap gap-2 rounded-lg border bg-card p-3"><Select value={filters.customerId} onValueChange={(value) => changeFilter('customerId', value)}><SelectTrigger className="w-[190px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All Customers</SelectItem>{data.customerOptions.map((customer) => <SelectItem key={customer.id} value={customer.id}>{customer.name}</SelectItem>)}</SelectContent></Select><Select value={filters.agingBucket} onValueChange={(value) => changeFilter('agingBucket', value)}><SelectTrigger className="w-[155px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All Aging</SelectItem>{Object.entries(agingLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Select value={filters.invoiceStatus} onValueChange={(value) => changeFilter('invoiceStatus', value)}><SelectTrigger className="w-[165px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All Statuses</SelectItem><SelectItem value="unpaid">Unpaid</SelectItem><SelectItem value="partially_paid">Partially Paid</SelectItem></SelectContent></Select><Select value={filters.sendStatus} onValueChange={(value) => changeFilter('sendStatus', value)}><SelectTrigger className="w-[165px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All Send Status</SelectItem><SelectItem value="never_sent">Never Sent</SelectItem><SelectItem value="sent">Sent</SelectItem><SelectItem value="updated_after_sent">Updated After Sent</SelectItem></SelectContent></Select><Select value={filters.jobStatus} onValueChange={(value) => changeFilter('jobStatus', value)}><SelectTrigger className="w-[150px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All Jobs</SelectItem><SelectItem value="open">Open Jobs</SelectItem><SelectItem value="complete">Complete Jobs</SelectItem></SelectContent></Select><Select value={`${sortBy}:${sortDir}`} onValueChange={(value) => { const [field, direction] = value.split(':') as [ArReportSort, 'asc' | 'desc']; setSortBy(field); setSortDir(direction); setPage(1); }}><SelectTrigger className="w-[190px]"><SelectValue /></SelectTrigger><SelectContent>{arReportDefaultColumns.filter((column) => column.sortBy).flatMap((column) => [<SelectItem key={`${column.id}-asc`} value={`${column.sortBy}:asc`}>{column.label}, ascending</SelectItem>, <SelectItem key={`${column.id}-desc`} value={`${column.sortBy}:desc`}>{column.label}, descending</SelectItem>])}</SelectContent></Select><Button variant="outline" onClick={() => setColumnConfigOpen(true)}><SlidersHorizontal className="mr-2 h-4 w-4" />Columns</Button></section>
    <section className="mt-5 w-full overflow-x-auto rounded-lg border" data-testid="accounts-receivable-table-scroll"><table className="min-w-full table-fixed text-left text-sm" style={{ minWidth: `${Math.max(tableMinWidth, 1)}px` }}><thead className="bg-muted/60 text-xs uppercase text-muted-foreground"><tr>{visible.map((column) => <Header key={column.id} column={column} sortBy={sortBy} sortDir={sortDir} onSort={changeSort} onResize={resizeColumn} />)}</tr></thead><tbody>{visible.length === 0 ? <tr><td className="px-3 py-10 text-center text-muted-foreground">Choose at least one column to view the report.</td></tr> : data.pageRows.length ? data.pageRows.map((row) => <tr key={row.id} className="border-t">{visible.map((column) => <Cell key={column.id} row={row} column={column} />)}</tr>) : <tr><td colSpan={visible.length} className="px-3 py-10 text-center text-muted-foreground">No approved outstanding invoices match these filters.</td></tr>}</tbody></table></section><div className="mt-4 flex items-center justify-between text-sm"><span className="text-muted-foreground">{data.totalCount} invoice{data.totalCount === 1 ? '' : 's'} · Page {data.page} of {data.totalPages}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={data.page <= 1} onClick={() => setPage((current) => current - 1)}>Previous</Button><Button variant="outline" size="sm" disabled={data.page >= data.totalPages} onClick={() => setPage((current) => current + 1)}>Next</Button></div></div><ColumnConfigModal open={columnConfigOpen} onOpenChange={setColumnConfigOpen} columns={columns} defaultColumns={arReportDefaultColumns} onSave={saveColumns} title="Accounts Receivable Columns" /></main>;
}
