import crypto from "crypto";
import type { Express } from "express";
import { and, eq, inArray, sql } from "drizzle-orm";
import { db } from "../db";
import { ObjectStorageService } from "../objectStorage";
import { localBridgeAgents, localFileCopyJobs, localFileDestinations, lineItemFiles } from "@shared/schema";
import { getRequestOrganizationId } from "../tenantContext";

const tokenHash = (token: string) => crypto.createHash("sha256").update(token).digest("hex");
const bridgeAuth = async (req: any, res: any, next: any) => { const raw = String(req.headers.authorization || "").replace(/^Bearer\s+/i, ""); if (!raw) return res.status(401).json({ error: "Bridge token required" }); const [agent] = await db.select().from(localBridgeAgents).where(and(eq(localBridgeAgents.tokenHash, tokenHash(raw)), eq(localBridgeAgents.status, "active"))).limit(1); if (!agent) return res.status(401).json({ error: "Invalid or revoked bridge token" }); req.bridgeAgent = agent; next(); };
export function registerLocalBridgeRoutes(app: Express, deps: { isAuthenticated: any; tenantContext: any; requireOrgOwnerAdmin: any }) {
  const admin = [deps.isAuthenticated, deps.tenantContext, deps.requireOrgOwnerAdmin];
  app.post("/api/local-bridge/admin/agents", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); const rawToken = crypto.randomBytes(32).toString("base64url"); const [agent] = await db.insert(localBridgeAgents).values({ organizationId, name: String(req.body?.name || "Local Bridge"), tokenHash: tokenHash(rawToken), status: "active" }).returning(); res.json({ success: true, data: { agent, token: rawToken } }); });
  app.get("/api/local-bridge/admin/agents", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); res.json({ success: true, data: await db.select().from(localBridgeAgents).where(eq(localBridgeAgents.organizationId, organizationId)) }); });
  app.post("/api/local-bridge/admin/agents/:id/revoke", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); await db.update(localBridgeAgents).set({ status: "revoked", revokedAt: new Date(), updatedAt: new Date() }).where(and(eq(localBridgeAgents.id, req.params.id), eq(localBridgeAgents.organizationId, organizationId))); res.json({ success: true, data: {} }); });
  app.post("/api/local-bridge/admin/destinations", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); const customerId = String(req.body?.customerId || ""); const localPath = String(req.body?.localPath || "").trim(); if (!customerId || !localPath) return res.status(400).json({ error: "customerId and localPath are required" }); const [destination] = await db.insert(localFileDestinations).values({ organizationId, customerId, localPath, destinationType: "customer_art_folder", enabled: req.body?.enabled !== false }).returning(); res.json({ success: true, data: destination }); });
  app.get("/api/local-bridge/admin/jobs", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); res.json({ success: true, data: await db.select().from(localFileCopyJobs).where(eq(localFileCopyJobs.organizationId, organizationId)).limit(50) }); });
  app.post("/api/local-bridge/heartbeat", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; await db.update(localBridgeAgents).set({ lastSeenAt: new Date(), machineLabel: String(req.body?.name || agent.name), agentVersion: req.body?.agentVersion || null, updatedAt: new Date() }).where(eq(localBridgeAgents.id, agent.id)); res.json({ success: true, data: { status: "active" } }); });
  app.get("/api/local-bridge/jobs", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const jobs = await db.select({ id: localFileCopyJobs.id, outputFilename: localFileCopyJobs.outputFilename, destinationPath: localFileDestinations.localPath }).from(localFileCopyJobs).innerJoin(localFileDestinations, eq(localFileCopyJobs.destinationId, localFileDestinations.id)).where(and(eq(localFileCopyJobs.organizationId, agent.organizationId), eq(localFileCopyJobs.status, "pending"), eq(localFileDestinations.destinationType, "customer_art_folder"))).limit(20); res.json({ success: true, data: jobs }); });
  app.post("/api/local-bridge/jobs/:id/claim", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const [job] = await db.update(localFileCopyJobs).set({ status: "claimed", claimedByAgentId: agent.id, claimedAt: new Date(), attempts: sql`${localFileCopyJobs.attempts} + 1`, updatedAt: new Date() }).where(and(eq(localFileCopyJobs.id, req.params.id), eq(localFileCopyJobs.organizationId, agent.organizationId), eq(localFileCopyJobs.status, "pending"))).returning(); if (!job) return res.status(409).json({ error: "Job is no longer available" }); res.json({ success: true, data: { ...job, downloadUrl: `/api/local-bridge/jobs/${job.id}/download`, destinationPath: (await db.select({ localPath: localFileDestinations.localPath }).from(localFileDestinations).where(eq(localFileDestinations.id, job.destinationId)).limit(1))[0]?.localPath } }); });
  app.get("/api/local-bridge/jobs/:id/download", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const [row] = await db.select({ key: lineItemFiles.storageKey, path: lineItemFiles.storagePath, name: lineItemFiles.originalFilename }).from(localFileCopyJobs).innerJoin(lineItemFiles, eq(localFileCopyJobs.sourceFileId, lineItemFiles.id)).where(and(eq(localFileCopyJobs.id, req.params.id), eq(localFileCopyJobs.organizationId, agent.organizationId), eq(localFileCopyJobs.claimedByAgentId, agent.id), eq(localFileCopyJobs.status, "claimed"))).limit(1); if (!row) return res.status(403).json({ error: "Job download is not authorized" }); const storage = new ObjectStorageService(); res.attachment(row.name); return storage.downloadObject(await storage.getObjectEntityFile(row.key || row.path), res, 0); });
  for (const outcome of ["succeeded", "failed"] as const) app.post(`/api/local-bridge/jobs/:id/${outcome}`, bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const [job] = await db.update(localFileCopyJobs).set({ status: outcome, completedAt: outcome === "succeeded" ? new Date() : null, lastError: outcome === "failed" ? String(req.body?.error || "Bridge copy failed") : null, updatedAt: new Date() }).where(and(eq(localFileCopyJobs.id, req.params.id), eq(localFileCopyJobs.organizationId, agent.organizationId), eq(localFileCopyJobs.claimedByAgentId, agent.id), eq(localFileCopyJobs.status, "claimed"))).returning(); if (!job) return res.status(409).json({ error: "Job is not claimed by this bridge" }); res.json({ success: true, data: job }); });
}
