import crypto from "crypto";
import path from "path";
import fs from "fs";
import archiver from "archiver";
import type { Express } from "express";
import { and, desc, eq, inArray, sql } from "drizzle-orm";
import { db } from "../db";
import { ObjectStorageService } from "../objectStorage";
import { auditLogs, customers, directPrintJobs, localBridgeAgents, localFileCopyJobs, localFileDestinations, lineItemFiles, orders, printerProfiles, productionRuns } from "@shared/schema";
import { getRequestOrganizationId } from "../tenantContext";

const tokenHash = (token: string) => crypto.createHash("sha256").update(token).digest("hex");
const bridgeAuth = async (req: any, res: any, next: any) => { const raw = String(req.headers.authorization || "").replace(/^Bearer\s+/i, ""); if (!raw) return res.status(401).json({ error: "Bridge token required" }); const [agent] = await db.select().from(localBridgeAgents).where(and(eq(localBridgeAgents.tokenHash, tokenHash(raw)), eq(localBridgeAgents.status, "active"))).limit(1); if (!agent) return res.status(401).json({ error: "Invalid or revoked bridge token" }); req.bridgeAgent = agent; next(); };
export function registerLocalBridgeRoutes(app: Express, deps: { isAuthenticated: any; tenantContext: any; requireOrgOwnerAdmin: any }) {
  const admin = [deps.isAuthenticated, deps.tenantContext, deps.requireOrgOwnerAdmin];
  app.post("/api/local-bridge/admin/agents", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); const rawToken = crypto.randomBytes(32).toString("base64url"); const [agent] = await db.insert(localBridgeAgents).values({ organizationId, name: String(req.body?.name || "Local Bridge"), tokenHash: tokenHash(rawToken), status: "active" }).returning(); res.json({ success: true, data: { agent, token: rawToken } }); });
  app.get("/api/local-bridge/admin/agents", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); res.json({ success: true, data: await db.select().from(localBridgeAgents).where(eq(localBridgeAgents.organizationId, organizationId)) }); });
  app.post("/api/local-bridge/admin/agents/:id/revoke", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); await db.update(localBridgeAgents).set({ status: "revoked", revokedAt: new Date(), updatedAt: new Date() }).where(and(eq(localBridgeAgents.id, req.params.id), eq(localBridgeAgents.organizationId, organizationId))); res.json({ success: true, data: {} }); });
  app.post("/api/local-bridge/admin/destinations", ...admin, async (req: any, res) => {
    const organizationId = getRequestOrganizationId(req); const customerId = String(req.body?.customerId || ""); const localPath = String(req.body?.localPath || "").trim();
    if (!customerId || !localPath) return res.status(400).json({ success: false, error: "customerId and localPath are required" });
    const [customer] = await db.select({ id: customers.id }).from(customers).where(and(eq(customers.id, customerId), eq(customers.organizationId, organizationId))).limit(1);
    if (!customer) return res.status(404).json({ success: false, error: "Customer not found" });
    const [existing] = await db.select({ id: localFileDestinations.id }).from(localFileDestinations).where(and(eq(localFileDestinations.organizationId, organizationId), eq(localFileDestinations.customerId, customerId), eq(localFileDestinations.destinationType, "customer_art_folder"))).orderBy(desc(localFileDestinations.updatedAt)).limit(1);
    const [destination] = existing
      ? await db.update(localFileDestinations).set({ localPath, enabled: req.body?.enabled !== false, updatedAt: new Date() }).where(eq(localFileDestinations.id, existing.id)).returning()
      : await db.insert(localFileDestinations).values({ organizationId, customerId, localPath, destinationType: "customer_art_folder", enabled: req.body?.enabled !== false }).returning();
    res.json({ success: true, data: destination });
  });
  app.delete("/api/local-bridge/admin/destinations", ...admin, async (req: any, res) => {
    const organizationId = getRequestOrganizationId(req); const customerId = String(req.body?.customerId || "");
    if (!customerId) return res.status(400).json({ success: false, error: "customerId is required" });
    const [customer] = await db.select({ id: customers.id }).from(customers).where(and(eq(customers.id, customerId), eq(customers.organizationId, organizationId))).limit(1);
    if (!customer) return res.status(404).json({ success: false, error: "Customer not found" });
    const updated = await db.update(localFileDestinations).set({ enabled: false, updatedAt: new Date() }).where(and(eq(localFileDestinations.organizationId, organizationId), eq(localFileDestinations.customerId, customerId), eq(localFileDestinations.destinationType, "customer_art_folder"))).returning();
    res.json({ success: true, data: updated[0] ?? null });
  });
  app.get("/api/local-bridge/admin/destinations", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); const customerId = String(req.query.customerId || ""); if (!customerId) return res.status(400).json({ error: "customerId is required" }); const [destination] = await db.select().from(localFileDestinations).where(and(eq(localFileDestinations.organizationId, organizationId), eq(localFileDestinations.customerId, customerId), eq(localFileDestinations.destinationType, "customer_art_folder"))).orderBy(desc(localFileDestinations.updatedAt)).limit(1); res.json({ success: true, data: destination ?? null }); });
  app.get("/api/local-bridge/admin/jobs", ...admin, async (req: any, res) => { const organizationId = getRequestOrganizationId(req); res.json({ success: true, data: await db.select().from(localFileCopyJobs).where(eq(localFileCopyJobs.organizationId, organizationId)).limit(50) }); });
  app.get("/api/local-bridge/admin/agent-package", ...admin, async (_req: any, res) => { const dir = [path.resolve(process.cwd(), "dist/local-bridge-agent"), path.resolve(process.cwd(), "local-bridge-agent")].find(fs.existsSync); if (!dir) return res.status(404).json({ error: "Agent package unavailable" }); res.attachment("printershero-local-bridge-agent-v1.zip"); const zip = archiver("zip"); zip.pipe(res); zip.directory(dir, "printershero-local-bridge-agent"); await zip.finalize(); });
  app.post("/api/local-bridge/heartbeat", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; await db.update(localBridgeAgents).set({ lastSeenAt: new Date(), machineLabel: String(req.body?.name || agent.name), agentVersion: req.body?.agentVersion || null, updatedAt: new Date() }).where(eq(localBridgeAgents.id, agent.id)); res.json({ success: true, data: { status: "active" } }); });
  // A print host only sees jobs assigned to its paired identity. Claiming is a
  // single conditional update so two agents cannot submit the same Traveler.
  app.get("/api/local-bridge/direct-print/jobs", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const rows = await db.select({ id: directPrintJobs.id, orderId: directPrintJobs.orderId, copies: directPrintJobs.copies, printNote: directPrintJobs.printNote, trailingFeedMm: directPrintJobs.trailingFeedMm, queueName: printerProfiles.windowsQueueName, destinationName: printerProfiles.displayName, location: printerProfiles.location }).from(directPrintJobs).innerJoin(printerProfiles, eq(directPrintJobs.destinationId, printerProfiles.id)).where(and(eq(directPrintJobs.organizationId, agent.organizationId), eq(directPrintJobs.agentId, agent.id), eq(directPrintJobs.status, "queued"))).limit(10); res.json({ success: true, data: rows }); });
  app.post("/api/local-bridge/direct-print/jobs/:id/claim", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const [job] = await db.update(directPrintJobs).set({ status: "claimed", claimedAt: new Date(), attempts: sql`${directPrintJobs.attempts} + 1`, updatedAt: new Date() }).where(and(eq(directPrintJobs.id, req.params.id), eq(directPrintJobs.organizationId, agent.organizationId), eq(directPrintJobs.agentId, agent.id), eq(directPrintJobs.status, "queued"))).returning(); if (!job) return res.status(409).json({ error: "Print job is no longer available" }); const [destination] = await db.select({ windowsQueueName: printerProfiles.windowsQueueName }).from(printerProfiles).where(and(eq(printerProfiles.id, job.destinationId), eq(printerProfiles.organizationId, agent.organizationId))).limit(1); res.json({ success: true, data: { ...job, queueName: destination?.windowsQueueName ?? null, travelerUrl: `/orders/${job.orderId}/traveler` } }); });
  app.get("/api/local-bridge/direct-print/jobs/:id/traveler", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const [job] = await db.select({ orderId: directPrintJobs.orderId, printNote: directPrintJobs.printNote, trailingFeedMm: directPrintJobs.trailingFeedMm }).from(directPrintJobs).where(and(eq(directPrintJobs.id, req.params.id), eq(directPrintJobs.agentId, agent.id), eq(directPrintJobs.organizationId, agent.organizationId), eq(directPrintJobs.status, "claimed"))).limit(1); if (!job) return res.status(404).json({ error: "Print job not claimed" }); const [order] = await db.select({ orderNumber: orders.orderNumber }).from(orders).where(and(eq(orders.id, job.orderId), eq(orders.organizationId, agent.organizationId))).limit(1); if (!order) return res.status(404).json({ error: "Order not found" }); res.json({ success: true, data: { orderId: job.orderId, orderNumber: order.orderNumber, printNote: job.printNote, trailingFeedMm: job.trailingFeedMm } }); });
  app.post("/api/local-bridge/direct-print/jobs/:id/:outcome", bridgeAuth, async (req: any, res) => { const outcome = req.params.outcome; if (outcome !== "submitted" && outcome !== "failed") return res.status(400).json({ error: "Invalid print outcome" }); const agent = req.bridgeAgent; const [job] = await db.update(directPrintJobs).set({ status: outcome, submittedAt: outcome === "submitted" ? new Date() : null, failedAt: outcome === "failed" ? new Date() : null, lastError: outcome === "failed" ? String(req.body?.error || "Windows print host failed") : null, updatedAt: new Date() }).where(and(eq(directPrintJobs.id, req.params.id), eq(directPrintJobs.organizationId, agent.organizationId), eq(directPrintJobs.agentId, agent.id), eq(directPrintJobs.status, "claimed"))).returning(); if (!job) return res.status(409).json({ error: "Print job is not claimed by this agent" }); res.json({ success: true, data: job }); });
  app.get("/api/local-bridge/jobs", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const jobs = await db.select({ id: localFileCopyJobs.id, outputFilename: localFileCopyJobs.outputFilename, destinationPath: localFileDestinations.localPath }).from(localFileCopyJobs).innerJoin(localFileDestinations, eq(localFileCopyJobs.destinationId, localFileDestinations.id)).where(and(eq(localFileCopyJobs.organizationId, agent.organizationId), eq(localFileCopyJobs.status, "pending"), eq(localFileDestinations.destinationType, "customer_art_folder"))).limit(20); res.json({ success: true, data: jobs }); });
  app.post("/api/local-bridge/jobs/:id/claim", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const [job] = await db.update(localFileCopyJobs).set({ status: "claimed", claimedByAgentId: agent.id, claimedAt: new Date(), attempts: sql`${localFileCopyJobs.attempts} + 1`, updatedAt: new Date() }).where(and(eq(localFileCopyJobs.id, req.params.id), eq(localFileCopyJobs.organizationId, agent.organizationId), eq(localFileCopyJobs.status, "pending"))).returning(); if (!job) return res.status(409).json({ error: "Job is no longer available" }); res.json({ success: true, data: { ...job, downloadUrl: `/api/local-bridge/jobs/${job.id}/download`, destinationPath: (await db.select({ localPath: localFileDestinations.localPath }).from(localFileDestinations).where(eq(localFileDestinations.id, job.destinationId)).limit(1))[0]?.localPath } }); });
  app.get("/api/local-bridge/jobs/:id/download", bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const [row] = await db.select({ key: lineItemFiles.storageKey, path: lineItemFiles.storagePath, outputFilename: localFileCopyJobs.outputFilename }).from(localFileCopyJobs).innerJoin(lineItemFiles, eq(localFileCopyJobs.sourceFileId, lineItemFiles.id)).where(and(eq(localFileCopyJobs.id, req.params.id), eq(localFileCopyJobs.organizationId, agent.organizationId), eq(localFileCopyJobs.claimedByAgentId, agent.id), eq(localFileCopyJobs.status, "claimed"))).limit(1); if (!row) return res.status(403).json({ error: "Job download is not authorized" }); const storage = new ObjectStorageService(); res.attachment(row.outputFilename); return storage.downloadObject(await storage.getObjectEntityFile(row.key || row.path), res, 0); });
  for (const outcome of ["succeeded", "failed"] as const) app.post(`/api/local-bridge/jobs/:id/${outcome}`, bridgeAuth, async (req: any, res) => { const agent = req.bridgeAgent; const [job] = await db.update(localFileCopyJobs).set({ status: outcome, completedAt: outcome === "succeeded" ? new Date() : null, lastError: outcome === "failed" ? String(req.body?.error || "Bridge copy failed") : null, updatedAt: new Date() }).where(and(eq(localFileCopyJobs.id, req.params.id), eq(localFileCopyJobs.organizationId, agent.organizationId), eq(localFileCopyJobs.claimedByAgentId, agent.id), eq(localFileCopyJobs.status, "claimed"))).returning(); if (!job) return res.status(409).json({ error: "Job is not claimed by this bridge" }); const [runFile] = await db.select({ productionRunId: lineItemFiles.productionRunId, runNumber: productionRuns.runNumber, fileName: lineItemFiles.originalFilename }).from(lineItemFiles).leftJoin(productionRuns, eq(productionRuns.id, lineItemFiles.productionRunId)).where(and(eq(lineItemFiles.id, job.sourceFileId), eq(lineItemFiles.organizationId, agent.organizationId))).limit(1); if (runFile?.productionRunId) await db.insert(auditLogs).values({ organizationId: agent.organizationId, userId: null, actionType: "UPDATE", entityType: "production_run", entityId: runFile.productionRunId, entityName: runFile.runNumber ? `PR-${String(runFile.runNumber).padStart(4, "0")}` : null, description: outcome === "succeeded" ? "Local Bridge copy completed for shared run file" : "Local Bridge copy failed for shared run file", newValues: { fileId: job.sourceFileId, filename: runFile.fileName, copyJobId: job.id, status: outcome, error: outcome === "failed" ? job.lastError : null } } as any); res.json({ success: true, data: job }); });
}
