import { createHash, randomUUID } from "node:crypto";
import type { OperationContext } from "../../application/operation.js";
import { requireOperationPrincipalScope } from "../../application/operation.js";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import { principalSubject, staffActorId } from "../../authorization/principals.js";
import { failure, success, type ApplicationResult, V2ApplicationError } from "../../errors/applicationError.js";
import { brandedId, canonicalJson, money, type InvoiceId, type OrganizationId, type PaymentId, type ProviderFinancialOperationId } from "../shared/commercialValues.js";
import type { BeginProviderFinancialOperationInput, ConfirmProviderPaymentInput, ConfirmProviderRefundInput, InvoiceSettlement, PaymentFact, ProviderFinancialOperation, RecordManualPaymentInput, RecordRefundInput, RefundFact } from "./contracts.js";

type Actor = Readonly<{ principalKind: OperationContext["principal"]["kind"]; principalSubject: string; staffActorUserId?: string }>;
type Reservation = Readonly<{ kind: "new" | "resumed" | "replay"; request: Readonly<{ id: string; resultJson: unknown | null }> }>;
export type FinancialLockedInvoice = Readonly<{ invoiceId: InvoiceId; customerId?: string; currency: string; totalCents: number; lifecycle: "draft" | "issued" | "void" }>;
export type ProviderPaymentConfirmation = Readonly<{ payment: PaymentFact; materialized: boolean }>;
export type ProviderRefundConfirmation = Readonly<{ refund: RefundFact; materialized: boolean }>;
export interface BillingFinancialTransaction {
  reserve(input: Readonly<{ organizationId: string; operation: string; businessRequestId: string; payloadFingerprint: string }> & Actor): Promise<Reservation>;
  lockInvoice(organizationId: OrganizationId, invoiceId: InvoiceId): Promise<FinancialLockedInvoice | null>;
  settlement(organizationId: OrganizationId, invoiceId: InvoiceId, currency: string, grossCents: number): Promise<InvoiceSettlement>;
  recordPayment(input: Readonly<{ organizationId: OrganizationId; invoiceId: InvoiceId; amountCents: number; currency: string; method: string; occurredAt: string; operationRequestId: string }> & Actor): Promise<PaymentFact>;
  recordRefund(input: Readonly<{ organizationId: OrganizationId; invoiceId: InvoiceId; paymentId: PaymentId; amountCents: number; currency: string; occurredAt: string; operationRequestId: string }> & Actor): Promise<RefundFact>;
  beginProvider(input: Readonly<{ organizationId: OrganizationId; invoiceId: InvoiceId; kind: "payment" | "refund"; paymentId?: PaymentId; amountCents: number; currency: string; provider: string; providerIdempotencyKey: string; providerAccountId?: string; operationRequestId: string }>): Promise<ProviderFinancialOperation>;
  confirmProviderPayment(input: Readonly<{ organizationId: OrganizationId; invoiceId: InvoiceId; providerOperationId: ProviderFinancialOperationId; providerEventId: string; providerTransactionId: string; occurredAt: string; operationRequestId: string }> & Actor): Promise<ProviderPaymentConfirmation>;
  confirmProviderRefund(input: Readonly<{ organizationId: OrganizationId; invoiceId: InvoiceId; paymentId: PaymentId; providerOperationId: ProviderFinancialOperationId; providerEventId: string; providerTransactionId: string; occurredAt: string; operationRequestId: string }> & Actor): Promise<ProviderRefundConfirmation>;
  attribute(input: Readonly<{ organizationId: string; operationRequestId: string; operation: string; resourceType: string; resourceId: string }> & Actor): Promise<void>;
  audit(input: Readonly<{ organizationId: string; operationRequestId: string; operation: string; eventType: string; resourceType: string; resourceId: string; changes: unknown }> & Actor): Promise<void>;
  enqueue(input: Readonly<{ organizationId: string; eventType: string; aggregateType: string; aggregateId: string; idempotencyKey: string; payload: unknown }>): Promise<void>;
  succeed(organizationId: string, requestId: string, resourceType: string, resourceId: string, result: unknown): Promise<void>;
}
export interface BillingFinancialTransactionRunner { transaction<T>(action: (transaction: BillingFinancialTransaction) => Promise<T>): Promise<T>; }
const actor = (context: OperationContext): Actor => ({ principalKind: context.principal.kind, principalSubject: principalSubject(context.principal), ...(staffActorId(context.principal) ? { staffActorUserId: staffActorId(context.principal) } : {}) });
const fingerprint = (value: unknown) => `sha256:${createHash("sha256").update(canonicalJson(value)).digest("hex")}`;
const assertMoney = (amount: { cents: number; currency: string }) => { if (!Number.isSafeInteger(amount.cents) || amount.cents <= 0) throw new V2ApplicationError("VALIDATION_ERROR", "Financial amounts must be positive exact integer cents."); };

/** Billing financial facts are append-only; provider uncertainty is a recovery record, not a payment. */
export class BillingPaymentsApplicationService {
  constructor(private readonly runner: BillingFinancialTransactionRunner, private readonly authority = new AuthorityPolicy()) {}
  async recordManualPayment(context: OperationContext, input: RecordManualPaymentInput): Promise<ApplicationResult<Readonly<{ payment: PaymentFact; settlement: InvoiceSettlement }>>>
  { return this.withInvoice(context, input, "billing.payment.record.v1", "payment.record", async (tx, invoice, requestId) => { this.assertCollectible(invoice, input.amount); const before = await tx.settlement(input.organizationId, input.invoiceId, invoice.currency, invoice.totalCents); if (input.amount.cents > before.collectibleBalance.cents) throw new V2ApplicationError("CONFLICT", "Payment exceeds the collectible Invoice balance."); const payment = await tx.recordPayment({ organizationId: input.organizationId, invoiceId: input.invoiceId, amountCents: input.amount.cents, currency: input.amount.currency, method: input.method, occurredAt: input.occurredAt, operationRequestId: requestId, ...actor(context) }); const settlement = await tx.settlement(input.organizationId, input.invoiceId, invoice.currency, invoice.totalCents); await this.finish(tx, context, requestId, "billing.payment.record.v1", "payment_recorded", "payment", payment.paymentId, { invoiceId: input.invoiceId, amountCents: input.amount.cents, source: "manual" }, { payment, settlement }); return { payment, settlement }; }); }
  async recordRefund(context: OperationContext, input: RecordRefundInput): Promise<ApplicationResult<Readonly<{ refund: RefundFact; settlement: InvoiceSettlement }>>>
  { return this.withInvoice(context, input, "billing.refund.record.v1", "refund.issue", async (tx, invoice, requestId) => { this.assertCollectible(invoice, input.amount); const refund = await tx.recordRefund({ organizationId: input.organizationId, invoiceId: input.invoiceId, paymentId: input.paymentId, amountCents: input.amount.cents, currency: input.amount.currency, occurredAt: input.occurredAt, operationRequestId: requestId, ...actor(context) }); const settlement = await tx.settlement(input.organizationId, input.invoiceId, invoice.currency, invoice.totalCents); await this.finish(tx, context, requestId, "billing.refund.record.v1", "refund_recorded", "refund", refund.refundId, { paymentId: input.paymentId, amountCents: input.amount.cents }, { refund, settlement }); return { refund, settlement }; }); }
  async beginProviderOperation(context: OperationContext, input: BeginProviderFinancialOperationInput): Promise<ApplicationResult<ProviderFinancialOperation>>
  { return this.withInvoice(context, input, `billing.provider.${input.kind}.begin.v1`, input.kind === "payment" ? "payment.record" : "refund.issue", async (tx, invoice, requestId) => { this.assertCollectible(invoice, input.amount); if (input.kind === "payment") { const settlement = await tx.settlement(input.organizationId, input.invoiceId, invoice.currency, invoice.totalCents); if (input.amount.cents > settlement.collectibleBalance.cents) throw new V2ApplicationError("CONFLICT", "Payment exceeds the collectible Invoice balance."); } const operation = await tx.beginProvider({ organizationId: input.organizationId, invoiceId: input.invoiceId, kind: input.kind, ...(input.paymentId ? { paymentId: input.paymentId } : {}), amountCents: input.amount.cents, currency: input.amount.currency, provider: input.provider, providerIdempotencyKey: input.providerIdempotencyKey, ...(input.providerAccountId ? { providerAccountId: input.providerAccountId } : {}), operationRequestId: requestId }); await tx.attribute({ organizationId: input.organizationId, operationRequestId: requestId, operation: `billing.provider.${input.kind}.begin.v1`, resourceType: "provider_financial_operation", resourceId: operation.providerOperationId, ...actor(context) }); await tx.audit({ organizationId: input.organizationId, operationRequestId: requestId, operation: `billing.provider.${input.kind}.begin.v1`, eventType: "provider_financial_reconciliation_required", resourceType: "provider_financial_operation", resourceId: operation.providerOperationId, changes: [{ kind: input.kind, provider: input.provider, reconciliationState: "pending" }], ...actor(context) }); await tx.succeed(input.organizationId, requestId, "provider_financial_operation", operation.providerOperationId, operation); return operation; }); }
  async confirmProviderPayment(context: OperationContext, input: ConfirmProviderPaymentInput): Promise<ApplicationResult<PaymentFact>> { return this.withInvoice(context, input, "billing.provider.payment.confirm.v1", "payment.record", async (tx, invoice, requestId) => { const confirmation = await tx.confirmProviderPayment({ organizationId: input.organizationId, invoiceId: input.invoiceId, providerOperationId: input.providerOperationId, providerEventId: input.providerEventId, providerTransactionId: input.providerTransactionId, occurredAt: input.occurredAt, operationRequestId: requestId, ...actor(context) }); if (confirmation.materialized) await this.finish(tx, context, requestId, "billing.provider.payment.confirm.v1", "provider_payment_succeeded", "payment", confirmation.payment.paymentId, { providerOperationId: input.providerOperationId }, confirmation.payment); else await tx.succeed(context.organizationId, requestId, "payment", confirmation.payment.paymentId, confirmation.payment); return confirmation.payment; }); }
  async confirmProviderRefund(context: OperationContext, input: ConfirmProviderRefundInput): Promise<ApplicationResult<RefundFact>> { return this.withInvoice(context, input, "billing.provider.refund.confirm.v1", "refund.issue", async (tx, invoice, requestId) => { const confirmation = await tx.confirmProviderRefund({ organizationId: input.organizationId, invoiceId: input.invoiceId, paymentId: input.paymentId, providerOperationId: input.providerOperationId, providerEventId: input.providerEventId, providerTransactionId: input.providerTransactionId, occurredAt: input.occurredAt, operationRequestId: requestId, ...actor(context) }); if (confirmation.materialized) await this.finish(tx, context, requestId, "billing.provider.refund.confirm.v1", "provider_refund_succeeded", "refund", confirmation.refund.refundId, { providerOperationId: input.providerOperationId, paymentId: input.paymentId }, confirmation.refund); else await tx.succeed(context.organizationId, requestId, "refund", confirmation.refund.refundId, confirmation.refund); return confirmation.refund; }); }
  private assertCollectible(invoice: FinancialLockedInvoice, amount: { currency: string; cents: number }) { assertMoney(amount); if (invoice.lifecycle !== "issued") throw new V2ApplicationError("CONFLICT", "Only an issued Invoice may accept financial transactions."); if (invoice.currency !== amount.currency) throw new V2ApplicationError("VALIDATION_ERROR", "Financial transaction currency must equal the issued Invoice currency."); }
  private async withInvoice<T extends { businessRequestId: string; organizationId: OrganizationId; invoiceId: InvoiceId }>(context: OperationContext, input: T, operation: string, capability: "payment.record" | "refund.issue", action: (tx: BillingFinancialTransaction, invoice: FinancialLockedInvoice, requestId: string) => Promise<unknown>): Promise<ApplicationResult<any>> {
    try {
      requireOperationPrincipalScope(context);
      if (!context.businessRequest || context.businessRequest.id !== input.businessRequestId) throw new V2ApplicationError("VALIDATION_ERROR", "A matching business request identity is required.");
      return success(await this.runner.transaction(async (tx) => {
        const locked = await tx.lockInvoice(input.organizationId, input.invoiceId);
        if (!locked) throw new V2ApplicationError("NOT_FOUND", "Invoice was not found.");
        const decision = this.authority.decide(context.principal, { capability, resource: { organizationId: context.organizationId, customerId: locked.customerId } });
        if (!decision.allowed) throw new V2ApplicationError("FORBIDDEN", "The principal is not authorized for this financial operation.");
        const reservation = await tx.reserve({ organizationId: input.organizationId, operation, businessRequestId: input.businessRequestId, payloadFingerprint: fingerprint(input), ...actor(context) });
        if (reservation.kind === "replay") return reservation.request.resultJson;
        return action(tx, locked, reservation.request.id);
      }));
    } catch (error) {
      return failure(error instanceof V2ApplicationError ? error : new V2ApplicationError("CONFLICT", "Financial operation conflicts with the immutable ledger."));
    }
  }
  private async finish(tx: BillingFinancialTransaction, context: OperationContext, requestId: string, operation: string, eventType: string, resourceType: string, resourceId: string, changes: unknown, result: unknown) { await tx.attribute({ organizationId: context.organizationId, operationRequestId: requestId, operation, resourceType, resourceId, ...actor(context) }); await tx.audit({ organizationId: context.organizationId, operationRequestId: requestId, operation, eventType, resourceType, resourceId, changes, ...actor(context) }); await tx.enqueue({ organizationId: context.organizationId, eventType: `billing.${eventType}.v1`, aggregateType: resourceType, aggregateId: resourceId, idempotencyKey: requestId, payload: { resourceId } }); await tx.succeed(context.organizationId, requestId, resourceType, resourceId, result); }
}
