import { Router, type Request } from "express";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import type { Principal } from "../../authorization/principals.js";
import type { OperationContext } from "../../application/operation.js";
import { V2ApplicationError } from "../../errors/applicationError.js";
import type { FormulaDomainApplicationService, FormulaRevisionDefinition } from "../../modules/pricing/formulaDomain.js";
import type { FormulaStatus, FormulaVisibility } from "../../modules/pricing/formulaDomain.js";

export interface FormulaDomainReadPort { list(organizationId:string,input?:Readonly<{includeInactive?:boolean;query?:string}>):Promise<readonly unknown[]>; get(organizationId:string,formulaId:string):Promise<unknown|null>; revisions(organizationId:string,formulaId:string):Promise<readonly unknown[]>; usage(organizationId:string,formulaId:string):Promise<readonly unknown[]>; }
export type FormulaHttpDependencies=Readonly<{reads:FormulaDomainReadPort;service:FormulaDomainApplicationService;principals:Readonly<{principal(request:Request,organizationId:string):Promise<Principal>}>}>;
const status=(code:string)=>code==="VALIDATION_ERROR"?400:code==="FORBIDDEN"?403:code==="NOT_FOUND"||code==="WRONG_TENANT"?404:code==="CONFLICT"||code==="STALE_STATE"||code==="IDEMPOTENCY_CONFLICT"?409:500;
const command=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new V2ApplicationError("VALIDATION_ERROR","A Formula command object is required.");return value as Record<string,unknown>;};
const context=async(request:Request,dependencies:FormulaHttpDependencies):Promise<OperationContext>=>{const organizationId=request.params.organizationId,body=command(request.body),businessRequestId=body.businessRequestId;if(!organizationId?.trim()||typeof businessRequestId!=="string"||!businessRequestId.trim())throw new V2ApplicationError("VALIDATION_ERROR","organizationId and businessRequestId are required.");return{principal:await dependencies.principals.principal(request,organizationId),organizationId,operationId:`http:${request.method}:${request.path}`,businessRequest:{id:businessRequestId,payloadFingerprint:"formula-fingerprint-is-derived-by-operation"}};};
const error=(response:any,cause:unknown,message:string)=>{const problem=cause instanceof V2ApplicationError?cause:new V2ApplicationError("INTERNAL_ERROR",message);return response.status(status(problem.code)).json({ok:false,error:{code:problem.code,message:problem.publicMessage}});};
const definition=(body:Record<string,unknown>):FormulaRevisionDefinition=>{const input=body.definition;if(!input||typeof input!=="object"||Array.isArray(input))throw new V2ApplicationError("VALIDATION_ERROR","Formula definition is required.");const raw=input as Record<string,unknown>;if(typeof raw.expression!=="string"||!Array.isArray(raw.declaredInputs))throw new V2ApplicationError("VALIDATION_ERROR","Formula expression and declared inputs are required.");return{expression:raw.expression,declaredInputs:raw.declaredInputs as any, ...(raw.validationEvidence&&typeof raw.validationEvidence==="object"&&!Array.isArray(raw.validationEvidence)?{validationEvidence:raw.validationEvidence as Record<string,unknown>}:{})};};

/** V2 Formula-domain transport. Formula revisions never use the legacy /api path. */
export const createFormulaRouter=(dependencies:FormulaHttpDependencies):Router=>{
  const router=Router({mergeParams:true});
  const read=async(request:Request)=>{const organizationId=request.params.organizationId;if(!organizationId?.trim())throw new V2ApplicationError("VALIDATION_ERROR","organizationId is required.");const principal=await dependencies.principals.principal(request,organizationId);if(!new AuthorityPolicy().decide(principal,{capability:"product.view",resource:{organizationId}}).allowed)throw new V2ApplicationError("FORBIDDEN","You do not have permission to view Formulas.");return organizationId;};
  router.get("/",async(request,response)=>{try{const organizationId=await read(request);return response.json({ok:true,data:await dependencies.reads.list(organizationId,{includeInactive:request.query.includeInactive==="true",...(typeof request.query.q==="string"?{query:request.query.q}:{})})});}catch(cause){return error(response,cause,"Formula list is unavailable.");}});
  router.get("/:formulaId",async(request,response)=>{try{const organizationId=await read(request),value=await dependencies.reads.get(organizationId,request.params.formulaId);if(!value)throw new V2ApplicationError("NOT_FOUND","The tenant-scoped Formula was not found.");return response.json({ok:true,data:value});}catch(cause){return error(response,cause,"Formula is unavailable.");}});
  // Revisions and usage are subordinate Formula resources. Do not make an
  // unknown or cross-tenant Formula look like an empty history/usage list.
  const requireFormula=async(organizationId:string,formulaId:string)=>{const value=await dependencies.reads.get(organizationId,formulaId);if(!value)throw new V2ApplicationError("NOT_FOUND","The tenant-scoped Formula was not found.");return value;};
  router.get("/:formulaId/revisions",async(request,response)=>{try{const organizationId=await read(request);await requireFormula(organizationId,request.params.formulaId);return response.json({ok:true,data:await dependencies.reads.revisions(organizationId,request.params.formulaId)});}catch(cause){return error(response,cause,"Formula revisions are unavailable.");}});
  router.get("/:formulaId/usage",async(request,response)=>{try{const organizationId=await read(request);await requireFormula(organizationId,request.params.formulaId);return response.json({ok:true,data:await dependencies.reads.usage(organizationId,request.params.formulaId)});}catch(cause){return error(response,cause,"Formula usage is unavailable.");}});
  router.post("/",async(request,response)=>{try{const body=command(request.body),result=await dependencies.service.create(await context(request,dependencies),{businessRequestId:body.businessRequestId as string,name:body.name as string, ...(typeof body.description==="string"?{description:body.description}:{}),visibility:body.visibility as FormulaVisibility,definition:definition(body)});return response.status(result.ok?201:status(result.error.code)).json(result.ok?{ok:true,data:result.value}:{ok:false,error:{code:result.error.code,message:result.error.publicMessage}});}catch(cause){return error(response,cause,"Formula could not be created.");}});
  router.post("/:formulaId/revisions",async(request,response)=>{try{const body=command(request.body),result=await dependencies.service.revise(await context(request,dependencies),{businessRequestId:body.businessRequestId as string,formulaId:request.params.formulaId,expectedCurrentRevisionId:body.expectedCurrentRevisionId as string,definition:definition(body)});return response.status(result.ok?200:status(result.error.code)).json(result.ok?{ok:true,data:result.value}:{ok:false,error:{code:result.error.code,message:result.error.publicMessage}});}catch(cause){return error(response,cause,"Formula could not be revised.");}});
  router.post("/:formulaId/metadata",async(request,response)=>{try{const body=command(request.body);if(!Object.hasOwn(body,"description")||(typeof body.description!=="string"&&body.description!==null))throw new V2ApplicationError("VALIDATION_ERROR","Formula description must be a string or null.");const result=await dependencies.service.updateMetadata(await context(request,dependencies),{businessRequestId:body.businessRequestId as string,formulaId:request.params.formulaId,expectedCurrentRevisionId:body.expectedCurrentRevisionId as string,name:body.name as string,...(typeof body.description==="string"?{description:body.description}:{})});return response.status(result.ok?200:status(result.error.code)).json(result.ok?{ok:true,data:result.value}:{ok:false,error:{code:result.error.code,message:result.error.publicMessage}});}catch(cause){return error(response,cause,"Formula metadata could not be updated.");}});
  router.post("/:formulaId/visibility",async(request,response)=>{try{const body=command(request.body),result=await dependencies.service.setVisibility(await context(request,dependencies),{businessRequestId:body.businessRequestId as string,formulaId:request.params.formulaId,expectedCurrentRevisionId:body.expectedCurrentRevisionId as string,visibility:body.visibility as FormulaVisibility});return response.status(result.ok?200:status(result.error.code)).json(result.ok?{ok:true,data:result.value}:{ok:false,error:{code:result.error.code,message:result.error.publicMessage}});}catch(cause){return error(response,cause,"Formula visibility could not be updated.");}});
  router.post("/:formulaId/status",async(request,response)=>{try{const body=command(request.body),result=await dependencies.service.setStatus(await context(request,dependencies),{businessRequestId:body.businessRequestId as string,formulaId:request.params.formulaId,expectedCurrentRevisionId:body.expectedCurrentRevisionId as string,status:body.status as FormulaStatus});return response.status(result.ok?200:status(result.error.code)).json(result.ok?{ok:true,data:result.value}:{ok:false,error:{code:result.error.code,message:result.error.publicMessage}});}catch(cause){return error(response,cause,"Formula status could not be updated.");}});
  return router;
};
