import type { Request, Response, Router } from "express";
import { Router as expressRouter } from "express";
import type { OperationContext } from "../../application/operation.js";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import type { Principal } from "../../authorization/principals.js";
import { type ApplicationResult, V2ApplicationError } from "../../errors/applicationError.js";
import type { CompleteFulfillmentInput, FulfillmentWorkspaceReadPort } from "../../modules/fulfillment/contracts.js";
import { brandedId, type OrderId, type OrderLineId } from "../../modules/shared/commercialValues.js";
export interface FulfillmentHttpService { getAvailability(context:OperationContext,orderId:OrderId):Promise<ApplicationResult<unknown>>;recordPickup(context:OperationContext,input:CompleteFulfillmentInput):Promise<ApplicationResult<unknown>>;recordShipment(context:OperationContext,input:CompleteFulfillmentInput):Promise<ApplicationResult<unknown>>; }
export interface VerifiedV2FulfillmentPrincipalProvider { principal(request:Request,organizationId:string):Promise<Principal> }
export type FulfillmentHttpDependencies=Readonly<{service:FulfillmentHttpService;principals:VerifiedV2FulfillmentPrincipalProvider;workspace:FulfillmentWorkspaceReadPort}>;
const status=(code:string)=>code==="VALIDATION_ERROR"?400:code==="FORBIDDEN"?403:code==="NOT_FOUND"||code==="WRONG_TENANT"?404:code==="CONFLICT"||code==="STALE_STATE"||code==="IDEMPOTENCY_CONFLICT"?409:500;
const object=(value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new V2ApplicationError("VALIDATION_ERROR","A Fulfillment command object is required.");return value as Record<string,unknown>;};
const context=async(request:Request,deps:FulfillmentHttpDependencies,mutation=false):Promise<OperationContext>=>{const organizationId=request.params.organizationId;if(!organizationId)throw new V2ApplicationError("VALIDATION_ERROR","organizationId is required.");const command=mutation?object(request.body):undefined;const candidate=command?.businessRequestId;if(mutation&&(typeof candidate!=="string"||!candidate.trim()))throw new V2ApplicationError("VALIDATION_ERROR","businessRequestId is required.");const id=typeof candidate==="string"?candidate:"";return {principal:await deps.principals.principal(request,organizationId),organizationId,operationId:`http:${request.method}:${request.path}`,...(mutation?{businessRequest:{id,payloadFingerprint:"route-fingerprint-is-derived-by-operation"}}:{})};};
const command=(request:Request):CompleteFulfillmentInput=>{const body=object(request.body),allocations=body.allocations;if(!Array.isArray(allocations))throw new V2ApplicationError("VALIDATION_ERROR","allocations must be an array.");return {businessRequestId:body.businessRequestId as string,orderId:brandedId<"OrderId">(request.params.orderId),allocations:allocations.map((value)=>{const item=object(value);if(typeof item.orderLineId!=="string"||typeof item.quantity!=="number")throw new V2ApplicationError("VALIDATION_ERROR","Each allocation requires orderLineId and quantity.");return {orderLineId:brandedId<"OrderLineId">(item.orderLineId),quantity:item.quantity};})};};
const send=(response:Response,result:ApplicationResult<unknown>)=>result.ok?response.status(200).json({ok:true,data:result.value}):response.status(status(result.error.code)).json({ok:false,error:{code:result.error.code,message:result.error.publicMessage}});
const run=async(response:Response,operation:()=>Promise<void>)=>{try{await operation();}catch(cause){const error=cause instanceof V2ApplicationError?cause:new V2ApplicationError("INTERNAL_ERROR","Fulfillment operation is unavailable.");response.status(status(error.code)).json({ok:false,error:{code:error.code,message:error.publicMessage}});}};
export const createFulfillmentRouter=(deps:FulfillmentHttpDependencies):Router=>{const router=expressRouter({mergeParams:true});router.get("/",(request,response)=>void run(response,async()=>{const op=await context(request,deps);if(!new AuthorityPolicy().decide(op.principal,{capability:"fulfillment.view",resource:{organizationId:op.organizationId}}).allowed)throw new V2ApplicationError("FORBIDDEN","Fulfillment access is unavailable.");response.status(200).json({ok:true,data:await deps.workspace.list(brandedId<"OrganizationId">(op.organizationId),{limit:Number(request.query.limit??25),...(typeof request.query.q==="string"?{search:request.query.q}:{}),...(typeof request.query.cursor==="string"?{cursor:request.query.cursor}:{})})});}));router.get("/orders/:orderId",(request,response)=>void run(response,async()=>{const op=await context(request,deps),result=await deps.workspace.get(brandedId<"OrganizationId">(op.organizationId),brandedId<"OrderId">(request.params.orderId));if(!result)throw new V2ApplicationError("NOT_FOUND","Order was not found.");if(!new AuthorityPolicy().decide(op.principal,{capability:"fulfillment.view",resource:{organizationId:op.organizationId,customerId:result.customerId}}).allowed)throw new V2ApplicationError("FORBIDDEN","Fulfillment access is unavailable.");response.status(200).json({ok:true,data:result});}));router.get("/orders/:orderId/availability",(request,response)=>void run(response,async()=>{send(response,await deps.service.getAvailability(await context(request,deps),brandedId<"OrderId">(request.params.orderId)));}));router.post("/orders/:orderId/pickups",(request,response)=>void run(response,async()=>{send(response,await deps.service.recordPickup(await context(request,deps,true),command(request)));}));router.post("/orders/:orderId/shipments",(request,response)=>void run(response,async()=>{send(response,await deps.service.recordShipment(await context(request,deps,true),command(request)));}));return router;};
