import { Router, type Request, type Response } from "express";
import type { Principal, PortalPrincipal } from "../../authorization/principals.js";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import { V2ApplicationError } from "../../errors/applicationError.js";
import type { PortalOrderCommand, PortalOrderCreationApplicationService } from "../../modules/portal/portalOrderCreation.js";
import type { OrderLineInput } from "../../modules/sales/orderApplication.js";

export type PortalOrderHttpDependencies=Readonly<{portalPrincipal:Readonly<{principal(request:Request):Promise<Principal>}>;service:PortalOrderCreationApplicationService}>;
const fail=(response:Response,cause:unknown)=>{const error=cause instanceof V2ApplicationError?cause:new V2ApplicationError("INTERNAL_ERROR","Portal Order creation is unavailable.");const status=error.code==="VALIDATION_ERROR"?400:error.code==="FORBIDDEN"?403:error.code==="NOT_FOUND"||error.code==="WRONG_TENANT"?404:error.code==="CONFLICT"||error.code==="STALE_STATE"||error.code==="IDEMPOTENCY_CONFLICT"?409:500;return response.status(status).json({ok:false,error:{code:error.code,message:error.publicMessage}});};
const command=(value:unknown):PortalOrderCommand=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new V2ApplicationError("VALIDATION_ERROR","A Portal Order command object is required.");const input=value as Record<string,unknown>;if(typeof input.businessRequestId!=="string"||!input.businessRequestId.trim())throw new V2ApplicationError("VALIDATION_ERROR","businessRequestId is required.");if(!Array.isArray(input.lines)||!input.lines.length)throw new V2ApplicationError("VALIDATION_ERROR","At least one Order line is required.");const lines=input.lines.map((line):OrderLineInput=>{if(!line||typeof line!=="object"||Array.isArray(line))throw new V2ApplicationError("VALIDATION_ERROR","Each Order line must be an object.");const item=line as Record<string,unknown>,quantity=item.quantity;if(typeof item.productId!=="string"||!item.productId.trim()||typeof quantity!=="number"||!Number.isSafeInteger(quantity)||quantity<=0)throw new V2ApplicationError("VALIDATION_ERROR","Each Order line requires an entitled Product and positive whole quantity.");return{...(typeof item.clientLineKey==="string"?{clientLineKey:item.clientLineKey}:{}),productId:item.productId,...(typeof item.description==="string"?{description:item.description}:{}),quantity,...(item.selections&&typeof item.selections==="object"&&!Array.isArray(item.selections)?{selections:item.selections as Record<string,unknown>}:{}),...(item.dimensions&&typeof item.dimensions==="object"&&!Array.isArray(item.dimensions)?{dimensions:item.dimensions as OrderLineInput["dimensions"]}:{}),selling:{kind:"calculated"}};});return{businessRequestId:input.businessRequestId.trim(),...(typeof input.purchaseOrderNumber==="string"?{purchaseOrderNumber:input.purchaseOrderNumber}:{}),...(typeof input.requestedDueDate==="string"?{requestedDueDate:input.requestedDueDate}:{}),...(input.requestedFulfillment&&typeof input.requestedFulfillment==="object"&&!Array.isArray(input.requestedFulfillment)?{requestedFulfillment:input.requestedFulfillment as PortalOrderCommand["requestedFulfillment"]}:{}),...(typeof input.notes==="string"?{notes:input.notes}:{}),lines};};
const principal=async(dependencies:PortalOrderHttpDependencies,request:Request):Promise<PortalPrincipal>=>{const actor=await dependencies.portalPrincipal.principal(request);if(actor.kind!=="portal")throw new V2ApplicationError("FORBIDDEN","Portal access is required.");if(!new AuthorityPolicy().decide(actor,{capability:"order.create",resource:{organizationId:actor.organizationId,customerId:actor.customerId}}).allowed)throw new V2ApplicationError("FORBIDDEN","Order creation is unavailable for this Portal account.");return actor;};
/** POST /v2/portal/orders delegates directly to canonical Sales. */
export const createPortalOrderRouter=(dependencies:PortalOrderHttpDependencies)=>{const router=Router();router.post("/orders",async(request,response)=>{try{const result=await dependencies.service.create(await principal(dependencies,request),command(request.body));if(!result.ok)return fail(response,result.error);return response.status(201).json({ok:true,data:result.value});}catch(cause){return fail(response,cause);}});return router;};
