import { Router, type Request, type Response } from "express";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import type { Principal } from "../../authorization/principals.js";
import { brandedId } from "../../modules/shared/commercialValues.js";
import type { ProductDraftGeneral, ProductDraftGeneralRead, ProductVersionLifecycle } from "../../modules/products/productVersionLifecycle.js";
import type { ProductVersionLifecycleApplicationService } from "../../modules/products/productVersionLifecycle.js";

export type ProductLifecycle = "active" | "inactive" | "draft" | "active_with_draft";
export type ProductCatalogItem = Readonly<{
  productId: string; displayName: string; category?: string; lifecycle: ProductLifecycle;
  measurementMode: "dimensions_required" | "quantity_only"; pricingSummary: string;
  productType?: Readonly<{ displayName: string; routePolicy: "route_required" | "no_route" | "unconfigured" }>;
  primaryMaterialName?: string; activeVersion?: Readonly<{ label: string; publishedAt?: string }>;
  hasDraft: boolean;
}>;
export type ProductWorkspaceDetail = Readonly<ProductCatalogItem & {
  description?: string; workflowIntent: "standard_production" | "fulfillment_only" | "service_fee";
  requiresProductionJob: boolean; requiresProofApproval: boolean;
  configurableOptionCount: number;
  versions: ProductVersionLifecycle;
}>;
export type ProductCatalogPage = Readonly<{ items: readonly ProductCatalogItem[]; page: number; pageSize: number; total: number; hasMore: boolean }>;
export interface ProductWorkspaceReadPort {
  list(organizationId: string, input?: Readonly<{ query?: string; page?: number; pageSize?: number }>): Promise<ProductCatalogPage>;
  get(organizationId: string, productId: string): Promise<ProductWorkspaceDetail | null>;
}
export interface ProductDraftGeneralReadPort { read(organizationId: string, productId: string): Promise<ProductDraftGeneralRead | null>; }
export type ProductHttpDependencies = Readonly<{ workspace: ProductWorkspaceReadPort; draftGeneral: ProductDraftGeneralReadPort; lifecycle: ProductVersionLifecycleApplicationService; principals: Readonly<{ principal(request: Request, organizationId: string): Promise<Principal> }> }>;
const deny = (response: Response, status: 403 | 404, code: "FORBIDDEN" | "NOT_FOUND", message: string) => response.status(status).json({ ok: false, error: { code, message } });
const validProductId = (value: string) => /^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$/u.test(value);
const positive = (value: unknown, fallback: number, max: number) => typeof value === "string" && /^\d+$/u.test(value) ? Math.min(Math.max(Number(value), 1), max) : fallback;
export const createProductRouter = (dependencies: ProductHttpDependencies) => {
  const router = Router({ mergeParams: true });
  const principalFor = async (request: Request) => { const organizationId = (request.params as Record<string, string>).organizationId!; const principal = await dependencies.principals.principal(request, organizationId); return { organizationId, allowed: new AuthorityPolicy().decide(principal, { capability: "product.view", resource: { organizationId } }).allowed }; };
  router.get("/", async (request, response) => { try { const { organizationId, allowed } = await principalFor(request); if (!allowed) return deny(response, 403, "FORBIDDEN", "Product access is unavailable."); const q = typeof request.query.q === "string" ? request.query.q : ""; return response.status(200).json({ ok: true, data: await dependencies.workspace.list(organizationId, { query: q, page: positive(request.query.page, 1, 100000), pageSize: positive(request.query.pageSize, 50, 100) }) }); } catch { return deny(response, 403, "FORBIDDEN", "Authenticated access is required."); } });
  router.post("/:productId/drafts", async (request, response) => { try { const organizationId = (request.params as Record<string,string>).organizationId; const principal = await dependencies.principals.principal(request, organizationId); if (!new AuthorityPolicy().decide(principal,{capability:"product.edit",resource:{organizationId}}).allowed) return deny(response,403,"FORBIDDEN","Product Draft access is unavailable."); if (!validProductId(request.params.productId)) return deny(response, 404, "NOT_FOUND", "Product is unavailable in this organization."); const body = request.body as Record<string,unknown>; const businessRequestId = typeof body?.businessRequestId === "string" ? body.businessRequestId.trim() : ""; const expectedActiveVersionUpdatedAt = typeof body?.expectedActiveVersionUpdatedAt === "string" ? body.expectedActiveVersionUpdatedAt : ""; if (!businessRequestId || !expectedActiveVersionUpdatedAt) return response.status(400).json({ ok:false,error:{code:"VALIDATION_ERROR",message:"A business request and current Active version state are required."} }); const result = await dependencies.lifecycle.createDraft({ principal, organizationId, operationId: businessRequestId, businessRequest:{id:businessRequestId,payloadFingerprint:businessRequestId} }, { productId: request.params.productId, businessRequestId, expectedActiveVersionUpdatedAt }); return result.ok ? response.status(200).json({ok:true,data:result.value}) : response.status(result.error.code === "FORBIDDEN" ? 403 : result.error.code === "NOT_FOUND" ? 404 : result.error.code === "VALIDATION_ERROR" ? 400 : 409).json({ok:false,error:{code:result.error.code,message:result.error.publicMessage}}); } catch { return deny(response, 403, "FORBIDDEN", "Authenticated access is required."); } });
  router.get("/:productId/draft/general", async (request, response) => { try { const { organizationId, allowed } = await principalFor(request); if (!allowed) return deny(response,403,"FORBIDDEN","Product access is unavailable."); if (!validProductId(request.params.productId)) return deny(response,404,"NOT_FOUND","Product is unavailable in this organization."); const draft = await dependencies.draftGeneral.read(organizationId,request.params.productId); return draft ? response.status(200).json({ok:true,data:draft}) : deny(response,404,"NOT_FOUND","A Product Draft is unavailable."); } catch { return deny(response,403,"FORBIDDEN","Authenticated access is required."); } });
  router.patch("/:productId/draft/general", async (request, response) => { try { const organizationId=(request.params as Record<string,string>).organizationId; const principal=await dependencies.principals.principal(request,organizationId); if(!new AuthorityPolicy().decide(principal,{capability:"product.edit",resource:{organizationId}}).allowed)return deny(response,403,"FORBIDDEN","Product Draft editing is unavailable."); if(!validProductId(request.params.productId))return deny(response,404,"NOT_FOUND","Product is unavailable in this organization."); const body=request.body as Record<string,unknown>; const businessRequestId=typeof body?.businessRequestId==="string"?body.businessRequestId.trim():""; const draftVersionId=typeof body?.draftVersionId==="string"?body.draftVersionId.trim():""; const expectedDraftUpdatedAt=typeof body?.expectedDraftUpdatedAt==="string"?body.expectedDraftUpdatedAt:""; const general=body?.general as ProductDraftGeneral; if(!businessRequestId||!draftVersionId||!expectedDraftUpdatedAt||!general||typeof general!=="object")return response.status(400).json({ok:false,error:{code:"VALIDATION_ERROR",message:"A Draft, its current revision, and General settings are required."}}); const result=await dependencies.lifecycle.updateDraftGeneral({principal,organizationId,operationId:businessRequestId,businessRequest:{id:businessRequestId,payloadFingerprint:businessRequestId}},{productId:request.params.productId,businessRequestId,draftVersionId,expectedDraftUpdatedAt,general}); return result.ok?response.status(200).json({ok:true,data:result.value}):response.status(result.error.code==="FORBIDDEN"?403:result.error.code==="NOT_FOUND"?404:result.error.code==="VALIDATION_ERROR"?400:409).json({ok:false,error:{code:result.error.code,message:result.error.publicMessage}}); } catch { return deny(response,403,"FORBIDDEN","Authenticated access is required."); } });
  router.get("/:productId", async (request, response) => { try { const { organizationId, allowed } = await principalFor(request); if (!allowed) return deny(response, 403, "FORBIDDEN", "Product access is unavailable."); if (!validProductId(request.params.productId)) return deny(response, 404, "NOT_FOUND", "Product is unavailable in this organization."); const product = await dependencies.workspace.get(organizationId, brandedId<"ProductId">(request.params.productId)); return product ? response.status(200).json({ ok: true, data: product }) : deny(response, 404, "NOT_FOUND", "Product is unavailable in this organization."); } catch { return deny(response, 403, "FORBIDDEN", "Authenticated access is required."); } });
  return router;
};
