import type { Request, Response, Router } from "express";
import { Router as expressRouter } from "express";
import type { OperationContext } from "../../application/operation.js";
import type { Principal } from "../../authorization/principals.js";
import { type ApplicationResult, V2ApplicationError } from "../../errors/applicationError.js";
import type { ProductionMutationResult } from "../../modules/production/productionApplication.js";
import type { ProductionAttemptId, ProductionWorkId } from "../../modules/shared/commercialValues.js";
export interface ProductionHttpService { listStationQueue(context:OperationContext,station:"flatbed"|"roll",limit?:number):Promise<ApplicationResult<unknown>>;getWork(context:OperationContext,id:ProductionWorkId):Promise<ApplicationResult<unknown>>;open(context:OperationContext,input:Readonly<Record<string,unknown>>):Promise<ApplicationResult<ProductionMutationResult>>;start(context:OperationContext,input:Readonly<Record<string,unknown>>):Promise<ApplicationResult<ProductionMutationResult>>;recordOutput(context:OperationContext,input:Readonly<Record<string,unknown>>):Promise<ApplicationResult<ProductionMutationResult>>;complete(context:OperationContext,input:Readonly<Record<string,unknown>>):Promise<ApplicationResult<ProductionMutationResult>>; }
export interface VerifiedV2ProductionPrincipalProvider {principal(request:Request,organizationId:string):Promise<Principal>}
export type ProductionHttpDependencies=Readonly<{service:ProductionHttpService;principals:VerifiedV2ProductionPrincipalProvider}>;
const status=(code:string)=>code==="VALIDATION_ERROR"?400:code==="FORBIDDEN"?403:code==="NOT_FOUND"||code==="WRONG_TENANT"?404:code==="CONFLICT"||code==="STALE_STATE"||code==="IDEMPOTENCY_CONFLICT"?409:500;
const body=(v:unknown)=>{if(!v||typeof v!=="object"||Array.isArray(v))throw new V2ApplicationError("VALIDATION_ERROR","A Production command object is required.");return v as Readonly<Record<string,unknown>>;};
const context=async(r:Request,d:ProductionHttpDependencies,mutation=false):Promise<OperationContext>=>{const organizationId=r.params.organizationId;if(!organizationId)throw new V2ApplicationError("VALIDATION_ERROR","organizationId is required.");const command=mutation?body(r.body):undefined;const id=command?.businessRequestId;if(mutation&&(typeof id!=="string"||!id.trim()))throw new V2ApplicationError("VALIDATION_ERROR","businessRequestId is required.");return {principal:await d.principals.principal(r,organizationId),organizationId,operationId:`http:${r.method}:${r.path}`,...(mutation?{businessRequest:{id:id as string,payloadFingerprint:"route-fingerprint-is-derived-by-operation"}}:{})};};
const send=(r:Response,result:ApplicationResult<unknown>)=>result.ok?r.status(200).json({ok:true,data:result.value}):r.status(status(result.error.code)).json({ok:false,error:{code:result.error.code,message:result.error.publicMessage}});
const run=async(r:Response,op:()=>Promise<ApplicationResult<unknown>>)=>{try{send(r,await op());}catch(cause){const e=cause instanceof V2ApplicationError?cause:new V2ApplicationError("INTERNAL_ERROR","Production operation is unavailable.");r.status(status(e.code)).json({ok:false,error:{code:e.code,message:e.publicMessage}});}};
export const createProductionRouter=(d:ProductionHttpDependencies):Router=>{const router=expressRouter({mergeParams:true});router.get("/stations/:station/queue",(q,r)=>void run(r,async()=>{const station=q.params.station;if(station!=="flatbed"&&station!=="roll")throw new V2ApplicationError("VALIDATION_ERROR","Production station is invalid.");return d.service.listStationQueue(await context(q,d),station,Number(q.query.limit??50));}));router.get("/works/:productionWorkId",(q,r)=>void run(r,async()=>d.service.getWork(await context(q,d),q.params.productionWorkId as ProductionWorkId)));router.post("/works",(q,r)=>void run(r,async()=>d.service.open(await context(q,d,true),body(q.body))));router.post("/works/:productionWorkId/attempts",(q,r)=>void run(r,async()=>d.service.start(await context(q,d,true),{...body(q.body),productionWorkId:q.params.productionWorkId as ProductionWorkId})));router.post("/attempts/:productionAttemptId/output",(q,r)=>void run(r,async()=>d.service.recordOutput(await context(q,d,true),{...body(q.body),productionAttemptId:q.params.productionAttemptId as ProductionAttemptId})));router.post("/attempts/:productionAttemptId/complete",(q,r)=>void run(r,async()=>d.service.complete(await context(q,d,true),{...body(q.body),productionAttemptId:q.params.productionAttemptId as ProductionAttemptId})));return router;};
