import { Router } from "express";
import type { Request, Response } from "express";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import { staffActorId, type Principal } from "../../authorization/principals.js";
import { V2ApplicationError } from "../../errors/applicationError.js";
import type { VerifiedV2PrincipalProvider } from "./quoteRoutes.js";
import type { QuickBooksIntegrationReadinessService } from "../../../infrastructure/accounting/quickBooksIntegrationReadiness.js";
import type { PostgresQuickBooksSyncNow, QuickBooksSyncSubject } from "../../../infrastructure/accounting/quickBooksBillingQueue.js";

export type QuickBooksIntegrationHttpDependencies=Readonly<{integrations:QuickBooksIntegrationReadinessService;quickBooksSync:PostgresQuickBooksSyncNow;principals:VerifiedV2PrincipalProvider;publicWebOrigin?:string}>;
const fail=(response:Response,cause:unknown)=>{const error=cause instanceof V2ApplicationError?cause:new V2ApplicationError("CONFLICT",cause instanceof Error?cause.message:"QuickBooks integration is unavailable.");response.status(error.code==="FORBIDDEN"?403:error.code==="VALIDATION_ERROR"?400:409).json({ok:false,error:{code:error.code,message:error.publicMessage}});};
const operator=async(request:Request,deps:QuickBooksIntegrationHttpDependencies):Promise<{organizationId:string;principal:Principal}>=>{const organizationId=request.params.organizationId;if(!organizationId)throw new V2ApplicationError("VALIDATION_ERROR","organizationId is required.");const principal=await deps.principals.principal(request,organizationId);if(!new AuthorityPolicy().decide(principal,{capability:"organization.configure",resource:{organizationId}}).allowed)throw new V2ApplicationError("FORBIDDEN","You do not have permission to configure Accounting.");return {organizationId,principal};};
const previewScope=(value:unknown)=>value==="historical"||value==="all_unsynced"?value:"open_ar";
const positiveInt=(value:unknown,fallback:number)=>typeof value==="string"&&Number.isInteger(Number(value))&&Number(value)>0?Number(value):fallback;
const subject=(value:unknown):QuickBooksSyncSubject|null=>value==="invoice"||value==="payment"||value==="refund"?value:null;

/** Accounting Settings is the only V2 HTTP surface for routine QuickBooks operations. */
export const createQuickBooksIntegrationRouter=(deps:QuickBooksIntegrationHttpDependencies)=>{
  const router=Router({mergeParams:true});
  router.get("/",async(req,res)=>{try{const {organizationId}=await operator(req,deps);res.json({ok:true,data:await deps.integrations.readiness(organizationId)});}catch(error){fail(res,error);}});
  router.post("/connect",async(req,res)=>{try{const {organizationId}=await operator(req,deps);res.json({ok:true,data:await deps.integrations.beginConnect(organizationId)});}catch(error){fail(res,error);}});
  router.post("/disconnect",async(req,res)=>{try{const {organizationId}=await operator(req,deps);res.json({ok:true,data:await deps.integrations.disconnect(organizationId)});}catch(error){fail(res,error);}});
  router.get("/operations",async(req,res)=>{try{const {organizationId}=await operator(req,deps);res.json({ok:true,data:await deps.quickBooksSync.operations(organizationId)});}catch(error){fail(res,error);}});
  router.post("/sync-selected",async(req,res)=>{try{const {organizationId}=await operator(req,deps);const supplied:unknown[]=Array.isArray(req.body?.invoiceIds)?req.body.invoiceIds:[];const ids:string[]=[...new Set(supplied.map((value):string=>typeof value==="string"?value.trim():"").filter((value:string)=>value.length>0))];const invoiceIds=await deps.quickBooksSync.enqueueInvoices(organizationId,ids);res.status(202).json({ok:true,data:{invoiceIds,state:"queued"}});}catch(error){fail(res,error);}});
  router.post("/queue/:subjectKind/:subjectId/retry",async(req,res)=>{try{const {organizationId}=await operator(req,deps);const kind=subject(req.params.subjectKind);if(!kind)throw new V2ApplicationError("VALIDATION_ERROR","QuickBooks subject type is invalid.");const result=await deps.quickBooksSync.retry(organizationId,kind,req.params.subjectId);res.status(202).json({ok:true,data:{subjectKind:kind,subjectId:req.params.subjectId,...result}});}catch(error){fail(res,error);}});
  router.get("/import-preview/customers",async(req,res)=>{try{const {organizationId}=await operator(req,deps);res.json({ok:true,data:await deps.quickBooksSync.customerImportPreview(organizationId)});}catch(error){fail(res,error);}});
  router.get("/import-preview/invoices",async(req,res)=>{try{const {organizationId}=await operator(req,deps);const pageSize=Math.min(100,positiveInt(req.query.pageSize,25));res.json({ok:true,data:await deps.quickBooksSync.importPreview(organizationId,previewScope(req.query.scope),positiveInt(req.query.page,1),pageSize)});}catch(error){fail(res,error);}});
  router.post("/import/invoices",async(req,res)=>{try{const {organizationId,principal}=await operator(req,deps);const userId=staffActorId(principal);if(!userId)throw new V2ApplicationError("FORBIDDEN","A staff Accounting operator is required for QuickBooks imports.");const raw:unknown[]=Array.isArray(req.body?.invoices)?req.body.invoices:[];const invoices=raw.map((row:unknown)=>({qbId:typeof (row as {qbId?:unknown})?.qbId==="string"?(row as {qbId:string}).qbId:"",classification:(row as {classification?:unknown})?.classification})).filter((row):row is {qbId:string;classification:"open_ar"|"historical"|"skip"}=>row.classification==="open_ar"||row.classification==="historical"||row.classification==="skip");res.json({ok:true,data:await deps.quickBooksSync.importInvoices(organizationId,userId,invoices)});}catch(error){fail(res,error);}});
  return router;
};
const returnToSettings=(deps:QuickBooksIntegrationHttpDependencies,response:Response,result:"connected"|"error")=>{const origin=deps.publicWebOrigin?.replace(/\/$/u,"");if(!origin)return response.status(400).send("QuickBooks connection could not return to Settings.");return response.redirect(302,`${origin}/settings?section=accounting&quickbooks=${result}`);};
/** Intuit redirects to this fixed endpoint. The HMAC-bound, expiring OAuth
 * state is the tenant binding; callback parameters are never accepted as
 * tenant authority. */
export const createQuickBooksIntegrationCallback=(deps:QuickBooksIntegrationHttpDependencies)=>(async(request:Request,response:Response)=>{const code=typeof request.query.code==="string"?request.query.code:"";const realmId=typeof request.query.realmId==="string"?request.query.realmId:"";const state=typeof request.query.state==="string"?request.query.state:"";if(typeof request.query.error==="string")return returnToSettings(deps,response,"error");try{const proto=String(request.headers["x-forwarded-proto"]??request.protocol).split(",")[0]!.trim();const host=String(request.headers["x-forwarded-host"]??request.get("host")).split(",")[0]!.trim();await deps.integrations.finishConnect({state,code,realmId,callbackUrl:`${proto}://${host}${request.originalUrl}`});return returnToSettings(deps,response,"connected");}catch{return returnToSettings(deps,response,"error");}});
