import type { Request, Response, Router } from "express";
import { Router as expressRouter } from "express";
import { V2ApplicationError } from "../../errors/applicationError.js";
import type { FulfillmentHttpDependencies } from "./fulfillmentRoutes.js";

const object=(value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new V2ApplicationError("VALIDATION_ERROR","A shipment command object is required.");return value as Record<string,unknown>;};
const code=(error:V2ApplicationError)=>error.code==="VALIDATION_ERROR"?400:error.code==="FORBIDDEN"?403:error.code==="NOT_FOUND"?404:error.code==="CONFLICT"?409:500;
const context=async(request:Request,deps:FulfillmentHttpDependencies)=>{const body=object(request.body),organizationId=request.params.organizationId,requestId=body.businessRequestId;if(!organizationId||typeof requestId!=="string"||!requestId.trim())throw new V2ApplicationError("VALIDATION_ERROR","businessRequestId is required.");return {organizationId,operationId:`http:${request.method}:${request.path}`,businessRequest:{id:requestId,payloadFingerprint:"route-fingerprint-is-derived-by-operation"},principal:await deps.principals.principal(request,organizationId)} as const;};
const readContext=async(request:Request,deps:FulfillmentHttpDependencies)=>{const organizationId=request.params.organizationId;if(!organizationId)throw new V2ApplicationError("VALIDATION_ERROR","organizationId is required.");return {organizationId,operationId:`http:${request.method}:${request.path}`,principal:await deps.principals.principal(request,organizationId)} as const;};
const allocations=(value:unknown)=>{if(!Array.isArray(value)||!value.length)throw new V2ApplicationError("VALIDATION_ERROR","allocations must contain one or more OrderLine quantities.");return value.map(item=>{const allocation=object(item),quantity=allocation.quantity;if(typeof allocation.orderId!=="string"||typeof allocation.orderLineId!=="string"||typeof quantity!=="number"||!Number.isSafeInteger(quantity)||quantity<=0)throw new V2ApplicationError("VALIDATION_ERROR","Each allocation requires orderId, orderLineId, and a positive whole quantity.");return {orderId:allocation.orderId,orderLineId:allocation.orderLineId,quantity};});};
const send=async(response:Response,operation:()=>Promise<any>)=>{try{const result=await operation();if(result.ok)response.status(200).json({ok:true,data:result.value});else response.status(code(result.error)).json({ok:false,error:{code:result.error.code,message:result.error.publicMessage}});}catch(cause){const error=cause instanceof V2ApplicationError?cause:new V2ApplicationError("INTERNAL_ERROR","Shipment operation is unavailable.");response.status(code(error)).json({ok:false,error:{code:error.code,message:error.publicMessage}});}};
/** Mounted under the existing authenticated /fulfillment prefix. */
export const createShipmentContainerRouter=(deps:FulfillmentHttpDependencies):Router=>{const router=expressRouter({mergeParams:true});
  // Legacy routes remain mounted for compatibility; new work must use the
  // append-only prepared recovery endpoints below.
  // These former browser-orchestrated commands could create an empty
  // container, mark it shipped, then attach handoffs later.  They are kept as
  // explicit fail-closed compatibility responses; new work must use prepare
  // followed by the single atomic finalization command below.
  router.post("/shipments",(_request,response)=>void send(response,async()=>{throw new V2ApplicationError("VALIDATION_ERROR","Create a prepared shipment with allocations instead.");}));
  router.post("/shipments/:shipmentId/ship",(_request,response)=>void send(response,async()=>{throw new V2ApplicationError("VALIDATION_ERROR","Use atomic shipment finalization with the active prepared revision.");}));
  router.post("/shipments/:shipmentId/handoffs",(_request,response)=>void send(response,async()=>{throw new V2ApplicationError("VALIDATION_ERROR","Shipment handoffs are created only by atomic shipment finalization.");}));
  router.get("/shipments",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const limit=typeof request.query.limit==="string"?Number(request.query.limit):undefined,status=typeof request.query.status==="string"?request.query.status:undefined;if(limit!==undefined&&(!Number.isSafeInteger(limit)||limit<1||limit>100))throw new V2ApplicationError("VALIDATION_ERROR","limit must be a whole number from 1 through 100.");if(status!==undefined&&status!=="prepared"&&status!=="shipped"&&status!=="voided")throw new V2ApplicationError("VALIDATION_ERROR","status must be prepared, shipped, or voided.");return deps.shipments.list(await readContext(request,deps),{...(status?{status}:{}),...(limit?{limit}:{})});}));
  router.get("/shipments/:shipmentId",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");return deps.shipments.get(await readContext(request,deps),request.params.shipmentId);}));
  router.post("/shipments/prepared",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body),carrier=body.carrier===undefined?{}:object(body.carrier);return deps.shipments.createPrepared(await context(request,deps),{customerId:typeof body.customerId==="string"?body.customerId:undefined,destination:body.destination,carrier,allocations:allocations(body.allocations)});}));
  router.post("/shipments/:shipmentId/correct",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body),carrier=body.carrier===undefined?{}:object(body.carrier);if(typeof body.reason!=="string")throw new V2ApplicationError("VALIDATION_ERROR","reason is required.");return deps.shipments.correctPrepared(await context(request,deps),{shipmentId:request.params.shipmentId,carrier,allocations:allocations(body.allocations),reason:body.reason});}));
  router.post("/shipments/:shipmentId/cancel",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body);if(typeof body.reason!=="string")throw new V2ApplicationError("VALIDATION_ERROR","reason is required.");return deps.shipments.voidPrepared(await context(request,deps),{shipmentId:request.params.shipmentId,reason:body.reason});}));
  router.post("/shipments/:shipmentId/finalize",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body);if(typeof body.expectedPreparedRevisionId!=="string"||!body.expectedPreparedRevisionId.trim())throw new V2ApplicationError("VALIDATION_ERROR","expectedPreparedRevisionId is required.");return deps.shipments.finalize(await context(request,deps),{shipmentId:request.params.shipmentId,expectedPreparedRevisionId:body.expectedPreparedRevisionId});}));
  return router;
};
