import type { Request, Response, Router } from "express";
import { Router as expressRouter } from "express";
import { V2ApplicationError } from "../../errors/applicationError.js";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import type { FulfillmentHttpDependencies } from "./fulfillmentRoutes.js";

const object=(value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new V2ApplicationError("VALIDATION_ERROR","A shipment command object is required.");return value as Record<string,unknown>;};
const code=(error:V2ApplicationError)=>error.code==="VALIDATION_ERROR"?400:error.code==="FORBIDDEN"?403:error.code==="NOT_FOUND"?404:error.code==="CONFLICT"?409:500;
const context=async(request:Request,deps:FulfillmentHttpDependencies)=>{const body=object(request.body),organizationId=request.params.organizationId,requestId=body.businessRequestId;if(!organizationId||typeof requestId!=="string"||!requestId.trim())throw new V2ApplicationError("VALIDATION_ERROR","businessRequestId is required.");return {organizationId,operationId:`http:${request.method}:${request.path}`,businessRequest:{id:requestId,payloadFingerprint:"route-fingerprint-is-derived-by-operation"},principal:await deps.principals.principal(request,organizationId)} as const;};
const readContext=async(request:Request,deps:FulfillmentHttpDependencies)=>{const organizationId=request.params.organizationId;if(!organizationId)throw new V2ApplicationError("VALIDATION_ERROR","organizationId is required.");return {organizationId,operationId:`http:${request.method}:${request.path}`,principal:await deps.principals.principal(request,organizationId)} as const;};
const allocations=(value:unknown)=>{if(!Array.isArray(value)||!value.length)throw new V2ApplicationError("VALIDATION_ERROR","allocations must contain one or more OrderLine quantities.");return value.map(item=>{const allocation=object(item),quantity=allocation.quantity;if(typeof allocation.orderId!=="string"||typeof allocation.orderLineId!=="string"||typeof quantity!=="number"||!Number.isSafeInteger(quantity)||quantity<=0)throw new V2ApplicationError("VALIDATION_ERROR","Each allocation requires orderId, orderLineId, and a positive whole quantity.");return {orderId:allocation.orderId,orderLineId:allocation.orderLineId,quantity,...(typeof allocation.replacementObligationId==="string"?{replacementObligationId:allocation.replacementObligationId}:{})};});};
const policy=(value:unknown)=>{const body=object(value),mode=body.mode;if(mode!=="pass_through"&&mode!=="flat"&&mode!=="percent"&&mode!=="no_charge"&&mode!=="manual")throw new V2ApplicationError("VALIDATION_ERROR","A valid shipping pricing mode is required.");if(typeof body.currency!=="string")throw new V2ApplicationError("VALIDATION_ERROR","Shipping policy currency is required.");const optional=(key:"flatAmountCents"|"percentageBasisPoints")=>body[key]===undefined?undefined:typeof body[key]==="number"&&Number.isSafeInteger(body[key])?body[key] as number:undefined;if(body.flatAmountCents!==undefined&&optional("flatAmountCents")===undefined)throw new V2ApplicationError("VALIDATION_ERROR","Flat shipping markup must be whole cents.");if(body.percentageBasisPoints!==undefined&&optional("percentageBasisPoints")===undefined)throw new V2ApplicationError("VALIDATION_ERROR","Shipping percentage must be whole basis points.");return {mode,currency:body.currency, ...(optional("flatAmountCents")===undefined?{}:{flatAmountCents:optional("flatAmountCents")}), ...(optional("percentageBasisPoints")===undefined?{}:{percentageBasisPoints:optional("percentageBasisPoints")})} as const;};
const shippingAllocations=(value:unknown)=>{if(!Array.isArray(value)||!value.length)throw new V2ApplicationError("VALIDATION_ERROR","allocations must contain every participating Order.");return value.map(item=>{const row=object(item);if(typeof row.orderId!=="string"||typeof row.customerShippingPriceCents!=="number"||!Number.isSafeInteger(row.customerShippingPriceCents)||row.customerShippingPriceCents<0)throw new V2ApplicationError("VALIDATION_ERROR","Each allocation requires orderId and non-negative whole customerShippingPriceCents.");return {orderId:row.orderId,customerShippingPriceCents:row.customerShippingPriceCents};});};
const send=async(response:Response,operation:()=>Promise<any>)=>{try{const result=await operation();if(result.ok)response.status(200).json({ok:true,data:result.value});else response.status(code(result.error)).json({ok:false,error:{code:result.error.code,message:result.error.publicMessage}});}catch(cause){const error=cause instanceof V2ApplicationError?cause:new V2ApplicationError("INTERNAL_ERROR","Shipment operation is unavailable.");response.status(code(error)).json({ok:false,error:{code:error.code,message:error.publicMessage}});}};
/** Mounted under the existing authenticated /fulfillment prefix. */
export const createShipmentContainerRouter=(deps:FulfillmentHttpDependencies):Router=>{const router=expressRouter({mergeParams:true});
  // Legacy routes remain mounted for compatibility; new work must use the
  // append-only prepared recovery endpoints below.
  // These former browser-orchestrated commands could create an empty
  // container, mark it shipped, then attach handoffs later.  They are kept as
  // explicit fail-closed compatibility responses; new work must use prepare
  // followed by the single atomic finalization command below.
  router.post("/shipments",(_request,response)=>void send(response,async()=>{throw new V2ApplicationError("VALIDATION_ERROR","Create a prepared shipment with allocations instead.");}));
  router.post("/shipments/:shipmentId/ship",(_request,response)=>void send(response,async()=>{throw new V2ApplicationError("VALIDATION_ERROR","Use atomic shipment finalization with the active prepared revision.");}));
  router.post("/shipments/:shipmentId/handoffs",(_request,response)=>void send(response,async()=>{throw new V2ApplicationError("VALIDATION_ERROR","Shipment handoffs are created only by atomic shipment finalization.");}));
  router.get("/shipments",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const limit=typeof request.query.limit==="string"?Number(request.query.limit):undefined,status=typeof request.query.status==="string"?request.query.status:undefined;if(limit!==undefined&&(!Number.isSafeInteger(limit)||limit<1||limit>100))throw new V2ApplicationError("VALIDATION_ERROR","limit must be a whole number from 1 through 100.");if(status!==undefined&&status!=="prepared"&&status!=="shipped"&&status!=="voided")throw new V2ApplicationError("VALIDATION_ERROR","status must be prepared, shipped, or voided.");return deps.shipments.list(await readContext(request,deps),{...(status?{status}:{}),...(limit?{limit}:{})});}));
  router.get("/shipments/:shipmentId",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");return deps.shipments.get(await readContext(request,deps),request.params.shipmentId);}));
  // This is intentionally a separate staff-only DTO. Existing shipment,
  // portal, packing-slip, and customer routes never receive carrier cost or margin.
  router.get("/shipments/:shipmentId/internal-economics",(request,response)=>void send(response,async()=>{if(!deps.shipmentEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipment economics runtime is unavailable.");const op=await readContext(request,deps);if(op.principal.kind!=="staff"||!new AuthorityPolicy().decide(op.principal,{capability:"fulfillment.shipping.cost",resource:{organizationId:op.organizationId}}).allowed)throw new V2ApplicationError("FORBIDDEN","Internal shipment economics are staff-only.");const detail=await deps.shipmentEconomics.readStaffEconomics(op.organizationId as any,request.params.shipmentId);if(!detail)throw new V2ApplicationError("NOT_FOUND","Shipment was not found.");return {ok:true,value:detail};}));
  router.get("/shipping-pricing-policy",(request,response)=>void send(response,async()=>{if(!deps.shippingEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipping policy runtime is unavailable.");return {ok:true,value:await deps.shippingEconomics.readPolicy(await readContext(request,deps))};}));
  router.put("/shipping-pricing-policy",(request,response)=>void send(response,async()=>{if(!deps.shippingEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipping policy runtime is unavailable.");return {ok:true,value:await deps.shippingEconomics.saveOrganizationPolicy(await context(request,deps),policy(request.body))};}));
  router.get("/customers/:customerId/shipping-pricing-policy",(request,response)=>void send(response,async()=>{if(!deps.shippingEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipping policy runtime is unavailable.");return {ok:true,value:await deps.shippingEconomics.readPolicy(await readContext(request,deps),request.params.customerId as any)};}));
  router.put("/customers/:customerId/shipping-pricing-policy",(request,response)=>void send(response,async()=>{if(!deps.shippingEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipping policy runtime is unavailable.");return {ok:true,value:await deps.shippingEconomics.saveCustomerPolicy(await context(request,deps),request.params.customerId as any,policy(request.body))};}));
  router.delete("/customers/:customerId/shipping-pricing-policy",(request,response)=>void send(response,async()=>{if(!deps.shippingEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipping policy runtime is unavailable.");return {ok:true,value:await deps.shippingEconomics.saveCustomerPolicy(await context(request,deps),request.params.customerId as any)};}));
  router.post("/shipments/:shipmentId/economics/estimated-cost",(request,response)=>void send(response,async()=>{if(!deps.shippingEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipping economics runtime is unavailable.");const body=object(request.body);if(typeof body.estimatedCarrierCostCents!=="number")throw new V2ApplicationError("VALIDATION_ERROR","estimatedCarrierCostCents is required.");const value=await deps.shippingEconomics.setEstimatedCost(await context(request,deps),{shipmentId:request.params.shipmentId,estimatedCarrierCostCents:body.estimatedCarrierCostCents});if(!value)throw new V2ApplicationError("NOT_FOUND","Shipment was not found.");return {ok:true,value};}));
  router.post("/shipments/:shipmentId/economics/actual-cost",(request,response)=>void send(response,async()=>{if(!deps.shippingEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipping economics runtime is unavailable.");const body=object(request.body);if(typeof body.actualCarrierCostCents!=="number"||typeof body.reason!=="string"||!["titan","customer","carrier","pending"].includes(String(body.responsibility)))throw new V2ApplicationError("VALIDATION_ERROR","actualCarrierCostCents, responsibility, and reason are required.");const value=await deps.shippingEconomics.setActualCost(await context(request,deps),{shipmentId:request.params.shipmentId,actualCarrierCostCents:body.actualCarrierCostCents,responsibility:body.responsibility as any,reason:body.reason,...(typeof body.note==="string"?{note:body.note}:{})});if(!value)throw new V2ApplicationError("NOT_FOUND","Shipment was not found.");return {ok:true,value};}));
  router.post("/shipments/:shipmentId/economics/customer-price",(request,response)=>void send(response,async()=>{if(!deps.shippingEconomics)throw new V2ApplicationError("INTERNAL_ERROR","Shipping economics runtime is unavailable.");const body=object(request.body);if(body.manualCustomerPriceCents!==undefined&&(typeof body.manualCustomerPriceCents!=="number"||!Number.isSafeInteger(body.manualCustomerPriceCents)))throw new V2ApplicationError("VALIDATION_ERROR","manualCustomerPriceCents must be whole cents.");return {ok:true,value:await deps.shippingEconomics.establishCustomerPrice(await context(request,deps),{shipmentId:request.params.shipmentId,...(body.manualCustomerPriceCents===undefined?{}:{manualCustomerPriceCents:body.manualCustomerPriceCents})})};}));
  router.get("/shipments/:shipmentId/shipping-allocations",(request,response)=>void send(response,async()=>{if(!deps.shippingAllocations)throw new V2ApplicationError("INTERNAL_ERROR","Shipping allocation runtime is unavailable.");return {ok:true,value:await deps.shippingAllocations.read(await readContext(request,deps),request.params.shipmentId)};}));
  router.post("/shipments/:shipmentId/shipping-allocations/equal",(request,response)=>void send(response,async()=>{if(!deps.shippingAllocations)throw new V2ApplicationError("INTERNAL_ERROR","Shipping allocation runtime is unavailable.");return {ok:true,value:await deps.shippingAllocations.establishEqual(await context(request,deps),request.params.shipmentId)};}));
  router.put("/shipments/:shipmentId/shipping-allocations/manual",(request,response)=>void send(response,async()=>{if(!deps.shippingAllocations)throw new V2ApplicationError("INTERNAL_ERROR","Shipping allocation runtime is unavailable.");const body=object(request.body);return {ok:true,value:await deps.shippingAllocations.setManual(await context(request,deps),request.params.shipmentId,shippingAllocations(body.allocations))};}));
  router.post("/shipments/:shipmentId/shipping-allocations/project",(request,response)=>void send(response,async()=>{if(!deps.shippingAllocations)throw new V2ApplicationError("INTERNAL_ERROR","Shipping allocation runtime is unavailable.");return {ok:true,value:await deps.shippingAllocations.project(await context(request,deps),request.params.shipmentId)};}));
  router.post("/shipments/prepared",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body),carrier=body.carrier===undefined?{}:object(body.carrier);return deps.shipments.createPrepared(await context(request,deps),{customerId:typeof body.customerId==="string"?body.customerId:undefined,destination:body.destination,carrier,allocations:allocations(body.allocations)});}));
  router.post("/shipments/:shipmentId/correct",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body),carrier=body.carrier===undefined?{}:object(body.carrier);if(typeof body.reason!=="string")throw new V2ApplicationError("VALIDATION_ERROR","reason is required.");return deps.shipments.correctPrepared(await context(request,deps),{shipmentId:request.params.shipmentId,carrier,allocations:allocations(body.allocations),reason:body.reason});}));
  router.post("/shipments/:shipmentId/cancel",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body);if(typeof body.reason!=="string")throw new V2ApplicationError("VALIDATION_ERROR","reason is required.");return deps.shipments.voidPrepared(await context(request,deps),{shipmentId:request.params.shipmentId,reason:body.reason});}));
  router.post("/shipments/:shipmentId/finalize",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body);if(typeof body.expectedPreparedRevisionId!=="string"||!body.expectedPreparedRevisionId.trim())throw new V2ApplicationError("VALIDATION_ERROR","expectedPreparedRevisionId is required.");return deps.shipments.finalize(await context(request,deps),{shipmentId:request.params.shipmentId,expectedPreparedRevisionId:body.expectedPreparedRevisionId});}));
  return router;
};
