import type { Request, Response, Router } from "express";
import { Router as expressRouter } from "express";
import { V2ApplicationError } from "../../errors/applicationError.js";
import type { FulfillmentHttpDependencies } from "./fulfillmentRoutes.js";
import { brandedId } from "../../modules/shared/commercialValues.js";

const object=(value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new V2ApplicationError("VALIDATION_ERROR","A shipment command object is required.");return value as Record<string,unknown>;};
const code=(error:V2ApplicationError)=>error.code==="VALIDATION_ERROR"?400:error.code==="FORBIDDEN"?403:error.code==="NOT_FOUND"?404:error.code==="CONFLICT"?409:500;
const context=async(request:Request,deps:FulfillmentHttpDependencies)=>{const body=object(request.body),organizationId=request.params.organizationId,requestId=body.businessRequestId;if(!organizationId||typeof requestId!=="string"||!requestId.trim())throw new V2ApplicationError("VALIDATION_ERROR","businessRequestId is required.");return {organizationId,operationId:`http:${request.method}:${request.path}`,businessRequest:{id:requestId,payloadFingerprint:"route-fingerprint-is-derived-by-operation"},principal:await deps.principals.principal(request,organizationId)} as const;};
const send=async(response:Response,operation:()=>Promise<any>)=>{try{const result=await operation();if(result.ok)response.status(200).json({ok:true,data:result.value});else response.status(code(result.error)).json({ok:false,error:{code:result.error.code,message:result.error.publicMessage}});}catch(cause){const error=cause instanceof V2ApplicationError?cause:new V2ApplicationError("INTERNAL_ERROR","Shipment operation is unavailable.");response.status(code(error)).json({ok:false,error:{code:error.code,message:error.publicMessage}});}};
/** Mounted under the existing authenticated /fulfillment prefix. */
export const createShipmentContainerRouter=(deps:FulfillmentHttpDependencies):Router=>{const router=expressRouter({mergeParams:true});router.post("/shipments",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body),carrier=body.carrier===undefined?{}:object(body.carrier);return deps.shipments.create(await context(request,deps),{customerId:typeof body.customerId==="string"?body.customerId:undefined,destination:body.destination,carrier});}));router.post("/shipments/:shipmentId/ship",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body);return deps.shipments.ship(await context(request,deps),{shipmentId:request.params.shipmentId,carrier:body.carrier===undefined?{}:object(body.carrier)});}));router.post("/shipments/:shipmentId/handoffs",(request,response)=>void send(response,async()=>{if(!deps.shipments)throw new V2ApplicationError("INTERNAL_ERROR","Shipment runtime is unavailable.");const body=object(request.body);if(!Array.isArray(body.handoffIds)||!body.handoffIds.every(value=>typeof value==="string"))throw new V2ApplicationError("VALIDATION_ERROR","handoffIds must be an array.");return deps.shipments.attach(await context(request,deps),{shipmentId:request.params.shipmentId,handoffIds:body.handoffIds.map(value=>brandedId<"FulfillmentHandoffId">(value))});}));return router;};
