import { Router, type Request, type Response } from "express";
import { canManageTeamAccess, canReadTeamAccess } from "../../authorization/teamAccessAuthority.js";
import { V2ApplicationError } from "../../errors/applicationError.js";
import { optionalString, parseCapabilities, requiredString } from "../../modules/organization/teamAccess.js";
import type { PostgresTeamAccess } from "../../../infrastructure/organization/postgresTeamAccess.js";
import { shouldCaptureM77fQaPortalSetup } from "../../../infrastructure/communications/m77fQaProofDeliverySafety.js";
import type { VerifiedV2PrincipalProvider } from "./quoteRoutes.js";

export type TeamAccessHttpDependencies = Readonly<{ teamAccess: PostgresTeamAccess; principals: VerifiedV2PrincipalProvider; qaSetupAllowed?: (organizationId: string) => boolean }>;
const fail = (response: Response, cause: unknown) => { const error = cause instanceof V2ApplicationError ? cause : new V2ApplicationError("INTERNAL_ERROR", "Team & Access is unavailable."); const status = error.code === "FORBIDDEN" ? 403 : error.code === "NOT_FOUND" || error.code === "WRONG_TENANT" ? 404 : error.code === "STALE_STATE" || error.code === "CONFLICT" || error.code === "IDEMPOTENCY_CONFLICT" ? 409 : error.code === "VALIDATION_ERROR" ? 400 : 500; response.status(status).json({ ok: false, error: { code: error.code, message: error.publicMessage } }); };
const bodyOf = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const context = (body: Record<string, unknown>) => ({ businessRequestId: requiredString(body.businessRequestId, "businessRequestId"), expectedAuthorityRevision: requiredString(body.expectedAuthorityRevision, "expectedAuthorityRevision") });
const reader = async (request: Request, dependencies: TeamAccessHttpDependencies) => { const organizationId = requiredString(request.params.organizationId, "organizationId"); const principal = await dependencies.principals.principal(request, organizationId); if (!canReadTeamAccess(principal)) throw new V2ApplicationError("FORBIDDEN", "An active internal Staff membership is required to view Team & Access."); if (principal.organizationId !== organizationId) throw new V2ApplicationError("WRONG_TENANT", "Team access is organization scoped."); return { organizationId, principal }; };
const manager = async (request: Request, dependencies: TeamAccessHttpDependencies) => { const result = await reader(request, dependencies); if (!canManageTeamAccess(result.principal)) throw new V2ApplicationError("FORBIDDEN", "Only an organization Owner, Administrator, or Platform Developer can change Team & Access."); return result; };

export const createTeamAccessRouter = (dependencies: TeamAccessHttpDependencies) => {
  const router = Router({ mergeParams: true });
  router.get("/", async (request, response) => { try { const { organizationId, principal } = await reader(request, dependencies); response.json({ ok: true, data: await dependencies.teamAccess.read(organizationId, canManageTeamAccess(principal)) }); } catch (cause) { fail(response, cause); } });
  router.get("/staff", async (request, response) => { try { const { organizationId } = await reader(request, dependencies); const data = await dependencies.teamAccess.read(organizationId); response.json({ ok: true, data: { staff: data.staff, invitations: data.invitations, authorityRevision: data.authorityRevision } }); } catch (cause) { fail(response, cause); } });
  router.post("/staff/invitations", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); const role = body.legacyRole; if (role !== undefined && role !== "admin" && role !== "manager" && role !== "member") throw new V2ApplicationError("VALIDATION_ERROR", "legacyRole is invalid."); const data = await dependencies.teamAccess.createInvitation(principal, organizationId, { email: requiredString(body.email, "email"), legacyRole: role as "admin" | "manager" | "member" | undefined }, context(body)); response.status(201).json({ ok: true, data }); } catch (cause) { fail(response, cause); } });
  router.patch("/staff/:userId/status", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); if (typeof body.active !== "boolean") throw new V2ApplicationError("VALIDATION_ERROR", "active is required."); await dependencies.teamAccess.setMembershipActive(principal, organizationId, requiredString(request.params.userId, "userId"), body.active, context(body)); response.json({ ok: true, data: { userId: request.params.userId, status: body.active ? "active" : "disabled" } }); } catch (cause) { fail(response, cause); } });
  router.put("/staff/:userId/permission-sets", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); if (!Array.isArray(body.permissionSetIds) || body.permissionSetIds.some((id) => typeof id !== "string" || !id.trim())) throw new V2ApplicationError("VALIDATION_ERROR", "permissionSetIds is required."); await dependencies.teamAccess.replaceStaffAssignments(principal, organizationId, requiredString(request.params.userId, "userId"), body.permissionSetIds as string[], context(body)); response.json({ ok: true, data: { userId: request.params.userId } }); } catch (cause) { fail(response, cause); } });
  router.get("/portal-access", async (request, response) => { try { const { organizationId } = await reader(request, dependencies); const data = await dependencies.teamAccess.read(organizationId); response.json({ ok: true, data: { portalAccess: data.portalAccess, authorityRevision: data.authorityRevision } }); } catch (cause) { fail(response, cause); } });
  // QA-only setup capture is deliberately separate from normal bootstrap: its
  // token is returned once to the authenticated capability holder and the
  // provider boundary is never called.  The guard defaults to the exact
  // deployed-DEV/QA predicate; the optional dependency is test-only wiring.
  router.post("/portal-access/m77f-qa-setup", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); if (body.confirmM77fQaPortalSetup !== true) throw new V2ApplicationError("VALIDATION_ERROR", "confirmM77fQaPortalSetup: true is required."); if (!(dependencies.qaSetupAllowed ?? shouldCaptureM77fQaPortalSetup)(organizationId)) throw new V2ApplicationError("FORBIDDEN", "QA Portal setup capture is unavailable."); const data = await dependencies.teamAccess.bootstrapPortalAccess(principal, organizationId, { customerId: requiredString(body.customerId, "customerId"), contactId: requiredString(body.contactId, "contactId"), permissionSetId: requiredString(body.permissionSetId, "permissionSetId") }, context(body), { captureM77fQaSetupUrl: true }); response.status(201).json({ ok: true, data }); } catch (cause) { fail(response, cause); } });
  router.post("/portal-access/:portalAccessId/m77f-qa-reset", async (request,response)=>{try{const body=bodyOf(request.body);const {organizationId,principal}=await manager(request,dependencies);if(body.confirmM77fQaPortalReset!==true)throw new V2ApplicationError("VALIDATION_ERROR","confirmM77fQaPortalReset: true is required.");const data=await dependencies.teamAccess.captureM77fQaPortalReset(principal,organizationId,{portalAccessId:requiredString(request.params.portalAccessId,"portalAccessId"),customerId:requiredString(body.customerId,"customerId"),contactId:requiredString(body.contactId,"contactId")},context(body));response.setHeader("cache-control","no-store");response.status(201).json({ok:true,data});}catch(cause){fail(response,cause);}});
  router.post("/portal-access/bootstrap", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); const data = await dependencies.teamAccess.bootstrapPortalAccess(principal, organizationId, { customerId: requiredString(body.customerId, "customerId"), contactId: requiredString(body.contactId, "contactId"), permissionSetId: requiredString(body.permissionSetId, "permissionSetId") }, context(body)); response.status(201).json({ ok: true, data }); } catch (cause) { fail(response, cause); } });
  router.post("/portal-access/:portalAccessId/resend-setup", async (request, response) => { try { const body=bodyOf(request.body); const {organizationId,principal}=await manager(request,dependencies); const data=await dependencies.teamAccess.resendPortalSetup(principal,organizationId,requiredString(request.params.portalAccessId,"portalAccessId"),context(body)); response.json({ok:true,data}); } catch(cause) { fail(response,cause); } });
  router.patch("/portal-access/:portalAccessId/status", async (request,response) => { try { const body=bodyOf(request.body); const {organizationId,principal}=await manager(request,dependencies); if(body.status!=="suspended"&&body.status!=="disabled")throw new V2ApplicationError("VALIDATION_ERROR","status must be suspended or disabled."); await dependencies.teamAccess.setPortalAccessStatus(principal,organizationId,requiredString(request.params.portalAccessId,"portalAccessId"),body.status,context(body)); response.json({ok:true,data:{portalAccessId:request.params.portalAccessId,status:body.status}}); } catch(cause) { fail(response,cause); } });
  router.put("/portal-access/:portalAccessId/permission-sets", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); if (!Array.isArray(body.permissionSetIds) || body.permissionSetIds.some((id) => typeof id !== "string" || !id.trim())) throw new V2ApplicationError("VALIDATION_ERROR", "permissionSetIds is required."); await dependencies.teamAccess.replacePortalAssignments(principal, organizationId, requiredString(request.params.portalAccessId, "portalAccessId"), body.permissionSetIds as string[], context(body)); response.json({ ok: true, data: { portalAccessId: request.params.portalAccessId } }); } catch (cause) { fail(response, cause); } });
  router.get("/permission-sets", async (request, response) => { try { const { organizationId } = await reader(request, dependencies); const data = await dependencies.teamAccess.read(organizationId); response.json({ ok: true, data: { permissionSets: data.permissionSets, capabilityGroups: data.capabilityGroups, authorityRevision: data.authorityRevision } }); } catch (cause) { fail(response, cause); } });
  router.get("/permission-sets/:permissionSetId", async (request, response) => { try { const { organizationId } = await reader(request, dependencies); const data = await dependencies.teamAccess.read(organizationId); const permissionSet = (data.permissionSets as readonly { permissionSetId: string }[]).find((item) => item.permissionSetId === request.params.permissionSetId); if (!permissionSet) throw new V2ApplicationError("NOT_FOUND", "Permission set was not found."); response.json({ ok: true, data: { permissionSet, capabilityGroups: data.capabilityGroups, authorityRevision: data.authorityRevision } }); } catch (cause) { fail(response, cause); } });
  router.post("/permission-sets", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); const principalKind = body.principalKind === "portal" ? "portal" : body.principalKind === undefined || body.principalKind === "staff" ? "staff" : (() => { throw new V2ApplicationError("VALIDATION_ERROR", "principalKind is invalid."); })(); const data = await dependencies.teamAccess.createCustomSet(principal, organizationId, { name: requiredString(body.name, "name"), description: optionalString(body.description, "description"), principalKind, capabilities: parseCapabilities(body.capabilities) }, context(body)); response.status(201).json({ ok: true, data }); } catch (cause) { fail(response, cause); } });
  router.post("/permission-sets/:permissionSetId/clone", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); const data = await dependencies.teamAccess.cloneStaffSet(principal, organizationId, requiredString(request.params.permissionSetId, "permissionSetId"), { name: requiredString(body.name, "name"), description: optionalString(body.description, "description") }, context(body)); response.status(201).json({ ok: true, data }); } catch (cause) { fail(response, cause); } });
  router.put("/permission-sets/:permissionSetId", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await manager(request, dependencies); if (typeof body.active !== "boolean") throw new V2ApplicationError("VALIDATION_ERROR", "active is required."); await dependencies.teamAccess.updateCustomSet(principal, organizationId, requiredString(request.params.permissionSetId, "permissionSetId"), { name: requiredString(body.name, "name"), description: optionalString(body.description, "description"), active: body.active, capabilities: parseCapabilities(body.capabilities) }, context(body)); response.json({ ok: true, data: { permissionSetId: request.params.permissionSetId } }); } catch (cause) { fail(response, cause); } });
  router.get("/readiness", async (request, response) => { try { const { organizationId } = await reader(request, dependencies); const data = await dependencies.teamAccess.read(organizationId); response.json({ ok: true, data: data.readiness }); } catch (cause) { fail(response, cause); } });
  return router;
};
