import { Router, type Request, type Response } from "express";
import { AuthorityPolicy } from "../../authorization/authorityPolicy.js";
import type { StaffPrincipal } from "../../authorization/principals.js";
import { V2ApplicationError } from "../../errors/applicationError.js";
import { optionalString, parseCapabilities, requiredString } from "../../modules/organization/teamAccess.js";
import type { PostgresTeamAccess } from "../../../infrastructure/organization/postgresTeamAccess.js";
import type { VerifiedV2PrincipalProvider } from "./quoteRoutes.js";

export type TeamAccessHttpDependencies = Readonly<{ teamAccess: PostgresTeamAccess; principals: VerifiedV2PrincipalProvider }>;
const fail = (response: Response, cause: unknown) => { const error = cause instanceof V2ApplicationError ? cause : new V2ApplicationError("INTERNAL_ERROR", "Team & Access is unavailable."); const status = error.code === "FORBIDDEN" ? 403 : error.code === "NOT_FOUND" || error.code === "WRONG_TENANT" ? 404 : error.code === "STALE_STATE" || error.code === "CONFLICT" || error.code === "IDEMPOTENCY_CONFLICT" ? 409 : error.code === "VALIDATION_ERROR" ? 400 : 500; response.status(status).json({ ok: false, error: { code: error.code, message: error.publicMessage } }); };
const bodyOf = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const context = (body: Record<string, unknown>) => ({ businessRequestId: requiredString(body.businessRequestId, "businessRequestId"), expectedAuthorityRevision: requiredString(body.expectedAuthorityRevision, "expectedAuthorityRevision") });
const operator = async (request: Request, dependencies: TeamAccessHttpDependencies, capability: "permissions.view" | "permissions.manageSets" | "permissions.assignStaff" | "permissions.assignPortal") => { const organizationId = requiredString(request.params.organizationId, "organizationId"); const principal = await dependencies.principals.principal(request, organizationId); if (principal.kind !== "staff" || !new AuthorityPolicy().decide(principal, { capability, resource: { organizationId } }).allowed) throw new V2ApplicationError("FORBIDDEN", "You do not have permission to manage Team & Access."); return { organizationId, principal }; };

export const createTeamAccessRouter = (dependencies: TeamAccessHttpDependencies) => {
  const router = Router({ mergeParams: true });
  router.get("/", async (request, response) => { try { const { organizationId, principal } = await operator(request, dependencies, "permissions.view"); response.json({ ok: true, data: await dependencies.teamAccess.read(organizationId, principal.authority.source === "permission_set" && principal.authority.capabilities.includes("permissions.assignPortal")) }); } catch (cause) { fail(response, cause); } });
  router.get("/staff", async (request, response) => { try { const { organizationId } = await operator(request, dependencies, "permissions.view"); const data = await dependencies.teamAccess.read(organizationId); response.json({ ok: true, data: { staff: data.staff, invitations: data.invitations, authorityRevision: data.authorityRevision } }); } catch (cause) { fail(response, cause); } });
  router.post("/staff/invitations", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await operator(request, dependencies, "permissions.assignStaff"); const role = body.legacyRole; if (role !== undefined && role !== "admin" && role !== "manager" && role !== "member") throw new V2ApplicationError("VALIDATION_ERROR", "legacyRole is invalid."); const data = await dependencies.teamAccess.createInvitation(principal as StaffPrincipal, organizationId, { email: requiredString(body.email, "email"), legacyRole: role as "admin" | "manager" | "member" | undefined }, context(body)); response.status(201).json({ ok: true, data }); } catch (cause) { fail(response, cause); } });
  router.patch("/staff/:userId/status", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await operator(request, dependencies, "permissions.assignStaff"); if (typeof body.active !== "boolean") throw new V2ApplicationError("VALIDATION_ERROR", "active is required."); await dependencies.teamAccess.setMembershipActive(principal as StaffPrincipal, organizationId, requiredString(request.params.userId, "userId"), body.active, context(body)); response.json({ ok: true, data: { userId: request.params.userId, status: body.active ? "active" : "disabled" } }); } catch (cause) { fail(response, cause); } });
  router.put("/staff/:userId/permission-sets", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await operator(request, dependencies, "permissions.assignStaff"); if (!Array.isArray(body.permissionSetIds) || body.permissionSetIds.some((id) => typeof id !== "string" || !id.trim())) throw new V2ApplicationError("VALIDATION_ERROR", "permissionSetIds is required."); await dependencies.teamAccess.replaceStaffAssignments(principal as StaffPrincipal, organizationId, requiredString(request.params.userId, "userId"), body.permissionSetIds as string[], context(body)); response.json({ ok: true, data: { userId: request.params.userId } }); } catch (cause) { fail(response, cause); } });
  router.get("/portal-access", async (request, response) => { try { const { organizationId } = await operator(request, dependencies, "permissions.view"); const data = await dependencies.teamAccess.read(organizationId); response.json({ ok: true, data: { portalAccess: data.portalAccess, authorityRevision: data.authorityRevision } }); } catch (cause) { fail(response, cause); } });
  router.post("/portal-access/bootstrap", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await operator(request, dependencies, "permissions.assignPortal"); const data = await dependencies.teamAccess.bootstrapPortalAccess(principal as StaffPrincipal, organizationId, { customerId: requiredString(body.customerId, "customerId"), contactId: requiredString(body.contactId, "contactId"), permissionSetId: requiredString(body.permissionSetId, "permissionSetId") }, context(body)); response.status(201).json({ ok: true, data }); } catch (cause) { fail(response, cause); } });
  router.post("/portal-access/:portalAccessId/resend-setup", async (request, response) => { try { const body=bodyOf(request.body); const {organizationId,principal}=await operator(request,dependencies,"permissions.assignPortal"); const data=await dependencies.teamAccess.resendPortalSetup(principal as StaffPrincipal,organizationId,requiredString(request.params.portalAccessId,"portalAccessId"),context(body)); response.json({ok:true,data}); } catch(cause) { fail(response,cause); } });
  router.patch("/portal-access/:portalAccessId/status", async (request,response) => { try { const body=bodyOf(request.body); const {organizationId,principal}=await operator(request,dependencies,"permissions.assignPortal"); if(body.status!=="suspended"&&body.status!=="disabled")throw new V2ApplicationError("VALIDATION_ERROR","status must be suspended or disabled."); await dependencies.teamAccess.setPortalAccessStatus(principal as StaffPrincipal,organizationId,requiredString(request.params.portalAccessId,"portalAccessId"),body.status,context(body)); response.json({ok:true,data:{portalAccessId:request.params.portalAccessId,status:body.status}}); } catch(cause) { fail(response,cause); } });
  router.put("/portal-access/:portalAccessId/permission-sets", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await operator(request, dependencies, "permissions.assignPortal"); if (!Array.isArray(body.permissionSetIds) || body.permissionSetIds.some((id) => typeof id !== "string" || !id.trim())) throw new V2ApplicationError("VALIDATION_ERROR", "permissionSetIds is required."); await dependencies.teamAccess.replacePortalAssignments(principal as StaffPrincipal, organizationId, requiredString(request.params.portalAccessId, "portalAccessId"), body.permissionSetIds as string[], context(body)); response.json({ ok: true, data: { portalAccessId: request.params.portalAccessId } }); } catch (cause) { fail(response, cause); } });
  router.get("/permission-sets", async (request, response) => { try { const { organizationId } = await operator(request, dependencies, "permissions.view"); const data = await dependencies.teamAccess.read(organizationId); response.json({ ok: true, data: { permissionSets: data.permissionSets, capabilityGroups: data.capabilityGroups, authorityRevision: data.authorityRevision } }); } catch (cause) { fail(response, cause); } });
  router.get("/permission-sets/:permissionSetId", async (request, response) => { try { const { organizationId } = await operator(request, dependencies, "permissions.view"); const data = await dependencies.teamAccess.read(organizationId); const permissionSet = (data.permissionSets as readonly { permissionSetId: string }[]).find((item) => item.permissionSetId === request.params.permissionSetId); if (!permissionSet) throw new V2ApplicationError("NOT_FOUND", "Permission set was not found."); response.json({ ok: true, data: { permissionSet, capabilityGroups: data.capabilityGroups, authorityRevision: data.authorityRevision } }); } catch (cause) { fail(response, cause); } });
  router.post("/permission-sets", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await operator(request, dependencies, "permissions.manageSets"); const principalKind = body.principalKind === "portal" ? "portal" : body.principalKind === undefined || body.principalKind === "staff" ? "staff" : (() => { throw new V2ApplicationError("VALIDATION_ERROR", "principalKind is invalid."); })(); const data = await dependencies.teamAccess.createCustomSet(principal as StaffPrincipal, organizationId, { name: requiredString(body.name, "name"), description: optionalString(body.description, "description"), principalKind, capabilities: parseCapabilities(body.capabilities) }, context(body)); response.status(201).json({ ok: true, data }); } catch (cause) { fail(response, cause); } });
  router.put("/permission-sets/:permissionSetId", async (request, response) => { try { const body = bodyOf(request.body); const { organizationId, principal } = await operator(request, dependencies, "permissions.manageSets"); if (typeof body.active !== "boolean") throw new V2ApplicationError("VALIDATION_ERROR", "active is required."); await dependencies.teamAccess.updateCustomSet(principal as StaffPrincipal, organizationId, requiredString(request.params.permissionSetId, "permissionSetId"), { name: requiredString(body.name, "name"), description: optionalString(body.description, "description"), active: body.active, capabilities: parseCapabilities(body.capabilities) }, context(body)); response.json({ ok: true, data: { permissionSetId: request.params.permissionSetId } }); } catch (cause) { fail(response, cause); } });
  router.get("/readiness", async (request, response) => { try { const { organizationId } = await operator(request, dependencies, "permissions.view"); const data = await dependencies.teamAccess.read(organizationId); response.json({ ok: true, data: data.readiness }); } catch (cause) { fail(response, cause); } });
  return router;
};
