import type { Pool } from "pg";
import { extractProductOptionPricingMatrix, resolveProductOptionPricingMatrixBaseRateCents } from "../../../shared/productOptionPricingMatrix.js";
import type { ProductActiveDefinition, ProductCatalogItem, ProductCatalogPage, ProductWorkspaceDetail, ProductWorkspaceReadPort } from "../../src/interfaces/http/productRoutes.js";
import { PostgresProductVersionLifecycleReader } from "./postgresProductVersionLifecycle.js";

type Row = { product_id:string; product_name:string; product_updated_at:Date; description:string; category:string|null; measurement_mode:"dimensions_required"|"quantity_only"; workflow_intent:"standard_production"|"fulfillment_only"|"service_fee"; requires_production_job:boolean; requires_proof_approval:boolean; is_active:boolean; pricing_engine:string|null; pricing_profile_key:string|null; pricing_formula_id:string|null; product_formula:string|null; product_type_name:string|null; routing_mode:"route_required"|"no_route"|"unconfigured"|null; default_route_template_id:string|null; material_name:string|null; active_tree_id:string|null; active_published_at:Date|null; active_tree_json:unknown; draft_tree_id:string|null; draft_updated_at:Date|null; formula_name:string|null; formula_expression:string|null };
type RecipeRow = { component_id:string; material_name:string; material_sku:string|null; quantity:string; quantity_unit:string; quantity_kind:string; condition_option_id:string|null; condition_choice_value:string|null; replaces_pbv2_compatibility:boolean };
type RoutingRow = { routing_mode:"route_required"|"no_route"|"unconfigured"; route_template_name:string|null; source_template_revision:string|null; source_template_fingerprint:string|null; steps_json:unknown };
const record=(value:unknown):Record<string,any>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,any>:{};
const str=(value:unknown)=>typeof value==="string"?value:"";
const finite=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:undefined;
const selectionKey=(node:Record<string,unknown>)=>{const input=record(node.input);return str(input.selectionKey)||str(node.key)||str(node.id);};
const pricing=(r:Row) => { const tree=record(r.active_tree_json), meta=record(tree.meta), p=record(meta.pricingV2); if (record(tree.pricingMatrix).dimensions?.length || record(meta.pricingMatrix).dimensions?.length) return "Matrix"; if (r.pricing_engine==="formulaLibrary"||r.pricing_engine==="pricingFormula"||typeof meta.pricingFormula==="string") return "Formula"; if (r.pricing_profile_key==="fee") return "Flat fee"; if (typeof record(p.base).perSqftCents==="number") return "Per sq ft"; if (typeof record(p.base).perPieceCents==="number") return "Per piece"; return "Not configured"; };
const lifecycle=(r:Row):ProductCatalogItem["lifecycle"]=>!r.is_active&&r.draft_tree_id?"draft":!r.is_active?"inactive":r.draft_tree_id?"active_with_draft":"active";
const item=(r:Row):ProductCatalogItem=>({ productId:r.product_id,displayName:r.product_name,...(r.category?{category:r.category}:{}),lifecycle:lifecycle(r),measurementMode:r.measurement_mode,pricingSummary:pricing(r),...(r.product_type_name?{productType:{displayName:r.product_type_name,routePolicy:r.routing_mode==="route_required"&&r.default_route_template_id?"route_required":r.routing_mode==="no_route"?"no_route":"unconfigured"} }:{}),...(r.material_name?{primaryMaterialName:r.material_name}:{}),...(r.active_tree_id?{activeVersion:{label:r.active_published_at?`Published ${r.active_published_at.toISOString().slice(0,10)}`:"Active"}}:{}),hasDraft:Boolean(r.draft_tree_id)});

const activeDefinition=(r:Row, components:readonly RecipeRow[], routing?:RoutingRow):ProductActiveDefinition|undefined=>{
  if(!r.active_tree_id)return undefined;
  const tree=record(r.active_tree_json), meta=record(tree.meta), nodes=record(tree.nodes), roots=Array.isArray(tree.rootNodeIds)?tree.rootNodeIds:[];
  const options=roots.flatMap(id=>{const node=record(nodes[String(id)]), input=record(node.input), type=str(input.type); if(node.kind!=="question"||!type)return[]; const choices=(Array.isArray(node.choices)?node.choices:[]).flatMap(raw=>{const choice=record(raw), value=choice.value; return ["string","number","boolean"].includes(typeof value)?[{label:str(choice.label)||String(value),value:value as string|number|boolean}]:[];}); const defaultLabel=choices.find(choice=>choice.value===input.defaultValue)?.label; return [{label:str(node.label)||str(node.id),inputType:type,required:Boolean(input.required),...(defaultLabel?{defaultLabel}:{}),choices}];});
  const condition=(optionId:string|null, choice:string|null)=>{if(!optionId||!choice)return undefined; const node=Object.values(nodes).map(record).find(value=>str(value.id)===optionId||selectionKey(value)===optionId||selectionKey(value).replace(/^opt_/u,"")===optionId.replace(/^opt_/u,"")); const selected=(Array.isArray(node?.choices)?node!.choices:[]).map(record).find(value=>value.value===choice); return `When ${str(node?.label)||optionId} = ${str(selected?.label)||choice}`;};
  const p=record(meta.pricingV2), base=record(p.base), qty=Array.isArray(p.qtyTiers)?p.qtyTiers:[], sqft=Array.isArray(p.sqftTiers)?p.sqftTiers:[];
  const tiers=(qty.length?qty:sqft).map(raw=>{const tier=record(raw);return {minimum:Number(tier.minQty??tier.minSqft??1),maximum:typeof tier.maxQty==="number"?tier.maxQty:null,...(finite(tier.perPieceCents)!==undefined?{perPieceCents:finite(tier.perPieceCents)!}:{}),...(finite(tier.perSqftCents)!==undefined?{perSquareFootCents:finite(tier.perSqftCents)!}:{}),...(finite(tier.minimumChargeCents)!==undefined?{minimumChargeCents:finite(tier.minimumChargeCents)!}:{})};});
  const matrix=extractProductOptionPricingMatrix(tree); const matrixView=matrix?{pricingUnit:record(p).optionMatrixPricingUnit==="per_piece"?"per_piece" as const:"per_square_foot" as const,dimensions:matrix.dimensions.map(key=>{const node=Object.values(nodes).map(record).find(value=>selectionKey(value)===key);return str(node?.label)||key;}),rows:matrix.rows.map(raw=>{const row=record(raw), match=record(row.when??row.match??row.combination); return {selections:matrix.dimensions.map(key=>{const node=Object.values(nodes).map(record).find(value=>selectionKey(value)===key), choice=(Array.isArray(node?.choices)?node!.choices:[]).map(record).find(value=>value.value===match[key]); return `${str(node?.label)||key}: ${str(choice?.label)||String(match[key]??"—")}`;}),baseRateCents:resolveProductOptionPricingMatrixBaseRateCents(raw)??0,tierCount:Array.isArray(row.qtyTiers)?row.qtyTiers.length:0,computedSheetTiers:row.tierBasis==="computed_sheet_usage"};})}:undefined;
  const expression=str(meta.pricingFormula)||str(r.formula_expression)||str(r.product_formula); const variables=Object.fromEntries(Object.entries({...record(meta.pricingFormulaVariables),...record(meta.formulaVariables)}).filter(([,value])=>typeof value==="number"&&Number.isFinite(value))) as Record<string,number>;
  const mode=matrix&&expression?"matrix_formula":matrix?"matrix":expression?"formula":finite(base.perPieceCents)!==undefined||finite(base.perSqftCents)!==undefined?"simple":"unconfigured";
  const spec=record(meta.productionUnitSpecification), productionUnits=(Array.isArray(spec.rules)?spec.rules:[]).flatMap(raw=>{const rule=record(raw), when=record(rule.when); const conditional=str(when.selectionKey)&&when.equals!==undefined?(()=>{const node=Object.values(nodes).map(record).find(value=>selectionKey(value)===when.selectionKey), choice=(Array.isArray(node?.choices)?node!.choices:[]).map(record).find(value=>value.value===when.equals);return `When ${str(node?.label)||String(when.selectionKey)} = ${str(choice?.label)||String(when.equals)}`;})():undefined;return str(rule.key)?[{key:str(rule.key),...(str(rule.side)?{side:str(rule.side)}:{}),...(conditional?{condition:conditional}:{})}]:[];});
  return {productVersionId:r.active_tree_id,options,pricing:{mode,...(finite(base.perPieceCents)!==undefined?{perPieceCents:finite(base.perPieceCents)!}:{}),...(finite(base.perSqftCents)!==undefined?{perSquareFootCents:finite(base.perSqftCents)!}:{}),...(finite(base.minimumChargeCents)!==undefined?{minimumChargeCents:finite(base.minimumChargeCents)!}:{}),...(p.tierBasis==="computed_sheet_usage"?{tierBasis:"computed_sheet_usage" as const}:qty.length?{tierBasis:"quantity" as const}:sqft.length?{tierBasis:"square_foot" as const}:{}),tiers,...(expression?{formula:{...(r.formula_name?{name:r.formula_name}:{}),expression,variables}}:{}),...(matrixView?{matrix:matrixView}:{})},recipe:components.map(component=>({componentId:component.component_id,materialName:component.material_name,...(component.material_sku?{materialSku:component.material_sku}:{}),quantity:component.quantity,unit:component.quantity_unit,basis:component.quantity_kind,...(condition(component.condition_option_id,component.condition_choice_value)?{condition:condition(component.condition_option_id,component.condition_choice_value)!}:{}),replacesCompatibility:component.replaces_pbv2_compatibility})),productionUnits,...(routing?{routing:{mode:routing.routing_mode,...(routing.route_template_name?{templateName:routing.route_template_name}:{}),...(routing.source_template_revision?{revision:routing.source_template_revision}:{}),...(routing.source_template_fingerprint?{fingerprint:routing.source_template_fingerprint}:{}),steps:(Array.isArray(routing.steps_json)?routing.steps_json:[]).map(raw=>str(record(raw).kind)).filter(Boolean)}}:{})};
};

/** Bounded Product-administration reader. It deliberately never resolves historical Sales configuration. */
export class PostgresProductWorkspaceReads implements ProductWorkspaceReadPort { private readonly versions:PostgresProductVersionLifecycleReader; constructor(private readonly pool:Pool){this.versions=new PostgresProductVersionLifecycleReader(pool);} private select(){return `SELECT p.id product_id,p.name product_name,p.updated_at product_updated_at,p.description,p.category,p.measurement_mode,p.workflow_intent,p.requires_production_job,p.requires_proof_approval,p.is_active,p.pricing_engine,p.pricing_profile_key,p.pricing_formula_id,p.pricing_formula product_formula,pt.name product_type_name,pt.routing_mode,pt.default_route_template_id,m.name material_name,a.id active_tree_id,a.published_at active_published_at,a.tree_json active_tree_json,d.id draft_tree_id,d.updated_at draft_updated_at,f.name formula_name,f.expression formula_expression`;}
 async list(organizationId:string,input:Readonly<{query?:string;page?:number;pageSize?:number}>={}) : Promise<ProductCatalogPage>{const page=Math.max(1,input.page??1),pageSize=Math.min(100,Math.max(1,input.pageSize??50)),q=(input.query??"").trim(),where=`p.organization_id=$1 AND (p.name ILIKE $2 OR COALESCE(p.category,'') ILIKE $2)`; const joins=` FROM products p LEFT JOIN product_types pt ON pt.id=p.product_type_id AND pt.organization_id=p.organization_id LEFT JOIN materials m ON m.id=p.primary_material_id AND m.organization_id=p.organization_id LEFT JOIN pbv2_tree_versions a ON a.id=p.pbv2_active_tree_version_id AND a.organization_id=p.organization_id AND a.product_id=p.id AND a.status='ACTIVE' LEFT JOIN LATERAL (SELECT id,updated_at FROM pbv2_tree_versions d WHERE d.organization_id=p.organization_id AND d.product_id=p.id AND d.status='DRAFT' ORDER BY d.updated_at DESC,d.id DESC LIMIT 1) d ON TRUE LEFT JOIN pricing_formulas f ON f.id=p.pricing_formula_id AND f.organization_id=p.organization_id AND f.is_active=TRUE`; const values=[organizationId,`%${q}%`,pageSize,(page-1)*pageSize]; const [totalResult,result]=await Promise.all([this.pool.query<{total:string}>(`SELECT count(*)::text total FROM products p WHERE ${where}`,[organizationId,`%${q}%`]),this.pool.query<Row>(`${this.select()} ${joins} WHERE ${where} ORDER BY p.name,p.id LIMIT $3 OFFSET $4`,values)]); const total=Number(totalResult.rows[0]?.total??0); return {items:result.rows.map(item),page,pageSize,total,hasMore:page*pageSize<total};}
 async get(organizationId:string,productId:string):Promise<ProductWorkspaceDetail|null>{const joins=` FROM products p LEFT JOIN product_types pt ON pt.id=p.product_type_id AND pt.organization_id=p.organization_id LEFT JOIN materials m ON m.id=p.primary_material_id AND m.organization_id=p.organization_id LEFT JOIN pbv2_tree_versions a ON a.id=p.pbv2_active_tree_version_id AND a.organization_id=p.organization_id AND a.product_id=p.id AND a.status='ACTIVE' LEFT JOIN LATERAL (SELECT id,updated_at FROM pbv2_tree_versions d WHERE d.organization_id=p.organization_id AND d.product_id=p.id AND d.status='DRAFT' ORDER BY d.updated_at DESC,d.id DESC LIMIT 1) d ON TRUE LEFT JOIN pricing_formulas f ON f.id=p.pricing_formula_id AND f.organization_id=p.organization_id AND f.is_active=TRUE`;const result=await this.pool.query<Row>(`${this.select()} ${joins} WHERE p.organization_id=$1 AND p.id=$2`,[organizationId,productId]);const r=result.rows[0];if(!r)return null;const [versions,componentResult,routingResult]=await Promise.all([this.versions.read(organizationId,productId),r.active_tree_id?this.pool.query<RecipeRow>(`SELECT c.id component_id,c.material_name_snapshot material_name,c.material_sku_snapshot material_sku,c.quantity::text quantity,c.quantity_unit,c.quantity_kind,c.condition_option_id,c.condition_choice_value,c.replaces_pbv2_compatibility FROM v2_product_recipes recipe JOIN v2_product_recipe_components c ON c.recipe_id=recipe.id WHERE recipe.organization_id=$1 AND recipe.product_version_id=$2 ORDER BY c.position,c.id`,[organizationId,r.active_tree_id]):Promise.resolve({rows:[] as RecipeRow[]}),r.active_tree_id?this.pool.query<RoutingRow>(`SELECT spec.routing_mode,template.name route_template_name,spec.source_template_revision::text,spec.source_template_fingerprint,spec.steps_json FROM v2_product_version_routing_specs spec LEFT JOIN v2_route_templates template ON template.id=spec.route_template_id AND template.organization_id=spec.organization_id WHERE spec.organization_id=$1 AND spec.product_version_id=$2`,[organizationId,r.active_tree_id]):Promise.resolve({rows:[] as RoutingRow[]})]);if(!versions)return null;const nodes=record(r.active_tree_json).nodes;const definition=activeDefinition(r,componentResult.rows,routingResult.rows[0]);return {...item(r),productUpdatedAt:r.product_updated_at.toISOString(),...(r.description?{description:r.description}:{}),workflowIntent:r.workflow_intent,requiresProductionJob:r.requires_production_job,requiresProofApproval:r.requires_proof_approval,configurableOptionCount:nodes&&typeof nodes==="object"?Object.values(nodes).filter((n:any)=>n&&n.kind!=="group"&&String(n.type).toUpperCase()!=="GROUP").length:0,...(definition?{activeDefinition:definition}:{}),versions};}}
