import { useQuery } from "@tanstack/react-query";
import React, { useState } from "react";
import { artworkApi, orderApi, type ArtworkWorkspaceDetailAssignment } from "./api";
import { ArtworkUploadPanel } from "./ArtworkUploadPanel";

const unavailable = "—";
const text = (value: unknown, fallback = unavailable) => typeof value === "string" && value.trim() ? value : fallback;
const bytes = (value: unknown) => typeof value !== "number" || !Number.isFinite(value) || value < 0 ? unavailable : value < 1024 ? `${value} B` : value < 1024 * 1024 ? `${(value / 1024).toFixed(1)} KB` : `${(value / (1024 * 1024)).toFixed(1)} MB`;
const date = (value: unknown) => typeof value !== "string" || Number.isNaN(new Date(value).valueOf()) ? unavailable : new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value));
const usage = (item: Readonly<{ purpose?: string; side?: string; sourcePageIndex?: number; layerKey?: string; layerOrder?: number }>) => [typeof item.purpose === "string" ? item.purpose.replaceAll("_", " ") : undefined, text(item.side, ""), typeof item.sourcePageIndex === "number" && item.sourcePageIndex >= 0 ? `page ${item.sourcePageIndex + 1}` : undefined, typeof item.layerKey === "string" && item.layerKey.trim() && typeof item.layerOrder === "number" && item.layerOrder >= 0 ? `${item.layerKey} ${item.layerOrder + 1}` : undefined].filter(Boolean).join(" · ") || "Assignment";
const dimensions = (file: Readonly<{ pageCount?: number; detectedWidthMicrons?: number; detectedHeightMicrons?: number }>) => [typeof file.pageCount === "number" && file.pageCount > 0 ? `${file.pageCount} page${file.pageCount === 1 ? "" : "s"}` : undefined, typeof file.detectedWidthMicrons === "number" && file.detectedWidthMicrons > 0 && typeof file.detectedHeightMicrons === "number" && file.detectedHeightMicrons > 0 ? `${(file.detectedWidthMicrons / 1000).toFixed(1)} × ${(file.detectedHeightMicrons / 1000).toFixed(1)} mm` : undefined].filter(Boolean).join(" · ") || unavailable;
const source = (value: unknown) => typeof value === "string" && value.trim() ? value.replaceAll("_", " ") : "Not recorded";
const FileGlyph = ({ filename }: Readonly<{ filename: unknown }>) => <span className="v2-artwork-glyph" aria-label="No preview available">{text(filename, "FILE").split(".").pop()?.slice(0, 3).toUpperCase() || "FILE"}</span>;

const AssignmentContext = ({ item, openCustomer, openOrder }: Readonly<{ item: ArtworkWorkspaceDetailAssignment; openCustomer: (id: string) => void; openOrder: (id: string) => void }>) => <section className="v2-artwork-assignment-card">
  <header><strong>{usage(item.assignment)}</strong><small>Canonical assignment</small></header>
  <dl><div><dt>Order</dt><dd><button type="button" onClick={() => openOrder(item.assignment.orderId)}>#{item.orderNumber}</button></dd></div><div><dt>Customer</dt><dd>{item.customerId ? <button type="button" onClick={() => openCustomer(item.customerId!)}>{item.customerDisplayName}</button> : item.customerDisplayName}</dd></div><div><dt>Line item</dt><dd>{item.lineDescription || unavailable}</dd></div></dl>
</section>;

const ArtworkDetail = ({ organizationId, sessionScope, fileId, canView, backToCatalog, openArtwork, openCustomer, openOrder }: Readonly<{ organizationId: string; sessionScope: string; fileId: string; canView: boolean; backToCatalog: () => void; openArtwork: (id: string) => void; openCustomer: (id: string) => void; openOrder: (id: string) => void }>) => {
  const detail = useQuery({ queryKey: ["v2", sessionScope, organizationId, "artwork", "file", fileId], queryFn: () => artworkApi.detail(organizationId, fileId), enabled: Boolean(organizationId && sessionScope && canView && fileId) });
  if (detail.isLoading) return <section className="v2-artwork"><p className="v2-proof-empty">Loading Artwork…</p></section>;
  if (detail.isError || !detail.data) return <section className="v2-artwork"><button className="v2-artwork-back" type="button" onClick={backToCatalog}>← Artwork</button><p className="v2-proof-empty">Artwork is unavailable.</p></section>;
  const artwork = detail.data;
  return <section className="v2-artwork v2-artwork-detail" aria-label="Artwork detail">
    <button className="v2-artwork-back" type="button" onClick={backToCatalog}>← Artwork</button>
    <header className="v2-artwork-detail-header"><div><FileGlyph filename={artwork.file.displayFilename} /><div><p className="eyebrow">Canonical Artwork file</p><h1>{text(artwork.file.displayFilename, "Artwork file")}</h1><p>{text(artwork.file.contentType)} · {bytes(artwork.file.byteSize)} · adopted {date(artwork.file.createdAt)}</p></div></div><span>No preview available</span></header>
    <div className="v2-artwork-detail-grid">
      <section><h2>File metadata</h2><dl><div><dt>Original filename</dt><dd>{text(artwork.file.originalFilename)}</dd></div><div><dt>Source</dt><dd>{source(artwork.file.source)}</dd></div><div><dt>Pages / dimensions</dt><dd>{dimensions(artwork.file)}</dd></div><div><dt>Preview</dt><dd>Private preview/download access is not available in the current Artwork contract.</dd></div></dl></section>
      <section><h2>Lineage</h2>{artwork.file.derivedFromArtworkFileId ? <p>This file is derived from <button type="button" className="v2-artwork-link" onClick={() => openArtwork(artwork.file.derivedFromArtworkFileId!)}>related Artwork</button>.</p> : <p>Original canonical Artwork file.</p>}<small>Lineage is shown only when persisted by Artwork.</small></section>
    </div>
    <section className="v2-artwork-assignments"><header><div><h2>Assignments</h2><p>One Artwork file can be used by multiple Order lines.</p></div><span>{artwork.assignments.length}</span></header>{artwork.assignments.length ? <div>{artwork.assignments.map((assignment) => <AssignmentContext key={assignment.assignment.id} item={assignment} openCustomer={openCustomer} openOrder={openOrder} />)}</div> : <p className="v2-artwork-empty">No canonical assignments are available for this Artwork file.</p>}</section>
    <section className="v2-artwork-note"><h2>Workflow context</h2><p>Proofing, Prepress, and Production own their workflow records. This Artwork detail does not duplicate their state or actions.</p></section>
  </section>;
};

/** Canonical Artwork files shown through their real typed assignments, not a second file universe. */
export const ArtworkWorkspace = ({ organizationId, sessionScope, canView, orderId, lineId, artworkFileId, openArtwork, openCustomer, openOrder, backToCatalog }: Readonly<{ organizationId: string; sessionScope: string; canView: boolean; orderId?: string; lineId?: string; artworkFileId?: string; openArtwork: (id: string) => void; openCustomer: (id: string) => void; openOrder: (id: string) => void; backToCatalog: () => void }>) => {
  const [search, setSearch] = useState("");
  const workspace = useQuery({ queryKey: ["v2", sessionScope, organizationId, "artwork", "workspace", search], queryFn: () => artworkApi.workspace(organizationId, search), enabled: Boolean(organizationId && sessionScope && canView && !artworkFileId) });
  const order = useQuery({ queryKey: ["v2", sessionScope, organizationId, "artwork", "target-order", orderId], queryFn: () => orderApi.get(organizationId, orderId!), enabled: Boolean(organizationId && sessionScope && canView && orderId && lineId && !artworkFileId) });
  if (!organizationId) return <section className="v2-artwork"><p className="v2-proof-empty">Enter an authenticated organization in Sales before opening Artwork.</p></section>;
  if (!canView) return <section className="v2-artwork"><p className="v2-proof-empty">You do not have permission to view Artwork.</p></section>;
  if (artworkFileId) return <ArtworkDetail organizationId={organizationId} sessionScope={sessionScope} fileId={artworkFileId} canView={canView} backToCatalog={backToCatalog} openArtwork={openArtwork} openCustomer={openCustomer} openOrder={openOrder} />;
  const items = (workspace.data?.items ?? []).filter((item) => (!orderId || item.assignment.orderId === orderId) && (!lineId || item.assignment.orderLineId === lineId));
  const targetLine = order.data?.order.lines.find((line) => line.lineId === lineId);
  return <section className="v2-artwork"><header className="v2-artwork-heading"><div><h1>Artwork</h1><p>Files attach to line items, not just orders.</p></div>{orderId && <span>Order context</span>}</header>
    {orderId && <div className="v2-artwork-focus"><strong>Focused on Order artwork{lineId ? " line" : ""}.</strong><span>Artwork ownership and typed assignments remain canonical.</span><button type="button" onClick={() => openOrder(orderId)}>Open Order</button></div>}
    <div className="v2-artwork-tools"><label>Search Artwork<input aria-label="Search Artwork" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="File, order, customer, line…" /></label><small>Each row is an assignment; a file can legitimately appear in several usages.</small></div>
    {orderId && lineId && order.isLoading && <section className="v2-artwork-note"><p>Loading the selected Order line…</p></section>}
    {orderId && lineId && order.isError && <section className="v2-artwork-note"><p className="v2-product-version-message">The selected Order line is unavailable for Artwork upload.</p></section>}
    {orderId && lineId && order.data && !targetLine && <section className="v2-artwork-note"><p className="v2-product-version-message">The selected Order line is unavailable for Artwork upload.</p></section>}
    {orderId && lineId && targetLine && <ArtworkUploadPanel organizationId={organizationId} target={{ orderId, orderLineId: lineId, orderNumber: order.data!.number.display, lineDescription: targetLine.description || `Line ${targetLine.position}` }} onUploaded={() => void workspace.refetch()} />}
    {!orderId && <section className="v2-artwork-note"><h2>Upload Artwork</h2><p>Open Artwork from an Order line to upload and assign a canonical PDF.</p></section>}
    <div className="v2-artwork-table-wrap"><table><thead><tr><th>File</th><th>Order</th><th>Type / assignment</th><th>Size</th><th>Derived file</th><th /></tr></thead><tbody>{workspace.isLoading && <tr><td colSpan={6}>Loading Artwork…</td></tr>}{workspace.isError && <tr><td colSpan={6}>Artwork is unavailable in this organization.</td></tr>}{workspace.isSuccess && !items.length && <tr><td colSpan={6}>No canonical Artwork assignments match this context.</td></tr>}{items.map((item) => <tr key={item.assignment.id}><td><button className="v2-artwork-file" type="button" onClick={() => openArtwork(item.file.id)}><FileGlyph filename={item.file.displayFilename} /><span><b>{item.file.displayFilename}</b><small>No preview available · {item.file.contentType}</small></span></button></td><td><button className="v2-artwork-link" type="button" onClick={() => openOrder(item.assignment.orderId)}>#{item.orderNumber}</button><small>{item.customerId ? <button className="v2-artwork-link" type="button" onClick={() => openCustomer(item.customerId!)}>{item.customerDisplayName}</button> : item.customerDisplayName} · {item.lineDescription}</small></td><td><em>{usage(item.assignment)}</em></td><td>{bytes(item.file.byteSize)}<small>{dimensions(item.file)}</small></td><td>{item.file.derivedFromArtworkFileId ? <button className="v2-artwork-link" type="button" onClick={() => openArtwork(item.file.derivedFromArtworkFileId!)}>View parent</button> : "Original"}</td><td><button className="v2-artwork-open" type="button" onClick={() => openArtwork(item.file.id)}>Open</button></td></tr>)}</tbody></table></div>
  </section>;
};
