import { useQuery } from "@tanstack/react-query";
import { financeApi, orderApi, quoteApi } from "./api";

/** Read/navigation dashboard composed from bounded canonical workspace projections. */
export const CommandCenter = ({ organizationId, sessionScope, canQuoteView, canOrderView, canFinanceView, navigate }: Readonly<{ organizationId: string; sessionScope: string; canQuoteView: boolean; canOrderView: boolean; canFinanceView: boolean; navigate: (page: "quotes" | "orders" | "invoices" | "payments") => void }>) => {
  const quotes = useQuery({ queryKey: ["v2", sessionScope, organizationId, "command-center", "quotes"], queryFn: () => quoteApi.list(organizationId), enabled: Boolean(organizationId && sessionScope && canQuoteView) });
  const orders = useQuery({ queryKey: ["v2", sessionScope, organizationId, "command-center", "orders"], queryFn: () => orderApi.list(organizationId), enabled: Boolean(organizationId && sessionScope && canOrderView) });
  const finance = useQuery({ queryKey: ["v2", sessionScope, organizationId, "command-center", "finance"], queryFn: () => financeApi.overview(organizationId), enabled: Boolean(organizationId && sessionScope && canFinanceView) });
  const invoices = finance.data?.items ?? [];
  const outstanding = invoices.reduce((sum, item) => sum + item.balance.cents, 0);
  if (!organizationId) return <section className="v2-command-center"><p className="v2-proof-empty">Enter an authenticated organization to load its canonical workspace summary.</p></section>;
  return <section className="v2-command-center"><header><div><p>Workspace overview</p><h1>Command Center</h1><span>Read-only summaries from Sales and Billing projections. Operations remain with their owners.</span></div></header>
    <div className="v2-command-metrics">{canQuoteView && <button onClick={() => navigate("quotes")}><small>Quotes</small><b>{quotes.data?.items.length ?? "—"}</b><span>bounded current list</span></button>}{canOrderView && <button onClick={() => navigate("orders")}><small>Open orders</small><b>{orders.data?.items.filter((item) => item.lifecycle === "open").length ?? "—"}</b><span>bounded current list</span></button>}{canFinanceView && <button onClick={() => navigate("invoices")}><small>Invoices</small><b>{invoices.length}</b><span>Order-backed and issued documents</span></button>}{canFinanceView && <button onClick={() => navigate("payments")}><small>Outstanding balance</small><b>{new Intl.NumberFormat(undefined, { style: "currency", currency: invoices[0]?.gross.currency ?? "USD" }).format(outstanding / 100)}</b><span>derived settlement projection</span></button>}</div>
    <div className="v2-command-grid">{canQuoteView && <article><header><h2>Recent quotes</h2><button onClick={() => navigate("quotes")}>Open Quotes</button></header>{quotes.data?.items.slice(0, 5).map((quote) => <p key={quote.quoteId}><b>{quote.number}</b><span>{quote.customerDisplayName}</span><small>{quote.lifecycle}</small></p>)}{quotes.isSuccess && !quotes.data.items.length && <em>No canonical Quotes available.</em>}</article>}{canOrderView && <article><header><h2>Open orders</h2><button onClick={() => navigate("orders")}>Open Orders</button></header>{orders.data?.items.filter((order) => order.lifecycle === "open").slice(0, 5).map((order) => <p key={order.orderId}><b>{order.number}</b><span>{order.customerDisplayName}</span><small>{order.routing === "routed" ? "Routing present" : "No route"}</small></p>)}{orders.isSuccess && !orders.data.items.filter((order) => order.lifecycle === "open").length && <em>No open canonical Orders available.</em>}</article>}{canFinanceView && <article><header><h2>Billing attention</h2><button onClick={() => navigate("invoices")}>Open Invoices</button></header>{invoices.filter((invoice) => invoice.balance.cents > 0).slice(0, 5).map((invoice) => <p key={invoice.invoiceId}><b>Order {invoice.sourceOrderNumber}</b><span>{invoice.customerName ?? "Customer unavailable"}</span><small>{invoice.settlement ?? "Settlement unavailable"}</small></p>)}{finance.isSuccess && !invoices.some((invoice) => invoice.balance.cents > 0) && <em>No outstanding canonical Invoice balances.</em>}</article>}</div>
  </section>;
};
