import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { fulfillmentApi, newBusinessRequestId, type ApiError, type FulfillmentMethod, type FulfillmentWorkspaceOrder } from "./api";

const keys={list:(scope:string,org:string,q:string)=>["v2",scope,org,"fulfillment","workspace",q] as const,detail:(scope:string,org:string,order:string)=>["v2",scope,org,"fulfillment","order",order] as const};
const errorText=(error:unknown)=>(error as ApiError)?.message??"The Fulfillment service is unavailable.";
const lineState=(line:FulfillmentWorkspaceOrder["lines"][number])=>line.completedFulfillmentQuantity>=line.orderedQuantity?"Fulfilled":line.completedFulfillmentQuantity>0?"Partially fulfilled":line.availableFulfillmentQuantity>0?line.remainingProductionQuantity>0?"Partially available":"Ready to fulfill":"Awaiting production";

/** Operator workspace: server-authoritative physical availability, immutable handoff history. */
export const FulfillmentWorkspace=({organizationId,sessionScope,canView,canPickup,canShip,csrfReady,orderId,onSelectOrder,openOrder,openCustomer}:{organizationId:string;sessionScope:string;canView:boolean;canPickup:boolean;canShip:boolean;csrfReady:boolean;orderId:string;onSelectOrder:(id:string)=>void;openOrder:(id:string)=>void;openCustomer:(id:string)=>void})=>{
 const client=useQueryClient(); const [search,setSearch]=useState(""); const [selected,setSelected]=useState(orderId); const [lineId,setLineId]=useState(""); const [method,setMethod]=useState<FulfillmentMethod>("pickup"); const [quantity,setQuantity]=useState(""); const [notice,setNotice]=useState("");
 const list=useQuery({queryKey:keys.list(sessionScope,organizationId,search),queryFn:()=>fulfillmentApi.list(organizationId,{q:search}),enabled:Boolean(organizationId&&sessionScope&&canView)});
 useEffect(()=>{setSelected(orderId);},[orderId]);
 useEffect(()=>{if(!selected&&!orderId&&list.data?.items[0])setSelected(list.data.items[0].orderId);},[list.data,orderId,selected]);
 const selectOrder=(id:string)=>{setSelected(id);onSelectOrder(id);};
 const detail=useQuery({queryKey:keys.detail(sessionScope,organizationId,selected),queryFn:()=>fulfillmentApi.get(organizationId,selected),enabled:Boolean(selected&&organizationId&&sessionScope&&canView)});
 const order=detail.data; const line=order?.lines.find((item)=>item.orderLineId===lineId)??order?.lines[0];
 useEffect(()=>{if(line&&line.orderLineId!==lineId)setLineId(line.orderLineId);},[line,lineId]);
 useEffect(()=>{if(line)setQuantity(String(line.availableFulfillmentQuantity));},[line?.orderLineId,line?.availableFulfillmentQuantity]);
 const refresh=async()=>{await client.invalidateQueries({queryKey:["v2",sessionScope,organizationId,"fulfillment"]});};
 const complete=useMutation({mutationFn:(input:{method:FulfillmentMethod;quantity:number})=>fulfillmentApi.complete(organizationId,order!.orderId,input.method,newBusinessRequestId(),[{orderLineId:line!.orderLineId,quantity:input.quantity}]),onSuccess:async()=>{setNotice("Authoritative handoff recorded. Production availability and immutable history were refreshed.");await refresh();},onError:async(error)=>{setNotice(errorText(error));const apiError=error as unknown as ApiError;if(apiError.code==="CONFLICT"||apiError.code==="STALE_STATE")await refresh();}});
 const exact=Number(quantity),valid=Boolean(line&&Number.isInteger(exact)&&exact>0&&exact<=line.availableFulfillmentQuantity);
 const submit=(all=false)=>{if(!line)return;const handoffQuantity=all?line.availableFulfillmentQuantity:exact;if(!Number.isInteger(handoffQuantity)||handoffQuantity<1)return;complete.mutate({method,quantity:handoffQuantity});};
 if(!organizationId)return <section className="v2-fulfillment"><div className="v2-proof-empty">Enter an authenticated organization in Sales before opening Fulfillment.</div></section>;
 if(!canView)return <section className="v2-fulfillment"><div className="v2-proof-empty">You do not have permission to view Fulfillment.</div></section>;
 return <section className="v2-fulfillment">
  <aside className="v2-fulfillment-list"><header><h1>Fulfillment</h1><p>Orders group the work; line handoffs remain independent.</p><input aria-label="Search fulfillment orders" value={search} onChange={(event)=>{setSearch(event.target.value);setSelected("");}} placeholder="Search order or customer" /></header><div>{list.data?.items.map((item)=>{const available=item.lines.reduce((n,current)=>n+current.availableFulfillmentQuantity,0),remaining=item.lines.reduce((n,current)=>n+current.remainingFulfillmentQuantity,0);return <button key={item.orderId} className={item.orderId===selected?"active":""} onClick={()=>selectOrder(item.orderId)}><b>{item.number}</b><span>{item.customerName}</span><small>{available} available · {remaining} commercial remaining</small></button>;})}{list.isSuccess&&!list.data?.items.length&&<p className="v2-proof-empty">No Sales Orders match this search.</p>}</div></aside>
  <main className="v2-fulfillment-main">{order?<OrderDetail order={order} lineId={line?.orderLineId??""} setLineId={setLineId} openOrder={openOrder} openCustomer={openCustomer} />:detail.isError?<div className="v2-proof-empty">This Fulfillment Order is unavailable or no longer accessible.</div>:<div className="v2-proof-empty">Loading authenticated Fulfillment work…</div>}</main>
  <aside className="v2-fulfillment-rail">{line?<><section><small>Active order line</small><h2>{line.description}</h2><strong className="v2-fulfillment-status">{lineState(line)}</strong><dl><div><dt>Ordered</dt><dd>{line.orderedQuantity}</dd></div><div><dt>Produced</dt><dd>{line.completedProductionQuantity}</dd></div><div><dt>Available</dt><dd>{line.availableFulfillmentQuantity}</dd></div><div><dt>Fulfilled</dt><dd>{line.completedFulfillmentQuantity}</dd></div><div><dt>In production</dt><dd>{line.remainingProductionQuantity}</dd></div><div><dt>Not handed off</dt><dd>{line.remainingFulfillmentQuantity}</dd></div></dl></section><section className="v2-fulfillment-actions"><small>Handoff action</small><div className="v2-fulfillment-method" aria-label="Fulfillment method"><button className={method==="pickup"?"active":""} onClick={()=>setMethod("pickup")}>Pickup</button><button className={method==="shipment"?"active":""} onClick={()=>setMethod("shipment")}>Shipment</button></div><label>Exact quantity<input aria-label="Fulfillment quantity" type="number" min="1" max={line.availableFulfillmentQuantity} step="1" value={quantity} onChange={(event)=>setQuantity(event.target.value)} /></label>{line.availableFulfillmentQuantity===0?<p>{line.remainingProductionQuantity>0?"No physical quantity is currently available for handoff.":"This line has no remaining handoff quantity."}</p>:<><button className="v2-fulfillment-action primary" disabled={!csrfReady||complete.isPending||!valid||(method==="pickup"?!canPickup:!canShip)} onClick={()=>submit()}>Record partial</button><button className="v2-fulfillment-action" disabled={!csrfReady||complete.isPending||(method==="pickup"?!canPickup:!canShip)} onClick={()=>submit(true)}>Hand off available</button></>}<p>Production output remains upstream. Method is recorded only on this immutable handoff fact.</p>{notice&&<p className="v2-fulfillment-notice">{notice}</p>}</section></>:null}</aside>
 </section>;
};

const OrderDetail=({order,lineId,setLineId,openOrder,openCustomer}:{order:FulfillmentWorkspaceOrder;lineId:string;setLineId:(id:string)=>void;openOrder:(id:string)=>void;openCustomer:(id:string)=>void})=><><header className="v2-fulfillment-header"><div><span>{order.number} · {order.customerName}</span><h1>Order fulfillment</h1><p>Production output, Sales demand, and Fulfillment handoffs remain separate authoritative facts.</p><div className="v2-fulfillment-context"><button onClick={()=>openOrder(order.orderId)}>Open Order</button>{order.customerId&&<button onClick={()=>openCustomer(order.customerId!)}>Open Customer</button>}</div></div><small>{order.commercialState}</small></header><section className="v2-fulfillment-lines"><h2>Order lines</h2>{order.lines.map((line)=><button key={line.orderLineId} className={line.orderLineId===lineId?"active":""} onClick={()=>setLineId(line.orderLineId)}><div><b>{line.description}</b><small>Ordered {line.orderedQuantity} · Produced {line.completedProductionQuantity} · Available {line.availableFulfillmentQuantity} · Fulfilled {line.completedFulfillmentQuantity}</small></div><strong>{lineState(line)}</strong></button>)}</section><section className="v2-fulfillment-history"><h2>Handoff history</h2>{order.handoffs.length?order.handoffs.map(({handoff,allocations})=><article key={handoff.handoffId}><b>{handoff.method}</b><span>{new Date(handoff.completedAt).toLocaleString()}</span><small>{allocations.map((allocation)=>`${allocation.quantity} × ${order.lines.find((line)=>line.orderLineId===allocation.orderLineId)?.description??"order line"}`).join(", ")}</small><small>Recorded by {handoff.completedPrincipalSubject}</small></article>):<p>No customer handoffs recorded for this order.</p>}</section></>;
