import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { financeApi, money, type FinancialInvoiceRead, type FinancialInvoiceListItem } from "./api";

const keys = {
  list: (scope: string, organizationId: string, query: string, lifecycle: string, page: number, pageSize: number) => ["v2", scope, organizationId, "billing", "financial-invoices", query, lifecycle, page, pageSize] as const,
  detail: (scope: string, organizationId: string, source: "v2" | "legacy", invoiceId: string) => ["v2", scope, organizationId, "billing", "financial-invoice", source, invoiceId] as const,
};
const customerName = (invoice: Pick<FinancialInvoiceListItem, "customerName">) => invoice.customerName ?? "Customer unavailable";

/** Secondary Billing workspace: it deliberately shares Finance's paged, mixed-source projection. */
export const InvoiceWorkspace = ({ organizationId, sessionScope, canView }: Readonly<{ organizationId: string; sessionScope: string; canView: boolean }>) => {
  const [query, setQuery] = useState("");
  const [lifecycle, setLifecycle] = useState<"" | FinancialInvoiceListItem["lifecycle"]>("");
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(25);
  const [selected, setSelected] = useState("");
  const [selectedSource, setSelectedSource] = useState<"v2" | "legacy">("v2");
  const list = useQuery({ queryKey: keys.list(sessionScope, organizationId, query, lifecycle, page, pageSize), queryFn: () => financeApi.overview(organizationId, { page, pageSize, ...(query ? { q: query } : {}), ...(lifecycle ? { lifecycle } : {}), sort: "updated", direction: "desc" }), enabled: Boolean(organizationId && sessionScope && canView) });
  useEffect(() => { if (!selected && list.data?.items[0]) { setSelected(list.data.items[0].invoiceId); setSelectedSource(list.data.items[0].source); } }, [list.data, selected]);
  const detail = useQuery({ queryKey: keys.detail(sessionScope, organizationId, selectedSource, selected), queryFn: () => selectedSource === "legacy" ? financeApi.legacyInvoice(organizationId, selected) : financeApi.invoice(organizationId, selected), enabled: Boolean(selected && organizationId && sessionScope && canView) });
  const reset = () => { setPage(1); setSelected(""); setSelectedSource("v2"); };
  if (!organizationId) return <section className="v2-invoices"><div className="v2-proof-empty">Enter an authenticated organization in Sales before opening Invoices.</div></section>;
  if (!canView) return <section className="v2-invoices"><div className="v2-proof-empty">You do not have permission to view Invoices.</div></section>;
  return <section className="v2-invoices">
    <aside className="v2-invoice-list"><header><h1>Invoices</h1><input aria-label="Search invoices" value={query} onChange={(event) => { setQuery(event.target.value); reset(); }} placeholder="Invoice, Order, customer, PO" /><select aria-label="Invoice lifecycle" value={lifecycle} onChange={(event) => { setLifecycle(event.target.value as typeof lifecycle); reset(); }}><option value="">All lifecycles</option><option value="draft">Order-backed</option><option value="issued">Issued</option><option value="void">Void</option></select><label>Rows <select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); reset(); }}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label></header><div>{list.data?.items.map((item) => <button key={`${item.source}:${item.recordId}`} className={item.invoiceId === selected && item.source === selectedSource ? "active" : ""} onClick={() => { setSelected(item.invoiceId); setSelectedSource(item.source); }}><b>{item.source === "legacy" ? "Legacy" : "Invoice"} {item.sourceOrderNumber}</b><span>{customerName(item)}</span><small>{item.settlement ?? item.lifecycle} · {money(item.gross)}</small></button>)}{list.isSuccess && !list.data?.items.length && <p className="v2-proof-empty">No Billing Invoices match this view.</p>}</div><footer><small>{list.data ? `${list.data.totalMatching} matching · page ${list.data.page}` : "Loading…"}</small><button disabled={page <= 1 || list.isFetching} onClick={() => setPage((value) => value - 1)}>Previous</button><button disabled={!list.data?.hasNextPage || list.isFetching} onClick={() => setPage((value) => value + 1)}>Next</button></footer></aside>
    <main className="v2-invoice-main">{detail.data ? <InvoiceDetail read={detail.data} organizationId={organizationId} /> : <div className="v2-proof-empty">Loading authenticated Billing record…</div>}</main>
    <aside className="v2-invoice-rail">{detail.data && <><section><small>Billing status</small><h2>{detail.data.invoice.lifecycle === "draft" ? "Order-backed" : detail.data.invoice.lifecycle}</h2><p>{detail.data.invoice.source === "legacy" ? "Compatibility record; read only." : detail.data.invoice.lifecycle === "draft" ? "This payable Invoice follows the current Sales Order. Payment and Refund history remains immutable." : "Issued facts are frozen in Billing's immutable checkpoint."}</p></section><section><small>Settlement</small><dl><div><dt>Paid</dt><dd>{money(detail.data.settlement.paid)}</dd></div><div><dt>Refunded</dt><dd>{money(detail.data.settlement.refunded)}</dd></div><div><dt>Balance</dt><dd>{money(detail.data.settlement.balance)}</dd></div></dl></section></>}</aside>
  </section>;
};

const InvoiceDetail = ({ read, organizationId }: Readonly<{ read: FinancialInvoiceRead; organizationId: string }>) => {
  const invoice = read.invoice;
  return <><header className="v2-invoice-header"><div><span>Billing record · Source Order {invoice.sourceOrderNumber ?? "unavailable"}</span><h1>Invoice</h1><p>{invoice.customerPresentation?.customerDisplayName ?? invoice.customerPresentation?.companyName ?? "Customer unavailable"}</p></div><div><span className={`v2-invoice-state ${invoice.lifecycle}`}>{invoice.lifecycle === "draft" ? "Order-backed" : invoice.lifecycle}</span>{invoice.source !== "legacy" && <button type="button" onClick={() => window.open(`/v2/organizations/${encodeURIComponent(organizationId)}/invoices/${encodeURIComponent(invoice.invoiceId)}/document.pdf`, "_blank", "noopener,noreferrer")}>Preview PDF</button>}</div></header><section className="v2-invoice-document"><div className="v2-invoice-document-title"><h2>Commercial snapshot</h2><p>{invoice.lifecycle === "draft" ? "Current payable Billing projection from Sales." : "Issued Billing checkpoint; this document no longer follows Sales changes."}</p></div><table><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Amount</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.sourceOrderLineId}><td>{line.description}</td><td>{line.quantity}</td><td>{money(line.sellingUnitAmount)}</td><td>{money(line.lineAmount)}</td></tr>)}</tbody></table><dl className="v2-invoice-totals"><div><dt>Subtotal</dt><dd>{money(invoice.subtotal)}</dd></div><div><dt>Tax</dt><dd>{money(invoice.taxTotal)}</dd></div><div className="total"><dt>Total</dt><dd>{money(invoice.total)}</dd></div><div><dt>Paid</dt><dd>{money(read.settlement.paid)}</dd></div><div><dt>Balance</dt><dd>{money(read.settlement.balance)}</dd></div></dl></section>{invoice.lifecycle === "issued" && <section className="v2-invoice-checkpoint"><h2>Issued checkpoint</h2><p>Issued {invoice.issuedAt ? new Date(invoice.issuedAt).toLocaleString() : "at an unavailable timestamp"}. Customer presentation, commercial totals, tax evidence, and lines are frozen by Billing.</p></section>}</>;
};
