import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { newBusinessRequestId, numberingSettingsApi, type ApiError, type NumberingSettings } from "./api";
type Form = Readonly<{ quotePrefix: string; quoteNextNumber: string; orderPrefix: string; orderNextNumber: string }>;
const formOf = (value: NumberingSettings): Form => { const quote = value.documents.find((item) => item.kind === "quote"); const order = value.documents.find((item) => item.kind === "order"); return { quotePrefix: quote?.prefix ?? "", quoteNextNumber: quote?.nextNumber ?? "", orderPrefix: order?.prefix ?? "", orderNextNumber: order?.nextNumber ?? "" }; };
export const NumberingSettingsWorkspace = ({ organizationId, sessionScope, canConfigure }: Readonly<{ organizationId: string; sessionScope: string; canConfigure: boolean }>) => {
  const client = useQueryClient(); const key = ["v2", sessionScope, organizationId, "settings", "numbering"] as const; const [form, setForm] = useState<Form>({ quotePrefix: "", quoteNextNumber: "", orderPrefix: "", orderNextNumber: "" }); const [notice, setNotice] = useState("");
  const query = useQuery({ queryKey: key, queryFn: () => numberingSettingsApi.get(organizationId), enabled: Boolean(organizationId && sessionScope && canConfigure) });
  useEffect(() => { if (query.data) setForm(formOf(query.data)); }, [query.data?.revision]);
  const save = useMutation({ mutationFn: () => numberingSettingsApi.save(organizationId, newBusinessRequestId(), { expectedRevision: query.data!.revision, quote: { prefix: form.quotePrefix, nextNumber: form.quoteNextNumber }, order: { prefix: form.orderPrefix, nextNumber: form.orderNextNumber } }), onSuccess: (value) => { client.setQueryData(key, value); setNotice("Numbering settings saved."); }, onError: (error) => setNotice((error as unknown as ApiError).message ?? "Numbering settings could not be saved.") });
  if (!canConfigure) return <section className="v2-settings-future"><h2>Numbering</h2><p>You do not have permission to configure document numbering.</p></section>;
  return <section className="v2-settings-form"><header><small>SETTINGS · ORGANIZATION</small><h1>Numbering</h1><p>Configure future native V2 Quote and Order display numbers. Existing historical document identifiers are preserved.</p></header>{query.isLoading ? <p>Loading numbering settings…</p> : <><section className="v2-settings-form-card"><h2>Document series</h2><div className="v2-settings-numbering"><Number label="Quote" prefix={form.quotePrefix} next={form.quoteNextNumber} preview={query.data?.documents.find((item) => item.kind === "quote")?.nextDisplayNumber} onPrefix={(quotePrefix) => setForm({ ...form, quotePrefix })} onNext={(quoteNextNumber) => setForm({ ...form, quoteNextNumber })}/><Number label="Order" prefix={form.orderPrefix} next={form.orderNextNumber} preview={query.data?.documents.find((item) => item.kind === "order")?.nextDisplayNumber} onPrefix={(orderPrefix) => setForm({ ...form, orderPrefix })} onNext={(orderNextNumber) => setForm({ ...form, orderNextNumber })}/></div><p className="v2-settings-muted">Shared job numbers use the Order display number and cannot be configured separately.</p></section><section className="v2-settings-panel"><h2>Compatibility</h2><p>{query.data?.readiness.reasons.join(" · ") || "Native V2 numbering is ready."}</p></section><button className="button" type="button" disabled={save.isPending || !query.data} onClick={() => { setNotice(""); save.mutate(); }}>{save.isPending ? "Saving…" : "Save numbering"}</button>{notice && <p className={notice.includes("saved") ? "notice" : "notice error"}>{notice}</p>}</>}</section>;
};
const Number = ({ label, prefix, next, preview, onPrefix, onNext }: Readonly<{ label: string; prefix: string; next: string; preview?: string; onPrefix: (value: string) => void; onNext: (value: string) => void }>) => <div><h3>{label}</h3><label className="field">Prefix<input value={prefix} onChange={(event) => onPrefix(event.target.value)} /></label><label className="field">Next number<input inputMode="numeric" value={next} onChange={(event) => onNext(event.target.value)} /></label><p className="v2-settings-muted">Next display: {preview ?? "—"}</p></div>;
