import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { OrderLineArtworkCompact, OrderLineArtworkDetail, artworkForOrderLine, lineArtworkUploadTarget, protectedArtworkContentPath } from "./OrderLineArtwork";
import { orderConfigurationPresentation } from "./orderConfigurationPresentation";
import type { ArtworkOrderProjection } from "./api";

const entry = (id: string, lineId: string, filename: string, side?: "front" | "back"): ArtworkOrderProjection => ({ file: { id: `file-${id}`, originalFilename: filename, displayFilename: filename, contentType: "application/pdf", byteSize: 1024, source: "customer_upload", createdAt: "2026-08-26" }, assignment: { id: `assignment-${id}`, artworkFileId: `file-${id}`, orderId: "order-a", orderLineId: lineId, purpose: "customer_supplied", ...(side ? { side } : {}), createdAt: "2026-08-26" } });
const artwork = [entry("front", "line-a", "front.pdf", "front"), entry("back", "line-a", "back.pdf", "back"), entry("additional", "line-a", "additional.pdf", "front"), entry("other", "line-b", "other.pdf")];
assert.deepEqual(artworkForOrderLine(artwork, "line-a").map((value) => value.file.displayFilename), ["front.pdf", "back.pdf", "additional.pdf"]);
assert.equal(protectedArtworkContentPath("org/a", artwork[0]!), "/v2/organizations/org%2Fa/artwork/files/file-front/content#page=1");
const compact = renderToStaticMarkup(<OrderLineArtworkCompact organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView onOpen={() => undefined} />);
assert.match(compact, /front\.pdf|3 files/);
assert.match(compact, /\/v2\/organizations\/org-a\/artwork\/files\/file-front\/content/);
assert.doesNotMatch(compact, /other\.pdf|assignment-front|object_key|storageProvider/);
const detail = renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView canAdopt uploadTarget={{ orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" }} onOpen={() => undefined} onUploaded={() => undefined} />);
assert.match(detail, /front\.pdf.*customer supplied · front/s);
assert.match(detail, /back\.pdf.*customer supplied · back/s);
assert.match(detail, /additional\.pdf.*customer supplied · front/s);
assert.match(detail, /Upload Artwork/);
assert.doesNotMatch(detail, /Select (an? )?line/i, "expanded-line upload must not need a second line picker");
assert.deepEqual(lineArtworkUploadTarget("order-a", "ORD-1", { lineId: "line-a", description: "Banner", position: 1 }), { orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" });
assert.doesNotMatch(detail, /other\.pdf|assignment-front/);
const viewOnlyDetail = renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView uploadTarget={{ orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" }} onOpen={() => undefined} />);
assert.match(viewOnlyDetail, /front\.pdf/);
assert.doesNotMatch(viewOnlyDetail, /Upload Artwork/, "view-only staff must not receive a line upload action");
const adoptionOnlyDetail = renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView={false} canAdopt uploadTarget={{ orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" }} onOpen={() => undefined} onUploaded={() => undefined} />);
assert.match(adoptionOnlyDetail, /Upload Artwork/);
assert.doesNotMatch(adoptionOnlyDetail, /front\.pdf|back\.pdf/, "staff without artwork.view must receive no Artwork data");
assert.match(renderToStaticMarkup(<OrderLineArtworkCompact organizationId="org-a" orderLineId="line-none" artwork={artwork} loading={false} canView onOpen={() => undefined} />), /No artwork/);
assert.match(renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-none" artwork={artwork} loading={false} canView onOpen={() => undefined} />), /No art assigned/);
assert.doesNotMatch(orderConfigurationPresentation({ selections: { opt_old: "choice_old", print_sides__import_x: "yes" } }), /opt_|choice_|_import/);
const workspace = await readFile(new URL("./OrderWorkspace.tsx", import.meta.url), "utf8");
assert.match(workspace, /onOpen=\{\(\) => setEditingLineId\(line\.lineId\)\}/, "Items Artwork status must select its line rather than navigate to the Order-wide Artwork tab");
assert.match(workspace, /onArtworkUploaded=\{artworkUploaded\}/, "line upload publishes to the shared Order Artwork cache");
assert.match(workspace, /onUploaded=\{artworkUploaded\}/, "Order-wide upload uses the same cache publication");
assert.match(workspace, /await queryClient\.fetchQuery\(\{ queryKey: key, queryFn: loadOrderArtwork, staleTime: 0 \}\)/, "panel completion awaits a pinned canonical confirmation");
assert.match(workspace, /const loadOrderArtwork = async \(\) => confirmArtworkProjection/, "stale reconciliation must not overwrite committed evidence");
console.log("Saved Order line Artwork presentation tests passed.");
