import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { OrderLineArtworkCompact, OrderLineArtworkDetail, artworkForOrderLine, lineArtworkUploadTarget, protectedArtworkContentPath } from "./OrderLineArtwork";
import { orderConfigurationPresentation } from "./orderConfigurationPresentation";
import type { ArtworkOrderProjection, OrderRead } from "./api";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { OrderWorkspace } from "./OrderWorkspace";
import { salesKeys } from "./quoteFormQueries";
import { orderArtworkKey } from "./orderArtworkCache";
import { createSalesWorkspaceClient } from "./salesWorkspaceApi";

const entry = (id: string, lineId: string, filename: string, side?: "front" | "back"): ArtworkOrderProjection => ({ file: { id: `file-${id}`, originalFilename: filename, displayFilename: filename, contentType: "application/pdf", byteSize: 1024, source: "customer_upload", createdAt: "2026-08-26" }, assignment: { id: `assignment-${id}`, artworkFileId: `file-${id}`, orderId: "order-a", orderLineId: lineId, purpose: "customer_supplied", ...(side ? { side } : {}), createdAt: "2026-08-26" } });
const artwork = [entry("front", "line-a", "front.pdf", "front"), entry("back", "line-a", "back.pdf", "back"), entry("additional", "line-a", "additional.pdf", "front"), entry("other", "line-b", "other.pdf")];
assert.deepEqual(artworkForOrderLine(artwork, "line-a").map((value) => value.file.displayFilename), ["front.pdf", "back.pdf", "additional.pdf"]);
assert.equal(protectedArtworkContentPath("org/a", artwork[0]!), "/v2/organizations/org%2Fa/artwork/files/file-front/content#page=1");
const compact = renderToStaticMarkup(<OrderLineArtworkCompact organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView onOpen={() => undefined} />);
assert.match(compact, /front\.pdf|3 files/);
assert.match(compact, /\/v2\/organizations\/org-a\/artwork\/files\/file-front\/content/);
assert.doesNotMatch(compact, /other\.pdf|assignment-front|object_key|storageProvider/);
const detail = renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView canAdopt={false} uploadTarget={{ orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" }} onOpen={() => undefined} />);
assert.match(detail, /front\.pdf.*customer supplied · front/s);
assert.match(detail, /back\.pdf.*customer supplied · back/s);
assert.match(detail, /additional\.pdf.*customer supplied · front/s);
assert.doesNotMatch(detail, /Upload Artwork|Remove Artwork/, "canonical commercial presentation remains read-only");
assert.doesNotMatch(detail, /Select (an? )?line/i, "expanded-line upload must not need a second line picker");
assert.deepEqual(lineArtworkUploadTarget("order-a", "ORD-1", { lineId: "line-a", description: "Banner", position: 1 }), { orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" });
assert.doesNotMatch(detail, /other\.pdf|assignment-front/);
const viewOnlyDetail = renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView uploadTarget={{ orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" }} onOpen={() => undefined} />);
assert.match(viewOnlyDetail, /front\.pdf/);
assert.doesNotMatch(viewOnlyDetail, /Upload Artwork/, "view-only staff must not receive a line upload action");
const adoptionOnlyDetail = renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView={false} canAdopt uploadTarget={{ orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" }} onOpen={() => undefined} onUploaded={() => undefined} />);
assert.match(adoptionOnlyDetail, /Upload Artwork/);
assert.doesNotMatch(adoptionOnlyDetail, /front\.pdf|back\.pdf/, "staff without artwork.view must receive no Artwork data");
const ownerDetail = renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-a" artwork={artwork} loading={false} canView canAdopt uploadTarget={{ orderId: "order-a", orderLineId: "line-a", orderNumber: "ORD-1", lineDescription: "Banner" }} onOpen={() => undefined} onUploaded={() => undefined} />);
assert.match(ownerDetail, /Upload Artwork/, "separate Artifact-owned workspaces retain their existing canonical adoption authority");
assert.match(renderToStaticMarkup(<OrderLineArtworkCompact organizationId="org-a" orderLineId="line-none" artwork={artwork} loading={false} canView onOpen={() => undefined} />), /No artwork/);
assert.match(renderToStaticMarkup(<OrderLineArtworkDetail organizationId="org-a" orderLineId="line-none" artwork={artwork} loading={false} canView onOpen={() => undefined} />), /No art assigned/);
assert.doesNotMatch(orderConfigurationPresentation({ selections: { opt_old: "choice_old", print_sides__import_x: "yes" } }), /opt_|choice_|_import/);
const workspace = await readFile(new URL("./OrderWorkspace.tsx", import.meta.url), "utf8");
assert.match(workspace, /onOpen=\{\(\) => setEditingLineId\(line\.lineId\)\}/, "Items Artwork status must select its line rather than navigate to the Order-wide Artwork tab");
assert.match(workspace, /canAdopt=\{false\}/, "canonical line detail cannot upload before entering TEMP");
assert.match(workspace, /canUpload=\{false\}/, "canonical Order-wide Artwork is read-only");
assert.doesNotMatch(workspace, /artworkUploaded|cacheOrderArtworkUpload|cacheOrderArtworkRemoval|artworkRemoval=|orderApi\.patch/);
const temporary = await readFile(new URL("./TransactionalSalesWorkspace.tsx", import.meta.url), "utf8");
assert.match(temporary, /client\.stageIntent/);
assert.match(temporary, /client\.uploadArtwork/);
assert.match(temporary, /client\.removeArtwork/);
Object.assign(globalThis, { React });
const cache = new QueryClient();
const order: OrderRead = { order: { organizationId: "org-a", orderId: "order-a", customerContact: { organizationId: "org-a", customerId: "customer-a" }, terms: {}, currency: "USD", commercialState: "open", lines: [{ lineId: "line-a", productId: "product-a", description: "Banner", quantity: 2, position: 1, resolvedConfiguration: {}, calculatedUnitAmount: { cents: 5000, currency: "USD" }, calculatedLineAmount: { cents: 10000, currency: "USD" }, sellingUnitAmount: { cents: 5000, currency: "USD" }, sellingLineAmount: { cents: 10000, currency: "USD" }, sellingPriceDecision: { kind: "calculated" } }] }, number: { display: "ORD-1", core: "1" }, revision: "7", totals: { calculated: { cents: 10000, currency: "USD" }, selling: { cents: 10000, currency: "USD" } }, routes: [], completionEligibility: { eligible: false, blockers: [], lines: [] } };
cache.setQueryData(salesKeys.order("scope-a", "org-a", "order-a"), order);
cache.setQueryData(orderArtworkKey("scope-a", "org-a", "order-a"), artwork);
const client = createSalesWorkspaceClient({ request: async () => { throw new Error("Canonical Artwork presentation must not issue commands"); }, commandHeaders: () => ({ "x-v2-csrf-token": "test-csrf" }) });
const canonical = renderToStaticMarkup(<QueryClientProvider client={cache}><OrderWorkspace organizationId="org-a" sessionScope="scope-a" userId="user-a" orderId="order-a" workspaceClient={client} workspaceCapabilities={{ quoteCreate: false, orderCreate: false, quoteOverridePrice: false, orderView: true, orderEdit: true, artworkView: true, artworkAdopt: true, artworkAssign: true }} canEdit canCreate={false} canCancel={false} canOverridePrice={false} canViewInvoice={false} canViewArtwork canAdoptArtwork canRemoveArtwork canViewProofing={false} canViewProduction={false} csrfReady onBack={() => undefined} /></QueryClientProvider>);
assert.match(canonical, /<button class="button" type="button">Edit Order<\/button>/);
assert.doesNotMatch(canonical, /Upload Artwork|Remove Artwork|>Save<\/button>|input[^>]*type="file"/, "even full Artifact permissions cannot create an immediate commercial mutation in the Order pane");
console.log("Saved Order line Artwork presentation tests passed.");
