import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { newBusinessRequestId, organizationSettingsApi, type ApiError, type OrganizationAddress, type OrganizationSettings } from "./api";

type Section = "business" | "documents";
type Profile = Readonly<{ displayName: string; legalName: string; phone: string; email: string; website: string; timeZone: string; currency: string; businessAddress: OrganizationAddress }>;
type Documents = Readonly<{ footerNote: string; paymentInstructions: string; checksPayableTo: string; remittanceAddress: OrganizationAddress }>;
const emptyAddress = (): OrganizationAddress => ({ line1: "", line2: "", city: "", region: "", postalCode: "", country: "" });
const profileOf = (value: OrganizationSettings): Profile => ({ ...value.businessProfile, legalName: value.businessProfile.legalName ?? "", phone: value.businessProfile.phone ?? "", email: value.businessProfile.email ?? "", website: value.businessProfile.website ?? "", timeZone: value.businessProfile.timeZone ?? "", currency: value.businessProfile.currency ?? "", businessAddress: value.businessProfile.businessAddress ?? emptyAddress() });
const documentsOf = (value: OrganizationSettings): Documents => ({ footerNote: value.documentsBranding.footerNote ?? "", paymentInstructions: value.documentsBranding.paymentInstructions ?? "", checksPayableTo: value.documentsBranding.checksPayableTo ?? "", remittanceAddress: value.documentsBranding.remittanceAddress ?? emptyAddress() });

export const OrganizationSettingsWorkspace = ({ organizationId, sessionScope, canConfigure, section }: Readonly<{ organizationId: string; sessionScope: string; canConfigure: boolean; section: Section }>) => {
  const client = useQueryClient(); const key = ["v2", sessionScope, organizationId, "settings", "organization"] as const;
  const [profile, setProfile] = useState<Profile>({ displayName: "", legalName: "", phone: "", email: "", website: "", timeZone: "", currency: "", businessAddress: emptyAddress() });
  const [documents, setDocuments] = useState<Documents>({ footerNote: "", paymentInstructions: "", checksPayableTo: "", remittanceAddress: emptyAddress() }); const [notice, setNotice] = useState("");
  const query = useQuery({ queryKey: key, queryFn: () => organizationSettingsApi.get(organizationId), enabled: Boolean(organizationId && sessionScope && canConfigure) });
  useEffect(() => { if (query.data) { setProfile(profileOf(query.data)); setDocuments(documentsOf(query.data)); } }, [query.data?.revision]);
  const saveProfile = useMutation({ mutationFn: () => organizationSettingsApi.saveBusinessProfile(organizationId, newBusinessRequestId(), { expectedRevision: query.data!.revision, ...profile }), onSuccess: (value) => { client.setQueryData(key, value); setNotice("Business profile saved."); }, onError: (error) => setNotice((error as unknown as ApiError).message ?? "Business profile could not be saved.") });
  const saveDocuments = useMutation({ mutationFn: () => organizationSettingsApi.saveDocumentsBranding(organizationId, newBusinessRequestId(), { expectedRevision: query.data!.revision, ...documents }), onSuccess: (value) => { client.setQueryData(key, value); setNotice("Document settings saved."); }, onError: (error) => setNotice((error as unknown as ApiError).message ?? "Document settings could not be saved.") });
  if (!canConfigure) return <section className="v2-settings-future"><h2>{section === "business" ? "Business Profile" : "Documents & Branding"}</h2><p>You do not have permission to configure Organization settings.</p></section>;
  if (query.isLoading) return <p>Loading Organization settings…</p>;
  const heading = section === "business" ? "Business Profile" : "Documents & Branding";
  return <section className="v2-settings-form"><header><small>SETTINGS · ORGANIZATION</small><h1>{heading}</h1><p>{section === "business" ? "Customer-facing organization identity and the canonical Pickup address." : "Text facts rendered into customer documents. Business identity itself remains owned by Business Profile."}</p></header>
    {section === "business" ? <><section className="v2-settings-form-card"><h2>Business identity</h2><div className="v2-settings-fields"><Text label="Display name" value={profile.displayName} onChange={(displayName) => setProfile({ ...profile, displayName })}/><Text label="Legal name" value={profile.legalName} onChange={(legalName) => setProfile({ ...profile, legalName })}/><Text label="Phone" value={profile.phone} onChange={(phone) => setProfile({ ...profile, phone })}/><Text label="Business email" value={profile.email} onChange={(email) => setProfile({ ...profile, email })}/><Text label="Website" value={profile.website} onChange={(website) => setProfile({ ...profile, website })}/><Text label="Time zone" value={profile.timeZone} onChange={(timeZone) => setProfile({ ...profile, timeZone })}/><Text label="Currency" value={profile.currency} onChange={(currency) => setProfile({ ...profile, currency })}/></div></section><Address title="Business address" value={profile.businessAddress} onChange={(businessAddress) => setProfile({ ...profile, businessAddress })}/><button className="button" type="button" disabled={saveProfile.isPending || !query.data} onClick={() => { setNotice(""); saveProfile.mutate(); }}>{saveProfile.isPending ? "Saving…" : "Save Business Profile"}</button></> : <><section className="v2-settings-form-card"><h2>Logo</h2><p className="v2-settings-muted">Status: {query.data?.documentsBranding.logo.status === "configured" ? "Configured" : "Not configured"}</p><div className="v2-settings-row-actions"><button type="button" disabled>Replace logo</button><button type="button" disabled>Remove logo</button></div><p className="v2-settings-muted">A tenant-owned, private document-asset adoption contract is not available yet. Artwork intake is Order-line PDF-only and is not used for organization branding.</p></section><section className="v2-settings-form-card"><h2>Document identity</h2><Text label="Document footer" value={documents.footerNote} multiline onChange={(footerNote) => setDocuments({ ...documents, footerNote })}/><Text label="Payment instructions" value={documents.paymentInstructions} multiline onChange={(paymentInstructions) => setDocuments({ ...documents, paymentInstructions })}/><Text label="Checks payable to" value={documents.checksPayableTo} onChange={(checksPayableTo) => setDocuments({ ...documents, checksPayableTo })}/></section><Address title="Remittance address" value={documents.remittanceAddress} onChange={(remittanceAddress) => setDocuments({ ...documents, remittanceAddress })}/><button className="button" type="button" disabled={saveDocuments.isPending || !query.data} onClick={() => { setNotice(""); saveDocuments.mutate(); }}>{saveDocuments.isPending ? "Saving…" : "Save Document Settings"}</button></>}
    {notice && <p className={notice.includes("saved") ? "notice" : "notice error"}>{notice}</p>}
  </section>;
};
const Text = ({ label, value, onChange, multiline = false }: Readonly<{ label: string; value: string; onChange: (value: string) => void; multiline?: boolean }>) => <label className="field">{label}{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} /> : <input value={value} onChange={(event) => onChange(event.target.value)} />}</label>;
const Address = ({ title, value, onChange }: Readonly<{ title: string; value: OrganizationAddress; onChange: (value: OrganizationAddress) => void }>) => <section className="v2-settings-form-card"><h2>{title}</h2><div className="v2-settings-fields"><Text label="Address line 1" value={value.line1 ?? ""} onChange={(line1) => onChange({ ...value, line1 })}/><Text label="Address line 2" value={value.line2 ?? ""} onChange={(line2) => onChange({ ...value, line2 })}/><Text label="City" value={value.city ?? ""} onChange={(city) => onChange({ ...value, city })}/><Text label="Region" value={value.region ?? ""} onChange={(region) => onChange({ ...value, region })}/><Text label="Postal code" value={value.postalCode ?? ""} onChange={(postalCode) => onChange({ ...value, postalCode })}/><Text label="Country" value={value.country ?? ""} onChange={(country) => onChange({ ...value, country })}/></div></section>;
