import React, { useEffect, useMemo, useState } from "react";
import { Elements, PaymentElement, useElements, useStripe } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
import { useQuery } from "@tanstack/react-query";
import "./portal.css";

type Money = Readonly<{ cents: number; currency: string }>;
type Session = Readonly<{ portal: Readonly<{ displayName: string; customerId: string }>; returnTo: string; csrfToken: string; sessionScope: string }>;
type OrderSummary = Readonly<{ orderId: string; number: string; purchaseOrderNumber?: string; createdAt: string; requestedDueDate?: string; status: "open" | "completed" | "cancelled"; total: Money; payment: "unbilled" | "open_balance" | "settled"; fulfillment: "not_required" | "required" | "partial" | "fulfilled" }>;
type OrderDetail = OrderSummary & Readonly<{ lines: readonly Readonly<{ lineId: string; description: string; quantity: number; unitPrice: Money; lineTotal: Money }>[]; shipments: readonly Readonly<{ shipmentId: string; status: "prepared" | "shipped"; carrier?: string; service?: string; trackingNumber?: string; shippedAt?: string; quantity: number }>[] }>;
type QuoteSummary = Readonly<{ quoteId: string; number: string; createdAt: string; requestedDueDate?: string; status: string; total: Money; convertedOrderId?: string }>;
type QuoteDetail = QuoteSummary & Readonly<{ lines: readonly Readonly<{ lineId: string; description: string; quantity: number; unitPrice: Money; lineTotal: Money }>[] }>;
type OrdersDashboard = Readonly<{ recentOrders: readonly OrderSummary[]; currentOrderCount: number; historicalOrderCount: number; openBalanceOrderCount: number }>;
type PortalProof = Readonly<{ proofVersionId: string; orderNumber: string; lineDescription: string; revision: number; issuedAt: string; status: "awaiting_response" | "approved" | "revision_requested" | "superseded"; actionable: boolean; response?: Readonly<{ outcome: string; comment?: string; respondedAt: string }>; artifacts: readonly Readonly<{ artworkFileId: string; filename: string; contentType: string; viewUrl: string }>[] }>;
type CatalogItem = Readonly<{ productId: string; displayName: string; requiresDimensions: boolean; currency: string }>;
type PortalInvoice = Readonly<{ invoiceId: string; sourceOrderNumber?: string; settlement?: string; lifecycle?: string; balance: Money }>;
/**
 * Required canonical aggregate checkout contract (M7.5I-C):
 * POST /v2/portal/payments/stripe/payment-intents
 * { businessRequestId, allocations: [{ invoiceId, amountCents }] }
 * → one PaymentIntent plus server-validated allocation evidence. The browser
 * never supplies a total, Customer, organization, or provider identity. The
 * browser never loops the legacy per-Invoice endpoint.
 */

const request = async <T,>(path: string, init?: RequestInit): Promise<T> => {
  const response = await fetch(path, { credentials: "include", ...init, headers: { "content-type": "application/json", ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => null);
  if (!response.ok) throw Object.assign(new Error(body?.error?.message ?? "Request failed."), { status: response.status });
  return body.data as T;
};
const uploadPortalArtwork = async (path: string, csrfToken: string, file: File): Promise<void> => {
  const body = new FormData();
  body.append("businessRequestId", id());
  body.append("file", file);
  const response = await fetch(path, { method: "POST", credentials: "include", headers: { "x-v2-csrf-token": csrfToken }, body });
  const payload = await response.json().catch(() => null);
  if (!response.ok) throw new Error(payload?.error?.message ?? "Artwork could not be uploaded.");
};
const money = (value: Money) => new Intl.NumberFormat("en-US", { style: "currency", currency: value.currency }).format(value.cents / 100);
const decimalCents = (cents: number) => `${Math.floor(cents / 100)}.${String(cents % 100).padStart(2, "0")}`;
const inputCents = (value: string): number | null => {
  const match = /^(\d+)(?:\.(\d{1,2}))?$/u.exec(value.trim());
  if (!match) return null;
  const cents = Number(`${match[1]}${(match[2] ?? "").padEnd(2, "0")}`);
  return Number.isSafeInteger(cents) && cents > 0 ? cents : null;
};
const date = (value?: string) => value ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(value)) : "—";
const id = () => crypto.randomUUID();
const locationPath = () => window.location.pathname;
const routeId = (section: "orders" | "quotes" | "invoices" | "proofs") => locationPath().match(new RegExp(`^/portal/${section}/([A-Za-z0-9_-]+)$`))?.[1] ?? null;
const safeReturnTo = () => {
  const value = new URLSearchParams(window.location.search).get("returnTo") ?? "/portal";
  return /^\/portal\/(?:orders|quotes|proofs|invoices|catalog)(?:\/[A-Za-z0-9_-]+)?$/u.test(value) || value === "/portal" ? value : "/portal";
};
/** Portal reads share the application QueryClient. The authenticated session
 * scope prevents a completed customer session from reusing another account's
 * cached projection after an in-browser identity change. */
const usePortalQuery = <T,>(sessionScope: string, resource: readonly string[], queryFn: () => Promise<T>, enabled = true) => useQuery({
  queryKey: ["v2", "portal", sessionScope, ...resource],
  queryFn,
  enabled: Boolean(sessionScope) && enabled,
});

const status = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());
const Badge = ({ children, tone }: Readonly<{ children: string; tone?: "warning" | "success" | "danger" }>) => <span className={`portal-badge${tone ? ` ${tone}` : ""}`}>{children}</span>;
const Notice = ({ children, tone = "info" }: Readonly<{ children: React.ReactNode; tone?: "info" | "warning" | "success" }>) => <div className={`portal-notice ${tone}`}>{children}</div>;
const Empty = ({ title, children }: Readonly<{ title: string; children: React.ReactNode }>) => <div className="portal-empty"><strong>{title}</strong><p>{children}</p></div>;
const Loading = () => <div className="portal-loading" aria-live="polite">Loading your account…</div>;

const CredentialCard = ({ title, children }: Readonly<{ title: string; children: React.ReactNode }>) => <main className="portal-auth"><section><p className="portal-kicker">PrintersHero</p><h1>{title}</h1>{children}</section></main>;
const PasswordField = ({ id: fieldId, label, value, onChange, autoComplete, minLength }: Readonly<{ id: string; label: string; value: string; onChange: (value: string) => void; autoComplete: "new-password" | "current-password"; minLength?: number }>) => {
  const [visible, setVisible] = useState(false);
  return <label>{label}<div className="portal-password"><input id={fieldId} type={visible ? "text" : "password"} autoComplete={autoComplete} value={value} onChange={(event) => onChange(event.target.value)} minLength={minLength} required /><button type="button" onClick={() => setVisible((current) => !current)} aria-pressed={visible}>{visible ? "Hide password" : "Show password"}</button></div></label>;
};

const SignIn = ({ destination, onSession }: Readonly<{ destination: string; onSession: (session: Session) => void }>) => {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const next = await request<Session>("/v2/portal/auth/login", { method: "POST", body: JSON.stringify({ email, password, returnTo: destination }) }); onSession(next); history.replaceState(null, "", next.returnTo); } catch (reason) { setError(reason instanceof Error ? reason.message : "Sign in failed."); } finally { setBusy(false); } };
  return <CredentialCard title="Customer portal"><p>Sign in to view your print work, invoices, proofs, and approved catalog.</p><form onSubmit={submit}><label>Email<input type="email" autoComplete="username" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><PasswordField id="portal-current-password" label="Password" autoComplete="current-password" value={password} onChange={setPassword} />{error && <Notice tone="warning">{error}</Notice>}<button className="portal-primary" disabled={busy}>{busy ? "Signing in…" : "Sign in"}</button></form><a href="/portal/forgot-password">Forgot password?</a></CredentialCard>;
};

const PortalSetup = ({ kind }: Readonly<{ kind: "setup" | "reset" }>) => {
  const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState(""); const [complete, setComplete] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (password !== confirmation) return setError("Passwords do not match."); try { await request(`/v2/portal/auth/${kind === "setup" ? "setup" : "reset-password"}`, { method: "POST", body: JSON.stringify({ token: new URLSearchParams(window.location.search).get("token") ?? "", password }) }); setComplete(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "This link is unavailable."); } };
  if (complete) return <CredentialCard title={kind === "setup" ? "Account ready" : "Password updated"}><p>Your secure portal access is ready.</p><a className="portal-primary" href={kind === "setup" ? safeReturnTo() : "/portal"}>Sign in</a></CredentialCard>;
  return <CredentialCard title={kind === "setup" ? "Create your portal account" : "Set a new password"}><p>{kind === "setup" ? "Choose a secure password for your customer portal." : "Choose a new password for your secure customer portal."}</p><form onSubmit={submit}><PasswordField id="portal-new-password" label="Password" autoComplete="new-password" value={password} onChange={setPassword} minLength={12} /><PasswordField id="portal-confirm-new-password" label="Confirm password" autoComplete="new-password" value={confirmation} onChange={setConfirmation} minLength={12} />{error && <Notice tone="warning">{error}</Notice>}<button className="portal-primary">{kind === "setup" ? "Create account" : "Update password"}</button></form></CredentialCard>;
};

const ForgotPassword = () => {
  const [email, setEmail] = useState(""); const [submitted, setSubmitted] = useState(false);
  return <CredentialCard title="Reset your password"><p>Enter your email and we will send reset instructions if it belongs to an eligible customer portal account.</p>{submitted ? <Notice>If eligible, password-reset instructions have been sent.</Notice> : <form onSubmit={async (event) => { event.preventDefault(); await request("/v2/portal/auth/forgot-password", { method: "POST", body: JSON.stringify({ email }) }).catch(() => undefined); setSubmitted(true); }}><label>Email<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><button className="portal-primary">Send reset instructions</button></form>}<a href="/portal">Back to sign in</a></CredentialCard>;
};

const NAV = [
  ["/portal", "Home"], ["/portal/orders", "Orders"], ["/portal/catalog", "Shop"], ["/portal/quotes", "Quotes"], ["/portal/proofs", "Proofs"], ["/portal/invoices", "Invoices"], ["/portal/account", "Account"],
] as const;

const Shell = ({ session, children }: Readonly<{ session: Session; children: React.ReactNode }>) => {
  const [open, setOpen] = useState(false); const current = locationPath();
  const active = (target: string) => target === "/portal" ? current === target : current.startsWith(target);
  return <div className="portal-shell"><header className="portal-header"><a className="portal-brand" href="/portal"><span>PH</span><strong>PrintersHero<small>{session.portal.displayName}</small></strong></a><nav className="portal-main-nav" aria-label="Portal navigation">{NAV.map(([href, label]) => <a key={href} href={href} aria-current={active(href) ? "page" : undefined}>{label}</a>)}</nav><div className="portal-header-actions"><a className="portal-quiet portal-new-order" href="/portal/catalog">Start new order</a><button className="portal-menu" onClick={() => setOpen((currentOpen) => !currentOpen)} aria-expanded={open} aria-controls="portal-mobile-nav">{open ? "Close" : "Menu"}</button></div></header>{open && <nav id="portal-mobile-nav" className="portal-mobile-nav">{NAV.map(([href, label]) => <a key={href} href={href}>{label}</a>)}</nav>}<main className="portal-page">{children}</main><nav className="portal-bottom-nav" aria-label="Portal shortcuts">{NAV.filter(([, label]) => label !== "Quotes" && label !== "Account").map(([href, label]) => <a key={href} href={href} aria-current={active(href) ? "page" : undefined}>{label}</a>)}</nav></div>;
};

const PageHeader = ({ title, description, actions }: Readonly<{ title: string; description: string; actions?: React.ReactNode }>) => <header className="portal-page-header"><div><h1>{title}</h1><p>{description}</p></div>{actions && <div className="portal-page-actions">{actions}</div>}</header>;
const Section = ({ title, action, children, className = "" }: Readonly<{ title?: string; action?: React.ReactNode; children: React.ReactNode; className?: string }>) => <section className={`portal-section ${className}`}><>{title && <header><h2>{title}</h2>{action}</header>}</>{children}</section>;

const Home = ({ session }: Readonly<{ session: Session }>) => {
  const orders = usePortalQuery(session.sessionScope, ["orders", "dashboard"], () => request<OrdersDashboard>("/v2/portal/orders/dashboard"));
  const proofs = usePortalQuery(session.sessionScope, ["proofs"], () => request<{ items: readonly PortalProof[] }>("/v2/portal/proofs"));
  const invoices = usePortalQuery(session.sessionScope, ["invoices"], () => request<{ items: any[] }>("/v2/portal/invoices"));
  if (orders.isPending || proofs.isPending || invoices.isPending) return <Loading />;
  const activeOrders = orders.data?.recentOrders ?? []; const actionableProofs = (proofs.data?.items ?? []).filter((proof) => proof.actionable); const openInvoices = (invoices.data?.items ?? []).filter((invoice) => Number(invoice.balance?.cents ?? 0) > 0); const error = orders.error ?? proofs.error ?? invoices.error;
  return <><PageHeader title={`Welcome back, ${session.portal.displayName}`} description="Here is what needs your attention today." actions={<><a className="portal-quiet" href="/portal/catalog">Browse products</a><a className="portal-primary" href="/portal/catalog">Start new order</a></>} />{error && <Notice tone="warning">{error instanceof Error ? error.message : "Your dashboard could not be loaded."}</Notice>}<div className="portal-stat-grid"><Stat label="Orders in progress" value={String(orders.data?.currentOrderCount ?? 0)} hint="Received through fulfillment" /><Stat label="Proofs to approve" value={String(actionableProofs.length)} hint={actionableProofs.length ? "Production is waiting" : "Nothing waiting on you"} tone={actionableProofs.length ? "warning" : undefined} /><Stat label="Open balance" value={money(openInvoices.reduce<Money>((total, invoice) => ({ cents: total.cents + Number(invoice.balance?.cents ?? 0), currency: total.currency }), { cents: 0, currency: "USD" }))} hint={`${orders.data?.openBalanceOrderCount ?? 0} order${orders.data?.openBalanceOrderCount === 1 ? "" : "s"} with a balance`} /></div><div className="portal-dashboard-grid"><div className="portal-dashboard-primary"><Section title="Proofs needing attention" action={<a href="/portal/proofs">All proofs</a>}>{actionableProofs.length ? <List>{actionableProofs.slice(0, 4).map((proof) => <a key={proof.proofVersionId} href={`/portal/proofs/${encodeURIComponent(proof.proofVersionId)}`}><div><strong>{proof.orderNumber}</strong><small>{proof.lineDescription} · Version {proof.revision}</small></div><Badge tone="warning">Action required</Badge></a>)}</List> : <Empty title="No proofs are waiting on you">We will email you when a new proof is ready.</Empty>}</Section><Section title="Orders in progress" action={<a href="/portal/orders">All orders</a>}>{activeOrders.length ? <List>{activeOrders.map((order) => <OrderRow key={order.orderId} order={order} />)}</List> : <Empty title="No orders in progress">Your completed orders stay available under Orders.</Empty>}</Section></div><div><Section title="Open invoices" action={<a className="portal-primary compact" href="/portal/invoices">Pay</a>}>{openInvoices.length ? <List>{openInvoices.slice(0, 4).map((invoice) => <a key={invoice.invoiceId} href={`/portal/invoices/${encodeURIComponent(invoice.invoiceId)}`}><div><strong>{invoice.sourceOrderNumber ?? "Invoice"}</strong><small>Balance due</small></div><strong>{money(invoice.balance)}</strong></a>)}</List> : <Empty title="You are all paid up">Nothing is currently outstanding.</Empty>}</Section></div></div></>;
};
const Stat = ({ label, value, hint, tone }: Readonly<{ label: string; value: string; hint: string; tone?: "warning" }>) => <article className={`portal-stat ${tone ?? ""}`}><small>{label}</small><strong>{value}</strong><span>{hint}</span></article>;
const List = ({ children }: Readonly<{ children: React.ReactNode }>) => <div className="portal-list">{children}</div>;
const OrderRow = ({ order }: Readonly<{ order: OrderSummary }>) => <a href={`/portal/orders/${encodeURIComponent(order.orderId)}`}><div><strong>{order.number}{order.purchaseOrderNumber ? ` · PO ${order.purchaseOrderNumber}` : ""}</strong><small>Placed {date(order.createdAt)}{order.requestedDueDate ? ` · Due ${date(order.requestedDueDate)}` : ""}</small></div><div className="portal-row-summary"><Badge>{status(order.fulfillment)}</Badge><strong>{money(order.total)}</strong></div></a>;

const Orders = () => {
  const [items, setItems] = useState<readonly OrderSummary[] | null>(null); const [query, setQuery] = useState(""); const [tab, setTab] = useState<"current" | "history">("current"); const [error, setError] = useState("");
  useEffect(() => { void request<{ items: readonly OrderSummary[] }>("/v2/portal/orders").then((result) => setItems(result.items)).catch((reason) => setError(reason instanceof Error ? reason.message : "Orders are unavailable.")); }, []);
  if (!items && !error) return <Loading />; const filtered = (items ?? []).filter((order) => (tab === "current" ? order.status === "open" : order.status !== "open") && `${order.number} ${order.purchaseOrderNumber ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader title="Orders" description="Search current and historical print work by order number or PO." actions={<a className="portal-primary" href="/portal/catalog">Start new order</a>} /><div className="portal-toolbar"><div className="portal-tabs"><button className={tab === "current" ? "active" : ""} onClick={() => setTab("current")}>Current</button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}>History</button></div><input aria-label="Search orders" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Order number or PO" /></div>{error && <Notice tone="warning">{error}</Notice>}<Section>{filtered.length ? <List>{filtered.map((order) => <OrderRow key={order.orderId} order={order} />)}</List> : <Empty title={tab === "current" ? "No orders in progress" : "No past orders yet"}>When you place an order it appears here with live status and tracking.</Empty>}</Section></>;
};

const OrderDetailPage = ({ orderId, csrfToken }: Readonly<{ orderId: string; csrfToken: string }>) => {
  const [order, setOrder] = useState<OrderDetail | null>(null); const [error, setError] = useState(""); const [uploadingLineId, setUploadingLineId] = useState<string | null>(null); const [uploadNotice, setUploadNotice] = useState("");
  const refresh = async () => { try { setOrder(await request<OrderDetail>(`/v2/portal/orders/${encodeURIComponent(orderId)}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : "This Order could not be opened."); } };
  useEffect(() => { void refresh(); }, [orderId]);
  const upload = async (lineId: string, file?: File) => { if (!file) return; setUploadingLineId(lineId); setUploadNotice(""); setError(""); try { await uploadPortalArtwork(`/v2/portal/orders/${encodeURIComponent(orderId)}/lines/${encodeURIComponent(lineId)}/artwork`, csrfToken, file); setUploadNotice("Your source artwork was uploaded for the team to review."); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Artwork could not be uploaded."); } finally { setUploadingLineId(null); } };
  if (!order && !error) return <Loading />; if (!order) return <><PageHeader title="Order not available" description="We could not open this Order." actions={<a className="portal-quiet" href="/portal/orders">All orders</a>} /><Notice tone="warning">{error}</Notice></>;
  return <><PageHeader title={order.number} description={`Placed ${date(order.createdAt)}${order.purchaseOrderNumber ? ` · PO ${order.purchaseOrderNumber}` : ""}${order.requestedDueDate ? ` · Due ${date(order.requestedDueDate)}` : ""}`} actions={<a className="portal-quiet" href="/portal/orders">All orders</a>} />{uploadNotice && <Notice tone="success">{uploadNotice}</Notice>}{error && <Notice tone="warning">{error}</Notice>}<div className="portal-detail-grid"><div><Section title="Order summary"><dl className="portal-facts"><div><dt>Status</dt><dd><Badge>{status(order.status)}</Badge></dd></div><div><dt>Fulfillment</dt><dd><Badge>{status(order.fulfillment)}</Badge></dd></div><div><dt>Order total</dt><dd>{money(order.total)}</dd></div><div><dt>Payment</dt><dd>{status(order.payment)}</dd></div></dl></Section><Section title="Items">{order.lines.map((line) => <article className="portal-line portal-line-artwork" key={line.lineId}><div><strong>{line.description}</strong><small>Quantity {line.quantity.toLocaleString()} · {money(line.unitPrice)} each</small><label className="portal-artwork-upload">Add source artwork (PDF)<input type="file" accept="application/pdf" disabled={uploadingLineId === line.lineId} onChange={(event) => { void upload(line.lineId, event.currentTarget.files?.[0]); event.currentTarget.value = ""; }} /></label></div><strong>{money(line.lineTotal)}</strong></article>)}</Section><Section title="Shipments & pickup">{order.shipments.length ? <div className="portal-shipment-list">{order.shipments.map((shipment) => <article key={shipment.shipmentId}><div><strong>{shipment.carrier ?? (shipment.status === "shipped" ? "Shipment" : "Preparing shipment")}</strong><small>{shipment.service ?? ""}{shipment.trackingNumber ? ` · ${shipment.trackingNumber}` : ""}{shipment.shippedAt ? ` · Shipped ${date(shipment.shippedAt)}` : ""}</small></div><Badge tone={shipment.status === "shipped" ? "success" : undefined}>{status(shipment.status)}</Badge></article>)}</div> : <Empty title="Nothing has shipped yet">Tracking appears here for each shipment, including partial shipments.</Empty>}</Section></div><aside><Section title="Need help?"><p className="portal-muted">Your account representative can help with changes to your order.</p></Section></aside></div></>;
};

const Quotes = () => {
  const [items, setItems] = useState<readonly QuoteSummary[] | null>(null); const [error, setError] = useState("");
  useEffect(() => { void request<{ items: readonly QuoteSummary[] }>("/v2/portal/quotes").then((result) => setItems(result.items)).catch((reason) => setError(reason instanceof Error ? reason.message : "Quotes are unavailable.")); }, []);
  if (!items && !error) return <Loading />; const active = (items ?? []).filter((quote) => !quote.convertedOrderId); const history = (items ?? []).filter((quote) => Boolean(quote.convertedOrderId));
  return <><PageHeader title="Quotes" description="Pricing we have prepared for you." />{error && <Notice tone="warning">{error}</Notice>}<Section title={`Open quotes (${active.length})`}>{active.length ? <QuoteRows items={active} /> : <Empty title="No open quotes">Ask your account representative for a quote and it will appear here.</Empty>}</Section><Section title="Quote history"><>{history.length ? <QuoteRows items={history} /> : <Empty title="No past quotes yet">Accepted and converted quotes remain available here.</Empty>}</></Section></>;
};
const QuoteRows = ({ items }: Readonly<{ items: readonly QuoteSummary[] }>) => <List>{items.map((quote) => <a key={quote.quoteId} href={`/portal/quotes/${encodeURIComponent(quote.quoteId)}`}><div><strong>{quote.number}</strong><small>{date(quote.createdAt)}{quote.requestedDueDate ? ` · Due ${date(quote.requestedDueDate)}` : ""}</small></div><div className="portal-row-summary"><Badge>{status(quote.status)}</Badge><strong>{money(quote.total)}</strong></div></a>)}</List>;
const QuoteDetailPage = ({ quoteId }: Readonly<{ quoteId: string }>) => {
  const [quote, setQuote] = useState<QuoteDetail | null>(null); const [error, setError] = useState("");
  useEffect(() => { void request<QuoteDetail>(`/v2/portal/quotes/${encodeURIComponent(quoteId)}`).then(setQuote).catch((reason) => setError(reason instanceof Error ? reason.message : "This Quote could not be opened.")); }, [quoteId]);
  if (!quote && !error) return <Loading />; if (!quote) return <><PageHeader title="Quote not available" description="We could not open this Quote." /><Notice tone="warning">{error}</Notice></>;
  return <><PageHeader title={quote.number} description={`Prepared ${date(quote.createdAt)}${quote.requestedDueDate ? ` · Due ${date(quote.requestedDueDate)}` : ""}`} actions={<a className="portal-quiet" href="/portal/quotes">All quotes</a>} /><Section title="Quote details"><div className="portal-line-list">{quote.lines.map((line) => <article className="portal-line" key={line.lineId}><div><strong>{line.description}</strong><small>Quantity {line.quantity.toLocaleString()} · {money(line.unitPrice)} each</small></div><strong>{money(line.lineTotal)}</strong></article>)}</div><dl className="portal-total"><dt>Total</dt><dd>{money(quote.total)}</dd></dl></Section>{quote.convertedOrderId ? <Notice tone="success">This Quote was converted to an Order.</Notice> : <Notice>Quote acceptance is completed through your account representative until a canonical portal acceptance contract is available.</Notice>}</>;
};

const Proofs = () => {
  const [items, setItems] = useState<readonly PortalProof[] | null>(null); const [error, setError] = useState("");
  useEffect(() => { void request<{ items: readonly PortalProof[] }>("/v2/portal/proofs").then((result) => setItems(result.items)).catch((reason) => setError(reason instanceof Error ? reason.message : "Proofs are unavailable.")); }, []);
  if (!items && !error) return <Loading />; const waiting = (items ?? []).filter((proof) => proof.actionable); const history = (items ?? []).filter((proof) => !proof.actionable);
  return <><PageHeader title="Proofs" description="Review exact issued versions and let us know when they are ready." />{error && <Notice tone="warning">{error}</Notice>}<Section title={`Action required (${waiting.length})`}>{waiting.length ? <ProofRows items={waiting} /> : <Empty title="Nothing waiting on you">We will email you as soon as a proof is ready to review.</Empty>}</Section><Section title="Proof history">{history.length ? <ProofRows items={history} /> : <Empty title="No proof history yet">Issued proof versions remain available here.</Empty>}</Section></>;
};
const ProofRows = ({ items }: Readonly<{ items: readonly PortalProof[] }>) => <List>{items.map((proof) => <a key={proof.proofVersionId} href={`/portal/proofs/${encodeURIComponent(proof.proofVersionId)}`}><div><strong>{proof.orderNumber}</strong><small>{proof.lineDescription} · Version {proof.revision} · Issued {date(proof.issuedAt)}</small></div><Badge tone={proof.actionable ? "warning" : proof.status === "approved" ? "success" : undefined}>{proof.actionable ? "Action required" : status(proof.status)}</Badge></a>)}</List>;
const ProofDetailPage = ({ proofId, csrfToken }: Readonly<{ proofId: string; csrfToken: string }>) => {
  const [proof, setProof] = useState<PortalProof | null>(null); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const refresh = async () => { try { setProof(await request<PortalProof>(`/v2/portal/proofs/${encodeURIComponent(proofId)}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : "This proof could not be opened."); } };
  useEffect(() => { void refresh(); }, [proofId]); const respond = async (outcome: "approved" | "revision_requested") => { setBusy(true); setError(""); try { await request(`/v2/portal/proofs/${encodeURIComponent(proofId)}/respond`, { method: "POST", headers: { "x-v2-csrf-token": csrfToken }, body: JSON.stringify({ businessRequestId: id(), outcome, ...(comment.trim() ? { comment: comment.trim() } : {}) }) }); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Your response could not be recorded."); } finally { setBusy(false); } };
  if (!proof && !error) return <Loading />; if (!proof) return <><PageHeader title="Proof not available" description="We could not open this proof." /><Notice tone="warning">{error}</Notice></>;
  return <><PageHeader title={`Proof v${proof.revision}`} description={`Order ${proof.orderNumber} · ${proof.lineDescription}`} actions={<a className="portal-quiet" href="/portal/proofs">All proofs</a>} />{error && <Notice tone="warning">{error}</Notice>}<Section title="Issued artwork">{proof.artifacts.map((artifact) => <article className="portal-proof-artifact" key={artifact.artworkFileId}><strong>{artifact.filename}</strong>{artifact.contentType === "application/pdf" ? <iframe title={`Proof ${artifact.filename}`} src={artifact.viewUrl} /> : artifact.contentType.startsWith("image/") ? <img src={artifact.viewUrl} alt={`Proof ${artifact.filename}`} /> : <a className="portal-quiet" href={artifact.viewUrl} target="_blank" rel="noreferrer">Open proof file</a>}</article>)}</Section>{proof.response && <Notice tone={proof.response.outcome === "approved" ? "success" : "info"}>{proof.response.outcome === "approved" ? "Approved" : "Changes requested"}{proof.response.comment ? `: ${proof.response.comment}` : ""}</Notice>}{proof.actionable && <Section title="Your decision"><label>Comments (optional)<textarea value={comment} maxLength={8000} onChange={(event) => setComment(event.target.value)} /></label><div className="portal-actions"><button className="portal-primary" disabled={busy} onClick={() => void respond("approved")}>Approve proof</button><button className="portal-quiet" disabled={busy} onClick={() => void respond("revision_requested")}>Request changes</button></div></Section>}</>;
};

const Catalog = ({ csrfToken }: Readonly<{ csrfToken: string }>) => {
  const [items, setItems] = useState<readonly CatalogItem[] | null>(null); const [selectedId, setSelectedId] = useState(""); const [quantity, setQuantity] = useState("1"); const [width, setWidth] = useState(""); const [height, setHeight] = useState(""); const [preview, setPreview] = useState<Money | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void request<{ items: readonly CatalogItem[] }>("/v2/portal/catalog").then((result) => { setItems(result.items); setSelectedId(result.items[0]?.productId ?? ""); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Your catalog could not be loaded.")); }, []);
  const selected = items?.find((item) => item.productId === selectedId); const dimensions = selected?.requiresDimensions ? { width, height, unit: "in" as const } : undefined;
  const quote = async () => { if (!selected) return; const count = Number(quantity); if (!Number.isSafeInteger(count) || count <= 0) return setError("Enter a positive whole quantity."); if (selected.requiresDimensions && (!width.trim() || !height.trim())) return setError("Enter width and height for this Product."); setBusy(true); setError(""); try { const result = await request<{ lineAmount: Money }>(`/v2/portal/catalog/${encodeURIComponent(selected.productId)}/price-preview`, { method: "POST", headers: { "x-v2-csrf-token": csrfToken }, body: JSON.stringify({ quantity: count, ...(dimensions ? { dimensions } : {}) }) }); setPreview(result.lineAmount); } catch (reason) { setError(reason instanceof Error ? reason.message : "We could not price this configuration."); } finally { setBusy(false); } };
  const createOrder = async () => { if (!selected) return; const count = Number(quantity); if (!Number.isSafeInteger(count) || count <= 0) return setError("Enter a positive whole quantity."); setBusy(true); setError(""); setNotice(""); try { const result = await request<{ order: { order: { number?: { display?: string } } } }>("/v2/portal/orders", { method: "POST", headers: { "x-v2-csrf-token": csrfToken }, body: JSON.stringify({ businessRequestId: id(), lines: [{ productId: selected.productId, quantity: count, ...(dimensions ? { dimensions } : {}) }] }) }); setNotice(`Order ${result.order.order.number?.display ?? "created"} was created and is now available in Orders.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Your Order could not be created."); } finally { setBusy(false); } };
  if (!items && !error) return <Loading />;
  return <><PageHeader title="Shop" description="Products approved for your account, priced at your agreed rates." />{error && <Notice tone="warning">{error}</Notice>}{notice && <Notice tone="success">{notice}</Notice>}{!items?.length ? <Section><Empty title="No products are available">Contact your account representative if you need help ordering an item.</Empty></Section> : <div className="portal-catalog-grid"><section className="portal-catalog-items">{items.map((item) => <button key={item.productId} className={item.productId === selectedId ? "selected" : ""} onClick={() => { setSelectedId(item.productId); setPreview(null); }}><span className="portal-product-thumb">{item.displayName.slice(0, 2)}</span><strong>{item.displayName}</strong><small>Your approved price</small></button>)}</section><Section title={selected?.displayName ?? "Product"} className="portal-configure"><p className="portal-muted">Configure your Product and request the authoritative price from the server.</p><label>Quantity<input type="number" min="1" step="1" value={quantity} onChange={(event) => { setQuantity(event.target.value); setPreview(null); }} /></label>{selected?.requiresDimensions && <div className="portal-dimensions"><label>Width (in)<input inputMode="decimal" value={width} onChange={(event) => { setWidth(event.target.value); setPreview(null); }} /></label><label>Height (in)<input inputMode="decimal" value={height} onChange={(event) => { setHeight(event.target.value); setPreview(null); }} /></label></div>}<div className="portal-price"><small>Your price</small><strong>{preview ? money(preview) : "Request a price"}</strong><span>Pricing and eligibility are verified by PrintersHero.</span></div><div className="portal-actions"><button className="portal-quiet" disabled={busy} onClick={() => void quote()}>{busy ? "Checking…" : "Check price"}</button><button className="portal-primary" disabled={busy || !preview} onClick={() => void createOrder()}>{busy ? "Creating…" : "Create order"}</button></div><p className="portal-muted">Artwork upload and rich Product option configuration use the canonical controls in their next completed portal surface; this page does not invent a local configuration model.</p></Section></div>}</>;
};

const CardForm = ({ clientSecret, publishableKey, stripeAccountId, onDone, onError }: Readonly<{ clientSecret: string; publishableKey: string; stripeAccountId: string; onDone: () => void; onError: (message: string) => void }>) => { const stripePromise = useMemo(() => loadStripe(publishableKey, { stripeAccount: stripeAccountId }), [publishableKey, stripeAccountId]); return <Elements stripe={stripePromise} options={{ clientSecret }}><CardConfirmation onDone={onDone} onError={onError} /></Elements>; };
const CardConfirmation = ({ onDone, onError }: Readonly<{ onDone: () => void; onError: (message: string) => void }>) => { const stripe = useStripe(); const elements = useElements(); const [busy, setBusy] = useState(false); return <form onSubmit={async (event) => { event.preventDefault(); if (!stripe || !elements) return; setBusy(true); const result = await stripe.confirmPayment({ elements, redirect: "if_required" }); setBusy(false); if (result.error) return onError(result.error.message ?? "Card payment could not be confirmed."); onDone(); }}><PaymentElement /><button className="portal-primary" disabled={!stripe || busy}>{busy ? "Confirming…" : "Confirm card payment"}</button></form>; };

const MultiInvoiceReview = ({ rows, selections, onSelection, onBegin, busy }: Readonly<{ rows: readonly PortalInvoice[]; selections: Readonly<Record<string, string>>; onSelection: (next: Readonly<Record<string, string>>) => void; onBegin: (allocations: readonly Readonly<{ invoiceId: string; amountCents: number }>[]) => void; busy: boolean }>) => {
  const selected = rows.flatMap((invoice) => selections[invoice.invoiceId] === undefined ? [] : [{ invoice, amountCents: inputCents(selections[invoice.invoiceId] ?? "") }]);
  if (!selected.length) return null;
  const invalid = selected.some(({ invoice, amountCents }) => amountCents === null || amountCents > invoice.balance.cents);
  const currencies = new Set(selected.map(({ invoice }) => invoice.balance.currency)); const allocations = selected.flatMap(({ invoice, amountCents }) => amountCents === null ? [] : [{ invoiceId: invoice.invoiceId, amountCents }]);
  const total = allocations.reduce((sum, allocation) => sum + allocation.amountCents, 0); const currency = selected[0]?.invoice.balance.currency ?? "USD";
  const update = (invoiceId: string, value: string) => onSelection({ ...selections, [invoiceId]: value });
  return <Section title="Review one payment" className="portal-payment-review"><p className="portal-muted">Selected invoices are prepared as allocations for one payment transaction. The server will revalidate every amount and current balance before card checkout.</p><div className="portal-payment-allocations">{selected.map(({ invoice, amountCents }) => <label key={invoice.invoiceId}><span><strong>{invoice.sourceOrderNumber ?? "Invoice"}</strong><small>Current balance {money(invoice.balance)}</small></span><input aria-label={`Payment amount for ${invoice.sourceOrderNumber ?? "Invoice"}`} inputMode="decimal" value={selections[invoice.invoiceId] ?? ""} onChange={(event) => update(invoice.invoiceId, event.target.value)} />{amountCents !== null && <strong>{money({ cents: amountCents, currency: invoice.balance.currency })}</strong>}</label>)}</div>{invalid && <Notice tone="warning">Each allocation must be a positive amount no greater than its current Invoice balance.</Notice>}{currencies.size > 1 && <Notice tone="warning">Invoices in different currencies cannot be included in one card payment.</Notice>}<dl className="portal-total"><dt>One payment total</dt><dd>{money({ cents: total, currency })}</dd></dl><div className="portal-actions"><button className="portal-primary" disabled={busy || invalid || currencies.size > 1} onClick={() => onBegin(allocations)}>{busy ? "Preparing card payment…" : "Pay selected invoices"}</button></div></Section>;
};

const Invoices = ({ csrfToken }: Readonly<{ csrfToken: string }>) => {
  const invoiceId = routeId("invoices"); const [list, setList] = useState<Readonly<{ items: readonly PortalInvoice[] }> | null>(null); const [detail, setDetail] = useState<any | null>(null); const [error, setError] = useState(""); const [payment, setPayment] = useState<any | null>(null); const [paymentBusy, setPaymentBusy] = useState(false); const [selections, setSelections] = useState<Readonly<Record<string, string>>>({});
  const refresh = async () => { try { setError(""); if (invoiceId) setDetail(await request(`/v2/portal/invoices/${encodeURIComponent(invoiceId)}`)); else setList(await request<Readonly<{ items: readonly PortalInvoice[] }>>("/v2/portal/invoices")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Invoices are unavailable."); } };
  useEffect(() => { void refresh(); }, [invoiceId]); if ((!list && !detail) && !error) return <Loading />;
  if (!invoiceId) {
    const rows = list?.items ?? []; const eligible = (invoice: PortalInvoice) => invoice.balance.cents > 0 && invoice.lifecycle !== "void";
    const toggle = (invoice: PortalInvoice, checked: boolean) => setSelections((current) => { const next = { ...current }; if (checked) next[invoice.invoiceId] = decimalCents(invoice.balance.cents); else delete next[invoice.invoiceId]; return next; });
    const beginAggregate = async (allocations: readonly Readonly<{ invoiceId: string; amountCents: number }>[]) => { setPaymentBusy(true); try { setError(""); setPayment(await request("/v2/portal/payments/stripe/payment-intents", { method: "POST", headers: { "x-v2-csrf-token": csrfToken }, body: JSON.stringify({ businessRequestId: id(), allocations }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Card payment is unavailable."); } finally { setPaymentBusy(false); } };
    return <><PageHeader title="Invoices" description="View open and paid invoices, or review eligible balances as one payment." />{error && <Notice tone="warning">{error}</Notice>}<Section>{rows.length ? <><List>{rows.map((invoice) => <div className="portal-invoice-row" key={invoice.invoiceId}><label><input type="checkbox" checked={selections[invoice.invoiceId] !== undefined} disabled={!eligible(invoice)} onChange={(event) => toggle(invoice, event.target.checked)} aria-label={`Select ${invoice.sourceOrderNumber ?? "Invoice"}`} /><a href={`/portal/invoices/${encodeURIComponent(invoice.invoiceId)}`}><div><strong>{invoice.sourceOrderNumber ?? "Invoice"}</strong><small>{status(invoice.settlement ?? invoice.lifecycle ?? "unknown")}</small></div><strong>{money(invoice.balance)}</strong></a></label></div>)}</List><MultiInvoiceReview rows={rows.filter(eligible)} selections={selections} onSelection={setSelections} onBegin={(allocations) => void beginAggregate(allocations)} busy={paymentBusy || Boolean(payment)} />{payment && <Section title="Pay selected invoices"><p className="portal-muted">Your invoices update only after Stripe’s signed confirmation is received.</p><CardForm {...payment} onDone={() => { setPayment(null); setSelections({}); void refresh(); }} onError={setError} /></Section>}</> : <Empty title="No invoices yet">Your invoices and payment history will appear here.</Empty>}</Section></>;
  }
  if (!detail) return <><PageHeader title="Invoice not available" description="We could not open this Invoice." /><Notice tone="warning">{error}</Notice><a className="portal-quiet" href="/portal/invoices">Back to your invoices</a></>; const balance: Money = detail.settlement?.balance ?? { cents: 0, currency: detail.invoice?.currency ?? "USD" }; const payable = balance.cents > 0 && detail.invoice?.lifecycle !== "void"; const begin = async () => { try { setError(""); setPayment(await request(`/v2/portal/invoices/${encodeURIComponent(invoiceId)}/stripe/payment-intents`, { method: "POST", headers: { "x-v2-csrf-token": csrfToken }, body: JSON.stringify({ businessRequestId: id() }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Card payment is unavailable."); } };
  return <><PageHeader title={`Invoice ${detail.invoice.invoiceNumber?.display ?? detail.invoice.sourceOrderNumber ?? ""}`} description={detail.invoice.customerPresentation?.customerDisplayName ?? "Your invoice"} actions={<><a className="portal-quiet" href={`/v2/portal/invoices/${encodeURIComponent(invoiceId)}/document.pdf`} target="_blank" rel="noreferrer">View PDF</a>{payable && !payment && <button className="portal-primary" onClick={() => void begin()}>Pay by card</button>}</>} />{error && <Notice tone="warning">{error}</Notice>}<Section title="Invoice details">{detail.invoice.lines.map((line: any) => <article className="portal-line" key={line.sourceOrderLineId}><div><strong>{line.description}</strong><small>Quantity {line.quantity}</small></div><strong>{money(line.lineAmount)}</strong></article>)}<dl className="portal-total"><dt>Total</dt><dd>{money(detail.invoice.total)}</dd><dt>Amount due</dt><dd>{money({ ...balance, cents: Math.abs(balance.cents) })}</dd></dl></Section>{payment && <Section title="Pay invoice"><p className="portal-muted">Your invoice updates only after Stripe’s signed confirmation is received.</p><CardForm {...payment} onDone={() => { setPayment(null); void refresh(); }} onError={setError} /></Section>}<Section title="Payment history">{detail.history?.length ? detail.history.map((entry: any) => <p key={entry.id}>{entry.kind === "refund" ? "Refund" : "Payment"} · {money(entry.amount)}</p>) : <Empty title="No payments recorded">Payments will appear here after they are confirmed.</Empty>}</Section></>;
};

const Account = ({ session }: Readonly<{ session: Session }>) => <><PageHeader title="Account" description="Your portal access and account details." /><div className="portal-detail-grid"><Section title="Company"><dl className="portal-facts"><div><dt>Account</dt><dd>{session.portal.displayName}</dd></div><div><dt>Customer reference</dt><dd>{session.portal.customerId}</dd></div></dl><p className="portal-muted">Contact your account representative if company information, addresses, or terms need to change.</p></Section><Section title="Security"><p className="portal-muted">Need a new password?</p><a className="portal-quiet" href="/portal/forgot-password">Reset password</a></Section></div></>;

const AuthenticatedPortal = ({ session }: Readonly<{ session: Session }>) => {
  const path = locationPath(); const orderId = routeId("orders"); const quoteId = routeId("quotes"); const proofId = routeId("proofs");
  let page: React.ReactNode;
  if (path === "/portal" || path === "/portal/") page = <Home session={session} />;
  else if (path === "/portal/orders") page = <Orders />;
  else if (orderId) page = <OrderDetailPage orderId={orderId} csrfToken={session.csrfToken} />;
  else if (path === "/portal/quotes") page = <Quotes />;
  else if (quoteId) page = <QuoteDetailPage quoteId={quoteId} />;
  else if (path === "/portal/proofs") page = <Proofs />;
  else if (proofId) page = <ProofDetailPage proofId={proofId} csrfToken={session.csrfToken} />;
  else if (path === "/portal/catalog") page = <Catalog csrfToken={session.csrfToken} />;
  else if (path === "/portal/invoices" || Boolean(routeId("invoices"))) page = <Invoices csrfToken={session.csrfToken} />;
  else if (path === "/portal/account") page = <Account session={session} />;
  else page = <><PageHeader title="Page not available" description="This portal page is not available." /><a className="portal-primary" href="/portal">Back to home</a></>;
  return <Shell session={session}>{page}</Shell>;
};

export const PortalApp = () => {
  const path = locationPath(); const [session, setSession] = useState<Session | null>(null); const [checked, setChecked] = useState(false);
  useEffect(() => { if (path === "/portal/setup" || path === "/portal/reset-password" || path === "/portal/forgot-password") return; void request<Session>("/v2/portal/auth/session").then((value) => { setSession(value); if (path === "/portal") history.replaceState(null, "", value.returnTo); }).catch(() => setSession(null)).finally(() => setChecked(true)); }, [path]);
  if (path === "/portal/setup") return <PortalSetup kind="setup" />;
  if (path === "/portal/reset-password") return <PortalSetup kind="reset" />;
  if (path === "/portal/forgot-password") return <ForgotPassword />;
  if (!checked) return <Loading />;
  return session ? <AuthenticatedPortal session={session} /> : <SignIn destination={path} onSession={setSession} />;
};
