import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { artworkApi, newBusinessRequestId, prepressApi, type ArtworkOrderProjection, type PrepressQueueItem, type ProductionRequirementCoverage } from "./api";

const keys={queue:(scope:string,org:string)=>["v2",scope,org,"prepress","queue"] as const,artwork:(scope:string,org:string,order:string)=>["v2",scope,org,"artwork","order",order] as const};
const label=(r:ProductionRequirementCoverage["requirement"])=>r.side?`${r.side[0]!.toUpperCase()}${r.side.slice(1)}${r.sourcePageIndex===undefined?"":` · Page ${r.sourcePageIndex+1}`}${r.layerKey?` · ${r.layerKey} ${r.layerOrder!+1}`:""}`:r.key;
const state=(coverage:ProductionRequirementCoverage,item:PrepressQueueItem)=>!coverage.productionArtworkCovered?"Needs Production Art":coverage.prepressComplete?"Prepress Complete":coverage.prepressUnits.some((unit)=>unit.startedAt)?"In Prepress":item.routingStepKind!=="prepress"?`Waiting on ${item.routingStepKind??"Routing"}`:"Ready for Prepress";
const statusClass=(value:string)=>value==="Prepress Complete"?"ok":value==="In Prepress"?"active":value==="Ready for Prepress"?"ready":value.startsWith("Needs")?"warn":"neutral";
const fileLabel=(item:ArtworkOrderProjection)=>`${item.file.displayFilename} · ${item.assignment.purpose.replaceAll("_"," ")}${item.assignment.side?` · ${item.assignment.side}`:""}`;

/**
 * Lovable's order-centric three-panel composition, backed entirely by the
 * frozen requirement/Artwork/Prepress projections. It never manufactures a
 * line-level Prepress state or a Production release.
 */
export const PrepressWorkspace=({organizationId,sessionScope,canView,canWork,canComplete}:{organizationId:string;sessionScope:string;canView:boolean;canWork:boolean;canComplete:boolean})=>{
  const queryClient=useQueryClient();
  const queue=useQuery({queryKey:keys.queue(sessionScope,organizationId),queryFn:()=>prepressApi.list(organizationId),enabled:Boolean(organizationId&&sessionScope&&canView)});
  const [selectedLineId,setSelectedLineId]=useState(""); const [selectedRequirement,setSelectedRequirement]=useState("");
  useEffect(()=>{if(!selectedLineId&&queue.data?.[0])setSelectedLineId(queue.data[0].orderLineId);},[queue.data,selectedLineId]);
  const item=queue.data?.find((entry)=>entry.orderLineId===selectedLineId);
  useEffect(()=>{if(item&&!item.coverage.requirements.some((entry)=>entry.requirement.key===selectedRequirement))setSelectedRequirement(item.coverage.requirements[0]?.requirement.key??"");},[item,selectedRequirement]);
  const requirement=item?.coverage.requirements.find((entry)=>entry.requirement.key===selectedRequirement);
  const artwork=useQuery({queryKey:keys.artwork(sessionScope,organizationId,item?.orderId??""),queryFn:()=>artworkApi.forOrder(organizationId,item!.orderId),enabled:Boolean(item&&sessionScope&&canView)});
  const refresh=async()=>{await queryClient.invalidateQueries({queryKey:keys.queue(sessionScope,organizationId)});if(item)await queryClient.invalidateQueries({queryKey:keys.artwork(sessionScope,organizationId,item.orderId)});};
  const begin=useMutation({mutationFn:async(input:{assignmentId:string;prepressUnitId?:string})=>{const unitId=input.prepressUnitId??(await prepressApi.open(organizationId,newBusinessRequestId(),input.assignmentId)).unit.prepressUnitId;return prepressApi.start(organizationId,unitId,newBusinessRequestId());},onSuccess:refresh});
  const complete=useMutation({mutationFn:(id:string)=>prepressApi.complete(organizationId,id,newBusinessRequestId()),onSuccess:refresh});
  if(!organizationId)return <section className="v2-prepress"><div className="v2-proof-empty">Enter an authenticated organization in Sales before opening Prepress.</div></section>;
  if(!canView)return <section className="v2-prepress"><div className="v2-proof-empty">You do not have permission to view Prepress.</div></section>;
  const orderGroups=new Map<string,PrepressQueueItem[]>();for(const entry of queue.data??[])orderGroups.set(entry.orderId,[...(orderGroups.get(entry.orderId)??[]),entry]);
  const lineArtwork=(artwork.data??[]).filter((entry)=>entry.assignment.orderLineId===item?.orderLineId);
  const production=lineArtwork.filter((entry)=>entry.assignment.purpose==="production"); const supplied=lineArtwork.filter((entry)=>entry.assignment.purpose!=="production");
  const selectedUnit=requirement?.prepressUnits[0]; const candidates=requirement?.artworkAssignmentIds??[];
  return <section className="v2-prepress">
    <aside className="v2-prepress-queue"><header><div><h2>Prepress Queue</h2><span>{queue.data?.length??0} line items</span></div><input aria-label="Search Prepress queue" placeholder="Search order, customer, product…" disabled /></header><div className="v2-prepress-order-list">
      {[...orderGroups.values()].map((lines)=>{const first=lines[0]!;return <section key={first.orderId} className="v2-prepress-order"><strong>{first.orderNumber}</strong><span>{first.customerDisplayName}</span>{lines.map((line)=><button key={line.orderLineId} className={line.orderLineId===selectedLineId?"active":""} onClick={()=>setSelectedLineId(line.orderLineId)}><b>{line.lineDescription}</b><small>Qty {line.quantity}</small><div>{line.coverage.state==="unconfigured"?<em className="neutral">Requirements unconfigured</em>:line.coverage.requirements.map((r)=><em key={r.requirement.key} className={statusClass(state(r,line))}>{label(r.requirement)} · {state(r,line)}</em>)}</div></button>)}</section>;})}
      {queue.isSuccess&&!queue.data?.length&&<p className="v2-proof-empty">No routed Prepress work is available.</p>}
    </div></aside>
    <main className="v2-prepress-main">{item?<><header className="v2-prepress-header"><div><span>{item.orderNumber} · {item.customerDisplayName}</span><h1>{item.lineDescription}</h1><p>Required production units are frozen from the accepted configured product.</p></div><div className="v2-prepress-aggregate"><b>{item.coverage.state==="configured"?(item.coverage.allRequiredPrepressUnitsComplete?"All required Prepress complete":item.coverage.productionArtworkComplete?"Production Artwork covered":"Production Artwork missing"):"Requirements unconfigured"}</b><small>Routing: {item.routingStepKind??"not available"}</small></div></header>
      <div className="v2-prepress-art"><section><h2>Line item / customer art</h2>{supplied.length?supplied.map((entry)=><article key={entry.assignment.id}><b>{fileLabel(entry)}</b><small>{entry.file.contentType} · {entry.file.byteSize.toLocaleString()} bytes</small></article>):<p>No customer or reference Artwork attached.</p>}</section><section className="v2-prepress-production"><h2>Production art</h2>{item.coverage.state==="configured"?item.coverage.requirements.map((entry)=><button key={entry.requirement.key} className={entry.requirement.key===selectedRequirement?"active":""} onClick={()=>setSelectedRequirement(entry.requirement.key)}><b>{label(entry.requirement)}</b><span className={statusClass(state(entry,item))}>{state(entry,item)}</span><small>{entry.productionArtworkCovered?`${entry.artworkAssignmentIds.length} explicit production assignment${entry.artworkAssignmentIds.length===1?"":"s"}`:"Production Artwork missing"}</small></button>):<p>Required production units are not configured for this historical line.</p>}</section></div>
      <section className="v2-prepress-viewer"><div><small>Production Art Preview</small><h2>{requirement?label(requirement.requirement):"Select a required unit"}</h2></div><div className="v2-prepress-canvas">{requirement?.productionArtworkCovered?<><b>Preview unavailable</b><span>Artwork rendition generation is not part of this workspace foundation.</span></>:<><b>No production Artwork</b><span>This required unit remains visible; absence does not remove the requirement.</span></>}</div>{requirement&&<footer>{requirement.requirement.key} · {requirement.requirement.sourcePageIndex===undefined?"No page selection":`Page ${requirement.requirement.sourcePageIndex+1}`} {requirement.requirement.layerKey?`· ${requirement.requirement.layerKey} ${requirement.requirement.layerOrder!+1}`:""}</footer>}</section>
      <section className="v2-prepress-lower"><article><h2>Production Plan</h2><p>Production planning is deferred. This workspace does not assign a destination or start Production.</p></article><article><h2>Material</h2><p>Material visibility remains owned by Product/Inventory and is not fabricated here.</p></article><article><h2>Prepress Notes & Flags</h2><p>No Prepress note/flag domain is defined yet.</p></article><article><h2>Production Alerts</h2><p>Downstream Production alerts are deferred to the Production domain.</p></article></section>
    </>:<div className="v2-proof-empty">Loading authenticated Prepress queue…</div>}</main>
    <aside className="v2-prepress-rail"><section><small>Selected production unit</small><h2>{requirement?label(requirement.requirement):"No unit selected"}</h2>{requirement&&<dl><div><dt>Artwork</dt><dd>{requirement.productionArtworkCovered?"Covered":"Missing"}</dd></div><div><dt>Prepress</dt><dd>{state(requirement,item!)}</dd></div><div><dt>Completion</dt><dd>{requirement.prepressComplete?"Recorded":"Not complete"}</dd></div></dl>}</section>{requirement&&<section className="v2-prepress-actions">{!requirement.productionArtworkCovered?<p>Assign real Production Artwork in the approved Artwork workflow before starting Prepress.</p>:candidates.length!==1?<p>Multiple Production Artwork assignments can satisfy this unit. Current-selection policy is intentionally undecided.</p>:!selectedUnit?<button className="v2-primary-button" disabled={!canWork||begin.isPending||item?.routingStepKind!=="prepress"} onClick={()=>begin.mutate({assignmentId:candidates[0]!})}>Start Prepress</button>:!selectedUnit.startedAt?<button className="v2-primary-button" disabled={!canWork||begin.isPending} onClick={()=>begin.mutate({assignmentId:candidates[0]!,prepressUnitId:selectedUnit.prepressUnitId})}>Start Prepress</button>:!selectedUnit.completedAt?<button className="v2-primary-button" disabled={!canComplete||complete.isPending} onClick={()=>complete.mutate(selectedUnit.prepressUnitId)}>Complete Prepress</button>:<p className="v2-prepress-complete">Prepress completion is recorded for this unit only. Routing and Production remain unchanged.</p>}</section>}</aside>
  </section>;
};
