import { OperationalQueuePager } from "./OperationalQueuePager";
import React, { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { artworkApi, newBusinessRequestId, prepressApi, type ArtworkOrderProjection, type PrepressQueueItem, type PrepressQueueRequirementState, type ProductionRequirementCoverage } from "./api";

const keys = { queue: (scope:string, org:string, page:number, pageSize:number, search:string, requirementState:PrepressQueueRequirementState) => ["v2", scope, org, "prepress", "queue", page, pageSize, search, requirementState] as const, artwork: (scope:string, org:string, order:string) => ["v2", scope, org, "artwork", "order", order] as const, unit: (scope:string, org:string, unit:string) => ["v2", scope, org, "prepress", "unit", unit] as const };
const label = (r:ProductionRequirementCoverage["requirement"]) => r.side ? `${r.side[0]!.toUpperCase()}${r.side.slice(1)}${r.sourcePageIndex===undefined?"":` · Page ${r.sourcePageIndex+1}`}${r.layerKey?` · ${r.layerKey} ${r.layerOrder!+1}`:""}` : r.key;
const state = (coverage:ProductionRequirementCoverage,item:PrepressQueueItem) => !coverage.productionArtworkCovered ? "Needs Production Art" : coverage.prepressComplete ? "Prepress Complete" : coverage.prepressUnits.some((unit)=>unit.startedAt) ? "In Prepress" : item.routingStepKind!=="prepress" ? `Waiting on ${item.routingStepKind??"Routing"}` : "Ready for Prepress";
const statusClass = (value:string) => value==="Prepress Complete" ? "ok" : value==="In Prepress" ? "active" : value==="Ready for Prepress" ? "ready" : value.startsWith("Needs") ? "warn" : "neutral";
const fileLabel = (item:ArtworkOrderProjection) => `${item.file.displayFilename} · ${item.assignment.purpose.replaceAll("_"," ")}${item.assignment.side?` · ${item.assignment.side}`:""}`;
const prerequisite = (item:PrepressQueueItem) => item.routingStepKind==="proofing" ? "Routing is still at Proofing; Prepress cannot start." : item.routingStepKind==="prepress" ? "Routing has made Prepress current. Proofing remains owned by Proofing." : `Routing is currently at ${item.routingStepKind??"an unavailable step"}.`;

/** Approved three-rail Prepress hierarchy, backed only by canonical owner projections. */
export const PrepressWorkspace=({organizationId,sessionScope,canView,canArtworkAssign,canWork,canComplete,lineId,prepressUnitId,onSelectLine,openOrder,openCustomer,openArtwork}:{organizationId:string;sessionScope:string;canView:boolean;canArtworkAssign:boolean;canWork:boolean;canComplete:boolean;lineId?:string;prepressUnitId?:string;onSelectLine?:(lineId:string)=>void;openOrder?:(orderId:string)=>void;openCustomer?:(customerId:string)=>void;openArtwork?:(artworkFileId:string)=>void})=>{
  const queryClient=useQueryClient();
  const [requirementState,setRequirementState]=useState<PrepressQueueRequirementState>(lineId||prepressUnitId?"all":"configured");
  const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState<25|50|100>(25);
  const [selectedLineId,setSelectedLineId]=useState(lineId??""); const [selectedRequirement,setSelectedRequirement]=useState(""); const [query,setQuery]=useState("");
  const queue=useQuery({queryKey:keys.queue(sessionScope,organizationId,page,pageSize,query,requirementState),queryFn:()=>prepressApi.list(organizationId,{page,pageSize,search:query,requirementState}),enabled:Boolean(organizationId&&sessionScope&&canView)});
  const needsConfiguration=useQuery({queryKey:keys.queue(sessionScope,organizationId,1,25,query,"unconfigured"),queryFn:()=>prepressApi.list(organizationId,{page:1,pageSize:25,search:query,requirementState:"unconfigured"}),enabled:Boolean(organizationId&&sessionScope&&canView)});
  const unit=useQuery({queryKey:keys.unit(sessionScope,organizationId,prepressUnitId??""),queryFn:()=>prepressApi.get(organizationId,prepressUnitId!),enabled:Boolean(organizationId&&sessionScope&&canView&&prepressUnitId)});
  const filtered=queue.data?.items??[];
  useEffect(()=>{if(lineId&&lineId!==selectedLineId){setSelectedLineId(lineId);setRequirementState("all");setPage(1);}},[lineId]);
  useEffect(()=>{if(prepressUnitId){setRequirementState("all");setPage(1);}},[prepressUnitId]);
  useEffect(()=>{if(unit.data)setSelectedLineId(unit.data.orderLineId);},[unit.data]);
  const activeLineId=selectedLineId||filtered[0]?.orderLineId||"";
  const item=filtered.find((entry)=>entry.orderLineId===activeLineId);
  useEffect(()=>{if(!item)return;const matching=prepressUnitId?item.coverage.requirements.find((entry)=>entry.prepressUnits.some((candidate)=>candidate.prepressUnitId===prepressUnitId)):undefined;if(matching){setSelectedRequirement(matching.requirement.key);return;}if(!item.coverage.requirements.some((entry)=>entry.requirement.key===selectedRequirement))setSelectedRequirement(item.coverage.requirements[0]?.requirement.key??"");},[item,prepressUnitId,selectedRequirement]);
  const activeRequirementKey=selectedRequirement||item?.coverage.requirements[0]?.requirement.key||"";
  const requirement=item?.coverage.requirements.find((entry)=>entry.requirement.key===activeRequirementKey);
  const artwork=useQuery({queryKey:keys.artwork(sessionScope,organizationId,item?.orderId??""),queryFn:()=>artworkApi.forOrder(organizationId,item!.orderId),enabled:Boolean(item&&sessionScope&&canView)});
  const refresh=async()=>{await queryClient.invalidateQueries({queryKey:["v2",sessionScope,organizationId,"prepress","queue"]});if(item)await queryClient.invalidateQueries({queryKey:keys.artwork(sessionScope,organizationId,item.orderId)});};
  const assignProduction=useMutation({mutationFn:(source:ArtworkOrderProjection)=>artworkApi.assign(organizationId,source.file.id,newBusinessRequestId(),{orderId:item!.orderId,orderLineId:item!.orderLineId,purpose:"production",...(requirement?.requirement.side?{side:requirement.requirement.side}:{}),...(requirement?.requirement.sourcePageIndex===undefined?{}:{sourcePageIndex:requirement.requirement.sourcePageIndex}),...(requirement?.requirement.layerKey?{layerKey:requirement.requirement.layerKey,layerOrder:requirement.requirement.layerOrder}:{})}),onSuccess:refresh});
  const begin=useMutation({mutationFn:async(input:{assignmentId:string;prepressUnitId?:string})=>{const unitId=input.prepressUnitId??(await prepressApi.open(organizationId,newBusinessRequestId(),input.assignmentId)).unit.prepressUnitId;return prepressApi.start(organizationId,unitId,newBusinessRequestId());},onSuccess:refresh});
  const complete=useMutation({mutationFn:(id:string)=>prepressApi.complete(organizationId,id,newBusinessRequestId()),onSuccess:refresh});
  if(!organizationId)return <section className="v2-prepress"><div className="v2-proof-empty">Enter an authenticated organization in Sales before opening Prepress.</div></section>;
  if(!canView)return <section className="v2-prepress"><div className="v2-proof-empty">You do not have permission to view Prepress.</div></section>;
  const groups=new Map<string,PrepressQueueItem[]>();for(const entry of filtered)groups.set(entry.orderId,[...(groups.get(entry.orderId)??[]),entry]);
  const lineArtwork=(artwork.data??[]).filter((entry)=>entry.assignment.orderLineId===item?.orderLineId); const productionArtwork=lineArtwork.filter((entry)=>entry.assignment.purpose==="production"); const suppliedArtwork=lineArtwork.filter((entry)=>entry.assignment.purpose!=="production");
  const selectedUnit=requirement?.prepressUnits[0]; const candidates=requirement?.artworkAssignmentIds??[];
  const sourceArtwork=suppliedArtwork.find((entry)=>entry.assignment.side===requirement?.requirement.side&&entry.assignment.sourcePageIndex===requirement?.requirement.sourcePageIndex&&entry.assignment.layerKey===requirement?.requirement.layerKey&&entry.assignment.layerOrder===requirement?.requirement.layerOrder);
  const unavailable=Boolean((selectedLineId&&queue.isSuccess&&!item)||(prepressUnitId&&unit.isError)); const selectLine=(next:string)=>{setSelectedLineId(next);onSelectLine?.(next);};
  const selectView=(next:PrepressQueueRequirementState)=>{setRequirementState(next);setPage(1);setSelectedLineId("");setSelectedRequirement("");};
  return <section className="v2-prepress">
    <aside className="v2-prepress-queue"><header><div><h2>Prepress Queue</h2><span>{queue.data?.pagination.totalCount??0} line items</span></div><input aria-label="Search Prepress queue" placeholder="Search order, customer, product…" value={query} onChange={(event)=>{setQuery(event.target.value);setPage(1);setSelectedLineId("");}} /></header>
    <div className="v2-prepress-queue-views" role="group" aria-label="Prepress queue view">
      <button type="button" aria-pressed={requirementState==="configured"} onClick={()=>selectView("configured")}>Active work</button>
      <button type="button" aria-pressed={requirementState==="unconfigured"} onClick={()=>selectView("unconfigured")}>Needs configuration ({needsConfiguration.data?.pagination.totalCount??"…"})</button>
      <button type="button" aria-pressed={requirementState==="all"} onClick={()=>selectView("all")}>All routed work</button>
    </div>
    {needsConfiguration.isError&&<p role="alert">The needs-configuration count is unavailable.</p>}
    {requirementState==="unconfigured"&&<p className="v2-prepress-recovery-note">These lines have no frozen production requirements and remain available for review. Open the Order to inspect its configuration and history.</p>}
    <OperationalQueuePager page={page} pageSize={pageSize} total={queue.data?.pagination.totalCount??0} totalPages={queue.data?.pagination.totalPages??0} onPage={(next)=>{setPage(next);setSelectedLineId("");}} onPageSize={(next)=>{setPageSize(next);setPage(1);setSelectedLineId("");}}/><div className="v2-prepress-order-list">
      {[...groups.values()].map((lines)=>{const first=lines[0]!;return <section key={first.orderId} className="v2-prepress-order"><strong>{first.orderNumber}</strong><span>{first.customerDisplayName}{first.requestedDueDate?` · Due ${first.requestedDueDate.slice(0,10)}`:""}</span>{lines.map((line)=><button key={line.orderLineId} className={line.orderLineId===activeLineId?"active":""} onClick={()=>selectLine(line.orderLineId)}><b>{line.lineDescription}</b><small>Qty {line.quantity}</small><div>{line.coverage.state==="unconfigured"?<em className="neutral">Requirements unconfigured</em>:line.coverage.requirements.map((coverage)=><em key={coverage.requirement.key} className={statusClass(state(coverage,line))}>{label(coverage.requirement)} · {state(coverage,line)}</em>)}</div></button>)}</section>;})}
      {queue.isSuccess&&!filtered.length&&<p className="v2-proof-empty">{query?"No Prepress work matches this search.":requirementState==="unconfigured"?"No routed Prepress work needs configuration.":requirementState==="configured"?"No active Prepress work is available. Review Needs configuration for other routed lines.":"No routed Prepress work is available."}</p>}
    </div><OperationalQueuePager page={page} pageSize={pageSize} total={queue.data?.pagination.totalCount??0} totalPages={queue.data?.pagination.totalPages??0} onPage={(next)=>{setPage(next);setSelectedLineId("");}} onPageSize={(next)=>{setPageSize(next);setPage(1);setSelectedLineId("");}}/></aside>
    <main className="v2-prepress-main">{unavailable?<div className="v2-proof-empty">The selected Prepress work is unavailable in this organization.</div>:item?<><header className="v2-prepress-header"><div><span>{item.orderNumber} · {item.customerDisplayName}</span><h1>{item.lineDescription}</h1><p>{item.coverage.state==="configured"?"Required production units are frozen from the accepted configured product.":"Requirements are unconfigured. Review this line through its Order before production work can be prepared."}</p><div className="v2-prepress-context-links"><button onClick={()=>openOrder?.(item.orderId)}>Open Order</button>{item.customerId&&<button onClick={()=>openCustomer?.(item.customerId!)}>Open Customer</button>}</div></div><div className="v2-prepress-aggregate"><b>{item.coverage.state==="configured"?(item.coverage.allRequiredPrepressUnitsComplete?"All required Prepress complete":item.coverage.productionArtworkComplete?"Production Artwork covered":"Production Artwork missing"):"Requirements unconfigured"}</b><small>Routing: {item.routingStepKind??"not available"}</small></div></header>
      <div className="v2-prepress-art"><section><h2>Line item / customer art</h2>{suppliedArtwork.length?suppliedArtwork.map((entry)=><article key={entry.assignment.id}><b>{fileLabel(entry)}</b><small>{entry.file.contentType} · {entry.file.byteSize.toLocaleString()} bytes</small><button onClick={()=>openArtwork?.(entry.file.id)}>Open Artwork</button></article>):<p>No customer or reference Artwork attached.</p>}</section><section className="v2-prepress-production"><h2>Production art</h2>{item.coverage.state==="configured"?item.coverage.requirements.map((coverage)=><button key={coverage.requirement.key} className={coverage.requirement.key===activeRequirementKey?"active":""} onClick={()=>setSelectedRequirement(coverage.requirement.key)}><b>{label(coverage.requirement)}</b><span className={statusClass(state(coverage,item))}>{state(coverage,item)}</span><small>{coverage.productionArtworkCovered?`${coverage.artworkAssignmentIds.length} explicit production assignment${coverage.artworkAssignmentIds.length===1?"":"s"}`:"Production Artwork missing"}</small></button>):<p>Required production units are not configured for this line. Its existing Artwork and history remain available for review.</p>}{productionArtwork.length>0&&<p className="v2-prepress-art-summary">{productionArtwork.length} canonical production Artwork assignment{productionArtwork.length===1?"":"s"} on this line.</p>}</section></div>
      <section className="v2-prepress-viewer"><div><small>Production Art Preview</small><h2>{requirement?label(requirement.requirement):"Select a required unit"}</h2></div><div className="v2-prepress-canvas">{item.coverage.state==="unconfigured"?<><b>Requirements unconfigured</b><span>Open the Order to review this line before preparing production Artwork.</span></>:requirement?.productionArtworkCovered?<><b>Preview unavailable</b><span>This workspace shows canonical preparation evidence without exposing private Artwork storage.</span></>:<><b>No production Artwork</b><span>This required unit remains visible; absence does not remove the requirement.</span></>}</div>{requirement&&<footer>{requirement.requirement.key} · {requirement.requirement.sourcePageIndex===undefined?"No page selection":`Page ${requirement.requirement.sourcePageIndex+1}`} {requirement.requirement.layerKey?`· ${requirement.requirement.layerKey} ${requirement.requirement.layerOrder!+1}`:""}</footer>}</section>
      <section className="v2-prepress-lower"><article><h2>Workflow boundary</h2><p>Prepress records preparation evidence only. Routing evaluates progression; Production owns execution.</p></article><article><h2>Artwork boundary</h2><p>Production Artwork remains Artwork-owned. This workspace uses canonical assignments and required side/page/layer facts.</p></article></section>
    </>:<div className="v2-proof-empty">{queue.isError?"The Prepress queue is unavailable.":queue.isSuccess?"Select a line to review Prepress work.":"Loading authenticated Prepress queue…"}</div>}</main>
    <aside className="v2-prepress-rail">{item&&<><section><small>Order line context</small><h2>{item.lineDescription}</h2><dl><div><dt>Order</dt><dd>{item.orderNumber}</dd></div><div><dt>Quantity</dt><dd>{item.quantity}</dd></div><div><dt>Customer</dt><dd>{item.customerDisplayName}</dd></div><div><dt>Due</dt><dd>{item.requestedDueDate?.slice(0,10)??"Not recorded"}</dd></div></dl></section><section><small>Routing prerequisite</small><p>{prerequisite(item)}</p></section><section><small>Selected production unit</small><h2>{requirement?label(requirement.requirement):"No unit selected"}</h2>{requirement&&<dl><div><dt>Artwork</dt><dd>{requirement.productionArtworkCovered?"Covered":"Missing"}</dd></div><div><dt>Prepress</dt><dd>{state(requirement,item)}</dd></div><div><dt>Completion</dt><dd>{requirement.prepressComplete?"Recorded":"Not complete"}</dd></div></dl>}</section>{requirement&&<section className="v2-prepress-actions">{!requirement.productionArtworkCovered?sourceArtwork?<><p>Customer Artwork is ready for this exact required unit. The canonical file will receive a production assignment.</p><button className="v2-primary-button" disabled={!canArtworkAssign||assignProduction.isPending} onClick={()=>assignProduction.mutate(sourceArtwork)}>{assignProduction.isPending?"Designating Production Artwork…":"Use customer Artwork for Production"}</button></>:<p>Customer Artwork for this required unit is missing. Add it through Artwork before starting Prepress.</p>:candidates.length!==1?<p>Multiple Production Artwork assignments can satisfy this unit. Current-selection policy is intentionally undecided.</p>:!selectedUnit?<button className="v2-primary-button" disabled={!canWork||begin.isPending||item.routingStepKind!=="prepress"} onClick={()=>begin.mutate({assignmentId:candidates[0]!})}>Start Prepress</button>:!selectedUnit.startedAt?<button className="v2-primary-button" disabled={!canWork||begin.isPending} onClick={()=>begin.mutate({assignmentId:candidates[0]!,prepressUnitId:selectedUnit.prepressUnitId})}>Start Prepress</button>:!selectedUnit.completedAt?<button className="v2-primary-button" disabled={!canComplete||complete.isPending} onClick={()=>complete.mutate(selectedUnit.prepressUnitId)}>Complete Prepress</button>:<p className="v2-prepress-complete">Prepress completion is recorded for this unit only. Routing and Production remain unchanged.</p>}{assignProduction.isError&&<p className="v2-product-version-message" role="alert">{(assignProduction.error as Error).message}</p>}{begin.isError&&<p className="v2-product-version-message" role="alert">{(begin.error as Error).message}</p>}{complete.isError&&<p className="v2-product-version-message" role="alert">{(complete.error as Error).message}</p>}</section>}</>}</aside>
  </section>;
};
