import assert from "node:assert/strict";
import { artworkFilePath, artworkPath, contactPath, customerPath, formulaAuthoringPath, fulfillmentPath, invoicePath, legacyProductEditorRedirect, newProductBuilderPath, orderPath, prepressPath, prepressUnitPath, productBuilderPath, productPath, productionPath, proofingPath, quotePath, readArtworkLocation, readContactLocation, readCustomerLocation, readFormulaAuthoringContext, readFulfillmentLocation, readInvoiceLocation, readOrderLocation, readPrepressLocation, readProductBuilderLocation, readProductLocation, readProductionLocation, readProofingLocation, readQuoteLocation, readWorkspaceLocation, workspacePath } from "./productRouting";

assert.deepEqual(readProductLocation("/products"), {});
assert.equal(readProductLocation("/products/product-a"), null);
assert.equal(readProductLocation("/products/product%2Da"), null);
assert.equal(readProductLocation("/products/%2Fwrong"), null);
assert.equal(readProductLocation("/quotes"), null);
assert.equal(productPath("product a"), "/products/product%20a");
assert.equal(legacyProductEditorRedirect("/products/product-a"), "/product-builder/product-a?draft=1");
assert.equal(legacyProductEditorRedirect("/products/product-a", "?draft=0"), "/product-builder/product-a?draft=1");
assert.equal(legacyProductEditorRedirect("/products/product-a/edit", "?draftTreeVersionId=legacy-tree"), "/product-builder/product-a?draft=1");
assert.equal(legacyProductEditorRedirect("/products/new"), null);
assert.equal(legacyProductEditorRedirect("/products/%2Fwrong/edit"), null);
assert.equal(readProductBuilderLocation("/product-builder"), null);
assert.deepEqual(readProductBuilderLocation("/product-builder/product-a"), { productId: "product-a" });
assert.equal(readProductBuilderLocation("/product-builder/%2Fwrong"), null);
assert.equal(productBuilderPath("product a"), "/product-builder/product%20a?draft=1");
assert.equal(formulaAuthoringPath({ productId: "product a", draftVersionId: "draft a", intent: "new" }), "/formulas?product=product+a&draft=draft+a&formulaIntent=new");
assert.equal(formulaAuthoringPath({ productId: "product-a", draftVersionId: "draft-a", intent: "revise", formulaId: "formula-a" }), "/formulas?product=product-a&draft=draft-a&formulaIntent=revise&formula=formula-a");
assert.deepEqual(readFormulaAuthoringContext("/formulas", "?product=product-a&draft=draft-a&formulaIntent=new"), { productId: "product-a", draftVersionId: "draft-a", intent: "new" });
assert.deepEqual(readFormulaAuthoringContext("/formulas", "?product=product-a&draft=draft-a&formulaIntent=revise&formula=formula-a"), { productId: "product-a", draftVersionId: "draft-a", intent: "revise", formulaId: "formula-a" });
assert.equal(readFormulaAuthoringContext("/formulas", "?product=product-a&draft=draft-a&formulaIntent=revise"), null);
assert.equal(readFormulaAuthoringContext("/formulas", "?product=product-a&draft=draft-a&formulaIntent=redirect&return=https%3A%2F%2Fevil.example"), null, "Formula authoring context accepts no arbitrary return URL");
assert.equal(readFormulaAuthoringContext("/formulas", "?product=https%3A%2F%2Fevil.example&draft=draft-a&formulaIntent=new"), null, "external values are not valid internal product identities");
assert.equal(productBuilderPath("product-a", { formulaId: "formula-a", formulaRevisionId: "revision-2" }), "/product-builder/product-a?draft=1&formulaReturn=1&formula=formula-a&formulaRevision=revision-2");
assert.deepEqual(readProductBuilderLocation("/product-builder/product-a", "?draft=1&formulaReturn=1&formula=formula-a&formulaRevision=revision-2"), { productId: "product-a", formulaReturn: { formulaId: "formula-a", formulaRevisionId: "revision-2" } });
assert.deepEqual(readProductBuilderLocation("/product-builder/product-a", "?formulaReturn=1&formula=https%3A%2F%2Fevil.example&formulaRevision=revision-2"), { productId: "product-a" }, "malformed Formula return context is discarded rather than navigated");
assert.deepEqual(readWorkspaceLocation("/product-builder/product-a"), { page: "productBuilder", productId: "product-a" });
assert.equal(newProductBuilderPath(), "/products/new");
assert.deepEqual(readProductBuilderLocation("/products/new"), { newProduct: true });
assert.deepEqual(readWorkspaceLocation("/products/new"), { page: "productBuilder", newProduct: true });
assert.deepEqual(readCustomerLocation("/customers"), {});
assert.deepEqual(readCustomerLocation("/customers/customer-a"), { customerId: "customer-a" });
assert.equal(readCustomerLocation("/customers/%2Fwrong"), null);
assert.deepEqual(readWorkspaceLocation("/customers/customer-a"), { page: "customers", customerId: "customer-a" });
assert.equal(readWorkspaceLocation("/products/product-a"), null);
assert.equal(customerPath("customer a"), "/customers/customer%20a");
assert.deepEqual(readContactLocation("/contacts"), {});
assert.deepEqual(readContactLocation("/contacts/contact-a"), { contactId: "contact-a" });
assert.equal(readContactLocation("/contacts/%2Fwrong"), null);
assert.deepEqual(readWorkspaceLocation("/contacts/contact-a"), { page: "contacts", contactId: "contact-a" });
assert.equal(contactPath("contact a"), "/contacts/contact%20a");
assert.deepEqual(readWorkspaceLocation("/artwork"), { page: "artwork" });
assert.deepEqual(readArtworkLocation("/artwork/files/file-a"), { artworkFileId: "file-a" });
assert.deepEqual(readWorkspaceLocation("/artwork/files/file-a"), { page: "artwork", artworkFileId: "file-a" });
assert.equal(readArtworkLocation("/artwork/files/%2Fwrong"), null);
assert.equal(artworkFilePath("file a"), "/artwork/files/file%20a");
assert.deepEqual(readArtworkLocation("/artwork/orders/order-a/lines/line-a"), { orderId: "order-a", lineId: "line-a" });
assert.deepEqual(readWorkspaceLocation("/artwork/orders/order-a"), { page: "artwork", orderId: "order-a" });
assert.deepEqual(readWorkspaceLocation("/artwork/orders/order-a/lines/line-a"), { page: "artwork", orderId: "order-a", lineId: "line-a" });
assert.equal(artworkPath("order a", "line a"), "/artwork/orders/order%20a/lines/line%20a");
assert.deepEqual(readWorkspaceLocation("/proofing"), { page: "proofing" });
assert.deepEqual(readProofingLocation("/proofing/works/proof-a"), { proofWorkId: "proof-a" });
assert.deepEqual(readWorkspaceLocation("/proofing/works/proof-a"), { page: "proofing", proofWorkId: "proof-a" });
assert.equal(proofingPath("proof a"), "/proofing/works/proof%20a");
assert.deepEqual(readProofingLocation("/proofing/orders/order-a/lines/line-a"), { orderId: "order-a", lineId: "line-a" });
assert.deepEqual(readWorkspaceLocation("/proofing/orders/order-a/lines/line-a"), { page: "proofing", orderId: "order-a", lineId: "line-a" });
assert.equal(proofingPath(undefined, "order a", "line a"), "/proofing/orders/order%20a/lines/line%20a");
assert.deepEqual(readWorkspaceLocation("/prepress"), { page: "prepress" });
assert.deepEqual(readPrepressLocation("/prepress/lines/line-a"), { lineId: "line-a" });
assert.deepEqual(readWorkspaceLocation("/prepress/lines/line-a"), { page: "prepress", lineId: "line-a" });
assert.equal(readPrepressLocation("/prepress/lines/%2Fwrong"), null);
assert.equal(prepressPath("line a"), "/prepress/lines/line%20a");
assert.deepEqual(readPrepressLocation("/prepress/units/unit-a"), { prepressUnitId: "unit-a" });
assert.deepEqual(readWorkspaceLocation("/prepress/units/unit-a"), { page: "prepress", prepressUnitId: "unit-a" });
assert.equal(prepressUnitPath("unit a"), "/prepress/units/unit%20a");
assert.equal(workspacePath("artwork"), "/artwork");
assert.deepEqual(readQuoteLocation("/quotes/quote-a"), { quoteId: "quote-a" });
assert.deepEqual(readOrderLocation("/orders/order-a"), { orderId: "order-a" });
assert.deepEqual(readWorkspaceLocation("/quotes/quote-a"), { page: "quotes", quoteId: "quote-a" });
assert.deepEqual(readWorkspaceLocation("/orders/order-a"), { page: "orders", orderId: "order-a" });
assert.equal(quotePath("quote a"), "/quotes/quote%20a");
assert.equal(orderPath("order a"), "/orders/order%20a");
assert.deepEqual(readInvoiceLocation("/invoices/invoice-a"), { invoiceId: "invoice-a" });
assert.deepEqual(readWorkspaceLocation("/invoices"), { page: "invoices" });
assert.deepEqual(readWorkspaceLocation("/invoices/invoice-a"), { page: "invoices", invoiceId: "invoice-a" });
assert.equal(invoicePath("invoice a"), "/invoices/invoice%20a");
assert.deepEqual(readFulfillmentLocation("/fulfillment/orders/order-a"), { orderId: "order-a" });
assert.deepEqual(readWorkspaceLocation("/fulfillment"), { page: "fulfillment" });
assert.deepEqual(readWorkspaceLocation("/fulfillment/orders/order-a"), { page: "fulfillment", orderId: "order-a" });
assert.equal(fulfillmentPath("order a"), "/fulfillment/orders/order%20a");
assert.deepEqual(readProductionLocation("/production/flatbed"), { station: "flatbed" });
assert.deepEqual(readWorkspaceLocation("/production"), { page: "production" });
assert.deepEqual(readWorkspaceLocation("/production/roll"), { page: "production", station: "roll" });
assert.equal(productionPath("flatbed"), "/production/flatbed");
assert.deepEqual(readWorkspaceLocation("/payments"), { page: "payments" });
assert.equal(workspacePath("payments"), "/payments");
assert.deepEqual(readWorkspaceLocation("/routing"), { page: "routing" });
assert.equal(workspacePath("routing"), "/routing");
assert.deepEqual(readWorkspaceLocation("/formulas"), { page: "formulas" });
assert.equal(workspacePath("formulas"), "/formulas");
assert.deepEqual(readWorkspaceLocation("/"), { page: "home" });
assert.deepEqual(readWorkspaceLocation("/appearance"), { page: "appearance" });
