import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import React, { useState } from "react";
import { newBusinessRequestId, productApi, type ProductCatalogItem, type ProductDraftGeneral, type ProductDraftGeneralRead, type ProductVersionSummary, type ProductWorkspaceDetail } from "./api";

const keys={list:(s:string,o:string,q:string,p:number)=>["v2",s,o,"products",q,p] as const,detail:(s:string,o:string,id:string)=>["v2",s,o,"products",id] as const,draftGeneral:(s:string,o:string,id:string)=>["v2",s,o,"products",id,"draft-general"] as const};
const dash="—", initials=(s:string)=>s.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"P";
const status=(p:ProductCatalogItem)=>p.lifecycle==="active_with_draft"?"Active · Draft":p.lifecycle==="draft"?"Draft":p.lifecycle==="inactive"?"Inactive":"Active";
const basis=(p:ProductCatalogItem)=>p.measurementMode==="quantity_only"?"Quantity only":"Dimensions + quantity";
const route=(p:ProductCatalogItem)=>!p.productType?dash:p.productType.routePolicy==="route_required"?`${p.productType.displayName} · Route required`:p.productType.routePolicy==="no_route"?`${p.productType.displayName} · No route`:`${p.productType.displayName} · Unconfigured`;
const date=(value?:string)=>value?new Intl.DateTimeFormat(undefined,{year:"numeric",month:"short",day:"numeric"}).format(new Date(value)):dash;
const versionStatus=(value:ProductVersionSummary["status"])=>value==="active"?"Active":value==="draft"?"Draft":value[0].toUpperCase()+value.slice(1);

export const ProductWorkspace=({organizationId,sessionScope,productId,canView,canEdit,openProduct,backToCatalog}:Readonly<{organizationId:string;sessionScope:string;productId:string;canView:boolean;canEdit:boolean;openProduct:(id:string)=>void;backToCatalog:()=>void}>)=>{
  const[query,setQuery]=useState(""),[page,setPage]=useState(1),[editingDraft,setEditingDraft]=useState(()=>typeof window!=="undefined"&&new URLSearchParams(window.location.search).get("draft")==="1");
  const list=useQuery({queryKey:keys.list(sessionScope,organizationId,query,page),queryFn:()=>productApi.list(organizationId,query,page),enabled:Boolean(organizationId&&sessionScope&&canView&&!productId)});
  const detail=useQuery({queryKey:keys.detail(sessionScope,organizationId,productId),queryFn:()=>productApi.get(organizationId,productId),enabled:Boolean(organizationId&&sessionScope&&canView&&productId)});
  if(!organizationId)return <section className="v2-products"><p className="v2-proof-empty">Products are unavailable.</p></section>;
  if(!canView)return <section className="v2-products"><p className="v2-proof-empty">You do not have permission to view Products.</p></section>;
  if(productId)return <Detail state={detail} canEdit={canEdit} organizationId={organizationId} sessionScope={sessionScope} editingDraft={editingDraft} openDraft={()=>{window.history.pushState({},"",`/products/${encodeURIComponent(productId)}?draft=1`);setEditingDraft(true);}} closeDraft={()=>{window.history.pushState({},"",`/products/${encodeURIComponent(productId)}`);setEditingDraft(false);}} back={backToCatalog}/>;
  return <section className="v2-products" aria-label="Products"><header className="v2-products-heading"><div><h1>Products</h1><p>{list.data?`${list.data.total} configurable product${list.data.total===1?"":"s"}`:"Products"}</p></div></header><div className="v2-products-tools"><label><span>⌕</span><input aria-label="Search Products" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Product or category…"/></label></div><div className="v2-products-table-wrap"><table className="v2-products-table"><thead><tr><th>Product</th><th>Category</th><th>Pricing</th><th>Route</th><th>Basis</th><th>Primary Material</th><th>Status</th></tr></thead><tbody>{list.isLoading&&<tr><td colSpan={7}>Loading Products…</td></tr>}{list.isError&&<tr><td colSpan={7}>Products are unavailable.</td></tr>}{list.isSuccess&&!list.data.items.length&&<tr><td colSpan={7}>{query?"No Products match this search.":"No Products are available."}</td></tr>}{list.data?.items.map(p=><tr key={p.productId}><td><button className="v2-products-link" type="button" onClick={()=>openProduct(p.productId)}><i>{initials(p.displayName)}</i><b>{p.displayName}</b></button></td><td>{p.category??dash}</td><td>{p.pricingSummary}</td><td>{route(p)}</td><td>{basis(p)}</td><td>{p.primaryMaterialName??dash}</td><td><em className={`v2-product-status ${p.lifecycle}`}>{status(p)}</em></td></tr>)}</tbody></table></div>{list.data&&list.data.total>list.data.pageSize&&<nav className="v2-products-pagination"><span>Page {list.data.page}</span><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button disabled={!list.data.hasMore} onClick={()=>setPage(page+1)}>Next</button></nav>}</section>;
};
const Field=({label,value}:{label:string;value:string})=><div><dt>{label}</dt><dd>{value}</dd></div>;
const VersionRow=({version}:{version:ProductVersionSummary})=><li><span><em className={`v2-product-status ${version.status}`}>{versionStatus(version.status)}</em>{version.publishedAt?`Published ${date(version.publishedAt)}`:`Updated ${date(version.updatedAt)}`}</span><small>Created {date(version.createdAt)}</small></li>;
const Versions=({product,canEdit,organizationId,sessionScope,onEditDraft}:{product:ProductWorkspaceDetail;canEdit:boolean;organizationId:string;sessionScope:string;onEditDraft:()=>void})=>{
  const client=useQueryClient(),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  const create=async()=>{if(!product.versions.active)return;setSaving(true);setMessage("");try{const versions=await productApi.createDraft(organizationId,product.productId,newBusinessRequestId(),product.versions.active.updatedAt);client.setQueryData(keys.detail(sessionScope,organizationId,product.productId),{...product,versions,lifecycle:versions.draft?"active_with_draft":product.lifecycle});client.invalidateQueries({queryKey:["v2",sessionScope,organizationId,"products"]});setMessage("Draft created.");}catch(error){setMessage((error as {message?:string}).message??"Unable to create Draft.");client.invalidateQueries({queryKey:keys.detail(sessionScope,organizationId,product.productId)});}finally{setSaving(false);}};
  const v=product.versions;return <article className="v2-product-versions"><header><h2>Versions</h2>{canEdit&&v.canCreateDraft?<button type="button" onClick={()=>void create()} disabled={saving}>{saving?"Creating…":"Create Draft"}</button>:canEdit&&v.draft?<button type="button" onClick={onEditDraft}>Edit Draft</button>:null}</header>{message?<p className="v2-product-version-message">{message}</p>:null}<dl><Field label="Active" value={v.active?`${v.active.publishedAt?`Published ${date(v.active.publishedAt)}`:"Active"}`:dash}/><Field label="Draft" value={v.draft?`Updated ${date(v.draft.updatedAt)}`:dash}/></dl>{v.history.length?<><h3>History</h3><ul>{v.history.map((version,index)=><VersionRow key={`${version.status}-${version.createdAt}-${index}`} version={version}/>)}</ul>{v.historyHasMore?<p className="v2-product-history-more">More history is available.</p>:null}</>:null}</article>;
};
const ProductDraftBuilder=({product,organizationId,sessionScope,canEdit,back}:{product:ProductWorkspaceDetail;organizationId:string;sessionScope:string;canEdit:boolean;back:()=>void})=>{
  const client=useQueryClient();const draft=useQuery({queryKey:keys.draftGeneral(sessionScope,organizationId,product.productId),queryFn:()=>productApi.draftGeneral(organizationId,product.productId),enabled:Boolean(organizationId&&sessionScope)});
  const save=useMutation({mutationFn:(value:ProductDraftGeneralRead)=>productApi.saveDraftGeneral(organizationId,product.productId,newBusinessRequestId(),{draftVersionId:value.draftVersionId,expectedDraftUpdatedAt:value.draftUpdatedAt,general:value.general}),onSuccess:value=>client.setQueryData(keys.draftGeneral(sessionScope,organizationId,product.productId),value)});
  if(draft.isLoading)return <section className="v2-products"><p className="v2-proof-empty">Loading Draft…</p></section>;
  if(draft.isError||!draft.data)return <section className="v2-products"><button className="v2-products-back" onClick={back}>← Product</button><p className="v2-proof-empty">A Product Draft is unavailable.</p></section>;
  const value=draft.data;return <section className="v2-products v2-product-builder"><header><button className="v2-products-back" onClick={back}>← Product</button><div><h1>Product Builder</h1><p>{product.displayName} · Draft</p></div><button type="submit" form="product-draft-general" disabled={!canEdit||save.isPending}>{save.isPending?"Saving…":"Save Draft"}</button></header><nav aria-label="Product Builder steps"><b>1 General</b></nav>{save.isSuccess&&<p className="v2-product-version-message">Draft saved.</p>}{save.isError&&<p className="v2-product-version-message">{(save.error as {message?:string}).message??"Unable to save Draft."}</p>}<div className="v2-product-builder-grid"><GeneralForm key={`${value.draftVersionId}:${value.draftUpdatedAt}`} value={value} disabled={!canEdit||save.isPending} onSave={next=>save.mutate(next)}/><aside><h2>Customer preview</h2><div><b>{value.general.displayName}</b><span>{value.general.category??"Product"}</span>{value.general.description&&<p>{value.general.description}</p>}<small>{value.general.storefrontVisible?"Visible in storefront":"Internal only"}</small></div></aside></div></section>;
};
const GeneralForm=({value,disabled,onSave}:{value:ProductDraftGeneralRead;disabled:boolean;onSave:(next:ProductDraftGeneralRead)=>void})=>{const[general,setGeneral]=useState(value.general);const change=<K extends keyof ProductDraftGeneral>(key:K,next:ProductDraftGeneral[K])=>setGeneral(current=>({...current,[key]:next}));return <form id="product-draft-general" className="v2-product-general" onSubmit={event=>{event.preventDefault();onSave({...value,general});}}><h2>General</h2><label>Product name<input value={general.displayName} disabled={disabled} onChange={event=>change("displayName",event.target.value)}/></label><label>Category<input value={general.category??""} disabled={disabled} onChange={event=>change("category",event.target.value||null)}/></label><label className="wide">Customer-facing description<textarea value={general.description??""} disabled={disabled} onChange={event=>change("description",event.target.value||null)}/></label><label>Measurement<select value={general.measurementMode} disabled={disabled} onChange={event=>change("measurementMode",event.target.value as ProductDraftGeneral["measurementMode"])}><option value="dimensions_required">Dimensions + quantity</option><option value="quantity_only">Quantity only</option></select></label><label>Workflow<select value={general.workflowIntent} disabled={disabled} onChange={event=>change("workflowIntent",event.target.value as ProductDraftGeneral["workflowIntent"])}><option value="standard_production">Standard production</option><option value="fulfillment_only">Fulfillment only</option><option value="service_fee">Service / fee</option></select></label><label className="toggle">Show in customer storefront<input type="checkbox" checked={general.storefrontVisible} disabled={disabled} onChange={event=>change("storefrontVisible",event.target.checked)}/></label><label className="toggle">Requires proof approval<input type="checkbox" checked={general.requiresProofApproval} disabled={disabled||general.workflowIntent!=="standard_production"} onChange={event=>change("requiresProofApproval",event.target.checked)}/></label><label className="toggle">Requires production job<input type="checkbox" checked={general.requiresProductionJob} disabled={disabled||general.workflowIntent!=="standard_production"} onChange={event=>change("requiresProductionJob",event.target.checked)}/></label></form>};
const Detail=({state,canEdit,organizationId,sessionScope,editingDraft,openDraft,closeDraft,back}:{state:ReturnType<typeof useQuery<ProductWorkspaceDetail>>;canEdit:boolean;organizationId:string;sessionScope:string;editingDraft:boolean;openDraft:()=>void;closeDraft:()=>void;back:()=>void})=>{if(state.isLoading)return <section className="v2-products"><p className="v2-proof-empty">Loading Product…</p></section>;if(state.isError||!state.data)return <section className="v2-products"><button className="v2-products-back" onClick={back}>← Products</button><p className="v2-proof-empty">Product not found.</p></section>;const p=state.data;if(editingDraft)return <ProductDraftBuilder product={p} organizationId={organizationId} sessionScope={sessionScope} canEdit={canEdit} back={closeDraft}/>;return <section className="v2-products v2-product-detail"><button className="v2-products-back" onClick={back}>← Products</button><header className="v2-products-heading"><div><h1>{p.displayName}</h1><p>{[p.category,p.productType?.displayName].filter(Boolean).join(" · ")||"Product"}</p></div><em className={`v2-product-status ${p.lifecycle}`}>{status(p)}</em></header><div className="v2-product-detail-grid"><article><h2>Product details</h2><dl><Field label="Measurement" value={basis(p)}/><Field label="Workflow" value={p.workflowIntent==="service_fee"?"Service / fee":p.workflowIntent==="fulfillment_only"?"Fulfillment only":"Standard production"}/><Field label="Configurable options" value={p.configurableOptionCount?`${p.configurableOptionCount} option${p.configurableOptionCount===1?"":"s"}`:dash}/></dl></article><article><h2>Pricing</h2><dl><Field label="Method" value={p.pricingSummary}/><Field label="Current version" value={p.activeVersion?.label??dash}/><Field label="Draft" value={p.hasDraft?"Available":dash}/></dl></article><article><h2>Production policy</h2><dl><Field label="Product Type" value={p.productType?.displayName??dash}/><Field label="Route policy" value={p.productType?.routePolicy==="route_required"?"Route required":p.productType?.routePolicy==="no_route"?"No route":p.productType?"Unconfigured":dash}/><Field label="Proof required" value={p.requiresProofApproval?"Yes":"No"}/><Field label="Production required" value={p.requiresProductionJob?"Yes":"No"}/></dl></article><article><h2>Primary Material</h2><dl><Field label="Material" value={p.primaryMaterialName??dash}/></dl></article><Versions product={p} canEdit={canEdit} organizationId={organizationId} sessionScope={sessionScope} onEditDraft={openDraft}/></div></section>;
};
