import assert from "node:assert/strict";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ProductWorkspace } from "./ProductWorkspace";
const item={productId:"product-a",displayName:"Rigid Sign",category:"Signs",lifecycle:"active_with_draft" as const,measurementMode:"dimensions_required" as const,pricingSummary:"Per sq ft",productType:{displayName:"Flatbed",routePolicy:"route_required" as const},primaryMaterialName:"Coroplast",hasDraft:true,activeVersion:{label:"Published 2026-08-17"}};
const listClient=new QueryClient();listClient.setQueryData(["v2","scope-a","org-a","products","",1],{items:[item],page:1,pageSize:50,total:1,hasMore:false});const list=renderToStaticMarkup(<QueryClientProvider client={listClient}><ProductWorkspace organizationId="org-a" sessionScope="scope-a" productId="" canView canEdit openProduct={()=>{}} backToCatalog={()=>{}}/></QueryClientProvider>);for(const text of ["Products","Rigid Sign","Signs","Per sq ft","Flatbed","Primary Material","Active"])assert.match(list,new RegExp(text));for(const text of ["product-a","Configuration ID","Content hash","New Product"])assert.doesNotMatch(list,new RegExp(text));
const activeDefinition={productVersionId:"active-a",options:[{label:"Print Sides",inputType:"select",required:true,defaultLabel:"Single sided",choices:[{label:"Single sided",value:"single"},{label:"Double sided",value:"double"}]}],pricing:{mode:"matrix" as const,minimumChargeCents:500,tiers:[],matrix:{pricingUnit:"per_square_foot" as const,dimensions:["Thickness","Print Sides"],rows:[{selections:["Thickness: 4mm","Print Sides: Double sided"],baseRateCents:125,tierCount:0,computedSheetTiers:false}]}},recipe:[{componentId:"component-4mm",materialName:"Coroplast - 4mm",quantity:"1",unit:"square_foot",basis:"per_area",replacesCompatibility:true}],productionUnits:[{key:"front",side:"front"},{key:"back",side:"back",condition:"When Print Sides = Double sided"}],routing:{mode:"route_required" as const,templateName:"Standard Production",revision:"1",steps:["proofing","prepress","production","fulfillment"]}};
const detailClient=new QueryClient();detailClient.setQueryData(["v2","scope-a","org-a","products","product-a"],{...item,productUpdatedAt:"2026-08-18T00:00:00.000Z",workflowIntent:"standard_production" as const,requiresProductionJob:true,requiresProofApproval:false,configurableOptionCount:4,activeDefinition,versions:{active:{productVersionId:"active-a",status:"active" as const,createdAt:"2026-08-15T00:00:00.000Z",updatedAt:"2026-08-17T00:00:00.000Z",publishedAt:"2026-08-17T00:00:00.000Z",editable:false},draft:{productVersionId:"draft-a",status:"draft" as const,createdAt:"2026-08-18T00:00:00.000Z",updatedAt:"2026-08-18T00:00:00.000Z",editable:true},history:[{productVersionId:"deprecated-a",status:"deprecated" as const,createdAt:"2026-08-14T00:00:00.000Z",updatedAt:"2026-08-16T00:00:00.000Z",publishedAt:"2026-08-16T00:00:00.000Z",editable:false}],historyLimit:25,historyHasMore:false,canCreateDraft:false}});const detail=renderToStaticMarkup(<QueryClientProvider client={detailClient}><ProductWorkspace organizationId="org-a" sessionScope="scope-a" productId="product-a" canView canEdit openProduct={()=>{}} backToCatalog={()=>{}}/></QueryClientProvider>);for(const text of ["Product details","Pricing","Production policy","Primary Material","Versions","History","4 options","Publish Draft","Active Product definition","Print Sides","Matrix","Coroplast - 4mm","Standard Production","When Print Sides = Double sided"])assert.match(detail,new RegExp(text));assert.doesNotMatch(detail,/product-a/);console.log("Product workspace visual contract tests passed.");
