import assert from "node:assert/strict";
import { artworkPath, contactPath, customerPath, fulfillmentPath, invoicePath, orderPath, productBuilderPath, productPath, productionPath, proofingPath, quotePath, readArtworkLocation, readContactLocation, readCustomerLocation, readFulfillmentLocation, readInvoiceLocation, readOrderLocation, readProductBuilderLocation, readProductLocation, readProductionLocation, readProofingLocation, readQuoteLocation, readWorkspaceLocation, workspacePath } from "./productRouting";

assert.deepEqual(readProductLocation("/products"), {});
assert.deepEqual(readProductLocation("/products/product-a"), { productId: "product-a" });
assert.deepEqual(readProductLocation("/products/product%2Da"), { productId: "product-a" });
assert.equal(readProductLocation("/products/%2Fwrong"), null);
assert.equal(readProductLocation("/quotes"), null);
assert.equal(productPath("product a"), "/products/product%20a");
assert.deepEqual(readProductBuilderLocation("/product-builder"), {});
assert.deepEqual(readProductBuilderLocation("/product-builder/product-a"), { productId: "product-a" });
assert.equal(readProductBuilderLocation("/product-builder/%2Fwrong"), null);
assert.equal(productBuilderPath("product a"), "/product-builder/product%20a?draft=1");
assert.deepEqual(readWorkspaceLocation("/product-builder/product-a"), { page: "productBuilder", productId: "product-a" });
assert.deepEqual(readCustomerLocation("/customers"), {});
assert.deepEqual(readCustomerLocation("/customers/customer-a"), { customerId: "customer-a" });
assert.equal(readCustomerLocation("/customers/%2Fwrong"), null);
assert.deepEqual(readWorkspaceLocation("/customers/customer-a"), { page: "customers", customerId: "customer-a" });
assert.deepEqual(readWorkspaceLocation("/products/product-a"), { page: "products", productId: "product-a" });
assert.equal(customerPath("customer a"), "/customers/customer%20a");
assert.deepEqual(readContactLocation("/contacts"), {});
assert.deepEqual(readContactLocation("/contacts/contact-a"), { contactId: "contact-a" });
assert.equal(readContactLocation("/contacts/%2Fwrong"), null);
assert.deepEqual(readWorkspaceLocation("/contacts/contact-a"), { page: "contacts", contactId: "contact-a" });
assert.equal(contactPath("contact a"), "/contacts/contact%20a");
assert.deepEqual(readWorkspaceLocation("/artwork"), { page: "artwork" });
assert.deepEqual(readArtworkLocation("/artwork/orders/order-a/lines/line-a"), { orderId: "order-a", lineId: "line-a" });
assert.deepEqual(readWorkspaceLocation("/artwork/orders/order-a"), { page: "artwork", orderId: "order-a" });
assert.deepEqual(readWorkspaceLocation("/artwork/orders/order-a/lines/line-a"), { page: "artwork", orderId: "order-a", lineId: "line-a" });
assert.equal(artworkPath("order a", "line a"), "/artwork/orders/order%20a/lines/line%20a");
assert.deepEqual(readWorkspaceLocation("/proofing"), { page: "proofing" });
assert.deepEqual(readProofingLocation("/proofing/works/proof-a"), { proofWorkId: "proof-a" });
assert.deepEqual(readWorkspaceLocation("/proofing/works/proof-a"), { page: "proofing", proofWorkId: "proof-a" });
assert.equal(proofingPath("proof a"), "/proofing/works/proof%20a");
assert.deepEqual(readProofingLocation("/proofing/orders/order-a/lines/line-a"), { orderId: "order-a", lineId: "line-a" });
assert.deepEqual(readWorkspaceLocation("/proofing/orders/order-a/lines/line-a"), { page: "proofing", orderId: "order-a", lineId: "line-a" });
assert.equal(proofingPath(undefined, "order a", "line a"), "/proofing/orders/order%20a/lines/line%20a");
assert.deepEqual(readWorkspaceLocation("/prepress"), { page: "prepress" });
assert.equal(workspacePath("artwork"), "/artwork");
assert.deepEqual(readQuoteLocation("/quotes/quote-a"), { quoteId: "quote-a" });
assert.deepEqual(readOrderLocation("/orders/order-a"), { orderId: "order-a" });
assert.deepEqual(readWorkspaceLocation("/quotes/quote-a"), { page: "quotes", quoteId: "quote-a" });
assert.deepEqual(readWorkspaceLocation("/orders/order-a"), { page: "orders", orderId: "order-a" });
assert.equal(quotePath("quote a"), "/quotes/quote%20a");
assert.equal(orderPath("order a"), "/orders/order%20a");
assert.deepEqual(readInvoiceLocation("/invoices/invoice-a"), { invoiceId: "invoice-a" });
assert.deepEqual(readWorkspaceLocation("/invoices"), { page: "invoices" });
assert.deepEqual(readWorkspaceLocation("/invoices/invoice-a"), { page: "invoices", invoiceId: "invoice-a" });
assert.equal(invoicePath("invoice a"), "/invoices/invoice%20a");
assert.deepEqual(readFulfillmentLocation("/fulfillment/orders/order-a"), { orderId: "order-a" });
assert.deepEqual(readWorkspaceLocation("/fulfillment"), { page: "fulfillment" });
assert.deepEqual(readWorkspaceLocation("/fulfillment/orders/order-a"), { page: "fulfillment", orderId: "order-a" });
assert.equal(fulfillmentPath("order a"), "/fulfillment/orders/order%20a");
assert.deepEqual(readProductionLocation("/production/flatbed"), { station: "flatbed" });
assert.deepEqual(readWorkspaceLocation("/production"), { page: "production" });
assert.deepEqual(readWorkspaceLocation("/production/roll"), { page: "production", station: "roll" });
assert.equal(productionPath("flatbed"), "/production/flatbed");
assert.deepEqual(readWorkspaceLocation("/payments"), { page: "payments" });
assert.equal(workspacePath("payments"), "/payments");
assert.deepEqual(readWorkspaceLocation("/routing"), { page: "routing" });
assert.equal(workspacePath("routing"), "/routing");
assert.deepEqual(readWorkspaceLocation("/"), { page: "home" });
assert.deepEqual(readWorkspaceLocation("/appearance"), { page: "appearance" });
