import React, { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { artworkApi, newBusinessRequestId, orderApi, proofingApi, type ApiError, type ArtworkOrderProjection, type OrderRead, type ProofQueueItem, type ProofWorkProjection } from "./api";

const keys = {
  queue: (scope: string, organizationId: string) => ["v2", scope, organizationId, "proofing", "works"] as const,
  work: (scope: string, organizationId: string, proofWorkId: string) => ["v2", scope, organizationId, "proofing", "work", proofWorkId] as const,
  artwork: (scope: string, organizationId: string, orderId: string) => ["v2", scope, organizationId, "artwork", "order", orderId] as const,
};
const status = (item: ProofQueueItem) => !item.latest ? "Draft" : item.latest.outcome === "approved" ? "Approved" : item.latest.outcome === "revision_requested" ? "Revision Requested" : item.latest.issuedAt ? "Issued" : "Draft";
const versionStatus = (entry: ProofWorkProjection["versions"][number]) => entry.response?.outcome?.replaceAll("_", " ") ?? (entry.version.issuedAt ? "Issued" : "Draft");
const errorText = (error: unknown) => (error as ApiError | undefined)?.message ?? "The Proofing operation could not be completed.";
export type ProofingOrderLineContext = Readonly<{ order: OrderRead; line: OrderRead["order"]["lines"][number]; sourceArtwork: readonly ArtworkOrderProjection[] }>;

export const ProofingWorkspace = ({ organizationId, sessionScope, canView, canPrepare = false, canIssue = false, canRespond = false, proofWorkId, orderId, lineId }: { organizationId: string; sessionScope: string; canView: boolean; canPrepare?: boolean; canIssue?: boolean; canRespond?: boolean; proofWorkId?: string; orderId?: string; lineId?: string }) => {
  const client = useQueryClient(); const [selectedId, setSelectedId] = useState(""); const [search, setSearch] = useState("");
  const queue = useQuery({ queryKey: keys.queue(sessionScope, organizationId), queryFn: () => proofingApi.list(organizationId), enabled: Boolean(canView && organizationId && sessionScope) });
  useEffect(() => { if (proofWorkId) setSelectedId(proofWorkId); }, [proofWorkId]);
  useEffect(() => { if (!proofWorkId && !selectedId && queue.data?.[0]) setSelectedId(queue.data[0].work.proofWorkId); }, [proofWorkId, queue.data, selectedId]);
  const scopedWork = useMemo(() => orderId && lineId ? queue.data?.find((item) => item.work.orderId === orderId && item.work.orderLineId === lineId) : undefined, [lineId, orderId, queue.data]);
  useEffect(() => { if (!proofWorkId && scopedWork) setSelectedId(scopedWork.work.proofWorkId); }, [proofWorkId, scopedWork]);
  const work = useQuery({ queryKey: keys.work(sessionScope, organizationId, selectedId), queryFn: () => proofingApi.get(organizationId, selectedId), enabled: Boolean(selectedId && canView) });
  const contextOrderId = orderId ?? work.data?.work.orderId ?? ""; const contextLineId = lineId ?? work.data?.work.orderLineId ?? "";
  const order = useQuery({ queryKey: ["v2", sessionScope, organizationId, "orders", contextOrderId], queryFn: () => orderApi.get(organizationId, contextOrderId), enabled: Boolean(contextOrderId && canView) });
  const artwork = useQuery({ queryKey: keys.artwork(sessionScope, organizationId, contextOrderId), queryFn: () => artworkApi.forOrder(organizationId, contextOrderId), enabled: Boolean(contextOrderId && canView) });
  const line = order.data?.order.lines.find((candidate) => candidate.lineId === contextLineId);
  const sourceArtwork = useMemo(() => (artwork.data ?? []).filter((item) => item.assignment.orderLineId === contextLineId && (item.assignment.purpose === "customer_supplied" || item.assignment.purpose === "reference")), [artwork.data, contextLineId]);
  const context = order.data && line ? { order: order.data, line, sourceArtwork } : undefined;
  const refresh = async (nextWorkId?: string) => { if (nextWorkId) setSelectedId(nextWorkId); await client.invalidateQueries({ queryKey: keys.queue(sessionScope, organizationId) }); await client.invalidateQueries({ queryKey: keys.work(sessionScope, organizationId, nextWorkId ?? selectedId) }); };
  const entries = useMemo(() => queue.data?.filter((item) => `${item.orderNumber} ${item.customerDisplayName} ${item.lineDescription}`.toLowerCase().includes(search.toLowerCase())) ?? [], [queue.data, search]);
  if (!organizationId || !canView) return <section className="v2-proofing"><div className="v2-proof-empty">{!organizationId ? "Enter an authenticated organization in Sales before opening Proofing." : "You do not have permission to view Proofing."}</div></section>;
  return <section className="v2-proofing"><aside className="v2-proof-queue"><header><div><h2>Proof Queue</h2><span>{queue.data?.length ?? 0} proofs</span></div><input aria-label="Search proof queue" placeholder="Order, customer, item" value={search} onChange={(event) => setSearch(event.target.value)} /></header><div className="v2-proof-queue-list">{entries.map((item) => <button type="button" key={item.work.proofWorkId} onClick={() => setSelectedId(item.work.proofWorkId)} className={selectedId === item.work.proofWorkId ? "active" : ""}><strong>#{item.orderNumber}</strong><b>{item.lineDescription}</b><span>{item.customerDisplayName}</span><em data-status={status(item)}>{status(item)}</em></button>)}</div></aside><main className="v2-proof-main">{work.isLoading || order.isLoading || artwork.isLoading ? <div className="skeleton" /> : !work.data && !context ? <div className="v2-proof-empty">Open Proofing from an Order line to start canonical Proof Work.</div> : <>{context && <Context context={context} />}{work.data && work.data.versions.length > 0 && <ProofHistory projection={work.data} />}<ProofWorkflowActions organizationId={organizationId} context={context} projection={work.data} canPrepare={canPrepare} canIssue={canIssue} canRespond={canRespond} onRefresh={refresh} /></>}</main></section>;
};

const Context = ({ context }: { context: ProofingOrderLineContext }) => <section className="v2-proof-source"><div><small>Order</small><strong>#{context.order.number.display}</strong><span>Authenticated Order context</span></div><div><small>Line item</small><strong>{context.line.description}</strong><span>{context.sourceArtwork.length ? `${context.sourceArtwork.length} canonical Artwork item${context.sourceArtwork.length === 1 ? "" : "s"} ready` : "Artwork required before Proofing can start"}</span></div><span>Proofing owns durable review evidence; Routing owns route progression.</span></section>;

export const ProofWorkflowActions = ({ organizationId, context, projection, canPrepare, canIssue, canRespond, onRefresh }: Readonly<{ organizationId: string; context?: ProofingOrderLineContext; projection?: ProofWorkProjection; canPrepare: boolean; canIssue: boolean; canRespond: boolean; onRefresh: (proofWorkId?: string) => Promise<void> }>) => {
  const [notice, setNotice] = useState(""); const [comment, setComment] = useState(""); const latest = projection?.versions[0]; const assignments = context?.sourceArtwork.map((item) => item.assignment.id) ?? [];
  const start = useMutation({ mutationFn: () => proofingApi.start(organizationId, newBusinessRequestId(), context!.order.order.orderId, context!.line.lineId), onSuccess: async (result) => { setNotice("Proof Work started from canonical Artwork."); await onRefresh(result.work.proofWorkId); }, onError: (error) => setNotice(errorText(error)) });
  const createVersion = useMutation({ mutationFn: () => proofingApi.createVersion(organizationId, projection!.work.proofWorkId, newBusinessRequestId(), assignments), onSuccess: async () => { setNotice("Proof Version created from immutable Artwork evidence."); await onRefresh(projection!.work.proofWorkId); }, onError: (error) => setNotice(errorText(error)) });
  const issue = useMutation({ mutationFn: () => proofingApi.issue(organizationId, latest!.version.proofVersionId, newBusinessRequestId()), onSuccess: async () => { setNotice("Proof issued for response. No external delivery was performed."); await onRefresh(projection!.work.proofWorkId); }, onError: (error) => setNotice(errorText(error)) });
  const respond = useMutation({ mutationFn: (outcome: "approved" | "revision_requested") => proofingApi.respond(organizationId, latest!.version.proofVersionId, newBusinessRequestId(), outcome, comment, context?.order.order.customerContact.customerId), onSuccess: async (_, outcome) => { setNotice(outcome === "approved" ? "Approval recorded as canonical Proofing evidence." : "Revision request recorded; create the next Proof Version when ready."); setComment(""); await onRefresh(projection!.work.proofWorkId); }, onError: (error) => setNotice(errorText(error)) });
  const pending = start.isPending || createVersion.isPending || issue.isPending || respond.isPending;
  if (!context) return <div className="v2-proof-empty">The selected Proof Work has no readable Order-line context.</div>;
  if (!projection) return <Action title="Proofing workflow" notice={notice}>{assignments.length ? <><p>Canonical Artwork is ready. Start durable Proof Work for this Order line.</p>{canPrepare ? <button type="button" className="button" disabled={pending} onClick={() => start.mutate()}>{start.isPending ? "Starting…" : "Start Proofing"}</button> : <Permission />}</> : <p>Canonical customer-supplied or reference Artwork is required before Proofing can start.</p>}</Action>;
  if (!latest) return <Action title="Proofing workflow" notice={notice}><p>Create the first immutable Proof Version from the canonical Artwork shown above.</p>{canPrepare ? <button type="button" className="button" disabled={!assignments.length || pending} onClick={() => createVersion.mutate()}>Create Proof Version</button> : <Permission />}</Action>;
  if (latest.response?.outcome === "approved") return <Action title="Proofing complete" notice={notice}><p>Issued Proof Version v{latest.version.sequence} has canonical approval evidence. Routing may now evaluate its own frozen prerequisite.</p></Action>;
  if (latest.response?.outcome === "revision_requested") return <Action title="Revision requested" notice={notice}><p>Version v{latest.version.sequence} remains immutable.</p>{canPrepare && <button type="button" className="button" disabled={pending} onClick={() => createVersion.mutate()}>Create Next Proof Version</button>}</Action>;
  if (!latest.version.issuedAt) return <Action title={`Proof Version v${latest.version.sequence}`} notice={notice}><p>Issuing records availability for response; it does not send customer email or SMS.</p>{canIssue ? <button type="button" className="button" disabled={pending} onClick={() => issue.mutate()}>Issue Proof</button> : <Permission />}</Action>;
  return <Action title="Awaiting response" notice={notice}><p>Record the known customer response. This creates immutable Proofing evidence and does not send a message.</p><label className="field">Response note (optional)<textarea aria-label="Proof response note" value={comment} maxLength={8000} onChange={(event) => setComment(event.target.value)} /></label>{canRespond ? <div className="v2-order-context-actions"><button type="button" className="button" disabled={pending} onClick={() => respond.mutate("approved")}>Approve Proof</button><button type="button" className="button secondary" disabled={pending} onClick={() => respond.mutate("revision_requested")}>Request Revision</button></div> : <Permission />}</Action>;
};
const Action = ({ title, notice, children }: { title: string; notice: string; children: React.ReactNode }) => <section className="v2-proof-actions"><h2>{title}</h2>{children}{notice && <p role="status">{notice}</p>}</section>;
const Permission = () => <p className="v2-sales-permission-note">You do not have permission for this Proofing action.</p>;
const ProofHistory = ({ projection }: { projection: ProofWorkProjection }) => <section className="v2-proof-versions"><h2>Immutable Proof History</h2>{projection.versions.map((entry) => <div key={entry.version.proofVersionId}><strong>v{entry.version.sequence}</strong><span>{versionStatus(entry)}</span>{entry.response?.comment && <p>{entry.response.comment}</p>}</div>)}</section>;
