import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { quickBooksIntegrationApi, type ApiError, type QuickBooksOperationsRead } from "./api";
import { quickBooksIntegrationCallbackNotice } from "./quickBooksIntegrationCallbackNotice";

const label=(value:string)=>({not_connected:"Not connected",connected_sandbox:"Connected · Sandbox",connected_production:"Connected · Production",connected_unknown:"Connected · Mode unknown",authorization_required:"Authorization required",reconnect_required:"Reconnect required",worker_not_ready:"Worker not ready",sync_ready:"Sync ready",action_required:"Action required"} as Record<string,string>)[value]??"Unknown";
const money=(cents:number|null,currency:string|null)=>cents===null?"—":new Intl.NumberFormat(undefined,{style:"currency",currency:currency??"USD"}).format(cents/100);
const kind=(value:"invoice"|"payment"|"refund")=>value[0]!.toUpperCase()+value.slice(1);
const reason=(value:string|null)=>value??"Review this record before the automatic worker can continue.";

/** Settings is intentionally the single QuickBooks operator console. It shows
 * provider readiness, bounded compatibility imports, queue-only exports, and
 * safe recovery without placing integration controls in Finance. */
export const QuickBooksSettingsWorkspace=({organizationId,sessionScope,canConfigure}:{organizationId:string;sessionScope:string;canConfigure:boolean})=>{
  const client=useQueryClient(); const key=["v2",sessionScope,organizationId,"settings","accounting"] as const;
  const operationsKey=[...key,"operations"] as const;
  const [invoiceScope,setInvoiceScope]=useState<"open_ar"|"historical"|"all_unsynced">("open_ar");
  const [invoicePage,setInvoicePage]=useState(1); const [importSelection,setImportSelection]=useState<Set<string>>(()=>new Set()); const [syncSelection,setSyncSelection]=useState<Set<string>>(()=>new Set());
  const callbackNotice=typeof window === "undefined" ? undefined : quickBooksIntegrationCallbackNotice(window.location.search);
  const query=useQuery({queryKey:key,queryFn:()=>quickBooksIntegrationApi.get(organizationId),enabled:Boolean(organizationId&&sessionScope&&canConfigure)});
  const operations=useQuery({queryKey:operationsKey,queryFn:()=>quickBooksIntegrationApi.operations(organizationId),enabled:Boolean(organizationId&&sessionScope&&canConfigure)});
  const invoicePreview=useQuery({queryKey:[...key,"invoice-import",invoiceScope,invoicePage],queryFn:()=>quickBooksIntegrationApi.invoiceImportPreview(organizationId,invoiceScope,invoicePage),enabled:Boolean(organizationId&&sessionScope&&canConfigure&&query.data?.connected)});
  const customerPreview=useQuery({queryKey:[...key,"customer-import"],queryFn:()=>quickBooksIntegrationApi.customerImportPreview(organizationId),enabled:false});
  const refresh=async()=>{await client.invalidateQueries({queryKey:key});await client.invalidateQueries({queryKey:operationsKey});};
  const connect=useMutation({mutationFn:()=>quickBooksIntegrationApi.connect(organizationId),onSuccess:(value)=>window.location.assign(value.authorizeUrl)});
  const disconnect=useMutation({mutationFn:()=>quickBooksIntegrationApi.disconnect(organizationId),onSuccess:refresh});
  const sync=useMutation({mutationFn:()=>quickBooksIntegrationApi.syncSelected(organizationId,[...syncSelection]),onSuccess:async()=>{setSyncSelection(new Set());await refresh();}});
  const retry=useMutation({mutationFn:({subjectKind,subjectId}:{subjectKind:"invoice"|"payment"|"refund";subjectId:string})=>quickBooksIntegrationApi.retry(organizationId,subjectKind,subjectId),onSuccess:refresh});
  const importInvoices=useMutation({mutationFn:()=>quickBooksIntegrationApi.importInvoices(organizationId,[...importSelection].map(qbId=>{const row=invoicePreview.data?.rows.find(item=>item.qbInvoiceId===qbId);return {qbId,classification:row?.classification??"historical"};})),onSuccess:async()=>{setImportSelection(new Set());await client.invalidateQueries({queryKey:[...key,"invoice-import"]});}});
  if(!canConfigure)return <main className="lab"><h1>Accounting</h1><p>You do not have permission to configure Accounting.</p></main>;
  const value=query.data; const error=(query.error??operations.error??connect.error??disconnect.error??sync.error??retry.error??importInvoices.error) as unknown as ApiError|undefined;
  const reconnect=value?.state==="authorization_required"||value?.state==="reconnect_required";
  const activity=operations.data?.activity??[]; const failures=activity.filter(item=>item.state==="blocked"||item.state==="uncertain"||item.state==="retry");
  const toggle=(current:Set<string>,id:string,set:(value:Set<string>)=>void)=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);set(next);};
  return <main className="lab v2-sales-tax-settings"><header><small>SETTINGS · INTEGRATIONS</small><h1>Accounting</h1><p>One console for QuickBooks connection, bounded compatibility import, V2 queue-only synchronization, and recovery. Credentials and provider payloads remain server-side.</p></header>
    {query.isLoading?<p>Loading accounting readiness…</p>:<>
      <section className="v2-sales-notes"><h2>1. Connection</h2>{callbackNotice&&<p className="notice error">{callbackNotice}</p>}<p><b>Status:</b> {label(value?.state??"not_connected")}</p><p><b>Connection mode:</b> {(value?.environment??"unknown").toUpperCase()}</p>{value?.connectedCompanyName&&<p><b>Connected company:</b> {value.connectedCompanyName}</p>}<p>{value?.actionRequired??"Sync worker ready. QuickBooks receives a projection of canonical V2 Billing facts."}</p>{value?.state!=="sync_ready"&&<button className="button" type="button" disabled={connect.isPending} onClick={()=>connect.mutate()}>{connect.isPending?"Opening QuickBooks…":reconnect?"Reconnect QuickBooks":"Connect QuickBooks"}</button>}{value?.connected&&<button className="button secondary" type="button" disabled={disconnect.isPending} onClick={()=>disconnect.mutate()}>{disconnect.isPending?"Disconnecting…":"Disconnect QuickBooks"}</button>}</section>
      <section className="v2-sales-notes"><h2>2. Import from QuickBooks</h2><p>Preview first, then explicitly adopt no more than 100 compatibility records. Imported historical documents retain their QuickBooks Doc # and never become outbound V2 invoices.</p><div><button className="button secondary" disabled={customerPreview.isFetching||!value?.connected} onClick={()=>customerPreview.refetch()}>{customerPreview.isFetching?"Loading Customers…":"Preview Customers"}</button>{customerPreview.data&&<p>{customerPreview.data.length} Customers reviewed · {customerPreview.data.filter(row=>row.contactNeedsReview).length} require contact review. No customer is silently guessed.</p>}</div><label>Invoice scope <select value={invoiceScope} onChange={event=>{setInvoiceScope(event.target.value as typeof invoiceScope);setInvoicePage(1);setImportSelection(new Set());}}><option value="open_ar">Open A/R</option><option value="historical">Historical</option><option value="all_unsynced">All unsynced</option></select></label>{invoicePreview.isLoading?<p>Loading bounded Invoice preview…</p>:<>{invoicePreview.data?.rows.length? <><div className="v2-finance-quickbooks-selection-items">{invoicePreview.data.rows.map(row=><label key={row.qbInvoiceId}><input type="checkbox" disabled={!row.canImport} checked={importSelection.has(row.qbInvoiceId)} onChange={()=>toggle(importSelection,row.qbInvoiceId,setImportSelection)}/>{row.qbDocNumber||row.qbInvoiceId} · {row.customerRefName||"Customer unavailable"} · {row.classification}{row.canImport?"":` · ${row.cannotImportReason??"review required"}`}</label>)}</div><button className="button" disabled={!importSelection.size||importInvoices.isPending} onClick={()=>importInvoices.mutate()}>{importInvoices.isPending?"Importing…":`Import selected (${importSelection.size})`}</button></>:<p>No eligible QuickBooks Invoices in this bounded preview.</p>}<button className="button secondary" disabled={invoicePage<=1} onClick={()=>setInvoicePage(page=>page-1)}>Previous</button><button className="button secondary" disabled={!invoicePreview.data?.hasNextPage} onClick={()=>setInvoicePage(page=>page+1)}>Next</button>{importInvoices.data&&<p>Import result: {importInvoices.data.created} created, {importInvoices.data.updated} updated, {importInvoices.data.skipped} skipped, {importInvoices.data.failed} failed.</p>}</>}</section>
      <section className="v2-sales-notes"><h2>3. Sync to QuickBooks</h2><p>Selected issued V2 Invoices enqueue the same canonical accounting queue. The browser never directly writes to QuickBooks.</p>{operations.isLoading?<p>Loading eligible V2 Invoices…</p>:operations.data?.eligibleInvoices.length?<><div className="v2-finance-quickbooks-selection-items">{operations.data.eligibleInvoices.map(row=><label key={row.invoiceId}><input type="checkbox" checked={syncSelection.has(row.invoiceId)} onChange={()=>toggle(syncSelection,row.invoiceId,setSyncSelection)}/>{row.displayNumber} · {row.customerName} · {money(row.totalCents,row.currency)}</label>)}</div><button className="button" disabled={!syncSelection.size||sync.isPending} onClick={()=>sync.mutate()}>{sync.isPending?"Queueing…":`Sync selected (${syncSelection.size})`}</button></>:<p>No eligible unsynced V2 Invoices. Completed records remain protected from duplicate export.</p>}</section>
      <section className="v2-sales-notes"><h2>4. Sync Queue / Activity</h2><p>The worker runs automatically. This activity view intentionally omits lease IDs and provider payloads.</p>{activity.length?<div className="v2-finance-quickbooks-selection-items">{activity.map(row=><div key={row.jobId}><b>{kind(row.subjectKind)}</b> · {row.displayNumber} · {money(row.amountCents,row.currency)} · <b>{row.state}</b><br/><small>Attempts {row.attemptCount} · last activity {new Date(row.updatedAt).toLocaleString()} · {row.completedAt?`succeeded ${new Date(row.completedAt).toLocaleString()}`:"not yet completed"}{row.providerId?" · provider linked":""}</small></div>)}</div>:<p>No V2 QuickBooks activity yet.</p>}</section>
      <section className="v2-sales-notes"><h2>5. Action Required / Failures</h2>{failures.length?<div className="v2-finance-quickbooks-selection-items">{failures.map(row=><div key={`failure-${row.jobId}`}><b>{kind(row.subjectKind)} · {row.displayNumber}</b><p>{reason(row.lastError)}</p>{row.state==="uncertain"?<p>Provider reconciliation is required before retry; no blind retry is available.</p>:row.retryEligible&&<button className="button" disabled={retry.isPending} onClick={()=>retry.mutate({subjectKind:row.subjectKind,subjectId:row.subjectId})}>{retry.isPending?"Queueing recovery…":`Retry ${kind(row.subjectKind)} Sync`}</button>}</div>)}</div>:<p>No QuickBooks action is currently required.</p>}</section>
      {error&&<p className="notice error">{error.message??"Accounting integration is unavailable."}</p>}
    </>}</main>;
};
