import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const source = readFileSync(resolve("v2/ui/src/QuickBooksSettingsWorkspace.tsx"), "utf8");
const styles = readFileSync(resolve("v2/ui/src/QuickBooksSettingsWorkspace.css"), "utf8");

assert.match(source, /QuickBooks operational health/);
assert.match(source, /Operators approve each current Invoice version, then Force Sync/);
assert.match(source, /Approved current V2 Invoice versions queue automatically/);
assert.match(source, /Review invoice accounting work/);
assert.match(source, /Approve for accounting/);
assert.match(source, /Approval required/);
assert.match(source, /Force Sync selected/);
assert.match(source, /row\.accountingApproval!=="approved"/);
assert.match(source, /Open financial facts/);
assert.match(source, /Review activity/);
assert.match(source, /Open import preview/);
assert.match(source, /Select visible/);
assert.match(source, /Clear selection/);
assert.match(source, /setSelection\(new Set\(\)\)/);
assert.match(source, /setFinancialSelection\(new Set\(\)\)/);
assert.match(source, /selection\.size > 100/);
assert.match(source, /financialSelection\.size > 100/);
assert.match(source, /Reconcile & resume/);
assert.match(source, /Retry sync/);
assert.match(source, /No V2 invoices need synchronization/);
assert.match(source, /Nothing needs action/);
assert.match(source, /quickBooksCompanyConnectionCopy/);
assert.match(source, /Dismiss QuickBooks authorization notice/);
assert.match(source, /Company association retained · authorization required/);
assert.match(source, /state\?\.companyAssociated && <button/);
assert.match(styles, /\.v2-quickbooks-health span\{[^}]*white-space:normal/);
console.log("QuickBooks operations console presentation contracts passed.");
