import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { newBusinessRequestId, taxSettingsApi, type ApiError, type SalesTaxJurisdiction } from "./api";

const percentage = (basisPoints:number) => (basisPoints / 100).toFixed(2).replace(/\.00$/u, "").replace(/(\.\d)0$/u, "$1");
const state = (value:string) => value === "ready" ? "Ready" : value === "conflict" ? "Conflict" : value === "needs_attention" ? "Needs attention" : "Not configured";
type Form = Readonly<{ name:string; countryCode:string; regionCode:string; postalCode:string; ratePercent:string; active:boolean; shipping:boolean; localDelivery:boolean }>;
const blank = ():Form => ({name:"",countryCode:"US",regionCode:"",postalCode:"",ratePercent:"",active:true,shipping:true,localDelivery:true});

export const SalesTaxSettingsWorkspace=({organizationId,sessionScope,canConfigure}:{organizationId:string;sessionScope:string;canConfigure:boolean})=>{
  const client=useQueryClient(); const key=["v2",sessionScope,organizationId,"settings","sales-tax"] as const;
  const [home,setHome]=useState(blank); const [destination,setDestination]=useState(blank); const [notice,setNotice]=useState("");
  const query=useQuery({queryKey:key,queryFn:()=>taxSettingsApi.get(organizationId),enabled:Boolean(organizationId&&sessionScope&&canConfigure)});
  useEffect(()=>{const value=query.data?.homeBusiness;if(!value)return;setHome({name:value.name,countryCode:value.countryCode,regionCode:value.regionCode,postalCode:value.postalCode??"",ratePercent:percentage(value.rateBasisPoints),active:value.active,shipping:true,localDelivery:true});},[query.data?.homeBusiness?.jurisdictionId]);
  const saveHome=useMutation({mutationFn:()=>taxSettingsApi.saveHomeBusiness(organizationId,newBusinessRequestId(),{name:home.name,countryCode:home.countryCode,regionCode:home.regionCode,postalCode:home.postalCode||undefined,ratePercent:home.ratePercent,active:home.active}),onSuccess:(value)=>{client.setQueryData(key,value);setNotice("Home / Business jurisdiction saved.");},onError:(error)=>setNotice((error as unknown as ApiError).message??"Sales Tax settings could not be saved.")});
  const create=useMutation({mutationFn:()=>taxSettingsApi.createDestination(organizationId,newBusinessRequestId(),{expectedRevision:query.data!.revision,name:destination.name,countryCode:destination.countryCode,regionCode:destination.regionCode,postalCode:destination.postalCode||undefined,ratePercent:destination.ratePercent,active:destination.active,destinationMethods:[...(destination.shipping?["shipping" as const]:[]),...(destination.localDelivery?["local_delivery" as const]:[])]}),onSuccess:(value)=>{client.setQueryData(key,value);setDestination(blank());setNotice("Destination jurisdiction saved.");},onError:(error)=>setNotice((error as unknown as ApiError).message??"Destination jurisdiction could not be saved.")});
  const toggle=useMutation({mutationFn:(value:SalesTaxJurisdiction)=>taxSettingsApi.updateDestination(organizationId,value.jurisdictionId,newBusinessRequestId(),{expectedRevision:query.data!.revision,name:value.name,countryCode:value.countryCode,regionCode:value.regionCode,postalCode:value.postalCode,ratePercent:percentage(value.rateBasisPoints),active:!value.active,destinationMethods:value.destinationMethods??["shipping","local_delivery"]}),onSuccess:(value)=>{client.setQueryData(key,value);setNotice("Destination jurisdiction updated.");},onError:(error)=>setNotice((error as unknown as ApiError).message??"Destination jurisdiction could not be updated.")});
  if(!canConfigure)return <section className="v2-settings-future"><h2>Sales Tax</h2><p>You do not have permission to configure Sales Tax for this organization.</p></section>;
  const readiness=query.data?.readiness;
  return <section className="v2-sales-tax-settings"><header><small>SETTINGS · SALES</small><h1>Sales Tax</h1><p>Configure the tenant jurisdictions used to resolve authoritative tax for taxable customer documents. The server calculates and freezes commercial tax evidence.</p></header>
    {query.isLoading?<p>Loading Sales Tax settings…</p>:<>
      <section className="v2-settings-tax-coverage"><h2>Fulfillment coverage</h2><p>Each fulfillment method reports its own readiness. A missing destination rule blocks only documents using that method.</p><div>{([{label:"Pickup",value:readiness?.pickup},{label:"Shipping",value:readiness?.shipping},{label:"Local Delivery",value:readiness?.localDelivery}]).map(({label,value})=> <article key={label}><b>{label}</b><span className={`v2-settings-chip is-${value?.status === "ready" ? "ready" : "attention"}`}>{state(value?.status??"not_configured")}</span><p>{value?.jurisdictionName ? `${value.jurisdictionName} · ${percentage(value.rateBasisPoints ?? 0)}%` : value?.reason ?? "No active jurisdiction is configured."}</p></article>)}</div></section>
      <section className="v2-sales-notes"><h2>Home / business jurisdiction</h2><p>Used only for Pickup. It is independent from destination jurisdiction rules.</p><Fields value={home} setValue={setHome} methods={false}/><button className="button" type="button" disabled={saveHome.isPending} onClick={()=>{setNotice("");saveHome.mutate();}}>{saveHome.isPending?"Saving…":"Save Home / Business tax"}</button></section>
      <section className="v2-sales-notes"><h2>Destination jurisdictions</h2><p>Shipping and Local Delivery resolve against the frozen destination country, region, and optional postal code. Postal-specific rules take precedence over regional rules.</p>{query.data?.destinationJurisdictions.length ? <div className="v2-settings-tax-table">{query.data.destinationJurisdictions.map((item)=><article key={item.jurisdictionId}><div><strong>{item.name}</strong><span>{item.countryCode} / {item.regionCode}{item.postalCode?` / ${item.postalCode}`:" · all postal codes"}</span></div><div><span>{percentage(item.rateBasisPoints)}%</span><small>{item.destinationMethods?.map((method)=>method === "local_delivery" ? "Local Delivery" : "Shipping").join(" · ")}</small></div><button type="button" disabled={toggle.isPending} onClick={()=>toggle.mutate(item)}>{item.active?"Deactivate":"Activate"}</button></article>)}</div>:<p className="v2-settings-empty">No destination jurisdictions are configured. Shipping and Local Delivery remain explicitly not configured.</p>}
      <h3>Add destination jurisdiction</h3><Fields value={destination} setValue={setDestination} methods/><button className="button" type="button" disabled={create.isPending||!query.data?.revision} onClick={()=>{setNotice("");create.mutate();}}>{create.isPending?"Saving…":"Add destination jurisdiction"}</button></section>
      {notice&&<p className={notice.includes("saved")||notice.includes("updated")?"notice":"notice error"}>{notice}</p>}
    </>}
  </section>;
};
const Fields=({value,setValue,methods}:{value:Form;setValue:(next:Form)=>void;methods:boolean})=><div className="v2-sales-inline-grid"><label className="field">Jurisdiction<input value={value.name} onChange={(event)=>setValue({...value,name:event.target.value})} placeholder="Jurisdiction name" /></label><label className="field">Country<input value={value.countryCode} onChange={(event)=>setValue({...value,countryCode:event.target.value})} placeholder="US" /></label><label className="field">Region<input value={value.regionCode} onChange={(event)=>setValue({...value,regionCode:event.target.value})} placeholder="State / province" /></label><label className="field">Postal code (optional)<input value={value.postalCode} onChange={(event)=>setValue({...value,postalCode:event.target.value})} /></label><label className="field">Tax rate (%)<input value={value.ratePercent} inputMode="decimal" onChange={(event)=>setValue({...value,ratePercent:event.target.value})} placeholder="7.25" /></label><label className="field"><input type="checkbox" checked={value.active} onChange={(event)=>setValue({...value,active:event.target.checked})} /> Active</label>{methods&&<><label className="field"><input type="checkbox" checked={value.shipping} onChange={(event)=>setValue({...value,shipping:event.target.checked})} /> Shipping</label><label className="field"><input type="checkbox" checked={value.localDelivery} onChange={(event)=>setValue({...value,localDelivery:event.target.checked})} /> Local Delivery</label></>}</div>;
