import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { newBusinessRequestId, taxSettingsApi, type ApiError } from "./api";

const percentage = (basisPoints:number) => (basisPoints / 100).toFixed(2).replace(/\.00$/u, "").replace(/(\.\d)0$/u,"$1");
export const SalesTaxSettingsWorkspace=({organizationId,sessionScope,canConfigure}:{organizationId:string;sessionScope:string;canConfigure:boolean})=>{
  const client=useQueryClient(); const [name,setName]=useState("");const [country,setCountry]=useState("US");const [region,setRegion]=useState("");const [postal,setPostal]=useState("");const [rate,setRate]=useState("");const [active,setActive]=useState(true);const [notice,setNotice]=useState("");
  const query=useQuery({queryKey:["v2",sessionScope,organizationId,"settings","sales-tax"],queryFn:()=>taxSettingsApi.get(organizationId),enabled:Boolean(organizationId&&sessionScope&&canConfigure)});
  useEffect(()=>{const value=query.data?.homeBusiness;if(!value)return;setName(value.name);setCountry(value.countryCode);setRegion(value.regionCode);setPostal(value.postalCode??"");setRate(percentage(value.rateBasisPoints));setActive(value.active);},[query.data?.homeBusiness?.jurisdictionId]);
  const save=useMutation({mutationFn:()=>taxSettingsApi.saveHomeBusiness(organizationId,newBusinessRequestId(),{name,countryCode:country,regionCode:region,postalCode:postal||undefined,ratePercent:rate,active}),onSuccess:(value)=>{client.setQueryData(["v2",sessionScope,organizationId,"settings","sales-tax"],value);setNotice("Sales Tax settings saved.");},onError:(error)=>setNotice((error as unknown as ApiError).message??"Sales Tax settings could not be saved.")});
  if(!canConfigure)return <main className="lab"><h1>Sales Tax</h1><p>You do not have permission to configure Sales Tax for this organization.</p></main>;
  const current=query.data?.homeBusiness;
  return <main className="lab v2-sales-tax-settings"><header><small>SETTINGS</small><h1>Sales Tax</h1><p>Configure the active Home / Business jurisdiction used for Pickup orders. Sales applies this configuration server-side when it freezes commercial tax evidence.</p></header>{query.isLoading?<p>Loading Sales Tax settings…</p>:<section className="v2-sales-notes"><h2>Home / Business</h2><p>{current?`Pickup currently uses ${current.name}.`:"No Home / Business jurisdiction is configured. Pickup Quotes cannot resolve authoritative tax until one is saved."}</p><div className="v2-sales-inline-grid"><label className="field">Jurisdiction<input value={name} disabled={save.isPending} onChange={e=>setName(e.target.value)} placeholder="Jurisdiction name" /></label><label className="field">Country<input value={country} disabled={save.isPending} onChange={e=>setCountry(e.target.value)} placeholder="US" /></label><label className="field">Region<input value={region} disabled={save.isPending} onChange={e=>setRegion(e.target.value)} placeholder="State / province" /></label><label className="field">Postal code (optional)<input value={postal} disabled={save.isPending} onChange={e=>setPostal(e.target.value)} /></label><label className="field">Tax rate (%)<input value={rate} inputMode="decimal" disabled={save.isPending} onChange={e=>setRate(e.target.value)} placeholder="7.25" /></label></div><label className="field"><input type="checkbox" checked={active} disabled={save.isPending} onChange={e=>setActive(e.target.checked)} /> Active for Pickup tax resolution</label><button className="button" type="button" disabled={save.isPending} onClick={()=>{setNotice("");save.mutate();}}>{save.isPending?"Saving…":"Save Home / Business tax"}</button>{notice&&<p className={notice.includes("saved")?"notice":"notice error"}>{notice}</p>}{current&&<p><b>Current server state:</b> {current.active?"Active":"Inactive"} · {percentage(current.rateBasisPoints)}% · {current.countryCode} / {current.regionCode}{current.postalCode?` / ${current.postalCode}`:""}</p>}</section>}</main>;
};
