import React, { useEffect, useMemo, useState } from "react";
import { fulfillmentApi, newBusinessRequestId, shipmentEconomicsApi, shippingPricingApi, type ApiError, type FulfillmentShipmentCarrierInput, type FulfillmentShipmentContainer, type FulfillmentShipmentDetail, type FulfillmentWorkspaceOrder, type ReplacementObligationProjection, type ShippingPricingPolicyRead, type StaffShipmentEconomics } from "./api";

type Selection = Readonly<{ orderId: string; orderNumber: string; orderLineId: string; description: string; available: number; replacementObligationId?: string; customerId?: string; destination?: unknown; quantity: string }>;
type SelectionByKey = Readonly<Record<string, Selection>>;
const keyOf = (orderId: string, lineId: string, replacementObligationId?: string) => `${orderId}:${lineId}:${replacementObligationId ?? "original"}`;
const message = (error: unknown) => (error as ApiError | undefined)?.message ?? "The shipment operation could not be completed.";
export const shipmentQuantityValid = (quantity: string, available: number) => Number.isInteger(Number(quantity)) && Number(quantity) > 0 && Number(quantity) <= available;
export const groupShipmentAllocations = (items: readonly Readonly<{ orderId: string; orderLineId: string; quantity: string; replacementObligationId?: string }>[]) => items.map(item => ({ orderId: item.orderId, orderLineId: item.orderLineId, quantity: Number(item.quantity), ...(item.replacementObligationId ? { replacementObligationId:item.replacementObligationId } : {}) }));
const carrierInput = (carrierName: string, carrierService: string, trackingNumber: string, notes: string, packageCount: string): FulfillmentShipmentCarrierInput => ({
  ...(carrierName.trim() ? { carrierName: carrierName.trim() } : {}),
  ...(carrierService.trim() ? { carrierService: carrierService.trim() } : {}),
  ...(trackingNumber.trim() ? { trackingNumber: trackingNumber.trim() } : {}),
  ...(notes.trim() ? { notes: notes.trim() } : {}),
  ...(packageCount.trim() ? { packageCount: Number(packageCount) } : {}),
});

/**
 * Bounded shipment composer. It collects operator intent only: the server
 * persists prepared allocations and validates quantity atomically. It never
 * represents a customer handoff or a shipment until canonical finalization
 * can create both facts in one server-owned transaction.
 */
export const ShipmentBuilder = ({ organizationId, csrfReady, canShip, canReplace = false, canManageShippingCost = false, canManageShippingPrice = false, orders, replacementCandidates = [], refresh }: { organizationId: string; csrfReady: boolean; canShip: boolean; canReplace?: boolean; canManageShippingCost?:boolean; canManageShippingPrice?:boolean; orders: readonly FulfillmentWorkspaceOrder[]; replacementCandidates?: readonly ReplacementObligationProjection[]; refresh: () => Promise<void> }) => {
  const [expanded, setExpanded] = useState(false);
  const [selected, setSelected] = useState<SelectionByKey>({});
  const [shipment, setShipment] = useState<FulfillmentShipmentDetail>();
  const [shipments, setShipments] = useState<readonly FulfillmentShipmentContainer[]>([]);
  const [carrierName, setCarrierName] = useState(""); const [carrierService, setCarrierService] = useState(""); const [trackingNumber, setTrackingNumber] = useState(""); const [notes, setNotes] = useState(""); const [packageCount, setPackageCount] = useState(""); const [reason, setReason] = useState("");
  const [pending, setPending] = useState<"create" | "correct" | "cancel" | "finalize" | "load" | undefined>();
  const [notice, setNotice] = useState("");
  const selections = useMemo(() => Object.values(selected), [selected]);
  const prepared = shipment?.status === "prepared";
  const readOnly = Boolean(shipment && !prepared);
   const hasReplacement = selections.some(selection=>Boolean(selection.replacementObligationId));
   const editable = canShip && csrfReady && !pending && !readOnly && (!hasReplacement || canReplace);
  const metadata = () => carrierInput(carrierName, carrierService, trackingNumber, notes, packageCount);
  const allocations = () => groupShipmentAllocations(selections);
  const valid = selections.length > 0 && selections.every(item => shipmentQuantityValid(item.quantity, item.available));
  const resetForm = () => { setShipment(undefined); setSelected({}); setCarrierName(""); setCarrierService(""); setTrackingNumber(""); setNotes(""); setPackageCount(""); setReason(""); setNotice(""); };
  const restore = (detail: FulfillmentShipmentDetail) => {
    const restored: Record<string, Selection> = {};
    for (const allocation of detail.currentPreparedRevision?.allocations ?? []) {
      const order = orders.find(item => item.orderId === allocation.orderId); const line = order?.lines.find(item => item.orderLineId === allocation.orderLineId); if (!order || !line) continue;
       const key = keyOf(order.orderId, line.orderLineId, allocation.replacementObligationId);
      // Prepared allocations are proposed work, not completed fulfillment.
      // Current availability is a UI guard only; correction validation is
      // repeated atomically by the server at save/finalization time.
       const replacement = allocation.replacementObligationId ? replacementCandidates.find(candidate=>candidate.obligation.replacementObligationId===allocation.replacementObligationId) : undefined;
       restored[key] = { orderId: order.orderId, orderNumber: order.number, orderLineId: line.orderLineId, description: line.description, available: replacement?.remainingFulfillmentQuantity ?? line.availableFulfillmentQuantity, ...(allocation.replacementObligationId ? {replacementObligationId:allocation.replacementObligationId}:{}), ...(order.customerId ? { customerId: order.customerId } : {}), ...(order.requestedFulfillment?.destination ? { destination: order.requestedFulfillment.destination } : {}), quantity: String(allocation.quantity) };
    }
    const carrier = detail.currentPreparedRevision?.carrier ?? detail.carrier;
    setShipment(detail); setSelected(restored); setCarrierName(carrier.carrierName ?? ""); setCarrierService(carrier.carrierService ?? ""); setTrackingNumber(carrier.trackingNumber ?? ""); setNotes(carrier.notes ?? ""); setPackageCount(carrier.packageCount === undefined ? "" : String(carrier.packageCount)); setReason("");
  };
  const loadShipments = async () => { setPending("load"); try { setShipments(await fulfillmentApi.listShipments(organizationId)); } catch (error) { setNotice(message(error)); } finally { setPending(undefined); } };
  useEffect(() => { if (expanded) void loadShipments(); }, [expanded, organizationId]);
  const setQuantity = (key: string, quantity: string) => setSelected(current => current[key] ? { ...current, [key]: { ...current[key]!, quantity } } : current);
   const toggle = (order: FulfillmentWorkspaceOrder, line: FulfillmentWorkspaceOrder["lines"][number], replacement?: ReplacementObligationProjection) => {
     if (readOnly) return; const key = keyOf(order.orderId, line.orderLineId,replacement?.obligation.replacementObligationId),available=replacement?.remainingFulfillmentQuantity??line.availableFulfillmentQuantity;
     setSelected(current => { if (current[key]) { const { [key]: _removed, ...rest } = current; return rest; } return { ...current, [key]: { orderId: order.orderId, orderNumber: order.number, orderLineId: line.orderLineId, description: line.description, available, ...(replacement ? {replacementObligationId:replacement.obligation.replacementObligationId}:{}), ...(order.customerId ? { customerId: order.customerId } : {}), ...(order.requestedFulfillment?.destination ? { destination: order.requestedFulfillment.destination } : {}), quantity: String(available) } }; });
  };
  const refreshAll = async () => { await Promise.all([refresh(), loadShipments()]); };
  const create = async () => { if (!valid || !editable) return; setPending("create"); setNotice(""); try { const first = selections[0]!; const created = await fulfillmentApi.createShipment(organizationId, newBusinessRequestId(), { ...(first.customerId ? { customerId: first.customerId } : {}), ...(first.destination ? { destination: first.destination } : {}), carrier: metadata(), allocations: allocations() }); restore(created); setNotice(`Prepared shipment ${created.shipmentId}. Its allocations are server-owned and remain correctable until it is shipped.`); await refreshAll(); } catch (error) { setNotice(message(error)); } finally { setPending(undefined); } };
  const correct = async () => { if (!shipment || !prepared || !valid || !reason.trim() || !editable) return; setPending("correct"); setNotice(""); try { const corrected = await fulfillmentApi.correctShipment(organizationId, shipment.shipmentId, newBusinessRequestId(), { allocations: allocations(), reason: reason.trim(), carrier: metadata() }); restore(corrected); setNotice("Prepared shipment correction was saved with an immutable recovery reason."); await refreshAll(); } catch (error) { setNotice(message(error)); } finally { setPending(undefined); } };
  const cancel = async () => { if (!shipment || !prepared || !reason.trim() || !editable) return; setPending("cancel"); setNotice(""); try { const voided = await fulfillmentApi.cancelShipment(organizationId, shipment.shipmentId, newBusinessRequestId(), reason.trim()); restore(voided); setNotice("Prepared shipment voided. Server-authoritative allocations were released and the void remains in history."); await refreshAll(); } catch (error) { setNotice(message(error)); } finally { setPending(undefined); } };
  const finalize = async () => { const revisionId = shipment?.currentPreparedRevision?.revisionId; if (!shipment || !prepared || !revisionId || !editable) return; setPending("finalize"); setNotice(""); try { const finalized = await fulfillmentApi.finalizeShipment(organizationId, shipment.shipmentId, newBusinessRequestId(), revisionId); restore(finalized); setNotice("Shipment finalized. The server atomically created its immutable handoffs, allocations, document snapshots, and shipment history."); await refreshAll(); } catch (error) { setNotice(message(error)); } finally { setPending(undefined); } };
  return <section className="v2-fulfillment-shipment-builder">
    <header><div><small>Shipping</small><h2>Shipment container</h2><p>Prepare one physical shipment from a bounded set of currently loaded fulfillment lines. The server owns allocations, compatibility, and quantity validation; preparing a shipment does not fulfill or mark it shipped.</p></div><button type="button" onClick={() => setExpanded(value => !value)}>{expanded ? "Close shipment builder" : "Create shipment"}</button></header>
    {expanded && <div className="v2-fulfillment-shipment-body">
      <section className="v2-fulfillment-shipment-history"><header><h3>Prepared shipment recovery</h3><button type="button" disabled={Boolean(pending)} onClick={() => void loadShipments()}>{pending === "load" ? "Refreshing…" : "Refresh shipments"}</button></header>{shipments.length ? <div>{shipments.map(item => <button key={item.shipmentId} type="button" className={shipment?.shipmentId === item.shipmentId ? "active" : ""} onClick={() => void fulfillmentApi.getShipment(organizationId, item.shipmentId).then(restore).catch(error => setNotice(message(error)))}><b>{item.shipmentId}</b><small>{item.status}{item.carrier.trackingNumber ? ` · ${item.carrier.trackingNumber}` : ""}</small></button>)}</div> : <p>No persisted shipment containers are available in this bounded workspace.</p>}<button type="button" onClick={resetForm}>Start a new prepared shipment</button></section>
       <div className="v2-fulfillment-shipment-selection"><h3>{shipment ? "Shipment allocations" : "1. Select fulfillment quantities"}</h3>{readOnly && <p>This {shipment?.status} shipment is historical and read-only. A shipped shipment cannot be edited, cancelled, or turned back into prepared work.</p>}{orders.map(order => <article key={order.orderId}><b>{order.number} · {order.customerName}</b>{order.lines.filter(line => line.availableFulfillmentQuantity > 0 && !line.physicalIntegrityAnomaly || Boolean(selected[keyOf(order.orderId, line.orderLineId)])).map(line => { const key = keyOf(order.orderId, line.orderLineId); const active = selected[key]; return <label key={line.orderLineId} className="v2-fulfillment-shipment-line"><input type="checkbox" checked={Boolean(active)} disabled={readOnly || !canShip} onChange={() => toggle(order, line)} /><span><b>{line.description}</b><small>{line.availableFulfillmentQuantity} currently available · {line.completedFulfillmentQuantity} previously fulfilled</small></span>{active && <input aria-label={`${order.number} ${line.description} shipment quantity`} type="number" min="1" max={active.available} step="1" value={active.quantity} disabled={readOnly} onChange={event => setQuantity(key, event.target.value)} />}</label>; })}{replacementCandidates.filter(candidate=>candidate.obligation.orderId===order.orderId&&candidate.obligation.status!=="cancelled"&&candidate.remainingProductionQuantity===0&&candidate.remainingFulfillmentQuantity>0).map(candidate=>{const line=order.lines.find(value=>value.orderLineId===candidate.obligation.orderLineId);if(!line)return null;const key=keyOf(order.orderId,line.orderLineId,candidate.obligation.replacementObligationId),active=selected[key];return <label key={candidate.obligation.replacementObligationId} className="v2-fulfillment-shipment-line"><input type="checkbox" checked={Boolean(active)} disabled={readOnly||!canShip||!canReplace} onChange={()=>toggle(order,line,candidate)} /><span><b>Replacement · {line.description}</b><small>{candidate.remainingFulfillmentQuantity} replacement unit(s) available · original fulfillment remains historical</small></span>{active&&<input aria-label={`${order.number} replacement ${line.description} shipment quantity`} type="number" min="1" max={active.available} step="1" value={active.quantity} disabled={readOnly} onChange={event=>setQuantity(key,event.target.value)} />}</label>;})}</article>)}</div>
      <div className="v2-fulfillment-shipment-details"><h3>{shipment ? "Shipment details" : "2. Manual shipment details"}</h3><label>Carrier<input value={carrierName} disabled={readOnly} onChange={event => setCarrierName(event.target.value)} placeholder="Manual carrier" /></label><label>Service<input value={carrierService} disabled={readOnly} onChange={event => setCarrierService(event.target.value)} placeholder="Service" /></label><label>Tracking<input value={trackingNumber} disabled={readOnly} onChange={event => setTrackingNumber(event.target.value)} placeholder="Tracking number" /></label><label>Package count<input type="number" min="1" step="1" value={packageCount} disabled={readOnly} onChange={event => setPackageCount(event.target.value)} placeholder="Optional" /></label><label>Notes<textarea value={notes} disabled={readOnly} onChange={event => setNotes(event.target.value)} /></label>{prepared && <label>Correction or void reason<textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Required before correcting or voiding a prepared shipment" /></label>}<p>Carrier, service, tracking, notes, and package count are manual operator facts, not provider events.</p></div>
      {shipment&&(canManageShippingCost||canManageShippingPrice)&&<ShipmentEconomicsPanel organizationId={organizationId} shipmentId={shipment.shipmentId} customerId={shipment.customerId} csrfReady={csrfReady} canManageCost={canManageShippingCost} canManagePrice={canManageShippingPrice} />}
      <footer className="v2-fulfillment-shipment-actions"><p>{selections.length ? `${selections.length} line${selections.length === 1 ? "" : "s"} selected` : "Select one or more available lines."}</p>{!shipment ? <button type="button" className="primary" disabled={!editable || !valid} onClick={() => void create()}>{pending === "create" ? "Creating…" : "Create prepared shipment"}</button> : prepared ? <><button type="button" disabled={!editable || !valid || !reason.trim()} onClick={() => void correct()}>{pending === "correct" ? "Saving…" : "Save correction"}</button><button type="button" disabled={!editable || !reason.trim()} onClick={() => void cancel()}>{pending === "cancel" ? "Voiding…" : "Void prepared shipment"}</button><button type="button" className="primary" disabled={!editable || !shipment.currentPreparedRevision} onClick={() => void finalize()}>{pending === "finalize" ? "Finalizing…" : "Mark shipped"}</button><p className="v2-fulfillment-notice">Mark shipped invokes one server transaction: it revalidates the frozen prepared revision, creates immutable handoffs, allocations, snapshots and attachments, then transitions the container to shipped. A conflict leaves this draft prepared.</p></> : <p>{shipment.status === "shipped" ? "This shipment is shipped. Any physical correction must use a future explicit post-shipment correction workflow; this record remains immutable." : "This prepared shipment was voided. Its historical evidence remains available, but it cannot be edited or shipped."}</p>}<p>Pickup remains a separate handoff action and never requires carrier or tracking data.</p>{notice && <p className="v2-fulfillment-notice">{notice}</p>}</footer>
    </div>}
  </section>;
};

const cents=(value:number|undefined)=>value===undefined?"Not recorded":`${value.toLocaleString()} cents`;
const policyLabel=(policy:ShippingPricingPolicyRead|undefined)=>{const value=policy?.customerOverride??policy?.organizationDefault;if(!value)return "No organization policy configured";return `${value.mode.replaceAll("_"," ")} · ${policy?.customerOverride?"customer override":"organization default"}`;};
/** The only UI consumer of staff-only shipment economics. */
const ShipmentEconomicsPanel=({organizationId,shipmentId,customerId,csrfReady,canManageCost,canManagePrice}:{organizationId:string;shipmentId:string;customerId?:string;csrfReady:boolean;canManageCost:boolean;canManagePrice:boolean})=>{
 const [economics,setEconomics]=useState<StaffShipmentEconomics>();const [policy,setPolicy]=useState<ShippingPricingPolicyRead>();const [estimate,setEstimate]=useState("");const [actual,setActual]=useState("");const [actualReason,setActualReason]=useState("");const [manualPrice,setManualPrice]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 const load=async()=>{try{const values=await Promise.all([canManageCost?shipmentEconomicsApi.read(organizationId,shipmentId):Promise.resolve(undefined),canManagePrice?(customerId?shippingPricingApi.getCustomerPolicy(organizationId,customerId):shippingPricingApi.getOrganizationPolicy(organizationId)):Promise.resolve(undefined)]);setEconomics(values[0]);setPolicy(values[1]);}catch(error){setNotice(message(error));}};
 useEffect(()=>{void load();},[organizationId,shipmentId,customerId,canManageCost,canManagePrice]);
 const submit=async(work:()=>Promise<StaffShipmentEconomics>)=>{setBusy(true);setNotice("");try{setEconomics(await work());await load();}catch(error){setNotice(message(error));}finally{setBusy(false);}};
 const frozen=economics?.customerPriceFrozen===true;const manual=(policy?.customerOverride??policy?.organizationDefault)?.mode==="manual";
 return <section className="v2-fulfillment-history" data-testid="shipment-economics"><header><h3>Internal shipping economics</h3><p>Staff-only. Costs, policy evidence, and customer price are not included in customer or portal shipment records.</p></header>{canManageCost&&<><dl><div><dt>Estimated carrier cost</dt><dd>{cents(economics?.estimatedCarrierCostCents)}</dd></div><div><dt>Actual carrier cost</dt><dd>{cents(economics?.actualCarrierCostCents)}</dd></div></dl><div className="v2-sales-inline-grid"><label>Estimated carrier cost (cents)<input value={estimate} inputMode="numeric" onChange={event=>setEstimate(event.target.value)} /></label><button type="button" disabled={!csrfReady||busy||!Number.isSafeInteger(Number(estimate))||Number(estimate)<0} onClick={()=>void submit(()=>shipmentEconomicsApi.setEstimated(organizationId,shipmentId,newBusinessRequestId(),Number(estimate)))}>Save estimate</button><label>Actual carrier cost (cents)<input value={actual} inputMode="numeric" onChange={event=>setActual(event.target.value)} /></label><label>Actual-cost reason<input value={actualReason} onChange={event=>setActualReason(event.target.value)} /></label><button type="button" disabled={!csrfReady||busy||!Number.isSafeInteger(Number(actual))||Number(actual)<0||!actualReason.trim()} onClick={()=>void submit(()=>shipmentEconomicsApi.setActual(organizationId,shipmentId,newBusinessRequestId(),{actualCarrierCostCents:Number(actual),responsibility:"titan",reason:actualReason.trim()}))}>Save actual cost</button></div></>}{canManagePrice&&<><dl><div><dt>Effective policy</dt><dd>{economics?.pricingPolicySnapshot?`${economics.pricingPolicySnapshot.policy.mode.replaceAll("_"," ")} · ${economics.pricingPolicySnapshot.source.replaceAll("_"," ")} (frozen)`:policyLabel(policy)}</dd></div><div><dt>Customer shipping price</dt><dd>{cents(economics?.customerShippingPriceCents)}</dd></div><div><dt>Customer price state</dt><dd>{frozen?"Frozen":"Not established"}</dd></div></dl>{!frozen&&<div className="v2-sales-inline-grid">{manual&&<label>Manual customer price (cents)<input value={manualPrice} inputMode="numeric" onChange={event=>setManualPrice(event.target.value)} /></label>}<button type="button" disabled={!csrfReady||busy||(manual&&(!Number.isSafeInteger(Number(manualPrice))||Number(manualPrice)<0))} onClick={()=>void submit(()=>shipmentEconomicsApi.establishPrice(organizationId,shipmentId,newBusinessRequestId(),manual?Number(manualPrice):undefined))}>{manual?"Freeze manual customer price":"Establish and freeze customer price"}</button></div>}<p>Actual cost and later policy changes do not automatically reprice a frozen shipment.</p></>}{notice&&<p className="v2-fulfillment-notice">{notice}</p>}</section>;
};
