import React, { useEffect, useState } from "react";
import { fulfillmentOwnerApi } from "./fulfillmentOwnerApi";
import type { OrderingCustomerSender, ShipmentSenderIntent, ShippingSender } from "../../src/modules/fulfillment/shipmentSender";

export const ShipmentSenderControls = ({ organizationId, sessionScope, orderIds, intents, disabled, onChange }: { organizationId: string; sessionScope: string; orderIds: readonly string[]; intents: readonly ShipmentSenderIntent[]; disabled: boolean; onChange: (values: readonly ShipmentSenderIntent[]) => void }) => <section><h3>Blind shipping and return identity</h3><p>Sender is separate from Ship To. Customer source uses the complete billing address; Custom never falls back. Preparation freezes the selected return identity.</p>{orderIds.map(orderId => <OrderSender key={`${organizationId}:${sessionScope}:${orderId}`} organizationId={organizationId} orderId={orderId} value={intents.find(item => item.orderId === orderId) ?? { orderId }} disabled={disabled} change={value => onChange([...intents.filter(item => item.orderId !== orderId), value])} />)}</section>;
const fields = ["company", "recipient", "addressLine1", "addressLine2", "city", "region", "postalCode", "country", "phone", "email"] as const;
const OrderSender = ({ organizationId, orderId, value, disabled, change }: { organizationId: string; orderId: string; value: ShipmentSenderIntent; disabled: boolean; change: (value: ShipmentSenderIntent) => void }) => {
  const [context, setContext] = useState<OrderingCustomerSender>(), [error, setError] = useState("");
  useEffect(() => { let active = true; void fulfillmentOwnerApi.sender(organizationId, orderId).then(result => { if (active) setContext(result); }).catch(() => { if (active) setError("Customer sender context is unavailable. The owner will not invent a sender."); }); return () => { active = false; }; }, [organizationId, orderId]);
  const blind = value.blindShipping ?? context?.defaultBlindShipping;
  const source = value.source ?? "customer";
  return <fieldset disabled={disabled}><legend>Order {orderId}</legend><label>Blind shipping<select aria-label={`Blind shipping ${orderId}`} value={value.blindShipping === undefined ? "default" : value.blindShipping ? "yes" : "no"} onChange={event => { const { blindShipping: _old, ...rest } = value; change({ ...rest, ...(event.target.value === "default" ? {} : { blindShipping: event.target.value === "yes" }) }); }}><option value="default">Customer default{context ? context.defaultBlindShipping ? " (blind)" : " (not blind)" : " (loading)"}</option><option value="yes">Blind, override Customer</option><option value="no">Not blind, override Customer</option></select></label>{blind && <><label>Sender source<select aria-label={`Sender source ${orderId}`} value={source} onChange={event => change({ ...value, source: event.target.value as "customer" | "custom" })}><option value="customer">Ordering Customer billing address</option><option value="custom">Custom return sender</option></select></label>{source === "customer" ? <p>{context ? fields.map(field => (context.billingSender as Record<string, unknown>)[field]).filter(Boolean).join(", ") : "Loading Customer billing address..."}</p> : fields.map(field => <label key={field}>{field}<input aria-label={`${field} sender ${orderId}`} value={value.customSender?.[field] ?? ""} maxLength={500} onChange={event => change({ ...value, customSender: { ...value.customSender, [field]: event.target.value } as ShippingSender })} /></label>)}</>}{error && <p role="alert">{error}</p>}</fieldset>;
};
