import { useQuery } from "@tanstack/react-query";
import { teamAccessApi, type TeamAccessRead } from "./api";
type Section = "staff" | "permission-sets" | "portal";
export const TeamAccessWorkspace = ({ organizationId, sessionScope, canView, section }: Readonly<{ organizationId: string; sessionScope: string; canView: boolean; section: Section }>) => {
  const query = useQuery({ queryKey: ["v2", sessionScope, organizationId, "settings", "team-access"], queryFn: () => teamAccessApi.get(organizationId), enabled: Boolean(organizationId && sessionScope && canView) });
  const title = section === "staff" ? "Staff & Users" : section === "permission-sets" ? "Permission Sets" : "Customer Portal Access";
  if (!canView) return <section className="v2-settings-future"><h2>{title}</h2><p>You do not have permission to view Team & Access for this organization.</p></section>;
  if (query.isLoading) return <p>Loading Team & Access…</p>; if (query.error || !query.data) return <section className="v2-settings-future"><h2>{title}</h2><p>Team & Access is currently unavailable. No browser-local authority is substituted.</p></section>;
  return <section className="v2-settings-form"><header><small>SETTINGS · TEAM & ACCESS</small><h1>{title}</h1><p>Canonical tenant memberships and permission-set assignments. Global identity remains outside Settings.</p></header><Readiness value={query.data}/>{section === "staff" ? <Staff value={query.data}/> : section === "permission-sets" ? <Sets value={query.data}/> : <Portal value={query.data}/>}</section>;
};
const Readiness = ({ value }: Readonly<{ value: TeamAccessRead }>) => <section className="v2-settings-status"><strong>Authority status</strong><span className={`v2-settings-chip is-${value.readiness.status === "ready" ? "ready" : "attention"}`}>{value.readiness.status === "ready" ? "Ready" : "Needs attention"}</span><span>{value.readiness.activeStaffCount} active staff · {value.readiness.viableAdministratorCount} viable administrators · {value.readiness.pendingInvitationCount} pending invitations</span></section>;
const Staff = ({ value }: Readonly<{ value: TeamAccessRead }>) => <section className="v2-settings-form-card"><h2>Staff members</h2>{value.staff.length ? <div className="v2-settings-list">{value.staff.map((item) => <article key={item.memberId}><div><strong>{item.displayName}</strong><span>{item.email}</span></div><div><span className={`v2-settings-chip is-${item.status === "active" ? "ready" : "attention"}`}>{item.status}</span><small>{item.permissionSets.join(" · ") || "No assigned permission sets"}</small></div></article>)}</div> : <p className="v2-settings-empty">No Staff members are available in this organization.</p>}</section>;
const Sets = ({ value }: Readonly<{ value: TeamAccessRead }>) => <section className="v2-settings-form-card"><h2>Permission sets</h2>{value.permissionSets.length ? <div className="v2-settings-list">{value.permissionSets.map((item) => <article key={item.permissionSetId}><div><strong>{item.name}</strong><span>{item.description || "No description"}</span></div><div><span className={`v2-settings-chip is-${item.active ? "ready" : "attention"}`}>{item.active ? "Active" : "Inactive"}</span><small>{item.capabilities.length} capabilities · {item.principalKind}</small></div></article>)}</div> : <p className="v2-settings-empty">No permission sets are available.</p>}</section>;
const Portal = ({ value }: Readonly<{ value: TeamAccessRead }>) => <section className="v2-settings-form-card"><h2>Customer portal access</h2>{value.portalAccess.length ? <div className="v2-settings-list">{value.portalAccess.map((item) => <article key={item.portalAccessId}><div><strong>Customer {item.customerId}</strong><span>{item.permissionSets.join(" · ") || "No assigned permission sets"}</span></div><span className="v2-settings-chip is-optional">{item.status}</span></article>)}</div> : <p className="v2-settings-empty">No Customer Portal access records are currently available.</p>}</section>;
