import React, { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { newBusinessRequestId, teamAccessApi, type ApiError, type TeamAccessRead, type TeamPermissionSet } from "./api";

type Section = "staff" | "permission-sets" | "portal";
type EditSet = Readonly<{ permissionSetId?: string; name: string; description: string; principalKind: "staff" | "portal"; active: boolean; capabilities: readonly string[] }>;
const blankSet = (): EditSet => ({ name: "", description: "", principalKind: "staff", active: true, capabilities: [] });
const messageOf = (error: unknown, fallback: string) => (error as unknown as ApiError | undefined)?.message ?? fallback;
const selectedIds = (sets: readonly TeamPermissionSet[], names: readonly string[]) => sets.filter((item) => names.includes(item.name)).map((item) => item.permissionSetId);

export const TeamAccessWorkspace = ({ organizationId, sessionScope, canView, canManageSets, canAssignStaff, canAssignPortal, section, openCustomers }: Readonly<{ organizationId: string; sessionScope: string; canView: boolean; canManageSets: boolean; canAssignStaff: boolean; canAssignPortal: boolean; section: Section; openCustomers: () => void }>) => {
  const client = useQueryClient(); const key = ["v2", sessionScope, organizationId, "settings", "team-access"] as const;
  const query = useQuery({ queryKey: key, queryFn: () => teamAccessApi.get(organizationId), enabled: Boolean(organizationId && sessionScope && canView) });
  const [notice, setNotice] = useState(""); const refresh = () => client.invalidateQueries({ queryKey: key });
  const context = () => ({ businessRequestId: newBusinessRequestId(), expectedAuthorityRevision: query.data!.authorityRevision });
  const invite = useMutation({ mutationFn: (input: Readonly<{ email: string; legacyRole: "admin" | "manager" | "member" }>) => teamAccessApi.invite(organizationId, { ...context(), ...input }), onSuccess: () => { setNotice("Invitation created and handed to Gmail delivery."); refresh(); }, onError: (error) => setNotice(messageOf(error, "Staff invitation could not be created.")) });
  const membership = useMutation({ mutationFn: (input: Readonly<{ userId: string; active: boolean }>) => teamAccessApi.setStaffStatus(organizationId, input.userId, { ...context(), active: input.active }), onSuccess: () => { setNotice("Staff membership updated."); refresh(); }, onError: (error) => setNotice(messageOf(error, "Staff membership could not be updated.")) });
  const staffSets = useMutation({ mutationFn: (input: Readonly<{ userId: string; permissionSetIds: readonly string[] }>) => teamAccessApi.replaceStaffPermissionSets(organizationId, input.userId, { ...context(), permissionSetIds: input.permissionSetIds }), onSuccess: () => { setNotice("Staff permission sets updated."); refresh(); }, onError: (error) => setNotice(messageOf(error, "Staff permission sets could not be updated.")) });
  const permissionSets = useMutation({ mutationFn: (input: EditSet) => input.permissionSetId ? teamAccessApi.updatePermissionSet(organizationId, input.permissionSetId, { ...context(), name: input.name, description: input.description || undefined, active: input.active, capabilities: input.capabilities }) : teamAccessApi.createPermissionSet(organizationId, { ...context(), name: input.name, description: input.description || undefined, principalKind: input.principalKind, capabilities: input.capabilities }), onSuccess: () => { setNotice("Permission set saved."); refresh(); }, onError: (error) => setNotice(messageOf(error, "Permission set could not be saved.")) });
  const portalSets = useMutation({ mutationFn: (input: Readonly<{ portalAccessId: string; permissionSetIds: readonly string[] }>) => teamAccessApi.replacePortalPermissionSets(organizationId, input.portalAccessId, { ...context(), permissionSetIds: input.permissionSetIds }), onSuccess: () => { setNotice("Portal permission sets updated."); refresh(); }, onError: (error) => setNotice(messageOf(error, "Portal permission sets could not be updated.")) });
  const title = section === "staff" ? "Staff & Users" : section === "permission-sets" ? "Permission Sets" : "Customer Portal Access";
  if (!canView) return <PermissionDenied title={title} />;
  if (query.isLoading) return <p>Loading Team & Access…</p>;
  if (query.isError || !query.data) return <section className="v2-settings-future"><h2>{title}</h2><p>Team & Access is currently unavailable. No browser-local authority is substituted.</p></section>;
  const busy = invite.isPending || membership.isPending || staffSets.isPending || permissionSets.isPending || portalSets.isPending;
  return <section className="v2-settings-form"><header><small>SETTINGS · TEAM & ACCESS</small><h1>{title}</h1><p>Canonical tenant memberships and permission-set assignments. Global identity remains outside Settings.</p></header><Readiness value={query.data}/>{section === "staff" ? <Staff value={query.data} canAssign={canAssignStaff} busy={busy} invite={invite.mutate} changeStatus={membership.mutate} assign={staffSets.mutate}/> : section === "permission-sets" ? <Sets value={query.data} canManage={canManageSets} busy={busy} save={permissionSets.mutate}/> : <Portal value={query.data} canAssign={canAssignPortal} busy={busy} assign={portalSets.mutate} openCustomers={openCustomers}/>} {notice && <p className={notice.includes("updated") || notice.includes("saved") || notice.includes("created") ? "notice" : "notice error"}>{notice}</p>}</section>;
};

const PermissionDenied = ({ title }: Readonly<{ title: string }>) => <section className="v2-settings-panel v2-settings-future"><h2>{title}</h2><p>You do not have permission to view this setting. Contact an organization administrator.</p></section>;
const PermissionNotice = ({ action }: Readonly<{ action: string }>) => <p className="v2-settings-permission">You can view this setting, but do not have permission to {action}. Contact an organization administrator.</p>;
const Readiness = ({ value }: Readonly<{ value: TeamAccessRead }>) => <section className="v2-settings-status"><strong>Authority status</strong><span className={`v2-settings-chip is-${value.readiness.status === "ready" ? "ready" : "attention"}`}>{value.readiness.status === "ready" ? "Ready" : "Needs attention"}</span><span>{value.readiness.activeStaffCount} active staff · {value.readiness.viableAdministratorCount} viable administrators · {value.readiness.pendingInvitationCount} pending invitations</span></section>;

const Staff = ({ value, canAssign, busy, invite, changeStatus, assign }: Readonly<{ value: TeamAccessRead; canAssign: boolean; busy: boolean; invite: (input: Readonly<{ email: string; legacyRole: "admin" | "manager" | "member" }>) => void; changeStatus: (input: Readonly<{ userId: string; active: boolean }>) => void; assign: (input: Readonly<{ userId: string; permissionSetIds: readonly string[] }>) => void }>) => {
  const [showInvite, setShowInvite] = useState(false); const [editing, setEditing] = useState<string | null>(null); const [email, setEmail] = useState(""); const [role, setRole] = useState<"admin" | "manager" | "member">("member");
  const available = value.permissionSets.filter((item) => item.principalKind === "staff" && item.active);
  return <section className="v2-settings-form-card"><div className="v2-settings-section-title"><h2>Staff members</h2>{canAssign && <button type="button" className="button secondary" onClick={() => setShowInvite(!showInvite)}>{showInvite ? "Cancel invitation" : "Invite staff"}</button>}</div>{canAssign ? <>{showInvite && <form className="v2-settings-inline-form" onSubmit={(event) => { event.preventDefault(); invite({ email, legacyRole: role }); setEmail(""); setShowInvite(false); }}><label className="field">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="field">Bootstrap role<select value={role} onChange={(event) => setRole(event.target.value as typeof role)}><option value="member">Member</option><option value="manager">Manager</option><option value="admin">Admin</option></select></label><button className="button" disabled={busy}>Send invitation</button><p className="v2-settings-muted">Invitation delivery is owned by Gmail; no credential enters this page.</p></form>}</> : <PermissionNotice action="invite Staff, assign access, or change membership status"/>}<div className="v2-settings-list">{value.staff.map((item) => <article key={item.memberId}><div><strong>{item.displayName}</strong><span>{item.email}</span></div><div><span className={`v2-settings-chip is-${item.status === "active" ? "ready" : "attention"}`}>{item.status}</span><small>{item.permissionSets.join(" · ") || "No assigned permission sets"}</small></div>{canAssign && <div className="v2-settings-row-actions"><button type="button" onClick={() => setEditing(editing === item.memberId ? null : item.memberId)}>Edit access</button><button type="button" disabled={busy} onClick={() => { if (window.confirm(`${item.status === "active" ? "Disable" : "Enable"} ${item.displayName}?`)) changeStatus({ userId: item.memberId, active: item.status !== "active" }); }}>{item.status === "active" ? "Disable" : "Enable"}</button></div>}{editing === item.memberId && <AssignmentEditor sets={available} selected={selectedIds(value.permissionSets, item.permissionSets)} busy={busy} onSave={(permissionSetIds) => { assign({ userId: item.memberId, permissionSetIds }); setEditing(null); }}/>}</article>)}</div>{value.invitations.length > 0 && <div className="v2-settings-invitations"><h3>Invitations</h3>{value.invitations.map((item) => <p key={item.invitationId}><b>{item.email}</b> · {item.status} · delivery {item.deliveryState}</p>)}</div>}</section>;
};

const AssignmentEditor = ({ sets, selected, busy, onSave }: Readonly<{ sets: readonly TeamPermissionSet[]; selected: readonly string[]; busy: boolean; onSave: (ids: readonly string[]) => void }>) => { const [ids, setIds] = useState<readonly string[]>(selected); return <form className="v2-settings-assignment" onSubmit={(event) => { event.preventDefault(); onSave(ids); }}><p>Select active permission sets. The server enforces capability ceilings and the administrator safety floor.</p>{sets.map((item) => <label key={item.permissionSetId}><input type="checkbox" checked={ids.includes(item.permissionSetId)} onChange={(event) => setIds(event.target.checked ? [...ids, item.permissionSetId] : ids.filter((id) => id !== item.permissionSetId))}/>{item.name}{item.systemManaged ? " · system template" : ""}</label>)}<button className="button" disabled={busy || !ids.length}>Save access</button></form>; };

const Sets = ({ value, canManage, busy, save }: Readonly<{ value: TeamAccessRead; canManage: boolean; busy: boolean; save: (input: EditSet) => void }>) => { const [editing, setEditing] = useState<EditSet | null>(null); return <section className="v2-settings-form-card"><div className="v2-settings-section-title"><h2>Permission sets</h2>{canManage && <button className="button secondary" type="button" onClick={() => setEditing(blankSet())}>Create custom set</button>}</div><p className="v2-settings-muted">System permission sets are assignable but managed templates. Custom sets are administered here.</p>{!canManage && <PermissionNotice action="create or update custom permission sets"/>}<div className="v2-settings-list">{value.permissionSets.map((item) => <article key={item.permissionSetId}><div><strong>{item.name}</strong><span>{item.description || "No description"}</span></div><div><span className={`v2-settings-chip is-${item.active ? "ready" : "attention"}`}>{item.systemManaged ? "System template" : item.active ? "Custom active" : "Custom inactive"}</span><small>{item.capabilities.length} capabilities · {item.assignmentCount} assignments · {item.principalKind}</small></div>{canManage && !item.systemManaged && <div className="v2-settings-row-actions"><button type="button" onClick={() => setEditing({ permissionSetId: item.permissionSetId, name: item.name, description: item.description ?? "", principalKind: item.principalKind, active: item.active, capabilities: item.capabilities })}>Edit</button></div>}</article>)}</div>{editing && <SetEditor value={editing} groups={value.capabilityGroups} busy={busy} onCancel={() => setEditing(null)} onSave={(next) => { save(next); setEditing(null); }}/>}</section>;
};

const SetEditor = ({ value, groups, busy, onCancel, onSave }: Readonly<{ value: EditSet; groups: TeamAccessRead["capabilityGroups"]; busy: boolean; onCancel: () => void; onSave: (value: EditSet) => void }>) => { const [form, setForm] = useState(value); const toggle = (capability: string, checked: boolean) => setForm({ ...form, capabilities: checked ? [...form.capabilities, capability] : form.capabilities.filter((item) => item !== capability) }); return <form className="v2-settings-set-editor" onSubmit={(event) => { event.preventDefault(); onSave(form); }}><h3>{form.permissionSetId ? "Edit custom permission set" : "Create custom permission set"}</h3><div className="v2-settings-fields"><label className="field">Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></label><label className="field">Principal kind<select disabled={Boolean(form.permissionSetId)} value={form.principalKind} onChange={(event) => setForm({ ...form, principalKind: event.target.value as "staff" | "portal" })}><option value="staff">Staff</option><option value="portal">Portal</option></select></label><label className="field">Description<input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })}/></label>{form.permissionSetId && <label className="field"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })}/> Active</label>}</div><div className="v2-settings-capabilities">{groups.map((group) => <fieldset key={group.key}><legend>{group.label}</legend>{group.capabilities.map((capability) => <label key={capability}><input type="checkbox" checked={form.capabilities.includes(capability)} onChange={(event) => toggle(capability, event.target.checked)}/>{capability}</label>)}</fieldset>)}</div><div className="v2-settings-row-actions"><button className="button" disabled={busy || !form.capabilities.length}>Save permission set</button><button type="button" onClick={onCancel}>Cancel</button></div></form>; };

const Portal = ({ value, canAssign, busy, assign, openCustomers }: Readonly<{ value: TeamAccessRead; canAssign: boolean; busy: boolean; assign: (input: Readonly<{ portalAccessId: string; permissionSetIds: readonly string[] }>) => void; openCustomers: () => void }>) => { const [editing, setEditing] = useState<string | null>(null); const available = value.permissionSets.filter((item) => item.principalKind === "portal" && item.active); return <section className="v2-settings-form-card"><div className="v2-settings-section-title"><h2>Customer portal access</h2><button className="button secondary" type="button" onClick={openCustomers}>Open Customers</button></div><p className="v2-settings-muted">Portal users are distinct from Staff. Contacts are created and granted portal access by their owning customer/portal workflow; Settings assigns only existing Portal permission sets.</p>{!canAssign && <PermissionNotice action="assign Portal permission sets"/>}{value.portalAccess.length ? <div className="v2-settings-list">{value.portalAccess.map((item) => <article key={item.portalAccessId}><div><strong>Customer {item.customerId}</strong><span>{item.permissionSets.join(" · ") || "No assigned permission sets"}</span></div><span className="v2-settings-chip is-optional">{item.status}</span>{canAssign && <div className="v2-settings-row-actions"><button type="button" onClick={() => setEditing(editing === item.portalAccessId ? null : item.portalAccessId)}>Assign permissions</button></div>}{editing === item.portalAccessId && <AssignmentEditor sets={available} selected={selectedIds(value.permissionSets, item.permissionSets)} busy={busy} onSave={(permissionSetIds) => { assign({ portalAccessId: item.portalAccessId, permissionSetIds }); setEditing(null); }}/>}</article>)}</div> : <div className="v2-settings-empty"><strong>No Customer Portal access records are available.</strong><p>Create and manage Customer Contacts in their owning module, then grant Portal access through the canonical portal workflow. This page does not create Contacts or convert Staff identities.</p><button type="button" className="button secondary" onClick={openCustomers}>Open Customers</button></div>}</section>; };
