import { AuthorityPolicy } from "../../src/authorization/authorityPolicy.js";
import { PermissionSetPrincipalIssuer, type PermissionAuthorityReader } from "../../src/authorization/permissionSets.js";

const staffIdentity={subjectId:"staff-a",authenticatedAt:new Date(),authenticationMethod:"session" as const};
const portalIdentity={subjectId:"portal-a",authenticatedAt:new Date(),authenticationMethod:"portal_session" as const};
const reader = (overrides: Partial<Awaited<ReturnType<PermissionAuthorityReader["resolveStaff"]>>> = {}): PermissionAuthorityReader => ({
  resolveStaff: async () => ({organizationId:"org-a",organizationActive:true,authorityRevision:2,staff:{userId:"staff-a",membershipId:"m",membershipActive:true,permissionSets:[{id:"sales",name:"Sales",active:true,revision:1},{id:"accounting",name:"Accounting",active:true,revision:1}],capabilities:["quote.view","invoice.view"]},...overrides}),
  resolvePortal: async () => ({organizationId:"org-a",organizationActive:true,authorityRevision:2,portal:{userId:"portal-a",portalAccessId:"pa",customerId:"customer-a",accessActive:true,permissionSets:[{id:"portal",name:"Portal",active:true,revision:1}],assignedCapabilities:["quote.view","quote.create","invoice.view"],ceilingCapabilities:["quote.view","invoice.view"]}}),
});
describe("M1.5 final permission-set issuer",()=>{
  it("unions active staff sets and records final V2 authority evidence",async()=>{const principal=await new PermissionSetPrincipalIssuer(reader()).issue(staffIdentity,{organizationId:"org-a"});expect(principal.kind).toBe("staff");if(principal.kind!=="staff")return;expect(principal.authority.capabilities).toEqual(["invoice.view","quote.view"]);expect(principal.authority.permissionSetIds).toEqual(["sales","accounting"]);expect(principal.authority.source).toBe("permission_set");});
  it("fails closed without a V2 assignment even if a legacy membership exists",async()=>{const issuer=new PermissionSetPrincipalIssuer(reader({staff:{userId:"staff-a",membershipId:"m",membershipActive:true,permissionSets:[],capabilities:[]}}));await expect(issuer.issue(staffIdentity,{organizationId:"org-a"})).rejects.toMatchObject({code:"FORBIDDEN"});});
  it("intersects Portal sets with the explicit safe ceiling and customer scope",async()=>{const principal=await new PermissionSetPrincipalIssuer(reader()).issue(portalIdentity,{organizationId:"org-a"});expect(principal.kind).toBe("portal");if(principal.kind!=="portal")return;expect(principal.capabilities).toEqual(["invoice.view","quote.view"]);expect(new AuthorityPolicy().decide(principal,{capability:"quote.view",resource:{organizationId:"org-a",customerId:"customer-b"}})).toEqual({allowed:false,reason:"CUSTOMER_OUT_OF_SCOPE"});});
  it("re-resolves authority on every issuance",async()=>{let grant=true;const issuer=new PermissionSetPrincipalIssuer({resolvePortal:reader().resolvePortal,resolveStaff:async()=>({organizationId:"org-a",organizationActive:true,authorityRevision:grant?1:2,staff:{userId:"staff-a",membershipId:"m",membershipActive:true,permissionSets:grant?[{id:"s",name:"S",active:true,revision:1}]:[],capabilities:grant?["quote.view"]:[]}})});await issuer.issue(staffIdentity,{organizationId:"org-a"});grant=false;await expect(issuer.issue(staffIdentity,{organizationId:"org-a"})).rejects.toMatchObject({code:"FORBIDDEN"});});
});
