import { describe, expect, test } from "@jest/globals";
import { ProductVersionLifecycleApplicationService, type ProductVersionLifecycle, type ProductVersionTransaction, type ProductVersionTransactionRunner } from "../../src/modules/products/productVersionLifecycle";
import { V2ApplicationError } from "../../src/errors/applicationError";
import type { OperationContext } from "../../src/application/operation";

const activeUpdatedAt="2026-08-18T12:00:00.000Z";
const activeTree={schemaVersion:2,nodes:{size:{kind:"question",label:"Size"}},meta:{pricingV2:{base:{perPieceCents:500}}}};
const active=()=>({status:"active" as const,createdAt:"2026-08-17T12:00:00.000Z",updatedAt:activeUpdatedAt,publishedAt:"2026-08-18T11:00:00.000Z",editable:false});
const initial=():ProductVersionLifecycle=>({active:active(),history:[],historyLimit:25,historyHasMore:false,canCreateDraft:true});
const context=(id:string,capabilities:readonly any[]=["product.edit"]):OperationContext=>({organizationId:"org-a",operationId:id,businessRequest:{id,payloadFingerprint:id},principal:{kind:"staff",organizationId:"org-a",userId:"staff-a",authority:{membershipId:"membership-a",capabilities}}});

class DraftTransaction implements ProductVersionTransaction {
  readonly requests=new Map<string,ProductVersionLifecycle>();
  readonly product={activePointer:"active-a",activeTree:structuredClone(activeTree),activeUpdatedAt,draftTree:undefined as unknown};
  async reserve(input:any){const replay=this.requests.get(input.businessRequestId);return replay?{kind:"replay" as const,request:{id:input.businessRequestId,resultJson:replay}}:{kind:"new" as const,request:{id:input.businessRequestId,resultJson:null}};}
  async createDraftFromActive(input:any){if(!this.product.activePointer)throw new V2ApplicationError("CONFLICT","This Product has no Active version to draft from.");if(input.expectedActiveVersionUpdatedAt!==this.product.activeUpdatedAt)throw new V2ApplicationError("STALE_STATE","The Product Active version changed. Refresh and try again.");if(this.product.draftTree)throw new V2ApplicationError("CONFLICT","A Draft already exists for this Product.");this.product.draftTree=structuredClone(this.product.activeTree);return {draftId:"draft-a",lifecycle:{active:active(),draft:{status:"draft" as const,createdAt:"2026-08-18T12:01:00.000Z",updatedAt:"2026-08-18T12:01:00.000Z",editable:true},history:[],historyLimit:25,historyHasMore:false,canCreateDraft:false}};}
  async abandonDraft(input:any){if(!this.product.draftTree)throw new V2ApplicationError("CONFLICT","Only the current Draft can be abandoned.");if(input.draftVersionId!=="draft-a"||input.expectedDraftUpdatedAt!=="2026-08-18T12:01:00.000Z")throw new V2ApplicationError("STALE_STATE","This Draft changed elsewhere. Refresh and try again.");this.product.draftTree=undefined;return {active:active(),history:[{productVersionId:"draft-a",status:"archived" as const,createdAt:"2026-08-18T12:01:00.000Z",updatedAt:"2026-08-18T12:02:00.000Z",editable:false}],historyLimit:25,historyHasMore:false,canCreateDraft:true};}
  async succeed(_org:string,requestId:string,_draftId:string,lifecycle:ProductVersionLifecycle){this.requests.set(requestId,lifecycle);}
  async attribute(){return;}
  async audit(){return;}
}
class SerialRunner implements ProductVersionTransactionRunner { private tail=Promise.resolve(); constructor(readonly tx=new DraftTransaction()){} async transaction<T>(action:(tx:ProductVersionTransaction)=>Promise<T>):Promise<T>{const run=this.tail.then(()=>action(this.tx));this.tail=run.then(()=>undefined,()=>undefined);return run;} }

describe("P2 Product Version lifecycle command",()=>{
  test("copies ACTIVE to a separate DRAFT without mutating ACTIVE or its Product pointer",async()=>{const runner=new SerialRunner(),service=new ProductVersionLifecycleApplicationService(runner);const before=structuredClone(runner.tx.product.activeTree);const result=await service.createDraft(context("draft-1"),{productId:"product-a",businessRequestId:"draft-1",expectedActiveVersionUpdatedAt:activeUpdatedAt});expect(result).toMatchObject({ok:true,value:{active:active(),draft:{status:"draft",editable:true},canCreateDraft:false}});expect(runner.tx.product.activePointer).toBe("active-a");expect(runner.tx.product.activeTree).toEqual(before);expect(runner.tx.product.draftTree).toEqual(before);expect(runner.tx.product.draftTree).not.toBe(runner.tx.product.activeTree);});
  test("replays the same business request and rejects a second concurrent logical draft",async()=>{const runner=new SerialRunner(),service=new ProductVersionLifecycleApplicationService(runner);const first=service.createDraft(context("same"),{productId:"product-a",businessRequestId:"same",expectedActiveVersionUpdatedAt:activeUpdatedAt});const concurrent=service.createDraft(context("other"),{productId:"product-a",businessRequestId:"other",expectedActiveVersionUpdatedAt:activeUpdatedAt});const [created,blocked]=await Promise.all([first,concurrent]);expect(created.ok).toBe(true);expect(blocked).toMatchObject({ok:false,error:{code:"CONFLICT"}});const replay=await service.createDraft(context("same"),{productId:"product-a",businessRequestId:"same",expectedActiveVersionUpdatedAt:activeUpdatedAt});expect(replay).toEqual(created);});
  test("fails safely for stale state, draft-only state, and insufficient Product permission",async()=>{const staleRunner=new SerialRunner(),stale=new ProductVersionLifecycleApplicationService(staleRunner);await expect(stale.createDraft(context("stale"),{productId:"product-a",businessRequestId:"stale",expectedActiveVersionUpdatedAt:"2026-08-18T11:00:00.000Z"})).resolves.toMatchObject({ok:false,error:{code:"STALE_STATE"}});const noActiveRunner=new SerialRunner();noActiveRunner.tx.product.activePointer="";const noActive=new ProductVersionLifecycleApplicationService(noActiveRunner);await expect(noActive.createDraft(context("none"),{productId:"product-a",businessRequestId:"none",expectedActiveVersionUpdatedAt:activeUpdatedAt})).resolves.toMatchObject({ok:false,error:{code:"CONFLICT"}});const denied=new ProductVersionLifecycleApplicationService(new SerialRunner());await expect(denied.createDraft(context("denied",["product.view"]),{productId:"product-a",businessRequestId:"denied",expectedActiveVersionUpdatedAt:activeUpdatedAt})).resolves.toMatchObject({ok:false,error:{code:"FORBIDDEN"}});});
  test("archives an abandoned Draft without changing Active and permits a fresh Draft",async()=>{const runner=new SerialRunner(),service=new ProductVersionLifecycleApplicationService(runner);await service.createDraft(context("create"),{productId:"product-a",businessRequestId:"create",expectedActiveVersionUpdatedAt:activeUpdatedAt});const before=structuredClone(runner.tx.product.activeTree);const abandoned=await service.abandonDraft(context("abandon"),{productId:"product-a",draftVersionId:"draft-a",businessRequestId:"abandon",expectedDraftUpdatedAt:"2026-08-18T12:01:00.000Z"});expect(abandoned).toMatchObject({ok:true,value:{active:active(),history:[{productVersionId:"draft-a",status:"archived"}],canCreateDraft:true}});expect(runner.tx.product.activePointer).toBe("active-a");expect(runner.tx.product.activeTree).toEqual(before);expect(runner.tx.product.draftTree).toBeUndefined();const fresh=await service.createDraft(context("fresh"),{productId:"product-a",businessRequestId:"fresh",expectedActiveVersionUpdatedAt:activeUpdatedAt});expect(fresh).toMatchObject({ok:true,value:{draft:{status:"draft"}}});const denied=await service.abandonDraft(context("denied",["product.view"]),{productId:"product-a",draftVersionId:"draft-a",businessRequestId:"denied",expectedDraftUpdatedAt:"2026-08-18T12:01:00.000Z"});expect(denied).toMatchObject({ok:false,error:{code:"FORBIDDEN"}});});
});
