import assert from "node:assert/strict";
import type { OperationContext } from "../../src/application/operation.js";
import { ProductionApplicationService } from "../../src/modules/production/productionApplication.js";
import { availableForRun } from "../../src/modules/production/productionRuns.js";
import type { ProductionAttempt, ProductionOutputDisposition, ProductionWork, ProductionWorkEvent, ProductionWorkProjection } from "../../src/modules/production/contracts.js";
import { brandedId } from "../../src/modules/shared/commercialValues.js";

const org=brandedId<"OrganizationId">("reject-org"),other=brandedId<"OrganizationId">("other-org");
const work:ProductionWork={productionWorkId:brandedId<"ProductionWorkId">("reject-work"),organizationId:org,orderId:brandedId<"OrderId">("reject-order"),orderLineId:brandedId<"OrderLineId">("reject-line"),requirement:{key:"front",side:"front"},artworkAssignmentId:brandedId<"ArtworkAssignmentId">("reject-art"),artworkFileId:brandedId<"ArtworkFileId">("reject-file"),orderedQuantity:100,createdAt:"2026-09-13T00:00:00.000Z",createdPrincipalKind:"staff",createdPrincipalSubject:"operator"};
const attempt:ProductionAttempt={productionAttemptId:brandedId<"ProductionAttemptId">("reject-attempt"),organizationId:org,productionWorkId:work.productionWorkId,sequence:1,kind:"initial",stationKey:"flatbed",goodQuantity:100,wasteQuantity:0,startedAt:"2026-09-13T00:00:00.000Z",startedPrincipalKind:"staff",startedPrincipalSubject:"operator",completedAt:"2026-09-13T00:01:00.000Z",completedPrincipalKind:"staff",completedPrincipalSubject:"operator",terminalDisposition:"successful"};
const dispositions:ProductionOutputDisposition[]=[];const events:ProductionWorkEvent[]=[];
let fulfilled=0,prepared=false,lifecycleCalls=0;
const request=new Map<string,{fingerprint:string;result:unknown}>();
const projection=():ProductionWorkProjection=>{const rejected=dispositions.reduce((n,x)=>n+x.rejectedQuantity,0),usable=attempt.goodQuantity-rejected;return {work,attempts:[attempt],completedGoodQuantity:100,recordedGoodQuantity:100,rejectedGoodQuantity:rejected,usableGoodQuantity:usable,remainingGoodQuantity:100-usable,unitQuantitySatisfied:usable>=100,state:usable>=100?"complete":"ready",exceptionEvents:events,outputDispositions:dispositions};};
const tx={
 reserve:async(input:{businessRequestId:string;payloadFingerprint:string})=>{const prior=request.get(input.businessRequestId);if(prior){if(prior.fingerprint!==input.payloadFingerprint)throw Error("Idempotency key was reused with a different payload.");return {kind:"replay" as const,request:{id:input.businessRequestId,resultJson:prior.result}};}request.set(input.businessRequestId,{fingerprint:input.payloadFingerprint,result:null});return {kind:"new" as const,request:{id:input.businessRequestId,resultJson:null}};},
 succeed:async(_org:string,id:string,result:unknown)=>{request.get(id)!.result=result;},attribute:async()=>undefined,audit:async()=>undefined,
 lockWork:async(organizationId:string)=>organizationId===org?work:null,findWork:async()=>work,lockAttempt:async(organizationId:string,id:string)=>organizationId===org&&id===attempt.productionAttemptId?attempt:null,
 rejectAcceptedOutput:async(input:{id:string;rejectedQuantity:number;productionAttemptId:string;organizationId:string;productionWorkId:string;reason:string;category?:string})=>{if(input.organizationId!==org||input.productionWorkId!==work.productionWorkId||input.productionAttemptId!==attempt.productionAttemptId)throw Error("Production output lineage was not found.");if(prepared)throw Error("Correct or void the prepared shipment reservation before rejecting Production output.");const unfulfilled=projection().usableGoodQuantity-fulfilled,attemptRemaining=attempt.goodQuantity-dispositions.reduce((n,x)=>n+x.rejectedQuantity,0);if(input.rejectedQuantity>unfulfilled||input.rejectedQuantity>attemptRemaining)throw Error("Rejected quantity exceeds unfulfilled usable Production output.");const item:ProductionOutputDisposition={productionOutputDispositionId:brandedId<"ProductionOutputDispositionId">(input.id),organizationId:org,productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:input.rejectedQuantity,...(input.category?{category:input.category}:{}),reason:input.reason,createdAt:"2026-09-13T00:02:00.000Z",createdPrincipalKind:"staff",createdPrincipalSubject:"operator"};dispositions.push(item);return item;},
 appendWorkEvent:async(input:any)=>{const event:ProductionWorkEvent={productionWorkEventId:input.id,organizationId:org,productionWorkId:work.productionWorkId,sequence:events.length+1,kind:input.kind,reason:input.reason,productionAttemptId:attempt.productionAttemptId,createdAt:"2026-09-13T00:02:00.000Z",createdPrincipalKind:"staff",createdPrincipalSubject:"operator"};events.push(event);return event;},
 readWork:async()=>projection(),listStationQueue:async()=>({items:[projection()],pagination:{page:1,pageSize:25,totalCount:1,totalPages:1}}),listOrderWorks:async()=>[projection()],eligibleProductionAssignment:async()=>true,createOrGetWork:async()=>work,startAttempt:async()=>attempt,recordOutput:async()=>attempt,completeAttempt:async()=>attempt,createReworkSuccessor:async()=>{throw Error("not used");},
};
const context=(id:string,capabilities:readonly string[]=["production.output.reject"],organizationId=org):OperationContext=>({organizationId,operationId:id,businessRequest:{id,payloadFingerprint:id},principal:{kind:"staff",organizationId,userId:"operator",authority:{membershipId:"membership",capabilities:capabilities as any}}});
const service=new ProductionApplicationService({transaction:async(fn)=>fn(tx as never)},undefined,{reconcileOrder:async()=>{lifecycleCalls++;}} as never);

const first=await service.rejectOutput(context("reject-20"),{businessRequestId:"reject-20",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:20,reason:"Print defect",category:"quality"});
assert.equal(first.ok,true);assert.equal(attempt.goodQuantity,100,"historical accepted output remains immutable");assert.deepEqual({recorded:projection().recordedGoodQuantity,usable:projection().usableGoodQuantity,remaining:projection().remainingGoodQuantity},{recorded:100,usable:80,remaining:20});assert.equal(lifecycleCalls,1,"rejection invokes ordinary lifecycle reconciliation");
assert.equal(availableForRun({productionWorkId:work.productionWorkId,stationKey:"flatbed",materialFingerprint:null,orderedQuantity:100,recordedGoodQuantity:projection().usableGoodQuantity,reservedByOtherRuns:0,requestedQuantity:20}),20,"a normal successor Run can reserve only the replacement quantity");
assert.equal(Math.max(0,projection().usableGoodQuantity-fulfilled),80,"Fulfillment can see only usable accepted good output");
const replay=await service.rejectOutput(context("reject-20"),{businessRequestId:"reject-20",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:20,reason:"Print defect",category:"quality"});assert.equal(replay.ok,true);assert.equal(dispositions.length,1,"exact retry is idempotent");
const changed=await service.rejectOutput(context("reject-20"),{businessRequestId:"reject-20",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:10,reason:"Changed"});assert.equal(changed.ok,false,"changed retry conflicts");
fulfilled=80;const fulfilledBlocked=await service.rejectOutput(context("fulfilled-block"),{businessRequestId:"fulfilled-block",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:1,reason:"Too late"});assert.equal(fulfilledBlocked.ok,false,"already fulfilled usable output cannot be rejected");
fulfilled=0;prepared=true;const preparedBlocked=await service.rejectOutput(context("prepared-block"),{businessRequestId:"prepared-block",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:1,reason:"Reserved"});assert.equal(preparedBlocked.ok,false,"prepared shipment reservation blocks rejection");
prepared=false;const afterRelease=await service.rejectOutput(context("after-release"),{businessRequestId:"after-release",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:1,reason:"Released shipment"});assert.equal(afterRelease.ok,true,"released prepared reservation permits normal rejection");
const over=await service.rejectOutput(context("over"),{businessRequestId:"over",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:80,reason:"Over cap"});assert.equal(over.ok,false,"rejection cannot exceed unfulfilled usable output");
const denied=await service.rejectOutput(context("denied",["production.view"]),{businessRequestId:"denied",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:1,reason:"No authority"});assert.equal(denied.ok,false,"permission is enforced");
const foreign=await service.rejectOutput(context("foreign",["production.output.reject"],other),{businessRequestId:"foreign",productionWorkId:work.productionWorkId,productionAttemptId:attempt.productionAttemptId,rejectedQuantity:1,reason:"Wrong tenant"});assert.equal(foreign.ok,false,"cross-tenant output is rejected");
console.log("Production output disposition authority contract passed.");
