import { describe, expect, test } from "@jest/globals";
import { ProductVersionLifecycleApplicationService, type ProductDraftPricing, type ProductVersionTransactionRunner } from "../../src/modules/products/productVersionLifecycle";
import type { OperationContext } from "../../src/application/operation";
import { V2ApplicationError } from "../../src/errors/applicationError";

const context=(id:string,caps:readonly any[]=["product.edit"]):OperationContext=>({organizationId:"org-a",operationId:id,businessRequest:{id,payloadFingerprint:id},principal:{kind:"staff",organizationId:"org-a",userId:"staff",authority:{membershipId:"membership",capabilities:caps}}});
const base={perPieceCents:null,perSqftCents:500,minimumChargeCents:1000};
const input={productId:"product",draftVersionId:"draft",expectedDraftUpdatedAt:"2026-08-18T12:00:00.000Z",businessRequestId:"pricing-1",base,tierBasis:"square_foot" as const,tiers:[{tierId:"tier-1",minimum:1,maximum:24,perPieceCents:null,perSqftCents:400,minimumChargeCents:1500}]};
class Runner implements ProductVersionTransactionRunner { updated=input.expectedDraftUpdatedAt; requests=new Map<string,ProductDraftPricing>(); async transaction<T>(action:any):Promise<T>{return action({reserve:async(value:any)=>this.requests.has(value.businessRequestId)?{kind:"replay",request:{id:value.businessRequestId,resultJson:this.requests.get(value.businessRequestId)}}:{kind:"new",request:{id:value.businessRequestId,resultJson:null}},updateDraftPricing:async(value:any)=>{if(value.expectedDraftUpdatedAt!==this.updated)throw new V2ApplicationError("STALE_STATE","Draft changed");this.updated="2026-08-18T12:01:00.000Z";return{productId:"product",draftVersionId:"draft",draftUpdatedAt:this.updated,lifecycle:"draft",measurementMode:"dimensions_required",mode:"simple_with_tiers",editable:true,base:value.base,tierBasis:value.tierBasis,tiers:value.tiers};},succeed:async(_o:string,id:string,_r:string,value:ProductDraftPricing)=>this.requests.set(id,value),attribute:async()=>undefined,auditDraftPricing:async()=>undefined});}}
describe("P5 Draft Pricing command",()=>{test("saves simple pricing, replays exactly, and rejects stale, permission, mixed-rate, and invalid-tier writes",async()=>{const runner=new Runner(),service=new ProductVersionLifecycleApplicationService(runner);const saved=await service.updateDraftPricing(context("pricing-1"),input);expect(saved).toMatchObject({ok:true,value:{base,tierBasis:"square_foot",tiers:[{minimum:1,maximum:24,minimumChargeCents:1500}]}});await expect(service.updateDraftPricing(context("pricing-1"),input)).resolves.toEqual(saved);await expect(service.updateDraftPricing(context("stale"),{...input,businessRequestId:"stale"})).resolves.toMatchObject({ok:false,error:{code:"STALE_STATE"}});await expect(service.updateDraftPricing(context("denied",["product.view"]),{...input,businessRequestId:"denied"})).resolves.toMatchObject({ok:false,error:{code:"FORBIDDEN"}});await expect(service.updateDraftPricing(context("mixed"),{...input,businessRequestId:"mixed",base:{...base,perPieceCents:1}})).resolves.toMatchObject({ok:false,error:{code:"VALIDATION_ERROR"}});await expect(service.updateDraftPricing(context("tiers"),{...input,businessRequestId:"tiers",tiers:[{...input.tiers[0]!,minimum:2},{...input.tiers[0]!,tierId:"tier-2",minimum:2}]})).resolves.toMatchObject({ok:false,error:{code:"VALIDATION_ERROR"}});await expect(service.updateDraftPricing(context("bad-boundary"),{...input,businessRequestId:"bad-boundary",tiers:[{...input.tiers[0]!,maximum:0}]})).resolves.toMatchObject({ok:false,error:{code:"VALIDATION_ERROR"}});});});
