import assert from "node:assert/strict";
import { assertCompatibleRunMembers, availableForRun, canCompleteProductionRun, canRefreshRunPreparation, nextRunState, preparedArtworkIsCurrent, remainingRunAllocation, runAllocationIsResolved, terminalDispositionForRunAllocation, unusedRunReservationQuantity } from "../../src/modules/production/productionRuns.js";

const base={productionWorkId:"work-a",stationKey:"flatbed" as const,materialFingerprint:"material:coroplast",orderedQuantity:100,recordedGoodQuantity:20,reservedByOtherRuns:30,requestedQuantity:50};
assert.equal(availableForRun(base),50);
assertCompatibleRunMembers("flatbed",[base,{...base,productionWorkId:"work-b",requestedQuantity:1}]);
assert.throws(()=>assertCompatibleRunMembers("roll",[base]),/frozen station/);
assert.throws(()=>assertCompatibleRunMembers("flatbed",[{...base,requestedQuantity:51}]),/exceeds/);
assert.throws(()=>assertCompatibleRunMembers("flatbed",[base,{...base}]),/only once/);
assert.equal(nextRunState("draft","ready"),"ready");
assert.equal(nextRunState("ready","start"),"active");
assert.equal(nextRunState("active","hold"),"held");
assert.equal(nextRunState("held","resume"),"active");
assert.throws(()=>nextRunState("active","complete",false),/every allocation/);
assert.equal(nextRunState("active","complete",true),"completed");
assert.equal(remainingRunAllocation(50,20,4),30);
assert.throws(()=>remainingRunAllocation(50,51,0),/exceeds/);
assert.equal(terminalDispositionForRunAllocation(50,50,false),"successful");
assert.equal(terminalDispositionForRunAllocation(50,20,false),"released");
assert.equal(terminalDispositionForRunAllocation(50,0,true),"cancelled");
assert.throws(()=>terminalDispositionForRunAllocation(50,51,false),/valid Production/);
const artworkA={artworkAssignmentId:"assignment-a",artworkFileId:"file-a",identityFingerprint:`sha256:${"a".repeat(64)}`,objectVersion:"A"};
assert.equal(preparedArtworkIsCurrent(artworkA,artworkA),true);
assert.equal(preparedArtworkIsCurrent(artworkA,{...artworkA,objectVersion:"B"}),false);
assert.equal(canRefreshRunPreparation("draft"),true);
assert.equal(canRefreshRunPreparation("ready"),true);
assert.equal(canRefreshRunPreparation("active"),false);
assert.equal(unusedRunReservationQuantity(50,20,false),30);
assert.equal(unusedRunReservationQuantity(50,20,true),0);
assert.equal(runAllocationIsResolved({allocatedQuantity:50,goodQuantity:20}),false);
assert.equal(runAllocationIsResolved({allocatedQuantity:50,goodQuantity:20,releasedAt:"now"}),true);
assert.equal(canCompleteProductionRun([{allocatedQuantity:50,goodQuantity:50},{allocatedQuantity:50,goodQuantity:20,releasedAt:"now"}]),true);
assert.equal(canCompleteProductionRun([{allocatedQuantity:50,goodQuantity:20}]),false);
console.log("Production Run domain contracts passed.");
