import { describe, expect, test } from "@jest/globals";
import { ProductVersionLifecycleApplicationService, type ProductDraftPricingMatrix, type ProductVersionTransactionRunner } from "../../src/modules/products/productVersionLifecycle";
import type { OperationContext } from "../../src/application/operation";
import { V2ApplicationError } from "../../src/errors/applicationError";

const context=(id:string,caps:readonly any[]=["product.edit"]):OperationContext=>({organizationId:"org-a",operationId:id,businessRequest:{id,payloadFingerprint:id},principal:{kind:"staff",organizationId:"org-a",userId:"staff",authority:{membershipId:"membership",capabilities:caps}}});
const input={productId:"product",draftVersionId:"draft",expectedDraftUpdatedAt:"2026-08-18T12:00:00.000Z",businessRequestId:"matrix-1",matrixId:"matrix-a",pricingUnit:"per_piece" as const,dimensions:["finish"],rows:[{rowId:"row-a",combination:{finish:"matte"},baseRateCents:500,tierBasis:null,tiers:[]}]};
class Runner implements ProductVersionTransactionRunner { updated=input.expectedDraftUpdatedAt;requests=new Map<string,ProductDraftPricingMatrix>();async transaction<T>(action:any):Promise<T>{return action({reserve:async(value:any)=>this.requests.has(value.businessRequestId)?{kind:"replay",request:{id:value.businessRequestId,resultJson:this.requests.get(value.businessRequestId)}}:{kind:"new",request:{id:value.businessRequestId,resultJson:null}},updateDraftPricingMatrix:async(value:any)=>{if(value.expectedDraftUpdatedAt!==this.updated)throw new V2ApplicationError("STALE_STATE","Draft changed");this.updated="2026-08-18T12:01:00.000Z";return{productId:"product",draftVersionId:"draft",draftUpdatedAt:this.updated,lifecycle:"draft",editable:true,matrixId:value.matrix.matrixId,pricingUnit:value.matrix.pricingUnit,dimensions:[{selectionKey:"finish",label:"Finish",values:[{value:"matte",label:"Matte"}]}],rows:value.matrix.rows,warnings:[]};},succeed:async(_o:string,id:string,_r:string,value:ProductDraftPricingMatrix)=>this.requests.set(id,value),attribute:async()=>undefined,auditDraftPricingMatrix:async()=>undefined});}}
describe("P6A Draft Matrix command",()=>{test("saves stable matrix identities, replays exactly, and rejects stale and unauthorized writes",async()=>{const runner=new Runner(),service=new ProductVersionLifecycleApplicationService(runner);const saved=await service.updateDraftPricingMatrix(context("matrix-1"),input);expect(saved).toMatchObject({ok:true,value:{dimensions:[{selectionKey:"finish"}],rows:[{rowId:"row-a",combination:{finish:"matte"},baseRateCents:500}]}});await expect(service.updateDraftPricingMatrix(context("matrix-1"),input)).resolves.toEqual(saved);await expect(service.updateDraftPricingMatrix(context("stale"),{...input,businessRequestId:"stale"})).resolves.toMatchObject({ok:false,error:{code:"STALE_STATE"}});await expect(service.updateDraftPricingMatrix(context("denied",["product.view"]),{...input,businessRequestId:"denied"})).resolves.toMatchObject({ok:false,error:{code:"FORBIDDEN"}});});});
