import { describe, expect, test } from "@jest/globals";
import { V2ApplicationError } from "../../src/errors/applicationError";
import { ProductVersionLifecycleApplicationService, type ProductDraftFormulaPricing, type ProductVersionTransactionRunner } from "../../src/modules/products/productVersionLifecycle";
import { evaluateResolvedFormula } from "../../src/modules/pricing/v2PricingAdapter";
import type { StaffPrincipal } from "../../src/authorization/principals";

const principal=(capabilities:readonly("product.view"|"product.edit")[]=["product.view","product.edit"]):StaffPrincipal=>({kind:"staff",organizationId:"org",userId:"staff",authority:{membershipId:"membership",capabilities}});
const input={productId:"product",draftVersionId:"draft",expectedDraftUpdatedAt:"2026-08-18T12:00:00.000Z",businessRequestId:"formula-1",expression:"q * p",variables:{p:500}};
const context=(id:string,capabilities:readonly("product.view"|"product.edit")[]=["product.view","product.edit"])=>({principal:principal(capabilities),organizationId:"org",operationId:id,businessRequest:{id,payloadFingerprint:id}});
class Runner implements ProductVersionTransactionRunner { updated=input.expectedDraftUpdatedAt; requests=new Map<string,ProductDraftFormulaPricing>(); async transaction<T>(action:any):Promise<T>{return action({reserve:async(value:any)=>this.requests.has(value.businessRequestId)?{kind:"replay",request:{id:value.businessRequestId,resultJson:this.requests.get(value.businessRequestId)}}:{kind:"new",request:{id:value.businessRequestId,resultJson:null}},updateDraftFormulaPricing:async(value:any)=>{if(value.expectedDraftUpdatedAt!==this.updated)throw new V2ApplicationError("STALE_STATE","Draft changed");this.updated="2026-08-18T12:01:00.000Z";return{productId:"product",draftVersionId:"draft",draftUpdatedAt:this.updated,lifecycle:"draft",source:"embedded_editable",editable:true,expressionEditable:true,variablesEditable:true,inputs:[{key:"p",label:"p"}],expression:value.formula.expression,variables:value.formula.variables,supportedRuntimeVariables:["q","p"],warnings:[]};},succeed:async(_o:string,id:string,_r:string,value:ProductDraftFormulaPricing)=>this.requests.set(id,value),attribute:async()=>undefined,auditDraftFormulaPricing:async()=>undefined});}}
describe("P6B Draft Formula command",()=>{test("replays exactly and rejects stale and unauthorized writes",async()=>{const runner=new Runner(),service=new ProductVersionLifecycleApplicationService(runner),saved=await service.updateDraftFormulaPricing(context("formula-1"),input);expect(saved).toMatchObject({ok:true,value:{expression:"q * p",variables:{p:500}}});await expect(service.updateDraftFormulaPricing(context("formula-1"),input)).resolves.toEqual(saved);await expect(service.updateDraftFormulaPricing(context("stale"),{...input,businessRequestId:"stale"})).resolves.toMatchObject({ok:false,error:{code:"STALE_STATE"}});await expect(service.updateDraftFormulaPricing(context("denied",["product.view"]),{...input,businessRequestId:"denied"})).resolves.toMatchObject({ok:false,error:{code:"FORBIDDEN"}});});});
describe("P6B Formula language",()=>{test("uses the existing constrained evaluator, including legacy leading decimals",()=>{expect(evaluateResolvedFormula("ceil((w + .25) / 2) * p",{w:3,p:2})).toBe(4);expect(()=>evaluateResolvedFormula("floor(q)",{q:1})).toThrow("Unknown pricing formula variable");expect(()=>evaluateResolvedFormula("q +",{q:1})).toThrow();});});
