import assert from "node:assert/strict";
import { resolveShipmentSender, requireShipmentSenderSnapshot, type ShippingSender } from "../../src/modules/fulfillment/shipmentSender.js";
const sender:ShippingSender={company:"Customer Returns",addressLine1:"Billing Way",city:"Tampa",region:"FL",postalCode:"12345",country:"US"};
const rows=[{orderId:"order-a",customerId:"customer-a",defaultBlindShipping:true,billingSender:sender},{orderId:"order-b",customerId:"customer-a",defaultBlindShipping:true,billingSender:sender}];
assert.equal(resolveShipmentSender(rows).source,"customer","historical/unspecified source resolves whole Customer billing address");
assert.equal(resolveShipmentSender(rows,rows.map(row=>({orderId:row.orderId,blindShipping:false}))).blindShipping,false,"explicit false overrides Customer default");
assert.equal(resolveShipmentSender(rows.map(row=>({...row,defaultBlindShipping:false})),rows.map(row=>({orderId:row.orderId,blindShipping:true}))).blindShipping,true);
assert.throws(()=>resolveShipmentSender(rows,[{orderId:"order-a",blindShipping:false}]),/incompatible/);
assert.throws(()=>resolveShipmentSender(rows,[{orderId:"order-a",source:"custom",customSender:{...sender,company:"Different"}}]),/incompatible/);
assert.throws(()=>resolveShipmentSender(rows,[{orderId:"order-a",source:"custom",customSender:sender}]),/incompatible/,"even identical data cannot mix Customer and Custom sources");
assert.throws(()=>resolveShipmentSender([rows[0]!],[{orderId:"order-a",source:"custom",customSender:{company:"Incomplete"} as ShippingSender}]),/required/);
assert.equal(resolveShipmentSender([rows[0]!],[{orderId:"order-a",customSender:{company:"Legacy incomplete"} as ShippingSender}]).source,"customer","no explicit source retains historic whole-Customer fallback");
const custom=resolveShipmentSender([rows[0]!],[{orderId:"order-a",source:"custom",customSender:sender}]);assert.deepEqual(custom.sender,sender);assert.equal(custom.source,"custom");
const customer=resolveShipmentSender([rows[0]!],[{orderId:"order-a",source:"customer",customSender:{...sender,company:"Stale custom"}}]);assert.equal(customer.sender?.company,sender.company,"Customer selection ignores stale Custom data");
assert.equal(customer.intents[0]?.customSender,undefined,"public domain result does not disclose an actor's inactive Custom payload");
assert.equal(resolveShipmentSender([rows[0]!],[{orderId:"order-a",blindShipping:false,customSender:sender}]).intents[0]?.customSender,undefined);
assert.throws(()=>requireShipmentSenderSnapshot(null),/unavailable/);
assert.throws(()=>resolveShipmentSender([{...rows[0]!,billingSender:{...sender,city:null}}]),/required/,"incomplete Customer does not substitute Ship To or organization branding");
console.log("shipmentSender: 15 bounded sender identity/default/source checks PASS");
