CREATE TABLE IF NOT EXISTS "pbv2_option_group_templates" (
  "id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" varchar REFERENCES "organizations"("id") ON DELETE cascade,
  "is_system_template" boolean DEFAULT false NOT NULL,
  "state" text DEFAULT 'active' NOT NULL,
  "category" text NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "description" text,
  "tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "difficulty_level" text,
  "recommended_product_types" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "recommended_industries" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "recommended_pairings" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "compatibility_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "workflow_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "pricing_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "intent_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "preview_config" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "template_tree" jsonb NOT NULL,
  "created_by" varchar REFERENCES "users"("id") ON DELETE set null,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "archived_at" timestamp with time zone,
  CONSTRAINT "pbv2_option_group_templates_state_check" CHECK ("state" IN ('active', 'archived')),
  CONSTRAINT "pbv2_option_group_templates_system_org_check" CHECK (
    ("is_system_template" = true AND "organization_id" IS NULL)
    OR ("is_system_template" = false AND "organization_id" IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS "pbv2_option_group_templates_org_state_idx" ON "pbv2_option_group_templates" ("organization_id", "state");
CREATE INDEX IF NOT EXISTS "pbv2_option_group_templates_category_state_idx" ON "pbv2_option_group_templates" ("category", "state");
CREATE INDEX IF NOT EXISTS "pbv2_option_group_templates_system_idx" ON "pbv2_option_group_templates" ("is_system_template");
CREATE INDEX IF NOT EXISTS "pbv2_option_group_templates_slug_idx" ON "pbv2_option_group_templates" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "pbv2_option_group_templates_system_slug_uidx"
  ON "pbv2_option_group_templates" ("slug")
  WHERE "is_system_template" = true;
CREATE UNIQUE INDEX IF NOT EXISTS "pbv2_option_group_templates_org_slug_uidx"
  ON "pbv2_option_group_templates" ("organization_id", "slug")
  WHERE "is_system_template" = false AND "organization_id" IS NOT NULL;

INSERT INTO "pbv2_option_group_templates" (
  "id",
  "organization_id",
  "is_system_template",
  "state",
  "category",
  "name",
  "slug",
  "description",
  "tags",
  "difficulty_level",
  "recommended_product_types",
  "recommended_industries",
  "recommended_pairings",
  "compatibility_metadata",
  "workflow_metadata",
  "pricing_metadata",
  "intent_metadata",
  "preview_config",
  "template_tree"
)
VALUES
(
  'system_lamination',
  NULL,
  true,
  'active',
  'Finishing',
  'Lamination',
  'lamination',
  'Adds a simple lamination choice set for gloss or matte finishing.',
  '["finishing","protective","stickers","signage"]'::jsonb,
  'beginner',
  '["stickers","decals","signage","flat_goods"]'::jsonb,
  '["print_shop","wide_format","sign_shop"]'::jsonb,
  '["contour-cutting","white-ink"]'::jsonb,
  '{"compatibleProductTypes":["stickers","decals","signage"],"requiresCapabilities":[]}'::jsonb,
  '{"finishing_required":true,"requires_proof":false}'::jsonb,
  '{"pricingBehavior":"Often priced per square foot or as a finishing surcharge."}'::jsonb,
  '{"intent":"Offer protective or visual finish options.","productionImplications":["Adds finishing step after print"],"pricingBehavior":"per_sqft_or_flat","commonPairings":["Contour Cutting"],"onboardingNotes":["Use None as the default when lamination is optional."]}'::jsonb,
  '{"usedFor":"Protective finish and customer-facing sheen selection.","workflowImplications":["finishing"],"pricingImplications":["per_sqft finishing surcharge"]}'::jsonb,
  '{"schemaVersion":2,"templateKind":"pbv2_option_group_template","rootGroupId":"group_lamination","rootNodeIds":["group_lamination"],"nodes":{"group_lamination":{"id":"group_lamination","type":"GROUP","kind":"group","label":"Lamination","name":"Lamination","description":"Protective finish applied after printing.","displayOrder":0,"ui":{"sortOrder":0},"status":"ENABLED"},"opt_lamination_finish":{"id":"opt_lamination_finish","type":"OPTION","kind":"question","label":"Lamination","name":"Lamination","description":"Choose whether lamination is applied.","displayOrder":0,"input":{"selectionKey":"lamination_finish","type":"select","required":false,"defaultValue":"none","choices":[{"value":"none","label":"None"},{"value":"gloss","label":"Gloss"},{"value":"matte","label":"Matte"}]},"status":"ENABLED"}},"edges":[{"id":"edge_lamination_finish","fromNodeId":"group_lamination","toNodeId":"opt_lamination_finish","status":"DISABLED","condition":{"op":"EXISTS","value":{"op":"literal","value":true}}}],"rules":[]}'::jsonb
),
(
  'system_grommets',
  NULL,
  true,
  'active',
  'Finishing',
  'Grommets',
  'grommets',
  'Adds common grommet placement choices for banners and signs.',
  '["finishing","hardware","banners"]'::jsonb,
  'beginner',
  '["banners","signage","mesh_banners"]'::jsonb,
  '["sign_shop","wide_format"]'::jsonb,
  '["hemming","pole-pockets"]'::jsonb,
  '{"compatibleProductTypes":["banners","signage"],"requiresCapabilities":["grommet_press"]}'::jsonb,
  '{"finishing_required":true,"hardware_required":true}'::jsonb,
  '{"pricingBehavior":"Commonly priced by placement or included in banner finishing tiers."}'::jsonb,
  '{"intent":"Capture hardware placement requirements.","productionImplications":["Hardware finishing and placement checks"],"pricingBehavior":"flat_or_per_piece","onboardingNotes":["Custom placement should request notes or artwork markup."]}'::jsonb,
  '{"usedFor":"Banner hanging hardware and placement instructions.","workflowImplications":["hardware finishing"],"pricingImplications":["flat or per-piece charge"]}'::jsonb,
  '{"schemaVersion":2,"templateKind":"pbv2_option_group_template","rootGroupId":"group_grommets","rootNodeIds":["group_grommets"],"nodes":{"group_grommets":{"id":"group_grommets","type":"GROUP","kind":"group","label":"Grommets","name":"Grommets","description":"Hardware placement for hanging banners.","displayOrder":0,"ui":{"sortOrder":0},"status":"ENABLED"},"opt_grommet_placement":{"id":"opt_grommet_placement","type":"OPTION","kind":"question","label":"Grommet Placement","name":"Grommet Placement","description":"Select where grommets should be installed.","displayOrder":0,"input":{"selectionKey":"grommet_placement","type":"select","required":false,"defaultValue":"none","choices":[{"value":"none","label":"None"},{"value":"corners","label":"Corners"},{"value":"every_2_feet","label":"Every 2 Feet"},{"value":"custom","label":"Custom"}]},"status":"ENABLED"}},"edges":[{"id":"edge_grommet_placement","fromNodeId":"group_grommets","toNodeId":"opt_grommet_placement","status":"DISABLED","condition":{"op":"EXISTS","value":{"op":"literal","value":true}}}],"rules":[]}'::jsonb
),
(
  'system_contour_cutting',
  NULL,
  true,
  'active',
  'Finishing',
  'Contour Cutting',
  'contour-cutting',
  'Adds a yes/no contour cutting option for decals and cut graphics.',
  '["finishing","cutting","decals","stickers"]'::jsonb,
  'intermediate',
  '["stickers","decals","labels","signage"]'::jsonb,
  '["print_shop","sign_shop"]'::jsonb,
  '["lamination","white-ink"]'::jsonb,
  '{"compatibleProductTypes":["stickers","decals","labels"],"requiresCapabilities":["cutter"],"incompatibleCapabilities":[]}'::jsonb,
  '{"requires_vector_art":true,"requires_cutter":true,"finishing_required":true}'::jsonb,
  '{"pricingBehavior":"May add cutting setup, cut path, or per-piece pricing."}'::jsonb,
  '{"intent":"Capture whether the job needs cut-path finishing.","productionImplications":["Prepress must verify vector cut lines"],"pricingBehavior":"setup_or_per_piece","commonPairings":["Lamination"],"setupWarnings":["Reject artwork without a usable cut path when contour cutting is selected."]}'::jsonb,
  '{"usedFor":"Cut-path finishing for stickers, decals, and shaped graphics.","workflowImplications":["requires vector art","requires cutter"],"pricingImplications":["setup or per-piece finishing charge"]}'::jsonb,
  '{"schemaVersion":2,"templateKind":"pbv2_option_group_template","rootGroupId":"group_contour_cutting","rootNodeIds":["group_contour_cutting"],"nodes":{"group_contour_cutting":{"id":"group_contour_cutting","type":"GROUP","kind":"group","label":"Contour Cutting","name":"Contour Cutting","description":"Cut-path finishing choice.","displayOrder":0,"ui":{"sortOrder":0},"status":"ENABLED"},"opt_contour_cutting":{"id":"opt_contour_cutting","type":"OPTION","kind":"question","label":"Contour Cutting","name":"Contour Cutting","description":"Do these graphics need contour cutting?","displayOrder":0,"input":{"selectionKey":"contour_cutting","type":"select","required":false,"defaultValue":"no","choices":[{"value":"no","label":"No"},{"value":"yes","label":"Yes"}]},"status":"ENABLED"}},"edges":[{"id":"edge_contour_cutting","fromNodeId":"group_contour_cutting","toNodeId":"opt_contour_cutting","status":"DISABLED","condition":{"op":"EXISTS","value":{"op":"literal","value":true}}}],"rules":[]}'::jsonb
),
(
  'system_double_sided_printing',
  NULL,
  true,
  'active',
  'Print Setup',
  'Double-Sided Printing',
  'double-sided-printing',
  'Adds single-sided versus double-sided production choice.',
  '["printing","routing","setup"]'::jsonb,
  'beginner',
  '["cards","signage","sheets","rigid_substrates"]'::jsonb,
  '["print_shop","wide_format"]'::jsonb,
  '["rush-service"]'::jsonb,
  '{"compatibleProductionModes":["flatbed","sheet"],"incompatibleProductionModes":[]}'::jsonb,
  '{"may_affect_routing":true,"may_affect_production_time":true}'::jsonb,
  '{"pricingBehavior":"Often priced as a multiplier or second-side surcharge."}'::jsonb,
  '{"intent":"Capture side count for production routing and pricing.","productionImplications":["May require flipping, registration, or additional passes"],"pricingBehavior":"multiplier_or_surcharge","onboardingNotes":["Keep choice values stable because pricing rules may depend on them."]}'::jsonb,
  '{"usedFor":"Side count, routing, and second-side production handling.","workflowImplications":["routing","material handling"],"pricingImplications":["multiplier or second-side surcharge"]}'::jsonb,
  '{"schemaVersion":2,"templateKind":"pbv2_option_group_template","rootGroupId":"group_double_sided","rootNodeIds":["group_double_sided"],"nodes":{"group_double_sided":{"id":"group_double_sided","type":"GROUP","kind":"group","label":"Double-Sided Printing","name":"Double-Sided Printing","description":"One side or two sides.","displayOrder":0,"ui":{"sortOrder":0},"status":"ENABLED"},"opt_print_sides":{"id":"opt_print_sides","type":"OPTION","kind":"question","label":"Print Sides","name":"Print Sides","description":"Choose one-sided or two-sided printing.","displayOrder":0,"input":{"selectionKey":"print_sides","type":"select","required":false,"defaultValue":"single_sided","choices":[{"value":"single_sided","label":"Single-Sided"},{"value":"double_sided","label":"Double-Sided"}]},"status":"ENABLED"}},"edges":[{"id":"edge_print_sides","fromNodeId":"group_double_sided","toNodeId":"opt_print_sides","status":"DISABLED","condition":{"op":"EXISTS","value":{"op":"literal","value":true}}}],"rules":[]}'::jsonb
),
(
  'system_rush_service',
  NULL,
  true,
  'active',
  'Service',
  'Rush Service',
  'rush-service',
  'Adds standard versus rush turnaround choice.',
  '["turnaround","service","scheduling"]'::jsonb,
  'beginner',
  '["all"]'::jsonb,
  '["print_shop","sign_shop"]'::jsonb,
  '["proofing","double-sided-printing"]'::jsonb,
  '{"compatibleProductTypes":["all"],"requiresCapabilities":[]}'::jsonb,
  '{"scheduling_impact":true,"requires_capacity_check":true}'::jsonb,
  '{"pricingBehavior":"Usually priced as a surcharge or percentage uplift."}'::jsonb,
  '{"intent":"Capture schedule pressure before production planning.","productionImplications":["Requires capacity check and possible priority routing"],"pricingBehavior":"surcharge_or_percent","setupWarnings":["Do not promise rush before capacity is confirmed."]}'::jsonb,
  '{"usedFor":"Turnaround selection and production schedule pressure.","workflowImplications":["capacity check","priority routing"],"pricingImplications":["rush surcharge"]}'::jsonb,
  '{"schemaVersion":2,"templateKind":"pbv2_option_group_template","rootGroupId":"group_turnaround","rootNodeIds":["group_turnaround"],"nodes":{"group_turnaround":{"id":"group_turnaround","type":"GROUP","kind":"group","label":"Turnaround","name":"Turnaround","description":"Standard or rush timing.","displayOrder":0,"ui":{"sortOrder":0},"status":"ENABLED"},"opt_turnaround":{"id":"opt_turnaround","type":"OPTION","kind":"question","label":"Turnaround","name":"Turnaround","description":"Select the requested production turnaround.","displayOrder":0,"input":{"selectionKey":"turnaround","type":"select","required":false,"defaultValue":"standard","choices":[{"value":"standard","label":"Standard"},{"value":"rush","label":"Rush"}]},"status":"ENABLED"}},"edges":[{"id":"edge_turnaround","fromNodeId":"group_turnaround","toNodeId":"opt_turnaround","status":"DISABLED","condition":{"op":"EXISTS","value":{"op":"literal","value":true}}}],"rules":[]}'::jsonb
),
(
  'system_white_ink',
  NULL,
  true,
  'active',
  'Print Setup',
  'White Ink',
  'white-ink',
  'Adds white ink setup choices for clear, dark, or specialty media.',
  '["ink","specialty","prepress"]'::jsonb,
  'intermediate',
  '["clear_decals","window_graphics","specialty_media","flatbed"]'::jsonb,
  '["print_shop","wide_format"]'::jsonb,
  '["lamination","contour-cutting"]'::jsonb,
  '{"requiresCapabilities":["white_ink_printer"],"compatibleProductionModes":["flatbed","roll"],"incompatibleCapabilities":[]}'::jsonb,
  '{"requires_proof":true,"requires_white_capable_printer":true,"prepress_setup_required":true}'::jsonb,
  '{"pricingBehavior":"Often priced as a setup and ink coverage surcharge."}'::jsonb,
  '{"intent":"Capture white ink coverage requirements.","productionImplications":["Prepress must verify spot white or flood white setup"],"pricingBehavior":"setup_or_coverage_surcharge","setupWarnings":["Confirm printer capability before quoting."]}'::jsonb,
  '{"usedFor":"White ink setup on clear, colored, or specialty substrates.","workflowImplications":["proofing","white-capable printer"],"pricingImplications":["setup or coverage surcharge"]}'::jsonb,
  '{"schemaVersion":2,"templateKind":"pbv2_option_group_template","rootGroupId":"group_white_ink","rootNodeIds":["group_white_ink"],"nodes":{"group_white_ink":{"id":"group_white_ink","type":"GROUP","kind":"group","label":"White Ink","name":"White Ink","description":"White ink coverage setup.","displayOrder":0,"ui":{"sortOrder":0},"status":"ENABLED"},"opt_white_ink":{"id":"opt_white_ink","type":"OPTION","kind":"question","label":"White Ink","name":"White Ink","description":"Select white ink coverage.","displayOrder":0,"input":{"selectionKey":"white_ink","type":"select","required":false,"defaultValue":"none","choices":[{"value":"none","label":"No White"},{"value":"spot_white","label":"Spot White"},{"value":"flood_white","label":"Flood White"}]},"status":"ENABLED"}},"edges":[{"id":"edge_white_ink","fromNodeId":"group_white_ink","toNodeId":"opt_white_ink","status":"DISABLED","condition":{"op":"EXISTS","value":{"op":"literal","value":true}}}],"rules":[]}'::jsonb
)
ON CONFLICT ("id") DO UPDATE SET
  "organization_id" = NULL,
  "is_system_template" = true,
  "state" = EXCLUDED."state",
  "category" = EXCLUDED."category",
  "name" = EXCLUDED."name",
  "slug" = EXCLUDED."slug",
  "description" = EXCLUDED."description",
  "tags" = EXCLUDED."tags",
  "difficulty_level" = EXCLUDED."difficulty_level",
  "recommended_product_types" = EXCLUDED."recommended_product_types",
  "recommended_industries" = EXCLUDED."recommended_industries",
  "recommended_pairings" = EXCLUDED."recommended_pairings",
  "compatibility_metadata" = EXCLUDED."compatibility_metadata",
  "workflow_metadata" = EXCLUDED."workflow_metadata",
  "pricing_metadata" = EXCLUDED."pricing_metadata",
  "intent_metadata" = EXCLUDED."intent_metadata",
  "preview_config" = EXCLUDED."preview_config",
  "template_tree" = EXCLUDED."template_tree",
  "archived_at" = NULL,
  "updated_at" = now();
