import { expect, test, type APIRequestContext, type Page } from "@playwright/test";

type Fixture = Readonly<{ organizationA:string; organizationB:string; customerA:string; contactA:string; dimensionalProductA:string }>;
const login=async(api:APIRequestContext,actor:"staff-a"|"limited-a"|"staff-b")=>expect((await api.post("/_v2-browser-test/session",{data:{actor}})).status()).toBe(204);
const fixture=async(api:APIRequestContext):Promise<Fixture>=>{const response=await api.get("/_v2-browser-test/fixture");expect(response.ok()).toBeTruthy();return (await response.json()).data as Fixture;};
const csrf=async(api:APIRequestContext,org:string)=>{const response=await api.get(`/v2/organizations/${encodeURIComponent(org)}/ui-bootstrap`);expect(response.ok()).toBeTruthy();return (await response.json()).data.csrfToken as string;};
const proofUrl=(org:string,path:string)=>`/v2/organizations/${encodeURIComponent(org)}/proofing${path}`;
const openOrganization=async(page:Page,organizationId:string)=>{await page.goto("/");await page.getByLabel("Organization ID").fill(organizationId);await expect(page.getByLabel("Customer").first()).toBeEnabled();};
const createOrder=async(page:Page,f:Fixture)=>{
  await page.getByLabel("Customer").first().selectOption(f.customerA);await page.getByLabel("Contact").first().selectOption(f.contactA);await page.getByLabel("Product").first().selectOption(f.dimensionalProductA);
  await page.getByLabel("PO").fill("Proof browser PO");await page.getByLabel("Requested due date").fill("2026-12-31");await page.getByLabel("Width (in)").fill("24");await page.getByLabel("Height (in)").fill("18");await page.getByLabel("Quantity").first().fill("2");
  const created=page.waitForResponse((response)=>response.request().method()==="POST"&&response.url().endsWith(`/v2/organizations/${encodeURIComponent(f.organizationA)}/quotes`)&&response.status()===200);
  await page.getByRole("button",{name:"Create Quote"}).click();const quoteId=((await (await created).json()).data.quote.quote.quoteId) as string;
  await page.getByRole("button",{name:"Send Quote"}).click();await page.getByRole("button",{name:"Mark Quote Sent"}).click();await page.getByRole("button",{name:"Accept Quote & Create Order"}).click();
  const accepted=page.waitForResponse((response)=>response.request().method()==="POST"&&response.url().endsWith(`/quotes/${quoteId}/accept`)&&response.status()===200);
  await page.getByRole("button",{name:"Accept & Create Order"}).click();return (await (await accepted).json()).data.orderId as string;
};
const orderReadback=async(page:Page,orderId:string)=>{const response=await page.context().request.get(`/_v2-browser-test/order-readback/${encodeURIComponent(orderId)}`);expect(response.ok()).toBeTruthy();return (await response.json()).data as {lines:Array<{id:string}>;routes:unknown};};

test.describe.serial("M2.1.5 authenticated Proofing browser proof",()=>{
  test("real Artwork evidence issues, revises, versions, and approves without changing Routing",async({page,browser})=>{
    await login(page.context().request,"staff-a");const f=await fixture(page.context().request);await openOrganization(page,f.organizationA);const orderId=await createOrder(page,f);const before=await orderReadback(page,orderId);const orderLineId=before.lines[0]?.id;expect(orderLineId).toBeTruthy();
    const seeded=await page.context().request.post("/_v2-browser-test/seed-artwork",{data:{orderId,orderLineId}});expect(seeded.ok()).toBeTruthy();const assignmentId=((await seeded.json()).data.assignment.id) as string;
    const token=await csrf(page.context().request,f.organizationA);const headers={"x-v2-csrf-token":token};
    const startPayload={businessRequestId:`m215-start-${orderId}`,orderId,orderLineId};const start=await page.context().request.post(proofUrl(f.organizationA,"/works"),{headers,data:startPayload});expect(start.status()).toBe(200);const proofWorkId=((await start.json()).data.work.proofWorkId) as string;
    const versionOnePayload={businessRequestId:`m215-v1-${orderId}`,artworkAssignmentIds:[assignmentId]};const versionOne=await page.context().request.post(proofUrl(f.organizationA,`/works/${encodeURIComponent(proofWorkId)}/versions`),{headers,data:versionOnePayload});expect(versionOne.status()).toBe(200);const versionOneId=((await versionOne.json()).data.version.proofVersionId) as string;
    const issueOnePayload={businessRequestId:`m215-issue-v1-${orderId}`};expect((await page.context().request.post(proofUrl(f.organizationA,`/versions/${encodeURIComponent(versionOneId)}/issue`),{headers,data:issueOnePayload})).status()).toBe(200);
    const issued=await page.context().request.get(proofUrl(f.organizationA,`/works/${encodeURIComponent(proofWorkId)}`));expect(issued.ok()).toBeTruthy();expect((await issued.json()).data.versions[0].version.issuedAt).toBeTruthy();
    const revision=await page.context().request.post(proofUrl(f.organizationA,`/versions/${encodeURIComponent(versionOneId)}/respond`),{headers,data:{businessRequestId:`m215-revise-v1-${orderId}`,outcome:"revision_requested",comment:"Please adjust the supplied artwork."}});expect(revision.status()).toBe(200);
    const versionTwo=await page.context().request.post(proofUrl(f.organizationA,`/works/${encodeURIComponent(proofWorkId)}/versions`),{headers,data:{businessRequestId:`m215-v2-${orderId}`,artworkAssignmentIds:[assignmentId]}});expect(versionTwo.status()).toBe(200);const versionTwoId=((await versionTwo.json()).data.version.proofVersionId) as string;
    expect((await page.context().request.post(proofUrl(f.organizationA,`/versions/${encodeURIComponent(versionTwoId)}/issue`),{headers,data:{businessRequestId:`m215-issue-v2-${orderId}`}})).status()).toBe(200);
    const stale=await page.context().request.post(proofUrl(f.organizationA,`/versions/${encodeURIComponent(versionOneId)}/respond`),{headers,data:{businessRequestId:`m215-stale-v1-${orderId}`,outcome:"approved"}});expect(stale.status()).toBe(409);
    const approvalPayload={businessRequestId:`m215-approve-v2-${orderId}`,outcome:"approved",comment:"Approved for proofing."};const approved=await page.context().request.post(proofUrl(f.organizationA,`/versions/${encodeURIComponent(versionTwoId)}/respond`),{headers,data:approvalPayload});expect(approved.status()).toBe(200);const replay=await page.context().request.post(proofUrl(f.organizationA,`/versions/${encodeURIComponent(versionTwoId)}/respond`),{headers,data:approvalPayload});expect(replay.status()).toBe(200);
    const read=await page.context().request.get(proofUrl(f.organizationA,`/works/${encodeURIComponent(proofWorkId)}`));expect(read.ok()).toBeTruthy();const history=(await read.json()).data.versions as Array<{version:{proofVersionId:string;artwork:Array<{artworkAssignmentId:string}>};response?:{outcome:string;comment?:string}}>;expect(history).toHaveLength(2);expect(history[0]).toMatchObject({version:{proofVersionId:versionTwoId,artwork:[{artworkAssignmentId:assignmentId}]},response:{outcome:"approved"}});expect(history[1]).toMatchObject({version:{proofVersionId:versionOneId,artwork:[{artworkAssignmentId:assignmentId}]},response:{outcome:"revision_requested",comment:"Please adjust the supplied artwork."}});
    await page.getByRole("button",{name:"Proofing",exact:true}).click();await expect(page.getByRole("heading",{name:"Proof Queue"})).toBeVisible();await expect(page.getByText("Preview unavailable",{exact:true})).toBeVisible();await expect(page.getByText(/customer-art\.pdf/u).first()).toBeVisible();await expect(page.getByText("Approved",{exact:true}).first()).toBeVisible();await page.screenshot({path:"C:\\tmp\\m215-visual\\v2-proofing-1440x900.png",fullPage:true});
    const persisted=await page.context().request.get(`/_v2-browser-test/proof-readback/${encodeURIComponent(proofWorkId)}`);expect(persisted.ok()).toBeTruthy();const db=(await persisted.json()).data as {versions:Array<{sequence:number;issued_at:string}>;responses:Array<{outcome:string;staffActorVerified:boolean}>;audit:Array<{event_type:string;staffActorVerified:boolean}>;operations:Array<{business_request_id:string;status:string}>};expect(db.versions).toHaveLength(2);expect(db.responses).toEqual(expect.arrayContaining([expect.objectContaining({outcome:"approved",staffActorVerified:true}),expect.objectContaining({outcome:"revision_requested",staffActorVerified:true})]));expect(db.audit).toEqual(expect.arrayContaining([expect.objectContaining({event_type:"proof_issued",staffActorVerified:true}),expect.objectContaining({event_type:"proof_approved",staffActorVerified:true})]));expect(db.operations.filter((item)=>item.business_request_id===approvalPayload.businessRequestId)).toHaveLength(1);
    expect((await orderReadback(page,orderId)).routes).toEqual(before.routes);
    const limited=await browser.newContext({baseURL:"http://127.0.0.1:4174"});const foreign=await browser.newContext({baseURL:"http://127.0.0.1:4174"});try{await login(limited.request,"limited-a");const limitedToken=await csrf(limited.request,f.organizationA);expect((await limited.request.post(proofUrl(f.organizationA,`/versions/${encodeURIComponent(versionTwoId)}/respond`),{headers:{"x-v2-csrf-token":limitedToken},data:{businessRequestId:`m215-denied-${orderId}`,outcome:"approved"}})).status()).toBe(403);await login(foreign.request,"staff-b");const foreignToken=await csrf(foreign.request,f.organizationB);expect((await foreign.request.get(proofUrl(f.organizationB,`/works/${encodeURIComponent(proofWorkId)}`),{headers:{"x-v2-csrf-token":foreignToken}})).status()).toBe(404);}finally{await limited.close();await foreign.close();}
    const unchanged=await page.context().request.get(proofUrl(f.organizationA,`/works/${encodeURIComponent(proofWorkId)}`));expect((await unchanged.json()).data.versions).toHaveLength(2);
  });
});
