import { expect, test, type APIRequestContext, type Page } from "@playwright/test";

type Fixture=Readonly<{organizationA:string;organizationB:string;customerA:string;contactA:string;dimensionalProductA:string}>;
const login=async(api:APIRequestContext,actor:"staff-a"|"limited-a"|"staff-b")=>expect((await api.post("/_v2-browser-test/session",{data:{actor}})).status()).toBe(204);
const fixture=async(api:APIRequestContext):Promise<Fixture>=>{const response=await api.get("/_v2-browser-test/fixture");expect(response.ok()).toBeTruthy();return (await response.json()).data as Fixture;};
const csrf=async(api:APIRequestContext,org:string)=>{const response=await api.get(`/v2/organizations/${encodeURIComponent(org)}/ui-bootstrap`);expect(response.ok()).toBeTruthy();return (await response.json()).data.csrfToken as string;};
const prepressUrl=(org:string,path:string)=>`/v2/organizations/${encodeURIComponent(org)}/prepress${path}`;
const openOrganization=async(page:Page,organizationId:string)=>{await page.goto("/");await page.getByLabel("Organization ID").fill(organizationId);await expect(page.getByLabel("Customer").first()).toBeEnabled();};
const createOrder=async(page:Page,f:Fixture)=>{await page.getByLabel("Customer").first().selectOption(f.customerA);await page.getByLabel("Contact").first().selectOption(f.contactA);await page.getByLabel("Product").first().selectOption(f.dimensionalProductA);await page.getByLabel("PO").fill("Prepress browser PO");await page.getByLabel("Requested due date").fill("2026-12-31");await page.getByLabel("Width (in)").fill("24");await page.getByLabel("Height (in)").fill("18");await page.getByLabel("Quantity").first().fill("2");const created=page.waitForResponse((response)=>response.request().method()==="POST"&&response.url().endsWith(`/v2/organizations/${encodeURIComponent(f.organizationA)}/quotes`)&&response.status()===200);await page.getByRole("button",{name:"Create Quote"}).click();const quoteId=((await (await created).json()).data.quote.quote.quoteId) as string;await page.getByRole("button",{name:"Send Quote"}).click();await page.getByRole("button",{name:"Mark Quote Sent"}).click();await page.getByRole("button",{name:"Accept Quote & Create Order"}).click();const accepted=page.waitForResponse((response)=>response.request().method()==="POST"&&response.url().endsWith(`/quotes/${quoteId}/accept`)&&response.status()===200);await page.getByRole("button",{name:"Accept & Create Order"}).click();return (await (await accepted).json()).data.orderId as string;};
const orderReadback=async(page:Page,orderId:string)=>{const response=await page.context().request.get(`/_v2-browser-test/order-readback/${encodeURIComponent(orderId)}`);expect(response.ok()).toBeTruthy();return (await response.json()).data as {lines:Array<{id:string}>;routes:unknown};};

test.describe.serial("M2.2.5 authenticated Prepress browser proof",()=>{
  test("real frozen requirements, Artwork coverage, and unit start/complete remain independent",async({page,browser})=>{
    await login(page.context().request,"staff-a");const f=await fixture(page.context().request);await openOrganization(page,f.organizationA);const orderId=await createOrder(page,f);const before=await orderReadback(page,orderId);const orderLineId=before.lines[0]!.id;
    const customer=await page.context().request.post("/_v2-browser-test/seed-artwork",{data:{orderId,orderLineId}});expect(customer.ok()).toBeTruthy();const token=await csrf(page.context().request,f.organizationA);const headers={"x-v2-csrf-token":token};
    const missing=await page.context().request.get(prepressUrl(f.organizationA,`/lines/${encodeURIComponent(orderLineId)}/coverage`));expect(missing.ok()).toBeTruthy();expect((await missing.json()).data).toMatchObject({state:"configured",productionArtworkComplete:false});
    const rejected=await page.context().request.post(prepressUrl(f.organizationA,"/units"),{headers,data:{businessRequestId:`m225-customer-${orderId}`,artworkAssignmentId:((await customer.json()).data.assignment.id)}});expect(rejected.status()).toBe(409);
    const front=await page.context().request.post("/_v2-browser-test/seed-artwork",{data:{orderId,orderLineId,purpose:"production",side:"front"}});const back=await page.context().request.post("/_v2-browser-test/seed-artwork",{data:{orderId,orderLineId,purpose:"production",side:"back"}});expect(front.ok()).toBeTruthy();expect(back.ok()).toBeTruthy();
    expect((await page.context().request.post("/_v2-browser-test/enter-prepress",{data:{orderId,orderLineId}})).status()).toBe(204);
    const routingBeforePrepressOps=(await orderReadback(page,orderId)).routes;
    await page.getByRole("button",{name:"Prepress",exact:true}).click();await expect(page.getByRole("heading",{name:"Prepress Queue"})).toBeVisible();await expect(page.getByText("Production Artwork covered",{exact:true})).toBeVisible();await expect(page.getByText("Preview unavailable",{exact:true})).toBeVisible();await page.screenshot({path:"C:\\tmp\\m225-visual\\v2-prepress-before-1440x900.png",fullPage:true});
    await page.getByRole("button",{name:"Start Prepress",exact:true}).click();await expect(page.getByRole("button",{name:"Complete Prepress",exact:true})).toBeVisible();await page.getByRole("button",{name:"Complete Prepress",exact:true}).click();await expect(page.getByText("Prepress Complete",{exact:true}).first()).toBeVisible();await expect(page.getByText(/Front · Ready for Prepress/u).first()).toBeVisible();
    await page.locator(".v2-prepress-production").getByRole("button",{name:/Front.*Ready for Prepress/u}).click();await page.getByRole("button",{name:"Start Prepress",exact:true}).click();await page.getByRole("button",{name:"Complete Prepress",exact:true}).click();await expect(page.getByText("All required Prepress complete",{exact:true})).toBeVisible();await page.screenshot({path:"C:\\tmp\\m225-visual\\v2-prepress-complete-1440x900.png",fullPage:true});
    const coverage=await page.context().request.get(prepressUrl(f.organizationA,`/lines/${encodeURIComponent(orderLineId)}/coverage`));expect((await coverage.json()).data).toMatchObject({productionArtworkComplete:true,allRequiredPrepressUnitsComplete:true});
    const replay=await page.context().request.post(prepressUrl(f.organizationA,"/units"),{headers,data:{businessRequestId:`m225-replay-${orderId}`,artworkAssignmentId:((await front.json()).data.assignment.id)}});expect(replay.status()).toBe(200);const replayAgain=await page.context().request.post(prepressUrl(f.organizationA,"/units"),{headers,data:{businessRequestId:`m225-replay-${orderId}`,artworkAssignmentId:((await front.json()).data.assignment.id)}});expect(replayAgain.status()).toBe(200);expect((await replay.json()).data.unit.prepressUnitId).toBe((await replayAgain.json()).data.unit.prepressUnitId);expect((await orderReadback(page,orderId)).routes).toEqual(routingBeforePrepressOps);
    const limited=await browser.newContext({baseURL:"http://127.0.0.1:4174"});const foreign=await browser.newContext({baseURL:"http://127.0.0.1:4174"});try{await login(limited.request,"limited-a");const limitedToken=await csrf(limited.request,f.organizationA);expect((await limited.request.post(prepressUrl(f.organizationA,"/units"),{headers:{"x-v2-csrf-token":limitedToken},data:{businessRequestId:`m225-denied-${orderId}`,artworkAssignmentId:((await front.json()).data.assignment.id)}})).status()).toBe(403);await login(foreign.request,"staff-b");expect((await foreign.request.get(prepressUrl(f.organizationB,`/lines/${encodeURIComponent(orderLineId)}/coverage`))).status()).toBe(404);}finally{await limited.close();await foreign.close();}
  });
});
