import { expect, test, type APIRequestContext, type Page } from "@playwright/test";

type Fixture=Readonly<{organizationA:string;organizationB:string;customerA:string;contactA:string;dimensionalProductA:string}>;
const login=async(api:APIRequestContext,actor:"staff-a"|"limited-a"|"staff-b")=>expect((await api.post("/_v2-browser-test/session",{data:{actor}})).status()).toBe(204);
const fixture=async(api:APIRequestContext)=>{const response=await api.get("/_v2-browser-test/fixture");expect(response.ok()).toBeTruthy();return (await response.json()).data as Fixture;};
const fulfillment=(org:string,path="")=>`/v2/organizations/${encodeURIComponent(org)}/fulfillment${path}`;
const bootstrap=async(api:APIRequestContext,org:string)=>{const response=await api.get(`/v2/organizations/${encodeURIComponent(org)}/ui-bootstrap`);expect(response.ok()).toBeTruthy();return (await response.json()).data as {csrfToken:string;capabilities:Record<string,boolean>};};
const createOrder=async(page:Page,f:Fixture)=>{await page.goto("/");await page.getByLabel("Organization ID").fill(f.organizationA);await expect(page.getByLabel("Customer").first()).toBeEnabled();await page.getByLabel("Customer").first().selectOption(f.customerA);await page.getByLabel("Contact").first().selectOption(f.contactA);await page.getByLabel("Product").first().selectOption(f.dimensionalProductA);await page.getByLabel("Width (in)").fill("24");await page.getByLabel("Height (in)").fill("18");await page.getByLabel("Quantity").first().fill("100");const created=page.waitForResponse((response)=>response.request().method()==="POST"&&response.url().endsWith(`/v2/organizations/${encodeURIComponent(f.organizationA)}/quotes`)&&response.status()===200);await page.getByRole("button",{name:"Create Quote"}).click();const quoteId=((await (await created).json()).data.quote.quote.quoteId) as string;await page.getByRole("button",{name:"Send Quote"}).click();await page.getByRole("button",{name:"Mark Quote Sent"}).click();await page.getByRole("button",{name:"Accept Quote & Create Order"}).click();const accepted=page.waitForResponse((response)=>response.request().method()==="POST"&&response.url().endsWith(`/quotes/${quoteId}/accept`)&&response.status()===200);await page.getByRole("button",{name:"Accept & Create Order"}).click();return (await (await accepted).json()).data.orderId as string;};

test("M6 clone-backed Fulfillment refuses handoffs before Production output",async({page,browser})=>{
 const api=page.context().request;await login(api,"staff-a");const f=await fixture(api);const orderId=await createOrder(page,f);
 const orderReadback=await api.get(`/_v2-browser-test/order-readback/${encodeURIComponent(orderId)}`);expect(orderReadback.ok()).toBeTruthy();const before=(await orderReadback.json()).data as {lines:Array<{id:string;quantity:number}>;routes:unknown;invoice:unknown};const lineId=before.lines[0]!.id;expect(before.lines[0]!.quantity).toBe(100);
 const access=await bootstrap(api,f.organizationA);expect(access.capabilities.fulfillmentView).toBe(true);expect(access.capabilities.fulfillmentPickup).toBe(true);expect(access.capabilities.fulfillmentShip).toBe(true);const headers={"x-v2-csrf-token":access.csrfToken};
 const initial=await api.get(fulfillment(f.organizationA,`/orders/${encodeURIComponent(orderId)}`));expect(initial.ok()).toBeTruthy();expect((await initial.json()).data.lines[0]).toMatchObject({orderLineId:lineId,orderedQuantity:100,completedProductionQuantity:0,availableFulfillmentQuantity:0,remainingFulfillmentQuantity:100,completedPickupQuantity:0,completedShipmentQuantity:0});
 await page.getByRole("button",{name:"Fulfillment",exact:true}).click();await expect(page.getByRole("heading",{name:"Fulfillment"})).toBeVisible();await page.locator(".v2-fulfillment-list button").first().click();await expect(page.getByRole("heading",{name:"Order fulfillment"})).toBeVisible();await expect(page.getByLabel("Fulfillment quantity")).toHaveValue("0");await expect(page.getByText("No physical quantity is currently available for handoff.")).toBeVisible();await expect(page.getByRole("button",{name:"Record partial",exact:true})).toHaveCount(0);await page.screenshot({path:"C:\\tmp\\m3-visual\\v2-fulfillment-awaiting-production-1440x900.png",fullPage:true});
 const blocked=await api.post(fulfillment(f.organizationA,`/orders/${encodeURIComponent(orderId)}/pickups`),{headers,data:{businessRequestId:`m6-no-output-${orderId}`,allocations:[{orderLineId:lineId,quantity:1}]}});expect(blocked.status()).toBe(409);
 expect((await api.post(fulfillment(f.organizationA,`/orders/${encodeURIComponent(orderId)}/pickups`),{data:{businessRequestId:`m6-no-csrf-${orderId}`,allocations:[{orderLineId:lineId,quantity:1}]}})).status()).toBe(403);
 const readback=await api.get(`/_v2-browser-test/fulfillment-readback/${encodeURIComponent(orderId)}`);expect(readback.ok()).toBeTruthy();const persisted=(await readback.json()).data;expect(persisted.handoffs).toHaveLength(0);expect(persisted.allocations).toHaveLength(0);expect(persisted.route).toEqual(before.routes);expect(persisted.invoice).toEqual(before.invoice);
 const limited=await browser.newContext({baseURL:"http://127.0.0.1:4174"});const foreign=await browser.newContext({baseURL:"http://127.0.0.1:4174"});try{await login(limited.request,"limited-a");const limitedAccess=await bootstrap(limited.request,f.organizationA);expect(limitedAccess.capabilities.fulfillmentView).toBe(false);expect((await limited.request.get(fulfillment(f.organizationA))).status()).toBe(403);expect((await limited.request.post(fulfillment(f.organizationA,`/orders/${encodeURIComponent(orderId)}/pickups`),{headers:{"x-v2-csrf-token":limitedAccess.csrfToken},data:{businessRequestId:`m6-limited-${orderId}`,allocations:[{orderLineId:lineId,quantity:1}]}})).status()).toBe(403);await login(foreign.request,"staff-b");expect((await foreign.request.get(fulfillment(f.organizationB,`/orders/${encodeURIComponent(orderId)}`))).status()).toBe(404);}finally{await limited.close();await foreign.close();}
});
