import { createHash } from "node:crypto";
import { and, desc, eq } from "drizzle-orm";
import { auditLogs, pbv2TreeVersions, products } from "@shared/schema";
import { requiresPublishedPbv2BeforeActivation } from "@shared/pbv2/productionLifecycle";

type ProductLifecycleRecord = Pick<typeof products.$inferSelect, "id" | "organizationId" | "name" | "isActive" | "pbv2ActiveTreeVersionId" | "updatedAt">;
type Store = { get(input: { organizationId: string; productId: string }): Promise<(ProductLifecycleRecord & { draftTreeVersionId: string | null }) | null>; update(input: { organizationId: string; productId: string; actorUserId: string; isActive: boolean; expectedUpdatedAt: Date; reference: string }): Promise<typeof products.$inferSelect | null> };
const store: Store = {
  async get(input) { const { db } = await import("../../db"); const [product] = await db.select({ id: products.id, organizationId: products.organizationId, name: products.name, isActive: products.isActive, pbv2ActiveTreeVersionId: products.pbv2ActiveTreeVersionId, updatedAt: products.updatedAt }).from(products).where(and(eq(products.organizationId, input.organizationId), eq(products.id, input.productId))).limit(1); if (!product) return null; const [draft] = await db.select({ id: pbv2TreeVersions.id }).from(pbv2TreeVersions).where(and(eq(pbv2TreeVersions.organizationId, input.organizationId), eq(pbv2TreeVersions.productId, input.productId), eq(pbv2TreeVersions.status, "DRAFT"))).orderBy(desc(pbv2TreeVersions.updatedAt)).limit(1); return { ...product, draftTreeVersionId: draft?.id ?? null }; },
  async update(input) { const { db } = await import("../../db"); return db.transaction(async (tx) => { const [updated] = await tx.update(products).set({ isActive: input.isActive, updatedAt: new Date() }).where(and(eq(products.organizationId, input.organizationId), eq(products.id, input.productId), eq(products.updatedAt, input.expectedUpdatedAt))).returning(); if (!updated) return null; await tx.insert(auditLogs).values({ organizationId: input.organizationId, userId: input.actorUserId, entityType: "product", entityId: input.productId, actionType: "product_lifecycle_updated", description: `Product ${input.isActive ? "activated" : "deactivated"}.`, oldValues: { isActive: !input.isActive }, newValues: { isActive: input.isActive, operationReference: "products.update_lifecycle.v1", reference: input.reference } }); return updated; }); },
};
export class CanonicalProductLifecycleError extends Error { constructor(readonly code: "ACTOR_REQUIRED" | "PRODUCT_NOT_FOUND" | "PRODUCT_LIFECYCLE_STALE" | "NO_PRODUCT_LIFECYCLE_CHANGES" | "PBV2_DRAFT_MUST_BE_PUBLISHED", message: string) { super(message); this.name = "CanonicalProductLifecycleError"; } }
const fingerprint = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
export class CanonicalProductLifecycleOperations {
  constructor(private readonly repository: Store = store) {}
  async propose(input: { organizationId: string; productId: string; isActive: boolean }) { const product = await this.repository.get(input); if (!product) throw new CanonicalProductLifecycleError("PRODUCT_NOT_FOUND", "The product is no longer available."); this.validate(product, input.isActive); if (product.isActive === input.isActive) throw new CanonicalProductLifecycleError("NO_PRODUCT_LIFECYCLE_CHANGES", "The product already has the requested lifecycle state."); const expectedUpdatedAt = new Date(product.updatedAt).toISOString(); return { productId: product.id, productName: product.name, isActive: input.isActive, expectedUpdatedAt, operationReference: "products.update_lifecycle.v1" as const, appliedChanges: [{ field: "isActive", before: product.isActive, after: input.isActive }], fingerprint: fingerprint({ organizationId: input.organizationId, productId: product.id, isActive: input.isActive, expectedUpdatedAt, activeTree: product.pbv2ActiveTreeVersionId, draftTree: product.draftTreeVersionId }) }; }
  async execute(input: { organizationId: string; actorUserId: string; productId: string; isActive: boolean; expectedUpdatedAt?: string; auditContext?: { source: "product_editor" | "assistant_go"; reference?: string } }) { if (!input.actorUserId) throw new CanonicalProductLifecycleError("ACTOR_REQUIRED", "An authenticated actor is required."); const product = await this.repository.get(input); if (!product) throw new CanonicalProductLifecycleError("PRODUCT_NOT_FOUND", "The product is no longer available."); const version = new Date(product.updatedAt).toISOString(); if (input.expectedUpdatedAt && input.expectedUpdatedAt !== version) throw new CanonicalProductLifecycleError("PRODUCT_LIFECYCLE_STALE", "The product changed before its lifecycle could be updated."); this.validate(product, input.isActive); if (product.isActive === input.isActive) return { product, appliedChanges: [], resultingVersion: version, operationReference: "products.update_lifecycle.v1" as const, auditReference: `lifecycle:no-change:${product.id}` }; const reference = input.auditContext?.reference ?? `${input.auditContext?.source ?? "application"}:${product.id}:${version}`; const updated = await this.repository.update({ organizationId: input.organizationId, actorUserId: input.actorUserId, productId: input.productId, isActive: input.isActive, expectedUpdatedAt: new Date(input.expectedUpdatedAt ?? version), reference }); if (!updated) throw new CanonicalProductLifecycleError("PRODUCT_LIFECYCLE_STALE", "The product changed before its lifecycle could be updated."); return { product: updated, appliedChanges: [{ field: "isActive", before: product.isActive, after: input.isActive }], resultingVersion: new Date(updated.updatedAt).toISOString(), operationReference: "products.update_lifecycle.v1" as const, auditReference: reference }; }
  private validate(product: ProductLifecycleRecord & { draftTreeVersionId: string | null }, requestedActive: boolean) { if (requiresPublishedPbv2BeforeActivation({ currentlyActive: product.isActive, requestedActive, activeTreeVersionId: product.pbv2ActiveTreeVersionId, draftTreeVersionId: product.draftTreeVersionId })) throw new CanonicalProductLifecycleError("PBV2_DRAFT_MUST_BE_PUBLISHED", "Publish the PBV2 draft before activating this product for Order Entry."); }
}
export const canonicalProductLifecycleOperations = new CanonicalProductLifecycleOperations();
export function takeCanonicalProductLifecycleChange(value: Record<string, unknown>): boolean | undefined { if (!Object.prototype.hasOwnProperty.call(value, "isActive")) return undefined; const next = value.isActive; delete value.isActive; return typeof next === "boolean" ? next : undefined; }
