import { createHash, randomUUID } from "node:crypto";
import { hostname } from "node:os";
import type { Pool } from "pg";
import { AuthorityPolicy } from "../../src/authorization/authorityPolicy.js";
import { principalSubject, staffActorId, type Principal } from "../../src/authorization/principals.js";
import { V2ApplicationError } from "../../src/errors/applicationError.js";
import { PostgresInvoiceEmailSender, type InvoiceEmailDeliveryPlan } from "./invoiceEmailSender.js";

export const invoiceEmailSelectionLimit = 100;
export const invoiceEmailScheduleSpacingMs = 60_000;
export type InvoiceEmailState = "queued" | "processing" | "retry_wait" | "sent" | "failed" | "ambiguous";
export type InvoiceEmailAdmission = Readonly<{ batchId:string; selected:number; queuedInvoices:number; queuedMessages:number; skipped:number; replayed:boolean }>;
type Candidate = Readonly<{ invoiceId:string; customerId:string|null }>;
type Job = Readonly<{ id:string; organizationId:string; recipient:string; attemptCount:number }>;
const hash=(value:string)=>`sha256:${createHash("sha256").update(value).digest("hex")}`;
const concise=(cause:unknown)=>String((cause as {message?:unknown})?.message ?? cause ?? "Invoice email delivery failed").replace(/\s+/gu," ").replace(/\0/gu,"").trim().slice(0,900)||"Invoice email delivery failed";

/** Durable pacing and recovery only. Customer recipients, Billing PDFs, MIME,
 * Gmail, and delivery audit are owned solely by PostgresInvoiceEmailSender. */
export class PostgresInvoiceEmailDeliveryQueue {
  constructor(private readonly pool:Pool,private readonly sender=new PostgresInvoiceEmailSender(pool),private readonly authority=new AuthorityPolicy()) {}

  async admit(input:Readonly<{organizationId:string;principal:Principal;businessRequestId:string;invoiceIds:readonly string[]}>):Promise<InvoiceEmailAdmission>{
    this.assertAuthorized(input.organizationId,input.principal);
    const ids=this.ids(input.invoiceIds);if(!input.businessRequestId.trim())throw new V2ApplicationError("VALIDATION_ERROR","A business request identity is required.");
    const client=await this.pool.connect();try{await client.query("BEGIN");
      const previous=await client.query<{id:string;requested_invoice_count:number;queued_invoice_count:number;queued_message_count:number;skipped_invoice_count:number}>("SELECT id,requested_invoice_count,queued_invoice_count,queued_message_count,skipped_invoice_count FROM v2_invoice_email_delivery_batches WHERE organization_id=$1 AND business_request_id=$2 FOR UPDATE",[input.organizationId,input.businessRequestId]);
      if(previous.rows[0]){await client.query("COMMIT");const row=previous.rows[0];return {batchId:row.id,selected:row.requested_invoice_count,queuedInvoices:row.queued_invoice_count,queuedMessages:row.queued_message_count,skipped:row.skipped_invoice_count,replayed:true};}
      const plans=await this.plans(client,input.organizationId,input.principal,ids),batchId=randomUUID();let queuedInvoices=0,queuedMessages=0;
      await client.query("INSERT INTO v2_invoice_email_delivery_batches(id,organization_id,business_request_id,requested_invoice_count,principal_kind,principal_subject,staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7)",[batchId,input.organizationId,input.businessRequestId,ids.length,input.principal.kind,principalSubject(input.principal),staffActorId(input.principal)??null]);
      for(const {recipient,invoiceIds:members} of plans){
        const slice=members,jobId=randomUUID(),key=hash(`${input.businessRequestId}:${recipient}:${slice.slice().sort().join(",")}`),availableAt=new Date(Date.now()+queuedMessages*invoiceEmailScheduleSpacingMs);
        await client.query("INSERT INTO v2_invoice_email_delivery_jobs(id,organization_id,batch_id,recipient_email,recipient_normalized,logical_send_key,available_at) VALUES($1,$2,$3,$4,$4,$5,$6)",[jobId,input.organizationId,batchId,recipient,key,availableAt]);
        for(const invoiceId of slice)await client.query("INSERT INTO v2_invoice_email_delivery_items(organization_id,job_id,invoice_id) VALUES($1,$2,$3)",[input.organizationId,jobId,invoiceId]);
        queuedMessages+=1;
      }
      queuedInvoices=new Set(plans.flatMap((plan)=>plan.invoiceIds)).size;
      const skipped=ids.length-queuedInvoices,result={batchId,selected:ids.length,queuedInvoices,queuedMessages,skipped,replayed:false};
      await client.query("UPDATE v2_invoice_email_delivery_batches SET queued_invoice_count=$3,queued_message_count=$4,skipped_invoice_count=$5,result_json=$6::jsonb WHERE organization_id=$1 AND id=$2",[input.organizationId,batchId,queuedInvoices,queuedMessages,skipped,JSON.stringify(result)]);
      await client.query("INSERT INTO v2_audit_events(organization_id,operation,event_type,resource_type,resource_id,principal_kind,principal_subject,staff_actor_user_id,changes) VALUES($1,'billing.invoice.email.admit.v1','invoice_email_batch_admitted','invoice_email_batch',$2,$3,$4,$5,$6::jsonb)",[input.organizationId,batchId,input.principal.kind,principalSubject(input.principal),staffActorId(input.principal)??null,JSON.stringify([{selected:ids.length,queuedInvoices,queuedMessages,skipped,spacingMs:invoiceEmailScheduleSpacingMs}])]);
      await client.query("COMMIT");return result;
    }catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
  }

  async preview(input:Readonly<{organizationId:string;principal:Principal;invoiceIds:readonly string[]}>):Promise<Readonly<{selected:number;deliverableInvoices:number;recipientCount:number;skipped:number}>>{
    this.assertAuthorized(input.organizationId,input.principal);const ids=this.ids(input.invoiceIds);const client=await this.pool.connect();try{const plans=await this.plans(client,input.organizationId,input.principal,ids),deliverable=new Set(plans.flatMap((plan)=>plan.invoiceIds));return {selected:ids.length,deliverableInvoices:deliverable.size,recipientCount:plans.length,skipped:ids.length-deliverable.size};}finally{client.release();}
  }

  /** An ambiguous provider outcome is never retried automatically. */
  async retry(input:Readonly<{organizationId:string;principal:Principal;jobId:string}>):Promise<Readonly<{state:"queued";attemptCount:number}>>{
    this.assertAuthorized(input.organizationId,input.principal);const result=await this.pool.query<{attempt_count:number}>("UPDATE v2_invoice_email_delivery_jobs SET state='queued',available_at=now(),claimed_by=NULL,lease_expires_at=NULL,completed_at=NULL,last_error=NULL,provider_attempted_at=NULL,updated_at=now() WHERE organization_id=$1 AND id=$2 AND state IN ('failed','ambiguous') RETURNING attempt_count",[input.organizationId,input.jobId]);if(!result.rows[0])throw new V2ApplicationError("CONFLICT","This Invoice email is not eligible for intentional retry.");return {state:"queued",attemptCount:result.rows[0].attempt_count};
  }

  private ids(values:readonly string[]):string[]{const ids=[...new Set(values.map((value)=>String(value).trim()).filter(Boolean))];if(!ids.length||ids.length>invoiceEmailSelectionLimit)throw new V2ApplicationError("VALIDATION_ERROR",`Select between 1 and ${invoiceEmailSelectionLimit} V2 Invoices.`);return ids;}
  private assertAuthorized(organizationId:string,principal:Principal){if(principal.kind!=="staff"&&principal.kind!=="delegated_ai")throw new V2ApplicationError("FORBIDDEN","Only an authorized Invoice operator may send customer email.");if(!this.authority.decide(principal,{capability:"invoice.send",resource:{organizationId}}).allowed)throw new V2ApplicationError("FORBIDDEN","The principal cannot send Invoice email.");}
  private async plans(client:Pick<Pool,"query">,organizationId:string,principal:Principal,ids:readonly string[]):Promise<readonly InvoiceEmailDeliveryPlan[]>{const candidates=await client.query<Candidate>("SELECT id AS \"invoiceId\",customer_id AS \"customerId\" FROM v2_billing_invoices WHERE organization_id=$1 AND id=ANY($2::varchar[]) AND invoice_state<>'void'",[organizationId,ids]);const allowed=candidates.rows.filter((row)=>this.authority.decide(principal,{capability:"invoice.send",resource:{organizationId,customerId:row.customerId}}).allowed).map((row)=>row.invoiceId);return this.sender.plan(organizationId,allowed);}

  async claim(workerId:string,leaseSeconds:number,spacingMs:number):Promise<Job|null>{
    const client=await this.pool.connect();try{await client.query("BEGIN");const result=await client.query<{id:string;organization_id:string;recipient_email:string;attempt_count:number}>(`
      WITH uncertain AS (UPDATE v2_invoice_email_delivery_jobs SET state='ambiguous',last_error=COALESCE(last_error,'Provider outcome is uncertain after an interrupted delivery attempt. Verify delivery before intentional retry.'),claimed_by=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now() WHERE state='processing' AND lease_expires_at<=now() AND provider_attempted_at IS NOT NULL),
      candidate AS (SELECT id,organization_id FROM v2_invoice_email_delivery_jobs WHERE (state IN ('queued','retry_wait') AND available_at<=now()) OR (state='processing' AND lease_expires_at<=now() AND provider_attempted_at IS NULL) ORDER BY available_at,created_at FOR UPDATE SKIP LOCKED LIMIT 1),
      pace AS (INSERT INTO v2_invoice_email_delivery_rate_limits(organization_id,next_available_at) SELECT organization_id,now()+($2::text||' milliseconds')::interval FROM candidate ON CONFLICT(organization_id) DO UPDATE SET next_available_at=now()+($2::text||' milliseconds')::interval WHERE v2_invoice_email_delivery_rate_limits.next_available_at<=now() RETURNING organization_id)
      UPDATE v2_invoice_email_delivery_jobs j SET state='processing',claimed_by=$1,lease_expires_at=now()+($3::text||' seconds')::interval,attempt_count=j.attempt_count+1,updated_at=now() FROM candidate,pace WHERE j.id=candidate.id AND j.organization_id=pace.organization_id RETURNING j.id,j.organization_id,j.recipient_email,j.attempt_count`,[workerId,Math.max(0,spacingMs),leaseSeconds]);await client.query("COMMIT");const row=result.rows[0];return row?{id:row.id,organizationId:row.organization_id,recipient:row.recipient_email,attemptCount:row.attempt_count}:null;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
  }

  async process(job:Job,workerId:string,maxAttempts:number):Promise<InvoiceEmailState>{let providerAttempted=false;try{const invoiceIds=await this.invoiceIds(job),providerMessageId=await this.sender.send({organizationId:job.organizationId,recipient:job.recipient,invoiceIds,beforeProviderAttempt:async()=>{await this.markProviderAttempt(job,workerId);providerAttempted=true;},audit:{jobId:job.id,operation:"billing.invoice.email.delivery.v1",principalKind:"service",principalSubject:"invoice-email-worker"}});await this.finish(job,workerId,"sent",undefined,providerMessageId);return "sent";}catch(error){const requested=providerAttempted?this.providerState(error):this.preProviderState(error),state=requested==="retry_wait"&&job.attemptCount>=maxAttempts?"failed":requested;await this.finish(job,workerId,state,concise(error));return state;}}
  private async invoiceIds(job:Job):Promise<readonly string[]>{return (await this.pool.query<{invoice_id:string}>("SELECT invoice_id FROM v2_invoice_email_delivery_items WHERE organization_id=$1 AND job_id=$2 ORDER BY created_at,invoice_id",[job.organizationId,job.id])).rows.map((row)=>row.invoice_id);}
  private async markProviderAttempt(job:Job,workerId:string):Promise<void>{const marked=await this.pool.query<{id:string}>("UPDATE v2_invoice_email_delivery_jobs SET provider_attempted_at=now(),updated_at=now() WHERE organization_id=$1 AND id=$2 AND state='processing' AND claimed_by=$3 AND provider_attempted_at IS NULL RETURNING id",[job.organizationId,job.id,workerId]);if(!marked.rows[0])throw new V2ApplicationError("CONFLICT","Invoice email delivery ownership changed before the provider attempt.");}
  private providerState(error:unknown):InvoiceEmailState{const status=Number((error as {code?:unknown;response?:{status?:unknown}})?.code??(error as {response?:{status?:unknown}})?.response?.status);if(Number.isFinite(status)){if(status===429||status>=500)return "retry_wait";if(status>=400&&status<500)return "failed";}return "ambiguous";}
  private preProviderState(error:unknown):InvoiceEmailState{return error instanceof V2ApplicationError&&error.code==="VALIDATION_ERROR"?"failed":"retry_wait";}
  private async finish(job:Job,workerId:string,state:InvoiceEmailState,error?:string,providerMessageId?:string):Promise<void>{const backoff=Math.min(30*60_000,15_000*2**Math.min(Math.max(0,job.attemptCount-1),7));await this.pool.query("UPDATE v2_invoice_email_delivery_jobs SET state=$3::varchar,last_error=$4,provider_message_id=COALESCE($5,provider_message_id),sent_at=CASE WHEN $3::varchar='sent' THEN now() ELSE sent_at END,completed_at=CASE WHEN $3::varchar IN ('sent','failed','ambiguous') THEN now() ELSE NULL END,available_at=CASE WHEN $3::varchar='retry_wait' THEN now()+($6::text||' milliseconds')::interval ELSE available_at END,claimed_by=NULL,lease_expires_at=NULL,updated_at=now() WHERE organization_id=$1 AND id=$2 AND state='processing' AND claimed_by=$7",[job.organizationId,job.id,state,error??null,providerMessageId??null,backoff,workerId]);}
}

export class V2InvoiceEmailDeliveryWorker { constructor(private readonly queue:PostgresInvoiceEmailDeliveryQueue,private readonly workerId=`v2-invoice-email:${process.env.RAILWAY_REPLICA_ID||hostname()}:${process.pid}:${randomUUID().slice(0,8)}`) {} async run(input:Readonly<{limit:number;leaseSeconds:number;spacingMs:number;maxAttempts:number}>):Promise<Readonly<Record<InvoiceEmailState|"claimed",number>>>{const result:Record<InvoiceEmailState|"claimed",number>={claimed:0,queued:0,processing:0,retry_wait:0,sent:0,failed:0,ambiguous:0};for(let i=0;i<Math.max(1,input.limit);i+=1){const job=await this.queue.claim(this.workerId,input.leaseSeconds,input.spacingMs);if(!job)break;result.claimed+=1;result[await this.queue.process(job,this.workerId,input.maxAttempts)]+=1;}return result;} }
const number=(value:string|undefined,fallback:number,min:number,max:number)=>{const parsed=Number(value);return Number.isFinite(parsed)?Math.min(max,Math.max(min,Math.floor(parsed))):fallback;};
export const startV2InvoiceEmailDeliveryWorker=(pool:Pool,log:(event:string,data?:Record<string,unknown>)=>void):(()=>void)|null=>{if(process.env.V2_INVOICE_EMAIL_DELIVERY_ENABLED?.toLowerCase()==="false"){log("v2.invoice_email.worker.disabled",{reason:"disabled_by_configuration"});return null;}const worker=new V2InvoiceEmailDeliveryWorker(new PostgresInvoiceEmailDeliveryQueue(pool)),interval=number(process.env.V2_INVOICE_EMAIL_DELIVERY_INTERVAL_MS,20_000,1_000,300_000),limit=number(process.env.V2_INVOICE_EMAIL_DELIVERY_CONCURRENCY,1,1,4),leaseSeconds=number(process.env.V2_INVOICE_EMAIL_DELIVERY_LEASE_SECONDS,300,30,3600),spacingMs=number(process.env.V2_INVOICE_EMAIL_DELIVERY_MIN_SPACING_MS,invoiceEmailScheduleSpacingMs,0,60_000),maxAttempts=number(process.env.V2_INVOICE_EMAIL_DELIVERY_MAX_ATTEMPTS,5,1,20);let running=false;const tick=async()=>{if(running)return;running=true;try{const result=await worker.run({limit,leaseSeconds,spacingMs,maxAttempts});if(result.claimed)log("v2.invoice_email.worker.run",result);}catch(error){log("v2.invoice_email.worker.error",{message:concise(error)});}finally{running=false;}};const timer=setInterval(()=>void tick(),interval);timer.unref();void tick();log("v2.invoice_email.worker.started",{interval,limit,leaseSeconds,spacingMs,maxAttempts});return()=>clearInterval(timer);};
