import { createHash, randomBytes, randomUUID } from "node:crypto";
import { hostname } from "node:os";
import type { Pool } from "pg";
import { google } from "googleapis";
import { V2ApplicationError } from "../../src/errors/applicationError.js";
import { PostgresEmailIntegrationService, type ReadyGmailIntegration } from "./postgresEmailIntegration.js";

type State = "queued"|"processing"|"retry_wait"|"sent"|"failed"|"ambiguous";
type Job = Readonly<{id:string;organizationId:string;proofVersionId:string;recipient:string;portalAccessId:string;attemptCount:number}>;
type Context = Readonly<{orderNumber:string;lineDescription:string;sequence:number;portalStatus:string}>;
const concise=(cause:unknown)=>String((cause as {message?:unknown})?.message??cause??"Proof notification failed").replace(/\s+/gu," ").replace(/\0/gu,"").trim().slice(0,900)||"Proof notification failed";
const html=(value:string)=>value.replace(/[&<>"']/gu,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[character]??character));
const origin=()=>((process.env.APP_PUBLIC_WEB_ORIGIN??process.env.APP_URL??"").trim().replace(/\/$/u,""));

/** Durable proof notification delivery. Issuance is canonical proof evidence;
 * this queue only owns the recoverable customer-notification attempt. */
export class PostgresProofEmailDeliveryQueue {
  constructor(private readonly pool:Pool,private readonly email=new PostgresEmailIntegrationService(pool)){}
  async claim(workerId:string,leaseSeconds:number):Promise<Job|null>{
    const result=await this.pool.query<{id:string;organization_id:string;proof_version_id:string;recipient_email:string;portal_access_id:string;attempt_count:number}>(`WITH uncertain AS (
      UPDATE v2_proof_delivery_jobs SET state='ambiguous',last_error=COALESCE(last_error,'Provider outcome is uncertain after an interrupted attempt. Verify delivery before intentional retry.'),claimed_by=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now()
      WHERE state='processing' AND lease_expires_at<=now() AND provider_attempted_at IS NOT NULL
    ), candidate AS (
      SELECT id FROM v2_proof_delivery_jobs WHERE (state IN ('queued','retry_wait') AND available_at<=now()) OR (state='processing' AND lease_expires_at<=now() AND provider_attempted_at IS NULL)
      ORDER BY available_at,created_at FOR UPDATE SKIP LOCKED LIMIT 1
    ) UPDATE v2_proof_delivery_jobs j SET state='processing',claimed_by=$1,lease_expires_at=now()+($2::text||' seconds')::interval,attempt_count=j.attempt_count+1,updated_at=now()
      FROM candidate WHERE j.id=candidate.id RETURNING j.id,j.organization_id,j.proof_version_id,j.recipient_email,j.portal_access_id,j.attempt_count`,[workerId,leaseSeconds]);
    const row=result.rows[0];return row?{id:row.id,organizationId:row.organization_id,proofVersionId:row.proof_version_id,recipient:row.recipient_email,portalAccessId:row.portal_access_id,attemptCount:row.attempt_count}:null;
  }
  async process(job:Job,workerId:string,maxAttempts:number):Promise<State>{let providerAttempted=false;try{
    const integration=await this.email.requireReady(job.organizationId);const context=await this.context(job);const url=await this.reviewUrl(job,context);
    const marked=await this.pool.query("UPDATE v2_proof_delivery_jobs SET provider_attempted_at=now(),updated_at=now() WHERE organization_id=$1 AND id=$2 AND state='processing' AND claimed_by=$3 AND provider_attempted_at IS NULL RETURNING id",[job.organizationId,job.id,workerId]);if(!marked.rows[0])throw new V2ApplicationError("CONFLICT","Proof delivery ownership changed before the provider attempt.");providerAttempted=true;
    const providerMessageId=await this.deliver(integration,job.recipient,context,url);await this.finish(job,workerId,"sent",undefined,providerMessageId);await this.pool.query("INSERT INTO v2_audit_events(organization_id,operation,event_type,resource_type,resource_id,principal_kind,principal_subject,changes) VALUES($1,'proof.delivery.worker.v1','proof_notification_sent','proof_version',$2,'service','proof-email-worker',$3::jsonb)",[job.organizationId,job.proofVersionId,JSON.stringify([{jobId:job.id,recipient:job.recipient,providerMessageId}])]);return "sent";
  }catch(error){const requested=providerAttempted?this.providerState(error):error instanceof V2ApplicationError&&error.code==="VALIDATION_ERROR"?"failed":"retry_wait";const state=requested==="retry_wait"&&job.attemptCount>=maxAttempts?"failed":requested;await this.finish(job,workerId,state,concise(error));return state;}}
  private async context(job:Job):Promise<Context>{const result=await this.pool.query<{display_number:string;description:string;sequence:number;status:string}>(`SELECT d.display_number,l.description,v.sequence,a.status::text FROM v2_proof_delivery_jobs j JOIN v2_proof_versions v ON v.organization_id=j.organization_id AND v.id=j.proof_version_id JOIN v2_proof_works w ON w.organization_id=v.organization_id AND w.id=v.proof_work_id JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id JOIN v2_sales_document_lines l ON l.organization_id=w.organization_id AND l.id=w.order_line_id JOIN customer_portal_access a ON a.organization_id=j.organization_id AND a.id=j.portal_access_id WHERE j.organization_id=$1 AND j.id=$2`,[job.organizationId,job.id]);const row=result.rows[0];if(!row)throw new V2ApplicationError("VALIDATION_ERROR","The issued Proof no longer has deliverable customer context.");if(row.status!=="ACTIVE"&&row.status!=="PENDING_INVITE")throw new V2ApplicationError("VALIDATION_ERROR","Customer Portal access is suspended or disabled.");return{orderNumber:row.display_number,lineDescription:row.description,sequence:row.sequence,portalStatus:row.status};}
  private async reviewUrl(job:Job,context:Context):Promise<string>{const base=origin();if(!base)throw new V2ApplicationError("RETRYABLE_FAILURE","The customer portal public origin is unavailable.");const returnTo=`/portal/proofs/${encodeURIComponent(job.proofVersionId)}`;if(context.portalStatus==="ACTIVE")return`${base}${returnTo}`;
    const token=randomBytes(32).toString("hex"),tokenHash=createHash("sha256").update(token).digest("hex");const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("UPDATE customer_portal_invite_tokens SET revoked_at=now() WHERE organization_id=$1 AND access_id=$2 AND used_at IS NULL AND revoked_at IS NULL",[job.organizationId,job.portalAccessId]);await client.query("INSERT INTO customer_portal_invite_tokens(organization_id,access_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '72 hours')",[job.organizationId,job.portalAccessId,tokenHash]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}return`${base}/portal/setup?token=${encodeURIComponent(token)}&returnTo=${encodeURIComponent(returnTo)}`;
  }
  private async deliver(integration:ReadyGmailIntegration,recipient:string,context:Context,url:string):Promise<string>{const clientId=process.env.GOOGLE_CLIENT_ID,clientSecret=process.env.GOOGLE_CLIENT_SECRET;if(!clientId||!clientSecret)throw new V2ApplicationError("RETRYABLE_FAILURE","The platform Gmail delivery connection is unavailable.");const oauth=new google.auth.OAuth2(clientId,clientSecret);oauth.setCredentials({refresh_token:integration.refreshToken});const raw=Buffer.from([`From: \"${integration.displayName.replaceAll('"','')}\" <${integration.sendingAddress}>`,`To: ${recipient}`,`Subject: Proof v${context.sequence} for Order ${context.orderNumber}`,"MIME-Version: 1.0","Content-Type: text/html; charset=utf-8","",`<p>A proof for <strong>Order ${html(context.orderNumber)}</strong> is ready for review.</p><p>${html(context.lineDescription)}</p><p><a href=\"${html(url)}\">Review Proof</a></p><p>Sign in to the secure customer portal to approve it or request changes.</p>`].join("\r\n")).toString("base64url");const response=await google.gmail({version:"v1",auth:oauth}).users.messages.send({userId:"me",requestBody:{raw}},{timeout:30_000});if(!response.data.id)throw new Error("Provider did not return a message identity.");return response.data.id;}
  private providerState(error:unknown):State{const status=Number((error as {code?:unknown;response?:{status?:unknown}})?.code??(error as {response?:{status?:unknown}})?.response?.status);if(Number.isFinite(status)){if(status===429)return"retry_wait";if(status>=400&&status<500)return"failed";if(status>=500)return"ambiguous";}return"ambiguous";}
  private async finish(job:Job,workerId:string,state:State,error?:string,providerMessageId?:string){const backoff=Math.min(30*60_000,15_000*2**Math.min(Math.max(0,job.attemptCount-1),7));await this.pool.query(`WITH finished AS (UPDATE v2_proof_delivery_jobs SET state=$3,last_error=$4,provider_message_id=COALESCE($5,provider_message_id),delivered_at=CASE WHEN $3='sent' THEN now() ELSE delivered_at END,completed_at=CASE WHEN $3 IN ('sent','failed','ambiguous') THEN now() ELSE NULL END,available_at=CASE WHEN $3='retry_wait' THEN now()+($6::text||' milliseconds')::interval ELSE available_at END,claimed_by=NULL,lease_expires_at=NULL,updated_at=now() WHERE organization_id=$1 AND id=$2 AND state='processing' AND claimed_by=$7 RETURNING organization_id,portal_access_id,state), access_mark AS (UPDATE customer_portal_access a SET invite_sent_at=COALESCE(a.invite_sent_at,now()),updated_at=now() FROM finished f WHERE f.state='sent' AND a.organization_id=f.organization_id AND a.id=f.portal_access_id AND a.status='PENDING_INVITE'), token_mark AS (UPDATE customer_portal_invite_tokens t SET sent_at=COALESCE(t.sent_at,now()) FROM finished f WHERE f.state='sent' AND t.organization_id=f.organization_id AND t.access_id=f.portal_access_id AND t.used_at IS NULL AND t.revoked_at IS NULL) SELECT count(*) FROM finished`,[job.organizationId,job.id,state,error??null,providerMessageId??null,backoff,workerId]);}
}

export class V2ProofEmailDeliveryWorker{constructor(private readonly queue:PostgresProofEmailDeliveryQueue,private readonly workerId=`v2-proof-email:${process.env.RAILWAY_REPLICA_ID||hostname()}:${process.pid}:${randomUUID().slice(0,8)}`){}async run(limit:number,leaseSeconds:number,maxAttempts:number){const result:Record<string,number>={claimed:0};for(let index=0;index<limit;index+=1){const job=await this.queue.claim(this.workerId,leaseSeconds);if(!job)break;result.claimed+=1;const state=await this.queue.process(job,this.workerId,maxAttempts);result[state]=(result[state]??0)+1;}return result;}}
const number=(value:string|undefined,fallback:number,min:number,max:number)=>{const parsed=Number(value);return Number.isFinite(parsed)?Math.min(max,Math.max(min,Math.floor(parsed))):fallback;};
export const startV2ProofEmailDeliveryWorker=(pool:Pool,log:(event:string,data?:Record<string,unknown>)=>void):(()=>void)|null=>{if(process.env.V2_PROOF_EMAIL_DELIVERY_ENABLED?.toLowerCase()==="false"){log("v2.proof_email.worker.disabled",{reason:"disabled_by_configuration"});return null;}const worker=new V2ProofEmailDeliveryWorker(new PostgresProofEmailDeliveryQueue(pool));const interval=number(process.env.V2_PROOF_EMAIL_DELIVERY_INTERVAL_MS,20_000,1_000,300_000),limit=number(process.env.V2_PROOF_EMAIL_DELIVERY_CONCURRENCY,1,1,4),lease=number(process.env.V2_PROOF_EMAIL_DELIVERY_LEASE_SECONDS,300,30,3600),attempts=number(process.env.V2_PROOF_EMAIL_DELIVERY_MAX_ATTEMPTS,5,1,20);let running=false;const tick=async()=>{if(running)return;running=true;try{const result=await worker.run(limit,lease,attempts);if(result.claimed)log("v2.proof_email.worker.run",result);}catch(error){log("v2.proof_email.worker.error",{message:concise(error)});}finally{running=false;}};const timer=setInterval(()=>void tick(),interval);timer.unref();void tick();log("v2.proof_email.worker.started",{interval,limit,lease,attempts});return()=>clearInterval(timer);};
