import type {
  PortalAccount,
  PortalInvoice,
  PortalOrder,
  PortalProduct,
  PortalProof,
  PortalQuote,
} from "./types";

/** Mock fixtures — replaced by PrintersHero V2 API responses at port time. */

export const account: PortalAccount = {
  company: "Blue Ridge Outfitters",
  contactName: "Marta Reyes",
  email: "marta@blueridgeoutfitters.com",
  phone: "(828) 555-0147",
  accountRep: "Dale Hensley",
  terms: "Net 30",
  addresses: [
    { label: "Billing", lines: ["Blue Ridge Outfitters", "412 Depot St", "Asheville, NC 28801"] },
    { label: "Shipping", lines: ["Blue Ridge Outfitters — Warehouse", "88 Riverside Dr, Bay 4", "Asheville, NC 28801"] },
  ],
};

export const products: PortalProduct[] = [
  {
    id: "banner-13oz",
    name: "13oz Vinyl Banner",
    category: "Banners",
    blurb: "Scrim vinyl, full-color print, hemmed and grommeted for outdoor use.",
    imageHue: 28,
    startingAt: "$3.75 / sq ft",
    negotiated: true,
    artworkRequired: true,
    maxArtworkFiles: 3,
    fields: [
      { id: "size", kind: "dimensions", label: "Finished size", required: true, unit: "in" },
      { id: "qty", kind: "quantity", label: "Quantity", required: true, defaultValue: "2" },
      {
        id: "sides",
        kind: "select",
        label: "Print sides",
        required: true,
        defaultValue: "single",
        choices: [
          { id: "single", label: "Single sided" },
          { id: "double", label: "Double sided", hint: "Blockout liner added automatically" },
        ],
      },
      {
        id: "hem",
        kind: "select",
        label: "Hem",
        defaultValue: "all",
        choices: [
          { id: "all", label: "All four sides" },
          { id: "topbottom", label: "Top & bottom only" },
          { id: "none", label: "No hem" },
        ],
      },
      {
        id: "grommets",
        kind: "select",
        label: "Grommets",
        defaultValue: "24",
        choices: [
          { id: "24", label: "Every 24 in" },
          { id: "corners", label: "Corners only" },
          { id: "none", label: "None" },
        ],
      },
      {
        id: "polepocket",
        kind: "select",
        label: "Pole pockets",
        help: "Add sewn pockets for a pole or rod.",
        defaultValue: "none",
        choices: [
          { id: "none", label: "None" },
          { id: "topbottom3", label: "Top & bottom — 3 in" },
          { id: "top4", label: "Top only — 4 in" },
        ],
      },
    ],
  },
  {
    id: "coroplast-4mm",
    name: "4mm Coroplast Sign",
    category: "Rigid Signs",
    blurb: "Lightweight corrugated plastic yard and site signage.",
    imageHue: 145,
    startingAt: "$14.00 each",
    negotiated: true,
    artworkRequired: true,
    maxArtworkFiles: 2,
    fields: [
      { id: "size", kind: "dimensions", label: "Finished size", required: true, unit: "in" },
      { id: "qty", kind: "quantity", label: "Quantity", required: true, defaultValue: "25" },
      {
        id: "sides",
        kind: "select",
        label: "Print sides",
        required: true,
        defaultValue: "single",
        choices: [
          { id: "single", label: "Single sided" },
          { id: "double", label: "Double sided" },
        ],
      },
      {
        id: "flutes",
        kind: "select",
        label: "Flute direction",
        defaultValue: "vertical",
        choices: [
          { id: "vertical", label: "Vertical" },
          { id: "horizontal", label: "Horizontal" },
        ],
      },
      {
        id: "stakes",
        kind: "select",
        label: "H-stakes",
        defaultValue: "one",
        choices: [
          { id: "one", label: "One per sign" },
          { id: "none", label: "No stakes" },
        ],
      },
    ],
  },
  {
    id: "adhesive-vinyl",
    name: "Adhesive Vinyl",
    category: "Vinyl & Decals",
    blurb: "Calendared or cast print media for windows, walls and vehicles.",
    imageHue: 210,
    startingAt: "$6.20 / sq ft",
    artworkRequired: true,
    maxArtworkFiles: 4,
    fields: [
      { id: "size", kind: "dimensions", label: "Finished size", required: true, unit: "in" },
      { id: "qty", kind: "quantity", label: "Quantity", required: true, defaultValue: "4" },
      {
        id: "media",
        kind: "select",
        label: "Media",
        required: true,
        defaultValue: "calendared",
        choices: [
          { id: "calendared", label: "Calendared — flat surfaces" },
          { id: "cast", label: "Cast — curves & vehicles" },
          { id: "perf", label: "Perforated window film" },
        ],
      },
      {
        id: "laminate",
        kind: "select",
        label: "Laminate",
        defaultValue: "gloss",
        choices: [
          { id: "gloss", label: "Gloss" },
          { id: "matte", label: "Matte" },
          { id: "none", label: "None" },
        ],
      },
    ],
  },
  {
    id: "contour-stickers",
    name: "Contour Cut Stickers",
    category: "Vinyl & Decals",
    blurb: "Die-cut to your shape, kiss cut on sheets or supplied singly.",
    imageHue: 320,
    startingAt: "$0.68 each",
    artworkRequired: true,
    maxArtworkFiles: 4,
    fields: [
      { id: "size", kind: "dimensions", label: "Sticker size", required: true, unit: "in" },
      { id: "qty", kind: "quantity", label: "Quantity", required: true, defaultValue: "250" },
      {
        id: "cut",
        kind: "select",
        label: "Cut style",
        required: true,
        defaultValue: "kiss",
        choices: [
          { id: "kiss", label: "Kiss cut on sheets" },
          { id: "die", label: "Die cut singles" },
        ],
      },
      {
        id: "laminate",
        kind: "select",
        label: "Laminate",
        defaultValue: "matte",
        choices: [
          { id: "matte", label: "Matte" },
          { id: "gloss", label: "Gloss" },
          { id: "none", label: "None" },
        ],
      },
    ],
  },
  {
    id: "acrylic-sign",
    name: "Acrylic Sign",
    category: "Rigid Signs",
    blurb: "Clear or white acrylic panels with polished edges and mounting hardware.",
    imageHue: 190,
    startingAt: "$92.00 each",
    artworkRequired: true,
    maxArtworkFiles: 2,
    fields: [
      { id: "size", kind: "dimensions", label: "Panel size", required: true, unit: "in" },
      { id: "qty", kind: "quantity", label: "Quantity", required: true, defaultValue: "1" },
      {
        id: "thickness",
        kind: "select",
        label: "Thickness",
        required: true,
        defaultValue: "quarter",
        choices: [
          { id: "eighth", label: "1/8 in" },
          { id: "quarter", label: "1/4 in" },
        ],
      },
      {
        id: "facing",
        kind: "select",
        label: "Print surface",
        defaultValue: "second",
        choices: [
          { id: "second", label: "Second surface — printed behind" },
          { id: "first", label: "First surface" },
        ],
      },
      {
        id: "mount",
        kind: "select",
        label: "Mounting",
        defaultValue: "standoffs",
        choices: [
          { id: "standoffs", label: "Standoffs (4)" },
          { id: "cleat", label: "French cleat" },
          { id: "none", label: "No hardware" },
        ],
      },
    ],
  },
  {
    id: "poster-satin",
    name: "Satin Poster Print",
    category: "Posters",
    blurb: "Indoor satin paper posters for events and retail promotions.",
    imageHue: 55,
    startingAt: "$18.00 each",
    artworkRequired: true,
    maxArtworkFiles: 2,
    fields: [
      { id: "size", kind: "dimensions", label: "Finished size", required: true, unit: "in" },
      { id: "qty", kind: "quantity", label: "Quantity", required: true, defaultValue: "10" },
      {
        id: "mount",
        kind: "select",
        label: "Mounting",
        defaultValue: "none",
        choices: [
          { id: "none", label: "Unmounted" },
          { id: "foam", label: "Mounted on 3/16 foam" },
        ],
      },
    ],
  },
  {
    id: "styrene-sign",
    name: "Styrene Sign",
    category: "Rigid Signs",
    blurb: "Durable indoor styrene panels for shelf talkers and directional signs.",
    imageHue: 265,
    startingAt: "$21.50 each",
    artworkRequired: true,
    maxArtworkFiles: 2,
    fields: [
      { id: "size", kind: "dimensions", label: "Finished size", required: true, unit: "in" },
      { id: "qty", kind: "quantity", label: "Quantity", required: true, defaultValue: "12" },
      {
        id: "corners",
        kind: "select",
        label: "Corners",
        defaultValue: "square",
        choices: [
          { id: "square", label: "Square" },
          { id: "round", label: "Rounded 1/4 in" },
        ],
      },
    ],
  },
];

export const orders: PortalOrder[] = [
  {
    id: "o10671",
    number: "SO-10671",
    po: "BRO-2291",
    placedOn: "2026-08-28",
    dueOn: "2026-09-09",
    status: "Awaiting Your Approval",
    fulfillment: "Not Started",
    total: 2184.5,
    balance: 2184.5,
    contact: "Marta Reyes",
    shipTo: "88 Riverside Dr, Bay 4 — Asheville, NC",
    method: "Ship",
    lines: [
      {
        id: "l1",
        product: "13oz Vinyl Banner",
        description: "Fall Trail Series banner",
        qty: 6,
        size: '96" × 36"',
        options: ["Double sided", "Hem all sides", "Grommets every 24 in"],
        unitPrice: 168.75,
        total: 1012.5,
        artwork: [{ name: "trailseries-banner-v3.pdf", status: "Received" }],
        proofStatus: "Awaiting Your Approval",
      },
      {
        id: "l2",
        product: "4mm Coroplast Sign",
        description: "Trailhead directional signs",
        qty: 60,
        size: '24" × 18"',
        options: ["Single sided", "Vertical flutes", "H-stakes"],
        unitPrice: 19.53,
        total: 1172.0,
        artwork: [{ name: "trailhead-directional.ai", status: "Received" }],
        proofStatus: "Approved",
      },
    ],
    shipments: [],
    invoiceIds: [],
    documents: [{ name: "SO-10671 Order Acknowledgement.pdf", kind: "PDF", date: "2026-08-28" }],
    notes: "Please match the green from last spring's run.",
  },
  {
    id: "o10664",
    number: "SO-10664",
    po: "BRO-2277",
    placedOn: "2026-08-19",
    dueOn: "2026-09-02",
    status: "Partially Shipped",
    fulfillment: "Partially Fulfilled",
    total: 4820.0,
    balance: 1920.0,
    contact: "Marta Reyes",
    shipTo: "88 Riverside Dr, Bay 4 — Asheville, NC",
    method: "Ship",
    lines: [
      {
        id: "l1",
        product: "Adhesive Vinyl",
        description: "Storefront window graphics — 4 locations",
        qty: 12,
        size: '60" × 40"',
        options: ["Calendared", "Matte laminate"],
        unitPrice: 168.0,
        total: 2016.0,
        artwork: [{ name: "window-set-final.pdf", status: "Proof approved" }],
        proofStatus: "Approved",
      },
      {
        id: "l2",
        product: "Contour Cut Stickers",
        description: "Logo stickers, 3 in",
        qty: 2500,
        size: '3" × 3"',
        options: ["Kiss cut on sheets", "Matte laminate"],
        unitPrice: 0.62,
        total: 1550.0,
        artwork: [{ name: "bro-logo-sticker.ai", status: "Proof approved" }],
        proofStatus: "Approved",
      },
      {
        id: "l3",
        product: "Acrylic Sign",
        description: "Lobby panel",
        qty: 2,
        size: '36" × 24"',
        options: ["1/4 in", "Second surface", "Standoffs"],
        unitPrice: 627.0,
        total: 1254.0,
        artwork: [{ name: "lobby-panel.pdf", status: "Proof approved" }],
        proofStatus: "Approved",
      },
    ],
    shipments: [
      {
        id: "s1",
        carrier: "UPS",
        service: "Ground",
        tracking: "1Z9X4A310398472615",
        shippedOn: "2026-08-27",
        contents: "2,500 contour cut stickers",
        status: "Delivered",
      },
      {
        id: "s2",
        carrier: "FedEx",
        service: "Freight Priority",
        tracking: "774920183355",
        shippedOn: "2026-09-03",
        contents: "12 window graphic panels",
        status: "In Transit",
      },
    ],
    invoiceIds: ["i5521", "i5528"],
    documents: [
      { name: "SO-10664 Order Acknowledgement.pdf", kind: "PDF", date: "2026-08-19" },
      { name: "Packing Slip 2026-08-27.pdf", kind: "PDF", date: "2026-08-27" },
    ],
  },
  {
    id: "o10650",
    number: "SO-10650",
    po: "BRO-2260",
    placedOn: "2026-08-04",
    dueOn: "2026-08-14",
    status: "Ready for Pickup",
    fulfillment: "Pickup Ready",
    total: 762.0,
    balance: 762.0,
    contact: "Devin Locke",
    shipTo: "Will call — Hensley Print Co.",
    method: "Pickup",
    lines: [
      {
        id: "l1",
        product: "Satin Poster Print",
        description: "Autumn event posters",
        qty: 40,
        size: '24" × 36"',
        options: ["Unmounted"],
        unitPrice: 19.05,
        total: 762.0,
        artwork: [{ name: "autumn-event-poster.pdf", status: "Proof approved" }],
        proofStatus: "Approved",
      },
    ],
    shipments: [],
    invoiceIds: ["i5514"],
    documents: [{ name: "SO-10650 Pickup Notice.pdf", kind: "PDF", date: "2026-08-13" }],
  },
  {
    id: "o10611",
    number: "SO-10611",
    po: "BRO-2203",
    placedOn: "2026-06-11",
    status: "Completed",
    fulfillment: "Fulfilled",
    total: 1345.0,
    balance: 0,
    contact: "Marta Reyes",
    shipTo: "88 Riverside Dr, Bay 4 — Asheville, NC",
    method: "Ship",
    lines: [
      {
        id: "l1",
        product: "4mm Coroplast Sign",
        description: "Summer sale signs",
        qty: 75,
        size: '18" × 24"',
        options: ["Double sided", "H-stakes"],
        unitPrice: 17.93,
        total: 1345.0,
        artwork: [{ name: "summer-sale.pdf", status: "Proof approved" }],
        proofStatus: "Approved",
      },
    ],
    shipments: [
      {
        id: "s1",
        carrier: "UPS",
        service: "Ground",
        tracking: "1Z9X4A310381140022",
        shippedOn: "2026-06-18",
        contents: "75 coroplast signs",
        status: "Delivered",
      },
    ],
    invoiceIds: ["i5402"],
    documents: [{ name: "SO-10611 Invoice.pdf", kind: "PDF", date: "2026-06-18" }],
  },
  {
    id: "o10588",
    number: "SO-10588",
    po: "BRO-2181",
    placedOn: "2026-05-02",
    status: "Completed",
    fulfillment: "Fulfilled",
    total: 498.0,
    balance: 0,
    contact: "Devin Locke",
    shipTo: "Will call — Hensley Print Co.",
    method: "Pickup",
    lines: [
      {
        id: "l1",
        product: "Contour Cut Stickers",
        description: "Trail badge stickers",
        qty: 750,
        size: '2" × 2"',
        options: ["Die cut singles", "Gloss laminate"],
        unitPrice: 0.66,
        total: 498.0,
        artwork: [{ name: "trail-badges.ai", status: "Proof approved" }],
        proofStatus: "Approved",
      },
    ],
    shipments: [],
    invoiceIds: ["i5330"],
    documents: [],
  },
];

export const proofs: PortalProof[] = [
  {
    id: "pf-3301",
    orderId: "o10671",
    orderNumber: "SO-10671",
    jobName: "Fall Trail Series banner",
    version: 3,
    sentOn: "2026-09-05",
    status: "Awaiting Your Approval",
    hue: 28,
    size: '96" × 36"',
    history: [
      { version: 1, date: "2026-08-29", event: "Proof sent" },
      { version: 1, date: "2026-08-30", event: "Revision requested", note: "Trail name should read 'Craggy Ridge', not 'Craggy Ridge Trail'." },
      { version: 2, date: "2026-09-01", event: "Proof sent" },
      { version: 2, date: "2026-09-02", event: "Revision requested", note: "Logo needs more clearance from the hem." },
      { version: 3, date: "2026-09-05", event: "Proof sent" },
    ],
  },
  {
    id: "pf-3298",
    orderId: "o10671",
    orderNumber: "SO-10671",
    jobName: "Trailhead directional signs",
    version: 1,
    sentOn: "2026-08-30",
    status: "Approved",
    hue: 145,
    size: '24" × 18"',
    history: [
      { version: 1, date: "2026-08-30", event: "Proof sent" },
      { version: 1, date: "2026-08-31", event: "Approved by Marta Reyes" },
    ],
  },
  {
    id: "pf-3277",
    orderId: "o10664",
    orderNumber: "SO-10664",
    jobName: "Storefront window graphics",
    version: 2,
    sentOn: "2026-08-21",
    status: "Approved",
    hue: 210,
    size: '60" × 40"',
    history: [
      { version: 1, date: "2026-08-20", event: "Proof sent" },
      { version: 1, date: "2026-08-20", event: "Revision requested", note: "Swap the hours block to the right panel." },
      { version: 2, date: "2026-08-21", event: "Proof sent" },
      { version: 2, date: "2026-08-21", event: "Approved by Marta Reyes" },
    ],
  },
  {
    id: "pf-3260",
    orderId: "o10650",
    orderNumber: "SO-10650",
    jobName: "Autumn event posters",
    version: 1,
    sentOn: "2026-08-06",
    status: "Approved",
    hue: 55,
    size: '24" × 36"',
    history: [
      { version: 1, date: "2026-08-06", event: "Proof sent" },
      { version: 1, date: "2026-08-06", event: "Approved by Devin Locke" },
    ],
  },
];

export const quotes: PortalQuote[] = [
  {
    id: "q-2214",
    number: "QT-2214",
    date: "2026-09-02",
    expiresOn: "2026-10-02",
    status: "Open",
    total: 3410.0,
    po: "BRO-2298",
    lines: [
      {
        id: "l1",
        product: "Acrylic Sign",
        description: "Retail wayfinding panels",
        qty: 5,
        size: '30" × 20"',
        options: ["1/4 in", "Second surface", "Standoffs"],
        unitPrice: 486.0,
        total: 2430.0,
        artwork: [],
      },
      {
        id: "l2",
        product: "Styrene Sign",
        description: "Shelf talkers",
        qty: 40,
        size: '7" × 11"',
        options: ["Rounded corners"],
        unitPrice: 24.5,
        total: 980.0,
        artwork: [],
      },
    ],
    documents: [{ name: "QT-2214.pdf", kind: "PDF", date: "2026-09-02" }],
  },
  {
    id: "q-2201",
    number: "QT-2201",
    date: "2026-08-18",
    expiresOn: "2026-09-17",
    status: "Converted",
    total: 4820.0,
    lines: [
      {
        id: "l1",
        product: "Adhesive Vinyl",
        description: "Storefront window graphics",
        qty: 12,
        size: '60" × 40"',
        options: ["Calendared", "Matte laminate"],
        unitPrice: 168.0,
        total: 2016.0,
        artwork: [],
      },
    ],
    convertedOrderId: "o10664",
    documents: [{ name: "QT-2201.pdf", kind: "PDF", date: "2026-08-18" }],
  },
  {
    id: "q-2166",
    number: "QT-2166",
    date: "2026-07-02",
    expiresOn: "2026-08-01",
    status: "Expired",
    total: 1180.0,
    lines: [
      {
        id: "l1",
        product: "13oz Vinyl Banner",
        description: "Grand opening banners",
        qty: 4,
        size: '120" × 36"',
        options: ["Single sided", "Hem all sides"],
        unitPrice: 295.0,
        total: 1180.0,
        artwork: [],
      },
    ],
    documents: [{ name: "QT-2166.pdf", kind: "PDF", date: "2026-07-02" }],
  },
];

export const invoices: PortalInvoice[] = [
  {
    id: "i5528",
    number: "INV-5528",
    orderNumber: "SO-10664",
    orderId: "o10664",
    po: "BRO-2277",
    date: "2026-09-03",
    dueOn: "2026-10-03",
    total: 2016.0,
    paid: 0,
    balance: 2016.0,
    status: "Open",
    allowsPartial: true,
  },
  {
    id: "i5521",
    number: "INV-5521",
    orderNumber: "SO-10664",
    orderId: "o10664",
    po: "BRO-2277",
    date: "2026-08-27",
    dueOn: "2026-09-26",
    total: 1550.0,
    paid: 650.0,
    balance: 900.0,
    status: "Open",
    allowsPartial: true,
  },
  {
    id: "i5514",
    number: "INV-5514",
    orderNumber: "SO-10650",
    orderId: "o10650",
    po: "BRO-2260",
    date: "2026-08-13",
    dueOn: "2026-08-28",
    total: 762.0,
    paid: 0,
    balance: 762.0,
    status: "Overdue",
    allowsPartial: false,
  },
  {
    id: "i5402",
    number: "INV-5402",
    orderNumber: "SO-10611",
    orderId: "o10611",
    po: "BRO-2203",
    date: "2026-06-18",
    dueOn: "2026-07-18",
    total: 1345.0,
    paid: 1345.0,
    balance: 0,
    status: "Paid",
    allowsPartial: true,
  },
  {
    id: "i5330",
    number: "INV-5330",
    orderNumber: "SO-10588",
    orderId: "o10588",
    po: "BRO-2181",
    date: "2026-05-06",
    dueOn: "2026-06-05",
    total: 498.0,
    paid: 498.0,
    balance: 0,
    status: "Paid",
    allowsPartial: true,
  },
];
