import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { ROUTES } from "@/config/routes";

type Destination = { id: string; displayName: string; location: string | null; defaultCopies: number; isDefault: boolean; available: boolean };
export function TravelerPrintDialog({ orderId, open, onOpenChange }: { orderId: string; open: boolean; onOpenChange: (open: boolean) => void }) {
  const { toast } = useToast(); const [destinationId, setDestinationId] = useState(""); const [copies, setCopies] = useState("1"); const [note, setNote] = useState(""); const [submitting, setSubmitting] = useState(false);
  const query = useQuery<Destination[]>({ queryKey: ["/api/direct-print/traveler-destinations"], enabled: open, queryFn: async () => { const r = await fetch("/api/direct-print/traveler-destinations", { credentials: "include" }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "Could not load Traveler destinations"); return j.data; } });
  const destinations = query.data ?? []; const selected = destinations.find((d) => d.id === destinationId);
  useEffect(() => { if (!open || destinationId) return; const target = destinations.find((d) => d.isDefault && d.available) ?? destinations.find((d) => d.available) ?? destinations[0]; if (target) { setDestinationId(target.id); setCopies(String(target.defaultCopies || 1)); } }, [open, destinations, destinationId]);
  async function submit() { const parsed = Number(copies); if (!selected || !selected.available || !Number.isInteger(parsed) || parsed < 1 || parsed > 99) { toast({ title: "Select an available destination and enter 1–99 copies.", variant: "destructive" }); return; } setSubmitting(true); try { const r = await fetch(`/api/orders/${orderId}/direct-print/traveler`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ destinationId, copies: parsed, printNote: note }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "Direct print could not be queued"); toast({ title: `Traveler queued for ${selected.displayName}`, description: `${parsed} copy${parsed === 1 ? "" : "ies"} will be submitted when the Print Agent accepts it.` }); onOpenChange(false); } catch (error: any) { toast({ title: "Direct print unavailable", description: error.message, variant: "destructive" }); } finally { setSubmitting(false); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Print Traveler</DialogTitle><DialogDescription>Choose where this read-only Traveler print job goes.</DialogDescription></DialogHeader>{query.isLoading ? <p className="text-sm text-muted-foreground">Loading destinations…</p> : <div className="space-y-4"><div className="space-y-1.5"><Label>Printer / Destination</Label><Select value={destinationId} onValueChange={(id) => { setDestinationId(id); const d = destinations.find((x) => x.id === id); if (d) setCopies(String(d.defaultCopies || 1)); }}><SelectTrigger><SelectValue placeholder="Select a destination" /></SelectTrigger><SelectContent>{destinations.map((d) => <SelectItem value={d.id} key={d.id} disabled={!d.available}>{d.displayName}{d.location ? ` — ${d.location}` : ""}{d.available ? "" : " (offline)"}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label htmlFor="traveler-copies">Copies</Label><Input id="traveler-copies" type="number" min="1" max="99" step="1" value={copies} onChange={(e) => setCopies(e.target.value)} /></div><div className="space-y-1.5"><Label htmlFor="traveler-print-note">Print Note <span className="text-muted-foreground">(optional, print-only)</span></Label><Textarea id="traveler-print-note" value={note} maxLength={1000} onChange={(e) => setNote(e.target.value)} /></div></div>}<DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="secondary" onClick={() => window.open(ROUTES.orders.traveler(orderId), "_blank")}>Open Browser Print</Button><Button onClick={() => void submit()} disabled={query.isLoading || submitting || !selected?.available}>{submitting ? "Queueing…" : "Print"}</Button></DialogFooter></DialogContent></Dialog>;
}
