import { and, asc, desc, eq, gte, ilike, lt, or, sql } from 'drizzle-orm';
import { customers, invoices, orders, payments } from '@shared/schema';
import { db } from '../db';
import { getOrganizationTimezone } from './orderDueDateService';

export type PaymentDatePreset = 'today' | 'this-week' | 'this-month' | 'custom' | 'all';
export type PaymentListSort = 'paymentDate' | 'customer' | 'invoiceNumber' | 'orderNumber' | 'jobName' | 'method' | 'reference' | 'amount';
export type PaymentListInput = { organizationId: string; datePreset?: PaymentDatePreset; dateFrom?: string; dateTo?: string; customerId?: string; method?: string; search?: string; sortBy?: PaymentListSort; sortDir?: 'asc' | 'desc'; page?: number; pageSize?: number; now?: Date };

function parts(now: Date, timezone: string) { const values = new Intl.DateTimeFormat('en-US', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(now); const n = (type: string) => Number(values.find((part) => part.type === type)?.value || 0); return { year: n('year'), month: n('month'), day: n('day') }; }
function midnight(year: number, month: number, day: number, timezone: string) { const candidate = Date.UTC(year, month - 1, day); const observe = (value: number) => { const p = new Intl.DateTimeFormat('en-US', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).formatToParts(new Date(value)); const n = (type: string) => Number(p.find((part) => part.type === type)?.value || 0); return Date.UTC(n('year'), n('month') - 1, n('day'), n('hour'), n('minute'), n('second')); }; const adjusted = candidate - (observe(candidate) - candidate); return new Date(adjusted - (observe(adjusted) - candidate)); }
function nextDay(year: number, month: number, day: number) { const value = new Date(Date.UTC(year, month - 1, day + 1)); return { year: value.getUTCFullYear(), month: value.getUTCMonth() + 1, day: value.getUTCDate() }; }
export function paymentDateWindow(preset: PaymentDatePreset, timezone: string, now = new Date(), dateFrom?: string, dateTo?: string) { const today = parts(now, timezone); if (preset === 'all') return {}; let start = today; let end = nextDay(today.year, today.month, today.day); if (preset === 'this-month') { start = { ...today, day: 1 }; end = today.month === 12 ? { year: today.year + 1, month: 1, day: 1 } : { year: today.year, month: today.month + 1, day: 1 }; } if (preset === 'this-week') { const day = new Date(Date.UTC(today.year, today.month - 1, today.day)).getUTCDay(); const monday = new Date(Date.UTC(today.year, today.month - 1, today.day + (day === 0 ? -6 : 1 - day))); start = { year: monday.getUTCFullYear(), month: monday.getUTCMonth() + 1, day: monday.getUTCDate() }; } if (preset === 'custom' && /^\d{4}-\d{2}-\d{2}$/.test(dateFrom || '')) { const [year, month, day] = dateFrom!.split('-').map(Number); start = { year, month, day }; if (/^\d{4}-\d{2}-\d{2}$/.test(dateTo || '')) { const [endYear, endMonth, endDay] = dateTo!.split('-').map(Number); end = nextDay(endYear, endMonth, endDay); } } return { start: midnight(start.year, start.month, start.day, timezone), endExclusive: midnight(end.year, end.month, end.day, timezone) }; }
const sortValues: PaymentListSort[] = ['paymentDate', 'customer', 'invoiceNumber', 'orderNumber', 'jobName', 'method', 'reference', 'amount'];
export const normalizePaymentListSort = (value: unknown): PaymentListSort => sortValues.includes(value as PaymentListSort) ? value as PaymentListSort : 'paymentDate';

export async function listPayments(input: PaymentListInput) {
  const timezone = await getOrganizationTimezone(input.organizationId); const preset = input.datePreset || 'all'; const window = paymentDateWindow(preset, timezone, input.now, input.dateFrom, input.dateTo); const where: any[] = [eq(payments.organizationId, input.organizationId), eq(payments.status, 'succeeded')];
  if (window.start) where.push(gte(payments.appliedAt, window.start)); if (window.endExclusive) where.push(lt(payments.appliedAt, window.endExclusive)); if (input.customerId) where.push(eq(invoices.customerId, input.customerId)); if (input.method) where.push(eq(payments.method, input.method));
  const q = String(input.search || '').trim(); if (q) { const like = `%${q}%`; where.push(or(ilike(customers.companyName, like), ilike(invoices.displayNumber, like), ilike(orders.orderNumber, like), ilike(orders.label, like), ilike(payments.providerTransactionId, like), ilike(payments.quickbooksPaymentReference, like), ilike(payments.notes, like), ilike(payments.note, like))); }
  const predicate = and(...where); const sort = normalizePaymentListSort(input.sortBy); const direction = input.sortDir === 'asc' ? asc : desc; const column: any = ({ paymentDate: payments.appliedAt, customer: customers.companyName, invoiceNumber: invoices.displayNumber, orderNumber: orders.orderNumber, jobName: orders.label, method: payments.method, reference: payments.providerTransactionId, amount: payments.amountCents } as Record<PaymentListSort, any>)[sort]; const pageSize = Math.min(Math.max(Number(input.pageSize || 50), 1), 200); const page = Math.max(Number(input.page || 1), 1);
  const base = db.select({ id: payments.id, appliedAt: payments.appliedAt, amountCents: payments.amountCents, amount: payments.amount, method: payments.method, provider: payments.provider, status: payments.status, reference: payments.providerTransactionId, quickbooksPaymentReference: payments.quickbooksPaymentReference, note: payments.note, notes: payments.notes, customerId: customers.id, customerName: customers.companyName, invoiceId: invoices.id, invoiceNumber: invoices.displayNumber, invoiceLegacyNumber: invoices.invoiceNumber, orderId: orders.id, orderNumber: orders.orderNumber, jobName: orders.label }).from(payments).leftJoin(invoices, eq(payments.invoiceId, invoices.id)).leftJoin(customers, eq(invoices.customerId, customers.id)).leftJoin(orders, eq(invoices.orderId, orders.id));
  const [rows, countRows, totalRows] = await Promise.all([base.where(predicate).orderBy(direction(column), direction(payments.id)).limit(pageSize).offset((page - 1) * pageSize), db.select({ count: sql<number>`count(*)::int` }).from(payments).leftJoin(invoices, eq(payments.invoiceId, invoices.id)).leftJoin(customers, eq(invoices.customerId, customers.id)).leftJoin(orders, eq(invoices.orderId, orders.id)).where(predicate), db.select({ cents: sql<number>`coalesce(sum(${payments.amountCents}), 0)::int` }).from(payments).leftJoin(invoices, eq(payments.invoiceId, invoices.id)).leftJoin(customers, eq(invoices.customerId, customers.id)).leftJoin(orders, eq(invoices.orderId, orders.id)).where(predicate)]);
  const totalCount = Number(countRows[0]?.count || 0); return { rows, summary: { totalPayments: totalCount, totalCollectedCents: Number(totalRows[0]?.cents || 0) }, pagination: { page, pageSize, totalCount, totalPages: Math.max(1, Math.ceil(totalCount / pageSize)) }, timezone, datePreset: preset };
}
