import type { Pool, PoolClient } from "pg";
import { PostgresOperationRequestRepository } from "../persistence/postgresOperationRequests.js";
import type { ProductionTransaction, ProductionTransactionRunner } from "../../src/modules/production/productionApplication.js";
import type { ProductionAttempt, ProductionOperatorContext, ProductionWork, ProductionWorkProjection } from "../../src/modules/production/contracts.js";
import { brandedId, type OrganizationId, type ProductionAttemptId, type ProductionWorkId } from "../../src/modules/shared/commercialValues.js";

type WorkRow={id:string;organization_id:string;order_document_id:string;order_line_id:string;requirement_key:string;side:"front"|"back"|null;source_page_index:number|null;layer_key:string|null;layer_order:number|null;artwork_assignment_id:string;artwork_file_id:string;prepress_unit_id:string|null;ordered_quantity:number;created_at:Date;created_principal_kind:ProductionWork["createdPrincipalKind"];created_principal_subject:string;created_staff_actor_user_id:string|null};
type AttemptRow={id:string;organization_id:string;production_work_id:string;sequence:number;attempt_kind:ProductionAttempt["kind"];station_key:ProductionAttempt["stationKey"];good_quantity:number;waste_quantity:number;started_at:Date;started_principal_kind:ProductionAttempt["startedPrincipalKind"];started_principal_subject:string;started_staff_actor_user_id:string|null;completed_at:Date|null;completed_principal_kind:ProductionAttempt["completedPrincipalKind"]|null;completed_principal_subject:string|null;completed_staff_actor_user_id:string|null};
type OperatorContextRow={order_number:string|null;product_id:string|null;product_display_name:string|null;customer_id:string|null;customer_display_name:string|null};
const work=(r:WorkRow):ProductionWork=>({productionWorkId:brandedId<"ProductionWorkId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),orderId:brandedId<"OrderId">(r.order_document_id),orderLineId:brandedId<"OrderLineId">(r.order_line_id),requirement:{key:r.requirement_key,...(r.side?{side:r.side}:{}),...(r.source_page_index===null?{}:{sourcePageIndex:r.source_page_index}),...(r.layer_key===null?{}:{layerKey:r.layer_key,layerOrder:r.layer_order!})},artworkAssignmentId:brandedId<"ArtworkAssignmentId">(r.artwork_assignment_id),artworkFileId:brandedId<"ArtworkFileId">(r.artwork_file_id),...(r.prepress_unit_id?{prepressUnitId:brandedId<"PrepressUnitId">(r.prepress_unit_id)}:{}),orderedQuantity:r.ordered_quantity,createdAt:r.created_at.toISOString(),createdPrincipalKind:r.created_principal_kind,createdPrincipalSubject:r.created_principal_subject,...(r.created_staff_actor_user_id?{createdStaffActorUserId:r.created_staff_actor_user_id}:{})});
const attempt=(r:AttemptRow):ProductionAttempt=>({productionAttemptId:brandedId<"ProductionAttemptId">(r.id),organizationId:brandedId<"OrganizationId">(r.organization_id),productionWorkId:brandedId<"ProductionWorkId">(r.production_work_id),sequence:r.sequence,kind:r.attempt_kind,stationKey:r.station_key,goodQuantity:r.good_quantity,wasteQuantity:r.waste_quantity,startedAt:r.started_at.toISOString(),startedPrincipalKind:r.started_principal_kind,startedPrincipalSubject:r.started_principal_subject,...(r.started_staff_actor_user_id?{startedStaffActorUserId:r.started_staff_actor_user_id}:{}),...(r.completed_at?{completedAt:r.completed_at.toISOString(),completedPrincipalKind:r.completed_principal_kind!,completedPrincipalSubject:r.completed_principal_subject!,...(r.completed_staff_actor_user_id?{completedStaffActorUserId:r.completed_staff_actor_user_id}:{})}:{})});
export const productionOperatorContext=(row:OperatorContextRow):ProductionOperatorContext|undefined=>{
 const productName=row.product_display_name?.trim();
 const customerName=row.customer_display_name?.trim();
 const context:ProductionOperatorContext={
   ...(row.order_number?.trim()?{orderNumber:row.order_number.trim()}:{}),
   ...(row.product_id&&productName?{product:{productId:brandedId<"ProductId">(row.product_id),displayName:productName}}:{}),
   ...(row.customer_id?{customer:{customerId:brandedId<"CustomerId">(row.customer_id),displayName:customerName||"Customer unavailable"}}:{}),
 };
 return Object.keys(context).length?context:undefined;
};
export const productionOperatorContextSql=`SELECT d.display_number order_number,l.product_id,NULLIF(btrim(l.description),'') product_display_name,d.customer_id,
  COALESCE(NULLIF(btrim(c.display_name),''),NULLIF(btrim(c.company_name),'')) customer_display_name
  FROM v2_production_works w
  LEFT JOIN v2_sales_document_lines l ON l.organization_id=w.organization_id AND l.id=w.order_line_id AND l.document_id=w.order_document_id
  LEFT JOIN v2_sales_documents d ON d.organization_id=w.organization_id AND d.id=w.order_document_id AND d.document_kind='order'
  LEFT JOIN customers c ON c.organization_id=d.organization_id AND c.id=d.customer_id
  WHERE w.organization_id=$1 AND w.id=$2`;
export type ProductionPersistenceTestHooks=Readonly<{afterWork?:()=>Promise<void>;afterAttempt?:()=>Promise<void>;afterOutput?:()=>Promise<void>;afterAudit?:()=>Promise<void>}>;
export class PostgresProductionTransaction implements ProductionTransaction {
 private readonly requests=new PostgresOperationRequestRepository();constructor(private readonly client:PoolClient,private readonly hooks?:ProductionPersistenceTestHooks){}
 async reserve(input:Parameters<ProductionTransaction["reserve"]>[0]){const r=await this.requests.reserve(this.client,input);return {kind:r.kind,request:{id:r.request.id,resultJson:r.request.resultJson}};}
 async succeed(org:string,id:string,result:Parameters<ProductionTransaction["succeed"]>[2]){const resourceId=result.attempt?.productionAttemptId??result.work.productionWorkId;await this.requests.succeed(this.client,org,id,{resourceType:result.attempt?"production_attempt":"production_work",resourceId,resultJson:result});}
 async attribute(input:Parameters<ProductionTransaction["attribute"]>[0]){await this.requests.recordAttribution(this.client,{organizationId:input.organizationId,operationRequestId:input.requestId,operation:input.operation,resourceType:input.resourceType,resourceId:input.resourceId,principalKind:input.principalKind,principalSubject:input.principalSubject,staffActorUserId:input.staffActorUserId});}
 async audit(input:Parameters<ProductionTransaction["audit"]>[0]){const type=input.eventType==="production_work_opened"?"production_work":"production_attempt";await this.client.query("INSERT INTO v2_audit_events(organization_id,operation_request_id,operation,event_type,resource_type,resource_id,principal_kind,principal_subject,staff_actor_user_id,changes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)",[input.organizationId,input.requestId,input.operation,input.eventType,type,input.resourceId,input.principalKind,input.principalSubject,input.staffActorUserId??null,JSON.stringify([{kind:input.eventType,summary:input.summary}])]);await this.hooks?.afterAudit?.();}
 async eligibleProductionAssignment(org:OrganizationId,assignment:any){const r=await this.client.query<{valid:boolean}>(`SELECT EXISTS(SELECT 1 FROM v2_artwork_assignments a JOIN v2_sales_line_production_requirements r ON r.organization_id=a.organization_id AND r.order_line_id=a.order_line_id AND a.purpose='production' AND a.side IS NOT DISTINCT FROM r.side AND a.source_page_index IS NOT DISTINCT FROM r.source_page_index AND a.layer_key IS NOT DISTINCT FROM r.layer_key AND a.layer_order IS NOT DISTINCT FROM r.layer_order JOIN v2_route_instances ri ON ri.organization_id=a.organization_id AND ri.order_document_id=a.order_document_id AND ri.order_line_id=a.order_line_id JOIN v2_route_instance_steps step ON step.organization_id=ri.organization_id AND step.route_instance_id=ri.id AND step.id=ri.current_step_id WHERE a.organization_id=$1 AND a.id=$2 AND ri.route_state IN ('pending','active') AND step.step_kind='production' AND (NOT EXISTS(SELECT 1 FROM v2_route_instance_steps p WHERE p.organization_id=ri.organization_id AND p.route_instance_id=ri.id AND p.step_kind='prepress') OR EXISTS(SELECT 1 FROM v2_prepress_units pu WHERE pu.organization_id=a.organization_id AND pu.artwork_assignment_id=a.id AND pu.completed_at IS NOT NULL))) valid`,[org,assignment]);return r.rows[0]?.valid===true;}
 async createOrGetWork(input:Parameters<ProductionTransaction["createOrGetWork"]>[0]){const r=await this.client.query<WorkRow>(`INSERT INTO v2_production_works(id,organization_id,order_document_id,order_line_id,requirement_key,artwork_assignment_id,artwork_file_id,prepress_unit_id,side,source_page_index,layer_key,layer_order,ordered_quantity,created_principal_kind,created_principal_subject,created_staff_actor_user_id) SELECT $1,a.organization_id,a.order_document_id,a.order_line_id,req.requirement_key,a.id,a.artwork_file_id,pu.id,a.side,a.source_page_index,a.layer_key,a.layer_order,l.quantity,$3,$4,$5 FROM v2_artwork_assignments a JOIN v2_sales_line_production_requirements req ON req.organization_id=a.organization_id AND req.order_line_id=a.order_line_id AND a.side IS NOT DISTINCT FROM req.side AND a.source_page_index IS NOT DISTINCT FROM req.source_page_index AND a.layer_key IS NOT DISTINCT FROM req.layer_key AND a.layer_order IS NOT DISTINCT FROM req.layer_order JOIN v2_sales_document_lines l ON l.organization_id=a.organization_id AND l.id=a.order_line_id LEFT JOIN v2_prepress_units pu ON pu.organization_id=a.organization_id AND pu.artwork_assignment_id=a.id AND pu.completed_at IS NOT NULL WHERE a.organization_id=$2 AND a.id=$6 AND a.purpose='production' ON CONFLICT(organization_id,artwork_assignment_id) DO NOTHING RETURNING *`,[input.id,input.organizationId,input.principalKind,input.principalSubject,input.staffActorUserId??null,input.artworkAssignmentId]);if(r.rows[0]){await this.hooks?.afterWork?.();return work(r.rows[0]);}const prior=await this.client.query<WorkRow>("SELECT * FROM v2_production_works WHERE organization_id=$1 AND artwork_assignment_id=$2 FOR UPDATE",[input.organizationId,input.artworkAssignmentId]);if(!prior.rows[0])throw Error("Production work creation could not reload its authoritative row.");return work(prior.rows[0]);}
 async findWork(org:OrganizationId,id:ProductionWorkId){const r=await this.client.query<WorkRow>("SELECT * FROM v2_production_works WHERE organization_id=$1 AND id=$2",[org,id]);return r.rows[0]?work(r.rows[0]):null;}
 async lockWork(org:OrganizationId,id:ProductionWorkId){const r=await this.client.query<WorkRow>("SELECT * FROM v2_production_works WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,id]);return r.rows[0]?work(r.rows[0]):null;}
 async readWork(org:OrganizationId,id:ProductionWorkId):Promise<ProductionWorkProjection|null>{const found=await this.findWork(org,id);if(!found)return null;const [rows,presentation]=await Promise.all([
   this.client.query<AttemptRow>("SELECT * FROM v2_production_attempts WHERE organization_id=$1 AND production_work_id=$2 ORDER BY sequence",[org,id]),
   this.client.query<OperatorContextRow>(productionOperatorContextSql,[org,id]),
 ]);const attempts=rows.rows.map(attempt),completedGoodQuantity=attempts.filter(x=>x.completedAt).reduce((n,x)=>n+x.goodQuantity,0),operatorContext=presentation.rows[0]?productionOperatorContext(presentation.rows[0]):undefined;return {work:found,attempts,completedGoodQuantity,unitQuantitySatisfied:completedGoodQuantity>=found.orderedQuantity,...(operatorContext?{operatorContext}:{})};}
 /**
  * An untouched work has no durable station yet. It is therefore shown as
  * eligible Next up work in both station projections; the first attempt is the
  * authoritative station-selection event. Once an attempt exists, the work is
  * visible only through that attempt's station.
  */
 async listStationQueue(org:OrganizationId,station:"flatbed"|"roll",limit:number){const rows=await this.client.query<{id:string}>(`SELECT w.id FROM v2_production_works w WHERE w.organization_id=$1 AND (NOT EXISTS(SELECT 1 FROM v2_production_attempts untouched WHERE untouched.organization_id=w.organization_id AND untouched.production_work_id=w.id) OR EXISTS(SELECT 1 FROM v2_production_attempts assigned WHERE assigned.organization_id=w.organization_id AND assigned.production_work_id=w.id AND assigned.station_key=$2)) ORDER BY w.created_at DESC,w.id LIMIT $3`,[org,station,limit]);return Promise.all(rows.rows.map(row=>this.readWork(org,brandedId<"ProductionWorkId">(row.id)).then(value=>value!)));}
 async listOrderWorks(org:OrganizationId,orderId:any){const rows=await this.client.query<{id:string}>("SELECT id FROM v2_production_works WHERE organization_id=$1 AND order_document_id=$2 ORDER BY created_at DESC,id DESC",[org,orderId]);return Promise.all(rows.rows.map(row=>this.readWork(org,brandedId<"ProductionWorkId">(row.id)).then(value=>value!)));}
 async lockAttempt(org:OrganizationId,id:ProductionAttemptId){const r=await this.client.query<AttemptRow>("SELECT * FROM v2_production_attempts WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,id]);return r.rows[0]?attempt(r.rows[0]):null;}
 async startAttempt(input:Parameters<ProductionTransaction["startAttempt"]>[0]){const sequence=await this.client.query<{n:string}>("SELECT coalesce(max(sequence),0)+1 n FROM v2_production_attempts WHERE organization_id=$1 AND production_work_id=$2",[input.organizationId,input.productionWorkId]);const r=await this.client.query<AttemptRow>("INSERT INTO v2_production_attempts(id,organization_id,production_work_id,sequence,attempt_kind,station_key,started_principal_kind,started_principal_subject,started_staff_actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[input.id,input.organizationId,input.productionWorkId,Number(sequence.rows[0]!.n),input.kind,input.stationKey,input.principalKind,input.principalSubject,input.staffActorUserId??null]);await this.hooks?.afterAttempt?.();return attempt(r.rows[0]!);}
 async recordOutput(input:Parameters<ProductionTransaction["recordOutput"]>[0]){const r=await this.client.query<AttemptRow>("UPDATE v2_production_attempts SET good_quantity=good_quantity+$3,waste_quantity=waste_quantity+$4 WHERE organization_id=$1 AND id=$2 AND completed_at IS NULL RETURNING *",[input.organizationId,input.productionAttemptId,input.goodQuantityDelta,input.wasteQuantityDelta]);if(!r.rows[0])throw Error("Production output was not available.");await this.hooks?.afterOutput?.();return attempt(r.rows[0]);}
 async completeAttempt(input:Parameters<ProductionTransaction["completeAttempt"]>[0]){const r=await this.client.query<AttemptRow>("UPDATE v2_production_attempts SET completed_at=now(),completed_principal_kind=$3,completed_principal_subject=$4,completed_staff_actor_user_id=$5 WHERE organization_id=$1 AND id=$2 AND completed_at IS NULL RETURNING *",[input.organizationId,input.productionAttemptId,input.principalKind,input.principalSubject,input.staffActorUserId??null]);if(!r.rows[0])throw Error("Production attempt completion was not available.");return attempt(r.rows[0]);}
}
export class PostgresProductionTransactionRunner implements ProductionTransactionRunner {constructor(private readonly pool:Pool,private readonly hooks?:ProductionPersistenceTestHooks){}async transaction<T>(action:(tx:ProductionTransaction)=>Promise<T>){const client=await this.pool.connect();try{await client.query("BEGIN");const r=await action(new PostgresProductionTransaction(client,this.hooks));await client.query("COMMIT");return r;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}}
