import type { Pool, PoolClient } from "pg";
import { PostgresOperationRequestRepository } from "../persistence/postgresOperationRequests.js";
import type { InventoryBalance, InventoryLedgerTransaction, InventoryLedgerTransactionRunner, InventoryMovement, InventoryReconciliation, InventoryReservation } from "../../src/modules/inventory/inventoryLedger.js";
import { brandedId, type OrganizationId, type ProductionMaterialConsumptionId, type ProductionWorkId } from "../../src/modules/shared/commercialValues.js";
import { V2ApplicationError } from "../../src/errors/applicationError.js";

type WorkRow = { id: string; order_document_id: string; order_line_id: string; active_attempts: string };
type RequirementRow = { id: string; material_id: string; material_name_snapshot: string; material_sku_snapshot: string | null; quantity: string; quantity_unit: InventoryReservation["unit"] };
type MaterialRow = { id: string; name: string; sku: string | null; stock_quantity: string; consumption_unit: InventoryReservation["unit"] | null; inventory_unit: InventoryReservation["unit"] | null };
type ReservationRow = { id: string; material_id: string; material_name_snapshot: string; material_sku_snapshot: string | null; opened_quantity: string; quantity_unit: InventoryReservation["unit"]; material_requirement_id: string };
type ConsumptionRow = { id: string; organization_id: string; order_document_id: string; order_line_id: string; production_work_id: string; production_attempt_id: string; material_requirement_id: string | null; material_id: string; material_name_snapshot: string; material_sku_snapshot: string | null; quantity: string; quantity_unit: InventoryReservation["unit"]; consumption_kind: "consumed" | "waste" | "correction"; corrects_consumption_id: string | null };
type ReconciliationRow = { consumption_id: string; material_id: string; material_name_snapshot: string; quantity: string; quantity_unit: InventoryReservation["unit"]; consumption_kind: "consumed" | "waste" | "correction"; movement_id: string | null; error_code: string | null; error_message: string | null; failure_status: "retryable" | "blocked" | null; attempt_count: string };
type MovementRow = { id: string; organization_id: string; material_id: string; material_name_snapshot: string; material_sku_snapshot: string | null; production_work_id: string; reservation_id: string | null; material_requirement_id: string | null; consumption_id: string | null; quantity: string; quantity_unit: InventoryReservation["unit"]; movement_kind: InventoryMovement["kind"]; on_hand_delta: string; reserved_delta: string; created_at: Date };
const noRows = <T>(rows: readonly T[]) => rows.length === 0;
const movement = (row: MovementRow): InventoryMovement => Object.freeze({ movementId: row.id, organizationId: brandedId<"OrganizationId">(row.organization_id), materialId: row.material_id, materialName: row.material_name_snapshot, materialSku: row.material_sku_snapshot, productionWorkId: brandedId<"ProductionWorkId">(row.production_work_id), ...(row.reservation_id ? { reservationId: row.reservation_id } : {}), ...(row.material_requirement_id ? { requirementId: brandedId<"OrderLineMaterialRequirementId">(row.material_requirement_id) } : {}), ...(row.consumption_id ? { consumptionId: brandedId<"ProductionMaterialConsumptionId">(row.consumption_id) } : {}), quantity: row.quantity, unit: row.quantity_unit, kind: row.movement_kind, onHandDelta: row.on_hand_delta, reservedDelta: row.reserved_delta, createdAt: row.created_at.toISOString() });
const positive = (value: string) => /^\d+(?:\.\d{1,6})?$/u.test(value) && Number(value) > 0;

export type InventoryLedgerTestHooks = Readonly<{ afterMovement?: () => Promise<void> }>;

export class PostgresInventoryLedgerTransaction implements InventoryLedgerTransaction {
  private readonly requests = new PostgresOperationRequestRepository();
  constructor(private readonly client: PoolClient, private readonly hooks?: InventoryLedgerTestHooks) {}
  async reserve(input: Parameters<InventoryLedgerTransaction["reserve"]>[0]) { const result = await this.requests.reserve(this.client, input); return { kind: result.kind, request: { id: result.request.id, resultJson: result.request.resultJson } }; }
  async succeed(organizationId: string, requestId: string, result: unknown) { await this.requests.succeed(this.client, organizationId, requestId, { resourceType: "inventory_movement", resourceId: requestId, resultJson: result }); }
  async attribute(input: Parameters<InventoryLedgerTransaction["attribute"]>[0]) { await this.requests.recordAttribution(this.client, { organizationId: input.organizationId, operationRequestId: input.requestId, operation: input.operation, resourceType: "inventory_movement", resourceId: input.resourceId, principalKind: input.principalKind, principalSubject: input.principalSubject, staffActorUserId: input.staffActorUserId }); }
  async audit(input: Parameters<InventoryLedgerTransaction["audit"]>[0]) { await this.client.query("INSERT INTO v2_audit_events(organization_id,operation_request_id,operation,event_type,resource_type,resource_id,principal_kind,principal_subject,staff_actor_user_id,changes) VALUES($1,$2,$3,'inventory_movement_recorded','inventory_movement',$4,$5,$6,$7,$8::jsonb)", [input.organizationId, input.requestId, input.operation, input.resourceId, input.principalKind, input.principalSubject, input.staffActorUserId ?? null, JSON.stringify([{ kind: "inventory_ledger", summary: input.summary }])]); }
  private async work(org: OrganizationId, id: ProductionWorkId, lock = false): Promise<WorkRow> {
    const row = (await this.client.query<WorkRow>(`SELECT w.id,w.order_document_id,w.order_line_id,(SELECT count(*)::text FROM v2_production_attempts a WHERE a.organization_id=w.organization_id AND a.production_work_id=w.id AND a.completed_at IS NULL) active_attempts FROM v2_production_works w WHERE w.organization_id=$1 AND w.id=$2 ${lock ? "FOR UPDATE" : ""}`, [org, id])).rows[0];
    if (!row) throw new V2ApplicationError("NOT_FOUND", "Production work was not found.");
    return row;
  }
  private async requirements(org: OrganizationId, work: WorkRow): Promise<RequirementRow[]> { return (await this.client.query<RequirementRow>("SELECT id,material_id,material_name_snapshot,material_sku_snapshot,quantity::text,quantity_unit FROM v2_order_line_material_requirements WHERE organization_id=$1 AND order_document_id=$2 AND order_line_id=$3 ORDER BY material_id,id", [org, work.order_document_id, work.order_line_id])).rows; }
  private async lockMaterial(org: OrganizationId, id: string): Promise<MaterialRow> { const row = (await this.client.query<MaterialRow>("SELECT id,name,sku,stock_quantity::text,consumption_unit,inventory_unit FROM materials WHERE organization_id=$1 AND id=$2 FOR UPDATE", [org, id])).rows[0]; if (!row) throw new V2ApplicationError("NOT_FOUND", "Material was not found in this organization."); return row; }
  private async remainingReservation(org: OrganizationId, reservationId: string): Promise<string> { return (await this.client.query<{ remaining: string }>("SELECT COALESCE(sum(reserved_delta),0)::text remaining FROM v2_inventory_movements WHERE organization_id=$1 AND reservation_id=$2", [org, reservationId])).rows[0]!.remaining; }
  private async recordMovement(input: { organizationId: OrganizationId; work: WorkRow; material: MaterialRow; reservation?: ReservationRow; consumption?: ConsumptionRow; quantity: string; unit: InventoryReservation["unit"]; kind: InventoryMovement["kind"]; onHandDelta: string; reservedDelta: string; operationRequestId: string }): Promise<InventoryMovement> {
    if (!positive(input.quantity)) throw new V2ApplicationError("VALIDATION_ERROR", "Inventory quantity must be positive.");
    const requirementBound = Boolean(input.reservation || input.consumption?.material_requirement_id);
    if (input.material.consumption_unit && input.material.consumption_unit !== input.unit
      && (!requirementBound || input.material.inventory_unit !== input.unit)) {
      throw new V2ApplicationError("VALIDATION_ERROR", "Inventory unit must match the Material consumption unit or its frozen requirement inventory basis.");
    }
    const row = (await this.client.query<MovementRow>(`INSERT INTO v2_inventory_movements(organization_id,material_id,material_name_snapshot,material_sku_snapshot,order_document_id,order_line_id,production_work_id,production_attempt_id,material_requirement_id,reservation_id,consumption_id,quantity,quantity_unit,movement_kind,on_hand_delta,reserved_delta,operation_request_id)
      VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::numeric,$13,$14,$15::numeric,$16::numeric,$17) RETURNING *`, [input.organizationId, input.material.id, input.reservation?.material_name_snapshot ?? input.consumption?.material_name_snapshot ?? input.material.name, input.reservation?.material_sku_snapshot ?? input.consumption?.material_sku_snapshot ?? input.material.sku, input.work.order_document_id, input.work.order_line_id, input.work.id, input.consumption?.production_attempt_id ?? null, input.reservation?.material_requirement_id ?? input.consumption?.material_requirement_id ?? null, input.reservation?.id ?? null, input.consumption?.id ?? null, input.quantity, input.unit, input.kind, input.onHandDelta, input.reservedDelta, input.operationRequestId])).rows[0];
    if (!row) throw new V2ApplicationError("CONFLICT", "Inventory movement could not be recorded.");
    if (Number(input.onHandDelta) !== 0) await this.client.query("UPDATE materials SET stock_quantity=stock_quantity+$3::numeric,updated_at=now() WHERE organization_id=$1 AND id=$2", [input.organizationId, input.material.id, input.onHandDelta]);
    await this.hooks?.afterMovement?.();
    return movement(row);
  }
  async reserveForWork(input: Parameters<InventoryLedgerTransaction["reserveForWork"]>[0]): Promise<readonly InventoryReservation[]> {
    const work = await this.work(input.organizationId, input.productionWorkId, true); const requirements = await this.requirements(input.organizationId, work); if (noRows(requirements)) return [];
    const out: InventoryReservation[] = [];
    for (const requirement of requirements) {
      if (!positive(requirement.quantity)) throw new V2ApplicationError("VALIDATION_ERROR", "Frozen material requirement quantity is invalid.");
      const existing = (await this.client.query<ReservationRow>("SELECT id,material_id,material_name_snapshot,material_sku_snapshot,opened_quantity::text,quantity_unit,material_requirement_id FROM v2_inventory_reservations WHERE organization_id=$1 AND production_work_id=$2 AND material_requirement_id=$3", [input.organizationId, work.id, requirement.id])).rows[0];
      if (existing) { out.push(Object.freeze({ reservationId: existing.id, organizationId: input.organizationId, productionWorkId: input.productionWorkId, requirementId: brandedId<"OrderLineMaterialRequirementId">(existing.material_requirement_id), materialId: existing.material_id, materialName: existing.material_name_snapshot, materialSku: existing.material_sku_snapshot, quantity: existing.opened_quantity, unit: existing.quantity_unit })); continue; }
      const material = await this.lockMaterial(input.organizationId, requirement.material_id);
      const reserved = (await this.client.query<{ quantity: string }>("SELECT COALESCE(sum(reserved_delta),0)::text quantity FROM v2_inventory_movements WHERE organization_id=$1 AND material_id=$2", [input.organizationId, material.id])).rows[0]!.quantity;
      if (Number(material.stock_quantity) - Number(reserved) < Number(requirement.quantity)) throw new V2ApplicationError("CONFLICT", `Insufficient available stock for ${material.name}.`);
      const reservation = (await this.client.query<ReservationRow>("INSERT INTO v2_inventory_reservations(organization_id,order_document_id,order_line_id,production_work_id,material_requirement_id,material_id,material_name_snapshot,material_sku_snapshot,opened_quantity,quantity_unit,operation_request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::numeric,$10,$11) RETURNING id,material_id,material_name_snapshot,material_sku_snapshot,opened_quantity::text,quantity_unit,material_requirement_id", [input.organizationId, work.order_document_id, work.order_line_id, work.id, requirement.id, material.id, requirement.material_name_snapshot, requirement.material_sku_snapshot, requirement.quantity, requirement.quantity_unit, input.operationRequestId])).rows[0]!;
      await this.recordMovement({ organizationId: input.organizationId, work, material, reservation, quantity: requirement.quantity, unit: requirement.quantity_unit, kind: "reserve", onHandDelta: "0", reservedDelta: requirement.quantity, operationRequestId: input.operationRequestId });
      out.push(Object.freeze({ reservationId: reservation.id, organizationId: input.organizationId, productionWorkId: input.productionWorkId, requirementId: brandedId<"OrderLineMaterialRequirementId">(requirement.id), materialId: material.id, materialName: requirement.material_name_snapshot, materialSku: requirement.material_sku_snapshot, quantity: requirement.quantity, unit: requirement.quantity_unit }));
    }
    return out;
  }
  async releaseUnusedForWork(input: Parameters<InventoryLedgerTransaction["releaseUnusedForWork"]>[0]): Promise<readonly InventoryMovement[]> {
    const work = await this.work(input.organizationId, input.productionWorkId, true); if (Number(work.active_attempts) > 0) throw new V2ApplicationError("CONFLICT", "Unused inventory can be released only after the active Production attempt is completed.");
    const reservations = (await this.client.query<ReservationRow>("SELECT id,material_id,material_name_snapshot,material_sku_snapshot,opened_quantity::text,quantity_unit,material_requirement_id FROM v2_inventory_reservations WHERE organization_id=$1 AND production_work_id=$2 ORDER BY material_id,id", [input.organizationId, work.id])).rows; const out: InventoryMovement[] = [];
    for (const reservation of reservations) { const remaining = await this.remainingReservation(input.organizationId, reservation.id); if (Number(remaining) <= 0) continue; const material = await this.lockMaterial(input.organizationId, reservation.material_id); out.push(await this.recordMovement({ organizationId: input.organizationId, work, material, reservation, quantity: remaining, unit: reservation.quantity_unit, kind: "release", onHandDelta: "0", reservedDelta: `-${remaining}`, operationRequestId: input.operationRequestId })); }
    return out;
  }
  async applyConsumption(input: Parameters<InventoryLedgerTransaction["applyConsumption"]>[0]): Promise<InventoryMovement> {
    const existing = (await this.client.query<MovementRow>("SELECT * FROM v2_inventory_movements WHERE organization_id=$1 AND consumption_id=$2", [input.organizationId, input.consumptionId])).rows[0]; if (existing) return movement(existing);
    const consumption = (await this.client.query<ConsumptionRow>("SELECT * FROM v2_production_material_consumptions WHERE organization_id=$1 AND id=$2", [input.organizationId, input.consumptionId])).rows[0]; if (!consumption) throw new V2ApplicationError("NOT_FOUND", "Production material consumption was not found.");
    const work = await this.work(input.organizationId, brandedId<"ProductionWorkId">(consumption.production_work_id), true); const material = await this.lockMaterial(input.organizationId, consumption.material_id);
    let reservation: ReservationRow | undefined; let reservedDelta = "0";
    if (consumption.material_requirement_id && consumption.consumption_kind !== "correction") { reservation = (await this.client.query<ReservationRow>("SELECT id,material_id,material_name_snapshot,material_sku_snapshot,opened_quantity::text,quantity_unit,material_requirement_id FROM v2_inventory_reservations WHERE organization_id=$1 AND production_work_id=$2 AND material_requirement_id=$3", [input.organizationId, work.id, consumption.material_requirement_id])).rows[0]; if (reservation) { const remaining = Number(await this.remainingReservation(input.organizationId, reservation.id)); reservedDelta = remaining > 0 ? `-${Math.min(remaining, Number(consumption.quantity))}` : "0"; } }
    const correction = consumption.consumption_kind === "correction"; const delta = correction ? consumption.quantity : `-${consumption.quantity}`;
    return this.recordMovement({ organizationId: input.organizationId, work, material, reservation, consumption, quantity: consumption.quantity, unit: consumption.quantity_unit, kind: correction ? "correction" : consumption.consumption_kind === "waste" ? "waste" : "consume", onHandDelta: delta, reservedDelta, operationRequestId: input.operationRequestId });
  }
  async recordReconciliationFailure(input: Parameters<InventoryLedgerTransaction["recordReconciliationFailure"]>[0]): Promise<void> {
    const result = await this.client.query("INSERT INTO v2_inventory_reconciliation_attempts(organization_id,consumption_id,business_request_id,status,error_code,error_message) SELECT $1::varchar,$2::varchar,$3::varchar,$4::varchar,$5::varchar,$6::varchar WHERE EXISTS(SELECT 1 FROM v2_production_material_consumptions WHERE organization_id=$1::varchar AND id=$2::varchar)", [input.organizationId, input.consumptionId, input.businessRequestId, input.status, input.errorCode, input.errorMessage.slice(0, 500)]);
    if (result.rowCount !== 1) throw new V2ApplicationError("NOT_FOUND", "Production consumption was not found for reconciliation failure recording.");
  }
  async read(organizationId: OrganizationId, productionWorkId: ProductionWorkId): Promise<InventoryReconciliation | null> {
    const work = (await this.client.query<WorkRow>("SELECT w.id,w.order_document_id,w.order_line_id,'0' active_attempts FROM v2_production_works w WHERE w.organization_id=$1 AND w.id=$2", [organizationId, productionWorkId])).rows[0]; if (!work) return null;
    const movements = (await this.client.query<MovementRow>("SELECT * FROM v2_inventory_movements WHERE organization_id=$1 AND production_work_id=$2 ORDER BY created_at,id", [organizationId, work.id])).rows;
    const ids = [...new Set(movements.map((row) => row.material_id))]; const balances: InventoryBalance[] = [];
    for (const materialId of ids) { const material = (await this.client.query<MaterialRow>("SELECT id,name,sku,stock_quantity::text,consumption_unit,inventory_unit FROM materials WHERE organization_id=$1 AND id=$2", [organizationId, materialId])).rows[0]; if (!material) continue; const sum = (await this.client.query<{ reserved: string; unit: InventoryReservation["unit"] }>("SELECT COALESCE(sum(reserved_delta),0)::text reserved,max(quantity_unit) unit FROM v2_inventory_movements WHERE organization_id=$1 AND material_id=$2", [organizationId, materialId])).rows[0]!; balances.push(Object.freeze({ materialId, materialName: material.name, materialSku: material.sku, unit: sum.unit ?? material.inventory_unit ?? material.consumption_unit ?? "each", onHandQuantity: material.stock_quantity, reservedQuantity: sum.reserved, availableQuantity: String(Number(material.stock_quantity) - Number(sum.reserved)) })); }
    const facts = (await this.client.query<ReconciliationRow>(`SELECT c.id consumption_id,c.material_id,c.material_name_snapshot,c.quantity::text,c.quantity_unit,c.consumption_kind,m.id movement_id,
      last.error_code,last.error_message,last.status failure_status,COALESCE(attempts.n,0)::text attempt_count
      FROM v2_production_material_consumptions c
      LEFT JOIN v2_inventory_movements m ON m.organization_id=c.organization_id AND m.consumption_id=c.id
      LEFT JOIN LATERAL (SELECT error_code,error_message,status FROM v2_inventory_reconciliation_attempts a WHERE a.organization_id=c.organization_id AND a.consumption_id=c.id ORDER BY created_at DESC,id DESC LIMIT 1) last ON true
      LEFT JOIN LATERAL (SELECT count(*) n FROM v2_inventory_reconciliation_attempts a WHERE a.organization_id=c.organization_id AND a.consumption_id=c.id) attempts ON true
      WHERE c.organization_id=$1 AND c.production_work_id=$2 ORDER BY c.created_at,c.id`, [organizationId, work.id])).rows;
    return Object.freeze({ productionWorkId, balances, movements: movements.map(movement), facts: facts.map((row) => Object.freeze({ consumptionId: brandedId<"ProductionMaterialConsumptionId">(row.consumption_id), materialId: row.material_id, materialName: row.material_name_snapshot, quantity: row.quantity, unit: row.quantity_unit, kind: row.consumption_kind, status: row.movement_id ? "applied" as const : row.failure_status ?? "unapplied" as const, ...(row.error_code ? { lastFailureCode: row.error_code, lastFailureMessage: row.error_message ?? undefined } : {}), attemptCount: Number(row.attempt_count) })) });
  }
}
export class PostgresInventoryLedgerTransactionRunner implements InventoryLedgerTransactionRunner { constructor(private readonly pool: Pool, private readonly hooks?: InventoryLedgerTestHooks) {} async transaction<T>(action: (tx: InventoryLedgerTransaction) => Promise<T>): Promise<T> { const client = await this.pool.connect(); try { await client.query("BEGIN"); const result = await action(new PostgresInventoryLedgerTransaction(client, this.hooks)); await client.query("COMMIT"); return result; } catch (cause) { await client.query("ROLLBACK"); throw cause; } finally { client.release(); } } }
