import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import { PostgresProductionTransactionRunner } from "../infrastructure/production/postgresProductionTransaction.js";
import { assertV2ProductionPhysicalPostconditions } from "../infrastructure/production/productionPhysicalPostconditions.js";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { ProductionApplicationService } from "../src/modules/production/productionApplication.js";
import { brandedId } from "../src/modules/shared/commercialValues.js";
import type { Capability } from "../src/authorization/capabilities.js";
const migrationsFolder=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../server/db/migrations_v2");
const staff=(organizationId:string,userId:string,id:string,capabilities:readonly Capability[]=["production.view","production.work","production.complete"])=>({organizationId,operationId:`m23:${id}`,businessRequest:{id,payloadFingerprint:"m23"},principal:{kind:"staff" as const,organizationId,userId,authority:{membershipId:`m23-${userId}`,capabilities}}});
const count=async(c:{query:Function},sql:string,v:unknown[])=>Number((await c.query<{n:string}>(sql,v)).rows[0]!.n);
async function main(){const pool=new Pool({connectionString:requireV2M0CloneDatabaseUrl(),max:8,application_name:"m23-production-rehearsal"});try{await migrate(drizzle({client:pool}),{migrationsFolder,migrationsTable:"__drizzle_migrations_v2",migrationsSchema:"public"});const c=await pool.connect();try{
 await assertV2ProductionPhysicalPostconditions(c);const x=randomUUID(),org=`m23-${x}`,other=`m23-other-${x}`,user=`m23-user-${x}`,customer=`m23-customer-${x}`,type=`m23-type-${x}`,product=`m23-product-${x}`,order=`m23-order-${x}`,quote=`m23-quote-${x}`,line=`m23-line-${x}`,productionOnlyLine=`m23-production-only-line-${x}`,quoteLine=`m23-quote-line-${x}`,file=`m23-file-${x}`,front=`m23-front-${x}`,back=`m23-back-${x}`,productionOnlyArt=`m23-production-only-art-${x}`,otherArt=`m23-other-art-${x}`,route=`m23-route-${x}`,productionOnlyRoute=`m23-production-only-route-${x}`,pre=`m23-pre-${x}`,prod=`m23-prod-${x}`,productionOnlyStep=`m23-production-only-step-${x}`,template=`m23-template-${x}`;
 await c.query("BEGIN");await c.query("INSERT INTO organizations(id,name,slug) VALUES($1,'M23',$2),($3,'Other',$4)",[org,org,other,other]);await c.query("INSERT INTO users(id,email,role) VALUES($1,$2,'owner')",[user,`${user}@test`]);await c.query("INSERT INTO customers(id,organization_id,company_name,display_name,is_active,status) VALUES($1,$2,'M23','M23',true,'active')",[customer,org]);await c.query("INSERT INTO product_types(id,organization_id,name,routing_mode) VALUES($1,$2,'M23','no_route')",[type,org]);await c.query("INSERT INTO products(id,organization_id,name,description,is_active,measurement_mode,product_type_id) VALUES($1,$2,'M23','M23',true,'quantity_only',$3)",[product,org,type]);
 for(const [id,kind] of [[order,"order"],[quote,"quote"]] as const)await c.query("INSERT INTO v2_sales_documents(id,organization_id,document_kind,business_number,display_number,customer_id,currency,terms_json) VALUES($1,$2,$3,1,$4,$5,'USD','{}')",[id,org,kind,`${kind}-${x}`,customer]);await c.query("INSERT INTO v2_sales_order_details(document_id,organization_id) VALUES($1,$2)",[order,org]);await c.query("INSERT INTO v2_sales_quote_details(document_id,organization_id) VALUES($1,$2)",[quote,org]);
 await c.query("INSERT INTO v2_sales_document_lines(id,organization_id,document_id,position,product_id,description,quantity,currency,calculated_unit_cents,calculated_line_cents,selling_unit_cents,selling_line_cents,pricing_result_id,pricing_evidence_fingerprint,resolved_configuration,pricing_result,selling_price_decision,production_requirement_state,production_requirement_fingerprint,production_requirement_count) VALUES($1,$2,$3,0,$4,'M23',100,'USD',1,100,1,100,'m23','sha256:m23','{}','{}','{}','configured',$5,2)",[line,org,order,product,`sha256:${"a".repeat(64)}`]);
 await c.query("INSERT INTO v2_sales_document_lines(id,organization_id,document_id,position,product_id,description,quantity,currency,calculated_unit_cents,calculated_line_cents,selling_unit_cents,selling_line_cents,pricing_result_id,pricing_evidence_fingerprint,resolved_configuration,pricing_result,selling_price_decision,production_requirement_state,production_requirement_fingerprint,production_requirement_count) VALUES($1,$2,$3,1,$4,'M23 production only',100,'USD',1,100,1,100,'m23','sha256:m23','{}','{}','{}','configured',$5,1)",[productionOnlyLine,org,order,product,`sha256:${"b".repeat(64)}`]);
 for(const [key,side] of [["front","front"],["back","back"]] as const)await c.query("INSERT INTO v2_sales_line_production_requirements(organization_id,document_id,order_line_id,requirement_key,side) VALUES($1,$2,$3,$4,$5)",[org,order,line,key,side]);await c.query("INSERT INTO v2_artwork_files(id,organization_id,storage_provider,object_key,original_filename,display_filename,content_type,byte_size,source_kind) VALUES($1,$2,'clone',$3,'x.pdf','x.pdf','application/pdf',1,'customer_upload')",[file,org,`m23/${x}`]);
 await c.query("INSERT INTO v2_sales_line_production_requirements(organization_id,document_id,order_line_id,requirement_key,side) VALUES($1,$2,$3,'front','front')",[org,order,productionOnlyLine]);
 for(const [id,targetLine,side,fingerprint] of [[front,line,"front","a"],[back,line,"back","b"],[otherArt,line,"front","c"],[productionOnlyArt,productionOnlyLine,"front","d"]] as const)await c.query("INSERT INTO v2_artwork_assignments(id,organization_id,artwork_file_id,order_document_id,order_line_id,purpose,side,identity_fingerprint) VALUES($1,$2,$3,$4,$5,'production',$6,$7)",[id,org,file,order,targetLine,side,`sha256:${fingerprint.repeat(64)}`]);await c.query("INSERT INTO v2_route_templates(id,organization_id,name,normalized_name,definition_fingerprint) VALUES($1,$2,'M23','m23','m23')",[template,org]);for(const [id,targetLine,current] of [[route,line,prod],[productionOnlyRoute,productionOnlyLine,productionOnlyStep]] as const)await c.query("INSERT INTO v2_route_instances(id,organization_id,order_document_id,order_line_id,source_template_id,source_template_revision,source_template_fingerprint,route_state,current_step_id) VALUES($1,$2,$3,$4,$5,1,'m23','active',$6)",[id,org,order,targetLine,template,current]);await c.query("INSERT INTO v2_route_instance_steps(id,organization_id,route_instance_id,position,step_kind) VALUES($1,$2,$3,0,'prepress'),($4,$2,$3,1,'production'),($5,$2,$6,0,'production')",[pre,org,route,prod,productionOnlyStep,productionOnlyRoute]);
 for(const [id,assignment,side] of [[`m23-pf-${x}`,front,"front"],[`m23-pb-${x}`,back,"back"],[`m23-po-${x}`,otherArt,"front"]] as const)await c.query("INSERT INTO v2_prepress_units(id,organization_id,order_document_id,order_line_id,artwork_assignment_id,artwork_file_id,side,created_principal_kind,created_principal_subject,started_at,started_principal_kind,started_principal_subject,completed_at,completed_principal_kind,completed_principal_subject) VALUES($1,$2,$3,$4,$5,$6,$7,'staff','m23',now(),'staff','m23',now(),'staff','m23')",[id,org,order,line,assignment,file,side]);await c.query("COMMIT");
 const beforeRoute=await c.query("SELECT revision,route_state,current_step_id FROM v2_route_instances WHERE id=$1",[route]);const service=new ProductionApplicationService(new PostgresProductionTransactionRunner(pool));
 assert((await service.open(staff(org,user,"production-only"),{businessRequestId:"production-only",artworkAssignmentId:brandedId<"ArtworkAssignmentId">(productionOnlyArt)})).ok,"Production-only route does not require Prepress");
 const opened=await Promise.all([service.open(staff(org,user,"front-a"),{businessRequestId:"front-a",artworkAssignmentId:brandedId<"ArtworkAssignmentId">(front)}),service.open(staff(org,user,"front-b"),{businessRequestId:"front-b",artworkAssignmentId:brandedId<"ArtworkAssignmentId">(front)})]);assert(opened.every(x=>x.ok)&&opened[0]!.ok&&opened[1]!.ok&&opened[0]!.value.work.productionWorkId===opened[1]!.value.work.productionWorkId,"concurrent work creation converges");if(!opened[0]!.ok)return;const frontWork=opened[0]!.value.work;
 const backOpen=await service.open(staff(org,user,"back"),{businessRequestId:"back",artworkAssignmentId:brandedId<"ArtworkAssignmentId">(back)});assert(backOpen.ok,"Back opens independently");assert.notEqual(backOpen.ok&&backOpen.value.work.productionWorkId,frontWork.productionWorkId,"Front and Back are distinct work identities");
 if(!backOpen.ok)return;const backWork=backOpen.value.work;
 const [flatbedNextUp,rollNextUp]=await Promise.all([service.listStationQueue(staff(org,user,"flatbed-next-up"),"flatbed"),service.listStationQueue(staff(org,user,"roll-next-up"),"roll")]);
 assert(flatbedNextUp.ok&&rollNextUp.ok&&flatbedNextUp.value.some(item=>item.work.productionWorkId===backWork.productionWorkId)&&rollNextUp.value.some(item=>item.work.productionWorkId===backWork.productionWorkId),"untouched work appears as Next up in both station projections without a persisted station");
 const competingFirstStarts=await Promise.all([
  service.start(staff(org,user,"back-flatbed-first"),{businessRequestId:"back-flatbed-first",productionWorkId:backWork.productionWorkId,stationKey:"flatbed",kind:"initial"}),
  service.start(staff(org,user,"back-roll-first"),{businessRequestId:"back-roll-first",productionWorkId:backWork.productionWorkId,stationKey:"roll",kind:"initial"}),
 ]);
 const winningFirstStarts=competingFirstStarts.filter(result=>result.ok);
 assert.equal(winningFirstStarts.length,1,"competing first station starts converge to one durable initial attempt");
 assert.equal(competingFirstStarts.filter(result=>!result.ok).length,1,"losing first station start receives a deterministic conflict");
 const backAfterFirstStart=await service.getWork(staff(org,user,"back-after-first-start"),backWork.productionWorkId);
 assert(backAfterFirstStart.ok&&backAfterFirstStart.value.attempts.length===1&&["flatbed","roll"].includes(backAfterFirstStart.value.attempts[0]!.stationKey),"first attempt is the only durable station-selection fact");
 const start=await service.start(staff(org,user,"start"),{businessRequestId:"start",productionWorkId:frontWork.productionWorkId,stationKey:"flatbed",kind:"initial"});assert(start.ok&&start.value.attempt,"attempt starts");if(!start.ok||!start.value.attempt)return;const a1=start.value.attempt;assert((await service.recordOutput(staff(org,user,"out40"),{businessRequestId:"out40",productionAttemptId:a1.productionAttemptId,goodQuantityDelta:40})).ok);assert((await service.complete(staff(org,user,"complete1"),{businessRequestId:"complete1",productionAttemptId:a1.productionAttemptId})).ok);let projection=await service.getWork(staff(org,user,"read"),frontWork.productionWorkId);assert(projection.ok&&projection.value.completedGoodQuantity===40&&!projection.value.unitQuantitySatisfied,"partial attempt does not satisfy ordered unit quantity");
 const a2=await service.start(staff(org,user,"reprint"),{businessRequestId:"reprint",productionWorkId:frontWork.productionWorkId,stationKey:"roll",kind:"reprint"});assert(a2.ok&&a2.value.attempt?.sequence===2,"reprint preserves attempt sequence/history");if(!a2.ok||!a2.value.attempt)return;await service.recordOutput(staff(org,user,"out60"),{businessRequestId:"out60",productionAttemptId:a2.value.attempt.productionAttemptId,goodQuantityDelta:60});await service.complete(staff(org,user,"complete2"),{businessRequestId:"complete2",productionAttemptId:a2.value.attempt.productionAttemptId});projection=await service.getWork(staff(org,user,"read2"),frontWork.productionWorkId);assert(projection.ok&&projection.value.completedGoodQuantity===100&&projection.value.unitQuantitySatisfied&&projection.value.attempts.length===2,"multiple completed attempts satisfy only the one unit");
 await assert.rejects(c.query("UPDATE v2_production_attempts SET good_quantity=99 WHERE organization_id=$1 AND id=$2",[org,a1.productionAttemptId]),/immutable/i);await assert.rejects(c.query("INSERT INTO v2_production_works(organization_id,order_document_id,order_line_id,requirement_key,artwork_assignment_id,artwork_file_id,ordered_quantity,created_principal_kind,created_principal_subject) VALUES($1,$2,$3,'front',$4,$5,100,'staff','bad')",[other,order,line,front,file]),/(foreign key|Production work)/i);
 const afterRoute=await c.query("SELECT revision,route_state,current_step_id FROM v2_route_instances WHERE id=$1",[route]);assert.deepEqual(afterRoute.rows,beforeRoute.rows,"Production did not mutate Routing");assert.equal(await count(c,"SELECT count(*) n FROM v2_audit_events WHERE organization_id=$1 AND event_type LIKE 'production_%'",[org])>=8,true,"Audit persists");assert.equal(await count(c,"SELECT count(*) n FROM v2_principal_attributions WHERE organization_id=$1 AND resource_type IN ('production_work','production_attempt')",[org])>=8,true,"Attribution persists");
 const wb=await count(c,"SELECT count(*) n FROM v2_production_works WHERE organization_id=$1",[org]),ab=await count(c,"SELECT count(*) n FROM v2_audit_events WHERE organization_id=$1 AND event_type='production_work_opened'",[org]);const rolled=await new ProductionApplicationService(new PostgresProductionTransactionRunner(pool,{afterWork:async()=>{throw Error("rollback");}})).open(staff(org,user,"rollback"),{businessRequestId:"rollback",artworkAssignmentId:brandedId<"ArtworkAssignmentId">(otherArt)});assert(!rolled.ok);assert.equal(await count(c,"SELECT count(*) n FROM v2_production_works WHERE organization_id=$1",[org]),wb);assert.equal(await count(c,"SELECT count(*) n FROM v2_audit_events WHERE organization_id=$1 AND event_type='production_work_opened'",[org]),ab,"rollback leaves no work/audit");const denied=await service.open(staff(org,user,"denied",[]),{businessRequestId:"denied",artworkAssignmentId:brandedId<"ArtworkAssignmentId">(back)});assert(!denied.ok,"authority denied");assert.equal(await count(c,"SELECT count(*) n FROM v2_operation_requests WHERE organization_id=$1 AND business_request_id='denied'",[org]),0,"denied mutation leaves no operation");
 console.log("[m2.3] Production PostgreSQL clone rehearsal passed (30 assertions).");
}finally{c.release();}}finally{await pool.end();}}
main().catch(error=>{console.error(`[m2.3] rehearsal failed: ${error instanceof Error?error.stack??error.message:String(error)}`);process.exitCode=1;});
