import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import { PostgresFulfillmentTransactionRunner } from "../infrastructure/fulfillment/postgresFulfillmentTransaction.js";
import { assertV2FulfillmentPhysicalPostconditions } from "../infrastructure/fulfillment/fulfillmentPhysicalPostconditions.js";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { FulfillmentApplicationService } from "../src/modules/fulfillment/fulfillmentApplication.js";
import { brandedId } from "../src/modules/shared/commercialValues.js";
import type { Capability } from "../src/authorization/capabilities.js";
const migrationsFolder=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../server/db/migrations_v2");
const caps:readonly Capability[]=["fulfillment.view","fulfillment.pickup","fulfillment.ship"];
const context=(organizationId:string,userId:string,id:string,capabilities:readonly Capability[]=caps)=>({organizationId,operationId:`m3:${id}`,businessRequest:{id,payloadFingerprint:`m3:${id}`},principal:{kind:"staff" as const,organizationId,userId,authority:{membershipId:`m3-${userId}`,capabilities}}});
const count=async(c:{query:<T>(sql:string,values?:readonly unknown[])=>Promise<{rows:T[]}>},sql:string,v:unknown[])=>Number((await c.query<{n:string}>(sql,v)).rows[0]!.n);
async function addLine(c:{query:Function},input:{id:string;org:string;order:string;product:string;position:number;quantity:number}){await c.query("INSERT INTO v2_sales_document_lines(id,organization_id,document_id,position,product_id,description,quantity,currency,calculated_unit_cents,calculated_line_cents,selling_unit_cents,selling_line_cents,pricing_result_id,pricing_evidence_fingerprint,resolved_configuration,pricing_result,selling_price_decision,production_requirement_state,production_requirement_fingerprint,production_requirement_count) VALUES($1,$2,$3,$4,$5,'M3 item',$6,'USD',1,$7,1,$8,'m3','sha256:m3','{}','{}','{}','configured',$9,1)",[input.id,input.org,input.order,input.position,input.product,input.quantity,input.quantity,input.quantity,`sha256:${"a".repeat(64)}`]);}
async function completeProduction(c:{query:Function},input:{id:string;org:string;order:string;user:string;quantity:number}){const requirement=`${input.id}-requirement`,file=`${input.id}-file`,assignment=`${input.id}-assignment`,work=`${input.id}-work`,attempt=`${input.id}-attempt`;await c.query("INSERT INTO v2_sales_line_production_requirements(organization_id,document_id,order_line_id,requirement_key,side) VALUES($1,$2,$3,'front','front')",[input.org,input.order,input.id]);await c.query("INSERT INTO v2_artwork_files(id,organization_id,storage_provider,object_key,original_filename,display_filename,content_type,byte_size,source_kind) VALUES($1,$2,'clone',$3,'m3.pdf','m3.pdf','application/pdf',1,'customer_upload')",[file,input.org,`m3/${file}`]);await c.query("INSERT INTO v2_artwork_assignments(id,organization_id,artwork_file_id,order_document_id,order_line_id,purpose,side,identity_fingerprint) VALUES($1,$2,$3,$4,$5,'production','front',$6)",[assignment,input.org,file,input.order,input.id,`sha256:${"b".repeat(64)}`]);await c.query("INSERT INTO v2_production_works(id,organization_id,order_document_id,order_line_id,requirement_key,artwork_assignment_id,artwork_file_id,side,ordered_quantity,created_principal_kind,created_principal_subject,created_staff_actor_user_id) VALUES($1,$2,$3,$4,'front',$5,$6,'front',$7,'staff',$8,$9)",[work,input.org,input.order,input.id,assignment,file,input.quantity,input.user,input.user]);await c.query("INSERT INTO v2_production_attempts(id,organization_id,production_work_id,sequence,attempt_kind,station_key,good_quantity,started_principal_kind,started_principal_subject,started_staff_actor_user_id,completed_at,completed_principal_kind,completed_principal_subject,completed_staff_actor_user_id) VALUES($1,$2,$3,1,'initial','flatbed',$4,'staff',$5,$6,now(),'staff',$5,$6)",[attempt,input.org,work,input.quantity,input.user,input.user]);}
async function main(){const pool=new Pool({connectionString:requireV2M0CloneDatabaseUrl(),max:8,application_name:"m3-fulfillment-rehearsal"});try{await migrate(drizzle({client:pool}),{migrationsFolder,migrationsTable:"__drizzle_migrations_v2",migrationsSchema:"public"});const c=await pool.connect();try{
 await assertV2FulfillmentPhysicalPostconditions(c);const x=randomUUID(),org=`m3-${x}`,other=`m3-other-${x}`,user=`m3-user-${x}`,customer=`m3-customer-${x}`,type=`m3-type-${x}`,product=`m3-product-${x}`,order=`m3-order-${x}`,cancelOrder=`m3-cancel-order-${x}`;
 const line=`m3-line-${x}`,lineB=`m3-line-b-${x}`,raceLine=`m3-race-${x}`,rollbackLine=`m3-rollback-${x}`,cancelLine=`m3-cancel-line-${x}`;
 await c.query("BEGIN");await c.query("INSERT INTO organizations(id,name,slug) VALUES($1,'M3',$2),($3,'M3 Other',$4)",[org,org,other,other]);await c.query("INSERT INTO users(id,email,role) VALUES($1,$2,'owner')",[user,`${user}@test`]);await c.query("INSERT INTO customers(id,organization_id,company_name,display_name,is_active,status) VALUES($1,$2,'M3','M3',true,'active')",[customer,org]);await c.query("INSERT INTO product_types(id,organization_id,name,routing_mode) VALUES($1,$2,'M3','no_route')",[type,org]);await c.query("INSERT INTO products(id,organization_id,name,description,is_active,measurement_mode,product_type_id) VALUES($1,$2,'M3','M3',true,'quantity_only',$3)",[product,org,type]);
 for(const [id,businessNumber] of [[order,1],[cancelOrder,2]] as const){await c.query("INSERT INTO v2_sales_documents(id,organization_id,document_kind,business_number,display_number,customer_id,currency,terms_json) VALUES($1,$2,'order',$3,$4,$5,'USD','{}')",[id,org,businessNumber,`${id}-display`,customer]);await c.query("INSERT INTO v2_sales_order_details(document_id,organization_id) VALUES($1,$2)",[id,org]);}
 await addLine(c,{id:line,org,order,product,position:0,quantity:100});await addLine(c,{id:lineB,org,order,product,position:1,quantity:100});await addLine(c,{id:raceLine,org,order,product,position:2,quantity:100});await addLine(c,{id:rollbackLine,org,order,product,position:3,quantity:100});await addLine(c,{id:cancelLine,org,order:cancelOrder,product,position:0,quantity:100});await completeProduction(c,{id:line,org,order,user,quantity:100});await completeProduction(c,{id:lineB,org,order,user,quantity:100});await completeProduction(c,{id:raceLine,org,order,user,quantity:100});await completeProduction(c,{id:rollbackLine,org,order,user,quantity:100});await completeProduction(c,{id:cancelLine,org,order:cancelOrder,user,quantity:100});await c.query("COMMIT");
 const service=new FulfillmentApplicationService(new PostgresFulfillmentTransactionRunner(pool));const orderId=brandedId<"OrderId">(order);
 const pickup20=await service.recordPickup(context(org,user,"pickup-20"),{businessRequestId:"pickup-20",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(line),quantity:20}]});assert(pickup20.ok,"simple partial pickup completes only against completed Production output");
 const pickup30=await service.recordPickup(context(org,user,"pickup-30"),{businessRequestId:"pickup-30",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(line),quantity:30}]});assert(pickup30.ok&&pickup20.ok&&pickup30.value.handoff.handoffId!==pickup20.value.handoff.handoffId,"repeated pickup is a second immutable handoff");
 assert((await service.recordShipment(context(org,user,"ship-25"),{businessRequestId:"ship-25",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(line),quantity:25}]})).ok,"partial shipment completes");assert((await service.recordShipment(context(org,user,"ship-final"),{businessRequestId:"ship-final",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(line),quantity:25}]})).ok,"multiple shipment completes exact quantity");
 let availability=await service.getAvailability(context(org,user,"availability"),orderId);assert(availability.ok&&availability.value.find(x=>x.orderLineId===line)?.completedPickupQuantity===50&&availability.value.find(x=>x.orderLineId===line)?.completedShipmentQuantity===50&&availability.value.find(x=>x.orderLineId===line)?.remainingFulfillmentQuantity===0,"mixed fulfillment derives correct line availability");
 assert(!(await service.recordPickup(context(org,user,"over"),{businessRequestId:"over",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(line),quantity:1}]})).ok,"over-fulfillment is rejected");
 const idemInput={businessRequestId:"idem",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(lineB),quantity:25}]};const idem1=await service.recordPickup(context(org,user,"idem"),idemInput),idem2=await service.recordPickup(context(org,user,"idem"),idemInput);assert(idem1.ok&&idem2.ok&&idem1.value.handoff.handoffId===idem2.value.handoff.handoffId,"same request replays rather than duplicating history");assert(!(await service.recordPickup(context(org,user,"idem"),{...idemInput,allocations:[{orderLineId:brandedId<"OrderLineId">(lineB),quantity:26}]})).ok,"conflicting idempotency payload is rejected");
 const race=await Promise.all([service.recordPickup(context(org,user,"race-pickup"),{businessRequestId:"race-pickup",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(raceLine),quantity:60}]}),service.recordShipment(context(org,user,"race-shipment"),{businessRequestId:"race-shipment",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(raceLine),quantity:60}]})]);assert.equal(race.filter(x=>x.ok).length,1,"concurrent pickup-vs-shipment cannot over-fulfill");availability=await service.getAvailability(context(org,user,"race-read"),orderId);assert(availability.ok&&(availability.value.find(x=>x.orderLineId===raceLine)?.completedFulfillmentQuantity??101)<=100,"concurrent durable total never exceeds ordered quantity");
 const cancelledPickup=await service.recordPickup(context(org,user,"cancel-before"),{businessRequestId:"cancel-before",orderId:brandedId<"OrderId">(cancelOrder),allocations:[{orderLineId:brandedId<"OrderLineId">(cancelLine),quantity:30}]});assert(cancelledPickup.ok,"pre-cancellation handoff completes");await c.query("UPDATE v2_sales_order_details SET commercial_state='cancelled',cancelled_at=now(),cancellation_reason='M3 test' WHERE organization_id=$1 AND document_id=$2",[org,cancelOrder]);const cancelledAvailability=await service.getAvailability(context(org,user,"cancel-read"),brandedId<"OrderId">(cancelOrder));assert(cancelledAvailability.ok&&cancelledAvailability.value[0]?.completedFulfillmentQuantity===30,"cancellation retains historical handoff quantity");assert(!(await service.recordShipment(context(org,user,"cancel-after"),{businessRequestId:"cancel-after",orderId:brandedId<"OrderId">(cancelOrder),allocations:[{orderLineId:brandedId<"OrderLineId">(cancelLine),quantity:1}]})).ok,"new cancelled-order fulfillment is blocked");
 const before=await count(c,"SELECT count(*) n FROM v2_fulfillment_handoffs WHERE organization_id=$1",[org]);for(const [requestId,hooks] of [["rollback-header",{afterHandoff:async()=>{throw Error("header rollback");}}],["rollback-allocation",{afterAllocation:async()=>{throw Error("allocation rollback");}}],["rollback-audit",{afterAudit:async()=>{throw Error("audit rollback");}}]] as const){const rollback=new FulfillmentApplicationService(new PostgresFulfillmentTransactionRunner(pool,hooks));assert(!(await rollback.recordPickup(context(org,user,requestId),{businessRequestId:requestId,orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(rollbackLine),quantity:10}]})).ok,`${requestId} injected failure returns a failure`);}assert.equal(await count(c,"SELECT count(*) n FROM v2_fulfillment_handoffs WHERE organization_id=$1",[org]),before,"rollback leaves no orphan header");assert.equal(await count(c,"SELECT count(*) n FROM v2_fulfillment_handoff_lines WHERE organization_id=$1 AND order_line_id=$2",[org,rollbackLine]),0,"rollback leaves no partial allocation");assert.equal(await count(c,"SELECT count(*) n FROM v2_operation_requests WHERE organization_id=$1 AND business_request_id LIKE 'rollback-%'",[org]),0,"rollback leaves no completed idempotency record");assert.equal(await count(c,"SELECT count(*) n FROM v2_audit_events WHERE organization_id=$1 AND resource_id LIKE 'rollback-%'",[org]),0,"rollback leaves no misleading Audit record");
 await assert.rejects(c.query("UPDATE v2_fulfillment_handoffs SET handoff_method='shipment' WHERE id=(SELECT id FROM v2_fulfillment_handoffs WHERE organization_id=$1 LIMIT 1)",[org]),/immutable/i);await assert.rejects(c.query("DELETE FROM v2_fulfillment_handoff_lines WHERE id=(SELECT id FROM v2_fulfillment_handoff_lines WHERE organization_id=$1 LIMIT 1)",[org]),/immutable/i);assert(!(await service.recordPickup(context(other,user,"tenant"),{businessRequestId:"tenant",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(lineB),quantity:1}]})).ok,"cross-tenant order access is rejected");assert(!(await service.recordPickup(context(org,user,"denied",[]),{businessRequestId:"denied",orderId,allocations:[{orderLineId:brandedId<"OrderLineId">(lineB),quantity:1}]})).ok,"unauthorized mutation is rejected");assert.equal(await count(c,"SELECT count(*) n FROM v2_production_works WHERE organization_id=$1",[org]),5,"Fulfillment consumes Production output but never creates or mutates it");assert((await count(c,"SELECT count(*) n FROM v2_audit_events WHERE organization_id=$1 AND event_type LIKE 'fulfillment_%'",[org]))>=6,"shared Audit retains terminal handoff facts");assert((await count(c,"SELECT count(*) n FROM v2_principal_attributions WHERE organization_id=$1 AND resource_type='fulfillment_handoff'",[org]))>=6,"principal attribution remains truthful");console.log("[m6] Fulfillment PostgreSQL clone rehearsal passed (31 assertions).");
 }finally{c.release();}}finally{await pool.end();}}
main().catch(error=>{console.error(`[m3.1] rehearsal failed: ${error instanceof Error?error.stack??error.message:String(error)}`);process.exitCode=1;});
