import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import { PostgresBillingReadRunner } from "../infrastructure/billing/postgresBillingRead.js";
import { PostgresBillingInvoiceTransactionRunner, type BillingInvoicePersistenceTestHooks } from "../infrastructure/billing/postgresBillingInvoiceTransaction.js";
import { assertV2BillingPhysicalPostconditions, checkV2BillingPhysicalPostconditions } from "../infrastructure/billing/billingPhysicalPostconditions.js";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { BillingApplicationService } from "../src/modules/billing/billingApplication.js";
import { brandedId } from "../src/modules/shared/commercialValues.js";
const folder=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../server/db/migrations_v2");
const assertOk=(value:unknown,message:string):asserts value=>assert(value,message);
const context=(org:string,user:string,id:string,caps:readonly string[]=["invoice.view","invoice.issue"])=>({organizationId:org,operationId:`m3-billing:${id}`,businessRequest:{id,payloadFingerprint:`m3-billing:${id}`},principal:{kind:"staff" as const,organizationId:org,userId:user,authority:{membershipId:`m3-billing-${user}`,capabilities:caps as any}}});
const count=async(c:any,sql:string,args:unknown[])=>Number((await c.query<{n:string}>(sql,args)).rows[0]!.n);
async function seed(c:any,input:{org:string;customer:string;product:string;order:string;invoice:string;line:string;number:number;quantity:number;unit:number}){await c.query("INSERT INTO v2_sales_documents(id,organization_id,document_kind,business_number,display_number,customer_id,currency,terms_json) VALUES($1,$2,'order',$3,$4,$5,'USD','{}')",[input.order,input.org,input.number,`ORD-${input.number}`,input.customer]);await c.query("INSERT INTO v2_sales_order_details(document_id,organization_id) VALUES($1,$2)",[input.order,input.org]);await c.query("INSERT INTO v2_sales_document_lines(id,organization_id,document_id,position,product_id,description,quantity,currency,calculated_unit_cents,calculated_line_cents,selling_unit_cents,selling_line_cents,pricing_result_id,pricing_evidence_fingerprint,resolved_configuration,pricing_result,selling_price_decision) VALUES($1,$2,$3,0,$4,'Invoice fixture',$5,'USD',$6,$7,$6,$7,'fixture-price','sha256:fixture','{}','{}','{}')",[input.line,input.org,input.order,input.product,input.quantity,input.unit,input.quantity*input.unit]);await c.query("INSERT INTO v2_billing_invoices(id,organization_id,sales_order_document_id,invoice_state,customer_id,currency,source_sales_state_token,subtotal_cents,tax_total_cents,total_cents,tax_calculator_version,tax_evidence) VALUES($1,$2,$3,'draft',$4,'USD','1',$5,0,$5,'zero-tax','{}')",[input.invoice,input.org,input.order,input.customer,input.quantity*input.unit]);await c.query("INSERT INTO v2_billing_invoice_lines(id,organization_id,invoice_id,sales_order_document_id,source_sales_line_id,position,product_id,description,quantity,currency,selling_unit_cents,selling_line_cents,sales_pricing_evidence_fingerprint) VALUES($1,$2,$3,$4,$5,0,$6,'Invoice fixture',$7,'USD',$8,$9,'sha256:fixture')",[randomUUID(),input.org,input.invoice,input.order,input.line,input.product,input.quantity,input.unit,input.quantity*input.unit]);}
async function main(){const pool=new Pool({connectionString:requireV2M0CloneDatabaseUrl(),max:8,application_name:"m3-billing-rehearsal"});try{await migrate(drizzle({client:pool}),{migrationsFolder:folder,migrationsTable:"__drizzle_migrations_v2",migrationsSchema:"public"});const c=await pool.connect();try{assertV2BillingPhysicalPostconditions(await checkV2BillingPhysicalPostconditions(c));const x=randomUUID(),org=`m3-billing-${x}`,other=`m3-billing-other-${x}`,user=`m3-billing-user-${x}`,customer=`m3-billing-customer-${x}`,product=`m3-billing-product-${x}`,type=`m3-billing-type-${x}`;const ids=[1,2,3,4,5].map(n=>({order:`m3-billing-order-${n}-${x}`,invoice:`m3-billing-invoice-${n}-${x}`,line:`m3-billing-line-${n}-${x}`}));await c.query("BEGIN");await c.query("INSERT INTO organizations(id,name,slug) VALUES($1,'Billing',$1),($2,'Billing Other',$2)",[org,other]);await c.query("INSERT INTO users(id,email,role) VALUES($1,$2,'owner')",[user,`${user}@test`]);await c.query("INSERT INTO customers(id,organization_id,company_name,display_name,is_active,status) VALUES($1,$2,'Billing Customer','Billing Customer',true,'active')",[customer,org]);await c.query("INSERT INTO product_types(id,organization_id,name,routing_mode) VALUES($1,$2,'Billing Type','no_route')",[type,org]);await c.query("INSERT INTO products(id,organization_id,name,description,is_active,measurement_mode,product_type_id) VALUES($1,$2,'Billing Product','Billing Product',true,'quantity_only',$3)",[product,org,type]);for(const [index,id] of ids.entries())await seed(c,{org,customer,product,...id,number:index+1,quantity:index===0?100:10,unit:index===0?1234:100});await c.query("COMMIT");
const service=new BillingApplicationService(new PostgresBillingReadRunner(pool),undefined,new PostgresBillingInvoiceTransactionRunner(pool));const first=ids[0]!;const issueId=`issue-${x}`,issue=await service.issueInvoice(context(org,user,issueId),{organizationId:brandedId<"OrganizationId">(org),invoiceId:brandedId<"InvoiceId">(first.invoice),businessRequestId:brandedId<"BusinessRequestId">(issueId)});assertOk(issue.ok,"Draft Invoice issuance succeeds");assert.equal(issue.value.invoice.lifecycle,"issued","canonical existing Invoice transitioned to issued");assert.equal(issue.value.invoice.total.cents,123400,"issued total preserves exact integer cents");assert.equal(issue.value.checkpoint.lines[0]?.quantity,100,"issued checkpoint preserves line quantity");assert.equal(issue.value.checkpoint.lines[0]?.unitAmount.cents,1234,"issued checkpoint preserves line unit price");assert.equal(issue.value.checkpoint.commercial.taxTotal.cents,0,"issued checkpoint preserves tax snapshot");assert.equal(issue.value.boundary.silentOrderSynchronization,false,"issued boundary disables silent Sales synchronization");
const replay=await service.issueInvoice(context(org,user,issueId),{organizationId:brandedId<"OrganizationId">(org),invoiceId:brandedId<"InvoiceId">(first.invoice),businessRequestId:brandedId<"BusinessRequestId">(issueId)});assertOk(replay.ok,"same issuance request replays");assert.equal(replay.value.checkpoint.checkpointId,issue.value.checkpoint.checkpointId,"same request does not create a second checkpoint");assert(!(await service.issueInvoice(context(org,user,issueId),{organizationId:brandedId<"OrganizationId">(org),invoiceId:brandedId<"InvoiceId">(ids[1]!.invoice),businessRequestId:brandedId<"BusinessRequestId">(issueId)})).ok,"conflicting protected issuance identity is rejected");
assert.equal(await count(c,"SELECT count(*) n FROM v2_billing_invoice_checkpoints WHERE organization_id=$1 AND invoice_id=$2",[org,first.invoice]),1,"one issued checkpoint exists");assert.equal(await count(c,"SELECT count(*) n FROM v2_audit_events WHERE organization_id=$1 AND resource_id=$2 AND event_type='invoice_issued'",[org,first.invoice]),1,"one truthful issue Audit exists");assert.equal(await count(c,"SELECT count(*) n FROM v2_outbox_messages WHERE organization_id=$1 AND aggregate_id=$2 AND event_type='billing.invoice.issued.v1'",[org,first.invoice]),1,"one durable downstream issuance signal exists");assert.equal(await count(c,"SELECT count(*) n FROM v2_principal_attributions WHERE organization_id=$1 AND resource_id=$2 AND resource_type='invoice'",[org,first.invoice]),1,"issuance attribution is recorded");
await assert.rejects(c.query("UPDATE v2_billing_invoices SET total_cents=1 WHERE organization_id=$1 AND id=$2",[org,first.invoice]),/immutable/i);await assert.rejects(c.query("UPDATE v2_billing_invoice_lines SET quantity=1 WHERE organization_id=$1 AND invoice_id=$2",[org,first.invoice]),/immutable/i);await assert.rejects(c.query("UPDATE v2_billing_invoice_checkpoints SET checkpoint_json='{}'::jsonb WHERE organization_id=$1 AND invoice_id=$2",[org,first.invoice]),/immutable/i);assert.equal(await count(c,"SELECT count(*) n FROM v2_fulfillment_handoffs WHERE organization_id=$1",[org]),0,"Billing issuance does not mutate Fulfillment");
const race=ids[1]!,raceResults=await Promise.all(["a","b"].map(label=>service.issueInvoice(context(org,user,`race-${label}-${x}`),{organizationId:brandedId<"OrganizationId">(org),invoiceId:brandedId<"InvoiceId">(race.invoice),businessRequestId:brandedId<"BusinessRequestId">(`race-${label}-${x}`)})));assert.equal(raceResults.filter(result=>result.ok).length,1,"concurrent issuance yields one transition");assert.equal(await count(c,"SELECT count(*) n FROM v2_billing_invoice_checkpoints WHERE organization_id=$1 AND invoice_id=$2",[org,race.invoice]),1,"concurrent issuance creates one checkpoint");
const denied=await service.issueInvoice(context(org,user,`denied-${x}`,[]),{organizationId:brandedId<"OrganizationId">(org),invoiceId:brandedId<"InvoiceId">(ids[2]!.invoice),businessRequestId:brandedId<"BusinessRequestId">(`denied-${x}`)});assert(!denied.ok&&denied.error.code==="FORBIDDEN","authority is required for issuance");const foreign=await service.issueInvoice(context(other,user,`foreign-${x}`),{organizationId:brandedId<"OrganizationId">(other),invoiceId:brandedId<"InvoiceId">(ids[2]!.invoice),businessRequestId:brandedId<"BusinessRequestId">(`foreign-${x}`)});assert(!foreign.ok,"cross-tenant issuance is rejected");
for(const [name,hooks] of [["issue",{afterIssue:async()=>{throw Error("issue rollback");}}],["checkpoint",{afterCheckpoint:async()=>{throw Error("checkpoint rollback");}}],["outbox",{afterOutbox:async()=>{throw Error("outbox rollback");}}],["audit",{afterAudit:async()=>{throw Error("audit rollback");}}]] as const){const target=ids[3]!,id=`rollback-${name}-${x}`,before=await count(c,"SELECT count(*) n FROM v2_operation_requests WHERE organization_id=$1",[org]);const result=await new BillingApplicationService(new PostgresBillingReadRunner(pool),undefined,new PostgresBillingInvoiceTransactionRunner(pool,hooks as BillingInvoicePersistenceTestHooks)).issueInvoice(context(org,user,id),{organizationId:brandedId<"OrganizationId">(org),invoiceId:brandedId<"InvoiceId">(target.invoice),businessRequestId:brandedId<"BusinessRequestId">(id)});assert(!result.ok,`${name} failure rolls back issuance`);assert.equal(await count(c,"SELECT count(*) n FROM v2_billing_invoices WHERE organization_id=$1 AND id=$2 AND invoice_state='issued'",[org,target.invoice]),0,`${name} leaves no phantom issued invoice`);assert.equal(await count(c,"SELECT count(*) n FROM v2_operation_requests WHERE organization_id=$1",[org]),before,`${name} leaves no idempotency residue`);}
console.log("[m3.3] Billing Invoice PostgreSQL clone rehearsal passed (25 assertions).");}finally{c.release();}}finally{await pool.end();}}
main().catch(error=>{console.error(`[m3.3] rehearsal failed: ${error instanceof Error?error.stack??error.message:String(error)}`);process.exitCode=1;});
