import { randomUUID } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool, type PoolClient } from "pg";
import request from "supertest";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { assertV2M0PhysicalPostconditions, checkV2M0PhysicalPostconditions } from "../infrastructure/persistence/physicalPostconditions.js";
import { assertV2CommercialPhysicalPostconditions, checkV2CommercialPhysicalPostconditions } from "../infrastructure/sales/commercialPhysicalPostconditions.js";
import { PostgresQuoteTransactionRunner } from "../infrastructure/sales/postgresQuoteTransaction.js";
import { PostgresOrderTransactionRunner } from "../infrastructure/sales/postgresOrderTransaction.js";
import { PostgresQuoteConversionTransactionRunner } from "../infrastructure/sales/postgresQuoteConversionTransaction.js";
import { PostgresPermissionAuthorityReader } from "../infrastructure/authorization/postgresPermissionAuthorityRead.js";
import { PermissionSetPrincipalIssuer } from "../src/authorization/permissionSets.js";
import { QuoteApplicationService } from "../src/modules/sales/quoteApplication.js";
import { QuoteConversionApplicationService } from "../src/modules/sales/quoteConversionApplication.js";
import { OrderApplicationService } from "../src/modules/sales/orderApplication.js";
import { brandedId } from "../src/modules/shared/commercialValues.js";
import { PassportSessionIdentitySource } from "../infrastructure/authentication/trustedHostPrincipalProvider.js";
import { composeAuthenticatedQuoteRuntime } from "../infrastructure/sales/authenticatedQuoteRuntime.js";
import { createV2HttpApp } from "../src/interfaces/http/app.js";
import { loadV2RuntimeConfig } from "../src/config/runtimeConfig.js";

const migrationsFolder = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../server/db/migrations_v2");
const assert = (value: unknown, message: string): asserts value => { if (!value) throw new Error(message); };
const ctx = (principal: any, organizationId: string, id: string) => ({ principal, organizationId, operationId: `m110:${id}`, businessRequest: { id, payloadFingerprint: "operation-computes-canonical-fingerprint" } });

async function fixture(client: PoolClient) {
  const x=randomUUID(), org=`m110-org-${x}`, other=`m110-other-${x}`, user=`m110-user-${x}`, limited=`m110-limited-${x}`, foreignUser=`m110-foreign-${x}`, customer=`m110-customer-${x}`, contact=`m110-contact-${x}`, foreignCustomer=`m110-foreign-customer-${x}`, foreignContact=`m110-foreign-contact-${x}`, type=`m110-type-${x}`, serviceType=`m110-service-type-${x}`, foreignType=`m110-foreign-type-${x}`, product=`m110-product-${x}`, serviceProduct=`m110-service-product-${x}`, foreignProduct=`m110-foreign-product-${x}`, template=`m110-template-${x}`, tree=`m110-tree-${x}`, serviceTree=`m110-service-tree-${x}`, foreignTree=`m110-foreign-tree-${x}`, set=`m110-set-${x}`, limitedSet=`m110-limited-set-${x}`, foreignSet=`m110-foreign-set-${x}`;
  await client.query("BEGIN"); try {
    await client.query("INSERT INTO organizations(id,name,slug) VALUES($1,'M110',$2),($3,'Other',$4)",[org,`m110-${x}`,other,`m110-other-${x}`]);
    await client.query("INSERT INTO users(id,email,role) VALUES($1,$2,'owner'),($3,$4,'member'),($5,$6,'owner')",[user,`${user}@test`,limited,`${limited}@test`,foreignUser,`${foreignUser}@test`]);
    await client.query("INSERT INTO user_organizations(user_id,organization_id,role,is_active) VALUES($1,$3,'owner',true),($2,$3,'member',true),($4,$5,'owner',true)",[user,limited,org,foreignUser,other]);
    await client.query("INSERT INTO v2_permission_organization_state(organization_id) VALUES($1),($2)",[org,other]);
    await client.query("INSERT INTO v2_permission_sets(id,organization_id,name,normalized_name,principal_kind) VALUES($1,$4,'Conversion','conversion','staff'),($2,$4,'Limited','limited','staff'),($3,$5,'Foreign','foreign','staff')",[set,limitedSet,foreignSet,org,other]);
    for (const cap of ["quote.view","quote.create","quote.edit","quote.send","quote.convert","order.view","order.edit"]) await client.query("INSERT INTO v2_permission_set_capabilities(organization_id,permission_set_id,capability_id) VALUES($1,$2,$3)",[org,set,cap]);
    for (const cap of ["quote.view","quote.create","quote.edit","quote.send"]) await client.query("INSERT INTO v2_permission_set_capabilities(organization_id,permission_set_id,capability_id) VALUES($1,$2,$3)",[org,limitedSet,cap]);
    for (const cap of ["quote.view","quote.create","quote.edit","quote.send","quote.convert","order.view"]) await client.query("INSERT INTO v2_permission_set_capabilities(organization_id,permission_set_id,capability_id) VALUES($1,$2,$3)",[other,foreignSet,cap]);
    await client.query("INSERT INTO v2_staff_permission_set_assignments(organization_id,user_id,permission_set_id) VALUES($1,$2,$3),($1,$4,$5),($6,$7,$8)",[org,user,set,limited,limitedSet,other,foreignUser,foreignSet]);
    await client.query("INSERT INTO customers(id,organization_id,company_name,display_name,is_active,status) VALUES($1,$2,'Customer','Customer',true,'active')",[customer,org]);
    await client.query("INSERT INTO customer_contacts(id,organization_id,first_name,last_name,status) VALUES($1,$2,'C','One','active')",[contact,org]);
    await client.query("INSERT INTO customer_contact_links(organization_id,customer_id,contact_id,status) VALUES($1,$2,$3,'active')",[org,customer,contact]);
    await client.query("INSERT INTO customers(id,organization_id,company_name,display_name,is_active,status) VALUES($1,$2,'Foreign Customer','Foreign Customer',true,'active')",[foreignCustomer,other]);
    await client.query("INSERT INTO customer_contacts(id,organization_id,first_name,last_name,status) VALUES($1,$2,'Foreign','Contact','active')",[foreignContact,other]);
    await client.query("INSERT INTO customer_contact_links(organization_id,customer_id,contact_id,status) VALUES($1,$2,$3,'active')",[other,foreignCustomer,foreignContact]);
    await client.query("INSERT INTO v2_route_templates(id,organization_id,name,normalized_name,definition_fingerprint) VALUES($1,$2,'Printed','printed','sha256:m110')",[template,org]);
    for (const [position,kind] of ["proofing","prepress","production","fulfillment"].entries()) await client.query("INSERT INTO v2_route_template_steps(id,organization_id,route_template_id,position,step_kind) VALUES($1,$2,$3,$4,$5)",[randomUUID(),org,template,position,kind]);
    await client.query("INSERT INTO product_types(id,organization_id,name,routing_mode,default_route_template_id) VALUES($1,$2,'Printed','route_required',$3)",[type,org,template]);
    await client.query("INSERT INTO product_types(id,organization_id,name,routing_mode) VALUES($1,$2,'Service','no_route')",[serviceType,org]);
    const treeJson={schemaVersion:2,rootNodeIds:["finish"],nodes:{finish:{id:"finish",kind:"question",label:"Finish",input:{type:"select",selectionKey:"finish",defaultValue:"standard"},choices:[{value:"standard",label:"Standard"},{value:"premium",label:"Premium",priceDeltaCents:100}]}},meta:{pricingV2:{base:{perPieceCents:1000}}}};
    await client.query("INSERT INTO products(id,organization_id,name,description,is_active,measurement_mode,product_type_id) VALUES($1,$2,'Product','Product',true,'quantity_only',$3)",[product,org,type]);
    await client.query("INSERT INTO pbv2_tree_versions(id,organization_id,product_id,status,schema_version,tree_json,published_at) VALUES($1,$2,$3,'ACTIVE',2,$4::jsonb,now())",[tree,org,product,JSON.stringify(treeJson)]);
    await client.query("UPDATE products SET pbv2_active_tree_version_id=$1 WHERE id=$2 AND organization_id=$3",[tree,product,org]);
    const serviceJson={...treeJson,meta:{pricingV2:{base:{perPieceCents:250}}}};
    await client.query("INSERT INTO products(id,organization_id,name,description,is_active,measurement_mode,product_type_id) VALUES($1,$2,'Service','Service',true,'quantity_only',$3)",[serviceProduct,org,serviceType]);
    await client.query("INSERT INTO pbv2_tree_versions(id,organization_id,product_id,status,schema_version,tree_json,published_at) VALUES($1,$2,$3,'ACTIVE',2,$4::jsonb,now())",[serviceTree,org,serviceProduct,JSON.stringify(serviceJson)]);
    await client.query("UPDATE products SET pbv2_active_tree_version_id=$1 WHERE id=$2 AND organization_id=$3",[serviceTree,serviceProduct,org]);
    await client.query("INSERT INTO product_types(id,organization_id,name,routing_mode) VALUES($1,$2,'Foreign Service','no_route')",[foreignType,other]);
    await client.query("INSERT INTO products(id,organization_id,name,description,is_active,measurement_mode,product_type_id) VALUES($1,$2,'Foreign Product','Foreign Product',true,'quantity_only',$3)",[foreignProduct,other,foreignType]);
    await client.query("INSERT INTO pbv2_tree_versions(id,organization_id,product_id,status,schema_version,tree_json,published_at) VALUES($1,$2,$3,'ACTIVE',2,$4::jsonb,now())",[foreignTree,other,foreignProduct,JSON.stringify(serviceJson)]);
    await client.query("UPDATE products SET pbv2_active_tree_version_id=$1 WHERE id=$2 AND organization_id=$3",[foreignTree,foreignProduct,other]); await client.query("COMMIT");
  } catch(e) { await client.query("ROLLBACK"); throw e; }
  return {org,other,user,limited,foreignUser,customer,contact,foreignCustomer,foreignContact,type,product,tree,serviceType,serviceProduct,serviceTree,foreignType,foreignProduct,foreignTree};
}
const acceptedQuote = async (quote: QuoteApplicationService, staff: any, f: any, ref: any, label: string) => {
  const createId=`m110-${label}-create-${randomUUID()}`; const created=await quote.create(ctx(staff,f.org,createId),{businessRequestId:createId,customerContact:ref,purchaseOrderNumber:`PO-${label}`,lines:[{productId:f.product,quantity:2,selections:{finish:"premium"}}]}); assert(created.ok,`${label} create failed`); if(!created.ok) throw new Error();
  const sendId=`m110-${label}-send-${randomUUID()}`; const sent=await quote.recordDelivered(ctx(staff,f.org,sendId),{businessRequestId:sendId,quoteId:created.value.quote.quote.quoteId,expectedRevision:created.value.quote.revision,deliveryAttemptId:`fixture-${sendId}`,providerMessageId:`fixture-${sendId}`}); assert(sent.ok&&sent.value.checkpointId,`${label} send failed`); if(!sent.ok||!sent.value.checkpointId) throw new Error();
  const acceptId=`m110-${label}-accept-${randomUUID()}`; const accepted=await quote.accept(ctx(staff,f.org,acceptId),{businessRequestId:acceptId,quoteId:created.value.quote.quote.quoteId,expectedRevision:sent.value.quote.revision}); assert(accepted.ok&&accepted.value.checkpointId,`${label} accept failed`); if(!accepted.ok||!accepted.value.checkpointId) throw new Error();
  return {created,sent,accepted,quoteId:created.value.quote.quote.quoteId,sentCheckpointId:sent.value.checkpointId,acceptedCheckpointId:accepted.value.checkpointId};
};
const counts = async (client: PoolClient, org: string) => (await client.query<Record<string,number>>(`SELECT
  (SELECT count(*)::int FROM v2_sales_documents WHERE organization_id=$1 AND document_kind='order') orders,
  (SELECT count(*)::int FROM v2_sales_document_lines l JOIN v2_sales_documents d ON d.id=l.document_id AND d.organization_id=l.organization_id WHERE d.organization_id=$1 AND d.document_kind='order') order_lines,
  (SELECT count(*)::int FROM v2_billing_invoices WHERE organization_id=$1) invoices,
  (SELECT count(*)::int FROM v2_billing_invoice_lines WHERE organization_id=$1) invoice_lines,
  (SELECT count(*)::int FROM v2_route_instances WHERE organization_id=$1) routes,
  (SELECT count(*)::int FROM v2_route_instance_steps WHERE organization_id=$1) route_steps,
  (SELECT count(*)::int FROM v2_sales_quote_checkpoints WHERE organization_id=$1 AND checkpoint_kind='quote_converted') converted_checkpoints,
  (SELECT count(*)::int FROM v2_sales_quote_conversions WHERE organization_id=$1) conversions,
  (SELECT count(*)::int FROM v2_audit_events WHERE organization_id=$1 AND event_type IN ('order_created','quote_converted')) audits,
  (SELECT count(*)::int FROM v2_operation_requests WHERE organization_id=$1 AND operation='sales.quote.convert.v1' AND status='succeeded') succeeded_requests`,[org])).rows[0]!;
const waitForBlockedLock = async (client: PoolClient): Promise<void> => {
  for(let i=0;i<500;i++){ const r=await client.query<{count:number}>("SELECT count(*)::int count FROM pg_stat_activity WHERE application_name='m110-quote-conversion-rehearsal' AND wait_event_type='Lock'"); if((r.rows[0]?.count??0)>0)return; await new Promise<void>((resolve)=>setImmediate(resolve)); }
  throw new Error("second conversion did not reach deterministic PostgreSQL lock wait");
};
async function main() {
  const pool=new Pool({connectionString:requireV2M0CloneDatabaseUrl(),max:4,application_name:"m110-quote-conversion-rehearsal"});
  try { await migrate(drizzle({client:pool}),{migrationsFolder,migrationsTable:"__drizzle_migrations_v2",migrationsSchema:"public"}); const client=await pool.connect(); try {
    assertV2M0PhysicalPostconditions(await checkV2M0PhysicalPostconditions(client)); assertV2CommercialPhysicalPostconditions(await checkV2CommercialPhysicalPostconditions(client));
    const f=await fixture(client), issuer=new PermissionSetPrincipalIssuer(new PostgresPermissionAuthorityReader(client)), staff=await issuer.issue({subjectId:f.user,authenticatedAt:new Date(),authenticationMethod:"session"},{organizationId:f.org}), limited=await issuer.issue({subjectId:f.limited,authenticatedAt:new Date(),authenticationMethod:"session"},{organizationId:f.org}), foreign=await issuer.issue({subjectId:f.foreignUser,authenticatedAt:new Date(),authenticationMethod:"session"},{organizationId:f.other});
    const quote=new QuoteApplicationService(new PostgresQuoteTransactionRunner(pool)); const order=new OrderApplicationService(new PostgresOrderTransactionRunner(pool)); const conversion=new QuoteConversionApplicationService(new PostgresQuoteConversionTransactionRunner(pool),order);
    const ref={organizationId:brandedId<"OrganizationId">(f.org),customerId:brandedId<"CustomerId">(f.customer),contactId:brandedId<"ContactId">(f.contact)};
    const foreignRef={organizationId:brandedId<"OrganizationId">(f.other),customerId:brandedId<"CustomerId">(f.foreignCustomer),contactId:brandedId<"ContactId">(f.foreignContact)};
    const createId=`m110-create-${randomUUID()}`; const created=await quote.create(ctx(staff,f.org,createId),{businessRequestId:createId,customerContact:ref,purchaseOrderNumber:"PO-M110",lines:[{productId:f.product,quantity:2,selections:{finish:"premium"}},{productId:f.serviceProduct,quantity:1}]}); assert(created.ok,"Quote create failed"); if(!created.ok)return;
    const sentId=`m110-send-${randomUUID()}`; const sent=await quote.recordDelivered(ctx(staff,f.org,sentId),{businessRequestId:sentId,quoteId:created.value.quote.quote.quoteId,expectedRevision:created.value.quote.revision,deliveryAttemptId:`fixture-${sentId}`,providerMessageId:`fixture-${sentId}`}); assert(sent.ok,"Quote send failed"); if(!sent.ok)return;
    const acceptId=`m110-accept-${randomUUID()}`; const accepted=await quote.accept(ctx(staff,f.org,acceptId),{businessRequestId:acceptId,quoteId:created.value.quote.quote.quoteId,expectedRevision:sent.value.quote.revision}); assert(accepted.ok && accepted.value.checkpointId,"Quote accept failed"); if(!accepted.ok||!accepted.value.checkpointId)return;
    const acceptedLine=accepted.value.quote.quote.lines[0]!;
    // Mutate current PBV2 defaults and price after acceptance; conversion must ignore both.
    await client.query("UPDATE pbv2_tree_versions SET tree_json=$1::jsonb WHERE organization_id=$2 AND id=$3",[JSON.stringify({schemaVersion:2,rootNodeIds:["finish"],nodes:{finish:{id:"finish",kind:"question",label:"Finish",input:{type:"select",selectionKey:"finish",defaultValue:"standard"},choices:[{value:"standard",label:"Standard"},{value:"premium",label:"Premium",priceDeltaCents:999}]}},meta:{pricingV2:{base:{perPieceCents:9999}}}}),f.org,f.tree]);
    const currentTemplate=`m110-current-template-${randomUUID()}`; await client.query("INSERT INTO v2_route_templates(id,organization_id,name,normalized_name,definition_fingerprint) VALUES($1,$2,'Current Fulfillment',$3,'sha256:m110-current')",[currentTemplate,f.org,`current-${randomUUID()}`]); await client.query("INSERT INTO v2_route_template_steps(id,organization_id,route_template_id,position,step_kind) VALUES($1,$2,$3,0,'fulfillment')",[randomUUID(),f.org,currentTemplate]); await client.query("UPDATE product_types SET default_route_template_id=$1 WHERE organization_id=$2 AND id=$3",[currentTemplate,f.org,f.type]);
    const convertId=`m110-convert-${randomUUID()}`; const command={organizationId:brandedId<"OrganizationId">(f.org),quoteId:created.value.quote.quote.quoteId,sourceCheckpointId:accepted.value.checkpointId,businessRequestId:brandedId<"BusinessRequestId">(convertId),expectedStateToken:accepted.value.quote.revision};
    const result=await conversion.convert(ctx(staff,f.org,convertId),command); assert(result.ok,"Accepted Quote conversion failed"); if(!result.ok)return;
    const replay=await conversion.convert(ctx(staff,f.org,convertId),command); assert(replay.ok&&replay.value.orderId===result.value.orderId,"conversion replay diverged");
    const read=await order.read(ctx(staff,f.org,`m110-read-${randomUUID()}`),result.value.orderId); assert(read.ok,"converted Order unavailable"); if(!read.ok)return;
    const line=read.value.order.lines[0]!; const currentRoute=await client.query<{steps:number;kind:string}>("SELECT count(*)::int steps,min(s.step_kind) kind FROM v2_route_instances r JOIN v2_route_instance_steps s ON s.organization_id=r.organization_id AND s.route_instance_id=r.id WHERE r.organization_id=$1 AND r.order_document_id=$2",[f.org,result.value.orderId]); assert(read.value.order.lines.length===2&&read.value.routes.length===1&&currentRoute.rows[0]?.steps===1&&currentRoute.rows[0]?.kind==="fulfillment","current/no-route conversion policy was incorrect"); assert(line.resolvedConfiguration.selections.finish==="premium" && line.pricingResult.calculatedLineAmount.cents===acceptedLine.pricingResult.calculatedLineAmount.cents && line.sellingLineAmount.cents===acceptedLine.sellingLineAmount.cents,"conversion repriced or replaced frozen commercial evidence");
    const db=await client.query<{conversions:number;checkpoints:number;invoices:number;routes:number;audits:number}>(`SELECT (SELECT count(*)::int FROM v2_sales_quote_conversions WHERE organization_id=$1 AND quote_document_id=$2) conversions,(SELECT count(*)::int FROM v2_sales_quote_checkpoints WHERE organization_id=$1 AND quote_document_id=$2 AND checkpoint_kind='quote_converted') checkpoints,(SELECT count(*)::int FROM v2_billing_invoices WHERE organization_id=$1 AND sales_order_document_id=$3) invoices,(SELECT count(*)::int FROM v2_route_instances WHERE organization_id=$1 AND order_document_id=$3) routes,(SELECT count(*)::int FROM v2_audit_events WHERE organization_id=$1 AND resource_id=$2 AND event_type='quote_converted') audits`,[f.org,created.value.quote.quote.quoteId,result.value.orderId]);
    assert(JSON.stringify(db.rows[0])===JSON.stringify({conversions:1,checkpoints:1,invoices:1,routes:1,audits:1}),"conversion durable readback mismatch");
    const complete=await client.query<{source_checkpoint_id:string;conversion_checkpoint_id:string;order_document_id:string;payload:any;invoice_lines:number;invoice_matches:number;invoice_total:string;audit_subject:string;business_request_id:string}>(`SELECT x.source_checkpoint_id,x.conversion_checkpoint_id,x.order_document_id,cp.payload,
      (SELECT count(*)::int FROM v2_billing_invoice_lines il JOIN v2_billing_invoices i ON i.id=il.invoice_id AND i.organization_id=il.organization_id WHERE i.organization_id=x.organization_id AND i.sales_order_document_id=x.order_document_id) invoice_lines,
      (SELECT count(*)::int FROM v2_billing_invoice_lines il JOIN v2_sales_document_lines sl ON sl.organization_id=il.organization_id AND sl.document_id=il.sales_order_document_id AND sl.id=il.source_sales_line_id WHERE il.organization_id=x.organization_id AND il.sales_order_document_id=x.order_document_id AND il.selling_line_cents=sl.selling_line_cents AND il.selling_unit_cents=(sl.selling_price_decision->'resultingUnitAmount'->>'cents')::bigint) invoice_matches,
      (SELECT total_cents::text FROM v2_billing_invoices i WHERE i.organization_id=x.organization_id AND i.sales_order_document_id=x.order_document_id) invoice_total,
      (SELECT principal_subject FROM v2_audit_events a WHERE a.organization_id=x.organization_id AND a.resource_id=x.quote_document_id AND a.event_type='quote_converted') audit_subject,
      (SELECT business_request_id FROM v2_operation_requests r WHERE r.organization_id=x.organization_id AND r.id=x.operation_request_id) business_request_id
      FROM v2_sales_quote_conversions x JOIN v2_sales_quote_checkpoints cp ON cp.organization_id=x.organization_id AND cp.id=x.conversion_checkpoint_id WHERE x.organization_id=$1 AND x.quote_document_id=$2`,[f.org,created.value.quote.quote.quoteId]);
    const completeRow=complete.rows[0]!; assert(completeRow.source_checkpoint_id===accepted.value.checkpointId&&completeRow.order_document_id===result.value.orderId&&completeRow.payload.sourceCheckpointId===accepted.value.checkpointId&&completeRow.payload.commercial.lines.length===2&&completeRow.invoice_lines===2&&completeRow.invoice_matches===2&&Number(completeRow.invoice_total)===read.value.totals.selling.cents&&completeRow.audit_subject===f.user&&completeRow.business_request_id===convertId,"complete Quote/Order/Billing/Audit lineage readback failed");
    const postEditId=`m110-order-edit-${randomUUID()}`; const postEdit=await order.update(ctx(staff,f.org,postEditId),{businessRequestId:postEditId,orderId:result.value.orderId,expectedRevision:read.value.revision,patch:{purchaseOrderNumber:"PO-INDEPENDENT"}}); assert(postEdit.ok,"post-conversion Order mutation failed");
    const blockedId=`m110-quote-edit-${randomUUID()}`; const blocked=await quote.update(ctx(staff,f.org,blockedId),{businessRequestId:blockedId,quoteId:created.value.quote.quote.quoteId,expectedRevision:accepted.value.quote.revision,patch:{purchaseOrderNumber:"forbidden"}}); assert(!blocked.ok&&blocked.error.code==="CONFLICT","post-conversion Quote mutation was not safely rejected");

    // Deterministic different-request races: A holds the Quote row lock while B is observed waiting in PostgreSQL.
    for(let repetition=0;repetition<3;repetition++){
      const q=await acceptedQuote(quote,staff,f,ref,`race-${repetition}`),beforeRace=await counts(client,f.org); let release!:()=>void,entered!:()=>void;
      const held=new Promise<void>((resolve)=>{release=resolve;}); const locked=new Promise<void>((resolve)=>{entered=resolve;});
      const aId=`m110-race-a-${repetition}-${randomUUID()}`,bId=`m110-race-b-${repetition}-${randomUUID()}`;
      const base={organizationId:brandedId<"OrganizationId">(f.org),quoteId:q.quoteId,sourceCheckpointId:q.acceptedCheckpointId,expectedStateToken:q.accepted.value.quote.revision};
      const serviceA=new QuoteConversionApplicationService(new PostgresQuoteConversionTransactionRunner(pool),order,undefined,{afterQuoteLocked:async()=>{entered();await held;}});
      const a=serviceA.convert(ctx(staff,f.org,aId),{...base,businessRequestId:brandedId<"BusinessRequestId">(aId)}); await locked;
      const b=conversion.convert(ctx(staff,f.org,bId),{...base,businessRequestId:brandedId<"BusinessRequestId">(bId)}); await waitForBlockedLock(client); release();
      const [ar,br]=await Promise.all([a,b]); assert(ar.ok&&!br.ok&&br.error.code==="CONFLICT",`conversion race ${repetition} did not produce one winner/one conflict`);
      const c=await client.query<{orders:number;invoices:number;routes:number;checkpoints:number;lineage:number;audits:number}>(`SELECT (SELECT count(*)::int FROM v2_sales_quote_conversions x WHERE x.organization_id=$1 AND x.quote_document_id=$2) lineage,(SELECT count(*)::int FROM v2_sales_quote_checkpoints WHERE organization_id=$1 AND quote_document_id=$2 AND checkpoint_kind='quote_converted') checkpoints,(SELECT count(*)::int FROM v2_sales_documents d JOIN v2_sales_quote_conversions x ON x.order_document_id=d.id AND x.organization_id=d.organization_id WHERE x.organization_id=$1 AND x.quote_document_id=$2) orders,(SELECT count(*)::int FROM v2_billing_invoices i JOIN v2_sales_quote_conversions x ON x.order_document_id=i.sales_order_document_id AND x.organization_id=i.organization_id WHERE x.organization_id=$1 AND x.quote_document_id=$2) invoices,(SELECT count(*)::int FROM v2_route_instances r JOIN v2_sales_quote_conversions x ON x.order_document_id=r.order_document_id AND x.organization_id=r.organization_id WHERE x.organization_id=$1 AND x.quote_document_id=$2) routes,(SELECT count(*)::int FROM v2_audit_events WHERE organization_id=$1 AND resource_id=$2 AND event_type='quote_converted') audits`,[f.org,q.quoteId]);
      assert(Object.values(c.rows[0]!).every((value)=>value===1),`race ${repetition} durable state mismatch: ${JSON.stringify(c.rows[0])}`);
      const afterRace=await counts(client,f.org); assert(afterRace.orders-beforeRace.orders===1&&afterRace.invoices-beforeRace.invoices===1&&afterRace.routes-beforeRace.routes===1&&afterRace.conversions-beforeRace.conversions===1&&afterRace.converted_checkpoints-beforeRace.converted_checkpoints===1,"race left orphan loser state");
      const loser=await client.query<{requests:number;audits:number}>("SELECT (SELECT count(*)::int FROM v2_operation_requests WHERE organization_id=$1 AND business_request_id=$2) requests,(SELECT count(*)::int FROM v2_audit_events a JOIN v2_operation_requests r ON r.id=a.operation_request_id AND r.organization_id=a.organization_id WHERE r.organization_id=$1 AND r.business_request_id=$2) audits",[f.org,bId]); assert(loser.rows[0]?.requests===0&&loser.rows[0]?.audits===0,"race loser left operation or Audit state");
    }

    // Conversion wins the shared Quote lock; the blocked edit then observes lineage and fails.
    { const q=await acceptedQuote(quote,staff,f,ref,"edit-race"); let release!:()=>void,entered!:()=>void; const held=new Promise<void>(r=>{release=r;}); const locked=new Promise<void>(r=>{entered=r;});
      const convertRaceId=`m110-edit-race-convert-${randomUUID()}`; const convertRace=new QuoteConversionApplicationService(new PostgresQuoteConversionTransactionRunner(pool),order,undefined,{afterQuoteLocked:async()=>{entered();await held;}}).convert(ctx(staff,f.org,convertRaceId),{organizationId:brandedId<"OrganizationId">(f.org),quoteId:q.quoteId,sourceCheckpointId:q.acceptedCheckpointId,businessRequestId:brandedId<"BusinessRequestId">(convertRaceId),expectedStateToken:q.accepted.value.quote.revision}); await locked;
      const editId=`m110-edit-race-edit-${randomUUID()}`; const edit=quote.update(ctx(staff,f.org,editId),{businessRequestId:editId,quoteId:q.quoteId,expectedRevision:q.accepted.value.quote.revision,patch:{purchaseOrderNumber:"MIXED"}}); await waitForBlockedLock(client); release(); const [converted,edited]=await Promise.all([convertRace,edit]);
      assert(converted.ok&&!edited.ok&&edited.error.code==="CONFLICT","edit/conversion race was incoherent"); if(converted.ok){const o=await order.read(ctx(staff,f.org,randomUUID()),converted.value.orderId),qr=await quote.read(ctx(staff,f.org,randomUUID()),q.quoteId);assert(o.ok&&qr.ok&&qr.value.revision===q.accepted.value.quote.revision&&o.value.order.purchaseOrderNumber===q.accepted.value.quote.quote.purchaseOrderNumber,"race Order/Quote did not preserve accepted revision"); const evidence=await client.query<{payload:any;edit_requests:number;conversion_audits:number}>("SELECT cp.payload,(SELECT count(*)::int FROM v2_operation_requests WHERE organization_id=$1 AND business_request_id=$3) edit_requests,(SELECT count(*)::int FROM v2_audit_events WHERE organization_id=$1 AND resource_id=$2 AND event_type='quote_converted' AND principal_subject=$4) conversion_audits FROM v2_sales_quote_conversions x JOIN v2_sales_quote_checkpoints cp ON cp.organization_id=x.organization_id AND cp.id=x.conversion_checkpoint_id WHERE x.organization_id=$1 AND x.quote_document_id=$2",[f.org,q.quoteId,editId,f.user]);assert(evidence.rows[0]?.payload.commercial.purchaseOrderNumber===o.value.order.purchaseOrderNumber&&evidence.rows[0]?.edit_requests===0&&evidence.rows[0]?.conversion_audits===1,"edit race left mixed checkpoint, Audit, or loser operation state");}
    }

    // Every conversion write boundary rolls back the entire cross-module transaction; identical retry succeeds.
    for(const [point,hooks] of [
      ["order",{order:{afterSales:async()=>{throw new Error("after order");}}}],
      ["billing",{order:{afterBilling:async()=>{throw new Error("after billing");}}}],
      ["routing",{order:{afterRoute:async()=>{throw new Error("after routing");}}}],
      ["checkpoint",{quote:{afterConvertedCheckpoint:async()=>{throw new Error("after checkpoint");}}}],
      ["lineage",{quote:{afterConversionLineage:async()=>{throw new Error("after lineage");}}}],
      ["audit",{quote:{afterAudit:async()=>{throw new Error("after audit");}}}],
    ] as const){ const q=await acceptedQuote(quote,staff,f,ref,`rollback-${point}`),before=await counts(client,f.org),id=`m110-rollback-${point}-${randomUUID()}`,cmd={organizationId:brandedId<"OrganizationId">(f.org),quoteId:q.quoteId,sourceCheckpointId:q.acceptedCheckpointId,businessRequestId:brandedId<"BusinessRequestId">(id),expectedStateToken:q.accepted.value.quote.revision};
      const failed=await new QuoteConversionApplicationService(new PostgresQuoteConversionTransactionRunner(pool,hooks),order).convert(ctx(staff,f.org,id),cmd); assert(!failed.ok,`${point} injection committed`); assert(JSON.stringify(await counts(client,f.org))===JSON.stringify(before),`${point} rollback left partial state`); const retry=await conversion.convert(ctx(staff,f.org,id),cmd); assert(retry.ok,`${point} retry failed`);
    }

    // Checkpoint, scope, lifecycle, already-converted, and capability attacks fail without artifacts.
    { const qa=await acceptedQuote(quote,staff,f,ref,"adversarial-a"),qb=await acceptedQuote(quote,staff,f,ref,"adversarial-b"),foreignFixture={...f,org:f.other,product:f.foreignProduct},foreignQuote=await acceptedQuote(quote,foreign,foreignFixture,foreignRef,"foreign"),before=await counts(client,f.org);
      const attempt=async(label:string,principal:any,organizationId:string,sourceCheckpointId:string,quoteId=qa.quoteId,expected=qa.accepted.value.quote.revision)=>{const id=`m110-bad-${label}-${randomUUID()}`;return conversion.convert(ctx(principal,organizationId,id),{organizationId:brandedId<"OrganizationId">(organizationId),quoteId,sourceCheckpointId:brandedId<"QuoteCheckpointId">(sourceCheckpointId),businessRequestId:brandedId<"BusinessRequestId">(id),expectedStateToken:expected});};
      for(const [label,promise] of [["other-quote",attempt("other-quote",staff,f.org,qb.acceptedCheckpointId)],["foreign-checkpoint",attempt("foreign-checkpoint",staff,f.org,foreignQuote.acceptedCheckpointId)],["foreign-quote",attempt("foreign-quote",staff,f.org,foreignQuote.acceptedCheckpointId,foreignQuote.quoteId,foreignQuote.accepted.value.quote.revision)],["sent-kind",attempt("sent",staff,f.org,qa.sentCheckpointId)],["missing",attempt("missing",staff,f.org,randomUUID())],["foreign-principal",attempt("foreign",foreign,f.other,qa.acceptedCheckpointId)],["limited",attempt("limited",limited,f.org,qa.acceptedCheckpointId)]] as const){const bad=await promise;assert(!bad.ok,`${label} attack succeeded`);}
      const draftId=`m110-draft-${randomUUID()}`,draft=await quote.create(ctx(staff,f.org,draftId),{businessRequestId:draftId,customerContact:ref,lines:[{productId:f.product,quantity:1}]});assert(draft.ok,"draft fixture failed");if(draft.ok){const bad=await attempt("draft",staff,f.org,randomUUID(),draft.value.quote.quote.quoteId,draft.value.quote.revision);assert(!bad.ok&&bad.error.code==="CONFLICT","Draft Quote converted");}
      assert(JSON.stringify(await counts(client,f.org))===JSON.stringify(before),"adversarial rejection left conversion state");
      const goodId=`m110-adversarial-good-${randomUUID()}`; const good=await conversion.convert(ctx(staff,f.org,goodId),{organizationId:brandedId<"OrganizationId">(f.org),quoteId:qa.quoteId,sourceCheckpointId:qa.acceptedCheckpointId,businessRequestId:brandedId<"BusinessRequestId">(goodId),expectedStateToken:qa.accepted.value.quote.revision});assert(good.ok,"adversarial fixture conversion failed"); const again=await attempt("again",staff,f.org,qa.acceptedCheckpointId);assert(!again.ok&&again.error.code==="CONFLICT","already converted Quote created another Order");
      const sameId=`m110-cross-tenant-${randomUUID()}`,foreignConverted=await conversion.convert(ctx(foreign,f.other,sameId),{organizationId:brandedId<"OrganizationId">(f.other),quoteId:foreignQuote.quoteId,sourceCheckpointId:foreignQuote.acceptedCheckpointId,businessRequestId:brandedId<"BusinessRequestId">(sameId),expectedStateToken:foreignQuote.accepted.value.quote.revision}),tenantA=await acceptedQuote(quote,staff,f,ref,"cross-tenant-a"),tenantAConverted=await conversion.convert(ctx(staff,f.org,sameId),{organizationId:brandedId<"OrganizationId">(f.org),quoteId:tenantA.quoteId,sourceCheckpointId:tenantA.acceptedCheckpointId,businessRequestId:brandedId<"BusinessRequestId">(sameId),expectedStateToken:tenantA.accepted.value.quote.revision});assert(foreignConverted.ok&&tenantAConverted.ok&&foreignConverted.value.orderId!==tenantAConverted.value.orderId,"cross-tenant business request replay leaked or collided");
    }

    // Real trusted-session + fresh-per-request authority + synchronizer-CSRF HTTP path.
    { const q=await acceptedQuote(quote,staff,f,ref,"http"); const makeApp=(userId:string,sessionId:string,session:any,authenticated=true)=>{const runtime=composeAuthenticatedQuoteRuntime({pool,trustedHostIdentity:new PassportSessionIdentitySource(),trustedHostMiddleware:(req:any,_res:any,next:()=>void)=>{req.isAuthenticated=()=>authenticated;req.user=authenticated?{id:userId}:undefined;req.sessionID=sessionId;req.session=session;next();}});return createV2HttpApp(loadV2RuntimeConfig({NODE_ENV:"test",V2_SERVICE_NAME:"m110-http"}),{log:()=>undefined},undefined,runtime);};
      const sessionA:any={},appA=makeApp(f.user,"m110-http-a",sessionA),bootstrap=await request(appA).get(`/v2/organizations/${f.org}/ui-bootstrap`); const csrf=bootstrap.body.data.csrfToken as string,body={businessRequestId:`m110-http-${randomUUID()}`,sourceCheckpointId:q.acceptedCheckpointId,expectedRevision:q.accepted.value.quote.revision,role:"owner",capabilities:["*"],staffActorUserId:"forged"};
      assert((await request(appA).post(`/v2/organizations/${f.org}/quotes/${q.quoteId}/convert`).send(body)).status===403,"missing CSRF succeeded"); assert((await request(appA).post(`/v2/organizations/${f.org}/quotes/${q.quoteId}/convert`).set("x-v2-csrf-token","bad").send(body)).status===403,"invalid CSRF succeeded");
      const limitedSession:any={},limitedApp=makeApp(f.limited,"m110-http-limited",limitedSession),limitedBoot=await request(limitedApp).get(`/v2/organizations/${f.org}/ui-bootstrap`);assert((await request(limitedApp).post(`/v2/organizations/${f.org}/quotes/${q.quoteId}/convert`).set("x-v2-csrf-token",limitedBoot.body.data.csrfToken).send({...body,businessRequestId:`m110-http-limited-${randomUUID()}`})).status===403,"limited HTTP conversion succeeded");
      const sessionB:any={},appB=makeApp(f.user,"m110-http-b",sessionB);await request(appB).get(`/v2/organizations/${f.org}/ui-bootstrap`);assert((await request(appB).post(`/v2/organizations/${f.org}/quotes/${q.quoteId}/convert`).set("x-v2-csrf-token",csrf).send(body)).status===403,"cross-session CSRF succeeded");
      const unauth=makeApp(f.user,"m110-http-unauth",sessionA,false);assert((await request(unauth).post(`/v2/organizations/${f.org}/quotes/${q.quoteId}/convert`).set("x-v2-csrf-token",csrf).send(body)).status===403,"unauthenticated conversion succeeded");
      const invalid=await request(appA).post(`/v2/organizations/${f.org}/quotes/${q.quoteId}/convert`).set("x-v2-csrf-token",csrf).send({...body,businessRequestId:`m110-http-invalid-${randomUUID()}`,sourceCheckpointId:""});assert(invalid.status===400&&invalid.body.error.code==="VALIDATION_ERROR","invalid HTTP checkpoint was not typed");
      const foreignRoute=await request(appA).post(`/v2/organizations/${f.other}/quotes/${q.quoteId}/convert`).set("x-v2-csrf-token",csrf).send({...body,businessRequestId:`m110-http-foreign-${randomUUID()}`});assert([403,404].includes(foreignRoute.status),"foreign organization HTTP route succeeded");
      const ok=await request(appA).post(`/v2/organizations/${f.org}/quotes/${q.quoteId}/convert`).set("x-v2-csrf-token",csrf).send(body);assert(ok.status===200,"authenticated HTTP conversion failed");assert(Object.keys(ok.body.data).sort().join(",")===["conversionCheckpointId","draftInvoiceId","orderId","orderNumber","quoteId","sourceCheckpointId"].sort().join(","),"HTTP response leaked unintended state");const replayHttp=await request(appA).post(`/v2/organizations/${f.org}/quotes/${q.quoteId}/convert`).set("x-v2-csrf-token",csrf).send(body);assert(replayHttp.status===200&&replayHttp.body.data.orderId===ok.body.data.orderId,"HTTP replay diverged");
      const audit=await client.query<{principal_subject:string;staff_actor_user_id:string|null}>("SELECT principal_subject,staff_actor_user_id FROM v2_audit_events WHERE organization_id=$1 AND resource_id=$2 AND event_type='quote_converted'",[f.org,q.quoteId]);assert(audit.rows.length===1&&audit.rows[0]?.principal_subject===f.user&&audit.rows[0]?.staff_actor_user_id===f.user,"HTTP Audit actor was falsified");
    }
    console.log("[m1.10] full conversion concurrency, edit race, rollback, adversarial, HTTP, freeze, readback, and separation matrix passed.");
  } finally {client.release();}} finally {await pool.end();}}
main().catch((error)=>{console.error(`[m1.10] rehearsal failed: ${error instanceof Error ? error.stack ?? error.message : String(error)}`);process.exitCode=1;});
