import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { synchronizeProductionRequirements } from "../infrastructure/sales/postgresProductionRequirements.js";
import { assertV2ProductionRequirementsPhysicalPostconditions } from "../infrastructure/sales/productionRequirementsPhysicalPostconditions.js";
import { PostgresPrepressTransaction } from "../infrastructure/prepress/postgresPrepressTransaction.js";
import { brandedId } from "../src/modules/shared/commercialValues.js";
import type { SalesLineSnapshot } from "../src/modules/sales/contracts.js";

const migrationsFolder=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../server/db/migrations_v2");
const fakeLine=(id:string,units:readonly unknown[],mark:string):SalesLineSnapshot=>({lineId:brandedId<"SalesLineId">(id),resolvedConfiguration:{productionRequirements:{state:"configured",specificationFingerprint:`sha256:${mark.repeat(64)}`,units}}} as unknown as SalesLineSnapshot);
const count=async(c:{query:Function},sql:string,v:unknown[])=>Number((await c.query<{n:string}>(sql,v)).rows[0]!.n);
async function main(){
 const pool=new Pool({connectionString:requireV2M0CloneDatabaseUrl(),max:4,application_name:"m221-production-requirements"});
 try { await migrate(drizzle({client:pool}),{migrationsFolder,migrationsTable:"__drizzle_migrations_v2",migrationsSchema:"public"}); const c=await pool.connect(); try {
  await assertV2ProductionRequirementsPhysicalPostconditions(c); const x=randomUUID(),org=`m221-${x}`,other=`m221-other-${x}`,customer=`m221-customer-${x}`,type=`m221-type-${x}`,product=`m221-product-${x}`,order=`m221-order-${x}`,quote=`m221-quote-${x}`,line=`m221-line-${x}`,quoteLine=`m221-quote-line-${x}`,unknown=`m221-unknown-${x}`,file=`m221-file-${x}`,front=`m221-front-${x}`,back=`m221-back-${x}`;
  await c.query("BEGIN"); await c.query("INSERT INTO organizations(id,name,slug) VALUES($1,'M221',$2),($3,'Other',$4)",[org,`m221-${x}`,other,`m221-other-${x}`]); await c.query("INSERT INTO customers(id,organization_id,company_name,display_name,is_active,status) VALUES($1,$2,'M221','M221',true,'active')",[customer,org]); await c.query("INSERT INTO product_types(id,organization_id,name,routing_mode) VALUES($1,$2,'M221','no_route')",[type,org]); await c.query("INSERT INTO products(id,organization_id,name,description,is_active,measurement_mode,product_type_id) VALUES($1,$2,'M221','M221',true,'quantity_only',$3)",[product,org,type]);
  for(const [id,kind] of [[order,"order"],[quote,"quote"]] as const)await c.query("INSERT INTO v2_sales_documents(id,organization_id,document_kind,business_number,display_number,customer_id,currency,terms_json) VALUES($1,$2,$3,1,$4,$5,'USD','{}')",[id,org,kind,`${kind}-${x}`,customer]); await c.query("INSERT INTO v2_sales_order_details(document_id,organization_id) VALUES($1,$2)",[order,org]); await c.query("INSERT INTO v2_sales_quote_details(document_id,organization_id) VALUES($1,$2)",[quote,org]);
  for(const [id,doc,pos] of [[line,order,0],[unknown,order,1],[quoteLine,quote,0]] as const)await c.query("INSERT INTO v2_sales_document_lines(id,organization_id,document_id,position,product_id,description,quantity,currency,calculated_unit_cents,calculated_line_cents,selling_unit_cents,selling_line_cents,pricing_result_id,pricing_evidence_fingerprint,resolved_configuration,pricing_result,selling_price_decision) VALUES($1,$2,$3,$4,$5,'M221',1,'USD',1,1,1,1,'m221','sha256:m221','{}','{}','{}')",[id,org,doc,pos,product]); await c.query("COMMIT");
  const double=[{key:"front",side:"front"},{key:"back",side:"back"}] as const;
  await c.query("BEGIN"); await synchronizeProductionRequirements(c,org,order,fakeLine(line,double,"a")); await synchronizeProductionRequirements(c,org,quote,fakeLine(quoteLine,double,"a")); await c.query("COMMIT"); assert.equal(await count(c,"SELECT count(*) n FROM v2_sales_line_production_requirements WHERE organization_id=$1 AND order_line_id=$2",[org,line]),2); assert.deepEqual((await c.query("SELECT requirement_key FROM v2_sales_line_production_requirements WHERE organization_id=$1 AND order_line_id=$2 ORDER BY requirement_key",[org,line])).rows,(await c.query("SELECT requirement_key FROM v2_sales_line_production_requirements WHERE organization_id=$1 AND order_line_id=$2 ORDER BY requirement_key",[org,quoteLine])).rows,"accepted Quote evidence preserves exact requirement rows on Order conversion.");
  await c.query("BEGIN"); await synchronizeProductionRequirements(c,org,quote,fakeLine(quoteLine,[{key:"front",side:"front"}],"b")); await c.query("COMMIT"); assert.equal(await count(c,"SELECT count(*) n FROM v2_sales_line_production_requirements WHERE organization_id=$1 AND order_line_id=$2",[org,quoteLine]),1,"selection-driven requirement changes replace rows before operational history.");
  const prepress=new PostgresPrepressTransaction(c); assert.equal((await prepress.coverage(brandedId<"OrganizationId">(org),brandedId<"OrderLineId">(unknown))).state,"unconfigured");
  await c.query("INSERT INTO v2_artwork_files(id,organization_id,storage_provider,object_key,original_filename,display_filename,content_type,byte_size,source_kind) VALUES($1,$2,'clone',$3,'x.pdf','x.pdf','application/pdf',1,'customer_upload')",[file,org,`m221/${x}`]); for(const [id,side,h] of [[front,"front","c"],[back,"back","d"]] as const)await c.query("INSERT INTO v2_artwork_assignments(id,organization_id,artwork_file_id,order_document_id,order_line_id,purpose,side,identity_fingerprint) VALUES($1,$2,$3,$4,$5,'production',$6,$7)",[id,org,file,order,line,side,`sha256:${h.repeat(64)}`]); let coverage=await prepress.coverage(brandedId<"OrganizationId">(org),brandedId<"OrderLineId">(line)); assert(coverage.state==="configured"&&coverage.productionArtworkComplete&&!coverage.allRequiredPrepressUnitsComplete);
  for(const [id,assignment,side] of [[`m221-pf-${x}`,front,"front"],[`m221-pb-${x}`,back,"back"]] as const)await c.query("INSERT INTO v2_prepress_units(id,organization_id,order_document_id,order_line_id,artwork_assignment_id,artwork_file_id,side,created_principal_kind,created_principal_subject,started_at,started_principal_kind,started_principal_subject,completed_at,completed_principal_kind,completed_principal_subject) VALUES($1,$2,$3,$4,$5,$6,$7,'staff','m221',now(),'staff','m221',now(),'staff','m221')",[id,org,order,line,assignment,file,side]); coverage=await prepress.coverage(brandedId<"OrganizationId">(org),brandedId<"OrderLineId">(line)); assert(coverage.state==="configured"&&coverage.allRequiredPrepressUnitsComplete);
  await assert.rejects(c.query("INSERT INTO v2_sales_line_production_requirements(organization_id,document_id,order_line_id,requirement_key) VALUES($1,$2,$3,'front')",[org,order,line]),/unique/i); await assert.rejects(c.query("INSERT INTO v2_sales_line_production_requirements(organization_id,document_id,order_line_id,requirement_key) VALUES($1,$2,$3,'evil')",[other,order,line]),/foreign key/i);
  await c.query("BEGIN"); await assert.rejects(synchronizeProductionRequirements(c,org,order,fakeLine(line,[{key:"front",side:"front"}],"b")),/operational history/i); await c.query("ROLLBACK"); assert.equal(await count(c,"SELECT count(*) n FROM v2_sales_line_production_requirements WHERE organization_id=$1 AND order_line_id=$2",[org,line]),2,"operationally blocked edit leaves no partial replacement.");
  await c.query("BEGIN"); await c.query("UPDATE v2_sales_document_lines SET production_requirement_count=2 WHERE organization_id=$1 AND id=$2",[org,quoteLine]); await assert.rejects(c.query("SET CONSTRAINTS ALL IMMEDIATE"),/Frozen production requirement count/i); await c.query("ROLLBACK");
  console.log("[m2.2.1] Production requirements PostgreSQL clone rehearsal passed (18 assertions).");
 } finally {c.release();} } finally {await pool.end();}
}
main().catch((error)=>{console.error(`[m2.2.1] rehearsal failed: ${error instanceof Error?error.stack??error.message:String(error)}`);process.exitCode=1;});
