import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { Pool } from "pg";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { PostgresProductDraftOptionPricingReader, PostgresProductDraftPricingPreview, PostgresProductVersionTransactionRunner } from "../infrastructure/products/postgresProductVersionLifecycle.js";
import { PostgresProductsCompatibilityReader } from "../infrastructure/compatibility/postgresProductsRead.js";
import { ProductVersionLifecycleApplicationService, type ProductDraftOptionPricingImpact } from "../src/modules/products/productVersionLifecycle.js";
import { resolveActivePbv2PricingInput } from "../src/modules/products/pbv2CompatibilityResolution.js";
import { V2PricingParityAdapter } from "../src/modules/pricing/v2PricingAdapter.js";
import type { OperationContext } from "../src/application/operation.js";
import { brandedId, currencyCode, decimalText } from "../src/modules/shared/commercialValues.js";

const cloneHost = "ep-soft-frost-aef6c2jb-pooler.c-2.us-east-2.aws.neon.tech";
const record = (value: unknown): Record<string, any> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, any> : {};
const request = (label: string) => `p6c-option-pricing-${label}-${randomUUID()}`;
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const context = (organizationId: string, userId: string, id: string, caps: readonly any[] = ["product.edit"]): OperationContext => ({ organizationId, operationId: id, businessRequest: { id, payloadFingerprint: id }, principal: { kind: "staff", organizationId, userId, authority: { membershipId: `p6c-${organizationId}`, capabilities: caps } } });
type Candidate = { organizationId: string; productId: string; name: string; measurementMode: "dimensions_required" | "quantity_only"; activeId: string; activeUpdatedAt: Date; activeTree: unknown; draftId: string | null; };
type Exercise = { candidate: Candidate; draft: Awaited<ReturnType<PostgresProductDraftOptionPricingReader["read"]>> & {}; optionId: string; selectionKey: string; choiceValue: string; impact: ProductDraftOptionPricingImpact; };
const previewInput = (mode: Candidate["measurementMode"], selectionKey: string, choiceValue: string) => ({ quantity: 2, ...(mode === "dimensions_required" ? { width: 24, height: 24 } : {}), selections: { [selectionKey]: choiceValue } });
const withoutOptionPricing = (tree: unknown) => { const copy = structuredClone(record(tree)); for (const node of Object.values(record(copy.nodes)).map(record)) { delete node.pricingImpact; for (const choice of Array.isArray(node.choices) ? node.choices.map(record) : []) { delete choice.pricingImpact; delete choice.priceDeltaCents; } } return copy; };

async function activePrice(pool: Pool, candidate: Candidate, selections: Record<string, unknown>) {
  const row = (await pool.query<{ pricing_profile_key: string | null; schema_version: number; updated_at: Date; tree_json: unknown; formula_id: string | null; formula_code: string | null; formula_profile_key: string | null; formula_expression: string | null; formula_config: unknown; formula_updated_at: Date | null }>("SELECT p.pricing_profile_key,a.schema_version,a.updated_at,a.tree_json,f.id formula_id,f.code formula_code,f.pricing_profile_key formula_profile_key,f.expression formula_expression,f.config formula_config,f.updated_at formula_updated_at FROM products p JOIN pbv2_tree_versions a ON a.organization_id=p.organization_id AND a.id=p.pbv2_active_tree_version_id LEFT JOIN pricing_formulas f ON f.organization_id=p.organization_id AND f.id=p.pricing_formula_id AND f.is_active=TRUE WHERE p.organization_id=$1 AND p.id=$2", [candidate.organizationId, candidate.productId])).rows[0]!;
  const sellable = { organizationId: brandedId<"OrganizationId">(candidate.organizationId), productId: brandedId<"ProductId">(candidate.productId), displayName: candidate.name, lifecycle: "active" as const, pricingConfiguration: { id: brandedId<"PricingConfigurationId">(candidate.activeId), version: row.updated_at.toISOString(), contentHash: "sha256:active" }, requiresDimensions: candidate.measurementMode !== "quantity_only", pricingCurrency: currencyCode("USD") };
  const formula = row.formula_id && row.formula_profile_key && row.formula_expression && row.formula_updated_at ? { id: row.formula_id, code: row.formula_code ?? row.formula_id, profileKey: row.formula_profile_key, expression: row.formula_expression, config: record(row.formula_config), updatedAt: row.formula_updated_at.toISOString() } : null;
  const dimensions = candidate.measurementMode === "quantity_only" ? undefined : { width: decimalText("24"), height: decimalText("24"), unit: "in" as const };
  const resolved = resolveActivePbv2PricingInput(sellable, { id: candidate.activeId, schemaVersion: row.schema_version, publishedAt: row.updated_at.toISOString(), treeJson: row.tree_json, productMeasurementMode: candidate.measurementMode, productPricingProfileKey: row.pricing_profile_key, formula }, { organizationId: brandedId<"OrganizationId">(candidate.organizationId), productId: brandedId<"ProductId">(candidate.productId), quantity: 2, ...(dimensions ? { dimensions } : {}), selections: selections as any });
  assert(resolved.ok, "Active Product pricing did not resolve.");
  return (await new V2PricingParityAdapter().calculate({ organizationId: sellable.organizationId, sellableProduct: { ...sellable, pricingConfiguration: { ...sellable.pricingConfiguration, contentHash: resolved.value.resolvedConfiguration.pricingConfigurationContentHash } }, resolvedConfiguration: resolved.value.resolvedConfiguration, rules: resolved.value.rules, pricingContext: { channel: "staff", effectiveAt: new Date().toISOString() } })).calculatedLineAmount.cents;
}

async function main() {
  const url = requireV2M0CloneDatabaseUrl(), target = new URL(url); assert.equal(target.hostname, cloneHost, "P6C rehearsal refuses a database other than the authorized MAIN-derived DEV clone."); assert.equal(target.pathname.replace(/^\//u, ""), "neondb", "P6C rehearsal refuses a database other than neondb.");
  const pool = new Pool({ connectionString: url, max: 4 });
  try {
    const relations = (await pool.query<{ audit: string | null; requests: string | null; sales: string | null }>("SELECT to_regclass('public.v2_audit_events') audit,to_regclass('public.v2_operation_requests') requests,to_regclass('public.v2_sales_document_lines') sales")).rows[0]!; assert(relations.audit && relations.requests && relations.sales, "P6C setup is incomplete: the authorized clone is missing required V2 lifecycle/audit/commercial relations.");
    const actor = (await pool.query<{ id: string }>("SELECT id FROM users ORDER BY id LIMIT 1")).rows[0]?.id; assert(actor, "The authorized clone needs a Staff user.");
    const service = new ProductVersionLifecycleApplicationService(new PostgresProductVersionTransactionRunner(pool)), reader = new PostgresProductDraftOptionPricingReader(pool), preview = new PostgresProductDraftPricingPreview(pool), sales = new PostgresProductsCompatibilityReader(pool);
    const candidates = (await pool.query<Candidate>("SELECT p.organization_id AS \"organizationId\",p.id AS \"productId\",p.name,p.measurement_mode AS \"measurementMode\",a.id AS \"activeId\",a.updated_at AS \"activeUpdatedAt\",a.tree_json AS \"activeTree\",d.id AS \"draftId\" FROM products p JOIN pbv2_tree_versions a ON a.id=p.pbv2_active_tree_version_id AND a.status='ACTIVE' LEFT JOIN pbv2_tree_versions d ON d.organization_id=p.organization_id AND d.product_id=p.id AND d.status='DRAFT' WHERE p.is_active=TRUE ORDER BY p.name,p.id")).rows;
    let exercised: Exercise | undefined;
    for (const candidate of candidates) {
      if (!candidate.draftId) { const id = request("create-draft"), created = await service.createDraft(context(candidate.organizationId, actor, id), { productId: candidate.productId, businessRequestId: id, expectedActiveVersionUpdatedAt: candidate.activeUpdatedAt.toISOString() }); if (!created.ok) throw new Error(`P6C setup failed while preparing '${candidate.name}' (${candidate.productId}): ${created.error.code} ${created.error.publicMessage}`); }
      const draft = await reader.read(candidate.organizationId, candidate.productId); const eligible = draft?.options.flatMap(option => option.choices.filter(choice => choice.editable && choice.impact).map(choice => ({ option, choice })))[0];
      if (!draft || !eligible?.choice.impact) continue;
      try { await preview.preview(candidate.organizationId, candidate.productId, previewInput(candidate.measurementMode, eligible.option.selectionKey, eligible.choice.choiceValue)); exercised = { candidate, draft, optionId: eligible.option.optionId, selectionKey: eligible.option.selectionKey, choiceValue: eligible.choice.choiceValue, impact: eligible.choice.impact }; break; } catch { /* Candidate is real but lacks a previewable selection/default combination. */ }
    }
    assert(exercised, "The authorized clone has no real, previewable Draft Choice with a supported Option Pricing impact.");
    const { candidate, draft, optionId, selectionKey, choiceValue, impact } = exercised;
    const beforeProduct = (await pool.query("SELECT name,category,description,measurement_mode,workflow_intent,requires_proof_approval,requires_production_job,pbv2_active_tree_version_id FROM products WHERE organization_id=$1 AND id=$2", [candidate.organizationId, candidate.productId])).rows[0]!;
    const beforeActive = (await pool.query<{ tree_json: unknown }>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3", [candidate.organizationId, candidate.productId, candidate.activeId])).rows[0]!;
    const beforeDraft = (await pool.query<{ tree_json: unknown }>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3", [candidate.organizationId, candidate.productId, draft.draftVersionId])).rows[0]!;
    const beforeCommercial = (await pool.query<{ lines: string }>("SELECT count(*)::text lines FROM v2_sales_document_lines WHERE organization_id=$1 AND product_id=$2", [candidate.organizationId, candidate.productId])).rows[0]!;
    const input = previewInput(candidate.measurementMode, selectionKey, choiceValue), activeBefore = await activePrice(pool, candidate, input.selections), draftBefore = await preview.preview(candidate.organizationId, candidate.productId, input);
    const edited: ProductDraftOptionPricingImpact = impact.type === "multiplier" ? { ...impact, value: impact.value + 0.1 } : { ...impact, value: impact.value + 137 };
    const editId = request("edit"), saved = await service.updateDraftOptionPricing(context(candidate.organizationId, actor, editId), { productId: candidate.productId, draftVersionId: draft.draftVersionId, expectedDraftUpdatedAt: draft.draftUpdatedAt, businessRequestId: editId, optionId, choiceValue, impact: edited }); assert(saved.ok, "Draft Option Pricing save failed.");
    const replay = await service.updateDraftOptionPricing(context(candidate.organizationId, actor, editId), { productId: candidate.productId, draftVersionId: draft.draftVersionId, expectedDraftUpdatedAt: draft.draftUpdatedAt, businessRequestId: editId, optionId, choiceValue, impact: edited }); assert.deepEqual(replay, saved, "Exact Option Pricing request did not replay.");
    const draftAfter = await preview.preview(candidate.organizationId, candidate.productId, input), activeAfter = await activePrice(pool, candidate, input.selections); assert.notEqual(draftAfter.calculatedLineAmount.cents, draftBefore.calculatedLineAmount.cents, "Draft Preview did not use the edited Draft Option Pricing impact."); assert.equal(activeAfter, activeBefore, "Draft Option Pricing leaked into normal Active Sales pricing.");
    const reread = await reader.read(candidate.organizationId, candidate.productId); assert(reread, "Draft Option Pricing disappeared."); const option = reread.options.find(item => item.optionId === optionId)!; const choice = option.choices.find(item => item.choiceValue === choiceValue)!; assert.equal(option.selectionKey, selectionKey, "Option Pricing save changed selectionKey."); assert(choice, "Option Pricing save changed Choice identity.");
    const staleId = request("stale"), stale = await service.updateDraftOptionPricing(context(candidate.organizationId, actor, staleId), { productId: candidate.productId, draftVersionId: draft.draftVersionId, expectedDraftUpdatedAt: draft.draftUpdatedAt, businessRequestId: staleId, optionId, choiceValue, impact }); assert(!stale.ok && stale.error.code === "STALE_STATE", "Stale Option Pricing save was accepted.");
    const deniedId = request("denied"), denied = await service.updateDraftOptionPricing(context(candidate.organizationId, actor, deniedId, ["product.view"]), { productId: candidate.productId, draftVersionId: saved.value.draftVersionId, expectedDraftUpdatedAt: saved.value.draftUpdatedAt, businessRequestId: deniedId, optionId, choiceValue, impact: edited }); assert(!denied.ok && denied.error.code === "FORBIDDEN", "product.view edited Draft Option Pricing.");
    const active = await sales.getActivePricingConfiguration(brandedId<"OrganizationId">(candidate.organizationId), brandedId<"ProductId">(candidate.productId)); assert.equal(active?.id, candidate.activeId, "Normal Product resolution did not remain Active-only.");
    const afterProduct = (await pool.query("SELECT name,category,description,measurement_mode,workflow_intent,requires_proof_approval,requires_production_job,pbv2_active_tree_version_id FROM products WHERE organization_id=$1 AND id=$2", [candidate.organizationId, candidate.productId])).rows[0]!;
    const afterActive = (await pool.query<{ tree_json: unknown }>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3", [candidate.organizationId, candidate.productId, candidate.activeId])).rows[0]!;
    const afterDraft = (await pool.query<{ tree_json: unknown }>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3", [candidate.organizationId, candidate.productId, draft.draftVersionId])).rows[0]!;
    const afterCommercial = (await pool.query<{ lines: string }>("SELECT count(*)::text lines FROM v2_sales_document_lines WHERE organization_id=$1 AND product_id=$2", [candidate.organizationId, candidate.productId])).rows[0]!;
    assert.deepEqual(afterProduct, beforeProduct, "Draft Option Pricing save changed the Product row."); assert.equal(hash(afterActive.tree_json), hash(beforeActive.tree_json), "Draft Option Pricing save changed the Active tree."); assert.equal(hash(withoutOptionPricing(afterDraft.tree_json)), hash(withoutOptionPricing(beforeDraft.tree_json)), "Draft Option Pricing save changed a non-pricing Draft section."); assert.deepEqual(afterCommercial, beforeCommercial, "Draft Option Pricing save changed Quote or Order lines.");
    console.log(JSON.stringify({ product: candidate.name, activeVersion: candidate.activeId, draftVersion: draft.draftVersionId, impact: { before: impact, after: edited }, activePreview: activeBefore, draftPreview: { before: draftBefore.calculatedLineAmount.cents, after: draftAfter.calculatedLineAmount.cents } }, null, 2)); console.log("[p6c] Product Draft Option Pricing clone rehearsal passed.");
  } finally { await pool.end(); }
}
void main().catch(error => { console.error(`[p6c] ${error instanceof Error ? error.stack ?? error.message : String(error)}`); process.exitCode = 1; });
