import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { Pool } from "pg";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { PostgresProductDraftFormulaReader, PostgresProductDraftPricingPreview, PostgresProductVersionTransactionRunner } from "../infrastructure/products/postgresProductVersionLifecycle.js";
import { ProductVersionLifecycleApplicationService } from "../src/modules/products/productVersionLifecycle.js";
import type { OperationContext } from "../src/application/operation.js";
import { extractProductOptionPricingMatrix } from "../../shared/productOptionPricingMatrix.js";

const cloneHost="ep-soft-frost-aef6c2jb-pooler.c-2.us-east-2.aws.neon.tech";
const record=(value:unknown):Record<string,any>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,any>:{};
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const request=(label:string)=>`p6b-formula-${label}-${randomUUID()}`;
const context=(organizationId:string,userId:string,id:string,caps:readonly any[]=["product.edit"]):OperationContext=>({organizationId,operationId:id,businessRequest:{id,payloadFingerprint:id},principal:{kind:"staff",organizationId,userId,authority:{membershipId:`p6b-${organizationId}`,capabilities:caps}}});
type Candidate={organizationId:string;productId:string;name:string;measurementMode:"dimensions_required"|"quantity_only";activeId:string;activeUpdatedAt:Date;activeTree:unknown;draftId:string|null};
const previewInput=(mode:Candidate["measurementMode"])=>({quantity:2,...(mode==="dimensions_required"?{width:24,height:24}:{})});
const preserved=(tree:unknown)=>{const source=record(tree),meta=record(source.meta),pricing=structuredClone(record(meta.pricingV2));return{general:meta.general??null,options:source.nodes??null,basePricing:pricing,matrix:extractProductOptionPricingMatrix(source),materials:source.materials??meta.materials??null,routing:source.routing??meta.routing??null};};

async function main(){
 const url=requireV2M0CloneDatabaseUrl(),parsed=new URL(url);assert.equal(parsed.hostname,cloneHost,"P6B rehearsal refuses a database other than the authorized DEV clone.");assert.equal(parsed.pathname.replace(/^\//u,""),"neondb","P6B rehearsal refuses a database other than neondb.");
 const pool=new Pool({connectionString:url,max:4});
 try{
  const required=(await pool.query<{audit:string|null;requests:string|null;attributions:string|null}>("SELECT to_regclass('public.v2_audit_events') audit,to_regclass('public.v2_operation_requests') requests,to_regclass('public.v2_principal_attributions') attributions")).rows[0]!;
  assert(required.audit&&required.requests&&required.attributions,"P6B setup is incomplete: the authorized clone is missing required V2 lifecycle/audit relations.");
  const actor=(await pool.query<{id:string}>("SELECT id FROM users ORDER BY id LIMIT 1")).rows[0]?.id;assert(actor,"The authorized clone needs a Staff user.");
  const service=new ProductVersionLifecycleApplicationService(new PostgresProductVersionTransactionRunner(pool)),reader=new PostgresProductDraftFormulaReader(pool),preview=new PostgresProductDraftPricingPreview(pool);
  const libraryStats=(await pool.query<{references:string;formulas:string}>("SELECT count(*)::text references,count(DISTINCT pricing_formula_id)::text formulas FROM products WHERE pricing_formula_id IS NOT NULL")).rows[0]!;
  const candidates=(await pool.query<Candidate>(`SELECT p.organization_id AS "organizationId",p.id AS "productId",p.name,p.measurement_mode AS "measurementMode",a.id AS "activeId",a.updated_at AS "activeUpdatedAt",a.tree_json AS "activeTree",d.id AS "draftId" FROM products p JOIN pbv2_tree_versions a ON a.id=p.pbv2_active_tree_version_id AND a.status='ACTIVE' LEFT JOIN pbv2_tree_versions d ON d.organization_id=p.organization_id AND d.product_id=p.id AND d.status='DRAFT' WHERE p.is_active=TRUE ORDER BY p.id LIMIT 500`)).rows;
  let candidate:Candidate|undefined,formula:any,libraryCount=0,mixedCount=0;
  for(const item of candidates){if(item.measurementMode!=="dimensions_required")continue;if(!item.draftId){const activeMeta=record(record(item.activeTree).meta);if(typeof activeMeta.pricingFormula!=="string"||!activeMeta.pricingFormula.trim()||extractProductOptionPricingMatrix(item.activeTree))continue;const createId=request("create"),created=await service.createDraft(context(item.organizationId,actor,createId),{productId:item.productId,businessRequestId:createId,expectedActiveVersionUpdatedAt:item.activeUpdatedAt.toISOString()});assert(created.ok,`P6B setup failed while preparing Formula Product '${item.name}' (${item.productId}): ${created.ok?"":`${created.error.code} ${created.error.publicMessage}`}`);}
   const read=await reader.read(item.organizationId,item.productId);if(!read)continue;if(read.source==="library_reference_read_only")libraryCount++;if(read.source==="library_product_inputs_editable")mixedCount++;if(read.editable){candidate=item;formula=read;break;}
  }
  assert(candidate&&formula,"The authorized clone needs an embedded Formula Product Draft without Matrix pricing.");
  let libraryProtected=false;for(const item of candidates){const hasLibrary=(await pool.query<{id:string}>("SELECT id FROM products WHERE organization_id=$1 AND id=$2 AND pricing_formula_id IS NOT NULL",[item.organizationId,item.productId])).rows[0];if(!hasLibrary)continue;if(!item.draftId){const createId=request("library-draft"),created=await service.createDraft(context(item.organizationId,actor,createId),{productId:item.productId,businessRequestId:createId,expectedActiveVersionUpdatedAt:item.activeUpdatedAt.toISOString()});assert(created.ok,`P6B setup failed while preparing Formula Library Product '${item.name}' (${item.productId}): ${created.ok?"":`${created.error.code} ${created.error.publicMessage}`}`);}const library=await reader.read(item.organizationId,item.productId);if(!library||library.source!=="library_reference_read_only")continue;const beforeLibrary=(await pool.query<{id:string;expression:string;updated_at:Date}>("SELECT f.id,f.expression,f.updated_at FROM products p JOIN pricing_formulas f ON f.id=p.pricing_formula_id AND f.organization_id=p.organization_id WHERE p.organization_id=$1 AND p.id=$2",[item.organizationId,item.productId])).rows[0]!;const blockedId=request("library-blocked"),blocked=await service.updateDraftFormulaPricing(context(item.organizationId,actor,blockedId),{productId:item.productId,draftVersionId:library.draftVersionId,expectedDraftUpdatedAt:library.draftUpdatedAt,businessRequestId:blockedId,expression:library.expression,variables:library.variables});const afterLibrary=(await pool.query<{id:string;expression:string;updated_at:Date}>("SELECT f.id,f.expression,f.updated_at FROM products p JOIN pricing_formulas f ON f.id=p.pricing_formula_id AND f.organization_id=p.organization_id WHERE p.organization_id=$1 AND p.id=$2",[item.organizationId,item.productId])).rows[0]!;assert(!blocked.ok&&blocked.error.code==="CONFLICT","Formula Library reference was editable from Product Draft.");assert.deepEqual(afterLibrary,beforeLibrary,"Product Draft changed a shared Formula Library record.");libraryProtected=true;break;}assert(libraryStats.references===0||libraryProtected,"The clone has Formula Library references but no read-only representative was verified.");
  const beforeProduct=(await pool.query("SELECT name,category,description,measurement_mode,workflow_intent,requires_proof_approval,requires_production_job,pbv2_active_tree_version_id FROM products WHERE organization_id=$1 AND id=$2",[candidate.organizationId,candidate.productId])).rows[0]!;
  const beforeActive=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,candidate.activeId])).rows[0]!;
  const beforeDraft=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,formula.draftVersionId])).rows[0]!;
  const beforeCommercial=(await pool.query<{quotes:string;orders:string}>("SELECT count(*) FILTER (WHERE d.document_kind='quote')::text quotes,count(*) FILTER (WHERE d.document_kind='order')::text orders FROM v2_sales_document_lines l JOIN v2_sales_documents d ON d.organization_id=l.organization_id AND d.id=l.document_id WHERE l.organization_id=$1 AND l.product_id=$2",[candidate.organizationId,candidate.productId])).rows[0]!;
  const activeExpression=record(record(beforeActive.tree_json).meta).pricingFormula;assert.equal(typeof activeExpression,"string","The selected Active Product has no embedded formula.");
  const baseline=await preview.preview(candidate.organizationId,candidate.productId,previewInput(candidate.measurementMode));
  const expression=`(${formula.expression}) + 1`,editId=request("edit"),saved=await service.updateDraftFormulaPricing(context(candidate.organizationId,actor,editId),{productId:candidate.productId,draftVersionId:formula.draftVersionId,expectedDraftUpdatedAt:formula.draftUpdatedAt,businessRequestId:editId,expression,variables:formula.variables});assert(saved.ok,`Draft Formula save failed: ${saved.ok?"":saved.error.code} ${saved.ok?"":saved.error.publicMessage}; variables=${JSON.stringify(formula.variables)}`);
  const replay=await service.updateDraftFormulaPricing(context(candidate.organizationId,actor,editId),{productId:candidate.productId,draftVersionId:formula.draftVersionId,expectedDraftUpdatedAt:formula.draftUpdatedAt,businessRequestId:editId,expression,variables:formula.variables});assert.deepEqual(replay,saved,"Exact Formula request did not replay.");
  const draftPreview=await preview.preview(candidate.organizationId,candidate.productId,previewInput(candidate.measurementMode));assert.notEqual(draftPreview.calculatedLineAmount.cents,baseline.calculatedLineAmount.cents,"Draft Formula preview did not use the saved Draft expression.");
  const afterActive=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,candidate.activeId])).rows[0]!;const afterProduct=(await pool.query("SELECT name,category,description,measurement_mode,workflow_intent,requires_proof_approval,requires_production_job,pbv2_active_tree_version_id FROM products WHERE organization_id=$1 AND id=$2",[candidate.organizationId,candidate.productId])).rows[0]!;const afterDraft=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,formula.draftVersionId])).rows[0]!,afterCommercial=(await pool.query<{quotes:string;orders:string}>("SELECT count(*) FILTER (WHERE d.document_kind='quote')::text quotes,count(*) FILTER (WHERE d.document_kind='order')::text orders FROM v2_sales_document_lines l JOIN v2_sales_documents d ON d.organization_id=l.organization_id AND d.id=l.document_id WHERE l.organization_id=$1 AND l.product_id=$2",[candidate.organizationId,candidate.productId])).rows[0]!;
  assert.equal(hash(afterActive.tree_json),hash(beforeActive.tree_json),"Draft Formula save changed the Active tree.");assert.deepEqual(afterProduct,beforeProduct,"Draft Formula save changed the Product row.");assert.deepEqual(preserved(afterDraft.tree_json),preserved(beforeDraft.tree_json),"Draft Formula save changed a non-Formula Draft section.");assert.deepEqual(afterCommercial,beforeCommercial,"Draft Formula save changed commercial history.");
  const staleId=request("stale"),stale=await service.updateDraftFormulaPricing(context(candidate.organizationId,actor,staleId),{productId:candidate.productId,draftVersionId:formula.draftVersionId,expectedDraftUpdatedAt:formula.draftUpdatedAt,businessRequestId:staleId,expression,variables:formula.variables});assert(!stale.ok&&stale.error.code==="STALE_STATE","Stale Formula save was accepted.");
  const invalidId=request("invalid"),invalid=await service.updateDraftFormulaPricing(context(candidate.organizationId,actor,invalidId),{productId:candidate.productId,draftVersionId:saved.value.draftVersionId,expectedDraftUpdatedAt:saved.value.draftUpdatedAt,businessRequestId:invalidId,expression:"floor(q)",variables:saved.value.variables});assert(!invalid.ok&&invalid.error.code==="VALIDATION_ERROR","Unsupported Formula function was accepted.");
  const deniedId=request("denied"),denied=await service.updateDraftFormulaPricing(context(candidate.organizationId,actor,deniedId,["product.view"]),{productId:candidate.productId,draftVersionId:saved.value.draftVersionId,expectedDraftUpdatedAt:saved.value.draftUpdatedAt,businessRequestId:deniedId,expression,variables:saved.value.variables});assert(!denied.ok&&denied.error.code==="FORBIDDEN","product.view edited Formula settings.");
  const other=(await pool.query<{id:string}>("SELECT id FROM organizations WHERE id<>$1 LIMIT 1",[candidate.organizationId])).rows[0]?.id;assert(other,"The authorized clone needs a second organization.");assert.equal(await reader.read(other,candidate.productId),null,"Foreign tenant read Formula settings.");
  console.log(JSON.stringify({product:candidate.name,formulaSource:formula.source,activeFormula:activeExpression,draftFormula:saved.value.expression,baseline:baseline.calculatedLineAmount.cents,draftPreview:draftPreview.calculatedLineAmount.cents,formulaLibraryReferences:Number(libraryStats.references),formulaLibraryRecords:Number(libraryStats.formulas),libraryReadOnly:libraryProtected,matrixFormulaReadOnly:mixedCount},null,2));console.log("[p6b] Product Draft Formula clone rehearsal passed.");
 }finally{await pool.end();}
}
void main().catch(error=>{console.error(`[p6b] ${error instanceof Error?error.message:String(error)}`);process.exitCode=1;});
