import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { Pool } from "pg";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { PostgresProductDraftOptionsReader, PostgresProductDraftPricingMatrixReader, PostgresProductDraftPricingPreview, PostgresProductVersionTransactionRunner } from "../infrastructure/products/postgresProductVersionLifecycle.js";
import { PostgresProductsCompatibilityReader } from "../infrastructure/compatibility/postgresProductsRead.js";
import { ProductVersionLifecycleApplicationService, type ProductDraftPricingMatrix } from "../src/modules/products/productVersionLifecycle.js";
import type { OperationContext } from "../src/application/operation.js";
import { brandedId, currencyCode, decimalText } from "../src/modules/shared/commercialValues.js";
import { extractProductOptionPricingMatrix } from "../../shared/productOptionPricingMatrix.js";
import { resolveActivePbv2PricingInput } from "../src/modules/products/pbv2CompatibilityResolution.js";
import { V2PricingParityAdapter } from "../src/modules/pricing/v2PricingAdapter.js";

const cloneHost="ep-nameless-mud-aedtoak5-pooler.c-2.us-east-2.aws.neon.tech";
const request=(label:string)=>`p6a-matrix-${label}-${randomUUID()}`;
const context=(organizationId:string,userId:string,id:string,caps:readonly any[]=["product.edit"]):OperationContext=>({organizationId,operationId:id,businessRequest:{id,payloadFingerprint:id},principal:{kind:"staff",organizationId,userId,authority:{membershipId:`p6a-${organizationId}`,capabilities:caps}}});
const record=(value:unknown):Record<string,any>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,any>:{};
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const dimensionInput=(measurementMode:"dimensions_required"|"quantity_only")=>measurementMode==="dimensions_required"?{width:100,height:100}:{};
const choiceDimension=(tree:unknown)=>Object.values(record(record(tree).nodes)).map(record).flatMap(node=>{const input=record(node.input),choices=Array.isArray(node.choices)?node.choices.map(record).filter(choice=>typeof choice.value==="string"||typeof choice.value==="number"||typeof choice.value==="boolean"):[];const key=typeof input.selectionKey==="string"?input.selectionKey:typeof node.key==="string"?node.key:typeof node.id==="string"?node.id:"";return node.kind==="question"&&key&&choices.length?[{key,choices}]:[];})[0] as {key:string;choices:Record<string,any>[]}|undefined;
const preservedSections=(tree:unknown)=>{const source=record(tree),meta=record(source.meta),pricing=structuredClone(record(meta.pricingV2));delete pricing.optionMatrixPricingUnit;return{general:meta.general??null,formula:meta.pricingFormula??null,materials:source.materials??meta.materials??null,routing:source.routing??meta.routing??null,basePricing:pricing};};
type Candidate={organizationId:string;productId:string;name:string;measurementMode:"dimensions_required"|"quantity_only";activeId:string;activeUpdatedAt:Date;activeTree:unknown;draftId:string|null};
const matrixSelections=(matrix:ProductDraftPricingMatrix)=>Object.fromEntries(matrix.dimensions.map(dimension=>[dimension.selectionKey,matrix.rows[0]!.combination[dimension.selectionKey]]));
const activePrice=async(pool:Pool,candidate:Candidate,selections:Record<string,unknown>)=>{const row=(await pool.query<{pricing_profile_key:string|null;schema_version:number;updated_at:Date;tree_json:unknown}>("SELECT p.pricing_profile_key,a.schema_version,a.updated_at,a.tree_json FROM products p JOIN pbv2_tree_versions a ON a.organization_id=p.organization_id AND a.product_id=p.id AND a.id=p.pbv2_active_tree_version_id WHERE p.organization_id=$1 AND p.id=$2",[candidate.organizationId,candidate.productId])).rows[0]!;const sellable={organizationId:brandedId<"OrganizationId">(candidate.organizationId),productId:brandedId<"ProductId">(candidate.productId),displayName:candidate.name,lifecycle:"active" as const,pricingConfiguration:{id:brandedId<"PricingConfigurationId">(candidate.activeId),version:row.updated_at.toISOString(),contentHash:"sha256:active"},requiresDimensions:candidate.measurementMode!=="quantity_only",pricingCurrency:currencyCode("USD")};const dimensions=candidate.measurementMode==="quantity_only"?undefined:{width:decimalText("100"),height:decimalText("100"),unit:"in" as const};const resolved=resolveActivePbv2PricingInput(sellable,{id:candidate.activeId,schemaVersion:row.schema_version,publishedAt:row.updated_at.toISOString(),treeJson:row.tree_json,productMeasurementMode:candidate.measurementMode,productPricingProfileKey:row.pricing_profile_key,formula:null},{organizationId:brandedId<"OrganizationId">(candidate.organizationId),productId:brandedId<"ProductId">(candidate.productId),quantity:1,...(dimensions?{dimensions}:{}),selections:selections as any});assert(resolved.ok,"Active Matrix pricing could not resolve.");const value=await new V2PricingParityAdapter().calculate({organizationId:brandedId<"OrganizationId">(candidate.organizationId),sellableProduct:{...sellable,pricingConfiguration:{...sellable.pricingConfiguration,contentHash:resolved.value.resolvedConfiguration.pricingConfigurationContentHash}},resolvedConfiguration:resolved.value.resolvedConfiguration,rules:resolved.value.rules,pricingContext:{channel:"staff",effectiveAt:new Date().toISOString()}});return value.calculatedLineAmount.cents;};

async function main(){
 const url=requireV2M0CloneDatabaseUrl(),parsed=new URL(url);assert.equal(parsed.hostname,cloneHost,"P6A rehearsal refuses a database other than the authorized DEV clone.");assert.equal(parsed.pathname.replace(/^\//u,""),"neondb","P6A rehearsal refuses a database other than neondb.");
 const pool=new Pool({connectionString:url,max:4});
 try{
  await pool.query("SELECT 1");const actor=(await pool.query<{id:string}>("SELECT id FROM users ORDER BY id LIMIT 1")).rows[0]?.id;assert(actor,"The authorized clone needs a Staff user.");
  const service=new ProductVersionLifecycleApplicationService(new PostgresProductVersionTransactionRunner(pool)),reader=new PostgresProductDraftPricingMatrixReader(pool),preview=new PostgresProductDraftPricingPreview(pool),options=new PostgresProductDraftOptionsReader(pool),sales=new PostgresProductsCompatibilityReader(pool);
  const candidates=(await pool.query<Candidate>(`SELECT p.organization_id AS "organizationId",p.id AS "productId",p.name,p.measurement_mode AS "measurementMode",a.id AS "activeId",a.updated_at AS "activeUpdatedAt",a.tree_json AS "activeTree",d.id AS "draftId" FROM products p JOIN pbv2_tree_versions a ON a.id=p.pbv2_active_tree_version_id AND a.status='ACTIVE' LEFT JOIN pbv2_tree_versions d ON d.organization_id=p.organization_id AND d.product_id=p.id AND d.status='DRAFT' WHERE p.is_active=TRUE ORDER BY p.id LIMIT 500`)).rows;
  let candidate:Candidate|undefined,matrix:ProductDraftPricingMatrix|undefined,protectedMatrix:{candidate:Candidate;matrix:ProductDraftPricingMatrix}|undefined,activeMatrices=0,draftMatrices=0,editableMatrices=0,previewableMatrices=0;const unavailable:unknown[]=[];
  for(const item of candidates){const activeMatrix=extractProductOptionPricingMatrix(record(item.activeTree));if(!activeMatrix&&!item.draftId)continue;if(activeMatrix)activeMatrices++;if(activeMatrix&&!item.draftId){const id=request("create-draft"),created=await service.createDraft(context(item.organizationId,actor,id),{productId:item.productId,businessRequestId:id,expectedActiveVersionUpdatedAt:item.activeUpdatedAt.toISOString()});if(!created.ok)continue;}const value=await reader.read(item.organizationId,item.productId);if(!value)continue;draftMatrices++;if(!value.editable||!value.rows.length||!value.dimensions.length){if(!protectedMatrix&&!value.editable)protectedMatrix={candidate:item,matrix:value};unavailable.push({name:item.name,editable:value.editable,reason:value.unavailableReason,dimensions:value.dimensions.length,rows:value.rows.length});continue;}editableMatrices++;try{await preview.preview(item.organizationId,item.productId,{quantity:1,...dimensionInput(item.measurementMode),selections:matrixSelections(value)});previewableMatrices++;candidate=item;matrix=value;break;}catch{/* Not a compatibility-previewable representative. */}}
  if(!candidate||!matrix){for(const item of candidates){if(extractProductOptionPricingMatrix(record(item.activeTree))||typeof record(record(item.activeTree).meta).pricingFormula==="string")continue;const commercial=(await pool.query<{count:string}>("SELECT count(*)::text count FROM v2_sales_document_lines WHERE organization_id=$1 AND product_id=$2",[item.organizationId,item.productId])).rows[0];if(Number(commercial?.count??1)!==0)continue;const use=choiceDimension(item.activeTree);if(!use)continue;if(!item.draftId){const id=request("create-fallback-draft"),created=await service.createDraft(context(item.organizationId,actor,id),{productId:item.productId,businessRequestId:id,expectedActiveVersionUpdatedAt:item.activeUpdatedAt.toISOString()});if(!created.ok)continue;}const draft=(await pool.query<{id:string;updated_at:Date;tree_json:unknown}>("SELECT id,updated_at,tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND status='DRAFT' ORDER BY updated_at DESC LIMIT 1",[item.organizationId,item.productId])).rows[0];if(!draft||extractProductOptionPricingMatrix(record(draft.tree_json)))continue;const base=record(record(draft.tree_json).meta).pricingV2,unit=record(base.base).perPieceCents!==undefined?"per_piece" as const:"per_square_foot" as const,id=request("seed-real-draft"),seed=await service.updateDraftPricingMatrix(context(item.organizationId,actor,id),{productId:item.productId,draftVersionId:draft.id,expectedDraftUpdatedAt:draft.updated_at.toISOString(),businessRequestId:id,matrixId:`matrix:${draft.id}`,pricingUnit:unit,dimensions:[use.key],rows:use.choices.map((choice,index)=>({rowId:`new:seed-${index}`,combination:{[use.key]:choice.value},baseRateCents:500,tierBasis:null,tiers:[]}))});if(!seed.ok)continue;try{await preview.preview(item.organizationId,item.productId,{quantity:1,...dimensionInput(item.measurementMode),selections:matrixSelections(seed.value)});candidate=item;matrix=seed.value;break;}catch{/* Use the next existing non-commercial-compatible candidate. */}}}
  if(!candidate||!matrix)console.log(JSON.stringify({activeMatrices,draftMatrices,editableMatrices,previewableMatrices,unavailable:unavailable.slice(0,20)},null,2));assert(candidate&&matrix,"The authorized clone needs an editable Draft Matrix representative.");
  if(protectedMatrix){const protectedId=request("formula-protection"),blocked=await service.updateDraftPricingMatrix(context(protectedMatrix.candidate.organizationId,actor,protectedId),{productId:protectedMatrix.candidate.productId,draftVersionId:protectedMatrix.matrix.draftVersionId,expectedDraftUpdatedAt:protectedMatrix.matrix.draftUpdatedAt,businessRequestId:protectedId,matrixId:protectedMatrix.matrix.matrixId,pricingUnit:protectedMatrix.matrix.pricingUnit,dimensions:protectedMatrix.matrix.dimensions.map(value=>value.selectionKey),rows:protectedMatrix.matrix.rows});assert(!blocked.ok&&blocked.error.code==="CONFLICT","Matrix plus Formula mutation was accepted.");}
  const beforeProduct=(await pool.query("SELECT name,category,description,measurement_mode,workflow_intent,requires_proof_approval,requires_production_job,pbv2_active_tree_version_id FROM products WHERE organization_id=$1 AND id=$2",[candidate.organizationId,candidate.productId])).rows[0]!;
  const beforeActive=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,candidate.activeId])).rows[0]!;
  const beforeDraft=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,matrix.draftVersionId])).rows[0]!,beforeCommercial=(await pool.query<{quote_lines:string;order_lines:string}>("SELECT count(*) FILTER (WHERE d.document_kind='quote')::text quote_lines,count(*) FILTER (WHERE d.document_kind='order')::text order_lines FROM v2_sales_document_lines l JOIN v2_sales_documents d ON d.organization_id=l.organization_id AND d.id=l.document_id WHERE l.organization_id=$1 AND l.product_id=$2",[candidate.organizationId,candidate.productId])).rows[0]!;
  const active=await sales.getActivePricingConfiguration(brandedId<"OrganizationId">(candidate.organizationId),brandedId<"ProductId">(candidate.productId));assert.equal(active?.id,candidate.activeId,"Normal Product resolution did not remain Active-only.");
  const activePreview=await activePrice(pool,candidate,matrixSelections(matrix)),baseline=await preview.preview(candidate.organizationId,candidate.productId,{quantity:1,...dimensionInput(candidate.measurementMode),selections:matrixSelections(matrix)});
  const editedRow={...matrix.rows[0]!,baseRateCents:matrix.rows[0]!.baseRateCents+137};const editId=request("rate");const saved=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,editId),{productId:candidate.productId,draftVersionId:matrix.draftVersionId,expectedDraftUpdatedAt:matrix.draftUpdatedAt,businessRequestId:editId,matrixId:matrix.matrixId,pricingUnit:matrix.pricingUnit,dimensions:matrix.dimensions.map(value=>value.selectionKey),rows:[editedRow,...matrix.rows.slice(1)]});assert(saved.ok,"Draft Matrix row rate save failed.");assert.equal(saved.value.rows[0]!.baseRateCents,editedRow.baseRateCents,"Draft Matrix did not persist the edited row rate.");
  const replay=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,editId),{productId:candidate.productId,draftVersionId:matrix.draftVersionId,expectedDraftUpdatedAt:matrix.draftUpdatedAt,businessRequestId:editId,matrixId:matrix.matrixId,pricingUnit:matrix.pricingUnit,dimensions:matrix.dimensions.map(value=>value.selectionKey),rows:[editedRow,...matrix.rows.slice(1)]});assert.deepEqual(replay,saved,"Exact Matrix request did not replay.");let exercised=saved.value;if(exercised.rows.length>1){const removeId=request("remove-row"),removed=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,removeId),{productId:candidate.productId,draftVersionId:exercised.draftVersionId,expectedDraftUpdatedAt:exercised.draftUpdatedAt,businessRequestId:removeId,matrixId:exercised.matrixId,pricingUnit:exercised.pricingUnit,dimensions:exercised.dimensions.map(value=>value.selectionKey),rows:exercised.rows.slice(1)});assert(removed.ok,"Draft Matrix row removal failed.");const addId=request("add-row"),added=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,addId),{productId:candidate.productId,draftVersionId:removed.value.draftVersionId,expectedDraftUpdatedAt:removed.value.draftUpdatedAt,businessRequestId:addId,matrixId:removed.value.matrixId,pricingUnit:removed.value.pricingUnit,dimensions:removed.value.dimensions.map(value=>value.selectionKey),rows:[editedRow,...removed.value.rows]});assert(added.ok&&added.value.rows.some(row=>row.rowId===editedRow.rowId),"Draft Matrix row add did not preserve stable identity.");exercised=added.value;}
  const draftPreview=await preview.preview(candidate.organizationId,candidate.productId,{quantity:1,...dimensionInput(candidate.measurementMode),selections:matrixSelections(exercised)});assert.equal(hash(beforeActive.tree_json),hash((await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,candidate.activeId])).rows[0]!.tree_json),"Draft Matrix save changed the Active tree.");
  const duplicateId=request("duplicate"),duplicate=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,duplicateId),{productId:candidate.productId,draftVersionId:exercised.draftVersionId,expectedDraftUpdatedAt:exercised.draftUpdatedAt,businessRequestId:duplicateId,matrixId:exercised.matrixId,pricingUnit:exercised.pricingUnit,dimensions:exercised.dimensions.map(value=>value.selectionKey),rows:[...exercised.rows,{...exercised.rows[0]!,rowId:"new:duplicate"}]});assert(!duplicate.ok&&duplicate.error.code==="VALIDATION_ERROR","Duplicate Matrix combination was accepted.");
  const invalidDimensionId=request("dimension"),invalidDimension=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,invalidDimensionId),{productId:candidate.productId,draftVersionId:exercised.draftVersionId,expectedDraftUpdatedAt:exercised.draftUpdatedAt,businessRequestId:invalidDimensionId,matrixId:exercised.matrixId,pricingUnit:exercised.pricingUnit,dimensions:[...exercised.dimensions.map(value=>value.selectionKey),"missing-option"],rows:exercised.rows});assert(!invalidDimension.ok&&invalidDimension.error.code==="VALIDATION_ERROR","Unknown Matrix dimension was accepted.");
  const invalidChoiceId=request("choice"),firstDimension=exercised.dimensions[0]!,invalidChoice=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,invalidChoiceId),{productId:candidate.productId,draftVersionId:exercised.draftVersionId,expectedDraftUpdatedAt:exercised.draftUpdatedAt,businessRequestId:invalidChoiceId,matrixId:exercised.matrixId,pricingUnit:exercised.pricingUnit,dimensions:exercised.dimensions.map(value=>value.selectionKey),rows:[{...exercised.rows[0]!,combination:{...exercised.rows[0]!.combination,[firstDimension.selectionKey]:"not-a-choice"}},...exercised.rows.slice(1)]});assert(!invalidChoice.ok&&invalidChoice.error.code==="VALIDATION_ERROR","Invalid Matrix choice was accepted.");
  const currentOptions=await options.read(candidate.organizationId,candidate.productId);assert(currentOptions,"Draft Options read failed.");const referencedOption=currentOptions.options.find(option=>{const node=record(record(beforeDraft.tree_json).nodes)[option.optionId],input=record(node.input),key=typeof input.selectionKey==="string"?input.selectionKey:typeof node.key==="string"?node.key:option.optionId;return exercised.dimensions.some(dimension=>dimension.selectionKey===key);});assert(referencedOption,"Matrix dimension did not project to a Draft Option.");const removeId=request("protected-option");const removal=await service.updateDraftOptions(context(candidate.organizationId,actor,removeId),{productId:candidate.productId,draftVersionId:currentOptions.draftVersionId,expectedDraftUpdatedAt:currentOptions.draftUpdatedAt,businessRequestId:removeId,options:currentOptions.options.filter(option=>option.optionId!==referencedOption!.optionId)});assert(!removal.ok&&removal.error.code==="CONFLICT","Matrix-referenced option removal was accepted.");
  const labelId=request("label"),renamed=await service.updateDraftOptions(context(candidate.organizationId,actor,labelId),{productId:candidate.productId,draftVersionId:currentOptions.draftVersionId,expectedDraftUpdatedAt:currentOptions.draftUpdatedAt,businessRequestId:labelId,options:currentOptions.options.map(option=>option.optionId===referencedOption!.optionId?{...option,label:`${option.label} Draft`.slice(0,160)}:option)});assert(renamed.ok,"Matrix dimension label rename failed.");const renamedOptions=await options.read(candidate.organizationId,candidate.productId);assert(renamedOptions,"Draft Options disappeared after label rename.");const choice=renamedOptions.options.find(option=>option.optionId===referencedOption!.optionId)?.choices.find(value=>value.choiceValue===String(exercised.rows[0]!.combination[firstDimension.selectionKey]));assert(choice,"Matrix row choice did not project to a Draft Option choice.");const choiceRemovalId=request("protected-choice"),choiceRemoval=await service.updateDraftOptions(context(candidate.organizationId,actor,choiceRemovalId),{productId:candidate.productId,draftVersionId:renamedOptions.draftVersionId,expectedDraftUpdatedAt:renamedOptions.draftUpdatedAt,businessRequestId:choiceRemovalId,options:renamedOptions.options.map(option=>option.optionId===referencedOption!.optionId?{...option,choices:option.choices.filter(value=>value.choiceValue!==choice!.choiceValue),defaultValue:option.defaultValue===choice!.choiceValue?null:option.defaultValue}:option)});assert(!choiceRemoval.ok&&choiceRemoval.error.code==="CONFLICT","Matrix-referenced choice removal was accepted.");const afterLabel=await reader.read(candidate.organizationId,candidate.productId);assert(afterLabel&&afterLabel.dimensions.some(dimension=>dimension.selectionKey===firstDimension.selectionKey),"Option label rename changed Matrix identity.");
  const staleId=request("stale"),stale=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,staleId),{productId:candidate.productId,draftVersionId:matrix.draftVersionId,expectedDraftUpdatedAt:matrix.draftUpdatedAt,businessRequestId:staleId,matrixId:matrix.matrixId,pricingUnit:matrix.pricingUnit,dimensions:matrix.dimensions.map(value=>value.selectionKey),rows:matrix.rows});assert(!stale.ok&&stale.error.code==="STALE_STATE","Stale Matrix save was accepted.");const deniedId=request("denied"),denied=await service.updateDraftPricingMatrix(context(candidate.organizationId,actor,deniedId,["product.view"]),{productId:candidate.productId,draftVersionId:afterLabel.draftVersionId,expectedDraftUpdatedAt:afterLabel.draftUpdatedAt,businessRequestId:deniedId,matrixId:afterLabel.matrixId,pricingUnit:afterLabel.pricingUnit,dimensions:afterLabel.dimensions.map(value=>value.selectionKey),rows:afterLabel.rows});assert(!denied.ok&&denied.error.code==="FORBIDDEN","product.view edited Draft Matrix.");
  const other=(await pool.query<{id:string}>("SELECT id FROM organizations WHERE id<>$1 LIMIT 1",[candidate.organizationId])).rows[0]?.id;assert(other,"The authorized clone needs a second organization.");assert.equal(await reader.read(other,candidate.productId),null,"Foreign tenant read Draft Matrix.");
  const afterProduct=(await pool.query("SELECT name,category,description,measurement_mode,workflow_intent,requires_proof_approval,requires_production_job,pbv2_active_tree_version_id FROM products WHERE organization_id=$1 AND id=$2",[candidate.organizationId,candidate.productId])).rows[0]!,afterActive=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,candidate.activeId])).rows[0]!,afterDraft=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3",[candidate.organizationId,candidate.productId,matrix.draftVersionId])).rows[0]!,afterCommercial=(await pool.query<{quote_lines:string;order_lines:string}>("SELECT count(*) FILTER (WHERE d.document_kind='quote')::text quote_lines,count(*) FILTER (WHERE d.document_kind='order')::text order_lines FROM v2_sales_document_lines l JOIN v2_sales_documents d ON d.organization_id=l.organization_id AND d.id=l.document_id WHERE l.organization_id=$1 AND l.product_id=$2",[candidate.organizationId,candidate.productId])).rows[0]!;assert.deepEqual(afterProduct,beforeProduct,"Matrix save changed the Product row.");assert.equal(afterProduct.pbv2_active_tree_version_id,beforeProduct.pbv2_active_tree_version_id,"Matrix save changed the Active pointer.");assert.deepEqual(afterActive.tree_json,beforeActive.tree_json,"Matrix save changed the Active tree.");assert.deepEqual(preservedSections(afterDraft.tree_json),preservedSections(beforeDraft.tree_json),"Matrix save changed a non-pricing Draft section.");assert.deepEqual(afterCommercial,beforeCommercial,"Matrix save changed Quote or Order lines.");
  assert.notEqual(draftPreview.calculatedLineAmount.cents,activePreview,"Draft Matrix pricing leaked into Active pricing or did not use the edited Draft row.");console.log(JSON.stringify({product:candidate.name,activeVersion:candidate.activeId,draftVersion:matrix.draftVersionId,activePreview,draftPreview:draftPreview.calculatedLineAmount.cents,editedRowRate:editedRow.baseRateCents,pricingUnit:matrix.pricingUnit},null,2));console.log("[p6a] Product Draft Matrix clone rehearsal passed.");
 }finally{await pool.end();}
}
void main().catch(error=>{console.error(`[p6a] ${error instanceof Error?error.message:String(error)}`);process.exitCode=1;});
