import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { Pool, type PoolClient } from "pg";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { PostgresProductionTransactionRunner } from "../infrastructure/production/postgresProductionTransaction.js";
import { PostgresProductionMaterialConsumptionTransactionRunner } from "../infrastructure/production/postgresMaterialConsumptionTransaction.js";
import { ProductionApplicationService } from "../src/modules/production/productionApplication.js";
import { ProductionMaterialConsumptionApplicationService } from "../src/modules/production/materialConsumption.js";
import { brandedId } from "../src/modules/shared/commercialValues.js";
import type { OperationContext } from "../src/application/operation.js";

const cloneHost = "ep-soft-frost-aef6c2jb-pooler.c-2.us-east-2.aws.neon.tech";
const request = (label: string) => `p7c-${label}-${randomUUID()}`;
const context = (organizationId: string, userId: string, id: string, capabilities: readonly string[] = ["production.view", "production.work", "production.complete"]): OperationContext => ({ organizationId, operationId: id, businessRequest: { id, payloadFingerprint: id }, principal: { kind: "staff", organizationId, userId, authority: { membershipId: `p7c-${organizationId}`, capabilities: capabilities as any } } });
const assertOk = (value: unknown, message: string): asserts value => assert.ok(value, message);
type Fixture = Readonly<{ org: string; other: string; user: string; workArt: string; material: string; unplanned: string; requirement: string }>;

const fixture = async (c: PoolClient): Promise<Fixture> => {
  const x = randomUUID(), org=`p7c-${x}`, other=`p7c-other-${x}`, user=`p7c-user-${x}`, customer=`p7c-customer-${x}`, type=`p7c-type-${x}`, product=`p7c-product-${x}`, version=`p7c-version-${x}`, order=`p7c-order-${x}`, line=`p7c-line-${x}`, file=`p7c-file-${x}`, art=`p7c-art-${x}`, route=`p7c-route-${x}`, pre=`p7c-pre-${x}`, prodStep=`p7c-prod-step-${x}`, template=`p7c-template-${x}`, material=`p7c-grommets-${x}`, unplanned=`p7c-tape-${x}`, recipe=`p7c-recipe-${x}`, component=`p7c-component-${x}`, requirement=`p7c-requirement-${x}`;
  const tree={schemaVersion:2,rootNodeIds:["finish"],nodes:{finish:{id:"finish",kind:"question",label:"Finish",input:{type:"select",selectionKey:"finish",defaultValue:"standard"},choices:[{value:"standard",label:"Standard"}]}},meta:{pricingV2:{base:{perPieceCents:1000}}}};
  await c.query("BEGIN"); try {
    await c.query("INSERT INTO organizations(id,name,slug) VALUES($1,'P7C',$1),($2,'P7C Other',$2)",[org,other]);
    await c.query("INSERT INTO users(id,email,role) VALUES($1,$2,'owner')",[user,`${user}@test`]);
    await c.query("INSERT INTO customers(id,organization_id,company_name,display_name,is_active,status) VALUES($1,$2,'P7C','P7C',true,'active')",[customer,org]);
    await c.query("INSERT INTO product_types(id,organization_id,name,routing_mode) VALUES($1,$2,'P7C','no_route')",[type,org]);
    await c.query("INSERT INTO products(id,organization_id,name,description,is_active,measurement_mode,product_type_id) VALUES($1,$2,'P7C','P7C',true,'quantity_only',$3)",[product,org,type]);
    await c.query("INSERT INTO pbv2_tree_versions(id,organization_id,product_id,status,schema_version,tree_json,published_at) VALUES($1,$2,$3,'ACTIVE',2,$4::jsonb,now())",[version,org,product,JSON.stringify(tree)]);
    await c.query("UPDATE products SET pbv2_active_tree_version_id=$1 WHERE organization_id=$2 AND id=$3",[version,org,product]);
    await c.query("INSERT INTO materials(id,organization_id,name,sku,type,cost_per_unit,stock_quantity,consumption_unit,is_active) VALUES($1,$2,'P7C Grommets','P7C-GROM','consumable',1,500,'each',true),($3,$2,'P7C Tape','P7C-TAPE','consumable',1,25,'each',true)",[material,org,unplanned]);
    await c.query("INSERT INTO v2_product_recipes(id,organization_id,product_id,product_version_id,updated_by_user_id) VALUES($1,$2,$3,$4,$5)",[recipe,org,product,version,user]);
    await c.query("INSERT INTO v2_product_recipe_components(id,organization_id,recipe_id,material_id,position,quantity,quantity_unit,quantity_kind,material_name_snapshot,material_sku_snapshot) VALUES($1,$2,$3,$4,0,2,'each','per_piece','P7C Grommets','P7C-GROM')",[component,org,recipe,material]);
    await c.query("INSERT INTO v2_sales_documents(id,organization_id,document_kind,business_number,display_number,customer_id,currency,terms_json) VALUES($1,$2,'order',1,$3,$4,'USD','{}')",[order,org,`P7C-${x}`,customer]);
    await c.query("INSERT INTO v2_sales_order_details(document_id,organization_id) VALUES($1,$2)",[order,org]);
    await c.query("INSERT INTO v2_sales_document_lines(id,organization_id,document_id,position,product_id,description,quantity,currency,calculated_unit_cents,calculated_line_cents,selling_unit_cents,selling_line_cents,pricing_result_id,pricing_evidence_fingerprint,resolved_configuration,pricing_result,selling_price_decision,production_requirement_state,production_requirement_fingerprint,production_requirement_count) VALUES($1,$2,$3,0,$4,'P7C',100,'USD',1,100,1,100,'p7c','sha256:p7c','{}','{}','{}','configured',$5,1)",[line,org,order,product,`sha256:${"a".repeat(64)}`]);
    await c.query("INSERT INTO v2_order_line_material_requirements(id,organization_id,order_document_id,order_line_id,source_product_version_id,source_recipe_id,source_recipe_component_id,source_configuration_id,material_id,material_name_snapshot,material_sku_snapshot,quantity,quantity_unit,quantity_mode) VALUES($1,$2,$3,$4,$5,$6,$7,$5,$8,'P7C Grommets','P7C-GROM',200,'each','per_piece')",[requirement,org,order,line,version,recipe,component,material]);
    await c.query("INSERT INTO v2_sales_line_production_requirements(organization_id,document_id,order_line_id,requirement_key,side) VALUES($1,$2,$3,'front','front')",[org,order,line]);
    await c.query("INSERT INTO v2_artwork_files(id,organization_id,storage_provider,object_key,original_filename,display_filename,content_type,byte_size,source_kind) VALUES($1,$2,'clone',$3,'p7c.pdf','p7c.pdf','application/pdf',1,'customer_upload')",[file,org,`p7c/${x}`]);
    await c.query("INSERT INTO v2_artwork_assignments(id,organization_id,artwork_file_id,order_document_id,order_line_id,purpose,side,identity_fingerprint) VALUES($1,$2,$3,$4,$5,'production','front',$6)",[art,org,file,order,line,`sha256:${"b".repeat(64)}`]);
    await c.query("INSERT INTO v2_route_templates(id,organization_id,name,normalized_name,definition_fingerprint) VALUES($1,$2,'P7C','p7c','p7c')",[template,org]);
    await c.query("INSERT INTO v2_route_instances(id,organization_id,order_document_id,order_line_id,source_template_id,source_template_revision,source_template_fingerprint,route_state,current_step_id) VALUES($1,$2,$3,$4,$5,1,'p7c','active',$6)",[route,org,order,line,template,prodStep]);
    await c.query("INSERT INTO v2_route_instance_steps(id,organization_id,route_instance_id,position,step_kind) VALUES($1,$2,$3,0,'prepress'),($4,$2,$3,1,'production')",[pre,org,route,prodStep]);
    await c.query("INSERT INTO v2_prepress_units(id,organization_id,order_document_id,order_line_id,artwork_assignment_id,artwork_file_id,side,created_principal_kind,created_principal_subject,started_at,started_principal_kind,started_principal_subject,completed_at,completed_principal_kind,completed_principal_subject) VALUES($1,$2,$3,$4,$5,$6,'front','staff',$7,now(),'staff',$7,now(),'staff',$7)",[`${pre}-unit`,org,order,line,art,file,user]);
    await c.query("COMMIT");
  } catch (error) { await c.query("ROLLBACK"); throw error; }
  return {org,other,user,workArt:art,material,unplanned,requirement};
};

const main = async () => {
  const url=requireV2M0CloneDatabaseUrl(), target=new URL(url);
  assert.equal(target.hostname,cloneHost,"P7C refuses a database other than the authorized MAIN-derived DEV clone."); assert.equal(target.pathname.replace(/^\//u,""),"neondb","P7C refuses a database other than neondb.");
  const pool=new Pool({connectionString:url,max:8,application_name:"p7c-material-consumption-rehearsal"});
  try { const c=await pool.connect(); try {
    const tables=(await c.query<{facts:string|null;requirements:string|null;works:string|null}>("SELECT to_regclass('public.v2_production_material_consumptions') facts,to_regclass('public.v2_order_line_material_requirements') requirements,to_regclass('public.v2_production_works') works")).rows[0]!; assertOk(tables.facts&&tables.requirements&&tables.works,"P7C setup is incomplete: required relations are missing.");
    const f=await fixture(c), production=new ProductionApplicationService(new PostgresProductionTransactionRunner(pool)), consumption=new ProductionMaterialConsumptionApplicationService(new PostgresProductionMaterialConsumptionTransactionRunner(pool));
    const opened=await production.open(context(f.org,f.user,request("open")),{businessRequestId:request("bad") ,artworkAssignmentId:brandedId<"ArtworkAssignmentId">(f.workArt)}); // deliberately replaced below with one matching identity
    assert.ok(!opened.ok,"P7C matching request guard must reject mismatched business identities.");
    const openId=request("open"); const workOpen=await production.open(context(f.org,f.user,openId),{businessRequestId:openId,artworkAssignmentId:brandedId<"ArtworkAssignmentId">(f.workArt)}); assertOk(workOpen.ok,"P7C could not open Production work.");
    const startId=request("start"); const initial=await production.start(context(f.org,f.user,startId),{businessRequestId:startId,productionWorkId:workOpen.value.work.productionWorkId,stationKey:"flatbed",kind:"initial"}); assertOk(initial.ok&&initial.value.attempt,"P7C could not start an initial Production attempt.");
    const attempt=initial.value.attempt!; const stockBefore=(await c.query<{id:string;stock_quantity:string}>("SELECT id,stock_quantity::text FROM materials WHERE organization_id=$1 ORDER BY id",[f.org])).rows;
    const record=async(label:string,input:Omit<Parameters<typeof consumption.record>[1],"businessRequestId">)=>{const id=request(label);const result=await consumption.record(context(f.org,f.user,id),{...input,businessRequestId:id});assertOk(result.ok,`P7C ${label} failed: ${result.ok?"":result.error.publicMessage}`);return result.value;};
    const firstId=request("consume-80"); const firstInput={businessRequestId:firstId,productionWorkId:workOpen.value.work.productionWorkId,productionAttemptId:attempt.productionAttemptId,materialId:f.material,requirementId:brandedId<"OrderLineMaterialRequirementId">(f.requirement),quantity:"80",unit:"each" as const,kind:"consumed" as const};
    const firstResult=await consumption.record(context(f.org,f.user,firstId),firstInput);assertOk(firstResult.ok,`P7C initial consumption failed: ${firstResult.ok?"":`${firstResult.error.code} ${firstResult.error.publicMessage}`}`);const first=firstResult.value;
    const replay=await consumption.record(context(f.org,f.user,firstId),firstInput); assertOk(replay.ok&&replay.value.consumptionId===first.consumptionId,"P7C replay duplicated consumption");
    const badUnit=await consumption.record(context(f.org,f.user,"bad-unit"),{businessRequestId:"bad-unit",productionWorkId:workOpen.value.work.productionWorkId,productionAttemptId:attempt.productionAttemptId,materialId:f.unplanned,quantity:"1",unit:"sheet",kind:"consumed"});assert.ok(!badUnit.ok,"P7C accepted a Material consumption unit mismatch");
    await record("consume-120",{productionWorkId:workOpen.value.work.productionWorkId,productionAttemptId:attempt.productionAttemptId,materialId:f.material,requirementId:brandedId<"OrderLineMaterialRequirementId">(f.requirement),quantity:"120",unit:"each",kind:"consumed"});
    const waste=await record("waste-10",{productionWorkId:workOpen.value.work.productionWorkId,productionAttemptId:attempt.productionAttemptId,materialId:f.material,requirementId:brandedId<"OrderLineMaterialRequirementId">(f.requirement),quantity:"10",unit:"each",kind:"waste"});
    const projection=await consumption.read(context(f.org,f.user,request("projection")),workOpen.value.work.productionWorkId);assertOk(projection.ok,"P7C projection failed");const grommets=projection.value.comparison.find(row=>row.materialId===f.material)!;assert.deepEqual({expected:grommets.expectedQuantity,consumed:grommets.consumedQuantity,waste:grommets.wasteQuantity,total:grommets.totalPhysicalUsageQuantity,variance:grommets.varianceQuantity},{expected:"200",consumed:"200",waste:"10",total:"210",variance:"10"},"P7C expected-vs-actual projection diverged");
    // The two initial facts are deliberately independent partial events; use
    // a correction only for the separate waste entry, never a destructive edit.
    const correction=await record("reverse-waste",{productionWorkId:workOpen.value.work.productionWorkId,productionAttemptId:attempt.productionAttemptId,materialId:f.material,requirementId:brandedId<"OrderLineMaterialRequirementId">(f.requirement),quantity:"10",unit:"each",kind:"correction",correctsConsumptionId:waste.consumptionId}); assertOk(correction.correctsConsumptionId===waste.consumptionId,"P7C correction lost original linkage");
    const corrected=await consumption.read(context(f.org,f.user,request("corrected-projection")),workOpen.value.work.productionWorkId);assertOk(corrected.ok,"P7C corrected projection failed");const correctedGrommets=corrected.value.comparison.find(row=>row.materialId===f.material)!;assert.deepEqual({consumed:correctedGrommets.consumedQuantity,waste:correctedGrommets.wasteQuantity,total:correctedGrommets.totalPhysicalUsageQuantity,variance:correctedGrommets.varianceQuantity},{consumed:"200",waste:"0",total:"200",variance:"0"},"P7C correction did not produce deterministic effective totals");
    const outputId=request("output");assertOk((await production.recordOutput(context(f.org,f.user,outputId),{businessRequestId:outputId,productionAttemptId:attempt.productionAttemptId,goodQuantityDelta:40})).ok,"P7C partial output failed");const completeId=request("complete");assertOk((await production.complete(context(f.org,f.user,completeId),{businessRequestId:completeId,productionAttemptId:attempt.productionAttemptId})).ok,"P7C initial completion failed");
    const reprintId=request("reprint");const reprint=await production.start(context(f.org,f.user,reprintId),{businessRequestId:reprintId,productionWorkId:workOpen.value.work.productionWorkId,stationKey:"roll",kind:"reprint"});assertOk(reprint.ok&&reprint.value.attempt,"P7C reprint did not preserve Production attempt history");const reprintFact=await record("reprint-use",{productionWorkId:workOpen.value.work.productionWorkId,productionAttemptId:reprint.value.attempt!.productionAttemptId,materialId:f.unplanned,quantity:"1",unit:"each",kind:"waste"});assert.equal(reprintFact.productionAttemptId,reprint.value.attempt!.productionAttemptId,"P7C reprint usage lost attempt attribution");
    const countBefore=Number((await c.query<{n:string}>("SELECT count(*)::text n FROM v2_production_material_consumptions WHERE organization_id=$1",[f.org])).rows[0]!.n);const failing=new ProductionMaterialConsumptionApplicationService(new PostgresProductionMaterialConsumptionTransactionRunner(pool,{afterConsumption:async()=>{throw Error("p7c rollback")}}));const rollbackId=request("rollback");const rolled=await failing.record(context(f.org,f.user,rollbackId),{businessRequestId:rollbackId,productionWorkId:workOpen.value.work.productionWorkId,productionAttemptId:reprint.value.attempt!.productionAttemptId,materialId:f.unplanned,quantity:"2",unit:"each",kind:"consumed"});assert.ok(!rolled.ok,"P7C injected failure recorded consumption");assert.equal(Number((await c.query<{n:string}>("SELECT count(*)::text n FROM v2_production_material_consumptions WHERE organization_id=$1",[f.org])).rows[0]!.n),countBefore,"P7C rollback left a partial material fact");
    await assert.rejects(c.query("UPDATE v2_production_material_consumptions SET quantity=1 WHERE organization_id=$1 AND id=$2",[f.org,first.consumptionId]),/immutable/i);await assert.rejects(c.query("DELETE FROM v2_production_material_consumptions WHERE organization_id=$1 AND id=$2",[f.org,first.consumptionId]),/immutable/i);
    const foreign=await consumption.record(context(f.other,f.user,"foreign"),{businessRequestId:"foreign",productionWorkId:workOpen.value.work.productionWorkId,productionAttemptId:attempt.productionAttemptId,materialId:f.material,quantity:"1",unit:"each",kind:"consumed"});assert.ok(!foreign.ok,"P7C crossed tenant boundary");
    const stockAfter=(await c.query<{id:string;stock_quantity:string}>("SELECT id,stock_quantity::text FROM materials WHERE organization_id=$1 ORDER BY id",[f.org])).rows;assert.deepEqual(stockAfter,stockBefore,"P7C mutated Material stock");
    console.log(JSON.stringify({work:workOpen.value.work.productionWorkId,initialAttempt:attempt.productionAttemptId,reprintAttempt:reprint.value.attempt!.productionAttemptId,facts:countBefore,stock:"unchanged",rollback:"clean"},null,2));console.log("[p7c] Immutable Production material consumption clone rehearsal passed.");
  } finally {c.release();}} finally {await pool.end();}
};
void main().catch((error:unknown)=>{console.error(`[p7c] ${error instanceof Error?error.stack??error.message:String(error)}`);process.exitCode=1;});
