import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { Pool } from "pg";
import { requireV2M0CloneDatabaseUrl } from "../infrastructure/persistence/cloneSafety.js";
import { PostgresProductDraftOptionsReader, PostgresProductVersionTransactionRunner } from "../infrastructure/products/postgresProductVersionLifecycle.js";
import { PostgresProductsCompatibilityReader } from "../infrastructure/compatibility/postgresProductsRead.js";
import { ProductVersionLifecycleApplicationService, type ProductDraftOption } from "../src/modules/products/productVersionLifecycle.js";
import type { OperationContext } from "../src/application/operation.js";
import { brandedId } from "../src/modules/shared/commercialValues.js";

const cloneHost="ep-nameless-mud-aedtoak5-pooler.c-2.us-east-2.aws.neon.tech";
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const canonical=(value:unknown):string=>value===null||typeof value!=="object"?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonical).join(",")}]`:`{${Object.keys(value as Record<string,unknown>).sort().map(key=>`${JSON.stringify(key)}:${canonical((value as Record<string,unknown>)[key])}`).join(",")}}`;
const hash=(value:unknown)=>createHash("sha256").update(canonical(value)).digest("hex");
const request=(label:string)=>`p4-options-${label}-${randomUUID()}`;
const context=(organizationId:string,userId:string,id:string,caps:readonly any[]=["product.edit"]):OperationContext=>({organizationId,operationId:id,businessRequest:{id,payloadFingerprint:id},principal:{kind:"staff",organizationId,userId,authority:{membershipId:`p4-${organizationId}`,capabilities:caps}}});
const optionIds=(tree:unknown)=>{const source=record(tree),nodes=record(source.nodes),roots=Array.isArray(source.rootNodeIds)?source.rootNodeIds:[];return roots.flatMap(id=>{const node=record(nodes[String(id)]),input=record(node.input);return node.kind==="question"&&typeof node.id==="string"&&["boolean","select","multiselect","number","text","textarea"].includes(String(input.type))?[node.id]:[];});};
const outsideOptions=(tree:unknown)=>{const clone=structuredClone(record(tree)),ids=new Set(optionIds(clone)),nodes=record(clone.nodes);for(const id of ids)delete nodes[id];clone.nodes=nodes;clone.rootNodeIds=(Array.isArray(clone.rootNodeIds)?clone.rootNodeIds:[]).filter(id=>!ids.has(String(id)));return clone;};
const exactReference=(value:unknown,needles:ReadonlySet<string>):boolean=>typeof value==="string"?needles.has(value):Array.isArray(value)?value.some(item=>exactReference(item,needles)):value&&typeof value==="object"?Object.values(value as Record<string,unknown>).some(item=>exactReference(item,needles)):false;
const optionReference=(tree:unknown,id:string)=>{const source=structuredClone(record(tree)),nodes=record(source.nodes),node=record(nodes[id]),input=record(node.input);delete nodes[id];source.nodes=nodes;source.rootNodeIds=(Array.isArray(source.rootNodeIds)?source.rootNodeIds:[]).filter(root=>root!==id);return exactReference(source,new Set([id,typeof input.selectionKey==="string"?input.selectionKey:typeof node.key==="string"?node.key:""]));};
const choiceReference=(tree:unknown,id:string,value:string)=>{const source=structuredClone(record(tree)),node=record(record(source.nodes)[id]);node.choices=(Array.isArray(node.choices)?node.choices:[]).filter(choice=>record(choice).value!==value);record(source.nodes)[id]=node;return exactReference(source,new Set([value]));};
type Candidate={organizationId:string;productId:string;name:string;activeId:string;activePointer:string;activeTree:unknown;draftId:string;draftUpdatedAt:Date;draftTree:unknown};
const candidates=async(pool:Pool)=> (await pool.query<Candidate>(`SELECT p.organization_id AS "organizationId",p.id AS "productId",p.name,a.id AS "activeId",p.pbv2_active_tree_version_id AS "activePointer",a.tree_json AS "activeTree",d.id AS "draftId",d.updated_at AS "draftUpdatedAt",d.tree_json AS "draftTree" FROM products p JOIN pbv2_tree_versions a ON a.id=p.pbv2_active_tree_version_id AND a.organization_id=p.organization_id AND a.product_id=p.id AND a.status='ACTIVE' JOIN pbv2_tree_versions d ON d.organization_id=p.organization_id AND d.product_id=p.id AND d.status='DRAFT' WHERE p.is_active=TRUE ORDER BY d.updated_at,p.id LIMIT 100`)).rows;
const commercialReferences=async(pool:Pool,organizationId:string,productId:string)=>pool.query<{quotes:string;orders:string}>(`SELECT (SELECT count(*)::text FROM v2_sales_document_lines l JOIN v2_sales_documents d ON d.id=l.document_id AND d.organization_id=l.organization_id WHERE l.organization_id=$1 AND l.product_id=$2 AND d.document_kind='quote') quotes,(SELECT count(*)::text FROM v2_sales_document_lines l JOIN v2_sales_documents d ON d.id=l.document_id AND d.organization_id=l.organization_id WHERE l.organization_id=$1 AND l.product_id=$2 AND d.document_kind='order') orders`,[organizationId,productId]);
const rawDraft=async(pool:Pool,c:Candidate)=> (await pool.query<{tree_json:unknown;updated_at:Date}>("SELECT tree_json,updated_at FROM pbv2_tree_versions WHERE organization_id=$1 AND product_id=$2 AND id=$3 AND status='DRAFT'",[c.organizationId,c.productId,c.draftId])).rows[0]!;

async function main(){
  const url=requireV2M0CloneDatabaseUrl(),parsed=new URL(url);assert.equal(parsed.hostname,cloneHost,"P4 rehearsal refuses a database other than the authorized DEV clone.");assert.equal(parsed.pathname.replace(/^\//u,""),"neondb","P4 rehearsal refuses a database other than neondb.");
  const pool=new Pool({connectionString:url,max:4});
  try{
    await pool.query("SELECT 1");
    const reader=new PostgresProductDraftOptionsReader(pool),service=new ProductVersionLifecycleApplicationService(new PostgresProductVersionTransactionRunner(pool)),sales=new PostgresProductsCompatibilityReader(pool);
    const actor=(await pool.query<{id:string}>("SELECT id FROM users ORDER BY id LIMIT 1")).rows[0]?.id;assert(actor,"The authorized clone needs a Staff user.");
    const all=await candidates(pool);const candidate=all.find(item=>optionIds(item.draftTree).length>0&&optionIds(item.draftTree).some(id=>optionReference(item.draftTree,id)||Array.isArray(record(record(item.draftTree).nodes)[id]&&record(record(item.draftTree).nodes)[id].choices)&&record(record(item.draftTree).nodes)[id].choices.some(choice=>typeof record(choice).value==="string"&&choiceReference(item.draftTree,id,String(record(choice).value)))));
    assert(candidate,"The authorized clone needs a current Draft with a supported option and a pre-existing cross-reference for P4 safety rehearsal.");
    const initial=await reader.read(candidate.organizationId,candidate.productId);assert(initial&&initial.options.length,"Draft Options read failed.");
    const beforeTree=await rawDraft(pool,candidate),before={activeHash:hash(candidate.activeTree),activePointer:candidate.activePointer,product:(await pool.query("SELECT name,category,description,measurement_mode,workflow_intent,requires_proof_approval,requires_production_job,pbv2_active_tree_version_id FROM products WHERE organization_id=$1 AND id=$2",[candidate.organizationId,candidate.productId])).rows[0],outsideHash:hash(outsideOptions(beforeTree.tree_json)),general:record(record(beforeTree.tree_json).meta).general,commercial:(await commercialReferences(pool,candidate.organizationId,candidate.productId)).rows[0]!};
    const original=initial.options,first=original[0]!;const labelId=request("label");const labeled=await service.updateDraftOptions(context(candidate.organizationId,actor,labelId),{productId:candidate.productId,draftVersionId:initial.draftVersionId,expectedDraftUpdatedAt:initial.draftUpdatedAt,businessRequestId:labelId,options:original.map(option=>option.optionId===first.optionId?{...option,label:`${option.label} Draft`.slice(0,160)}:option)});assert(labeled.ok,"Safe option label edit failed.");assert.equal(labeled.value.options[0]!.optionId,first.optionId,"Label edit changed option identity.");
    const replay=await service.updateDraftOptions(context(candidate.organizationId,actor,labelId),{productId:candidate.productId,draftVersionId:initial.draftVersionId,expectedDraftUpdatedAt:initial.draftUpdatedAt,businessRequestId:labelId,options:original.map(option=>option.optionId===first.optionId?{...option,label:`${option.label} Draft`.slice(0,160)}:option)});assert.deepEqual(replay,labeled,"Exact request did not replay.");
    const addText:ProductDraftOption={optionId:`new:${randomUUID()}`,label:"P4 temporary text",inputType:"text",required:false,defaultValue:"",choices:[],canRemove:true};const addTextId=request("add-option");const textAdded=await service.updateDraftOptions(context(candidate.organizationId,actor,addTextId),{productId:candidate.productId,draftVersionId:labeled.value.draftVersionId,expectedDraftUpdatedAt:labeled.value.draftUpdatedAt,businessRequestId:addTextId,options:[...labeled.value.options,addText]});assert(textAdded.ok,"Add option failed.");const persistedText=textAdded.value.options.at(-1)!;assert(!persistedText.optionId.startsWith("new:"),"Server did not generate option identity.");
    const addChoice:ProductDraftOption={optionId:`new:${randomUUID()}`,label:"P4 temporary select",inputType:"select",required:false,defaultValue:"",choices:[{choiceValue:"",label:"First choice"}],canRemove:true};const choiceId=request("add-choice");const choiceAdded=await service.updateDraftOptions(context(candidate.organizationId,actor,choiceId),{productId:candidate.productId,draftVersionId:textAdded.value.draftVersionId,expectedDraftUpdatedAt:textAdded.value.draftUpdatedAt,businessRequestId:choiceId,options:[...textAdded.value.options,addChoice]});assert(choiceAdded.ok,"Add choice option failed.");const persistedChoice=choiceAdded.value.options.at(-1)!;assert.equal(persistedChoice.choices.length,1,"Choice was not persisted.");assert.notEqual(persistedChoice.choices[0]!.choiceValue,"","Server did not generate choice identity.");
    const changedChoice={...persistedChoice,choices:[{...persistedChoice.choices[0]!,label:"Renamed choice"},{choiceValue:"",label:"Second choice"}],defaultValue:persistedChoice.choices[0]!.choiceValue};const choiceEditId=request("edit-reorder-choice");const choiceEdited=await service.updateDraftOptions(context(candidate.organizationId,actor,choiceEditId),{productId:candidate.productId,draftVersionId:choiceAdded.value.draftVersionId,expectedDraftUpdatedAt:choiceAdded.value.draftUpdatedAt,businessRequestId:choiceEditId,options:choiceAdded.value.options.map(option=>option.optionId===persistedChoice.optionId?changedChoice:option)});assert(choiceEdited.ok,"Choice edit failed.");const afterChoice=choiceEdited.value.options.find(option=>option.optionId===persistedChoice.optionId)!;assert.equal(afterChoice.choices[0]!.choiceValue,persistedChoice.choices[0]!.choiceValue,"Choice label edit changed identity.");
    const reordered={...afterChoice,choices:[...afterChoice.choices].reverse()};const reorderId=request("reorder-choice");const reorderedResult=await service.updateDraftOptions(context(candidate.organizationId,actor,reorderId),{productId:candidate.productId,draftVersionId:choiceEdited.value.draftVersionId,expectedDraftUpdatedAt:choiceEdited.value.draftUpdatedAt,businessRequestId:reorderId,options:choiceEdited.value.options.map(option=>option.optionId===afterChoice.optionId?reordered:option)});assert(reorderedResult.ok,"Choice reorder failed.");
    const invalidId=request("invalid-default"),invalid=await service.updateDraftOptions(context(candidate.organizationId,actor,invalidId),{productId:candidate.productId,draftVersionId:reorderedResult.value.draftVersionId,expectedDraftUpdatedAt:reorderedResult.value.draftUpdatedAt,businessRequestId:invalidId,options:reorderedResult.value.options.map(option=>option.optionId===afterChoice.optionId?{...option,defaultValue:"not-a-choice"}:option)});assert(!invalid.ok&&invalid.error.code==="VALIDATION_ERROR","Invalid default was accepted.");
    const staleId=request("stale"),stale=await service.updateDraftOptions(context(candidate.organizationId,actor,staleId),{productId:candidate.productId,draftVersionId:initial.draftVersionId,expectedDraftUpdatedAt:initial.draftUpdatedAt,businessRequestId:staleId,options:initial.options});assert(!stale.ok&&stale.error.code==="STALE_STATE","Stale write was accepted.");
    const referencedTree=(await rawDraft(pool,candidate)).tree_json;const referencedOption=optionIds(referencedTree).find(id=>optionReference(referencedTree,id));const referencedChoice=optionIds(referencedTree).flatMap(id=>{const choices=record(record(referencedTree).nodes)[id]&&record(record(referencedTree).nodes)[id].choices;return Array.isArray(choices)?choices.map(choice=>String(record(choice).value)).filter(value=>choiceReference(referencedTree,id,value)).map(value=>({id,value})):[];})[0];const current=await reader.read(candidate.organizationId,candidate.productId);assert(current,"Draft disappeared.");const rejectId=request("referenced-removal");const rejected=await service.updateDraftOptions(context(candidate.organizationId,actor,rejectId),{productId:candidate.productId,draftVersionId:current.draftVersionId,expectedDraftUpdatedAt:current.draftUpdatedAt,businessRequestId:rejectId,options:referencedOption?current.options.filter(option=>option.optionId!==referencedOption):current.options.map(option=>option.optionId===referencedChoice!.id?{...option,choices:option.choices.filter(choice=>choice.choiceValue!==referencedChoice!.value)}:option)});assert(!rejected.ok&&rejected.error.code==="CONFLICT","Referenced removal was accepted.");
    const removeId=request("safe-removal");const removable=await service.updateDraftOptions(context(candidate.organizationId,actor,removeId),{productId:candidate.productId,draftVersionId:current.draftVersionId,expectedDraftUpdatedAt:current.draftUpdatedAt,businessRequestId:removeId,options:current.options.filter(option=>option.optionId!==persistedText.optionId&&option.optionId!==persistedChoice.optionId)});assert(removable.ok,"Safe temporary option removal failed.");
    const forbiddenId=request("forbidden"),forbidden=await service.updateDraftOptions(context(candidate.organizationId,actor,forbiddenId,["product.view"]),{productId:candidate.productId,draftVersionId:removable.value.draftVersionId,expectedDraftUpdatedAt:removable.value.draftUpdatedAt,businessRequestId:forbiddenId,options:removable.value.options});assert(!forbidden.ok&&forbidden.error.code==="FORBIDDEN","product.view edited Draft Options.");
    const other=(await pool.query<{id:string}>("SELECT id FROM organizations WHERE id<>$1 LIMIT 1",[candidate.organizationId])).rows[0]?.id;assert(other,"The authorized clone needs a second organization.");assert.equal(await reader.read(other,candidate.productId),null,"Foreign tenant read Draft Options.");const foreignId=request("foreign"),foreign=await service.updateDraftOptions(context(other,actor,foreignId),{productId:candidate.productId,draftVersionId:removable.value.draftVersionId,expectedDraftUpdatedAt:removable.value.draftUpdatedAt,businessRequestId:foreignId,options:removable.value.options});assert(!foreign.ok&&foreign.error.code==="NOT_FOUND","Foreign tenant edited Draft Options.");
    const afterTree=await rawDraft(pool,candidate),afterProduct=(await pool.query("SELECT name,category,description,measurement_mode,workflow_intent,requires_proof_approval,requires_production_job,pbv2_active_tree_version_id FROM products WHERE organization_id=$1 AND id=$2",[candidate.organizationId,candidate.productId])).rows[0];const active=(await pool.query<{tree_json:unknown}>("SELECT tree_json FROM pbv2_tree_versions WHERE id=$1 AND organization_id=$2",[candidate.activeId,candidate.organizationId])).rows[0]!;assert.deepEqual(afterProduct,before.product,"Options save changed the Product row.");assert.equal(afterProduct.pbv2_active_tree_version_id,before.activePointer,"Options save changed the Active pointer.");assert.equal(hash(active.tree_json),before.activeHash,"Options save changed the Active tree.");assert.equal(hash(outsideOptions(afterTree.tree_json)),before.outsideHash,"Options save changed unrelated Draft sections.");assert.deepEqual(record(record(afterTree.tree_json).meta).general,before.general,"Options save changed Draft General metadata.");assert.deepEqual((await commercialReferences(pool,candidate.organizationId,candidate.productId)).rows[0],before.commercial,"Options save changed Quote or Order references.");assert.equal((await sales.getActivePricingConfiguration(brandedId<"OrganizationId">(candidate.organizationId),brandedId<"ProductId">(candidate.productId)))?.id,candidate.activeId,"Normal Product resolution did not remain Active-only.");
    console.log(JSON.stringify({product:candidate.name,activeVersion:candidate.activeId,draftVersion:candidate.draftId,quoteLines:before.commercial.quotes,orderLines:before.commercial.orders},null,2));console.log("[p4] Product Draft Options clone rehearsal passed.");
  }finally{await pool.end();}
}
void main().catch(error=>{console.error(`[p4] ${error instanceof Error?error.message:String(error)}`);process.exitCode=1;});
