import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { apiFetch } from '@/lib/queryClient';
import { useRecordCustomerInvoicePayment } from '@/hooks/useInvoices';
import { useToast } from '@/hooks/use-toast';

export function MultiInvoicePaymentDialog({ open, onOpenChange, invoiceIds, onSuccess }: { open: boolean; onOpenChange(value: boolean): void; invoiceIds: string[]; onSuccess(): void }) {
  const [amount, setAmount] = useState(''); const [method, setMethod] = useState('check'); const [mode, setMode] = useState<'oldest_first' | 'proportional' | 'custom'>('oldest_first'); const [preview, setPreview] = useState<any>(null); const [custom, setCustom] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const { toast } = useToast(); const mutation = useRecordCustomerInvoicePayment();
  const amountCents = Math.round(Number(amount || 0) * 100);
  useEffect(() => { if (!open || !invoiceIds.length) return; setError(''); const allocationMode = mode === 'custom' ? 'oldest_first' : mode; void apiFetch('/api/invoices/customer-payment/preview', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ invoiceIds, amountCents: Math.max(1, amountCents || 1), allocationMode }) }).then(async (res) => { const body = await res.json().catch(() => ({})); if (res.ok) setPreview(body.data); else setError(body.error || 'Selected invoices cannot share one customer payment.'); }); }, [open, invoiceIds.join(','), amountCents, mode]);
  const submit = () => { if (!preview || amountCents <= 0) return setError('Enter a positive payment amount.'); const customAllocations = mode === 'custom' ? (preview.invoices || []).map((x: any) => ({ invoiceId: x.invoiceId, amountCents: Math.round(Number(custom[x.invoiceId] || 0) * 100) })) : undefined; if (!window.confirm(`Record one ${method} payment of $${(amountCents / 100).toFixed(2)} across ${invoiceIds.length} selected invoices?`)) return; mutation.mutate({ invoiceIds, amountCents, allocationMode: mode, customAllocations, method, expectedRemainingCents: Object.fromEntries((preview.invoices || []).map((x: any) => [x.invoiceId, x.remainingCents])) }, { onSuccess: () => { toast({ title: 'Customer payment recorded' }); onSuccess(); onOpenChange(false); }, onError: (e: Error) => setError(e.message) }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add Customer Payment</DialogTitle><DialogDescription>Apply one payment to {invoiceIds.length} selected invoices. All invoices must belong to the same customer.</DialogDescription></DialogHeader><div className="grid gap-3"><div><Label htmlFor="customer-payment-amount">Payment amount</Label><Input id="customer-payment-amount" type="number" min="0.01" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></div><div><Label>Payment method</Label><Select value={method} onValueChange={setMethod}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['cash','check','wire','bank_transfer','ach','other'].map((x) => <SelectItem key={x} value={x}>{x.replace('_', ' ')}</SelectItem>)}</SelectContent></Select></div><div><Label>Allocation</Label><Select value={mode} onValueChange={(value: any) => setMode(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="oldest_first">Oldest invoice first</SelectItem><SelectItem value="proportional">Proportional</SelectItem><SelectItem value="custom">Custom allocation</SelectItem></SelectContent></Select></div>{mode === 'custom' && preview ? <div className="grid gap-2">{preview.invoices.map((invoice: any) => <div className="flex items-center gap-2" key={invoice.invoiceId}><span className="flex-1 text-sm">Invoice {invoice.invoiceNumber}</span><Input className="w-28" type="number" min="0" step="0.01" aria-label={`Allocation for invoice ${invoice.invoiceNumber}`} value={custom[invoice.invoiceId] || ''} onChange={(e) => setCustom((old) => ({ ...old, [invoice.invoiceId]: e.target.value }))} /></div>)}</div> : null}{preview ? <p className="text-sm text-muted-foreground">Selected outstanding: ${(preview.totalOutstandingCents / 100).toFixed(2)}</p> : null}{error ? <p className="text-sm text-destructive">{error}</p> : null}<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={mutation.isPending || !preview} onClick={submit}>{mutation.isPending ? 'Recording…' : 'Record Payment'}</Button></div></div></DialogContent></Dialog>;
}
