import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { apiFetch } from '@/lib/queryClient';
import { useRecordCustomerInvoicePayment } from '@/hooks/useInvoices';
import { useToast } from '@/hooks/use-toast';
import { parseTenderedAmountCents, resolveCustomerPaymentAmounts } from '@/lib/customerPaymentTender';

export function MultiInvoicePaymentDialog({ open, onOpenChange, invoiceIds, onSuccess }: { open: boolean; onOpenChange(value: boolean): void; invoiceIds: string[]; onSuccess(): void }) {
  const [amount, setAmount] = useState(''); const [method, setMethod] = useState('check'); const [mode, setMode] = useState<'oldest_first' | 'proportional' | 'custom'>('oldest_first'); const [preview, setPreview] = useState<any>(null); const [custom, setCustom] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const { toast } = useToast(); const mutation = useRecordCustomerInvoicePayment();
  const tenderedAmountCents = parseTenderedAmountCents(amount);
  const amounts = resolveCustomerPaymentAmounts(Number(preview?.totalOutstandingCents || 0), tenderedAmountCents ?? 0);
  const appliedAmountCents = amounts.appliedAmountCents;
  const previewAmountCents = Math.max(1, preview ? appliedAmountCents : 1);
  const validTenderedAmount = tenderedAmountCents != null && tenderedAmountCents > 0;
  useEffect(() => { if (open) { setPreview(null); setCustom({}); setError(''); } }, [open, invoiceIds.join(',')]);
  useEffect(() => { if (!open || !invoiceIds.length) return; let cancelled = false; setError(''); const allocationMode = mode === 'custom' ? 'oldest_first' : mode; void apiFetch('/api/invoices/customer-payment/preview', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ invoiceIds, amountCents: previewAmountCents, allocationMode }) }).then(async (res) => { const body = await res.json().catch(() => ({})); if (cancelled) return; if (res.ok) setPreview(body.data); else setError(body.error || 'Selected invoices cannot share one customer payment.'); }); return () => { cancelled = true; }; }, [open, invoiceIds.join(','), previewAmountCents, mode]);
  const submit = () => { if (!preview || !validTenderedAmount || appliedAmountCents <= 0) return setError('Enter a positive payment amount.'); const customAllocations = mode === 'custom' ? (preview.invoices || []).map((x: any) => ({ invoiceId: x.invoiceId, amountCents: parseTenderedAmountCents(custom[x.invoiceId] || '') ?? 0 })) : undefined; const changeMessage = amounts.changeDueCents ? ` Change due: $${(amounts.changeDueCents / 100).toFixed(2)}.` : ''; if (!window.confirm(`Record one ${method} payment of $${(appliedAmountCents / 100).toFixed(2)} across ${invoiceIds.length} selected invoices?${changeMessage}`)) return; mutation.mutate({ invoiceIds, amountCents: appliedAmountCents, allocationMode: mode, customAllocations, method, expectedRemainingCents: Object.fromEntries((preview.invoices || []).map((x: any) => [x.invoiceId, x.remainingCents])) }, { onSuccess: () => { toast({ title: 'Customer payment recorded', description: amounts.changeDueCents ? `$${(amounts.changeDueCents / 100).toFixed(2)} change due.` : undefined }); onSuccess(); onOpenChange(false); }, onError: (e: Error) => setError(e.message) }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add Customer Payment</DialogTitle><DialogDescription>Apply one payment to {invoiceIds.length} selected invoices. All invoices must belong to the same customer.</DialogDescription></DialogHeader><div className="grid gap-3"><div className="rounded-md border border-border bg-muted/30 p-3"><p className="text-sm text-muted-foreground">Selected invoices total</p><p className="text-2xl font-semibold">{preview ? `$${(preview.totalOutstandingCents / 100).toFixed(2)}` : 'Loading…'}</p></div><div><Label htmlFor="customer-payment-amount">Payment received</Label><Input id="customer-payment-amount" inputMode="decimal" type="text" placeholder="0.00" value={amount} onChange={(e) => setAmount(e.target.value)} /></div>{preview && validTenderedAmount ? <div className="rounded-md border border-border px-3 py-2"><span className="text-sm text-muted-foreground">{amounts.changeDueCents > 0 ? 'Change due' : 'Remaining balance'}</span><p className="font-semibold">${((amounts.changeDueCents > 0 ? amounts.changeDueCents : amounts.remainingBalanceCents) / 100).toFixed(2)}</p></div> : null}<div><Label>Payment method</Label><Select value={method} onValueChange={setMethod}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['cash','check','wire','bank_transfer','ach','other'].map((x) => <SelectItem key={x} value={x}>{x.replace('_', ' ')}</SelectItem>)}</SelectContent></Select></div><div><Label>Allocation</Label><Select value={mode} onValueChange={(value: any) => setMode(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="oldest_first">Oldest invoice first</SelectItem><SelectItem value="proportional">Proportional</SelectItem><SelectItem value="custom">Custom allocation</SelectItem></SelectContent></Select></div>{mode === 'custom' && preview ? <div className="grid gap-2">{preview.invoices.map((invoice: any) => <div className="flex items-center gap-2" key={invoice.invoiceId}><span className="flex-1 text-sm">Invoice {invoice.invoiceNumber}</span><Input className="w-28" type="text" inputMode="decimal" placeholder="0.00" aria-label={`Allocation for invoice ${invoice.invoiceNumber}`} value={custom[invoice.invoiceId] || ''} onChange={(e) => setCustom((old) => ({ ...old, [invoice.invoiceId]: e.target.value }))} /></div>)}</div> : null}{error ? <p className="text-sm text-destructive">{error}</p> : null}<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={mutation.isPending || !preview || !validTenderedAmount || appliedAmountCents <= 0} onClick={submit}>{mutation.isPending ? 'Recording…' : 'Record Payment'}</Button></div></div></DialogContent></Dialog>;
}
