import { createHash, randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";

import { evaluateOptionTreeV2 } from "../../../server/services/optionTreeV2Evaluator";
import { V2PocError } from "../shared/errors";

export type PgFailurePoint = "after_request_claim" | "after_order_insert" | "after_line_insert" | "after_invoice_insert" | "after_invoice_line_insert" | "before_commit";
export type PgCreateOrderCommand = { organizationId: string; customerId: string; requestId: string; lines: Array<{ productId: string; quantity: number; selections?: Record<string, { value: string | number | boolean }>; widthIn?: number; heightIn?: number }> };
export type PgOrderLine = { id: string; productId: string; quantity: number; unitPriceCents: number; lineSubtotalCents: number; taxCents: number; totalCents: number; taxable: boolean; pricingSnapshot: Record<string, unknown> };
export type PgOrderResult = { order: { id: string; organizationId: string; customerId: string; subtotalCents: number; taxCents: number; totalCents: number; taxRateBasisPoints: number; lines: PgOrderLine[] }; invoice: { id: string; orderId: string; subtotalCents: number; taxCents: number; totalCents: number; lines: PgOrderLine[] }; idempotentReplay: boolean };

const operation = "create_order.v2_poc";
const idempotencyDdl = `CREATE TABLE IF NOT EXISTS v2_poc_order_create_requests (id varchar(64) PRIMARY KEY, organization_id varchar NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, actor_user_id varchar NOT NULL REFERENCES users(id) ON DELETE CASCADE, operation varchar(64) NOT NULL, request_id varchar(160) NOT NULL, request_hash varchar(64) NOT NULL, order_id varchar REFERENCES orders(id) ON DELETE SET NULL, invoice_id varchar REFERENCES invoices(id) ON DELETE SET NULL, result_json jsonb, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, CONSTRAINT v2_poc_order_create_requests_scope_unique UNIQUE (organization_id, actor_user_id, operation, request_id))`;
const centsToDecimal = (cents: number) => (cents / 100).toFixed(2);
const asCents = (value: unknown) => Math.round(Number(value) * 100);
const required = <T>(value: T | undefined | null, message: string): T => { if (value == null) throw new V2PocError("NOT_FOUND", message); return value; };
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value as Record<string, unknown>).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`; return JSON.stringify(value); }
function requestHash(command: PgCreateOrderCommand): string { return createHash("sha256").update(canonical({ version: 1, operation, organizationId: command.organizationId, customerId: command.customerId, lines: command.lines })).digest("hex"); }
function fail(point: PgFailurePoint | undefined, expected: PgFailurePoint): void { if (point === expected) throw new V2PocError("INJECTED_FAILURE", `Injected PostgreSQL failure at ${expected}.`); }

type PgConfiguration = { id: string; organizationId: string; name: string; activeTreeVersionId: string; treeJson: any; taxable: boolean; measurementMode: "quantity_only" | "dimensions_required"; basePerPieceCents: number | null; basePerSqftCents: number | null; minimumChargeCents: number };

class PgAuthorizationRepository {
  async resolve(client: PoolClient, actorId: string, organizationId: string) { const result = await client.query(`select uo.role,o.default_tax_rate,o.tax_enabled from user_organizations uo join organizations o on o.id=uo.organization_id where uo.user_id=$1 and uo.organization_id=$2 and o.delete_state='active' and o.is_archived=false`, [actorId, organizationId]); const row = result.rows[0] as { role: string; default_tax_rate: string; tax_enabled: boolean } | undefined; if (!row) throw new V2PocError("FORBIDDEN", "Actor is not an active member of the requested organization."); if (!["owner", "admin", "manager"].includes(row.role)) throw new V2PocError("FORBIDDEN", "Actor lacks the organization-scoped orders:create capability."); return { taxEnabled: row.tax_enabled, defaultTaxRateBasisPoints: Math.round(Number(row.default_tax_rate) * 10_000) }; }
}
class PgCustomerRepository {
  async get(client: PoolClient, organizationId: string, customerId: string) { const result = await client.query(`select id,is_tax_exempt,tax_rate_override,payment_terms from customers where id=$1 and organization_id=$2 and is_active=true`, [customerId, organizationId]); const row = result.rows[0] as { id: string; is_tax_exempt: boolean; tax_rate_override: string | null; payment_terms: string | null } | undefined; return row ? { id: row.id, taxExempt: row.is_tax_exempt, taxRateBasisPoints: row.tax_rate_override === null ? null : Math.round(Number(row.tax_rate_override) * 10_000), paymentTerms: row.payment_terms ?? "due_on_receipt" } : null; }
}
class PgCatalogRepository {
  async get(client: PoolClient, organizationId: string, productId: string): Promise<PgConfiguration | null> { const result = await client.query(`select p.id,p.organization_id,p.name,p.is_taxable,p.measurement_mode,t.id as tree_id,t.tree_json from products p join pbv2_tree_versions t on t.id=p.pbv2_active_tree_version_id and t.organization_id=p.organization_id and t.product_id=p.id and t.status='ACTIVE' where p.id=$1 and p.organization_id=$2 and p.is_active=true`, [productId, organizationId]); const row = result.rows[0] as any; if (!row) return null; const base = row.tree_json?.meta?.pricingV2?.base ?? {}; return { id: row.id, organizationId: row.organization_id, name: row.name, taxable: row.is_taxable, measurementMode: row.measurement_mode, activeTreeVersionId: row.tree_id, treeJson: row.tree_json, basePerPieceCents: Number.isFinite(Number(base.perPieceCents)) ? Number(base.perPieceCents) : null, basePerSqftCents: Number.isFinite(Number(base.perSqftCents)) ? Number(base.perSqftCents) : null, minimumChargeCents: Number.isFinite(Number(base.minimumChargeCents)) ? Number(base.minimumChargeCents) : 0 }; }
}
class PgPricingAdapter {
  price(configuration: PgConfiguration, input: PgCreateOrderCommand["lines"][number]): Omit<PgOrderLine, "id" | "taxCents" | "totalCents"> { if (!Number.isInteger(input.quantity) || input.quantity <= 0) throw new V2PocError("VALIDATION", "Line quantity must be a positive integer."); if (configuration.measurementMode === "dimensions_required" && (!input.widthIn || !input.heightIn)) throw new V2PocError("VALIDATION", "Dimensions are required for this product."); const squareFeet = ((input.widthIn ?? 0) * (input.heightIn ?? 0) / 144) * input.quantity; const baseCents = configuration.basePerPieceCents !== null ? configuration.basePerPieceCents * input.quantity : configuration.basePerSqftCents !== null ? Math.round(configuration.basePerSqftCents * squareFeet) : (() => { throw new V2PocError("VALIDATION", "Product has no supported PBV2 base-price configuration."); })(); const evaluated = evaluateOptionTreeV2({ tree: configuration.treeJson, selections: { schemaVersion: 2, selected: input.selections ?? {} }, width: input.widthIn ?? 0, height: input.heightIn ?? 0, quantity: input.quantity, basePrice: baseCents / 100 }); const optionCents = Math.round(evaluated.optionsPrice * 100); const subtotal = Math.max(baseCents + optionCents, configuration.minimumChargeCents); return { productId: configuration.id, quantity: input.quantity, unitPriceCents: Math.floor(subtotal / input.quantity), lineSubtotalCents: subtotal, taxable: configuration.taxable, pricingSnapshot: { pricingSystem: "pbv2", treeVersionId: configuration.activeTreeVersionId, selections: input.selections ?? {}, baseCents, optionCents, totalCents: subtotal, selectedOptions: evaluated.selectedOptions, visibleNodeIds: evaluated.visibleNodeIds } }; }
}
class PgOrderRepository {
  async allocateNumber(client: PoolClient, organizationId: string, type: "order" | "invoice") { const name = type === "order" ? "next_order_number" : "next_invoice_number"; const prefixName = type === "order" ? "order_number_prefix" : "invoice_number_prefix"; const defaultPrefix = type === "order" ? "ORD-" : "INV-"; const next = await client.query(`insert into global_variables (id,organization_id,name,value,description,category,is_active,created_at,updated_at) values (gen_random_uuid(),$1,$2,'1001',$3,'numbering',true,now(),now()) on conflict (organization_id,name) do update set value=(case when global_variables.value ~ '^[0-9]+$' then global_variables.value::integer else 1000 end + 1)::text,updated_at=now() returning (value::integer-1) as number_core`, [organizationId, name, `V2 POC ${type} number sequence`]); const core = Number(next.rows[0].number_core); const prefix = await client.query(`select value from global_variables where organization_id=$1 and name=$2`, [organizationId, prefixName]); return { core, display: `${String(prefix.rows[0]?.value ?? defaultPrefix).replace(/[^A-Za-z0-9_-]/g, "")}${core}` }; }
  async insertOrder(client: PoolClient, input: { organizationId: string; actorId: string; customerId: string; taxRateBps: number; lines: PgOrderLine[] }, hooks: { afterOrderInsert?: () => void; afterLineInsert?: () => void } = {}) { const numbering = await this.allocateNumber(client, input.organizationId, "order"); const subtotal = input.lines.reduce((sum, line) => sum + line.lineSubtotalCents, 0); const tax = input.lines.reduce((sum, line) => sum + line.taxCents, 0); const taxableSubtotal = input.lines.filter((line) => line.taxable).reduce((sum, line) => sum + line.lineSubtotalCents, 0); const total = subtotal + tax; const id = `v2poc-order-${randomUUID()}`; await client.query(`insert into orders (id,organization_id,order_number,display_number,number_core,customer_id,status,state,priority,fulfillment_status,subtotal,tax,tax_rate,tax_amount,taxable_subtotal,total,discount,created_by_user_id) values ($1,$2,$3,$4,$5,$6,'new','open','normal','pending',$7,$8,$9,$8,$10,$11,0,$12)`, [id,input.organizationId,String(numbering.core),numbering.display,numbering.core,input.customerId,centsToDecimal(subtotal),centsToDecimal(tax),(input.taxRateBps / 10_000).toFixed(4),centsToDecimal(taxableSubtotal),centsToDecimal(total),input.actorId]); hooks.afterOrderInsert?.(); const lines: PgOrderLine[] = []; for (const [index,line] of input.lines.entries()) { const lineId=`v2poc-line-${randomUUID()}`; await client.query(`insert into order_line_items (id,order_id,product_id,product_type,description,quantity,unit_price,total_price,status,option_selections_json,selected_options,pbv2_tree_version_id,pbv2_snapshot_json,priced_at,tax_amount,is_taxable_snapshot,sort_order) values ($1,$2,$3,'wide_roll',$4,$5,$6,$7,'new',$8,$9,$10,$11,now(),$12,$13,$14)`, [lineId,id,line.productId,`V2 POC priced line ${index+1}`,line.quantity,centsToDecimal(line.unitPriceCents),centsToDecimal(line.lineSubtotalCents),JSON.stringify((line.pricingSnapshot as any).selections),JSON.stringify((line.pricingSnapshot as any).selectedOptions ?? []),(line.pricingSnapshot as any).treeVersionId,JSON.stringify(line.pricingSnapshot),centsToDecimal(line.taxCents),line.taxable,index]); lines.push({...line,id:lineId}); } hooks.afterLineInsert?.(); return { id, organizationId: input.organizationId, customerId: input.customerId, subtotalCents: subtotal, taxCents: tax, totalCents: total, taxRateBasisPoints: input.taxRateBps, lines }; }
  async get(client: PoolClient, organizationId: string, orderId: string) { const header = await client.query(`select id,organization_id,customer_id,subtotal,tax_amount,total,tax_rate from orders where id=$1 and organization_id=$2`, [orderId,organizationId]); const order=header.rows[0] as any; if(!order) return null; const lines = await client.query(`select l.id,l.product_id,l.quantity,l.unit_price,l.total_price,l.tax_amount,l.is_taxable_snapshot,l.pbv2_snapshot_json from order_line_items l join orders o on o.id=l.order_id where l.order_id=$1 and o.organization_id=$2 order by l.sort_order,l.id`,[orderId,organizationId]); return { id:order.id,organizationId:order.organization_id,customerId:order.customer_id,subtotalCents:asCents(order.subtotal),taxCents:asCents(order.tax_amount),totalCents:asCents(order.total),taxRateBasisPoints:Math.round(Number(order.tax_rate ?? 0)*10_000),lines:lines.rows.map((line:any)=>({id:line.id,productId:line.product_id,quantity:line.quantity,unitPriceCents:asCents(line.unit_price),lineSubtotalCents:asCents(line.total_price),taxCents:asCents(line.tax_amount),totalCents:asCents(line.total_price)+asCents(line.tax_amount),taxable:line.is_taxable_snapshot,pricingSnapshot:line.pbv2_snapshot_json}))}; }
}
class PgBillingRepository {
  constructor(private readonly numbering: PgOrderRepository) {}
  async insertDraft(client: PoolClient, order: PgOrderResult["order"], actorId: string, terms: string, hooks: { afterInvoiceInsert?: () => void; afterInvoiceLineInsert?: () => void } = {}) { const number = await this.numbering.allocateNumber(client, order.organizationId, "invoice"); const id=`v2poc-invoice-${randomUUID()}`; await client.query(`insert into invoices (id,organization_id,invoice_number,display_number,number_core,order_id,customer_id,status,terms,subtotal,tax,total,subtotal_cents,tax_cents,shipping_cents,total_cents,amount_paid,balance_due,created_by_user_id) values ($1,$2,$3,$4,$5,$6,$7,'draft',$8,$9,$10,$11,$12,$13,0,$14,0,$11,$15)`, [id,order.organizationId,number.core,number.display,number.core,order.id,order.customerId,terms,centsToDecimal(order.subtotalCents),centsToDecimal(order.taxCents),centsToDecimal(order.totalCents),order.subtotalCents,order.taxCents,order.totalCents,actorId]); hooks.afterInvoiceInsert?.(); for (const [index,line] of order.lines.entries()) await client.query(`insert into invoice_line_items (id,invoice_id,order_line_item_id,product_id,product_type,description,quantity,unit_price,total_price,unit_price_cents,line_total_cents,sort_order,option_selections_json,selected_options) values ($1,$2,$3,$4,'wide_roll',$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[`v2poc-invoice-line-${randomUUID()}`,id,line.id,line.productId,`V2 POC priced line ${index+1}`,line.quantity,centsToDecimal(line.unitPriceCents),centsToDecimal(line.lineSubtotalCents),line.unitPriceCents,line.lineSubtotalCents,index,JSON.stringify((line.pricingSnapshot as any).selections),JSON.stringify((line.pricingSnapshot as any).selectedOptions??[])]); hooks.afterInvoiceLineInsert?.(); return { id,orderId:order.id,subtotalCents:order.subtotalCents,taxCents:order.taxCents,totalCents:order.totalCents,lines:order.lines }; }
  async getForOrder(client: PoolClient, organizationId: string, orderId: string) { const invoice=await client.query(`select id,order_id,subtotal_cents,tax_cents,total_cents from invoices where organization_id=$1 and order_id=$2 and status='draft' order by created_at,id limit 2`,[organizationId,orderId]); if(invoice.rowCount && invoice.rowCount > 1) throw new V2PocError("VALIDATION","Multiple draft invoices exist for this order."); const row=invoice.rows[0] as any; if(!row)return null; const lines=await client.query(`select ili.id,ili.product_id,ili.quantity,ili.unit_price_cents,ili.line_total_cents,ili.option_selections_json,ili.selected_options,oli.tax_amount,oli.is_taxable_snapshot,oli.pbv2_snapshot_json from invoice_line_items ili join order_line_items oli on oli.id=ili.order_line_item_id where ili.invoice_id=$1 order by ili.sort_order,ili.id`,[row.id]); return {id:row.id,orderId:row.order_id,subtotalCents:row.subtotal_cents,taxCents:row.tax_cents,totalCents:row.total_cents,lines:lines.rows.map((line:any)=>({id:line.id,productId:line.product_id,quantity:line.quantity,unitPriceCents:line.unit_price_cents,lineSubtotalCents:line.line_total_cents,taxCents:asCents(line.tax_amount),totalCents:line.line_total_cents+asCents(line.tax_amount),taxable:line.is_taxable_snapshot,pricingSnapshot:{...(line.pbv2_snapshot_json??{}),selections:line.option_selections_json,selectedOptions:line.selected_options}}))}; }
}
class PgRequestRepository {
  async claim(client: PoolClient, actorId: string, command: PgCreateOrderCommand, hash: string) { const id=`v2poc-request-${randomUUID()}`; const result=await client.query(`insert into v2_poc_order_create_requests (id,organization_id,actor_user_id,operation,request_id,request_hash) values ($1,$2,$3,$4,$5,$6) on conflict (organization_id,actor_user_id,operation,request_id) do nothing returning id`,[id,command.organizationId,actorId,operation,command.requestId,hash]); if(result.rowCount)return null; const existing=await client.query(`select request_hash,order_id,invoice_id from v2_poc_order_create_requests where organization_id=$1 and actor_user_id=$2 and operation=$3 and request_id=$4`,[command.organizationId,actorId,operation,command.requestId]); return required(existing.rows[0],"Idempotency request disappeared.") as {request_hash:string;order_id:string|null;invoice_id:string|null}; }
  async complete(client: PoolClient, actorId:string, command:PgCreateOrderCommand, hash:string, result:PgOrderResult) { await client.query(`update v2_poc_order_create_requests set order_id=$1,invoice_id=$2,result_json=$3,completed_at=now() where organization_id=$4 and actor_user_id=$5 and operation=$6 and request_id=$7 and request_hash=$8`,[result.order.id,result.invoice.id,JSON.stringify({orderId:result.order.id,invoiceId:result.invoice.id}),command.organizationId,actorId,operation,command.requestId,hash]); }
}
export class PostgresCreateOrderApplication {
  private readonly authorization=new PgAuthorizationRepository(); private readonly customers=new PgCustomerRepository(); private readonly catalog=new PgCatalogRepository(); private readonly pricing=new PgPricingAdapter(); private readonly orders=new PgOrderRepository(); private readonly billing=new PgBillingRepository(this.orders); private readonly requests=new PgRequestRepository();
  constructor(private readonly pool: Pool) {}
  async installExperimentalSchema(): Promise<void> { await this.pool.query(idempotencyDdl); }
  async execute(actorId: string, command: PgCreateOrderCommand, failurePoint?: PgFailurePoint): Promise<PgOrderResult> { const client=await this.pool.connect(); try { await client.query("begin"); const auth=await this.authorization.resolve(client,actorId,command.organizationId); if(!command.requestId.trim()||!command.lines.length)throw new V2PocError("VALIDATION","A request ID and at least one line are required."); const hash=requestHash(command); const existing=await this.requests.claim(client,actorId,command,hash); if(existing){if(existing.request_hash!==hash)throw new V2PocError("IDEMPOTENCY_CONFLICT","Request ID was already used with different content."); const order=await this.orders.get(client,command.organizationId,required(existing.order_id,"Idempotency request is incomplete.")); const invoice=await this.billing.getForOrder(client,command.organizationId,required(existing.order_id,"Idempotency request is incomplete.")); const replay={order:required(order,"Order not found."),invoice:required(invoice,"Invoice not found."),idempotentReplay:true}; await client.query("commit"); return replay;} fail(failurePoint,"after_request_claim"); const customer=required(await this.customers.get(client,command.organizationId,command.customerId),"Customer not found."); const taxRateBps=!auth.taxEnabled||customer.taxExempt?0:(customer.taxRateBasisPoints??auth.defaultTaxRateBasisPoints); const priced:PgOrderLine[]=[]; for(const line of command.lines){const configuration=required(await this.catalog.get(client,command.organizationId,line.productId),"Product pricing configuration not found."); const base=this.pricing.price(configuration,line); const taxCents=base.taxable?Math.round(base.lineSubtotalCents*taxRateBps/10_000):0; priced.push({...base,id:"",taxCents,totalCents:base.lineSubtotalCents+taxCents});} const order=await this.orders.insertOrder(client,{organizationId:command.organizationId,actorId,customerId:customer.id,taxRateBps,lines:priced},{afterOrderInsert:()=>fail(failurePoint,"after_order_insert"),afterLineInsert:()=>fail(failurePoint,"after_line_insert")}); const invoice=await this.billing.insertDraft(client,order,actorId,customer.paymentTerms,{afterInvoiceInsert:()=>fail(failurePoint,"after_invoice_insert"),afterInvoiceLineInsert:()=>fail(failurePoint,"after_invoice_line_insert")}); const result={order,invoice,idempotentReplay:false}; await this.requests.complete(client,actorId,command,hash,result); fail(failurePoint,"before_commit"); await client.query("commit"); return result;} catch(error){try{await client.query("rollback");}catch{} throw error;} finally{client.release();} }
  async readOrder(actorId:string,organizationId:string,orderId:string){const client=await this.pool.connect();try{await this.authorization.resolve(client,actorId,organizationId);const order=await this.orders.get(client,organizationId,orderId);if(!order)throw new V2PocError("NOT_FOUND","Order not found.");const invoice=await this.billing.getForOrder(client,organizationId,orderId);return{order,invoice:required(invoice,"Invoice not found.")};}finally{client.release();}}
  async previewProduct(actorId:string,organizationId:string,line:PgCreateOrderCommand["lines"][number]){const client=await this.pool.connect();try{await this.authorization.resolve(client,actorId,organizationId);const configuration=required(await this.catalog.get(client,organizationId,line.productId),"Product pricing configuration not found.");return this.pricing.price(configuration,line);}finally{client.release();}}
}
