import { createHash, randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { V2PocError } from "../shared/errors";

const cents = (value: unknown) => Math.round(Number(value ?? 0) * 100);
const decimal = (value: number) => (value / 100).toFixed(2);
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const ddl = `CREATE TABLE IF NOT EXISTS v2_poc_financial_requests (id varchar(96) PRIMARY KEY,organization_id varchar NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,actor_user_id varchar NOT NULL REFERENCES users(id) ON DELETE CASCADE,operation varchar(64) NOT NULL,request_id varchar(160) NOT NULL,request_hash varchar(64) NOT NULL,result_json jsonb,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(organization_id,actor_user_id,operation,request_id)); CREATE TABLE IF NOT EXISTS v2_poc_financial_refunds (id varchar(96) PRIMARY KEY,organization_id varchar NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,invoice_id varchar NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,payment_id varchar NOT NULL REFERENCES payments(id) ON DELETE RESTRICT,amount_cents integer NOT NULL CHECK(amount_cents>0),method varchar(32) NOT NULL,provider varchar(32),provider_refund_id varchar(160),status varchar(20) NOT NULL DEFAULT 'SUCCEEDED',actor_user_id varchar REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,provider,provider_refund_id)); CREATE TABLE IF NOT EXISTS v2_poc_financial_reconciliations (id varchar(96) PRIMARY KEY,organization_id varchar NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,invoice_id varchar NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,operation varchar(64) NOT NULL,external_key varchar(160) NOT NULL,status varchar(20) NOT NULL DEFAULT 'PENDING',attempts integer NOT NULL DEFAULT 0,payload_json jsonb NOT NULL,result_json jsonb,last_error text,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(organization_id,operation,external_key));`;

export type FinancialInvoice = { id: string; subtotalCents: number; taxCents: number; totalCents: number; netPaidCents: number; refundedCents: number; balanceDueCents: number; status: string; metadata: { poNumber: string | null; notesPublic: string | null } };
type Payment = { id: string; amountCents: number; provider: string; status: string };
type Request = { organizationId: string; invoiceId: string; requestId: string };

export class PostgresFinancialLifecycleApplication {
  constructor(private readonly pool: Pool) {}
  async installExperimentalSchema() { await this.pool.query(ddl); }
  private async authorized(client: PoolClient, actor: string, org: string, capability: string) {
    const r = await client.query("select role from user_organizations where user_id=$1 and organization_id=$2", [actor, org]);
    if (!r.rows[0] || !["owner", "admin"].includes(r.rows[0].role)) throw new V2PocError("FORBIDDEN", `Actor lacks ${capability}.`);
  }
  private async claim(client: PoolClient, actor: string, operation: string, request: Request, body: unknown) {
    const requestHash = hash(body); const id = `v2poc-fin-request-${randomUUID()}`;
    const inserted = await client.query("insert into v2_poc_financial_requests (id,organization_id,actor_user_id,operation,request_id,request_hash) values ($1,$2,$3,$4,$5,$6) on conflict do nothing returning id", [id,request.organizationId,actor,operation,request.requestId,requestHash]);
    if (inserted.rowCount) return null;
    const existing = await client.query("select request_hash,result_json from v2_poc_financial_requests where organization_id=$1 and actor_user_id=$2 and operation=$3 and request_id=$4", [request.organizationId,actor,operation,request.requestId]);
    if (existing.rows[0]?.request_hash !== requestHash) throw new V2PocError("IDEMPOTENCY_CONFLICT", "Request key has conflicting financial content.");
    if (!existing.rows[0]?.result_json) throw new V2PocError("RETRY_PENDING", "Financial request is pending reconciliation.");
    return existing.rows[0].result_json;
  }
  private async complete(client: PoolClient, actor: string, operation: string, request: Request, body: unknown, result: unknown) { await client.query("update v2_poc_financial_requests set result_json=$1,completed_at=now() where organization_id=$2 and actor_user_id=$3 and operation=$4 and request_id=$5 and request_hash=$6", [JSON.stringify(result),request.organizationId,actor,operation,request.requestId,hash(body)]); }
  private async load(client: PoolClient, org: string, invoiceId: string): Promise<{ invoice: any; payments: Payment[]; refunds: number }> {
    const invoice = (await client.query("select id,status,subtotal_cents,tax_cents,total_cents,customer_po_number,notes_public from invoices where id=$1 and organization_id=$2 for update", [invoiceId, org])).rows[0];
    if (!invoice) throw new V2PocError("NOT_FOUND", "Invoice not found.");
    const payments = (await client.query("select id,amount_cents,provider,status from payments where invoice_id=$1 and organization_id=$2 and status in ('succeeded','captured')", [invoiceId,org])).rows.map((r) => ({ id:r.id, amountCents:Number(r.amount_cents), provider:r.provider ?? "manual", status:r.status }));
    const refunds = Number((await client.query("select coalesce(sum(amount_cents),0)::int as amount from v2_poc_financial_refunds where invoice_id=$1 and organization_id=$2 and status='SUCCEEDED'", [invoiceId,org])).rows[0].amount);
    return { invoice, payments, refunds };
  }
  private async project(client: PoolClient, org: string, invoiceId: string): Promise<FinancialInvoice> {
    const state = await this.load(client,org,invoiceId); const paid = state.payments.reduce((sum,p) => sum+p.amountCents,0)-state.refunds;
    const total=Number(state.invoice.total_cents), net=Math.max(0,paid), due=Math.max(0,total-net); const status=due===0&&net>0?"paid":net>0?"partially_paid":state.invoice.status==="draft"?"draft":"sent";
    await client.query("update invoices set amount_paid=$1,balance_due=$2,status=$3,updated_at=now() where id=$4 and organization_id=$5",[decimal(net),decimal(due),status,invoiceId,org]);
    return { id:invoiceId,subtotalCents:Number(state.invoice.subtotal_cents),taxCents:Number(state.invoice.tax_cents),totalCents:total,netPaidCents:net,refundedCents:state.refunds,balanceDueCents:due,status,metadata:{poNumber:state.invoice.customer_po_number,notesPublic:state.invoice.notes_public} };
  }
  private async transaction<T>(actor:string, capability:string, request:Request, operation:string, body:unknown, work:(client:PoolClient)=>Promise<T>):Promise<T|any> { const client=await this.pool.connect(); try { await client.query("begin"); await this.authorized(client,actor,request.organizationId,capability); await client.query("select pg_advisory_xact_lock(hashtext($1))",[`${request.organizationId}:${request.invoiceId}`]); const replay=await this.claim(client,actor,operation,request,body); if(replay){await client.query("commit");return replay;} const result=await work(client); await this.complete(client,actor,operation,request,body,result); await client.query("commit");return result; } catch(error) { await client.query("rollback"); throw error; } finally { client.release(); } }
  async correctEditableInvoice(actor:string, input: Request & { lines:Array<{id:string;quantity:number;unitPriceCents:number}>; taxCents:number }) { return this.transaction(actor,"finance:correct",input,"correct",input,async(client)=>{ const state=await this.load(client,input.organizationId,input.invoiceId); if(state.payments.reduce((s,p)=>s+p.amountCents,0)-state.refunds>=Number(state.invoice.total_cents)) throw new V2PocError("LOCKED","Paid invoice financials are locked."); for(const line of input.lines){if(!Number.isInteger(line.quantity)||line.quantity<=0||!Number.isInteger(line.unitPriceCents)||line.unitPriceCents<0)throw new V2PocError("VALIDATION","Invalid financial line."); const changed=await client.query("update invoice_line_items set quantity=$1,unit_price=$2,total_price=$3,unit_price_cents=$4,line_total_cents=$5,updated_at=now() where id=$6 and invoice_id=$7",[line.quantity,decimal(line.unitPriceCents),decimal(line.quantity*line.unitPriceCents),line.unitPriceCents,line.quantity*line.unitPriceCents,line.id,input.invoiceId]); if(!changed.rowCount)throw new V2PocError("NOT_FOUND","Invoice line not found.");} const sums=(await client.query("select coalesce(sum(line_total_cents),0)::int as subtotal from invoice_line_items where invoice_id=$1",[input.invoiceId])).rows[0]; const subtotal=Number(sums.subtotal),total=subtotal+input.taxCents; await client.query("update invoices set subtotal=$1,tax=$2,total=$3,subtotal_cents=$4,tax_cents=$5,total_cents=$6,modified_after_billing=true,updated_at=now() where id=$7 and organization_id=$8",[decimal(subtotal),decimal(input.taxCents),decimal(total),subtotal,input.taxCents,total,input.invoiceId,input.organizationId]); return this.project(client,input.organizationId,input.invoiceId); }); }
  async updateMetadata(actor:string,input:Request & {poNumber?:string|null;notesPublic?:string|null}) { return this.transaction(actor,"finance:metadata",input,"metadata",input,async(client)=>{await this.load(client,input.organizationId,input.invoiceId); await client.query("update invoices set customer_po_number=coalesce($1,customer_po_number),notes_public=coalesce($2,notes_public),updated_at=now() where id=$3 and organization_id=$4",[input.poNumber??null,input.notesPublic??null,input.invoiceId,input.organizationId]);return this.project(client,input.organizationId,input.invoiceId);}); }
  async recordPayment(actor:string,input:Request & {amountCents:number;method:string;provider?:string;providerEventId?:string}) { return this.transaction(actor,"finance:payment",input,"payment",input,async(client)=>{const state=await this.load(client,input.organizationId,input.invoiceId); const paid=state.payments.reduce((s,p)=>s+p.amountCents,0)-state.refunds; if(!Number.isInteger(input.amountCents)||input.amountCents<=0||input.amountCents>Number(state.invoice.total_cents)-paid)throw new V2PocError("VALIDATION","Payment exceeds remaining balance."); const id=`v2poc-payment-${randomUUID()}`; await client.query("insert into payments (id,organization_id,invoice_id,amount,amount_cents,method,provider,status,provider_transaction_id,provider_idempotency_key,paid_at,succeeded_at) values ($1,$2,$3,$4,$5,$6,$7,'succeeded',$8,$9,now(),now())",[id,input.organizationId,input.invoiceId,decimal(input.amountCents),input.amountCents,input.method,input.provider??"manual",input.providerEventId??null,input.requestId]); return { paymentId:id,invoice:await this.project(client,input.organizationId,input.invoiceId) };}); }
  async refundPayment(actor:string,input:Request & {paymentId:string;amountCents:number;method:string;providerRefundId?:string}) { return this.transaction(actor,"finance:refund",input,"refund",input,async(client)=>{const state=await this.load(client,input.organizationId,input.invoiceId); const payment=state.payments.find((p)=>p.id===input.paymentId); if(!payment)throw new V2PocError("NOT_FOUND","Payment not refundable."); const prior=Number((await client.query("select coalesce(sum(amount_cents),0)::int as amount from v2_poc_financial_refunds where organization_id=$1 and payment_id=$2 and status='SUCCEEDED'",[input.organizationId,input.paymentId])).rows[0].amount); if(!Number.isInteger(input.amountCents)||input.amountCents<=0||input.amountCents>payment.amountCents-prior)throw new V2PocError("VALIDATION","Refund exceeds refundable payment amount."); const id=`v2poc-refund-${randomUUID()}`; await client.query("insert into v2_poc_financial_refunds (id,organization_id,invoice_id,payment_id,amount_cents,method,provider,provider_refund_id,actor_user_id) values ($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,input.organizationId,input.invoiceId,input.paymentId,input.amountCents,input.method,payment.provider,input.providerRefundId??null,actor]); return {refundId:id,invoice:await this.project(client,input.organizationId,input.invoiceId)};}); }
  async read(actor:string,org:string,invoiceId:string){const client=await this.pool.connect();try{await this.authorized(client,actor,org,"finance:view");await client.query("begin");const result=await this.project(client,org,invoiceId);const payments=(await client.query("select id,amount_cents,provider,status from payments where organization_id=$1 and invoice_id=$2",[org,invoiceId])).rows;const refunds=(await client.query("select id,payment_id,amount_cents,method from v2_poc_financial_refunds where organization_id=$1 and invoice_id=$2 order by created_at",[org,invoiceId])).rows;await client.query("commit");return{invoice:result,payments,refunds};}catch(error){try{await client.query("rollback");}catch{}throw error;}finally{client.release();}}
  async customerExposure(actor:string,org:string,customerId:string){const client=await this.pool.connect();try{await this.authorized(client,actor,org,"finance:view");const r=await client.query("select coalesce(sum(case when status in ('draft','finalized','billed','sent','partially_paid','overdue') then round(balance_due*100)::int else 0 end),0)::int as exposure from invoices where organization_id=$1 and customer_id=$2",[org,customerId]);return{exposureCents:Number(r.rows[0].exposure)};}finally{client.release();}}
}
