import { describe, expect, it } from "@jest/globals";
import { assistantProductionCommandAllowlist, createProductionAssistantCommandRegistry } from "../services/assistant/execution/commandRegistry";
import { createFulfillmentOperationCommandDefinition, createFulfillmentOperationExecutionCommand, fulfillmentOperationInputSchema } from "../services/assistant/execution/fulfillmentOperationsCommands";
import { fulfillmentOperationCommandNames } from "../services/assistant/fulfillmentOperationsService";
const fingerprint = "e".repeat(64);
const service: any = { revalidateProposal: async () => ({ valid: true, proposal: { fulfillmentIntakeSessionId: "fulfillment_1", proposalFingerprint: fingerprint, summary: "Create draft shipment.", sourceLinks: [{ label: "Open order", href: "/orders/order_1" }] } }), executeConfirmed: async () => ({ sourceLinks: [], summary: "Done." }) };
describe("assistant fulfillment operations commands", () => {
  it("completes the reviewed twenty-two-command registry with five fulfillment commands", () => { expect(assistantProductionCommandAllowlist).toHaveLength(22); const registry = createProductionAssistantCommandRegistry(...fulfillmentOperationCommandNames.map((name) => createFulfillmentOperationCommandDefinition(name, service))); expect(registry.list().map((item) => item.name).sort()).toEqual([...fulfillmentOperationCommandNames].sort()); expect(registry.list().every((item) => item.confirmationRequired && item.idempotencyPolicy === "server_generated_with_request_hash")).toBe(true); });
  it("uses opaque persisted proposals and stale revalidation", async () => { expect(() => fulfillmentOperationInputSchema.parse({ fulfillmentIntakeSessionId: "fulfillment_1", proposalFingerprint: fingerprint, orderId: "untrusted" })).toThrow(); const command = createFulfillmentOperationExecutionCommand("fulfillment.mark_shipped", service); const built = await command.buildPreview({ scope: { organizationId: "org_1", userId: "user_1", permissions: ["assistant.fulfillment.mark_shipped"], environment: "test" }, context: { version: "v1", route: "/fulfillment", entity: null, selection: [], filters: {}, capturedAt: new Date().toISOString() }, arguments: { fulfillmentIntakeSessionId: "fulfillment_1", proposalFingerprint: fingerprint } }); expect(built.preview.sideEffects.join(" ")).toContain("No production, invoice, payment"); service.revalidateProposal = async () => ({ valid: false, code: "FULFILLMENT_PROPOSAL_STALE", summary: "Changed" }); await expect(command.revalidate({ plan: { id: "plan_1", organizationId: "org_1", userId: "user_1", conversationId: "conversation_1", commandName: "fulfillment.mark_shipped", commandVersion: "v1", normalizedAction: "fulfillment.mark_shipped", sanitizedArguments: built.arguments, contextHash: "hash", permissionSnapshot: [], environment: "test", preview: built.preview, affectedRecords: built.preview.affectedRecords, riskLevel: "high", status: "awaiting_confirmation", version: 1, idempotencyKey: "aicmd_00000000-0000-0000-0000-000000000000", correlationId: "corr_1", expiresAt: new Date(), createdAt: new Date(), updatedAt: new Date() }, scope: { organizationId: "org_1", userId: "user_1", permissions: [], environment: "test" } })).resolves.toEqual({ valid: false, code: "FULFILLMENT_PROPOSAL_STALE", summary: "Changed" }); });
});
