import { buildCanonicalComplexProductTree, complexProductMatrixCellKey, parseTwoDimensionalPricingMatrix, specificationFingerprint, validateComplexProductSpecification, type ComplexProductSpecification } from "../services/assistant/complexProductSpecification";
import { extractProductOptionPricingMatrix, resolveProductOptionPricingMatrix } from "../../shared/productOptionPricingMatrix";
import { resolvePricingV2BaseRates } from "../../shared/pbv2/pricingAdapter";
import { configurableProductConfirmationDto, configurableProductResultDto } from "../services/assistant/complexProductPresentation";

const source = `| Thickness | Single-sided | Double-sided |
| --- | --- | --- |
| 3mm | $4.50 | $5.75 |
| 6mm | $6.25 | $7.75 |
| 12mm | $9.75 | $11.50 |
| 18mm | $12.50 | $14.75 |`;
function spec(): ComplexProductSpecification { const pricing = parseTwoDimensionalPricingMatrix(source, "thickness", "printed_sides"); return { kind: "configurable_product", name: "AI VALIDATION 19K PVC", category: "Rigid Substrates", description: "Disposable", taxable: true, requiresDimensions: true, materialForm: "sheet", sheet: { widthIn: 48, heightIn: 96, allowRotation: true }, route: "Flatbed", minimumChargeCents: 2500, optionGroups: [{ proposalKey: "thickness", name: "Thickness", required: true, selectionMode: "single", values: ["3mm", "6mm", "12mm", "18mm"].map((value) => ({ value, label: value })) }, { proposalKey: "printed_sides", name: "Printed Sides", required: true, selectionMode: "single", values: ["Single-sided", "Double-sided"].map((value) => ({ value, label: value })) }], pricing, review: { assumptions: [], warnings: [], blockers: [], unsupportedRelationships: ["Contour Cutting and White Ink require reviewed canonical templates."] } }; }

describe("complex product specification", () => {
  it("parses the PVC markdown matrix into integer cents in displayed order with JSONB-safe cell keys", () => { const matrix = parseTwoDimensionalPricingMatrix(source, "thickness", "printed_sides"); expect(matrix.rowValues).toEqual(["3mm", "6mm", "12mm", "18mm"]); expect(matrix.columnValues).toEqual(["Single-sided", "Double-sided"]); expect(Object.values(matrix.cells)).toContain(450); expect(Object.values(matrix.cells)).toContain(1475); expect(Object.keys(matrix.cells)).toEqual(expect.arrayContaining([complexProductMatrixCellKey("3mm", "Single-sided")])); expect(Object.keys(matrix.cells).every((key) => !/[\u0000-\u001f]/.test(key))).toBe(true); });
  it("rejects incomplete and malformed matrix values", () => { expect(() => parseTwoDimensionalPricingMatrix("Thickness,Single-sided,Double-sided\n3mm,4.50", "thickness", "sides")).toThrow("Every matrix row"); expect(() => parseTwoDimensionalPricingMatrix("Thickness,Single-sided\n3mm,-1", "thickness", "sides")).toThrow("Invalid non-negative"); });
  it("builds one canonical PBV2 DRAFT tree that the matrix resolver understands", () => { const value = spec(); expect(validateComplexProductSpecification(value)).toEqual([]); const tree = buildCanonicalComplexProductTree(value); expect(tree.status).toBe("DRAFT"); const matrix = extractProductOptionPricingMatrix(tree)!; expect(resolveProductOptionPricingMatrix({ pricingMatrix: matrix, selections: { thickness: "3mm", printed_sides: "Double-sided" } }).variables.base_price).toBe(5.75); expect(resolveProductOptionPricingMatrix({ pricingMatrix: matrix, selections: { thickness: "18mm", printed_sides: "Double-sided" } }).variables.base_price).toBe(14.75); });
  it.each([["3mm", "Single-sided", 4.5], ["3mm", "Double-sided", 5.75], ["12mm", "Single-sided", 9.75], ["18mm", "Double-sided", 14.75]])("resolves the canonical DRAFT price for %s + %s", (thickness, printedSides, expected) => { const tree = buildCanonicalComplexProductTree(spec()); const matrix = extractProductOptionPricingMatrix(tree)!; const result = resolveProductOptionPricingMatrix({ pricingMatrix: matrix, selections: { thickness, printed_sides: printedSides } }); expect(result.errors).toHaveLength(0); expect(result.variables.base_price).toBe(expected); });
  it("preserves the $25 minimum in the canonical PBV2 base-rate resolver", () => { const tree = buildCanonicalComplexProductTree(spec()); const rates = resolvePricingV2BaseRates(tree, { thickness: "3mm", printed_sides: "Single-sided" }, { widthIn: 1, heightIn: 1, quantity: 1 }); expect(rates.minimumChargeCents).toBe(2500); });
  it("fails completeness validation and fingerprints exact specifications", () => { const value = spec(); delete value.pricing.cells[complexProductMatrixCellKey("3mm", "Single-sided")]; expect(validateComplexProductSpecification(value)).toContain("Missing or invalid matrix cell: 3mm × Single-sided."); const complete = spec(); expect(specificationFingerprint(complete)).not.toBe(specificationFingerprint({ ...complete, minimumChargeCents: 2600 })); });
  it("preserves complete typed confirmation and result DTOs", () => { const value = spec(); const confirmation = configurableProductConfirmationDto({ proposalId: "proposal", fingerprint: specificationFingerprint(value), specification: value }); expect(confirmation.goEligible).toBe(true); expect(confirmation.matrix.cells[complexProductMatrixCellKey("3mm", "Double-sided")]).toBe(575); expect(confirmation.product.minimumChargeCents).toBe(2500); expect(configurableProductResultDto({ proposalId: "proposal", specification: value, productId: "product", pbv2TreeVersionId: "tree", reused: false })).toMatchObject({ optionGroupCount: 2, optionValueCount: 6, matrixCellCount: 8, inactive: true, pbv2Status: "DRAFT" }); });
  it("builds a quantity-only per-piece matrix without production configuration", () => {
    const value = spec(); value.name = "DEV Test Yard Signs 073126"; value.requiresDimensions = false; value.sheet = undefined; value.route = undefined; value.materialForm = undefined;
    value.pricing = { ...value.pricing, kind: "two_dimensional_per_piece", rowValues: ["3mm", "6mm"], columnValues: ["Single-sided", "Double-sided"], cells: { [complexProductMatrixCellKey("3mm", "Single-sided")]: 1200, [complexProductMatrixCellKey("3mm", "Double-sided")]: 1800, [complexProductMatrixCellKey("6mm", "Single-sided")]: 1600, [complexProductMatrixCellKey("6mm", "Double-sided")]: 2200 } };
    value.optionGroups[0].values = ["3mm", "6mm"].map((item) => ({ value: item, label: item }));
    const tree = buildCanonicalComplexProductTree(value); const matrix = extractProductOptionPricingMatrix(tree)!;
    expect(validateComplexProductSpecification(value)).toEqual([]);
    expect((tree.meta as any).pricingV2.optionMatrixPricingUnit).toBe("per_piece"); expect((tree.meta as any).pricingProfileKey).toBe("qty_only");
    expect((tree.meta as any).productIntake.sheet).toBeUndefined(); expect((tree.meta as any).productIntake.draftRouting).toBeUndefined();
    expect(resolveProductOptionPricingMatrix({ pricingMatrix: matrix, selections: { thickness: "6mm", printed_sides: "Double-sided" } }).variables.base_price).toBe(22);
    expect(configurableProductConfirmationDto({ proposalId: "proposal", fingerprint: specificationFingerprint(value), specification: value }).product).toMatchObject({ name: "DEV Test Yard Signs 073126", requiresDimensions: false });
  });
});
